### ISSUE TITLE
What is the right place to ask questions about semantic-release?

### ISSUE THREAD

**Issue by limonte** [semantic-release/semantic-release#1014]
When I hit the "New issue" button, these options are available:

![image](https://user-images.githubusercontent.com/6059356/49369892-361e9c00-f6fb-11e8-800f-742bb2b088e0.png)

There's no "question" option so I guess GitHub isn't the right place for asking questions. What is the right place then?

For now, I posted my question to StackOverflow: https://stackoverflow.com/q/53592360 and marked it with the `semantic-release` tag.

Thanks in advance and sorry about asking a question on GitHub :)

**Comment by pvdlg** [comment]
There is a section in the README of the project: [Get Help](https://github.com/semantic-release/semantic-release#get-help)
