### ISSUE TITLE
Monitor vulnerable dependencies

### ISSUE THREAD

**Issue by honzajavorek** [semantic-release/semantic-release#1015]
## Current behavior

There is no dependency monitoring.

## Expected behavior

The Semantic Release team is aware of all vulnerabilities it brings to the dependency chain and is able to mitigate them timely.

## Details

For projects using Semantic Release, it is a crucial piece of infrastructure. It handles secret keys, GitHub tokens, npm tokens, it publishes new versions to thousands or more people. For that reason, given the current [event-stream issue](https://github.com/dominictarr/event-stream/issues/116), it would be nice if the Semantic Release was aware of its own dependencies.

I use [Snyk](https://snyk.io/) to monitor dependencies on my GitHub projects and it's pretty effortless (and it's free for Open Source). There's also `npm audit`, but I'm not sure on how to make it SaaS, sending out notifications if something bad happens.

Currently when I check my project which uses the latest stable Semantic Release, I can see following:

```
✗ Low severity vulnerability found in deep-extend
  Description: Prototype Pollution
  Info: https://snyk.io/vuln/npm:deep-extend:20180409
  Introduced through: semantic-release@15.12.4
  From: semantic-release@15.12.4 > @semantic-release/npm@5.1.1 > registry-auth-token@3.3.2 > rc@1.1.7 > deep-extend@0.4.2

✗ Medium severity vulnerability found in mem
  Description: Denial of Service (DoS)
  Info: https://snyk.io/vuln/npm:mem:20180117
  Introduced through: semantic-release@15.12.4
  From: semantic-release@15.12.4 > @semantic-release/npm@5.1.1 > npm@6.4.1 > libnpx@10.2.0 > yargs@11.0.0 > os-locale@2.1.0 > mem@1.1.0

✗ Medium severity vulnerability found in chownr
  Description: Time of Check Time of Use (TOCTOU)
  Info: https://snyk.io/vuln/npm:chownr:20180731
  Introduced through: semantic-release@15.12.4, babel-cli@6.26.0
  From: semantic-release@15.12.4 > @semantic-release/npm@5.1.1 > npm@6.4.1 > chownr@1.0.1
  From: semantic-release@15.12.4 > @semantic-release/npm@5.1.1 > npm@6.4.1 > tar@4.4.6 > chownr@1.0.1
  From: semantic-release@15.12.4 > @semantic-release/npm@5.1.1 > npm@6.4.1 > cacache@11.2.0 > chownr@1.0.1
  and 10 more...
```

Without Semantic Release cooperating on updating the underlying dependencies, I can do nothing about these issues.

**Comment by pvdlg** [comment]
We use [Greenkeeper](https://github.com/greenkeeperio/greenkeeper) to keep our dependencies up to date. So we always use the latest version for each of our dependencies. GitHub also [monitor vulnerabilities in dependencies](https://help.github.com/articles/about-security-alerts-for-vulnerable-dependencies/). So I don't see any reason to add something on top of that.

The 3 vulnerabilities you are mentioning are all in [npm](https://github.com/npm/cli) (as we have a dependency to npm through the `@semantic-release/npm` plugin). I guess there is some kind of irony in the fact that the only vulnerabilities found by `npm audit` are its own... 

Anyway there is nothing more we can do here. I'd suggest you to open an issue with npm so they would update their vulnerable dependencies.

**Comment by honzajavorek** [comment]
I see, makes sense. Thanks!
