### ISSUE TITLE
Support of more commit conventions

### ISSUE THREAD

**Issue by Berkmann18** [semantic-release/semantic-release#1017]
## New feature motivation

As of now, this tool **doesn't** work with projects with commit conventions such as ESLint's or jQuery's which renders this pretty much useless which is unfortunate.

## New feature description

Be more aware of other commits conventions such as ESLint, jQuery, Ember, ...
## New feature implementation

Add more patterns (relevant to the other popular commit conventions) to the commit reader.

**Comment by pvdlg** [comment]
Yes it **does**. That's indicated in the first paragraph of the README:
> By default **semantic-release** uses [Angular Commit Message Conventions](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#-git-commit-guidelines). The commit message format can be changed with the [`preset` or `config` options](docs/usage/configuration.md#options) of the [@semantic-release/commit-analyzer](https://github.com/semantic-release/commit-analyzer#options) and [@semantic-release/release-notes-generator](https://github.com/semantic-release/release-notes-generator#options) plugins.

Any existing  conventional-commits preset can be used or you can create your own.

**Comment by Berkmann18** [comment]
@pvdlg Ah okay, I missed that bit (apologies).
I've noticed this and was wondering both lines were meant to be there or if there's just some missing content in one of them.

> - Commits with tag 'New' will be associated with a `patch` release.
...
> - Commits with tag 'New' will be associated with a `minor` release (per [default release rules](https://github.com/semantic-release/commit-analyzer/blob/master/lib/default-release-rules.js)).

**Comment by pvdlg** [comment]
What do you think is missing?

**Comment by Berkmann18** [comment]
@pvdlg Well, judging by the example above that unordered list:
> ```{
>  "plugins": [
>    ["semantic-release/commit-analyzer", {
>      "preset": "eslint",
>      "releaseRules": [
>        {"tag": "Docs", "message":"/README/", "release": "patch"},
>        {"type": "New", "release": "patch"}
>      ]
>    }],
>    "@semantic-release/release-notes-generator"
>  ]
>}
>```

I thought the one about `patch` releases would be when the `releaseRules` would look out for commits that would follow one like this:
```
{"type": "New", "message": "...", "release": "patch"}
```
Where `message` would describe a new feature that would should be treated as a patch or something not worthy of a minor bump.

**Comment by pvdlg** [comment]
I'm sorry, I read your message multiple times, but I do not understand what you are saying.
Are you asking a question about the inner functionning of the plugin?
Or are you reporting a problem? Is yes what do you think the doc should be then?

**Comment by Berkmann18** [comment]
@pvdlg 
> - Commits with tag 'New' will be associated with a `patch` release.
...
> - Commits with tag 'New' will be associated with a `minor` release (per [default release rules]
Those lines seem to contradict each other and confusing and unless both lines are there on purpose, I feel like some info is missing.
