### ISSUE TITLE
npm version fails with conventional-changelog

### ISSUE THREAD

**Issue by Berkmann18** [semantic-release/semantic-release#1024]
## Current behaviour
When `semantic-release` runs on TravisCI (like [here](https://travis-ci.org/Berkmann18/TemplateJS/jobs/466415832)) it goes through the following set of commands:
```bash
> npm version 1.0.0 --no-git-tag-version
> npm run changelog && git add CHANGELOG.md # that's what npm version does on the repo
> conventional-changelog -p eslint -i CHANGELOG.md -s -r 0
sh: 1: conventional-changelog: not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! tempjs@1.0.0 changelog: `conventional-changelog -p eslint -i CHANGELOG.md -s -r 0`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the tempjs@1.0.0 changelog script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2018-12-11T09_33_18_162Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tempjs@1.0.0 version: `npm run changelog && git add CHANGELOG.md`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tempjs@1.0.0 version script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2018-12-11T09_33_18_178Z-debug.log
[9:33:18 AM] [semantic-release] › ✖  Failed step "prepare" of plugin "@semantic-release/npm"
[9:33:18 AM] [semantic-release] › ✖  An error occurred while running semantic-release: { Error: Command failed: npm version 1.0.0 --no-git-tag-version
sh: 1: conventional-changelog: not found
# ...
```

This happens regardless of whether `conventional-changelog` is a _devDependency_ or a _global package on TravisCI_.

## Expected behaviour
```bash
> npm version 1.0.0 --no-git-tag-version
> npm run changelog && git add CHANGELOG.md # that's what npm version does on the repo
> conventional-changelog -p eslint -i CHANGELOG.md -s -r 0
# creates a git tag v1.0.0 within a commit named "1.0.0"
```

## Environment

- **semantic-release** version: 15.12.4
- CI environment: TravisCI
- Plugins used: `@semantic-release/commit-analyzer`, `@semantic-release/release-notes-generator`, `@semantic-release/npm` and `@semantic-release/github`
- **semantic-release** configuration: [.releaserc](https://github.com/Berkmann18/TemplateJS/blob/master/.releaserc)
- CI logs: [log](https://travis-ci.org/Berkmann18/TemplateJS/jobs/466415832#L609)

**Comment by pvdlg** [comment]
The `@semantic-release/npm` plugin runs `npm version` to increase the version in the `package.json` but you have overwritten that script [here](https://github.com/Berkmann18/TemplateJS/blob/4cc4af811e63157ce916e9e623d67e28880c10a8/package.json#L21). So this is what ends up running instead of the actual [`npm version`](https://docs.npmjs.com/cli/version.html) and it fails apparently.

Don't override [default npm scripts](https://docs.npmjs.com/misc/scripts).

It seems you want to generate a changelog file and push it to Git? Then use the plugins [@semantic-release/git](https://github.com/semantic-release/git) and [@semantic-release/changelog](https://github.com/semantic-release/changelog).

**Comment by Berkmann18** [comment]
@pvdlg The reason why I was overwriting it is to automate the changelog generation as recommended by the developers of `conventional-changelog`.

**Comment by pvdlg** [comment]
semantic-release embed `conventional-changelog` to parse the commits and generate the changelog. I guess their recommendation applies when you the `conventional-changelog` CLI in standalone.

You should just remove that `version` script and use the 2 plugins I mentioned.
