### ISSUE TITLE
Hotfixing / applying a fix ontop of an older tag (not current)

### ISSUE THREAD

**Issue by appsolutegeek** [semantic-release/semantic-release#1034]
Hi,

I have been using semantic-release to release my new code via the master branch. Now a time has come that I have to apply a fix on top of 1.7. Currently the version in master in 2.3 - so its way ahead.

What I have tried is creating a new branch from the tag and applying the fix on this branch - i am using conventional commits so i add it as a "fix" which should increase the patch number.

I was able to successfully release from a branch by passing in the --branch parameter. The problem is now I have to merge back master but this seems to want to release something else.

I am little on what I supposed to be doing to enable this kind of hotfixing.

I did initially try and release the hotfix directly from the master branch but because this is ahead of 1.7 then technically i would be releasing things between 1.7 and the latest - right ?

I was hoping for some insight of the correct way to do this. Normally we can just keep releasing from master but there are times when we need to patch on top a verion that is not the current release.

Semantec release, as far as I know, doesn't support any prefixing for hotfix - so I just decided to use a PATCH - is this the normal behaviour ?

Any help would be really nice, i came from lerna and i could control the suffix - so I would just add the .fix to the end of the release.

Thanks in advance

**Comment by bddckr** [comment]
It sounds like you're trying to release a "maintenace" release which is properly supported by the beta via https://github.com/semantic-release/semantic-release/issues/563. The documentation (that also links to more specific details) can be found [here](https://github.com/semantic-release/semantic-release/blob/beta/docs/usage/workflow-configuration.md).

**Comment by pvdlg** [comment]
As @bddckr mentioned this workflow is supported in the version 16.0.0-beta.
You can refer to the documentation on the `beta` branch: https://github.com/semantic-release/semantic-release/blob/beta/docs/usage/workflow-configuration.md

Feel free to try it out and give us feedback in #563 or open another issue if you encounter a problem.

**Comment by appsolutegeek** [comment]
Yes, great. Thanks, both. I am going to try it this weekend.
