### ISSUE TITLE
semantic-release should support the short npm repository fields

### ISSUE THREAD

**Issue by hawkrives** [semantic-release/semantic-release#104]
https://docs.npmjs.com/files/package.json#repository:

> [...]
> For GitHub, GitHub gist, Bitbucket, or GitLab repositories you can use the same shortcut syntax you use for npm install:
> 
> `"repository": "npm/npm"`
> `"repository": "gist:11081aaa281"`
> `"repository": "bitbucket:example/repo"`
> `"repository": "gitlab:another/repo"`

`npm` itself appears to use the [hosted-git-info](https://www.npmjs.com/package/hosted-git-info) package to do this.

Would you be amenable to a PR adding support for this?

**Comment by killswitch** [comment]
:+1: Had a bunch of trouble getting `semantic-release` working until I realized `"repository": "npm/npm"` was the problem.

**Comment by boennemann** [comment]
I agree that it should do that. If someone would like to give this a try I'm happy to accept contributions for it and help with any questions along the way.

This might be another relevant package: https://github.com/npm/normalize-package-data

Best,
Stephan

**Comment by hawkrives** [comment]
I suppose that now that #119 has been merged, I should take another look at this and see what else needs to happen to do it.

**Comment by pvdlg** [comment]
@hawkrives, I tested with last release of `semantic-release` and it works with every URL I tried:
- npm/npm
- bitbucket:example/repo
- gitlab:another/repo
- git@github.com:example/repo

Could you confirm that everything works on your end?

**Comment by hawkrives** [comment]
I don't think I use semantic-release for any projects currently, sorry! If you say it works for those shorthands, that's good enough for me! I believe that my original request is satisfied.
