### ISSUE TITLE
Pre-release publication

### ISSUE THREAD

**Issue by mg901** [semantic-release/semantic-release#1045]
Thank you for the wonderful tool. However, I have a question to which I did not find the answer. How to explain semantic-release that I want to publish a pre-release version? For example (@next, alpha or beta)

**Comment by travi** [comment]
this capability is currently in pre-release status itself. take a look at [this summary](https://github.com/semantic-release/semantic-release/issues/563#issuecomment-447535385) and the rest of that thread for more detail

**Comment by pvdlg** [comment]
That is supported in the version `16.0.0-beta`. You can install it with `npm install semantic-release@16.0.0-beta` and you can find the corresponding doc on the [beta](https://github.com/semantic-release/semantic-release/tree/beta).

**Comment by mg901** [comment]
Incredibly grateful

**Comment by meebix** [comment]
@pvdlg - This is an awesome update. Can I assume that on each version (and release) of the "beta" branch, for instance, is going to bump the corresponding number accordingly?

`beta.0`
`beta.1`
`beta.2`
etc.

semantic-release is taking care of this?

Thanks.

**Comment by pvdlg** [comment]
@meebix please see the documentation I linked in my [previous comment](https://github.com/semantic-release/semantic-release/issues/1045#issuecomment-450005789)
