### ISSUE TITLE
Integration into an existing project.

### ISSUE THREAD

**Issue by mg901** [semantic-release/semantic-release#1049]
I already have a project with version 4.0.1 and I want to automate versioning using semantic-release. However, when testing, semantic-release offers me to start with version 1.0.0. Unfortunately, I did not find the recipe documentation, as I can clearly tell him the version I need. Thank you in advance for your reply.

**Comment by pvdlg** [comment]
See https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#existing-version-tags
