### ISSUE TITLE
Change initial release versioning strategy

### ISSUE THREAD

**Issue by jeremenichelli** [semantic-release/semantic-release#1054]
## New feature motivation

Right now, semantic release publishes the package to version `1.0.0` in case it doesn't exists in the registry. Though I saw some discussions around this decision, I think is not ideal since usually the first release of a package is a beta or not full featured to be at `1.0.0` from the start, it owuld be great for it to be a `0.1.0` or even `0.0.1`.

## New feature description

When semantic release runs and finds out the package doesn't exist it publishes a non-major version of it.

## New feature implementation

Nothing technical, I think this is more a conceptual change than a technical one. 

Also, I want to thank you all contributors and maintainers for this amazing tool and for all your hard work ❤️

**Comment by travi** [comment]
see the FAQ for [the reasoning behind the current approach](https://semantic-release.gitbook.io/semantic-release/support/faq#can-i-set-the-initial-release-version-of-my-package-to-0-0-1). 

publishing a pre-release to the `alpha` or `beta` channel is even easier by using the beta channel of semantic-release. You can install it with `npm install semantic-release@16.0.0-beta` and you can find the corresponding doc on the [beta](https://github.com/semantic-release/semantic-release/tree/beta) branch.

**Comment by pvdlg** [comment]
Closing a per @travi [answer](https://github.com/semantic-release/semantic-release/issues/1054#issuecomment-450540506).
We won't change that behavior as we now support pre-releases(in version 16.0.0-beta).
