### ISSUE TITLE
My github releases do not look pretty on releases tab

### ISSUE THREAD

**Issue by appsolutegeek** [semantic-release/semantic-release#1059]
Hi,

I have been publishing to private repos up until now, and now I am trying to do github.

It does appear to be working, I mean, its creating new releases through travis .. but if you look here 

https://github.com/appsolutegeek/tslint-base/releases

My changelog info isn't displayed in bold like here https://github.com/semantic-release/semantic-release/releases

I am not including any extra assets but I would expect it to display the changelog per release.

can you help?

This is my config

```
{
  "branch": "master",
  "plugins": [
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    "@semantic-release/changelog",
    "@semantic-release/git",
    "@semantic-release/npm"
  ]
}
```

I must be missing something for including the correct markdown on the releases page.

Any ideas?

I never had this issue before as I wasn't using the github plugin.

Thanks in advance.

**Comment by bddckr** [comment]
Your repo's releases page isn't actually listing any _releases_, it is currently only listing _git tags_.

AFAIK for semantic-release to create a proper release on GitHub you need to use the [github plugin](https://github.com/semantic-release/github). According to the docs on it you don't have to configure its `assets` setting as that is empty by default. This should create a GitHub release.

**Comment by pvdlg** [comment]
Closing as [solution was provided](https://github.com/semantic-release/semantic-release/issues/1059#issuecomment-451532031) by @bddckr

**Comment by appsolutegeek** [comment]
> Your repo's releases page isn't actually listing any _releases_, it is currently only listing _git tags_.
> 
> AFAIK for semantic-release to create a proper release on GitHub you need to use the [github plugin](https://github.com/semantic-release/github). According to the docs of it you don't have to configure its `assets` setting as that is empty by default. This should create a GitHub release.

Ooopps, I missed adding the github plugin :-) Thanks..
