### ISSUE TITLE
Controlling the next version to be published ?

### ISSUE THREAD

**Issue by appsolutegeek** [semantic-release/semantic-release#1060]
Hi,

I have been doing some testing, removing github repos and unpublishing package that have just been published.

Now when i try and publish, npm complains because it says it already exists. After reading the npm unpublish command - it states that you can never use the version again.

My version in npm is always set to this

```
  "version": "0.0.0-development",
```

How do I control the next version temporary? So I can say start on version 1.3 for example?

Should i do something locally with the --no-ci ?

thanks in advance

**Comment by bddckr** [comment]
All you need to do is ensure the git repo has the matching tag (with the tag format you configured, by default `vX.Y.Z`. More info can be found [here](https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#existing-version-tags) in the semantic-release configuration documentation.

**Comment by pvdlg** [comment]
Closing as answer was provided by @bddckrv !
