### ISSUE TITLE
Changelog sometimes being empty despite commits

### ISSUE THREAD

**Issue by Berkmann18** [semantic-release/semantic-release#1068]
## Current behaviour
`semantic-release` generates a new changelog (with the version bump and all) which is empty (read nothing listed under the new version).
[Example here](https://github.com/Berkmann18/ServerBuilder/commit/41cc478bb2fee88f366e812025f8bc82033ebf0c) which has nothing under `3.2.0`

## Expected behaviour
It should write the changes corresponding to the version bump.
The example above should have an "Update" section with "Added `name` to the server and `env` to the instance".

## Environment

- **semantic-release** version: 15.13.3
- CI environment: TravisCI
- Plugins used:`@semantic-release/commit-analyzer`, `@semantic-release/release-notes-generator`, `@semantic-release/changelog`, `@semantic-release/npm`, `@semantic-release/github`, `@semantic-release/git`
- **semantic-release** configuration: [.releaserc](https://github.com/Berkmann18/ServerBuilder/blob/master/.releaserc)
- [CI log](https://travis-ci.org/Berkmann18/ServerBuilder/jobs/479102941).

**Comment by pvdlg** [comment]
That's because you are using the `eslint` for `@semantic-release/commit-analyzer` but the default one for `@semantic-release/release-notes-generator`.
You should use the same preset for both.

**Comment by pvdlg** [comment]
It seems works sometime because the angular release note generator can sometime parse the eslint formatted commits and make something out of it.

**Comment by Berkmann18** [comment]
Oh, that's interesting!
