### ISSUE TITLE
Branch is undefined when used in Jenkins

### ISSUE THREAD

**Issue by pongells** [semantic-release/semantic-release#1070]
## Current behavior

I am running `semantic-release` in Jenkins via the following Pipeline step triggered by a PR from my develop branch to the master branch:
```
stage('Semantic release') {
    sh("npx semantic-release --repository-url ${params.repository} --branch master")
}
```
Locally (with `"ci": false`) everything works as expected, while on Jenkins (in the correct non-detached branch) it cannot find the current branch.

Could it be something related to https://github.com/pvdlg/env-ci#jenkins ? 
> Triggering build when a Pull Request is opened/updated is supported only via the ghprb-plugin and gitlab-plugin. Therefore env-ci will set isPr, pr and prBranch and define branch with the Pull Request target branch only if one those plugin is used.

EDIT: the same happens if I merge develop to master without PR and then manually trigger the Jenkins job, so I guess not...

## Expected behavior

I would expect `semantic-release` to get the right branch, or for me to have a way to configure the CI ENV variables so that `semantic-release`  works (if there is a way, I'd be very grateful for some help).

## Environment

- **semantic-release** version: ^15.13.2
- CI environment: Jenkins
- Plugins used:  "@semantic-release/commit-analyzer", "@semantic-release/release-notes-generator", "@semantic-release/changelog", "@semantic-release/exec", "@semantic-release/npm", "@semantic-release/git"
- **semantic-release** configuration:
```
module.exports = {
    "plugins": [
        "@semantic-release/commit-analyzer",
        "@semantic-release/release-notes-generator",
        "@semantic-release/changelog",
        ["@semantic-release/exec", {
            "execCwd": "scripts/jenkins/",
            "prepareCmd": "lerna-version.sh ${nextRelease.version}"
        }],
        ["@semantic-release/npm", {
            "npmPublish": false
        }],
        ["@semantic-release/git", {
            "assets": ["packages/*/package.json", "packages/*/version.js", "CHANGELOG.md", "lerna.json", "package.json"],
            "message": "chore(release): ${nextRelease.version}\n\n${nextRelease.notes}"
        }]
    ],
    "dryRun": false,
    "ci": true
}
```
- CI logs: 
```
18:02:28 + npx semantic-release --repository-url ssh://myrepo --branch master
18:02:29 [18:02:29] [semantic-release] › ℹ  Running semantic-release version 15.13.2
18:02:30 [18:02:30] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/changelog"
18:02:30 [18:02:30] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/exec"
18:02:30 [18:02:30] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/npm"
18:02:30 [18:02:30] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/git"
18:02:30 [18:02:30] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
18:02:30 [18:02:30] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/exec"
18:02:30 [18:02:30] [semantic-release] › ✔  Loaded plugin "verifyRelease" from "@semantic-release/exec"
18:02:30 [18:02:30] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
18:02:30 [18:02:30] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/exec"
18:02:30 [18:02:30] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/changelog"
18:02:30 [18:02:30] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/exec"
18:02:30 [18:02:30] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/npm"
18:02:30 [18:02:30] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/git"
18:02:30 [18:02:30] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/exec"
18:02:30 [18:02:30] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/npm"
18:02:30 [18:02:30] [semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/exec"
18:02:30 [18:02:30] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/exec"
18:02:30 [18:02:30] [semantic-release] › ℹ  This test run was triggered on the branch undefined, while semantic-release is configured to only publish from master, therefore a new version won’t be published.
```

**Comment by pongells** [comment]
I "solved" the issue by manually providing the necessary ENV variables to the CI.. ugly but working.

Details:
this module needs: ` const {isCi, branch: ciBranch, isPr} = envCi({env, cwd});` 
and looking into `env-ci` for jenkins:
```
const pr = env.ghprbPullId || env.gitlabMergeRequestId || env.CHANGE_ID;
const isPr = Boolean(pr);
const localBranch = env.GIT_LOCAL_BRANCH || env.GIT_BRANCH || env.gitlabBranch || env.BRANCH_NAME;

return {
	name: 'Jenkins',
	service: 'jenkins',
	commit: env.ghprbActualCommit || env.GIT_COMMIT || head({env, cwd}),
	branch: isPr ? env.ghprbTargetBranch || env.gitlabTargetBranch : localBranch,
	build: env.BUILD_NUMBER,
	buildUrl: env.BUILD_URL,
	root: env.WORKSPACE,
	pr,
	isPr,
	prBranch: isPr ? env.ghprbSourceBranch || env.gitlabSourceBranch || localBranch : undefined,
};

```
so I just added:
`withEnv(["BRANCH_NAME=${params.branch}", "gitlabTargetBranch=${params.branch}"]) {`
to my Jenkins job.. 🥇

**Comment by pvdlg** [comment]
As mentioned in the [docs](https://github.com/pvdlg/env-ci#jenkins) `gitlabTargetBranch` require the [gitlab-plugin](https://github.com/jenkinsci/gitlab-plugin).
According to the [Jenkins documentation](https://wiki.jenkins.io/display/JENKINS/Building+a+software+project) the variable `GIT_BRANCH` should be set. I don't know why it's not set in your case. Likely an issue with your version/environment/configuration.
I would recommend to use `gitlab-plugin` so semantic-release can detect PR builds.

**Comment by pongells** [comment]
@pvdlg thanks, yeah, cannot use GitLab plugin because.. well because I am using BitBucket 🗡

**Comment by nathanbrock** [comment]
Hi @pvdlg. We're currently experiencing the same issue with Jenkins and the latest version of SR. We're not entirely sure if it's exactly 15.13.3 causing the issue, but have found pinning the version to 15.9.6, the last version we had running successfully, did the trick. We'll continue to investigate at what point the problem started.

**Comment by ZebraFlesh** [comment]
I ran into this myself and it _sounds_ like the same issue: Jenkins pipeline checks out a detached git head by default, so you'll see weird things like the branch is undefined and/or the git ref spec doesn't match. The solution is to tell jenkins to checkout to a local branch. (I did this in the declarative part of jenkins, instead of in the jenkinsfile; jenkins being jenkins, I'm sure there are multiple ways to achieve this configuration.) Everything worked as expected after that change. A longer discussion can be found in [this jenkins issue](https://issues.jenkins-ci.org/browse/JENKINS-6856).

**Comment by rodoabad** [comment]
@ZebraFlesh I'm using DSL right now and it was working on Pipelines but with DSL this is the rror I"m getting.

```
2019-03-26 15:07:05 CDT [Semantic release]: Load plugin verifyConditions from @semantic-release/npm
2019-03-26 15:07:06 CDT [Semantic release]: Load plugin verifyConditions from @semantic-release/github
2019-03-26 15:07:06 CDT [Semantic release]: Load plugin analyzeCommits from @semantic-release/commit-analyzer
2019-03-26 15:07:06 CDT [Semantic release]: Load plugin generateNotes from @semantic-release/release-notes-generator
2019-03-26 15:07:06 CDT [Semantic release]: Load plugin prepare from @semantic-release/npm
2019-03-26 15:07:06 CDT [Semantic release]: Load plugin publish from @semantic-release/npm
2019-03-26 15:07:06 CDT [Semantic release]: Load plugin publish from @semantic-release/github
2019-03-26 15:07:06 CDT [Semantic release]: Load plugin success from @semantic-release/github
2019-03-26 15:07:06 CDT [Semantic release]: Load plugin fail from @semantic-release/github
2019-03-26 15:07:06 CDT [Semantic release]: This test run was triggered on the branch origin/master, while semantic-release is configured to only publish from master, therefore a new version won’t be published.
```

**Comment by rodoabad** [comment]
I'm already doing...

```
git checkout master
npx semantic-release
```

to make sure I have a local branch.

**Comment by rodoabad** [comment]
If you're using DSL, use this...

<img width="1393" alt="Screen Shot 2019-03-26 at 3 48 48 PM" src="https://user-images.githubusercontent.com/1240667/55032356-b0429b80-4fde-11e9-9a68-db352f66eaf7.png">

**Comment by y0zg** [comment]
@rodoabad 
Your last comment saved me the time! Do you have this config in UI only or use in pipeline config as well? Also this discussion explains how to work with local branched in Jenkins  https://stackoverflow.com/questions/45399894/is-it-impossible-to-checkout-a-different-branch-in-jenkinsfile
