### ISSUE TITLE
How to *not* publish to npm or github?

### ISSUE THREAD

**Issue by simlu** [semantic-release/semantic-release#1075]
As per https://github.com/semantic-release/semantic-release/issues/753#issuecomment-455273645 I'm trying have a very simple release script that checks the next version and dumps it into a text file. It should not do anything else. However atm I unfortunately can't get it to *not* publish to github.

```
{
  "npmPublish": false,
  "verifyConditions": [
    "@semantic-release/github"
  ],
  "prepare": [
    {
      "path": "@semantic-release/exec",
      "cmd": "echo \"${nextRelease.version}\" > version.txt"
    }
  ],
  "publish": []
}
```

How can I change this so that it doesn't publish to github or npm, but still runs the prepare script?

Appreciate your help very much! Thank you!

Cheers, L~

**Comment by pvdlg** [comment]
Per our [Contributing guildline](https://github.com/semantic-release/semantic-release/blob/master/CONTRIBUTING.md#using-the-issue-tracker) please use the appropriate channels for requesting supporting.

You can use the [`plugins`](https://github.com/semantic-release/semantic-release/blob/master/docs/usage/plugins.md) and just not use the `@semantic-release/npm` or `@semantic-release/github`.

**Comment by simlu** [comment]
I guess I should have formulated it as a feature request. Thanks for getting back to me. I'll try to figure it out I guess.

**Comment by pvdlg** [comment]
> I guess I should have formulated it as a feature request. Thanks for getting back to me. I'll try to figure it out I guess.

The objective of having different channels to handle bugs/features and support request is to:
- encourage other users to answers support questions
- make the issue tracker clearer and less busy
- make support answers easier to be found by search engines
- encourage users to read the documentation, the FAQ and other support answers before opening an issues
- have a clear view of what development is in progress (issue tracker + Waffle), without cluttering the issue tracker with support request

The objective is evidently not to force people to "formulate" or disguise support questions as feature request.

**Comment by simlu** [comment]
Haha, I get that and I was mostly kidding. No I was even considering filing it as a bug initially, but then changed my mind.

It just feels weird that you can set

`"publish": []`

but then it still publishes. There might be something in the docs about it, but I haven't found it yet.

I'll try to investigate the other channels you mentioned. Which one should I prefer?
