### ISSUE TITLE
Uploading artifacts to CircleCI

### ISSUE THREAD

**Issue by pvdlg** [semantic-release/semantic-release#1078]
@pvdlg As [described](https://github.com/semantic-release/semantic-release/issues/753#issuecomment-455666575) it comes down to the fact that we can not use semantic-release to [store CircleCi artifacts](https://circleci.com/docs/2.0/artifacts/), since this is not done via a terminal command.

The requirements are:
1. We want to build an artifact that internally includes the release version, so when it's run by a user it's immediately clear (1) what release version this was going towards, i.e. it's clear when something is outdated and (2) what CircleCi build number is associated, i.e. it's easy to debug where the artifact came from exactly
2. Store the artifact in CircleCi
3. Use a version number that includes the CircleCi build number as well as the upcoming release number for above reasons.

Please let me know if you have any further questions about this use case!

I'm ok with the "hack" that I have in place. It is a hack, but should continue to work going forward unless something fundamentally changes with plugin handling.

_Originally posted by @simlu in https://github.com/semantic-release/semantic-release/issues/753#issuecomment-455810063_

**Comment by pvdlg** [comment]
Then just use the `@semantic-release/exec` plugin and configure the `publishCmd` with something like `./publish-artefact.sh ${nextRelease.version}`.
In the `puplish-artefact.sh` script the first argument will be the version being published by semantic-release.
In that script, build your stuff, name it the way you want using the version and whatever environment variable CircleCI provide and copy it in the directory where CircleCI pick the artifacts.

**Comment by simlu** [comment]
@pvdlg No, that doesn't work. We might have multiple builds for the same "upcoming" semantic-release release (same version number with different build number). With your approach the repo would get tagged and the next time semantic-release runs no upcoming version would be returned. That's why I need the kill switch `exit 1` as mentioned in the other thread....

**Comment by pvdlg** [comment]
Please see the [CI configuration documentation](https://github.com/semantic-release/semantic-release/blob/master/docs/usage/ci-configuration.md#run-semantic-release-only-after-all-tests-succeeded) that explicitly specify the following:
> The semantic-release command must be executed only after all the tests in the CI build pass. If the build runs multiple jobs (for example to test on multiple Operating Systems or Node versions) the CI has to be configured to guarantee that the semantic-release command is executed only after all jobs are successful. This can be achieved with Travis Build Stages, CircleCI Workflows, Codeship Deployment Pipelines, GitLab Pipelines, Codefresh Pipelines, Wercker Workflows or GoCD Pipelines.

A release must be unique, that's a basic requirement of semver, as a release with a given version must always be the same no matter when and where you download it. So a published version has to be built once and released once. This is why most package managers prevent to re-publish or unpublish a release with the same verssion. We are not going to change this behavior.

**Comment by simlu** [comment]
@pvdlg I'm not arguing with that at all. However this is the equivalent of compiling your program. The prime example here is a mobile app:

- You are not going to increase the version every time you compile, however the build number will
- You might juggle a lot of different version and builds on your device. It's really, really handy to know the version of the app, plus the build number and the branch when you look at it.

I'm not saying this needs to be supported (it works good enough for me now) and for npm packages your probably right to not care, but this is a real use case.

**Comment by pvdlg** [comment]
semantic-release is designed as a release tool not as a build one. It is meant to be used independently of your build tool, as a final step for releasing. This is why we determine the version only when we release, and we don't determine "would be version". This is by design. 

If you want to creates multiple builds that contains the version, semantic-release is not the right tool and you should using something to manage your versioning.
