### ISSUE TITLE
Use semantic-release with Jenkins CI and ssh only Github enterprise repo

### ISSUE THREAD

**Issue by kirasagi** [semantic-release/semantic-release#1081]
## Current behavior
From what I've read in the docs, we can do git authentication with ssh keys, and so I'm assuming we can use semantic-release with repos only accessible with ssh keys. 

I think I have configured ssh correctly in my Jenkins CI, however whenever I run semantic-release, it says I still need to provide a personal access token. From my understanding we only use personal access tokens when accessing the repo with https. I did make a personal access token, plus provide github url + prefix, but I'm getting a 406 error:

```
[Semantic release]: An error occurred while running semantic-release: { HttpError
    at response.text.then.message (/home/jenkins/.npm/_npx/378/lib/node_modules/semantic-release/node_modules/@octokit/rest/lib/request/request.js:72:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  name: 'HttpError',
  code: 406,
  status: undefined,
```

I also wasn't sure what to put as the github URL and github prefix. Since I was using github enterprise, I basically put `https://github.<company>.com` and `https://github.<company>.com/api/v3/`.
Some help on this would be appreciated.

## Expected behavior
I'm expecting semantic-release to run and do git authentication properly.

## Environment

- **semantic-release** version: 15.0.0
- CI environment: Jenkins CI
- Plugins used: `@semantic-release/commit-analyzer`, `@semantic-release/release-notes-generator`, `@semantic-release/npm`, `@semantic-release/github`
- **semantic-release** configuration: 
```
  "release": {
    "branch": "jenkins-build",
    "plugins": [
      "@semantic-release/commit-analyzer",
      "@semantic-release/release-notes-generator",
      [
        "@semantic-release/npm",
        {
          "pkgRoot": "dist/bti/test-lib"
        }
      ],
      ["@semantic-release/github",
        {
          "repositoryUrl": "https://github.company.com/benriqu/npm-test-lib"
        }
      ]
    ]
  }
```
- CI logs:
  - semantic-release logs without Github info: https://gist.github.com/kirasagi/f0ac530c7a1fcdc7e0df86f3620f7101
  - semantic-release logs with Github info: https://gist.github.com/kirasagi/adf3ec85253e4811bea24f200a0b9135

**Comment by pvdlg** [comment]
We can't help you with so few details.

I'm sure you noticed there is 3 different templates when opening an issue on this repo, and one of them is [Bug Report](https://github.com/semantic-release/semantic-release/issues/new?template=01_bug_report.md) which ask all the information we need to help.

May I ask if somehow you didn't see that template (maybe you opened the issue with a third-party client?)? Or if you choose to ignore it? If yes, why?

We have a lot of support requests and it's very time consuming to handle, especially when going back and forth, requesting additional informations. So we try to improve with issue templates and [contributing guidelines](https://github.com/semantic-release/semantic-release/blob/master/CONTRIBUTING.md#using-the-issue-tracker). But obviously that failed in this instance...

We would greatly appreciate if you could give us any feedback regarding improvements to our repo such that you would have provided those information right away when you opened this issue.

**Comment by pvdlg** [comment]
Please see the [`@semantic-release/github` options](https://github.com/semantic-release/github#options). It doesn't support the `repositoryUrl ` option.

`repositoryUrl ` is a global option as described in [semantic-release options documentation](https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#repositoryurl) and should be your repository URL.

If you are using a GitHub enterprise instance you have to set [`githubUrl`](https://github.com/semantic-release/github#options).

**Comment by kirasagi** [comment]
I added the `githubUrl` entry and I'm getting the same error. I have defined `GITHUB_URL` and `GITHUB_PREFIX` in my environment also so it should be the same result.

**Comment by pvdlg** [comment]
What is your configuration now?
What is the URL on which you access the GH instance?
On which URL is the API deployed?
Did you test that URL to make sure the API is available?

**Comment by kirasagi** [comment]
Configuration:
```
  "release": {
    "branch": "jenkins-build",
    "plugins": [
      "@semantic-release/commit-analyzer",
      "@semantic-release/release-notes-generator",
      [
        "@semantic-release/npm",
        {
          "pkgRoot": "dist/bti/test-lib"
        }
      ],
      [
        "@semantic-release/github",
        {
          "githubUrl": "https://github.<company>.com/"
        }
      ]
    ]
  }
```
GH instance url: `https://github.<company>.com/`
API: `https://github.<company>.com/api/v3/`
I tested the API url using `curl -u <user> https://github.<company>.com/api/v3/` using my personal access token as the password and it returned me the different endpoints for the API, so I think it works.

**Comment by pvdlg** [comment]
What is the value you set for  the `GITHUB_PREFIX` environment variable?

**Comment by kirasagi** [comment]
It's basically the same as the GH instance url except with `/api/v3/` added.

GH instance url: `https://github.<company>.com/` (same value as `GITHUB_URL` env)
API: `https://github.<company>.com/api/v3/` (same value as `GITHUB_PREFIX` env)

**Comment by pvdlg** [comment]
`GITHUB_PREFIX` is just the prefix not the URL. it should be set to `/api/v3`

**Comment by kirasagi** [comment]
That worked. With this I think the `GITHUB_PREFIX` term is confusing in this case because "prefix" usually means something added before, while `/api/v3` is after. Thanks for the help!
