### ISSUE TITLE
repositoryUrl needs an option to only use git origin (and ignore package.json)

### ISSUE THREAD

**Issue by icopp** [semantic-release/semantic-release#1082]
## New feature motivation

Bitbucket Pipelines now have zero-config `git push` functionality from a pipeline. However, this works by using a magic value git origin that passes through a reverse proxy the pipeline is connected to, which is not the same as the `repository.url` value in `package.json` and can't be statically set.

The only current workaround for this, without stripping out `repository.url`, is to use a `scripts` entry like `"semantic-release": "semantic-release --repository-url ${BITBUCKET_GIT_HTTP_ORIGIN}"` to explicitly invoke the magic value for the git origin, which is obviously pretty fragile.

## New feature description

This would use a new config option, such as `"repositoryUrlFromGitOrigin": true` / `--repository-url-from-git-origin`.

## New feature implementation

The behavior would be the same as automatically using the git origin in cases where the `repository.url` value in `package.json` doesn't exist.

**Comment by pvdlg** [comment]
> The only current workaround for this, without stripping out repository.url, is to use a scripts entry like "semantic-release": "semantic-release --repository-url ${BITBUCKET_GIT_HTTP_ORIGIN}" to explicitly invoke the magic value for the git origin, which is obviously pretty fragile.

Why is it fragile? Sure, it relies on a BitBucket specific environment variable, but having this `repositoryUrlFromGitOrigin` option would also relies on a BitBucket specific feature (to set the local repo remote URL as the authenticated one). So I don't really see why one is more fragile than the other.

Adding an option would also mean adding more confusion for users...and considering the number of support tickets we have, people are already pretty confused about repository URLs and authentication.

**Comment by pvdlg** [comment]
Closing has no answer was provided.
