### ISSUE TITLE
Ordering of git plugin and 0.0.0-development version

### ISSUE THREAD

**Issue by appsolutegeek** [semantic-release/semantic-release#1086]
Hi,

I was hoping somebody could confirm what I should be doing with regards to managing the version inside the package.json.

Up until now I have been using 0.0.0-development as the version inside package.json and had my following plugins like so 

```
  "plugins": [
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    "@semantic-release/changelog",
    "@semantic-release/git"
    "@semantic-release/npm",
  ]
```

With this setup, the package.json is not updated in the source control. I was wondering if i should change around my plugins so the update version ends up being inside of source control.

I don't know what implications this has and what is the recommended way of doing is 

Can anybody confirm ?

Thanks

**Comment by travi** [comment]
please take some time to read through the documentation. all of this is covered there, including [why the version is not updated in version control](https://semantic-release.gitbook.io/semantic-release/support/faq#why-is-the-package-jsons-version-not-updated-in-my-repository).

**Comment by appsolutegeek** [comment]
Thanks @travi , I missed that. Thanks for the link
