### ISSUE TITLE
Github and npm plugins keeps getting called while git plugin isn't, using Github enterprise

### ISSUE THREAD

**Issue by kirasagi** [semantic-release/semantic-release#1088]
## Current behavior

I'm working on a CI build where I have the git plugin turned on, and github/npm plugins turned off. However, for some reason when running semantic release it publishes an npm package and also makes a Github release. It also doesn't make a commit that updates the git repo of a new version (I believe git plugin is supposed to do this).

It seems that semantic release runs the Github and npm plugins by default. I am using Github enterprise.

## Expected behavior

Since I'm using the git plugin, it should make a commit for me that updates the version in my package.json. Semantic release should not publish a Github release and an npm package.

## Environment

- **semantic-release** version: 15.0.0
- CI environment: Jenkins
- Plugins used: `@semantic-release/commit-analyzer`, `@semantic-release/release-notes-generator`, `@semantic-release/changelog`, `@semantic-release/git`
- **semantic-release** configuration: 
Using a `.releaserc.json` file
```
{
  "branch": "jenkins-build-npm",
  "plugins": [
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    "@semantic-release/changelog",
    "@semantic-release/git"
  ]
}

```
- CI logs: https://gist.github.com/kirasagi/136765b895946b1ae4e65981862bb479

**Comment by pvdlg** [comment]
The `plugins` option has been added in [version 15.10.0](https://github.com/semantic-release/semantic-release/releases/tag/v15.10.0). You are using version 15.0.0
