### ISSUE TITLE
Unable to run semantic-release with Jenkins

### ISSUE THREAD

**Issue by dagnello** [semantic-release/semantic-release#1090]
## Current behavior
When running in Jenkins environment, unable to publish because branch name comes up as undefined:
[semantic-release] › ℹ  This test run was triggered on the branch undefined, while semantic-release is configured to only publish from master, therefore a new version won’t be published.

## Expected behavior

semantic release process continues with appropriate git branch

## Environment

- **semantic-release** version: 15.13.3
- CI environment: Jenkins
- Plugins used: ["@semantic-release/commit-analyzer",
      "@semantic-release/release-notes-generator",
      [
        "@semantic-release/npm",
        {
          "npmPublish": false
        }
      ],
      "@semantic-release/github"]
- **semantic-release** configuration: 
{
    "branch": "develop",
    "plugins": [
      "@semantic-release/commit-analyzer",
      "@semantic-release/release-notes-generator",
      [
        "@semantic-release/npm",
        {
          "npmPublish": false
        }
      ],
      "@semantic-release/github"
    ]
  }

- CI logs: 

```
16:37:59 > npx semantic-release --debug
16:37:59 
16:37:59 [16:38:16] [semantic-release] › ℹ  Running semantic-release version 15.13.3
16:37:59 2019-01-31T00:38:16.948Z semantic-release:config load config from: /home/jenkins/workspace/my-project-pipeline/package.json
16:37:59 2019-01-31T00:38:16.961Z semantic-release:config options values: { branch: 'test',
16:37:59   repositoryUrl: 'https://github.com/<something>/my-project',
16:37:59   tagFormat: 'v${version}',
16:37:59   plugins: 
16:37:59    [ '@semantic-release/commit-analyzer',
16:37:59      '@semantic-release/release-notes-generator',
16:37:59      [ '@semantic-release/npm', [Object] ],
16:37:59      '@semantic-release/github' ],
16:37:59   preset: 'angular',
16:37:59   _: [],
16:37:59   debug: true,
16:37:59   '$0': 'node_modules/.bin/semantic-release' }
16:38:00 2019-01-31T00:38:17.296Z semantic-release:plugins options for @semantic-release/npm/verifyConditions: { npmPublish: false }
16:38:00 [16:38:17] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/npm"
16:38:00 2019-01-31T00:38:17.297Z semantic-release:plugins options for @semantic-release/github/verifyConditions: {}
16:38:00 [16:38:17] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/github"
16:38:00 2019-01-31T00:38:17.297Z semantic-release:plugins options for @semantic-release/commit-analyzer/analyzeCommits: {}
16:38:00 [16:38:17] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
16:38:00 2019-01-31T00:38:17.298Z semantic-release:plugins options for @semantic-release/release-notes-generator/generateNotes: {}
16:38:00 [16:38:17] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
16:38:00 2019-01-31T00:38:17.298Z semantic-release:plugins options for @semantic-release/npm/prepare: { npmPublish: false }
16:38:00 [16:38:17] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/npm"
16:38:00 2019-01-31T00:38:17.298Z semantic-release:plugins options for @semantic-release/npm/publish: { npmPublish: false }
16:38:00 [16:38:17] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/npm"
16:38:00 2019-01-31T00:38:17.298Z semantic-release:plugins options for @semantic-release/github/publish: {}
16:38:00 [16:38:17] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/github"
16:38:00 2019-01-31T00:38:17.299Z semantic-release:plugins options for @semantic-release/github/success: {}
16:38:00 [16:38:17] [semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/github"
16:38:00 2019-01-31T00:38:17.299Z semantic-release:plugins options for @semantic-release/github/fail: {}
16:38:00 [16:38:17] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/github"
16:38:00 [16:38:17] [semantic-release] › ℹ  This test run was triggered on the branch undefined, while semantic-release is configured to only publish from test, therefore a new version won’t be published.
```

**Comment by pvdlg** [comment]
This is the code used to determine the branch on which the build is running: https://github.com/pvdlg/env-ci/blob/master/services/jenkins.js

According to the [Jenkins doc](https://wiki.jenkins.io/display/JENKINS/Building+a+software+project) the environment variable `GIT_BRANCH` should be set with the branch that triggered the build.

As you can see from the code we also check `GIT_LOCAL_BRANCH`, `gitlabBranch` and `BRANCH_NAME` as a backup solution. `GIT_BRANCH` is supposed to be set but with some version of Jenkins one of the other variable is used instead.

So I would suggest you to investigate why none of those variables are set. It's probably an issue specific to your environment.
I would also suggest to ask the Jenkins team if the `GIT_BRANCH` variable not being set is a bug or an error in the documentation. If it turns out there is yet another variable that can contain the current branch, please let us know so we can add it.

**Comment by dagnello** [comment]
@pvdlg thank you, this resolved this configuration issue.
