### ISSUE TITLE
Semantic Release doesn't follow if a repo is moved (npm publishing)

### ISSUE THREAD

**Issue by Aghassi** [semantic-release/semantic-release#1094]
## Current behavior

If you move a repo in GitHub from org to another, but don't update the package.json, it is possible to start having the release fail due to lack of permissions on the token even if the user still has write access to the repo.

## Expected behavior

I would expect that if the git url doesn't match the package.json repo url, then either:

1. We surface an error that is clearly saying "EURLMISMATCH" or something
2. We assume the git url is correct from git and use that one, then create an issue on the repo saying "package.json url doesn't match git url, please update"

## Environment

- **semantic-release** version:  15.13.3
- CI environment:  CircleCI
- Plugins used:  `git`, `npm`, `GitHub`, and the defaults
- **semantic-release** configuration:  
``` javascript
module.exports = {
  verifyConditions: [
    '@semantic-release/changelog',
    '@semantic-release/git',
    '@semantic-release/github',
  ],
  prepare: [
    '@semantic-release/npm',
    '@semantic-release/changelog',
    {
      path: '@semantic-release/git',
      assets: ['package.json', 'CHANGELOG.md', 'README.md', 'docs'],
    },
  ],
  publish: [
    {
      path: '@semantic-release/npm',
      // Update the package.json, but skip publishing to the registry
      npmPublish: false,
    },
    {
      path: '@semantic-release/github',
      assets: [['dist']],
    },
  ],
  success: ['@semantic-release/github'],
  fail: ['@semantic-release/github'],
};
```
- CI logs: 

```
[11:54:14 PM] [semantic-release] › ✖  The command "git push --dry-run https://[secure]@github.enterprise.com/org/repo.git. HEAD:master" failed with the error message remote: Repository not found.
fatal: repository 'https://[secure]@github.enterprise.com/org/repo.git.' not found
.
[11:54:14 PM] [semantic-release] › ℹ  Start step "fail" of plugin "@semantic-release/github"
[11:54:14 PM] [semantic-release] [@semantic-release/github] › ℹ  Verify GitHub authentication (https://github.enterprise.com/api/v3)
[11:54:22 PM] [semantic-release] › ✖  Failed step "fail" of plugin "@semantic-release/github"
[11:54:22 PM] [semantic-release] › ✖  EMISSINGREPO The repository org/repo doesn't exist.
The semantic-release repositoryUrl option must refer to your GitHub repository. The repository must be accessible with the GitHub API (https://developer.github.com/v3).

By default the repositoryUrl option is retrieved from the repository property of your package.json or the git origin url (https://git-scm.com/book/en/v2/Git-Basics-Working-with-Remotes) of the repository cloned by your CI environment.

If you are using GitHub Enterprise (https://enterprise.github.com) please make sure to configure the githubUrl and githubApiPathPrefix options (https://github.com/semantic-release/github/blob/master/README.md#options).

[11:54:22 PM] [semantic-release] › ✖  EGITNOPERMISSION The push permission to the Git repository is required.
semantic-release cannot push the version tag to the branch master on remote Git repository with URL https://[secure]@github.enterprise.com/org/repo.git.

Please refer to the authentication configuration documentation (https://github.com/semantic-release/semantic-release/blob/master/docs/usage/ci-configuration.md#authentication) to configure the Git credentials on your CI environment and make sure the repositoryUrl (https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#repositoryurl) is configured with a valid Git URL (https://git-scm.com/book/en/v2/Git-on-the-Server-The-Protocols).
```

**Comment by pvdlg** [comment]
> I would expect that if the git url doesn't match the package.json repo url, then either:
> 1. We surface an error that is clearly saying "EURLMISMATCH" or something
> 2. We assume the git url is correct from git and use that one, then create an issue on the repo saying "package.json url doesn't match git url, please update"

There is valid scenario where the remote URL of the local repo on the CI and the repository URL in the `package.json`. For example if the CI set the URL with `http` but you want to use a `https` or `ssh` URL.

In addition, each CI do they own stuff regarding the remote they set in the cloned repo, so we can't rely on that. This is why we favor the repository URL configured by the user over the one set by the CI.

Manually configuring the repository URL is by far a more common use case than moving the repo and forgetting to change the URL in the `package.json`. So we'll keep things as is and continue to allow user to configure the repository URL and override the one set by the CI.
