### ISSUE TITLE
Release custom versions on  each build

### ISSUE THREAD

**Issue by cyberhck** [semantic-release/semantic-release#1096]
## New feature motivation

Let's say I'm a library author and there's a new version, even though all tests have passed, I'd like to actually use it before I merge, so something  like <current version>-RC<PR number>+<build ID> (convention  can be something else, I'm sure we can find something better.

Let me give an example with totally random numbers, so if I have a PR and current version was 0.1.8, and the PR identifier is 103, and travis build ID is 182302, then a 0.1.8-RC103+182302 (obviously naming will be different which doesn't break semantic versioning)

## New feature description
I think current workflow should stay as it is, if we start releasing on each PR, people might get mad, I'd say have a flag something like `--enable-rc-publishing` (I'm very bad at naming, you guys will do a better job at this), if the flag is present, we start doing this, and on master, we simply do what we would have done.

I think we should also add a setup where only branch with certain naming pattern will do this, for instance, anything starting with "RC" branch will publish this, but individual PRs won't, totally up to author.

## New feature implementation

I'm not sure of this. I've never implemented a plugin, and I've definitely not digged into semantic-release's source code either.

It might be a lot of work, but it'd make workflow so much better.

Please express your thoughts on this.

**Comment by travi** [comment]
have you seen the support for pre-releases that is available in the beta version of semantic-release? what you describe sounds like it would largely be satisfied by that support: https://github.com/semantic-release/semantic-release/blob/beta/docs/recipes/pre-releases.md

**Comment by pvdlg** [comment]
Closing as answered in https://github.com/semantic-release/semantic-release/issues/1096#issuecomment-462103512. Already implemented in v16.0.0
