### ISSUE TITLE
Multi-branch and glob pre-releases impossible

### ISSUE THREAD

**Issue by dominykas** [semantic-release/semantic-release#1100]
## Current behavior

Suppose you have this in your config:

```
{
  branches: [
    { name: 'master', type: 'release' },
    { name: 'rc-*', type: 'prerelease', prerelease: 'rc' }
  ]
}
```

As soon as you have two `rc-*` branches, e.g. `rc-5` for `v5.x.x` prereleases and `rc-6` for `v6.x.x` prereleases, `semantic-release` will start failing with the following:

```
[3:39:07 PM] [semantic-release] › ✖  EPRERELEASEBRANCHES The pre-release branches are invalid in the `branches` configuration.
Each pre-release branch in the branches configuration (https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#branches) must have a unique prerelease property. If the prerelease property is set to true, then the name property is used instead.
```

## Expected behavior

I would like to be able to use a single suffix for multiple `prerelease` branches.

## Workaround

By setting `prerelease: true`, the `name` will be used for the prerelease suffix, but that means that publishing a pre-release from `rc-5.x.x` branch, will result in releases such as `v5.3.5-rc-5.x.x.1`, whereas the desirable version would be `v5.3.5-rc.1`.

## Environment

- **semantic-release** version: `16.0.0-beta.18`
- CI environment: (not applicable)
- Plugins used: defaults
- **semantic-release** configuration: (relevant details above)
- CI logs: (relevant details above)

---

I'm happy to entertain a PR if that's acceptable.

**Comment by pvdlg** [comment]
This is by design. If you were to allow to release from different branches with the same prerelease id you could en up with conflict:
- Create a `rc-5` and a `rc-6` branch from `master` (the last release is `1.0.0`)
- Push a `feat` to `rc-5` => release `1.1.0-rc.1`
- Push a `feat` to `rc-6` => release `1.1.0-rc.1` => npm error as you try to release the same version twice

**Comment by dominykas** [comment]
Not sure I follow? With release channel, the situation is exactly the same? 

* Create a `rc-5` and a `rc-6` branch from `master` (the last release is `1.0.0`)
* Push a `feat` to `rc-5` => release `1.1.0-rc.1@rc-5`
* Push a `feat` to `rc-6` => release `1.1.0-rc.1@rc-6` - the git tag is unique, in theory you'd be publishing into a different dist channel, but you still get the npm error?

My ultimate goal is channel-less pre-releases, but I'll go read through #1101.

**Comment by dominykas** [comment]
OK, so starting off the same version and releasing parallel pre-releases with different contents is an interesting use-case. Is it common? 

So the decision to make it unique is purely defensive, to avoid a potential tag collision? Would it make sense to only apply the restriction if the branches matches by the glob actually start at the same version? If they start at different versions - collision is not possible? The check doesn't even have to analyze commits - just the highest tag on a branch?

**Comment by pvdlg** [comment]
If we don't enforce that I don't think there is a scenario that doesn't create conflict or inconsistencies.
The name conflict is just an example of one problem that can happens.
A situation were you release `1.1.0-rc.1` then `2.0.0-rc.1` but `2.0.0-rc.1` doesn't contains all the commit included in `1.1.0-rc.1` is problematic.

**Comment by dominykas** [comment]
> A situation were you release 1.1.0-rc.1 then 2.0.0-rc.1 but 2.0.0-rc.1 doesn't contains all the commit included in 1.1.0-rc.1 is problematic.

Agreed, but this can happen regardless of the config and uniqueness of suffix? If the suffix is unique, then you end up with `1.1.0-rc-1.1.x.1` and `2.0.0-rc-2.x.x.1` which is just as bad, but also has unnecessarily complex version numbers?

But also 2.x might be a ground up rewrite, which doesn't need to have anything common with 1.x, so it's not always a bad thing.

**Comment by pvdlg** [comment]
I don't really any use case common enough to allow releasing from multiple branches on the same prerelease id.

I think I explained with a lot of details why it would be either impossible or at best extremely complex to implement.

So we'll keep the restriction in place for the reasons I explained above.

**Comment by dominykas** [comment]
That's fine, I already have tooling which automatically creates and removes branches, so that there is only one at a time, but it is hard to explain this behavior to people, it has to be said - this makes it hard to drive adoption.

Is there a recommended way to achieve v2.0.0-beta.1 and v1.1.0-beta.1 simultaneously?

**Comment by dominykas** [comment]
Also do you mind if I take a stab at alternative ways of ensuring the conditions you describe (version collision)? Be it a PR or an RFC-ish doc.
