### ISSUE TITLE
Many commits not considered for beta release

### ISSUE THREAD

**Issue by felixfbecker** [semantic-release/semantic-release#1103]
## Current behavior

I released a beta version: https://github.com/sourcegraph/lsp-client/releases/tag/v1.1.0-beta.1%40beta

As you can see, it semantic-release only detected 2 meaningful commits for the changelog and made it a minor version. However, there were many commits between this merge into the `beta` branch and the last tagged `v1.0.0` release, including a breaking change.

## Expected behavior

I would have expected these to appear in the release notes and to cause `2.0.0-beta.1`.

## Environment

- **semantic-release** 16.0.0-beta.18: 
- CI environment: Travis 
- Plugins used: default 
- **semantic-release** default 
- CI logs https://travis-ci.org/sourcegraph/lsp-client/jobs/496018543#L477

**Comment by Nargonath** [comment]
Looking at your repository and the CI log, it detected 15 commits which seems correct based on your history. There were:

- 2 `ci`
- 5 `chore`
- 1 `fix`
- 4 `refactor`
- 1 `feat`
- 1 `style`
- 1 `test`

Only the `feat` and `fix` commits should trigger a release. There is a `BREAKING CHANGE` for the `feat` commit: https://github.com/sourcegraph/lsp-client/commit/23c653d999458a6c3ec133f4bb12ff77efcca0fe but without the colon and the explanation. I'm not sure this format works for `semantic-release` hence that may be the reason it didn't trigger the major release and just the minor release.

**Comment by felixfbecker** [comment]
Oh, that makes sense

**Comment by Nargonath** [comment]
As a matter of example when using https://github.com/commitizen/cz-cli if you don't provide an explanation for your breaking change, the label is not added to the commit.

**Comment by pvdlg** [comment]
The parsing of the commit is done with [conventional-changelog](https://github.com/conventional-changelog/conventional-changelog) which follows the Angular convention closely and require a `BREAKING CHANGE` to have a descriptions explained by @Nargonath.
