### ISSUE TITLE
Use of `#` in commit body causes `closes` false positive

### ISSUE THREAD

**Issue by myii** [semantic-release/semantic-release#1107]
## Current behavior

Had this happen a few times now but manually fixed previously.  If a hash `#` appears in the commit body, it is seen as a `closes` in the release notes and changelog.  An existing example follows.

Commit https://github.com/saltstack-formulas/template-formula/commit/3a072c7:

```
ci(travis): prevent `release` stage running for PRs

* The `release` stage will always fail due to security reasons:
  - E.g. https://travis-ci.com/saltstack-formulas/template-formula/jobs/180068519#L466.
  - Discussed: #42 (comment).
* The `release` stage is unnecessary for PRs until the merge to `master`, in any case.
```

Resulted in both:

* https://github.com/saltstack-formulas/template-formula/releases/tag/v0.7.2
* https://github.com/saltstack-formulas/template-formula/blob/master/CHANGELOG.md#072-2019-02-24

Specifically:

> * **travis:** prevent `release` stage running for PRs ([3a072c7](https://github.com/saltstack-formulas/template-formula/commit/3a072c7)), closes [/travis-ci.com/saltstack-formulas/template-formula/jobs/180068519#L466](https://github.com//travis-ci.com/saltstack-formulas/template-formula/jobs/180068519/issues/L466) [/github.com/saltstack-formulas/template-formula/pull/42#issuecomment-466446324](https://github.com//github.com/saltstack-formulas/template-formula/pull/42/issues/issuecomment-466446324)

## Expected behavior

The `closes` shouldn't have been present:

> * **travis:** prevent `release` stage running for PRs ([3a072c7](https://github.com/saltstack-formulas/template-formula/commit/3a072c7))

## Environment

- **semantic-release** version: [15](https://github.com/saltstack-formulas/template-formula/blob/3a072c70077ba8b12c12abe4d0640a8a508fe3ab/.travis.yml#L70)
- CI environment: [Travis CI](https://github.com/saltstack-formulas/template-formula/blob/3a072c70077ba8b12c12abe4d0640a8a508fe3ab/.travis.yml)
- Plugins used: [changelog@3, exec@3 & git@7](https://github.com/saltstack-formulas/template-formula/blob/3a072c70077ba8b12c12abe4d0640a8a508fe3ab/.travis.yml#L62-L64)
- **semantic-release** configuration: [`release.config.js`](https://github.com/saltstack-formulas/template-formula/blob/3a072c70077ba8b12c12abe4d0640a8a508fe3ab/release.config.js)
- CI logs: Check under the [`Release`](https://travis-ci.com/saltstack-formulas/template-formula/builds/102058142) stage

## Further example that was manually fixed

* Commit: https://github.com/saltstack-formulas/template-formula/commit/068a94d
* Manual fix: https://github.com/saltstack-formulas/template-formula/commit/be4571d

**Comment by pvdlg** [comment]
The changelog is generated by [conventional-changelog](https://github.com/conventional-changelog/conventional-changelog) so I would suggest to open an issue over there.

**Comment by myii** [comment]
@pvdlg Thanks, I've copied across the issue over there, as shown linked above.  Would you prefer this issue is closed?

**Comment by pvdlg** [comment]
Yes I'll close it as there is nothing we can do here unfortunately.
