### ISSUE TITLE
Relation between pre-release (beta/alpha) and next for multi branching releases ?

### ISSUE THREAD

**Issue by appsolutegeek** [semantic-release/semantic-release#1120]
Hi,

I have had some great success on an alpha branch and adding and releasing and then finally merging into master and releasing on master. Seems to work great.

Initially, I was trying to use the branch NEXT but it is telling me that it only supports >=2.0.0 when I tried to release - my master branch has 1.x.x versions.

I was just looking for some confirmation, is the "next" branch always going to release the next major version ?

I have created an alpha and beta branch and these seem to work great, I am able to release with a suffix of alpha.x or beta.x and merging back in to master releases the product on the correct version (minus the suffix).

So am I doing this correctly, should developers work on the alpha branch and once QA is ready to test then create a beta from the alpha.

Developers can continue developing in alpha.

QA can test beta

any problems found by QA can be fixed in BETA and merged back to alpha (to ensure devs are working with the latest)

Finally, QA signs off on the BETA, so we merge beta to alpha (to ensure devs have the latest) and then merge beta to master which releases a new NON beta/alpha product.

I suppose what I didn't fully understand and maybe I still don't, I thought NEXT could be used as the next version to be released (i.e. developers working on it) but as I say it does seem that NEXT wants to release >=2.0.0

My .releaserc file contains the following

```
{
  "branches": [
    "+([1-9])?(.{+([1-9]),x}).x",
    "master",
    "next",
    {
      "name": "alpha",
      "prerelease": true
    },
    {
      "name": "beta",
      "prerelease": true
    }
  ],
  "plugins": [
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    "@semantic-release/changelog",
    "@semantic-release/git",
    "@semantic-release/npm"
  ]
}
```

and my versions are 

```
    "@semantic-release/changelog": "^3.0.2",
    "@semantic-release/git": "^7.1.0-beta.3",
    "@semantic-release/npm": "^5.2.0-beta.6",
    "semantic-release": "^16.0.0-beta.18",
```

my current versions available are

```
[ '1.0.0',
  '1.0.1',
  '1.0.2',
  '1.0.3',
  '1.0.4',
  '1.0.5',
  '1.0.6',
  '1.1.0-alpha.1',
  '1.1.0-alpha.2',
  '1.1.0-alpha.3',
  '1.1.0',
  '1.1.1',
  '1.2.0',
  '1.2.1',
  '1.2.2-alpha.1',
  '1.2.2',
  '1.2.3-alpha.1',
  '1.2.3-alpha.2',
  '1.2.3-alpha.3',
  '1.3.0' ]
```

**Comment by pvdlg** [comment]
This is explain in this doc: https://github.com/semantic-release/semantic-release/blob/beta/docs/usage/workflow-configuration.md

Regarding your question about the `next` branch the TL;DR is:
- If you configure `master` + `next` then `next` expect to host the next major release
- If you configure `master` + `next` + `next-major` then `next` expect to host the next minor release

Regarding the other questions you should also find answers in the same doc. The general rule is that you branch have a certain order `master` < `next` < `next-major` < `beta` < `alpha` and the a new version released from a branch should always be strictly higher by one release type (`patch`, `minor`, `major`) than the last version released on the previous branch.

So if you have `master` + `next` + `next-major` and the last version released from `master` is `2.0.0` then the versions released from `next` should be `>=2.1.0` and `<3.0.0`.
