### ISSUE TITLE
No package.json push to GitHub

### ISSUE THREAD

**Issue by ffflorian** [semantic-release/semantic-release#1128]
## Current behavior

The new version is published to npm, the tag and the release are created but the updated `package.json` file was not commited and / or pushed to GitHub.

## Expected behavior

The updated `package.json` file should be commited and pushed to GitHub.

## Environment

- **semantic-release** version: 15.13.3
- CI environment: GitHub Actions
- Plugins used: default
- **semantic-release** configuration: 
  - https://github.com/ffflorian/gh-open/blob/master/.github/main.workflow?short_path=9618edd#L59
  - https://github.com/ffflorian/actions/blob/master/semantic-release/entrypoint.sh
- CI logs: https://github.com/ffflorian/gh-open/runs/76867616

**Comment by travi** [comment]
have you configured semantic-release beyond the defaults? see https://semantic-release.gitbook.io/semantic-release/support/faq#why-is-the-package-jsons-version-not-updated-in-my-repository

**Comment by ffflorian** [comment]
@travi
I am sorry, seems like I forgot to read the FAQ :slightly_frowning_face: 

Thank you for your help!
