### ISSUE TITLE
Disable repository tests in dry-run mode

### ISSUE THREAD

**Issue by plup** [semantic-release/semantic-release#1130]
## New feature motivation

In my option the local mode shouldn't contact anything out the local setup. It should just stay local.

## New feature description

I'm trying to run some tests on the commit parsing to prepare a workflow configuration. This is what I want to do:

```
# semantic-release -p '@semantic-release/commit-analyzer' -b master --dry-run
```
And I'm expecting it to show what version it bumps (and later, what release note it produces)

Instead I have ENOREPOURL and if I put a dummy URL I get EGITNOPERMISSION. 

The workaround is to setup a dummy repository somewhere, configure authentication to it and always have access to it when I'm playing with `semantic-release`. 

Not very convenient if you work in docker containers.

**Comment by pvdlg** [comment]
Closing for similar reason to https://github.com/semantic-release/semantic-release/issues/1168#issuecomment-501350821
