### ISSUE TITLE
Fails to install with NPM

### ISSUE THREAD

**Issue by dustinws** [semantic-release/semantic-release#115]
Hello,

I'm trying to install with npm, but the installation fails at node-gyp rebuild.
node v-4.1.2
node-gyp v-3.0.3
npm  v-2.14.6

Here's npm's output:
dustin@dustin-laptop:~/Desktop/RamenJS$ npm install -g semantic-release-cli
 
> keytar@3.0.0 install /home/dustin/.linuxbrew/lib/node_modules/semantic-release-cli/node_modules/keytar
> node-gyp rebuild
Package gnome-keyring-1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gnome-keyring-1.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gnome-keyring-1' found
gyp: Call to 'pkg-config --libs-only-l gnome-keyring-1' returned exit status 1. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/dustin/.linuxbrew/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:355:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.16.0-4-amd64
gyp ERR! command "/home/dustin/.linuxbrew/Cellar/node/4.1.2/bin/node" "/home/dustin/.linuxbrew/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/dustin/.linuxbrew/lib/node_modules/semantic-release-cli/node_modules/keytar
gyp ERR! node -v v4.1.2
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/home/dustin/.linuxbrew/Cellar/node/4.1.2/bin/node" "/home/dustin/.linuxbrew/bin/npm" "install" "-g" "semantic-release-cli"
npm ERR! node v4.1.2
npm ERR! npm  v2.14.6
npm ERR! code ELIFECYCLE

npm ERR! keytar@3.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the keytar@3.0.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the keytar package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls keytar
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/dustin/Desktop/RamenJS/npm-debug.log

The Debug log spit this out:
silly vacuum-fs quitting because other entries in /home/dustin/.linuxbrew/lib/node_modules

The full debug log is here.
https://gist.github.com/dustinws/f93ccc09d5dcba84f805

EDIT: I should also mention that my I'm running a Debian Jesse system.

I have a feeling this is a local system error, any thoughts?

**Comment by boennemann** [comment]
Hey,

thanks for the report. It don't know much about your system, but it seems like keytar is incompatible with it somehow. Maybe there is something on how to fix this in their issue tracker?

I think to prevent this from happening in the first place we should make keytar an optinal dependency of this CLI so people can continue using semantic-release even if there are some problems with the native extensions.

Please let me know if you find anything.

Best,
Stephan

**Comment by dustinws** [comment]
Hello, I haven't been able to get to the bottom of it, but I've narrowed it down to a system issue. It's safe to close this out, thanks!

**Comment by joefitzgerald** [comment]
@dustinws can you elaborate on what the system issue was? /cc @thomasjo

**Comment by thomasjo** [comment]
@joefitzgerald His system didn't have the gnome-keyring library installed;

> [..] Package gnome-keyring-1 was not found in the pkg-config search path [..]

**Comment by joefitzgerald** [comment]
Ahh, yes, thanks @thomasjo.

**Comment by heydemo** [comment]
Had to apt-get install libgnome-keyring-dev on ubuntu 14.04 to fix this

**Comment by dustinws** [comment]
Unfortunately that still didn't fix mine. It can't find the "gnome-keyring-1" package. I'm running Debian Jesse, so maybe I need a slightly different package? Will look in to it later tonight. Thanks!

**Comment by afirdousi** [comment]
What do Windows users do for a similar situation ? "gnome-keyring" is Linux based.

I have opened a similar issue [Issue 131](https://github.com/semantic-release/semantic-release/issues/131)

**Comment by Guria** [comment]
`apt-get install libgnome-keyring-dev` does not helps me as well.

**Comment by davincho** [comment]
In my case it helped. I am running Ubuntu 15.10 with Gnome 3.

**Comment by zkochan** [comment]
Would be nice to have a not about this issue in the **Setup** section until its fixed. I had the same issue, Ubuntu 15.10

**Comment by Rambou** [comment]
a solution is to install 
for Debian/Ubuntu
> sudo apt-get install libsecret-1-dev

in order to work. at least worked for me. Its a keytar problem so look this too https://github.com/atom/atom/issues/1948#issuecomment-42344415
