### ISSUE TITLE
No release triggered?

### ISSUE THREAD

**Issue by simlu** [semantic-release/semantic-release#1158]
I'm looking at the following ci workflow

https://circleci.com/gh/blackflux/lambda-serverless-api/2235

with the `.releaserc.json` file

https://github.com/blackflux/lambda-serverless-api/blob/master/.releaserc.json

it should have triggered a release. However it didn't?

Anyone knows what's going on? Did something change recently?

**Comment by dominykas** [comment]
I only scanned through this briefly, but it seems you only have merges, chore commits and unprefixed commits - none of those are meant to trigger a release?

**Comment by simlu** [comment]
@dominykas Wow, nicely spotted. Apparently dependabot uses [black magic](https://github.com/dependabot/feedback/issues/255#issuecomment-436574414) to determine the appropriate commit message. Closing this as it's not a problem with semantic-release.
