### ISSUE TITLE
Add refactor/build commits to release notes

### ISSUE THREAD

**Issue by rarkins** [semantic-release/semantic-release#1159]
## Current behavior

Semantic Release publishes patches on `refactor` and `build` as desired, but the Release Notes do not include such commits.

## Expected behavior

I'd like to configure my Semantic Release to document patch and build commits in release notes.

## Environment

- **semantic-release** version: 15.13.3
- CI environment: Travis
- Plugins used: none
- **semantic-release** configuration:

```json
  "release": {
    "branch": "master",
    "tagFormat": "${version}",
    "analyzeCommits": {
      "preset": "angular",
      "releaseRules": [
        {
          "type": "docs",
          "scope": "readme.md",
          "release": "patch"
        },
        {
          "type": "refactor",
          "release": "patch"
        },
        {
          "type": "build",
          "release": "patch"
        }
      ]
    }
  }
```

**Comment by travi** [comment]
i think you would need to configure the [release notes generator](https://github.com/semantic-release/release-notes-generator) as well

**Comment by rarkins** [comment]
I agree, but I could not find any example or direct documentation for achieving this so was hoping to get guidance here.

**Comment by travi** [comment]
i think the config you show above may be a legacy format. i believe the recommended way to configure these types of details is through [plugin configuration](https://semantic-release.gitbook.io/semantic-release/usage/plugins). The repo that I linked above shows an example of configuring the release-notes-generator as well as the commit-analyzer plugin like you are showing above, but with the plugin approach. 

Are there specific details that the plugin configuration docs and the release-notes-generator don't make clear? It would be best if the docs could get updated to clarify something that may need more detail.

**Comment by rarkins** [comment]
This seems to be the parser that is ultimately used, although I can't be sure: https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-commits-parser

Presumably it then uses this: https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-angular

An within there, I don't see a flexibility to change which "types" are included in changelogs.

**Comment by travi** [comment]
ah, sorry, i didnt realize that the ability to choose the types wasnt exposed directly from the conventional-commits-parser api. semantic-release can only make the things configurable that are exposed. 

it looks like the only option would be to provide your own custom preset. you could probably extend the [angular preset](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-angular) and extend from there.

**Comment by spmeesseman** [comment]
@rarkins Hi :)  i made a preset just for this functionality - spmeesseman/conventional-changelog-spm

**Comment by pvdlg** [comment]
What ends up in the changelog is determined by the [conventional-changelog](https://github.com/conventional-changelog/conventional-changelog) that you use (by default `conventional-changelog-angular`).
I don't think those allow to customize which type of commits are included in the changelog. You would have to implement your own preset to change that.
