### ISSUE TITLE
missing version field breaks install via git

### ISSUE THREAD

**Issue by ds82** [semantic-release/semantic-release#116]
You cannot install a npm package without a version field. Since there is no version field in the repo when using semantic-release, it is not possible to install packages from github/tags/branches/etc. IMHO thats a major drawback.

Sadly I have no immediate solution for this, but I would like to know what you think about it.

**Comment by boennemann** [comment]
Hey @ds82,

if you have development workflows that require a version number you can just put _something_ there, e.g. `"version": "0.0.0-development"`. During publish time the placeholder will be overridden anyway.

Best,
Stephan

**Comment by ds82** [comment]
Thanks for clearing that up! That should work for us.
