### ISSUE TITLE
prerelease using 15x

### ISSUE THREAD

**Issue by scottnath** [semantic-release/semantic-release#1160]
Is it possible to release a prerelease/beta version using version 15x of semantic-release?

I am trying to have releases from a branch (called `version-x`) that would then be a prerelease resulting in `my-module-v0.0.2-version-x`.

I've tried these settings:
npm script:
`semantic-release -b version-x -t my-module-v\\${version}-version-x`
in package.json:
```
  "publishConfig": {
    "registry": "https://enterprise.registry.com",
    "tag": "version-x"
  },
```

Is this possible in 15x versions before you added the `branches` functionality?

thanks,
Scott

**Comment by travi** [comment]
the v16 beta has been working quite well for me and has been pretty stable. v15 does not have the added functionality. i would recommend just using the beta if you need the new functionality

**Comment by scottnath** [comment]
agreed. Got it working today with 16x. closing issue. thanks
