### ISSUE TITLE
Question: how to know when a new release was created from cli

### ISSUE THREAD

**Issue by BotellaA** [semantic-release/semantic-release#1169]
I have a question. I would like to know when I run npx semantic-release, if a new release was created or not. The goal is to trigger (or not) the next job in a CI.

Thanks for your help

**Comment by pvdlg** [comment]
If you want to trigger a command when a release is made you should use the [@semantic-release/exec](https://github.com/semantic-release/exec) plugin to run that command.
You can set your command in the `success`  step.
