### ISSUE TITLE
Need help to resolve some issues

### ISSUE THREAD

**Issue by mdreizin** [semantic-release/semantic-release#117]
Could you please help me to understand why I have the following issues:

```
semantic-release ERR! pre Failed to determine new version.
semantic-release ERR! pre ENOCHANGE There are no relevant changes, so no new version is released.
```

Please see:

https://github.com/mdreizin/webpack-config
https://travis-ci.org/mdreizin/webpack-config/jobs/86988528

**Comment by boennemann** [comment]
Hey @mdreizin,

I couldn't find any logs like this in the Travis build you linked to. Looking at your releases it seems like it's working now.
Should you have any more questions please join our Gitter room.

Thanks for trying semantic-release,
Stephan

**Comment by mdreizin** [comment]
@boennemann Thanks a lot for your help. I migrated to https://github.com/alrra/travis-after-all. Not it works fine. Thanks again for `semantic-release`.
