### ISSUE TITLE
'latest' tag pointing to 15.13.3, not 15.13.12 -- intentional?

### ISSUE THREAD

**Issue by hermo** [semantic-release/semantic-release#1174]
I was updating dependencies for my project and was wondering why NPM installs an old version of semantic-release when running something like `npm i -D semantic-release`.
It looks like the 'latest' tag is not actually pointing to the latest release. Is this intentional or a misconfiguration?

## Current behavior

The ['latest' NPM tag](https://www.npmjs.com/package/semantic-release) for semantic-release points to 15.13.3, which was released 3 months ago.

The 'next' tag points to 15.13.12, which was released only 3 weeks ago and appears to be the most recent stable version. 

## Expected behavior

The 'latest' NPM tag should be pointing at the latest released version.

I don't know how the 'latest' tag ever gets updated as the [`publishConfig:tag` in package.json](https://github.com/semantic-release/semantic-release/blob/6b1938fd7e264ede0ef3f7edacf7dd1eea619514/package.json#L113) states releases should always be tagged 'next' and has done so for years.

## Environment

Tested with Node 10.15.3 and npm 6.4.1

**Comment by pvdlg** [comment]
The last v15 version is now on `@latest`
