### ISSUE TITLE
Custom exit code for neutral

### ISSUE THREAD

**Issue by gr2m** [semantic-release/semantic-release#1180]
## New feature motivation

I’m looking into making semantic-release work nicely with GitHub actions. If I create a workflow that runs an action depending on semantic-release, the action will run if semantic-release ends with message such as 

>  This test run was triggered on the branch semantic-release-workflow, while semantic-release is configured to only publish from master, therefore a new version won’t be published

—https://github.com/gr2m/github-npm-registry-test/runs/126757041

GitHub actions supports the neutral exit code 78:
https://developer.github.com/actions/creating-github-actions/accessing-the-runtime-environment/#exit-codes-and-statuses

## New feature description

It would be great if I could configure an option such as `neutralExitCode` which defaults to `0`

## New feature implementation

It would need to be implemented in the `semantic-release` core package

**Comment by knidarkness** [comment]
@pvdlg , do you think that would be useful for now? If so, I could take care about this.

**Comment by gr2m** [comment]
Just fyi, GitHub Actions no longer support the exit code 78, it might come back, but it's currently unclear

**Comment by knidarkness** [comment]
@gr2m , are there some publications about how probable is that it will return?

**Comment by gr2m** [comment]
> are there some publications about how probable is that it will return

No

**Comment by petermein** [comment]
It would be nice for other CI pipelines aswell, CircleCI for example. 
I work with a non destructieve image registry, so i can't create 2 images with the same tag. 
When building and pushing it would be nice to not build if the same image is created.

**Comment by pvdlg** [comment]
This use case (do something after a release is made) was intended to be implemented via the `success` step. You can easily run a script on `success` via `@semantic-release/exec`.

The `success` step will be called only a released was published successfully. The advantage is that you get all the information related to the release that was made passed to the script.

@gr2m is there a use case where using `@semantic-release/exec` on the `success` step wouldn't work? Or would be better implemented with a specific exit code?

**Comment by gr2m** [comment]
Not really. I think we can close this issue
