### ISSUE TITLE
Follow markdownlint for the changelog

### ISSUE THREAD

**Issue by micheelengronne** [semantic-release/semantic-release#1182]
## New feature motivation

The current changelog does not follow markdown lint rules according to https://github.com/markdownlint/markdownlint

## New feature description

Change the changelog generation to follow markdown rules.

**Comment by pvdlg** [comment]
We use [conventional-changelog](https://github.com/conventional-changelog/conventional-changelog) to generate the changelogs. We have no plan to move away from that library at the moment.

You can open an issue/PR in their repo or you can implement you own preset to generate the markdown format you want.
