### ISSUE TITLE
branches.range template support

### ISSUE THREAD

**Issue by bryanlarsen** [semantic-release/semantic-release#1190]
## New feature motivation

We use Jenkins-X for CI/CD which deploys branches to the web automatically.   So if I push branch "foo" to a service named "bar" configured in Jenkins-X environment for "example.dev", Jenkins-X automatically makes it available at http://foo.bar.example.dev/

Really cool, but that means that "foo" has to be a DNS compatible name; and "1.0.x" is not such.

## New feature description

Process branches[].range with a lodash template to map the name to the valid N.N.x or N.x format.   cf. how branches[].prerelease supports lodash templtes.

**Comment by pvdlg** [comment]
I'm sorry I don't understand what you are asking...
What does "deploys branches to the web" means??? It's extremely vague, please be specific.

What DNS names have to do with semantic-release? 

Is it even related to semantic-release at all?

**Comment by pvdlg** [comment]
Closing as no response was provided.
