### ISSUE TITLE
Allow to create annotated git tag

### ISSUE THREAD

**Issue by vibhanshuc** [semantic-release/semantic-release#1192]
## New feature motivation

I am utililizing [`git describe`](https://git-scm.com/docs/git-describe) to find out the latest tag somewhere in my project. 

> The command finds the most recent tag that is reachable from a commit. If the tag points to the commit, then only the tag is shown.

For example if last released [annotated git tag](https://git-scm.com/book/en/v2/Git-Basics-Tagging) is `v1.1.0` and it is also associated with latest commit, then running `git describe` will return `v1.1.0`. When other commits are made on top of `v1.1.0` then running `git describe` returns something like this `v1.1.0-42-g0888269` where `0888269` is short sha of latest commit.

At this point if we create a new annotated git tag `v1.2.0` the `git describe` returns `v1.2.0`, and if it  is non-annotated tag then `git describe` returns `v1.1.0-g0888269` which is not reflecting the correct latest tag.

Since, semantic-release doesn't allow to create annotated tag this way of getting latest tag using `git describe` is unusable.

## New feature description

It will  allow to create [annotated tags](https://git-scm.com/book/en/v2/Git-Basics-Tagging) rather than lightweight tags when a new release is created.

## New feature implementation

We would need to change the [`tag`](https://github.com/semantic-release/semantic-release/blob/master/lib/git.js#L138) function so that it creates `annotated tag`, something like this

``` javascript
async function tag(tagName, execaOpts) {
  await execa('git', ['tag', tagName, '-a', '-m', `release ${tagName}`], execaOpts);
}
```

Not sure if it impacts other things or any change in any of the plugings is required.

**Comment by gr2m** [comment]
I think tags on GitHub are currently created in https://github.com/semantic-release/github using the API, I’m not sure if what you need is supported.

Maybe it’s something you can implement using the [exec plugin](https://github.com/semantic-release/exec)?

**Comment by pvdlg** [comment]
The tags are created in the core.

For information you can achieve with `git describe --tags`. See https://git-scm.com/docs/git-describe#Documentation/git-describe.txt---tags.

The `--tags` makes lightweight tags to behave like annotated tags for the purpose of `git describe`.

I'm not against using annotated tags, however I don't know what would be the impact.
Is there any other reasons to use annotated tags?

**Comment by vibhanshuc** [comment]
@pvdlg Alright. Thanks, I think information that yuo have shared will solve my use case. However we can have a option of creating annotated tags if need be. Because by the definition of annotated tags, it seems a much better option to have them, instead of lightweight tags.

> Annotated tags, however, are stored as full objects in the Git database. They’re checksummed; contain the tagger name, email, and date; have a tagging message; and can be signed and verified with GNU Privacy Guard (GPG). It’s generally recommended that you create annotated tags so you can have all this information; but if you want a temporary tag or for some reason don’t want to keep the other information, lightweight tags are available too.

**Comment by travi** [comment]
i've seen information that gave me the impression that github might also interpret annotated tags in a way that populates the github release, but i havent found documentation to confirm that. if true, maybe it could be used to simplify how release notes are included in the release? also may want to confirm if it would conflict with the current github release notes approach if not changed.

**Comment by pvdlg** [comment]
@vibhanshuc can you test how GitHub release works with annotated tags? If you create and push an annotated, does that automatically create aa release? Does GitHub behave differently than with a regular tag?

**Comment by vibhanshuc** [comment]
@pvdlg Simply pushing annotated tags doesn't seem to create a new release on github. Though both lightweight and annotated tags show on the github release page like this. Only difference I could spot was the message written alongside tags. 

1. Lightweight tag - message is taken from the commit it points to.
1. Annotated tag - messages forwared to the git command used to create annotated tag. `git tag <tag_version> -a -m <message>"


![image](https://user-images.githubusercontent.com/3676895/59058488-60bffc00-88ba-11e9-80a6-942c7a806929.png)

One can then edit these tags, whether lightweight or annotated, from the github tags page and publish them as releases.

![image](https://user-images.githubusercontent.com/3676895/59058868-2a36b100-88bb-11e9-9b14-55736dc1c823.png)

**Comment by vibhanshuc** [comment]
@pvdlg After reading these, I think using annotated tags for releases is better idea. 

1. https://rem.co/blog/2015/02/12/git-the-difference-between-lightweight-and-annotated-tags/
1. https://stackoverflow.com/questions/4971746/why-should-i-care-about-lightweight-vs-annotated-tags/4971817#4971817

**Comment by pvdlg** [comment]
Fixed by #1203

I released that on beta as it might have unexpected impact.

**Comment by sirasistant** [comment]
Hi! We are running a project where we build our artifacts on tags created by semantic release. Recently we have updated our beta version to beta 22, and we have seen that our build pipeline was failing. With this change of lightweight tags to annotated tags, we no more can know the branch the tag was associated with: https://www.appveyor.com/docs/branches/#sharing-common-configuration-between-branches 

> However, please note that in the case of an annotated tag, branch and APPVEYOR_REPO_TAG are mutually exclusive. This is because, for a webhook created as a result of an annotated tag, there is no practical, reliable way to recognize which branch the tag was created from.

Is it possible for this feature be configurable, and by default use this annotated tags but allow to use lightweight tags?

**Comment by yoyoys** [comment]
@pvdlg is there any way to customize annoted tag description?
