### ISSUE TITLE
Make semantic-release compatible with GitHub Actions

### ISSUE THREAD

**Issue by gr2m** [semantic-release/semantic-release#1194]
## New feature motivation

[GitHub Actions](https://developer.github.com/actions/) come with a token out of the box: `GITHUB_TOKEN` (see [Environment variables](https://developer.github.com/actions/creating-github-actions/accessing-the-runtime-environment/#runtime-environment-resources)).

Unfortunately that token cannot be used to authenticate git commands, not directly anyway. 

I want semantic-release to work out-of-the box with GitHub Actions. Especially in combination with GitHub’s new npm registry, this would remove the need to create any tokens by hand.

## New feature description

With a personal access token, this is possible:

```
git push https://${TOKEN}@github.com/gr2m/sandbox.git
```

But the `GITHUB_TOKEN` provided to GitHub actions is internally not a private access token, but a GitHub App installation token (🤷‍♂)

But there is a way, by prefixing it with `x-access-token` (mentioned [somewhere deep in GitHub’s developer documentation](https://developer.github.com/apps/quickstart-guides/creating-ci-tests-with-the-checks-api/#step-22-cloning-the-repository)).

So this _does_ work, but only with installation tokens

```
git push https://x-access-token:${TOKEN}@github.com/gr2m/sandbox.git
```

Installation tokens can be easily identified, they have a `v1.` prefix, so we could add a check like this

```
if (/^v1\./.test(TOKEN)) {
  // use "https://x-access-token:${TOKEN}@github.com/gr2m/sandbox.git" schema
}
```

Alternatively we can check for an [environmental variable that is always set in a GitHub Action](https://developer.github.com/actions/creating-github-actions/accessing-the-runtime-environment/#environment-variables), such as `GITHUB_ACTION`

## New feature implementation

I think the change would need to be implemented in `lib/get-git-auth-url.js`

https://github.com/semantic-release/semantic-release/blob/bcf3a853f2ad988a34edca0f484bd7df07d3c7ac/lib/get-git-auth-url.js#L46-L54

Instead of returning `auth: gitCredentials`, we could add an additional check if `gitCredentials` is a GitHub App installation access token, in which case we prefix it with `x-access-token:`

**Comment by pvdlg** [comment]
We already have something in place to add a token prefix:
https://github.com/semantic-release/semantic-release/blob/7e824b2c1831d3e0226cdaa5caf4533d99e34693/lib/get-git-auth-url.js#L6-L14

Would personal tokens works with the `x-access-token:`? If `git push https://x-access-token:${PERSONAL_TOKEN}@github.com/gr2m/sandbox.git` works then we could just add `x-access-token:` to every `GH_TOKEN` and `GITHUB_TOKEN`:
```js
const GIT_TOKENS = {
  GIT_CREDENTIALS: undefined,
  GH_TOKEN: 'x-access-token:',
  GITHUB_TOKEN: 'x-access-token:',
  GL_TOKEN: 'gitlab-ci-token:',
  GITLAB_TOKEN: 'gitlab-ci-token:',
  BB_TOKEN: 'x-token-auth:',
  BITBUCKET_TOKEN: 'x-token-auth:',
};
```

Otherwise we can move `GIT_TOKENS` inside the main function (to have to `env`) and do something like:
```js
const GIT_TOKENS = {
  GIT_CREDENTIALS: undefined,
  GH_TOKEN: isNil(env. GITHUB_ACTION) ? undefined : 'x-access-token:',
  GITHUB_TOKEN: isNil(env. GITHUB_ACTION) ? undefined : 'x-access-token:',
  GL_TOKEN: 'gitlab-ci-token:',
  GITLAB_TOKEN: 'gitlab-ci-token:',
  BB_TOKEN: 'x-token-auth:',
  BITBUCKET_TOKEN: 'x-token-auth:',
};
```

**Comment by gr2m** [comment]
Would that work to set the auth prefix to `x-access-token:` only if `GITHUB_ACTION` env variable is set?

```js
const GIT_TOKENS = {
  // ...
  GITHUB_ACTION: 'x-access-token:',
};
```

**Comment by pvdlg** [comment]
In the `GIT_TOKENS` object, the keys are used to access the value of the environment variables to which we add the prefix.
So if `GITHUB_ACTION` is set to `true`  you would end with `git push https://x-access-token:true@github.com/gr2m/sandbox.git`.

To add `x-access-token:` only if `GITHUB_ACTION` is set and not `false` you'd have to do that:
```js
const GIT_TOKENS = {
  GIT_CREDENTIALS: undefined,
  GH_TOKEN: isNil(env. GITHUB_ACTION) ? undefined : 'x-access-token:',
  GITHUB_TOKEN: isNil(env. GITHUB_ACTION) ? undefined : 'x-access-token:',
  GL_TOKEN: 'gitlab-ci-token:',
  GITLAB_TOKEN: 'gitlab-ci-token:',
  BB_TOKEN: 'x-token-auth:',
  BITBUCKET_TOKEN: 'x-token-auth:',
};
```
For info the `x-access-token:` is also mentioned here:
https://developer.github.com/apps/building-github-apps/authenticating-with-github-apps/#http-based-git-access-by-an-installation

**Comment by gr2m** [comment]
got it, thanks! The workaround is not necessary for `GH_TOKEN`, only for `GITHUB_TOKEN`. That should work 👍 I’ll start a PR and will try it out in my test setup at https://github.com/gr2m/github-npm-registry-test

**Comment by mkotsollaris** [comment]
I tried integrating via github actions but I am having troubles (opened issue with details here: https://github.com/semantic-release/semantic-release/issues/1333)
