### ISSUE TITLE
Docs: label default plugins

### ISSUE THREAD

**Issue by joh-klein** [semantic-release/semantic-release#1195]
Is there a reason why you [state in the docs ](https://github.com/semantic-release/semantic-release/blob/master/docs/usage/plugins.md#plugins-configuration )that one has to install e. g. `@semantic-release/commit-analyzer` even though it [is a dependency of semantic-release](https://github.com/semantic-release/semantic-release/blob/master/package.json#L22) itself?

As far as I can see, all of these plugins
```
"@semantic-release/commit-analyzer"	
"@semantic-release/error"	
"@semantic-release/github"	
"@semantic-release/npm"	
"@semantic-release/release-notes-generator"
```
could be labeled in the docs as default plugins that don't have to be installed separately. Or am I missing something?

**Comment by gr2m** [comment]
I agree, I don’t think these default plugins need to be installed, this might still be a relict from previous npm 2? 

I think we can update the docs, explaining that these default plugins are always available, but that additional plugins have to be installed and probably configured.

Can you get a pull request going?

**Comment by joh-klein** [comment]
Sure, I could give it a go. But I am rather unsure where to put it. My first thought was either to divide the [official plugins list](https://github.com/semantic-release/semantic-release/blob/master/docs/extending/plugins-list.md#official-plugins) into "Default (part of semantic-release)" and "Additional" – but does that make sense to newcomers? Or a little bit simpler: add a "Note: this is already part of the semantic-release package and does not have to be installed separately" underneath each of the default plugins, like so:

``` (md)
- [@semantic-release/github](https://github.com/semantic-release/github)
  - Note: this is already part of the semantic-release package and does not have to be installed separately
  - `verifyConditions`: Verify the presence and the validity of the GitHub authentication and release configuration
  - `publish`: Publish a [GitHub release](https://help.github.com/articles/about-releases)
  - `success`: Add a comment to GitHub issues and pull requests resolved in the release
  - `fail`: Open a GitHub issue when a release fails
```

Any remarks?

**Comment by gr2m** [comment]
Yeah adding the note sounds good to me. This is not set in stone, we can improve it with yet another PR if we come up with something better. But your suggestion is better than what we have today so let’s roll with it :)
