### ISSUE TITLE
Allow to set custom cwd

### ISSUE THREAD

**Issue by gr2m** [semantic-release/semantic-release#1205]
## New feature motivation

I want to run `semantic-release` in a subdirectory in GitHub Actions, without the need of creating a new Dockerfile.

Here is an example in action:
https://github.com/gr2m/deprecation/blob/master/.github/main.workflow?short_path=4be5c08#L30-L32

It is using the code from the [gr2m-actions-test branch](https://github.com/semantic-release/semantic-release/compare/gr2m-actions-test).

There is no way to `cd` into a directory (that I could find). I wish GitHub Actions would support a cwd setting, but they don’t, and there is no intent of implementing that.

I know this is an edge case, but I run out of ideas for workarounds, and the required change would be minimal.

## New feature description

Add `cwd` as a new configuration options that can be set everywhere e.g. `branch` can be set.

## New feature implementation

`cwd` is set internally on context and pass around throughout the code. A change would need to happen only in a single place:

https://github.com/semantic-release/semantic-release/blob/4ed62139778bebc705cce549c7534fd1ad1c17d3/index.js#L156

If `options.cwd` is set, `context.cwd` would be set to `options.cwd`

**Comment by pvdlg** [comment]
What's the reason to run from a subdirectory?

Be aware that the npm publish command will be run from that subdirectory as well, so you need all the stuff you want to publish in there.
You also need to have your `package.json` in that subdirectory for semantic-release to read its config.

**Comment by gr2m** [comment]
> What's the reason to run from a subdirectory?

Sorry, forgot to mention. I use [`@pika/pack`](https://github.com/pikapkg/pack) for building the Octokit libraries. It creates a `pkg/` folder with its own `package.json` file. Publish has to be run from this folder

```
pkg/
├── LICENSE
├── README.md
├── dist-node
│   └── index.js
├── dist-src
│   └── index.js
├── dist-types
│   └── index.d.ts
├── dist-web
│   └── index.js
└── package.json
```

> You also need to have your package.json in that subdirectory for semantic-release to read its config.

That’s a good point. I don’t have config at this point, but if I had, I could easily enough create a plugin for `@pika/build` which copies the configuration over into the `pkg/` folder

**Comment by pvdlg** [comment]
We have the [`pkgRoot` option](https://github.com/semantic-release/npm#options) in the `@semantic-release/npm` plugin for those cases.
It allows you to run semantic-release from your project root (and read the config in the root `package.json`) but run all the npm related commands from the subdirectory.

Would that cover your use case?

I don't think there is anything else (other than npm commands) that semantic-release does that cares about the current directory, but I might miss something.

**Comment by gr2m** [comment]
That was exactly what I was looking for, it works like a charm 👍
