### ISSUE TITLE
[prerelease] Custom branch and suffix 

### ISSUE THREAD

**Issue by naerion89** [semantic-release/semantic-release#1209]
Hi,

Is it possible to use custom branch and custom suffix for prerelease ? 

I use this git worklfow with a mono repository (java projects and angular projects )

Features branches merge on develop and develop branch merge to master

- I want to prerelease beta version when i push to develop
- I want to release version when i push to master

Ex : 

| Develop | Master  |
|--|--|
| 1.0.0.beta.1 |  |
| 1.0.0.beta.2 |  |
| 1.0.0.beta.3 |  |
| 1.0.0.beta.4 |  |
| | 1.0.0 |

Regards

**Comment by travi** [comment]
the beta version of semantic-release supports prerelease flows. take a look at the [docs for release branches](https://github.com/semantic-release/semantic-release/blob/beta/docs/usage/configuration.md#branches) in the beta branch to understand if it would handle your case.
