### ISSUE TITLE
can add '--no-verify' option in function verifyAuth of git.js file

### ISSUE THREAD

**Issue by xuyouxin** [semantic-release/semantic-release#1210]
When run the function verifyAuth of git.js file, it's very showly because our project has some mechanism(include some check, even trigger some test) when execute 'git push' command, it will be better add '--no-verify' option in function verifyAuth of git.js file.

The function push of git.js has the same problem.

- **semantic-release** version: 15.12.3

**Comment by pvdlg** [comment]
Not sure we want to do that....
There is probably other users who might not want to disable their git hooks even for semantic-release.

semantic-release will run on your CI to make releases which happens in an automated way, so the duration of the process is not so much of a concern. A few more minutes shouldn't make that much difference?

I'm also reluctant to add an option as we try to keep the configuration and documentation as simple as possible.

So unless it's a problem bigger than what I think or if there is a significant number of users who face the same problem, I'm don't think we'll make the suggested change at that point.

**Comment by pvdlg** [comment]
Closing as no answer provied
