### ISSUE TITLE
Include Pull-Request link into release notes

### ISSUE THREAD

**Issue by AndyOGo** [semantic-release/semantic-release#1211]
First, thanks for this awesome tool.

## New feature motivation

We would like to have easy and fast access to our **Merged Pull-Requests** by looking at the change log.

## New feature description

It would be nice to have:

- [ ] Parse and keep track of Merge Commits
- [ ] Link to Pull-Requests within release notes (resolved from related Merge Commits)
- [ ] Group all changes by their associated Pull-Requests within release notes

**Example:**

> `v1.0.0`
>
> # PR `feature/pr-branch` [#1234](https://github.com/foo/pull/1234)
>
> ## Feature
>  - list all feature commits here
>
> ## Bugfix
>  - list all bugfix commits here
>
> # PR `bugfix/pr-branch` [#5678](https://github.com/foo/pull/5678)
>
> ## Feature
>  - list all feature commits here
>
> ## Bugfix
>  - list all bugfix commits here
>

**Comment by gr2m** [comment]
You can implement custom release descriptions with a plugin, see https://semantic-release.gitbook.io/semantic-release/usage/plugins

**Comment by AndyOGo** [comment]
@gr2m thank you for your quick answer.

I really like the plug-able design, though I the Plugin's dev section seems to be empty?
https://semantic-release.gitbook.io/semantic-release/developer-guide/plugin

**Comment by pvdlg** [comment]
The release notes are generated by [@semantic-release/release-notes-generator](https://github.com/semantic-release/release-notes-generator) which use [conventional-changelog](https://github.com/conventional-changelog/conventional-changelog).
By default [conventional-changelog](https://github.com/conventional-changelog/conventional-changelog) produce a changelog with only informations access from the commits.

If you want to include other information, that you have to retrieve from GitHub for example, you have to create a plugin  similar to [@semantic-release/release-notes-generator](https://github.com/semantic-release/release-notes-generator).

**Comment by gr2m** [comment]
I think we can close this issue? Feel free to comment if you have further issues
