### ISSUE TITLE
Add the availability to filter commits on a sub path of the repository

### ISSUE THREAD

**Issue by jBouyoud** [semantic-release/semantic-release#1212]
## New feature motivation

With particular repository structure like this : 
```
/    | src  (that must be taken in account when releasing)
     | other stuff (that must NOT taken in account when releasing)
``` 
All commits are take in account but I'd like to take only commits that impact `src` folder.

Or with a monorepo structure : 
```
/    | pkg1
     | pkg2
```
When I run `cd pkg1 && semantic-release --tagPrefix=pkg1` or independently the same command on pkg2, all commits are take in account. 
I'd like to filter those commit to only one subpackage (at a time)

## New feature description

Add an option to be able to run semantic-release to a sub path (or a list of sub path) in the released git repository.

## New feature implementation

Add a configuration option in main semantic release configuration (or an environment variable), to be able to configure a list of subpath where semantic-release will works on.
This could be a cli option like `--gitSubPaths` or global configuration file key `gitSubPaths: []`
or a specific environment variable.

When retrieving commits to inject into the release pipeline (https://github.com/semantic-release/semantic-release/blob/master/lib/get-commits.js#L21), handle this new option by forwarding it to the git command (https://stackoverflow.com/questions/16343659/how-to-show-git-log-history-for-a-sub-directory-of-a-git-repo) 

Maybe with something like : 
```
const subPathOption = gitSubPaths.length == 0  ? '' : ` -- ${gitSubPaths.join(' ')}`;
const commits = (await getStream.array(
    gitLogParser.parse({_: `${gitHead ? gitHead + '..' : ''}HEAD${subPathOption}`}, {cwd, env: {...process.env, ...env}})
  ))
...
```

**Comment by pvdlg** [comment]
Monorepo are currently not supported. If we support we want to support every cases that can occur in a monorepo. Simply filtering commits that impact a sub directory won't cover every case.
See #193 for more details.

Regarding your first example (with `src`), if you follow a commit convention, which is a semantic-release requirement, all the commits that warrant a release should impact your sources.
By default `fix`, `feat`, `perf` and `BREAKING CHANGE` trigger a release. Those type of commits should impact your sources. Other commits that doesn't impact should be a `chore` or a `build`. Those will not trigger a release.
