### ISSUE TITLE
Unable to generate version number for use in Azure DevOps pipeline

### ISSUE THREAD

**Issue by McRegt** [semantic-release/semantic-release#1218]
## Current behavior

I am trying to create a version number based on the commit messages. To accomplish this I am using the semantic-release-ado to set the version in a variable for use later on in the ADO pipeline.

I am running into the issue where the npm token and github token are required.

![image](https://user-images.githubusercontent.com/6177851/60118930-9baca580-977d-11e9-9840-c2caae8b3233.png)

## Expected behavior

I have tried the --dry-run mode, but as described in other tickets it's in there for a reason and cannot be turned off. However, that is a problem in this scenario, as my repository is not located on GitHub and should not be published to either GitHub or NPM. I just want the version to be provided in a variable for use later on in the pipeline.

## Environment

- **semantic-release** version: 15.13.16
- CI environment: Azure DevOps Pipeline
- Plugins used: semantic-release-ado
- **semantic-release** configuration: 

``` json
{
  "name": "ProjectX",
  "lockfileVersion": 1,
  "config": {
    "commitizen": {
      "path": "./node_modules/cz-conventional-changelog",
      "maxHeaderWidth": 100,
      "maxLineWidth": 100,
      "defaultType": "",
      "defaultScope": "",
      "defaultSubject": "",
      "defaultBody": "",
      "defaultIssues": ""
    }
  },
  "devDependencies": {
    "cz-conventional-changelog": "^2.1.0"
  },
  "dependencies": {
    "semantic-release": "^15.13.16",
    "semantic-release-ado": "^1.0.2"
  }
}
```

- CI logs: see screenshot above.

**Comment by gr2m** [comment]
If you don’t want to publish to github/npm then you can disable these plugins.

It's documented in the readme of the ado plugin:
https://github.com/lluchmk/semantic-release-ado#usage

**Comment by McRegt** [comment]
Ah, it wasn't immediately clear that the default plugins are overwritten when defining custom ones.
I see this has also been [merged right after](https://github.com/semantic-release/semantic-release/pull/1216/commits/641021f87998761f0828b3154506ac9549ab4eaa). Thanks for the information, I can continue not defining the plugins solves the issue.
