### ISSUE TITLE
Add issue references to release notes

### ISSUE THREAD

**Issue by khaledosman** [semantic-release/semantic-release#1220]
## New feature motivation
According to conventional commits, or commitizen cli, you can add references to issues/tickets in the commit message's footer as follows:
```

    fix: add ticket prefix to commitlint

    REF-123

```

In my case I want to add Jira ticket references to the commits pushed to bitbucket and be able to see links to them in the generated changelog for each commit.

However when I run semantic-release with the default settings for the release-notes-generator, it doesn't include the references/issues to the generated changelog/release-notes even though they're part of the commit

## New feature description

There should be an option like a boolean flag, in release-notes-generator plugin that can add references to the generated release-notes similar to links to commit messages

**Comment by pvdlg** [comment]
The release note content is created by [@semantic-release/release-notes-generator](https://github.com/semantic-release/release-notes-generator) which wraps [conventional-changelog](https://github.com/conventional-changelog/conventional-changelog).

If you want to create a different release note you would have to implement your own [conventional-changelog](https://github.com/conventional-changelog/conventional-changelog) preset and configure semantic-release to use it with the [`preset` option](https://github.com/semantic-release/release-notes-generator#options).

**Comment by khaledosman** [comment]
hmm, thanks. I'll check it out

**Comment by lennertVanSever** [comment]
What worked for me is the following snippet

```JSON
"plugins": [
      "@semantic-release/commit-analyzer",
      [
        "@semantic-release/release-notes-generator",
        {
          "preset": "conventionalcommits",
          "presetConfig": {
            "issuePrefixes": ["TPD", "OS"],
            "commitUrlFormat": "{{host}}/{{owner}}/{{repository}}/commits/{{hash}}",
            "compareUrlFormat": "{{host}}/{{owner}}/{{repository}}/compare/{{currentTag}}%0D{{previousTag}}#diff",
            "issueUrlFormat": "https://<fill in jira host here>.atlassian.net/browse/{{prefix}}{{id}}"
          }
        }
      ],
```
The values in issuePrefixes should match your Jira project keys. If you then commit

```
feat: my new feature

Refs OS-18
```

it will correctly reference your Jira issue

**Comment by matifriaz** [comment]
I have tried this but it's not working. I am not sure why.

**Comment by SalahAdDin** [comment]
> ```json
> @semantic-release/release-notes-generator
> ```

Is there any big difference between `conventionalcommits` and `angular` presets?
