### ISSUE TITLE
Add specific types in release note without launching a new release

### ISSUE THREAD

**Issue by panquez** [semantic-release/semantic-release#1238]
## Current behavior

Angular types like "docs" "build" "test" either do not appear in release note and do not trigger a release, or appear in the release notes of the release thay have triggered. 

## Expected behavior

I would like to use some types (e.g. docs and test) in commit messages to reference them in the release notes but i do not know these types launch a new release. By consequence, these types only be added in the release notes of next release triggered by other types (as "feat" or "fix").

## Environment

I try this in my .releaserc configuration file

```{
  "plugins": [
    '@semantic-release/commit-analyzer', {
      "preset": "angular",
      "releaseRules": [
        {"type": "refactor", "release": false},
        {"type": "docs", "release": false},
        {"type": "tests", "release": false}
      ],
      "parserOpts": {
        "noteKeywords": ["BREAKING CHANGE", "BREAKING CHANGES"]
      }
    },
    '@semantic-release/release-notes-generator', 
    '@semantic-release/github', 
    'semantic-release-ado'
  ]
}
```

"release" : false -> no release done, but "docs", "test", and "refactor" types are not added in release note.

Thanks for your help.

**Comment by travi** [comment]
from a [previous issue comment](https://github.com/semantic-release/semantic-release/issues/1159#issuecomment-499977786):
> What ends up in the changelog is determined by the [conventional-changelog](https://github.com/conventional-changelog/conventional-changelog) that you use (by default `conventional-changelog-angular`).
I don't think those allow to customize which type of commits are included in the changelog. You would have to implement your own preset to change that.

**Comment by pvdlg** [comment]
See https://github.com/semantic-release/semantic-release/issues/1238#issuecomment-512284778

There is nothing we can as long as we use `conventional-changelog`. We don't plan to move away from it at that point.
