### ISSUE TITLE
Peer dependencies warning: marked-terminal requires marked@^0.4.0 || ^0.5.0 || ^0.6.0

### ISSUE THREAD

**Issue by ZebraFlesh** [semantic-release/semantic-release#1244]
Similar to #905 but this now crops up in semantic-release 15.13.19. Try the following:

1. Remove semantic-release: `npm uninstall semantic-release`
2. Validate marked and marked-terminal are not present: `npm ls marked marked-terminal`
3. `npm install --save-dev semantic-release@15.13.19`
4. Observe this warning `npm WARN marked-terminal@3.2.0 requires a peer of marked@^0.4.0 || ^0.5.0 || ^0.6.0 but none is installed. You must install peer dependencies yourself.`

Looking at node_modules/semantic-release/package.json, I see the following: `"marked": "^0.7.0",`

**Comment by gr2m** [comment]
Hmm marked was updated via https://github.com/semantic-release/semantic-release/pull/1234. Looks like there is a pending PR for marked-terminal: https://github.com/mikaelbr/marked-terminal/pull/54

The PR didn't require any code changes, so it should work just fine and you can ignore the warning.

**Comment by pvdlg** [comment]
The message doesn't appear anymore as the PR on `marked-terminal` was merged and released.

**Comment by G-Rath** [comment]
This warning is back again, as we're now up to `marked@0.8.0` - `marked-terminal@4` has been released supporting this version, but `semantic-release` is still using `marked-terminal@3`.
