### ISSUE TITLE
Doc for package managers and releases missing

### ISSUE THREAD

**Issue by esciara** [semantic-release/semantic-release#1245]
## Current behavior

Documentation about [package managers and languages](https://semantic-release.gitbook.io/semantic-release/recipes/recipes-2#package-managers-and-languages) is empty.

## Expected behavior

Having a list of what is available, whether officially or through the community.

## Environment

- **semantic-release** version: 15.13.19
- CI environment: N/A
- Plugins used: N/A
- **semantic-release** configuration: N/A
- CI logs: N/A

I might be able to help with #653, but not sure where to find the info. There is a [list of plugins](https://semantic-release.gitbook.io/semantic-release/extending/plugins-list) page in the doc, but cannot be sure whether it is complete, or where other community plugin could be found.

Maybe this issue could be a place to centralise the information that could be added in a PR?

**Comment by gr2m** [comment]
I'm not sure what @pvdlg had in mind for this page. Thanks for opening the issue though so we can start a conversation on it. I'd be very pragmatic, even little info is better than what we have now :)

**Comment by esciara** [comment]
Thanks for this reply. I started a little cleanup in the mean time #1246 . :blush:

**Comment by pvdlg** [comment]
Closing as #1246 was merged
