### ISSUE TITLE
docs: `gitbook serve .` does not necessarily display end result

### ISSUE THREAD

**Issue by esciara** [semantic-release/semantic-release#1250]
## Current behavior

Numbered list not rendered properly. See screenshot of a `gitbook.io` site:
<img width="763" alt="Screenshot 2019-08-01 at 06 48 37" src="https://user-images.githubusercontent.com/1336689/62266396-71a76c80-b428-11e9-84da-1f2e27c8baf2.png">

## Expected behavior

Properly rendered numbered list, as tested locally with `gitbook serve .`. See screenshot:

<img width="804" alt="Screenshot 2019-08-01 at 06 50 59" src="https://user-images.githubusercontent.com/1336689/62266484-c3e88d80-b428-11e9-8d0a-9d4a52c626ef.png">

## Environment

- **semantic-release** version: N/A
- CI environment: N/A
- Plugins used: N/A
- **semantic-release** configuration: N/A
- CI logs: N/A

**Comment by esciara** [comment]
Goops... forgot to ping @gr2m . 😄

**Comment by gr2m** [comment]
I don't know gitbook very well. I'll add a help wanted label, if you or someone else want to look into that, we'd appreciate it

**Comment by esciara** [comment]
Had a quick look, and could not find tricks about templates... Will try a fix, but can't test it locally. Suggest to accept it and see whether it fixes the issue.
