### ISSUE TITLE
Version issue in release 15.13.21

### ISSUE THREAD

**Issue by gempain** [semantic-release/semantic-release#1259]
Hello,

Yesterday evening, version **15.13.21** of `semantic-release` was released and published to NPM and we were able to upgrade without issue:
![Screen Shot 2019-08-13 at 09 37 58](https://user-images.githubusercontent.com/13135149/62923653-7c5dec00-bdae-11e9-8381-bc2d69ce6ba5.png)

This morning, the NPM registry is showing latest version as **15.13.19**:
![Screen Shot 2019-08-13 at 09 36 26](https://user-images.githubusercontent.com/13135149/62923530-3f91f500-bdae-11e9-8292-adcda3380414.png)

I swear I had the previous version installed on almost all my projects:
![Screen Shot 2019-08-13 at 09 36 07](https://user-images.githubusercontent.com/13135149/62923601-651efe80-bdae-11e9-9ece-32f1d52f86ee.png)

What's going on ?

Keep up the great work !

**Comment by gempain** [comment]
I can confirm that installing from NPM at this time gives you version **15.13.19**.
![Screen Shot 2019-08-13 at 09 53 39](https://user-images.githubusercontent.com/13135149/62924420-5df8f000-bdb0-11e9-94db-f15f28d780aa.png)

**Comment by travi** [comment]
```
$ npm dist-tags ls semantic-release
alpaca: 3.4.1
badger: 4.3.5
beta: 16.0.0-beta.22
latest: 15.13.19
next: 15.13.21
```

looks like the latest badge is incorrect on github, but looking at the dist-tags on npm shows that 15.13.21 is not tagged as `latest` there, but instead released under the `next` dist-tag. 

you can install using `npm install semantic-release@next` if you want to use that version before it is promoted to `latest`

**Comment by gempain** [comment]
@travi good to know. Thanks for the explanation !

**Comment by travi** [comment]
@pvdlg is the incorrect "latest" tag in github a case of https://github.com/semantic-release/semantic-release/issues/1221?

**Comment by pvdlg** [comment]
Published on `@latest`
