### ISSUE TITLE
Annotated tags break issues workflow on some CIs

### ISSUE THREAD

**Issue by pvdlg** [semantic-release/semantic-release#1262]
Hi! We are running a project where we build our artifacts on tags created by semantic release. Recently we have updated our beta version to beta 22, and we have seen that our build pipeline was failing. With this change of lightweight tags to annotated tags, we no more can know the branch the tag was associated with: https://www.appveyor.com/docs/branches/#sharing-common-configuration-between-branches 

> However, please note that in the case of an annotated tag, branch and APPVEYOR_REPO_TAG are mutually exclusive. This is because, for a webhook created as a result of an annotated tag, there is no practical, reliable way to recognize which branch the tag was created from.

Is it possible for this feature be configurable, and by default use this annotated tags but allow to use lightweight tags?

_Originally posted by @sirasistant in https://github.com/semantic-release/semantic-release/issues/1192#issuecomment-506263912_

**Comment by pvdlg** [comment]
Considering to revert #1203

**Comment by pvdlg** [comment]
Revert during merge from master to beta

**Comment by DanySK** [comment]
Please consider PR #1203, as annotated tags are required in some workflows.

**Comment by gr2m** [comment]
Can you file a new issue? 

We did merge #1203 but had to revert it as it broke other use cases. If you want to get it merged, we need to do the following

1. Create a pull request which adds a test for @sirasistant use case, making sure we don't break it in future. That would be great to have anyway, and we should merge a test like this independently
2. Create a new pull request adding annotated tags without breaking the test added in `1.`
