### ISSUE TITLE
Package.json not uploaded with git plugin

### ISSUE THREAD

**Issue by semoal** [semantic-release/semantic-release#1265]
## Current behavior

Actually, the git plugin is doing a commit on the branch, with only the changelog changed.

## Expected behavior

The git plugin should push the package.json with the version updated

## Environment

- **semantic-release** version: ^16.0.0-beta.22
- CI environment: gitlab
- Plugins used: 

```js
module.exports = {
  branches: [
    'master',
    {
      name: 'canary',
      prerelease: true
    }
  ],
  plugins: [
    '@semantic-release/commit-analyzer',
    '@semantic-release/release-notes-generator',
    '@semantic-release/changelog',
    [
      '@semantic-release/npm',
      {
        npmPublish: true,
        pkgRoot: 'package'
      }
    ],
    {
      path: '@semantic-release/git',
      assets: ['package.json', 'CHANGELOG.md'],
      // eslint-disable-next-line no-template-curly-in-string
      message: 'chore(release): ${nextRelease.version} [skip ci]nn${nextRelease.notes}'
    }
  ]
};

```

**Comment by pvdlg** [comment]
You configured `@semantic-release/npm` to update the `package.json` in the directory `package` and `@semantic-release/git` to commit the one in the project root.

**Comment by semoal** [comment]
But the `/package` folder is the compiled library, that contains a "dirty" package.json (distributable package.json).

Am i wrong?

**Comment by pvdlg** [comment]
I can't answer a question about the specificity of your project.
I'm just saying that what you see is expected considering your configuration. You have a plugin updating a `package.json` and you try to commit another one.

**Comment by semoal** [comment]
Probably the proper solution is: 
```
module.exports = {
  branches: [
    'master',
    {
      name: 'canary',
      prerelease: true
    }
  ],
  plugins: [
    '@semantic-release/commit-analyzer',
    '@semantic-release/release-notes-generator',
    '@semantic-release/changelog',
[
      '@semantic-release/npm',
      {
        npmPublish: false
 }
    ],
[
      '@semantic-release/npm',
      {
        npmPublish: true,
        pkgRoot: 'package'
      }
    ],
    {
      path: '@semantic-release/git',
      assets: ['package.json', 'CHANGELOG.md'],
      // eslint-disable-next-line no-template-curly-in-string
      message: 'chore(release): ${nextRelease.version} [skip ci]nn${nextRelease.notes}'
    }
  ]
};
```

One for updating the main project package on a commitable way (just update version number), 
and one for publishing making the distribuitable form in (package folder)

**Comment by pvdlg** [comment]
See https://github.com/semantic-release/npm#examples

**Comment by semoal** [comment]
Oh, nice one!
Didn't see that option. I'll give it a try

Thanks in advance Pierre!
