### ISSUE TITLE
Publish not in npm?

### ISSUE THREAD

**Issue by lapanoid** [semantic-release/semantic-release#127]
I want to make continues delivery with react-native android, so don't need npm at all, is it possible to hook this and generalize somehow?

**Comment by lapanoid** [comment]
If it is complicated, I can workaround it by publishing something lightweight (just package.json) and then do my graddle-android publishing stuff. But I don't now how to hook when semantic release successfully finished. @boennemann can you guide me here?

**Comment by boennemann** [comment]
Hey @lapanoid,

this is possible by implementing an alternative ["getLastRelease"](https://github.com/semantic-release/semantic-release#getlastrelease) plugin. You could base it on git tags to fully decouple semantic-release from npm.

Best,
Stephan

https://github.com/semantic-release/semantic-release/issues/56
