### ISSUE TITLE
Plugin options are not recognised on windows 

### ISSUE THREAD

**Issue by AndyOGo** [semantic-release/semantic-release#1270]
## Current behavior

Running `npx semantic-release --verify-conditions false --verify-release false --generate-notes false --prepare false --publish false --analyze-commits @semantic-release/commit-analyzer --dry-run` does not disable any step on Windows (except `--dry-run` seems to be working)

![Windows-disabling-sematic-release-plugins-not-working](https://user-images.githubusercontent.com/914443/63259460-c1869000-c27e-11e9-9da1-17dd3433b15f.png)

## Expected behavior

Running `npx semantic-release --verify-conditions false --verify-release false --generate-notes false --prepare false --publish false --analyze-commits @semantic-release/commit-analyzer --dry-run` should work the same as on UNIX systems like MacOS:

<img width="1275" alt="Screenshot 2019-08-19 at 12 40 14" src="https://user-images.githubusercontent.com/914443/63259400-8d12d400-c27e-11e9-9895-79fb41f6c4a7.png">

## Environment

- **semantic-release** version: `15.13.21`
- CI environment: None, running locally in dev environment
- Plugins used: `@semantic-release/commit-analyzer` (only default plugins)
- **semantic-release** configuration: None, just CLI options
- CI logs: None

**Comment by pvdlg** [comment]
According to your screenshot your two commands are different.
On the Windows one you `--generate-notespublish` which seems a typo.
On the Mac one you have `--prepare false` which you don't have on the windows one.

As far as I can tell semantic-release works as expected on both case.

**Comment by AndyOGo** [comment]
@pvdlg Thanks for your answer, you are right. Sorry for the inaccuracy, I will double check this tomorrow on a windows machine.

**Comment by AndyOGo** [comment]
@pvdlg Sorry for the wrong bug report. This works as expected.

![windows-disabled-plugins](https://user-images.githubusercontent.com/914443/63342019-c749a780-c34a-11e9-9a04-87121db09862.png)
