### ISSUE TITLE
Disabling verify steps still verifies git permissions and throws EGITNOPERMISSION

### ISSUE THREAD

**Issue by AndyOGo** [semantic-release/semantic-release#1271]
## Current behavior

Running `npx semantic-release --verify-conditions false --verify-release false --generate-notes false --prepare false --publish false --analyze-commits @semantic-release/commit-analyzer --dry-run` still verifies git permission and throws **EGITNOPERMISSION** even though this should be part of the **verify-conditions** plugin.

Reason we do this is, that we just want to get next version for coverage reporting.

This is currently hard coded in:
https://github.com/semantic-release/semantic-release/blob/1eb302545e3ed16044cb0533430d39ce0eeed9e2/index.js#L62-L78

CLI output:
```sh
npx semantic-release --verify-conditions false --verify-release false --generate-notes false --prepare false --publish false --analyze-commits @semantic-release/commit-analyzer --dry-run
npx: installed 736 in 12.398s
[12:39:47 PM] [semantic-release] › ℹ  Running semantic-release version 15.13.21
[12:39:47 PM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[12:39:47 PM] [semantic-release] › ⚠  Run automated release from branch master in dry-run mode
[12:39:50 PM] [semantic-release] › ✖  The command "git push --dry-run https://github.com/axa-ch/ui-render-standalone.git HEAD:master" failed with the error message remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/axa-ch/ui-render-standalone.git/'
.
[12:39:50 PM] [semantic-release] › ✖  EGITNOPERMISSION The push permission to the Git repository is required.
semantic-release cannot push the version tag to the branch master on remote Git repository with URL https://github.com/axa-ch/ui-render-standalone.git.

Please refer to the authentication configuration documentation to configure the Git credentials on your CI environment and make sure the repositoryUrl is configured with a valid Git URL.

{ SemanticReleaseError: The push permission to the Git repository is required.
    at module.exports (/Users/axawinterthur/.npm/_npx/3537/lib/node_modules/semantic-release/lib/get-error.js:6:10)
    at run (/Users/axawinterthur/.npm/_npx/3537/lib/node_modules/semantic-release/index.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  name: 'SemanticReleaseError',
  code: 'EGITNOPERMISSION',
  details:
   '**semantic-release** cannot push the version tag to the branch `master` on remote Git repository with URL `https://github.com/axa-ch/ui-render-standalone.git`.\n\nPlease refer to the [authentication configuration documentation](https://github.com/semantic-release/semantic-release/blob/master/docs/usage/ci-configuration.md#authentication) to configure the Git credentials on your CI environment and make sure the [repositoryUrl](https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#repositoryurl) is configured with a [valid Git URL](https://git-scm.com/book/en/v2/Git-on-the-Server-The-Protocols).'
```

## Expected behavior

Verification should only happen if needed and only implemented within a plugin by using the verifyCondition hook as documented here: https://semantic-release.gitbook.io/semantic-release/usage/plugins#plugins-implement-actions-for-release-steps

## Environment

- **semantic-release** version: `15.13.21`
- CI environment: None, tested locally
- Plugins used: `@semantic-release/commit-analyzer`
- **semantic-release** configuration: none, see cli arguments above
- CI logs: None, see local logs above

**Comment by pvdlg** [comment]
This is done this way on purpose. semantic-release need those permission to run.

It seems you need to get the next version but it's not really clear why.
This is a feature that has already been requested in #753. Please add a comment there with your detailed use case.

**Comment by AndyOGo** [comment]
@pvdlg Thanks you for your answer and sorry for the duplicate.

The reason we need it is for coverage reports, which we want to tag with the next version and send it to [sonarqube by setting `sonar.projectVersion` within `sonar-project.properties` file](https://docs.sonarqube.org/latest/analysis/scan/sonarscanner/).

**Comment by bblanke** [comment]
I'd still love to see this feature implemented. My use case is that:
- I build "test" releases in merge requests so developers can test their code before merging to our "next" branch.
- To build a release, I need to compute a version number before building. After building, I don't want to release it (i.e. make a tag + gitlab release)
- In merge requests, I have access to a readonly GITLAB_TOKEN - it does not allow push access, because I don't want tags to be accidentally pushed from merge requests

It'd be really ideal if semantic-release could use the readonly GITLAB_TOKEN to read the repo, determine the version that would be released if the branch were to be merged, and completely skip the check to see if the tag could actually be pushed.
