### ISSUE TITLE
Question: Hooking in and executing script after changelog generation and before publish to npm/git

### ISSUE THREAD

**Issue by Disane87** [semantic-release/semantic-release#1278]
For an angular lib I need to move the `CHANGELOG.md` to a subfolder `./dist/project` but I need to move them before the publish.

Is there any possibility to hooking in? I studied the docs but I can't discover this.

**Comment by pvdlg** [comment]
See https://semantic-release.gitbook.io/semantic-release/support/faq#how-can-i-use-a-npm-build-script-that-requires-the-package-jsons-version

You can do that in a `prepublishOnly` script
