### ISSUE TITLE
Add Path Filter for Analyzed Commits

### ISSUE THREAD

**Issue by DanielHabenicht** [semantic-release/semantic-release#1279]
## New feature motivation
We have a folder with an app in our repo which should be released semantically but as all commits written in the repo follow commitizen guidelines other commits do also trigger a release even if nothing changed in the app folder. 

Also, this might be the first step to semantic release supporting monorepos.

## New feature description
Add a configuration option to define a path that should be included (or narrowed down) for commit analyzation. 
Example: 
```jsonc
// releaserc.json
{
  "scopeToPath": "./path"
}
```

## New feature implementation
Just pass the option to the git-log-parser and add an option: 
```javascript
//get-commits.js
 gitLogParser.parse({_: [`${gitHead ? gitHead + '..' : ''}HEAD`, '--', './path/to/get/analyzed']}, {cwd, env: {...process.env, ...env}})
```
There are certain edge cases: 
1. If implemented the default value can't be `./`, as in conjunction with `cwd` the analyzed commits in a subfolder would be different. That means **no path should be set** by default. 

Please write back what you think about it and how the option should be named. I implement it afterwards. 🚀

**Comment by pvdlg** [comment]
I don't think we would implement that.

You mention that you have commits that trigger a release even though they don't modify your app. 
That seems contrary to any commit convention. By default in semantic-release (the Angular convention is the default) only `fix`, `feat` and `perf` commit triggers a release. If a commit doesn't modify your app it shouldn't be a `fix`, a `feat` or a `perf`.

**Comment by DanielHabenicht** [comment]
As I said I think that's the first step for making semantic release usable for monorepos. 

Of course, only `fix`, `feat` and `perf` should be used for changes that will trigger a release and vice versa for changes that should not trigger a release. But I am not committing against the convention: 

I have two apps in one repo which are living right beside one another: 
```
📦 MyRepo
 ┣ 📂app1
 ┣ 📂app2
```
Each app is released individually but with the current `semantic-release` version a commit which changes files in the folder of `app1` will also trigger a release for `app2` because `semantic-release` does not distinguish between the folder it is executed in (**only for commit analyzation**, I do know that it has a `cwd` setting for execution). 
So what I end up with are two apps which do get released if either of one gets a commit. 
Maybe you want to reconsider?

**Comment by DanielHabenicht** [comment]
@pvdlg I think we talked past another. I want to make semantic-release filter the commits for a specific folder, as they do not modify the version of `app1` but the version of `app2`.
