### ISSUE TITLE
Allow plugins to be individually run in dry mode.

### ISSUE THREAD

**Issue by AndrewLeedham** [semantic-release/semantic-release#1282]
## New feature motivation

I would like to be able to create a slack message via semantic-release-slack-bot when in dry-mode with the current release-notes. The idea being this would run for dev/stage branches, but would not literally update the CHANGELOG.MD or create a GitHub tag unless on master.

## New feature description

The user would be able to pass a dryRun option to plugins, which would allow them to be run on a case-by-case basis. Obviously this would be false by default, and turning it on would be at the users own risk.

## New feature implementation

To implement this I would imagine a third OR statement would need to be added [here](https://github.com/semantic-release/semantic-release/blob/448a0ff977fda5ad44c96571367f60e6fcdee73a/lib/plugins/normalize.js#L32) in order to check the plugin options as well as step type and overall options.

**Comment by pvdlg** [comment]
The dry-run feature is used to make sure everything is configured properly before running a release on the CI. What you suggest is quite different and would create a lot of confusion as you would have 2 dry-run feature doing different things.

It seems what you are asking is to have different plugins running on different branches.

That's not something we would implement. It would considerably complexity the codebase and would only solve very edge cases.

I'm not sure there is way to implement such feature without systematically creating issues on the repo. That would for example for example publish some release with a changelog and some without, depending from where they were published. Worst, you would end up with some release with an updated changelog and some other with an outdated one.

**Comment by AndrewLeedham** [comment]
Ok fair enough.

An alternate solution I thought of was having different release configs that are run on different branches, so the logic would be handled user-end. But I don't seem to be able to stop the analyse-commits/release-notes-generator plugins from creating tags etc.

**Comment by BeyondEvil** [comment]
> Ok fair enough.
> 
> An alternate solution I thought of was having different release configs that are run on different branches, so the logic would be handled user-end. But I don't seem to be able to stop the analyse-commits/release-notes-generator plugins from creating tags etc. Is that possible @pvdlg ?

I would love to have this as well!

**Comment by BeyondEvil** [comment]
@AndrewLeedham I've solved this for our project.

Here's how I did it:

`develop` branch is used for Stage releases.

<details>
<summary> Stage config (`.releaserc.stage.json`)</summary>
```json
{
    "branch": "develop",
    "preset": "eslint",
    "plugins": [
        "@semantic-release/commit-analyzer",
        [
            "@semantic-release/release-notes-generator",
            {
                "linkCompare": false,
                "writerOpts": {
                    "headerPartial": "{{#if isPatch}}##{{else}}#{{/if}} {{#if @root.linkCompare}}[Stage]({{@root.host}}/{{#if @root.owner}}{{@root.owner}}/{{/if}}{{@root.repository}}/compare/{{previousTag}}...{{currentTag}}){{else}}Stage{{/if}}{{#if title}} \"{{title}}\"{{/if}}{{#if date}} ({{date}}){{/if}}"
                }
            }
        ],
        "@semantic-release/changelog",
        [
            "@semantic-release/git",
            {
                "message": "chore(release): ${nextRelease.gitTag} [skip ci]\n\n${nextRelease.notes}"
            }
        ],
        [
            "@semantic-release/github", 
            {
                "successComment": false
            }
        ],
        [
            "semantic-release-slack-bot",
            {
                "notifyOnSuccess": true,
                "markdownReleaseNotes": true,
                "onSuccessTemplate": {
                    "text": "Updates to $package_name has been released to *Stage*!\n\n$release_notes"
                }
            }
        ]
    ]
}
```
</details>

`master` branch is used for Prod releases.

<details>
<summary> Prod config (`.releaserc.prod.json`)</summary>

```json
{
    "branch": "master",
    "preset": "eslint",
    "plugins": [
        "@semantic-release/commit-analyzer",
        "@semantic-release/release-notes-generator",
        "@semantic-release/changelog",
        "@semantic-release/git",
        "@semantic-release/github",
        [
            "semantic-release-slack-bot",
            {
                "notifyOnSuccess": true,
                "markdownReleaseNotes": true
            }
        ]
    ]
}
```

</details>

In CI, when a PR is merged to `develop`, we rename `.releaserc.stage.json` to `.releaserc.json` and then run `semantic-release --tag-format 'stage-v${version}'`

Because we provide our own `headerPartial` and `onSuccessTemplate` the release notes only mentions "Stage" and not anything about a version.

When we later merge `develop` into `master`, again CI renames the file (this time the prod-file) and then runs `semantic-release` (note without `--tag-format`)

If you want to skip having the changelog generated just remove that plugin from the config.

The way semantic-release works, in the way it handles tags, all the changes from "stage"-tags that happen between two "real" tags, gets picked up by the release notes.

Feel free to AMA if something is unclear.
