### ISSUE TITLE
When using `fix`, `feat`, `perf`, include commit body message.

### ISSUE THREAD

**Issue by rodoabad** [semantic-release/semantic-release#1283]
## New feature motivation

Sometimes, we want to give a more detailed explanation about the new feature we're releasing or about the bug we're fixing.

## New feature description

If any releasable prefix (probably not just `feat`, `fix`, `perf`) has a commit body, include it as part of the release notes.

**Comment by gr2m** [comment]
I would like that, too. It can be done with a plugin.

**Comment by pvdlg** [comment]
The release notes are done by https://github.com/semantic-release/release-notes-generator which internally uses https://github.com/conventional-changelog/conventional-changelog.

The default preset doesn't include the commit body in the changelog but you can create another (or modify an existing one) to add that.
