### ISSUE TITLE
what's the deal with v15.13.24? (revert, revert, revert...)

### ISSUE THREAD

**Issue by wmhilton** [semantic-release/semantic-release#1285]
I'm a little nervous to upgrade to the latest version of semantic-release, should I be worried?

![image](https://user-images.githubusercontent.com/587740/64479396-9c51b700-d184-11e9-9988-aa13b41432bf.png)

https://github.com/semantic-release/semantic-release/releases/tag/v15.13.24

**Comment by robcresswell** [comment]
@wmhilton It looks like those are all docs?

**Comment by gr2m** [comment]
> Should I be worried?

no 😄
