### ISSUE TITLE
Ignore plugin version tag in release config

### ISSUE THREAD

**Issue by DanielHabenicht** [semantic-release/semantic-release#1286]
## Current behavior

If using this config: 
```jsonc
{
    "branch": "master",
    "verifyConditions": [
        "@semantic-release/changelog@3.0.4",
        "@semantic-release/github"
    ],
    "verifyConfig": [
        "@semantic-release/github"
    ],
    "prepare": [
        {
            "path": "@semantic-release/changelog",
            "changelogFile": "src/changelog.md"
        }
    ],
    "publish": [
        {
            "path": "@semantic-release/exec",
            "cmd": "echo ##vso[build.addbuildtag]release"
        },
        {
            "path": "@semantic-release/github",
            "assets": [
                {
                    "path": "src/changelog.md",
                    "label": "Changelog"
                }
            ]
        }
    ],
    "fail": [
        "@semantic-release/github"
    ],
    "success": [
        "@semantic-release/github"
    ],
    "plugins": [
        [
            "@semantic-release/commit-analyzer"
        ],
        "@semantic-release/release-notes-generator"
    ]
}
```

This error is thrown (of course I installed the plugin before): 
```bash
[1:18:16 PM] [semantic-release] » ×  An error occurred while running semantic-release: { Error: Cannot find module '@semantic-release/changelog@3.0.4'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at resolveFileName (d:\a\_tasks\freestyle_87a45e6c-a243-455c-861d-37404e26212d\0.0.29\node_modules\resolve-from\index.js:29:39)
    at resolveFrom (d:\a\_tasks\freestyle_87a45e6c-a243-455c-861d-37404e26212d\0.0.29\node_modules\resolve-from\index.js:43:9)
    at module.exports (d:\a\_tasks\freestyle_87a45e6c-a243-455c-861d-37404e26212d\0.0.29\node_modules\resolve-from\index.js:46:47)
    at loadPlugin (d:\a\_tasks\freestyle_87a45e6c-a243-455c-861d-37404e26212d\0.0.29\node_modules\semantic-release\lib\plugins\utils.js:51:82)
    at module.exports (d:\a\_tasks\freestyle_87a45e6c-a243-455c-861d-37404e26212d\0.0.29\node_modules\semantic-release\lib\plugins\normalize.js:16:18)
    at castArray.map.pluginOpt (d:\a\_tasks\freestyle_87a45e6c-a243-455c-861d-37404e26212d\0.0.29\node_modules\semantic-release\lib\plugins\index.js:70:9)
    at Array.map (<anonymous>)
##[error]Cannot find module '@semantic-release/changelog@3.0.4'
```

## Expected behavior
 
Semantic-release should:
 1) ignore the version tag or
 2) check if the installed version is the one specified

I am for the first way as it is easier. 

Maybe you are asking yourself: Why the heck are you specifying a version number?
I want to use the `.releaserc` as only needed file for releasing something with semantic release (no package.json) nothing else. 

## Environment

- **semantic-release** version: 7.3.0
- CI environment: Azure Pipelines
You can see the log here: https://dev.azure.com/DanielHabenicht/test/_build/results?buildId=1497&view=logs&j=275f1d19-1bd8-5591-b06b-07d489ea915a

**Comment by pvdlg** [comment]
We won't implement such feature. We use plugins which mean you are responsible for installing those and choose the version you want. Adding an additional check won't change that.

The plugin are distributed as npm package and they must be made available by you before semantic-release runs. semantic-release has no way to install for you.

If you don't want to specify semantic-release in your `package.json` then use a global installation for both semantic-release and the plugins: https://github.com/semantic-release/semantic-release/blob/master/docs/usage/installation.md#global-installation

Also your config is probably wrong.`verifyConditions`, `prepare`, `publish`,  `fail`, `success` are deprecated and `verifyConfig` doesn't exists.
You should use only `plugins` to configure your plugins as explained in the doc.

**Comment by DanielHabenicht** [comment]
I do know that installing plugins is out of scope for `semantic release` and I don't want it to install them for me. 

But it is not out of scope for other tools that might just want to use the plugins specified in the `.releaserc` to install them before executing `semantic-release` (e.g. globally). Specifying a version right in the config would be a huge benefit, as there would be only a single source of truth. (No `package.json`, no scripts installing a pre-defined version of the plugin). 

How about just ignoring the version number?

PS: Thanks for the info about the config, it's really old as I've been using semantic release for a quite a while now and really like it. I've updated the example but the problem described still persists, `semantic-release` tries to match the whole plugin name to the path, instead of just the one without the version number.
