### ISSUE TITLE
Write a semantic-version-genversion plugin to generate module.version property

### ISSUE THREAD

**Issue by axelpale** [semantic-release/semantic-release#1288]
## New plugin motivation

A user [asked me](https://github.com/axelpale/genversion/issues/4) how to integrate [genversion](https://github.com/axelpale/genversion) with semantic-release.

Genversion is simple tool that adds `.version` property to a package without baking the package's whole package.json into the package's bundle. This is critical for client-side bundles as package.json might contain sensitive server-side configurations. The explicit version property helps in debugging e.g. to detect cache issues and to find out which version causes the problem.

Currently, semantic-release and genversion seems to be incompatible. The generation of the version property must be done after semantic-release figures out the new version but before the package is released to npm or bundled with webpack or similar.

Therefore I am now looking into building a plugin `semantic-release-genversion`. However, I wonder if the philosophy between semantic-release and genversion are too different for such plugin to exist.

I would love to hear your insightful opinion. 

## Third-party documentation

- [genversion](https://github.com/axelpale/genversion)
- [Discussion on benefits and caveats](https://stackoverflow.com/questions/9153571/is-there-a-way-to-get-version-from-package-json-in-nodejs-code) of importing version from package.json and [my answer](https://stackoverflow.com/a/46582508/638546).

Genversion API:
- [genversion.check(targetPath, callback)](https://github.com/axelpale/genversion#genversionchecktargetpath-callback)
- [genversion.generate(targetPath, opts, callback)](https://github.com/axelpale/genversion#genversiongeneratetargetpath-opts-callback)

**Comment by pvdlg** [comment]
Maybe instead of a plugin you could just call genversion in a `prepublishOnly` npm script, this way it would be called after semantic-release update the `package.json` with the new version and before the publish.

See https://github.com/semantic-release/semantic-release/blob/master/docs/support/FAQ.md#how-can-i-use-a-npm-build-script-that-requires-the-packagejsons-version-

**Comment by axelpale** [comment]
Ah, thanks for the tip! I believe this solves the original problem.
