### ISSUE TITLE
Invalid registry when using environment variables in npmrc

### ISSUE THREAD

**Issue by avizcaino** [semantic-release/semantic-release#1290]
## Current behavior
We have some sensitive information in our `.npmrc` file and need to make some repos public, so we decided to use environment variables there:

```
registry=${NEXUS_REGISTRY}
_auth=${REGISTRY_TOKEN}
```

This is working properly since it is installing packages published in this private registry in our projects. But when trying to publish the package to this private regisr
```
npm WARN invalid config registry="${NEXUS_REGISTRY}"
npm WARN invalid config Must be a full url with 'http://'
```
```
npm ERR! 400 Bad Request - PUT ***@ics-etc@fapi***
```

## Expected behavior
`semantic-release` should be able to publish to private registry regardless the environment variables defined in `.npmrc`.

## Environment
- **semantic-release** version: 16.0.0-beta.24
- CI environment: Github actions
- Plugins used: ---
- **semantic-release** configuration: 
```
{
  "branches": [
    "+([1-9])?(.{+([1-9]),x}).x",
    "master",
    "next",
    "next-major",
    { "name": "beta", "prerelease": true },
    { "name": "alpha", "prerelease": true }
  ]
}
```
- CI logs: 
```
npm WARN invalid config registry="${NEXUS_REGISTRY}"
npm WARN invalid config Must be a full url with 'http://'
```
```
npm ERR! 400 Bad Request - PUT ***@ics-etc@fapi***
```

**Comment by pvdlg** [comment]
Your NPM token should be configured in a variable named `NPM_TOKEN`. semantic-release will take care adding it to your `.npmrc` while releasing from the CI. See https://github.com/semantic-release/npm#environment-variables

According to the logs you provided there is something that add `registry="${NEXUS_REGISTRY}"` to your .npmrc and `NEXUS_REGISTRY` doesn't contains a valid URL. It's not semantic-release adding that.
The only thing semantic-release add temporarily to your .npmrc is `_auth` with the value from  `NPM_TOKEN`.

**Comment by avizcaino** [comment]
Sorry, I've made an error while copying the log in the description. `REGISTRY_URL` should be `NEXUS_REGISTRY`. I've already corrected that on the issue's description.

Also, after changing `REGISTRY_TOKEN` to `NPM_TOKEN`, the error is still the same...

But my main question (sorry for not explaining myself properly) is about the invalid URL: this URL has a server's IP that I don't want to make public in my public repos, is there a way to build that registry URL through environment variables?

**Comment by pvdlg** [comment]
It seems it's not related to semantic-release and probably due to a misconfiguration somewhere.
sematnic-release adds the `_auth` based on the variable `NPM_TOKEN` and then runs the `npm` CLI. So the registry config is completely managed by npm, not by semantic-release.

I tested that the following works locally:
```
$ export MY_REGISTRY=http://my-registry.com
$ echo 'registry=${MY_REGISTRY}' >> ~/.npmrc
$ npm config get registry

>> http://my-registry.com
```

So I'm guessing you have a problem with your `REGISTRY_URL` or `NEXUS_REGISTRY` config.

**Comment by avizcaino** [comment]
Couldn't find the problem yet... `npmrc` is built correctly but it seems that is unable to get registry's url properly.

I'll try to test it properly next week.

Thanks anyway.

**Comment by pvdlg** [comment]
I'm going to close this issue as it doesn't seems related to semantic-release.
Feel free to comment further here and to re-open if you think it's actually a bug in semantic-release.
