### ISSUE TITLE
Clarify EGITNOPERMISSION message to mention possible erroneous URL or server down

### ISSUE THREAD

**Issue by esciara** [semantic-release/semantic-release#1291]
When running `npx semantic-release --branch my_branch --repository-url http://my.gitlab.domain/my_group/my_repo.git --no-ci` while the server is down, or when the repo URL is wrong, `@semantic-release/gitlab` always throws a `EGITNOPERMISSION` error, which is erronous and can be confusing.

Here is an example:
```
[..]

[12:00:28 PM] [semantic-release] › ✖  The command "git ls-remote --heads origin master_scenario_at_16_17_45_252584" failed with the error message fatal: unable to access 'http://gitlab.my.localhost/esciara/autorelease-test-repo-2019-08-30.git/': Failed to connect to gitlab.my.localhost port 80: Connection refused
.
[12:00:28 PM] [semantic-release] › ✖  EGITNOPERMISSION The push permission to the Git repository is required.
semantic-release cannot push the version tag to the branch master_scenario_at_16_17_45_252584 on remote Git repository with URL http://gitlab-ci-token:[secure]@gitlab.my.localhost/esciara/autorelease-test-repo-2019-08-304.git.

Please refer to the authentication configuration documentation to configure the Git credentials on your CI environment and make sure the repositoryUrl is configured with a valid Git URL.

SemanticReleaseError: The push permission to the Git repository is required.
    at module.exports (/path/node_modules/semantic-release/lib/get-error.js:6:10)
    at run (/path/node_modules/semantic-release/index.js:77:11)
    at processTicksAndRejections (internal/process/task_queues.js:85:5) {
  name: 'SemanticReleaseError',
  code: 'EGITNOPERMISSION',
  details: '**semantic-release** cannot push the version tag to the branch `master_scenario_at_16_17_45_252584` on remote Git repository with URL `http://gitlab-ci-token:[secure]@gitlab.my.localhost/esciara/autorelease-test-repo-2019-08-304.git`.\n' +
    '\n' +
    'Please refer to the [authentication configuration documentation](https://github.com/semantic-release/semantic-release/blob/master/docs/usage/ci-configuration.md#authentication) to configure the Git credentials on your CI environment and make sure the [repositoryUrl](https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#repositoryurl) is configured with a [valid Git URL](https://git-scm.com/book/en/v2/Git-on-the-Server-The-Protocols).',
  semanticRelease: true
}
```

Is there any way to have the status checked before throwing this error? There are other instance when it is thrown, and the problem is not a permission problem. Not knowledgeable enough for a solution.

**Comment by knidarkness** [comment]
@pvdlg, I could take care of this issue by changing https://github.com/semantic-release/semantic-release/blob/5986bf920ef84d03fe9fd3efd00cc28a3a42d30b/lib/git.js#L121. I would add check in 'catch' block and distinct between errors. Is that fine?

**Comment by pvdlg** [comment]
How are you going to distinguish between those errors?

**Comment by knidarkness** [comment]
Ouch, misunderstood the problem cause. Right, we don't know difference between cases for wrong permissions & non-existent repo or server downtime. Actually I believe it's impossible due to security reasons.

Then, we could really just update the message in 
https://github.com/semantic-release/semantic-release/blob/6f33c76fde9639c8098e95aba205edddce9441f0/lib/definitions/errors.js#L29

as only available fix for now.

**Comment by esciara** [comment]
> We verify we have access to the Git repo using the `git` CLI by calling `git push --dry-run <repo url> HEAD:<branch>`.
> Unfortunately the error code returned by this command is the same whether the error is due to lack of permission or an invalid URL or a server down.

Since it is a gitlab plugin, why not use the gitlab API to verify that? For instance when I do a :
```
curl --header "Private-Token: <any_fake_token_here>" http://gitlab.example.com/api/v4/projects
```
I get the following message in return:
```
{"message":"401 Unauthorized"}
```
If the server is down, I get a timeout.
If the URL is invalid, I get an unresolved host or a 404 Not Found.
