### ISSUE TITLE
HEAD:undefined ( Could not push )

### ISSUE THREAD

**Issue by hashim-sohail** [semantic-release/semantic-release#1293]
Running semantic-releae in github actions workflow, fails at @semantic-release/git where the head is undefined

Command 
`npx semantic-release@beta`

Package Versions
```
    "@iteratec/semantic-release-bitbucket": "^1.1.1",
    "@semantic-release/changelog": "^3.0.4",
    "@semantic-release/commit-analyzer": "^6.2.0",
    "@semantic-release/exec": "^3.3.3",
    "@semantic-release/git": "^7.1.0-beta.3",
    "@semantic-release/npm": "^5.1.9",
    "@semantic-release/release-notes-generator": "^7.2.0",
```

Error
![Semantic Release Error](https://user-images.githubusercontent.com/22448789/65409283-c223c080-de00-11e9-97a2-b97c0663d25e.png)

**Comment by pvdlg** [comment]
Can you provide the full logs? If possible after running semantic-release with the `--debug` option? Thanks.

**Comment by gr2m** [comment]
@hashim-sohail make sure you check out your repository code using this step first

```
- uses: actions/checkout@master
```

Here is my workflow for reference: https://github.com/octokit/rest.js/blob/master/.github/workflows/release.yml

**Comment by hashim-sohail** [comment]
@pvdlg It was resolved, it was an issue with the conflicting versions of `@semantic-release/git`

**Comment by UziTech** [comment]
@hashim-sohail could you post how you solved it? I seem to have the same issue.

**Comment by UziTech** [comment]
For me it turns out updating `@semantic-release/apm-config` to v7.0.0 fixed it.
