### ISSUE TITLE
`feat(Col): add option for order-*` should trigger release but There are no relevant changes, so no new version is released.

### ISSUE THREAD

**Issue by kopax** [semantic-release/semantic-release#1303]
# There are no relevant change, so no new version is released

I have merged a commit with `feat(Col): add option for order-*` and I expect it should have triggered a release but instead: `There are no relevant changes, so no new version is released.`

## Result

- PR `dev` to `master` (release): https://github.com/bootstrap-styled/v4/pull/163
- Original fork `dev` to `dev`: https://github.com/bootstrap-styled/v4/pull/162
- Build-CI : https://travis-ci.org/bootstrap-styled/v4/jobs/593417335

It does not trigger a tag

## Expected

It should have tagged `3.1.2` (https://github.com/bootstrap-styled/v4/releases)

## Versions

- semantic-release: `15.13.24`
 - @semantic-release/changelog: `3.0.4`
 - @semantic-release/git: `7.0.16`
 - @semantic-release/github: `5.4.3`
 - @semantic-release/npm: `5.1.15`

**Comment by gr2m** [comment]
You merged the pull request, but you didn't squash the commit to update the commit message. The commit history in your main branch does not show the `feat(Col): ...` commit: https://github.com/bootstrap-styled/v4/commits/master

You can fix this by pushing an empty commit

```
git commit --allow-empty -m "feat(Col): add option for order-*"
git push
```

**Comment by travi** [comment]
when you merged it, did you do a normal merge, or a squash. the logs clearly show that [three commits were analyzed](https://travis-ci.org/bootstrap-styled/v4/jobs/593417335#L569-L578) and none of those three have the message shown above. if history is rewritten as part of the merge in such a way that semantic-release doesn't see the message, it wouldn't influence the published version.

**Comment by kopax** [comment]
Thanks for that command I didn't know it. I am very glad to know it now. I'll do it thanks!

**Comment by gr2m** [comment]
I'll close the issue as I'm fairly sure this will resolve your problem, but please comment and reopen the issue if it does not
