### ISSUE TITLE
Beta branch deployed to @latest tag

### ISSUE THREAD

**Issue by travis-w** [semantic-release/semantic-release#1304]
## Current behavior

Semantic release recently pushed a beta version of my project (beta branch) to the latest tag on npm. It recognized it was coming from the beta branch when running and even named it accordingly, however, it published to the wrong tag.

## Expected behavior

Should deploy to @beta tag on npm. Beta.22 deployed correctly previously.

## Environment

- **semantic-release** version: 16.0.0-beta.24
- CI environment: travis-ci
- Plugins used: 
- **semantic-release** configuration: https://github.com/travis-w/hijacker/tree/beta (default config)
- CI logs: https://travis-ci.org/travis-w/hijacker/jobs/593370791

**Comment by travis-w** [comment]
After some digging around, my guess is that this happened because of the update to @semantic-release/npm yesterday. Since that published as 5.2.0, semantic-release beta used that instead of 5.2.0-beta that contains the functionality to deploy to dist-tags.

https://github.com/semantic-release/npm/blob/v5.2.0/lib/publish.js#L20;L21
https://github.com/semantic-release/npm/blob/v5.2.0-beta.9%40beta/lib/publish.js#L22;L23

**Comment by pvdlg** [comment]
Should be fixed in v16.0.0-beta.25

**Comment by travis-w** [comment]
Working as expected. Thanks for the quick fix!
