### ISSUE TITLE
Incorrect last release on pre-release 

### ISSUE THREAD

**Issue by pvdlg** [semantic-release/semantic-release#1305]
See https://travis-ci.org/semantic-release/npm/jobs/593750522

Last release on `beta` was `5.2.0-beta.9`.
Version `5.2.0` and `5.2.0` were released from `master`.

When merging `master` into `beta` the last version was determined as `5.3.0` and all the commits since then were included. The last version should have been determined as `5.2.0-beta.9` and only the few commits merged from `master` to `beta` should have been included in the release.

**Comment by onrige** [comment]
I had the same problem on gitlab ci for prerelease on `next` channel. 

The first release was correct for major (`v2.0.0-rc.1`) but next is getting previous tag (`Found git tag v1.4.0 associated with version 1.4.0 on branch next`) and doesn't release `v2.0.0-rc.2`. 

The most interesting thing is that locally (in dry mode) it's determined the last release correctly.

**Comment by pvdlg** [comment]
Turns out it was due to commits that were cherry picked instead of being merged.
