### ISSUE TITLE
Problems with Installation on Windows Machine

### ISSUE THREAD

**Issue by afirdousi** [semantic-release/semantic-release#131]
I am trying to install semantic release for a sample that I am doing. Here is what happend

D:\git\node-npm-travis-git-integration-sample>npm install semantic-release-cli -g
/

> keytar@3.0.0 install C:\Users\Anas\AppData\Roaming\npm\node_modules\semantic-release-cli\node_modules\keytar
> node-gyp rebuild
> 
> npm ERR! Windows_NT 6.3.9600
> npm ERR! argv "C:\Program Files\nodejs\\node.exe"  "C:\ProgramFiles\nodejs\node_modules\npm\bin\npm-cli.js" "install" "sema
> ntic-release-cli" "-g"
> npm ERR! node v0.12.0
> npm ERR! npm  v2.5.1
> npm ERR! file C:\WINDOWS\system32\cmd.exe;
> npm ERR! path C:\WINDOWS\system32\cmd.exe;
> npm ERR! code ELIFECYCLE
> npm ERR! errno ENOENT
> npm ERR! syscall spawn C:\WINDOWS\system32\cmd.exe;
> 
> npm ERR! keytar@3.0.0 install: `node-gyp rebuild`
> npm ERR! spawn C:\WINDOWS\system32\cmd.exe; ENOENT
> npm ERR!
> npm ERR! Failed at the keytar@3.0.0 install script 'node-gyp rebuild'.
> npm ERR! This is most likely a problem with the keytar package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node-gyp rebuild
> npm ERR! You can get their info via:
> npm ERR!     npm owner ls keytar
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     D:\git\node-npm-travis-git-integration-sample\npm-debug.log

More info.

> OS : Windows 8 
> Python Installed :  Version 3.4
> Ruby 2.2 (Dont know if we even need it- I don't think so)
> NPM : Version 2.51
> Node : Version 0.12.0
> 
> Log file attached as a text file

[log.txt](https://github.com/semantic-release/semantic-release/files/33646/log.txt)

Anyone?

**Comment by afirdousi** [comment]
For anyone who is stuck with the same issue in a similar environment, I haven't found the solution yet but if you try to install a specific older version of semantic-release, it might work. Following worked in my scenario

> npm install semantic-release@1.0.3 -g

This is not a solution so please do not close this issue until we find a proper way out of this.

**Comment by egoroof** [comment]
It is so sad :disappointed_relieved: 

```
E:\Dropbox\repo\browser-id3-writer>npm install semantic-release-cli -g
C:\Users\Артём\AppData\Roaming\npm\semantic-release-cli -> C:\Users\Артём\AppData\Roaming\npm\node_modules\semantic-release-cli\bin\semantic-release.js

> keytar@3.0.0 install C:\Users\Артём\AppData\Roaming\npm\node_modules\semantic-release-cli\node_modules\keytar
> node-gyp rebuild


C:\Users\Артём\AppData\Roaming\npm\node_modules\semantic-release-cli\node_modules\keytar>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  reb
uild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:116:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:71:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Артём\AppData\Roaming\npm\node_modules\semantic-release-cli\node_modules\keytar
gyp ERR! node -v v5.1.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN install:keytar@3.0.0 keytar@3.0.0 install: `node-gyp rebuild`
npm WARN install:keytar@3.0.0 Exit status 1
C:\Users\Артём\AppData\Roaming\npm
└── (empty)

npm ERR! code 1
```

**Comment by rubenhazelaar** [comment]
Would be great if it worked on Windows :+1:

**Comment by hbetts** [comment]
@egoroof `keytar` (A dependency of `semantic-release`) has code that must be compiled natively. Please see the [node-gyp](https://github.com/nodejs/node-gyp#installation) documentation on requirements to compile native node modules.

@afirdousi I've looked through the log file but so far haven't see the specific failure. Any hints as to the actual error that's killing the installation?

**Comment by hbetts** [comment]
@rubenhazelaar are you encountering issues with installing `semantic-release-cli`?

**Comment by hbetts** [comment]
Also, for future reference, issues with `semantic-release-cli` should be taken up on the `semantic-release-cli` repo: https://github.com/semantic-release/cli

**Comment by rubenhazelaar** [comment]
@hbetts Yes, indeed the same as egoroof, however on better inspection I see now it's python that's missing for me (just as with egoroof I believe). I will let you know if it works out, thank you for the quick response.

**Comment by egoroof** [comment]
@hbetts yeah, I know. But it is lots of steps to do it (install python, visual studio and other). It is not possible to replace `keytar` to something which works without extra steps?

**Comment by rubenhazelaar** [comment]
That would be great

**Comment by hbetts** [comment]
There seem to be very few alternatives to `keytar`.

First off I'll note here that the `keytar` developers are aware of the desire by the community for support for prebuilt binaries so that consumers of the package do not need to have compilers installed locally. You can find the issues tracking this change here: https://github.com/atom/node-keytar/issues/27

An alternative is [xkeychain](https://www.npmjs.com/package/xkeychain), but it's listed as in development, and it also requires compiling on Windows.

A third option is [clortho](https://www.npmjs.com/package/clortho), but I'm not entirely sure that works in the same way as `keytar`, and I don't think it supports Linux.

**Comment by BioPhoton** [comment]
Any updates for the python installing process? Would be great to have a rough explanation of the steps needed to get it running on Windows. thx!

**Comment by Ahmed-Badawy** [comment]
still not working on windows till 9/2016 ... 
where's the bug fix ???

**Comment by BioPhoton** [comment]
If somebody is looking for alternatives here are some interesting repos: 
[conventional-changelog](https://github.com/conventional-changelog)

**Comment by boennemann** [comment]
Since semantic-release-cli >= 2 keytar is an optionalDependency, so it still works if keytar fails to compile. That fixes this issue.
