### ISSUE TITLE
Always pushes to undefined remote

### ISSUE THREAD

**Issue by Shadowlauch** [semantic-release/semantic-release#1322]
## Current behavior

Whenever I run semantic-release it pushes the new contents (commited by the git plugin) to the branch undefined. Now I saw that on a ci the branch name get derived from the enviroment and I'm currently testing this on my local PC. Does this have something to do with that?

## Expected behavior

It should push to the correct branch

## Environment

- **semantic-release** version: 16.0.0-beta.26
- CI environment: local
- Plugins used: 
    "@semantic-release/changelog": "^3.0.4",
    "@semantic-release/git": "^7.0.16",
    "@semantic-release/gitlab": "^4.0.0",
- **semantic-release** configuration: 

```json
{
  "branches": [
    "master",
    {
      "name": "developer",
      "prerelease": "beta"
    }
  ],
  "ci": false,
  "debug": true,
  "plugins": [
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    "@semantic-release/changelog",
    "@semantic-release/npm",
    [
      "@semantic-release/gitlab",
      {
        "gitlabUrl": "https://mbs-gitlab.vcs.de"
      }
    ],
    "@semantic-release/git"
  ]
}
```
- CI logs:

**Comment by pvdlg** [comment]
If you use the beta version of semantic-release, you should use the beta versions of the plugins as well: https://github.com/semantic-release/git/releases/tag/v7.1.0-beta.7%40beta
