### ISSUE TITLE
Is it possible to do everything except publish?

### ISSUE THREAD

**Issue by BeyondEvil** [semantic-release/semantic-release#1326]
## New feature motivation

Use this in projects that doesn't publish to NPM. For example: AWS Lambda/Serverless

## New feature description

Leverage all the functionality (semantic-versioning/tagging, release-notes generation and publishing, etc) _except_ publishing to NPM.

## New feature implementation

Maybe it can build on the `--dryRun` flag? Call it `--serverless`?

Maybe it's possible to do this already via some smart configuration settings, but I can't see it.

**Comment by BeyondEvil** [comment]
Is it possible to _override_ (not extend) the "core" `publish` method using a plugin? Maybe that can be used to solve this?

**Comment by gr2m** [comment]
https://semantic-release.gitbook.io/semantic-release/usage/configuration#plugins

Add a "release" key to your package.json and set plugins to the default plugins except npm

```json
{
  "release": {
    "plugins": [
      "@semantic-release/commit-analyzer",
      "@semantic-release/release-notes-generator",
      "@semantic-release/github"
    ]
  } 
}
```

**Comment by BeyondEvil** [comment]
Awesome! Did I miss to infer that from the docs?

Regardless, thank you! @gr2m 🙏

**Comment by dominykas** [comment]
You can also set `private: true` in your `package.json` - this way even `npm` itself will refuse to publish it.

**Comment by BeyondEvil** [comment]
> You can also set `private: true` in your `package.json` (and keep the default `semantic-release` config) - this way even `npm` itself will refuse to publish it.

But would that, in a CI situation, error out and fail the build? 🤔 

@dominykas

**Comment by dominykas** [comment]
It should just skip publishing: https://github.com/semantic-release/npm/blob/8726effc8ba5946ab3fc94391e9b5db7fe39320b/lib/publish.js#L36-L39

**Comment by BeyondEvil** [comment]
> It should just skip publishing: https://github.com/semantic-release/npm/blob/8726effc8ba5946ab3fc94391e9b5db7fe39320b/lib/publish.js#L36-L39

Ah, cool! Thanks! 🙏 @dominykas

**Comment by gr2m** [comment]
@dominykas super cool, I wasn't aware of that, thanks for sharing!
