### ISSUE TITLE
Version 15.13.27 depends (indirectly) on a package that has high vulnerability issues (https-proxy-agent)

### ISSUE THREAD

**Issue by tigermarques** [semantic-release/semantic-release#1327]
Hi,

I have semantic-release installed in version 15.13.27. This module depends on @semantic-release/npm, which, somewhere along the dependency tree, depends on https-proxy-agent in version 2.x.

NPM reports (with npm audit) that https-proxy-agent has a High vulnerability has stated here (https://nodesecurity.io/advisories/1184). This vulnerability is fixed in version >=3.0.0

Is it possible to incorporate this fix in semantic-release? I'm not sure of the implications because 3.0.0 is a major version and probably has breaking changes.

Thank you!

**Comment by pvdlg** [comment]
The problem is in `npm` (on which `@semantic-release/npm` depends):
```
├─┬ npm@6.12.0
│ └─┬ npm-registry-fetch@4.0.0
│   └─┬ make-fetch-happen@5.0.0
│     └── https-proxy-agent@2.2.2
```

Please open an issue over there.

**Comment by hernanif1** [comment]
Hi @tigermarques , I saw that you didn't created the issue so I copied and past this issue there:
https://github.com/semantic-release/npm/issues/206

**Comment by tigermarques** [comment]
Hi, thanks a lot for the feedback. Will follow the other issue.

**Comment by gr2m** [comment]
`npm` has to update its dependency on `npm-registry-fetch`. You can watch releases of `npm`. I don't think they track it anywhere themselves
