### ISSUE TITLE
How to trigger a release on a dependency update or shouldn't I do it?

### ISSUE THREAD

**Issue by rfgamaral** [semantic-release/semantic-release#1329]
I use dependabot on my repositories and when a `dependency` is updated (not `devDependency`) the commit message is something like `chore(deps): bump <dep> from <x> to <y>`. This does not trigger a release with `semantic-release`. I supposed this is expected with this configuration:

```json
{
  "ci": false,
  "plugins": [
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    "@semantic-release/changelog",
    "@semantic-release/npm",
    [
      "@semantic-release/git", {
        "message": "chore(release): ${nextRelease.version}\n\n${nextRelease.notes}"
      }
    ],
    "@semantic-release/github"
  ]
}
```

But `dependencies` are usually something that will affect my own package (either with bug fixing or new features) and sometimes my own package source code doesn't need to be updated at all.

What is the best course of action to trigger a new release of my package in this situation?

For reference, I'm referring to [@rfgamaral/parcel-plugin-typings-for-css-modules](https://github.com/rfgamaral/parcel-plugin-typings-for-css-modules).

**Comment by pvdlg** [comment]
semantic-release works with a commit convention and trigger release based on the rules associated with that convention.
The Angular convention specifies that `chore` commits should not trigger a release.
So I would recommend to configure your tool to generate `fix` commits when it update a `dependency`. That's what https://greenkeeper.io/ does for example.

**Comment by rfgamaral** [comment]
For future reference, what I wanted is [right here](https://dependabot.com/docs/config-file/#commit_message) in the third example.
