### ISSUE TITLE
Output of `--tag-format` is mangled.

### ISSUE THREAD

**Issue by BeyondEvil** [semantic-release/semantic-release#1330]
## Current behavior

If I specify `--tag-format 'v${version}-stage'`, all output (terminal, comments on issues/PRs, slack, etc) doesn't show the full tag, but a stripped version (`v${format}`).

```
$ semantic-release --tag-format 'v${version}-stage' --no-ci
[11:54:44 AM] [semantic-release] › ✔  Created tag v4.0.0-stage
[11:54:51 AM] [semantic-release] › ✔  Published release 4.0.0
```

<img width="1440" alt="wrong_tag" src="https://user-images.githubusercontent.com/15611634/67276183-6e21ff80-f4c4-11e9-9283-3b4f1b162465.png">

## Expected behavior

All output should adhere to the format specified.

## Environment

- **semantic-release** version: 15.13.27
- CI environment: local
```
{
    "branch": "master",
    "preset": "eslint",
    "plugins": [
        "@semantic-release/commit-analyzer",
        "@semantic-release/release-notes-generator",
        "@semantic-release/changelog",
        "@semantic-release/git",
        "@semantic-release/github",
        [
            "semantic-release-slack-bot",
            {
                "notifyOnSuccess": true,
            }
        ]
    ]
}
```

**Comment by pvdlg** [comment]
What you are pointing at is the name of the release which is generated by the `preset` that you use  with https://github.com/semantic-release/release-notes-generator.

The `--tag-format` option impact only the Git tag created.

**Comment by BeyondEvil** [comment]
For anyone else finding this, here's how you solve it:

```json
"@semantic-release/release-notes-generator",
            {
                "writerOpts": {
                    "headerPartial": "{{#if isPatch}}##{{else}}#{{/if}} {{#if @root.linkCompare}}[Stage]({{@root.host}}/{{#if @root.owner}}{{@root.owner}}/{{/if}}{{@root.repository}}/compare/{{previousTag}}...{{currentTag}}){{else}}Stage{{/if}}{{#if title}} \"{{title}}\"{{/if}}{{#if date}} ({{date}}){{/if}}"
                }
            }
```

The `headerPartial` takes a string that is of the type `hbs`-template.
