### ISSUE TITLE
authentication failed. 

### ISSUE THREAD

**Issue by SongGithub** [semantic-release/semantic-release#1334]
## problem: 
I am quite sure I have correct GH_TOKEN set, but it is complaining `Invalid username or password.`

## Cmd I used: 
export GH_TOKEN=123445 && \
npx semantic-release -r https://enterprise-github/experience  --debug --ci

## Error log
```
  semantic-release:git Error: Command failed: git push --dry-run https://enterprise-github/experience HEAD:master
  semantic-release:git remote: Invalid username or password.
  semantic-release:git fatal: Authentication failed for 'https://enterprise-github/experience/'
  semantic-release:git
  semantic-release:git
  semantic-release:git     at makeError (/usr/local/lib/node_modules/semantic-release/node_modules/execa/index.js:174:9)
  semantic-release:git     at Promise.all.then.arr (/usr/local/lib/node_modules/semantic-release/node_modules/execa/index.js:278:16)
  semantic-release:git     at process._tickCallback (internal/process/next_tick.js:68:7) +0ms
```

**Comment by SongGithub** [comment]
btw, I also don't what is purpose for semantic-release-cli init. 
`semantic-release-cli init --gh-token=123 --gh-username=username --npm-username=username --npm-token=a token`.

**Comment by pvdlg** [comment]
Is `https://enterprise-github/experience` the correct URL for your remote repo?
what do you get if you do `git push --dry-run https://enterprise-github/experience HEAD:master` locally?

**Comment by SongGithub** [comment]
- when I ran this cmd in local machine: it is working good. resp was "everything up to date", after it asked me my Github login creds. 
- when I ran this cmd in Docker, it complains `fatal: cannot run .git/hooks/pre-push: No such file or directory`, and hang on there forever.

**Comment by SongGithub** [comment]
latest error log: 
```
CI=true semantic-release -b develop --debug
[5:09:49 AM] [semantic-release] › ℹ  Running semantic-release version 15.13.27
  semantic-release:config load config from: undefined +0ms
  semantic-release:config options values: { branch: 'develop',
  semantic-release:config   repositoryUrl:
  semantic-release:config    'https://enterprise.github/experience.git',
  semantic-release:config   tagFormat: 'v${version}',
  semantic-release:config   plugins:
  semantic-release:config    [ '@semantic-release/commit-analyzer',
  semantic-release:config      '@semantic-release/release-notes-generator',
  semantic-release:config      '@semantic-release/npm',
  semantic-release:config      '@semantic-release/github' ],
  semantic-release:config   _: [],
  semantic-release:config   b: 'develop',
  semantic-release:config   debug: true,
  semantic-release:config   '$0': '/usr/local/bin/semantic-release' } +7ms
  semantic-release:plugins options for @semantic-release/npm/verifyConditions: {} +0ms
[5:09:49 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/npm"
  semantic-release:plugins options for @semantic-release/github/verifyConditions: {} +1ms
[5:09:49 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/github"
  semantic-release:plugins options for @semantic-release/commit-analyzer/analyzeCommits: {} +1ms
[5:09:49 AM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
  semantic-release:plugins options for @semantic-release/release-notes-generator/generateNotes: {} +0ms
[5:09:49 AM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
  semantic-release:plugins options for @semantic-release/npm/prepare: {} +1ms
[5:09:49 AM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/npm"
  semantic-release:plugins options for @semantic-release/npm/publish: {} +0ms
[5:09:49 AM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/npm"
  semantic-release:plugins options for @semantic-release/github/publish: {} +1ms
[5:09:49 AM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/github"
  semantic-release:plugins options for @semantic-release/github/success: {} +0ms
[5:09:49 AM] [semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/github"
  semantic-release:plugins options for @semantic-release/github/fail: {} +1ms
[5:09:49 AM] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/github"
[5:09:49 AM] [semantic-release] › ✔  Run automated release from branch develop
  semantic-release:git Error: Command failed: git push --dry-run https://enterprise.github/experience.git HEAD:develop
  semantic-release:git remote: Invalid username or password.
  semantic-release:git fatal: Authentication failed for 'https://enterprise.github/experience.git/'
  semantic-release:git
  semantic-release:git
  semantic-release:git     at makeError (/usr/local/lib/node_modules/semantic-release/node_modules/execa/index.js:174:9)
  semantic-release:git     at Promise.all.then.arr (/usr/local/lib/node_modules/semantic-release/node_modules/execa/index.js:278:16)
  semantic-release:git     at process._tickCallback (internal/process/next_tick.js:68:7) +0ms
[5:09:49 AM] [semantic-release] › ✔  Allowed to push to the Git repository
[5:09:49 AM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/npm"
[5:09:49 AM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/npm"
[5:09:49 AM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/github"
[5:09:49 AM] [semantic-release] [@semantic-release/github] › ℹ  Verify GitHub authentication
```

**Comment by SongGithub** [comment]
update, I have progressed to the next error after I added HTTP_PROXY as env var, following [these docs](https://github.com/semantic-release/github)

Current error is: `EINVALIDGHTOKEN Invalid GitHub token.`
But I am quite sure my GH_TOKEN is set as an env var `export GH_TOKEN=12345` and set to valid value (I can prove that manually.)

**Comment by SongGithub** [comment]
ok I got this solved myself. 
## my context: 
- work behind a forward proxy 
- internal Github enterprise used

## essential settings I found:
```
  NODE_TLS_REJECT_UNAUTHORIZED=0
  GH_PREFIX=/api/v3
  GH_URL=<base url to Github enterprise>
```

**Comment by travi** [comment]
for what its worth, i highly recommend to you and others that might find this thread not disabling tls validation with `NODE_TLS_REJECT_UNAUTHORIZED` (or any other method). instead, you should work with your ops team to configure your infrastructure to be able to properly trust the certs being served so that they can be properly verified.

**Comment by SongGithub** [comment]
That is right. The reason for me to use `NODE_TLS_REJECT_UNAUTHORIZED=0` is that the app will be working behind a forward-proxy where it is mandated to corporate *self-signed cert*.  Using the self-signed cert without this setting will cause errors.

**Comment by travi** [comment]
> Using the self-signed cert without this setting will cause errors.

i understand that your self-signed cert will fail to validate by default because its not from a trusted certificate-authority (CA). however, it can and should be validated. you (or others finding this thread) should to take steps to inform your server how to validate the self-signed cert properly. 

i'm going to avoid trying to suggest specifics on how to handle this properly, but this is why i suggested working with your ops team above. whoever is mandating the use of a signed cert should be able to help you use it properly since disabling validation should _not_ be recommended.

**Comment by k00p** [comment]
@SongGithub Node has an environment variable [NODE_EXTRA_CA_CERTS](https://nodejs.org/api/cli.html#cli_node_extra_ca_certs_file) where you can specify the appropriate certificate authority for your corporate proxy as a file (PEM/CRT/etc). This was the most secure option I could find. Please let me know if anyone comes up with something better!

**Comment by SongGithub** [comment]
thank you @k00p for the suggestion, I will definitely try it out.
