### ISSUE TITLE
Docs: Why does semantic-release require Node version >= 8.16?

### ISSUE THREAD

**Issue by papb** [semantic-release/semantic-release#1338]
I noticed that in the latest release [the minimum node version changed from 8.3 to 8.16](https://github.com/semantic-release/semantic-release/commit/2f3d93406991639d2497fb764be26d5ab2038ac5).

I am curious to know why :)

The documentation itself has [a FAQ with exactly my question](https://github.com/semantic-release/semantic-release/blob/master/docs/support/FAQ.md), but there is no clear answer: the answer was unchanged except from the number changing from 8.3 to 8.16.

Thanks!

**Comment by gr2m** [comment]
It's because eslint bumped their required version:
https://github.com/eslint/eslint/issues/12493

We could have worked around it but decided it's not worth the effort, as Node 8 will be out of maintenance at the end of this year anyway
