### ISSUE TITLE
[Question] How can I override `releaseNotes`?

### ISSUE THREAD

**Issue by BeyondEvil** [semantic-release/semantic-release#1339]
According to docs (or tests at least) if you use the `generateNotes` plugin endpoint, the results get concatenated.

Is it possible to override or otherwise change that behaviour?

We have jira ticket references in our commit messages `(ENG-1234)` and I want to replace them with a link to the actual ticket `[ENG-1234](<url to ticket>)`.

How can I accomplish that?

Thanks!

Edit: If it's not possible, would you accept a PR to make it possible?

Edit2: Can I use the `exec` plugin to solve this?

**Comment by pvdlg** [comment]
You need to implement your own [conventional-changelog](https://github.com/conventional-changelog/conventional-changelog) preset and configure it with the [`preset` option](https://github.com/semantic-release/release-notes-generator#options).
Probably by forking https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-angular and adding your transformation.

**Comment by BeyondEvil** [comment]
Ackchyually...

```
            {
                "linkCompare": false,
                "writerOpts": {
                    "headerPartial": "{{#if isPatch}}##{{else}}#{{/if}} {{#if @root.linkCompare}}[{{currentTag}}]({{@root.host}}/{{#if @root.owner}}{{@root.owner}}/{{/if}}{{@root.repository}}/compare/{{previousTag}}...{{currentTag}}){{else}}{{currentTag}}{{/if}}{{#if title}} \"{{title}}\"{{/if}}{{#if date}} ({{date}}){{/if}}",
                    "transform": (commit) => {
                        if (!commit.tag || typeof commit.tag !== `string`) { 
                            return 
                        }
                        console.log(commit)
                        commit.message = commit.message.replace(/ENG-\d+/g, '[$&](https://proxyco.atlassian.net/browse/$&)');
                        commit.shortHash = commit.hash.substring(0, 7); 
                        return commit
                    }
                }
            }
```
