### ISSUE TITLE
"Could not login to Travis CI" in setup

### ISSUE THREAD

**Issue by rafaeleyng** [semantic-release/semantic-release#134]
I had this error while trying to setup semantic-release for my very first time:

```
$ semantic-release-cli setup
? Is the GitHub repository private? No
? What is your npm registry? https://registry.npmjs.org/
? What is your npm username? rafaeleyng
? What is your npm email? rafaeleyng@gmail.com
? What is your GitHub username? rafaeleyng
? What CI are you using? Travis CI
ERR! semantic-release Could not login to Travis CI.
ERR! semantic-release Endpoint temporarily disabled
```

There were no Google results for those error messages so I'm pretty clueless.
I thought that might be an error of my usernames/passwords, but I double checked them and the problem remains.

**Comment by ghaiklor** [comment]
+1, also couldn't login to Travis CI.

**Comment by bahmutov** [comment]
Same problem with a little different message
```
ERR! semantic-release Could not login to Travis CI.
ERR! semantic-release you are currently not allowed to perform this request. please contact support@travis-ci.com.
```

**Comment by lewiscowper** [comment]
:+1: with this problem

```
ERR! semantic-release Could not login to Travis CI.
ERR! semantic-release you are currently not allowed to perform this request. please contact support@travis-ci.com.
```

**Comment by ghaiklor** [comment]
Summoning @boennemann to help with this critical issue.

**Comment by boennemann** [comment]
Hey all, 

thanks for the report. Just looking at this, it looks like Travis has some issues with their API, or changed their endpoints. This [blogpost](https://blog.travis-ci.com/2015-11-23-magnum-is-no-more) suggests something in that direction.

We'll investigate and see if we can fix this from our side, or if Travis needs to reenable their Endpoint.

Best,
Stephan

**Comment by boennemann** [comment]
Also summoning the semantic-release cli maintainer @christophwitzko  ;)

**Comment by bahmutov** [comment]
Seems for my issue the reason is because of DDOS, Travis now needs a user agent in the header, see https://github.com/semantic-release/cli/issues/69

**Comment by ghaiklor** [comment]
@bahmutov great, hope it will be merged soon :+1:

**Comment by bahmutov** [comment]
As a work around I am using CircleCI to do semantic-release. Here is step by step guide https://github.com/bahmutov/condition-circle/blob/master/HOW.md and I wrote a verify conditions plugin https://github.com/bahmutov/condition-circle to be used instead of the default `condition-travis` - seems to work pretty nicely

**Comment by boennemann** [comment]
This is working again, thanks so much @bahmutov.

https://github.com/semantic-release/cli/releases/tag/v1.3.3
