### ISSUE TITLE
step "success" hangs 

### ISSUE THREAD

**Issue by SongGithub** [semantic-release/semantic-release#1343]
## Current behavior
In the Github plugin, when it finishes step "publish", it continues to run "success" step, and it hangs forever & actually add tons of celebrating comments to Pull Requests included in the release. Colleagues complains that their email box got spammed by this release-bot 

Read through doco for the Github module, I can't see how to disable success step

## Expected behavior
I want to see it just passes & do nothing, if there is no configuration for "success" step. Because I don't need it to post comments to relevant Pull Requests for now. 

## Environment

- Plugins used: 
- @semantic-release/release-notes-generator
- @semantic-release/github
- @semantic-release/commit-analyzer

- **semantic-release** configuration:
```
{
  "repositoryUrl": "https://github/repo.git",
  "release": [
    {"success": false},
    {"fail": false},
    {"publish": false}
  ],
  "plugins": [
    "@semantic-release/commit-analyzer", {
      "preset": "angular",
      "parserOpts": {
        "noteKeywords": ["BREAKING CHANGE", "BREAKING CHANGES"]
      }
    },
    "@semantic-release/release-notes-generator",
    ["@semantic-release/github", {
      "assets": [
        {"path": "dist/main.css", "label": "CSS distribution"},
        {"path": "dist/index.js", "label": "JS distribution"}
      ]
    }],
  ]
}
```
 
- CI logs: 
```
[4:13:37 AM] [semantic-release] [@semantic-release/github] › ℹ  Published GitHub release: https://github/repo/releases/tag/v0.3.0
[4:13:37 AM] [semantic-release] › ✔  Completed step "publish" of plugin "@semantic-release/github"
[4:13:37 AM] [semantic-release] › ℹ  Start step "success" of plugin "@semantic-release/github
```

**Comment by SongGithub** [comment]
would these help? 
`      "successComment": false,
      "failComment": false,` 
```
    ["@semantic-release/github", {
      "successComment": false,
      "failComment": false,
      "assets": [
        {"path": "dist/main.css", "label": "CSS distribution"},
        {"path": "dist/index.js", "label": "JS distribution"}
      ]
    }]
```

**Comment by pvdlg** [comment]
Per [the documentation](https://github.com/semantic-release/github#options):
> `successComment`: The comment to add to each issue and pull request resolved by the release. Set to false to disable commenting on issues and pull requests.

Please try to search the documentation before opening issues to request support.
If you don't find the answer please use the [appropriate support channels](https://github.com/semantic-release/semantic-release#get-help)
