### ISSUE TITLE
All commits analyzed when there are ~1000+ tags

### ISSUE THREAD

**Issue by dominykas** [semantic-release/semantic-release#1352]
## Current behavior

`semantic-release` analyzes the whole history when there are more than ~1150 tags (this is on a Mac, in a repo with 3000+ tags - I can see in our Jenkins, that we're able to correctly release a repo with ~1800 tags, so the threshold may varies by OS?).

[`getTagHead` calls happen inside a `map()`](https://github.com/semantic-release/semantic-release/blob/56186419a791b02d806a5d40e7321959bad99134/lib/branches/get-tags.js#L24), i.e. they are parallel.

`getTagHead` will [return `undefined`](https://github.com/semantic-release/semantic-release/blob/56186419a791b02d806a5d40e7321959bad99134/lib/git.js#L17-L21) after swallowing an exception: `Error: Command failed with EAGAIN: git rev-list -1 v41.1.2`

Depending on tag order, etc - the latest tag may have `undefined` as `gitHead`, which will lead to [`getCommits` loading all commits](https://github.com/semantic-release/semantic-release/blob/56186419a791b02d806a5d40e7321959bad99134/lib/get-commits.js#L15), causing performance issues at the very least (we're performing additional analysis on commits - I did not wait for it to complete).

## Expected behavior

`semantic-release` should only analyze commits since last release.

## Environment

- **semantic-release** version: 16.0.0-beta.28
- CI environment: Haven't tried just yet, playing around on macOS
- Plugins used: Likely irrelevant
- **semantic-release** configuration: Likely irrelevant
- CI logs: Likely irrelevant

**Comment by dominykas** [comment]
Does `semantic-release` _need_ to know the commit of _every_ tag?

**Comment by pvdlg** [comment]
I made some changes in #1353.
However what you describe seems to indicate a deeper problem in your repo.
The tag `v41.1.2` was found by the command `git tag` but `git rev-list -1 v41.1.2` fails. I don't even know how that's possible...

**Comment by dominykas** [comment]
>  I don't even know how that's possible...

It failed with EAGAIN when running with all 3k tags. It works just fine when I slice the tags down to, say, 1000. It also fails with newer tags rather than older ones, so I assume I'm just hitting some child process limit either in OS or in node.

I'll test the fix tomorrow - thanks for the quick response!

**Comment by dominykas** [comment]
Thanks - this works!

One small note - https://github.com/semantic-release/semantic-release/blob/131734873e904176044767ad929b5f53579556f6/lib/branches/get-tags.js#L24 - this last `map()` is now redundant, I think?

**Comment by pvdlg** [comment]
Thanks, good catch!
