### ISSUE TITLE
Wrong pre-release version when channel is set to false

### ISSUE THREAD

**Issue by amille44420** [semantic-release/semantic-release#1357]
When I set `channel` to `false` on a `prerelease` branch, the release version does not match expectations.

## Context

The project has two branches (its purposes is not to be packaged for **npm**)

- `master` (production ready with CD)
- `next` (staging branch with CD)

The project runs with the following settings

```json
{
    "branches": [
        { "name": "master" },
        {
            "name": "next",
            "prerelease": true,
            "channel":  false
        }
    ],
    "plugins": [
        "@semantic-release/commit-analyzer",
        "@semantic-release/release-notes-generator",
        [ "@semantic-release/npm",  {
                "npmPublish": false
         } ],
        "@semantic-release/changelog",
        ["@semantic-release/git", {
                "assets": [
                    "CHANGELOG.md",
                    "package.json"
                ],
                "message": "chore(release): ${nextRelease.version}"
          }]
    ]
}
```

## Current behavior

I run the following scenario 

- `master `and `next` share the same `HEAD`
- initial release on `master` (releasing `v1.0.0`)
- add a commit `feat: something` on `next`
- new release on `next` (releasing `v1.1.0-next.1`)
- add a commit `feat: something else` on `next`
- new release on `next` ( ⚠️ releasing again `v1.1.0-next.1`)

## Expected behavior

At the end of my scenario I should release  `v1.1.0-next.2`

## Environment

```json
{
    "@semantic-release/changelog": "^3.0.5",
    "@semantic-release/git": "^7.1.0-beta.8",
    "semantic-release": "^16.0.0-beta.31",
    "semantic-release-cli": "^5.2.2"
}
```

**Comment by pvdlg** [comment]
Fixed by #1359
