### ISSUE TITLE
Branch configuration

### ISSUE THREAD

**Issue by matheussampaio** [semantic-release/semantic-release#136]
I want to publish my package on two channels: `latest` and `next`. Every new commit on `master` branch will be published on `next` tag and commits on `release` branch will be published on `latest`.

It's possible to have different branch configuration at the same time? Something like:
```js
{
    "name": "mypackage",
    "version": "0.0.0-semantically-released",
    "release": {
        "master": {
            // master branch will be published on `next` tag.
            "publishConfig": {
                "tag": "next"
            }
        },
        "release": {
            // Commits on branch release will be publish on `latest` tag.
            "branch": "release"
        }
    }
}
```

**Comment by boennemann** [comment]
Hey @matheussampaio,

for a setup like this you would just change the `package.json` to whatever you need on the respective branches. For example with semantic-release I have the current "latest" on the "badger" branch and I just set it up in the [package.json](https://github.com/semantic-release/semantic-release/blob/badger/package.json#L77-L79
), while my "next" channel lives on the "caribou" branch, where that is set up in the [package.json](https://github.com/semantic-release/semantic-release/blob/caribou/package.json#L74-L79) as well.

Whenever I want to backport non-breaking features/fixes from caribou to badger I cherry-pick them. If you want to move a version from "next" to "latest" you do that by changing the tag using `npm dist-tag`.

I hope that helps. If you have any further question I'm happy to help.

Best,
Stephan

**Comment by PatrickHeneise** [comment]
Is there another way? I think it's pretty awful to maintain two different package.json files, having to add it to .gitignore so it's not in pull-requests from branch a to branch b etc.

**Comment by gyoshev** [comment]
We had a similar idea at work, and developed a set of semantic-release plug-ins that enable this. See the [semantic-prerelease](https://github.com/telerik/semantic-prerelease) project and the [accompanying blog post](https://www.ofcodeandcolor.com/2017/10/13/semantic-prerelease/). We use prerelease tags for our `next` branch (we name it `develop`), but that should still work in this case.

**Comment by gr2m** [comment]
@gyoshev this is very insightful, thanks for sharing @gyoshev! We have some ideas about how we could utilize GitHub’s pre-releases and a GitHub app which would set a version to `@latest` once a GitHub pre-release was marked as normal release. Stay tuned :)
