### ISSUE TITLE
Postmortem: the deletion and recovery of semantic-release's main repository

### ISSUE THREAD

**Issue by gr2m** [semantic-release/semantic-release#1373]
https://github.com/semantic-release/semantic-relaese was accidentally deleted at 3:40pm Pacific time on Nov 29, 2019.

Most of the repository has been recovered by 4:00pm. All forks have been re-attached by 7:47pm.

Watchers and existing commit statuses could not be recovered.

## Root cause 

I was working on end-to-end tests using GitHub Actions (#1372). The end-to-end test does the following:

1. Creates a new repository in the @semantic-release-test organization
2. Sets up semantic-release
3. Creates a `feat: initial version` commit
4. Runs semantic-release, which publishes the new package to the npm registry and creates a release on the new repository.

Once the tests worked as planned, I added steps to clean up:

1. Un-publishes the package from the registry
2. Deletes the repository

In order to delete the repository, I use the [`request-action`](https://github.com/octokit/request-action/), with the following syntax

```yml
- uses: octokit/request-action@v1.x
  with:
    route: DELETE /repos/:owner/:repo
  env:
    GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_BOT_GITHUB_TOKEN }}
```

The problem here was that I forgot to set the `owner` and `repo` parameters, the correct syntax would have been

```yml
- uses: octokit/request-action@v1.x
  with:
    route: DELETE /repos/:owner/:repo
    owner: semantic-release-test
    repo: ${{ env.PKG_NAME }}
  env:
    GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_BOT_GITHUB_TOKEN }}
```

Instead of failing the build due to missing parameters, the `request-action` defaults `:owner` and `:repo` to current repository. So instead of deleting the temporary repository, https://github.com/semantic-release/semantic-release was deleted instead.

🤦‍♂️ 

### Recovery

Once we realized that the repository was deleted, we tried to recover it [as described here](https://help.github.com/en/github/administering-a-repository/restoring-a-deleted-repository#restoring-a-deleted-repository-that-was-owned-by-an-organization), but the deleted repository was not listed on https://github.com/organizations/semantic-release/settings/deleted_repositories.

After that failed, I tried to find a GitHubber that was currently online. I contacted @jasonetco from GitHub at 3:55pm who was able to recover most of the repository by 4:00pm. He was then able to track down an available support team who were able to start a process to re-attached all forks to the repository.

### Corrective and Preventative Measures

- @semantic-release-bot can no longer delete a repository in the @semantic-release organization.

	We use the @semantic-release-bot account for automation in the Semantic Release project. Until the incident, the account has been set as owner of the @semantic-release organization, which gave it the permission to delete https://github.com/organizations/semantic-release. We downgraded the account to member, and invited the account to each relevant repository with write access instead. **Update**: Done.
- Stop defaulting `:owner` and `:repo` parameters in https://github.com/octokit/request-action. 

  I'm coincidentally the maintainer of `request-action`, so I can make the change myself to prevent other users from suffering similar incidents. **Update**: [Done](https://github.com/octokit/request-action/pull/4).
- Reflect on the current setup of the end-to-end tests and find ways to further isolate them from the https://github.com/organizations/semantic-release repository. **Update**: See discussion at #1372

I apologize to everyone for the inconvenience this caused, especially to @pvdlg who put so much energy into the upcoming v16 release. Loosing all discussions from the issues and pull requests would have been a significant set back. 

On this thanksgiving, I'm thankful to my friend @jasonetco and everyone at GitHub how was able to recover most of https://github.com/organizations/semantic-release so swiftly.

**Comment by T0astBread** [comment]
Coincidentally, I was just evaluating semantic-release _exactly_ while this happened. Glad to know that everything's okay and it was just a mishap! 😄
