### ISSUE TITLE
secret GITLAB_TOKEN not detected while GL_TOKEN is

### ISSUE THREAD

**Issue by oupala** [semantic-release/semantic-release#1374]
## Current behavior

When using semantic-release on a private GitLab instance, it appears that the secret named GITLAB_TOKEN is not detected while GL_TOKEN is.

## Expected behavior

As written in the documentation, both name for the secret variable are supported:

> `GH_TOKEN` or `GITHUB_TOKEN`    | A GitHub [personal access token](https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line).

When I name the secret variable GL_TOKEN everything goes well. When I name it GITLAB_TOKEN (which is more meaningful in my opinion, the pipeline fails with the error below.

## Environment

- **semantic-release** version: 15.13.27
- CI environment: GitLab Community Edition 12.4.2, gitlab-runner 11.10.1, 
- Plugins used: 
  - @semantic-release/commit-analyzer
  - @semantic-release/release-notes-generator
  - @semantic-release/changelog
  - @semantic-release/npm
  - @semantic-release/git
  - @semantic-release/gitlab
- **semantic-release** configuration: 
- CI logs: 

>   name: 'SemanticReleaseError',
>   code: 'EGITNOPERMISSION',
>   details: '**semantic-release** cannot push the version tag to the branch `master` on the remote Git repository with URL `https://gitlab.private/group/project.git`.\n\nThis can be caused by:\n - a misconfiguration of the [repositoryUrl](https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#repositoryurl) option\n - the repository being unavailable\n - or missing push permission for the user configured via the [Git credentials on your CI environment](https://github.com/semantic-release/semantic-release/blob/master/docs/usage/ci-configuration.md#authentication)',

**Comment by pvdlg** [comment]
Are you sure it's configured with the correct token?
Both variable are handled the exact same way: https://github.com/semantic-release/semantic-release/blob/master/lib/get-git-auth-url.js#L24-L25

Note that is both variables are set, `GL_TOKEN` has a higher priority than `GITLAB_TOKEN`.
Maybe you have something else setting `GL_TOKEN` with a wrong token.

**Comment by oupala** [comment]
My bad. `GL_TOKEN` secret variable was not protected while `GITLAB_TOKEN` secret variable was not.

As my `master` branch was not protected, it could not access the `GITLAB_TOKEN` secret variable but was able to access `GL_TOKEN` secret variable.

Protecting the `master` branch allowed it to access the `GITLAB_TOKEN` secret variable.

Maybe something should be added to the documentation to warn users if they encounter the same error...
