### ISSUE TITLE
npm ERR! No version provided

### ISSUE THREAD

**Issue by ocombe** [semantic-release/semantic-release#138]
Hello,

I'm working on condition-snap to make semantic release work on SnapCI, but I cannot make it work, when it's supposed to publish on npm I get an error saying that no version was provided :-/

It appears that `semantic-release pre` doesn't return a version number on snap-ci, but it does return the right on my local windows machine :-/

Here is the log of the build that fails: https://snap-ci.com/ocombe/condition-snap/branch/master/logs/defaultPipeline/18/Semantic-release?back_to=build_history

Here is my repository: https://github.com/ocombe/condition-snap

**Comment by hbetts** [comment]
@ocombe I actually successfully use `semantic-release` for my projects on `snap-ci`, so hopefully I can help out.

Based on the error, I took a look at your `package.json` file. You don't have a version number in that file.

Now, `semantic-release` doesn't actually update the version field in a repo's `package.json` file, but that field must at least exist for `semantic-release` to work.

**Comment by ocombe** [comment]
Well I had one, and it told me that this version already existed in the npm registry (since it took the existing number instead of generating a new one) :(

**Comment by hbetts** [comment]
@ocombe at the time I was using the latest `semantic-release` version available on the npm registry. (Therefore what ever version is tagged as `latest`).

I must confess, I've switched from `snap-ci` to `travis-ci`, to get access to a build matrix, and to make it easier to manage all my projects.

**Comment by pvdlg** [comment]
A lot of version of `semantic-release` have been released since this issue was reported. Could you try again with `semantic-release@8.1.0` ? This version improve the way we detect the commit related to the last release.
