### ISSUE TITLE
Is it possible to pick the user which comments and adds labels to issues?

### ISSUE THREAD

**Issue by rfgamaral** [semantic-release/semantic-release#1384]
For instance, I commited a fix to a project and included the text `Closes #37` and `semantic-release` did all this for me:

![image](https://user-images.githubusercontent.com/96476/70524391-f0ca5100-1b3c-11ea-9ee8-6b94e35d573e.png)

I'm wondering if it's possible to configure the tool to use the name and profile picture of `semantic-release-bot` for the comment and the added label at the end instead of my own name?

**Comment by pvdlg** [comment]
The user used to write those comment is the user associated with the Github token you configure in `GITHUB_TOKEN` environment variable.

`@semantic-release-bot` is a user that belong to our organization and you can't use it as we won't share our credentials.

You can create your own bot user, git it permission on your repo and use a personal token associated with that user.

**Comment by rfgamaral** [comment]
Ok, that makes sense. Thanks @pvdlg.

**Comment by rubencabrera** [comment]
> You can create your own bot user, git it permission on your repo and use a personal token associated with that user.

I'm having more problems than I would admit using a bot account. Is it necessary to specify the different user somehow?

I keep getting the error:
```
 code: 'EGITNOPERMISSION',

  details: '**semantic-release** cannot push the version tag to the branch `semantic-release-2` on remote Git repository with URL `https://github.com/myuser/myrepo.git`.\n'
```

Although I can manually use the token from the CLI and push tags or commits for the bot account.
