### ISSUE TITLE
Use GitHub deploy keys on CircleCI

### ISSUE THREAD

**Issue by juliuscc** [semantic-release/semantic-release#1390]
## New feature motivation

Using SSH-keys that are user-specific is problematic, as the CI environment gets access to ALL repositories a user has on the service (GitHub in my case). There are deploy keys that can be used to push and pull from only a specific repo.

It would be helpful if semantic-release could use deploy keys also. If this feature were added, the company I work at would be a lot more comfortable with using semantic release. At this point, they are sceptical to giving read and write access to ALL repos.

## New feature description

Semantic release would be able to support an additional method of authentication. As far as I know, deploy keys do not support GitHub features like adding or commenting on issues, or adding GitHub releases. If you use deploy keys, you would probably have to give up these features, as long as tags can be pushed and pulled to the repository.

## New feature implementation

There might be a challenge with the GitHub-plugin not getting access to features it uses, but as the deploy key would probably be on a new environment variable, it should not have to change.

Also, using deploy keys works very differently to other authentication methods, I think. So it might not be a trivial task.

I would love to help with this PR. I am not sure if this has been discussed before, but I couldn't find it in issues. It might also be an issue with how I use semantic release, and this might already exist. If this requires any modifications to semantic release, and you think this should exist, please tell me what to fix and where. 😄

**Comment by pvdlg** [comment]
It seems deploy keys are just SSH keys with access limited to one repo. You should be able to authenticate with a SSH Key by following that recipe: https://github.com/semantic-release/semantic-release/blob/master/docs/recipes/git-auth-ssh-keys.md

As you mentioned you won't be  able to use the deploy key with the `@semantic-release/github` plugin.

**Comment by juliuscc** [comment]
I have tried doing this and always get the following error: `The command "undefined" failed with the error message ERROR: The key you are authenticating with has been marked as read only.`

## Steps to recreate
I created an empty repo with only semantic-release, and a config where I removed the npm and github plugin.

To create an SSH key I followed this (https://github.com/semantic-release/semantic-release/blob/master/docs/recipes/git-auth-ssh-keys.md) tutorial, for CircleCI. The run command seems to be written for the last generation of CircleCI (at least I couldn't get it to work), so I put every command on a seperate run command. I also had no passphrase which meant that I skipped `-N "<ssh_passphrase>"` when creating the SSH key and I skipped running `- echo 'echo ${SSL_PASSPHRASE}' > /tmp/askpass && chmod +x /tmp/askpass` in the CircleCI config.

I have added the key as a deploy key **with read/write access** as can be seen here:

![bild](https://user-images.githubusercontent.com/8337202/70867597-68eaa980-1f77-11ea-9faa-63af0cf3b8e1.png)

The Node version is 12.9.0. The repo is here: https://github.com/juliuscc/semantic-release-deploy-key-test and the CircleCI output can be found here: https://app.circleci.com/jobs/github/juliuscc/semantic-release-deploy-key-test/14

## CircleCI Output
```

> semantic-release-deploy-key-test@1.0.0 semantic-release /home/circleci/repo
> semantic-release

[7:05:58 PM] [semantic-release] › ℹ  Running semantic-release version 15.13.31
[7:05:58 PM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[7:05:58 PM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[7:05:58 PM] [semantic-release] › ✔  Run automated release from branch master
[7:05:59 PM] [semantic-release] › ✖  The command "undefined" failed with the error message ERROR: The key you are authenticating with has been marked as read only.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists..
[7:05:59 PM] [semantic-release] › ✖  EGITNOPERMISSION Cannot push to the Git repository.
semantic-release cannot push the version tag to the branch master on the remote Git repository with URL https://github.com/juliuscc/semantic-release-deploy-key-test.git.

This can be caused by:

    * a misconfiguration of the repositoryUrl (https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#repositoryurl) option
    * the repository being unavailable
    * or missing push permission for the user configured via the Git credentials on your CI environment (https://github.com/semantic-release/semantic-release/blob/master/docs/usage/ci-configuration.md#authentication)

SemanticReleaseError: Cannot push to the Git repository.
    at module.exports (/home/circleci/repo/node_modules/semantic-release/lib/get-error.js:6:10)
    at run (/home/circleci/repo/node_modules/semantic-release/index.js:79:11)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async module.exports (/home/circleci/repo/node_modules/semantic-release/index.js:170:22)
    at async module.exports (/home/circleci/repo/node_modules/semantic-release/cli.js:55:5) {
  name: 'SemanticReleaseError',
  code: 'EGITNOPERMISSION',
  details: '**semantic-release** cannot push the version tag to the branch `master` on the remote Git repository with URL `https://github.com/juliuscc/semantic-release-deploy-key-test.git`.\n' +
    '\n' +
    'This can be caused by:\n' +
    ' - a misconfiguration of the [repositoryUrl](https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#repositoryurl) option\n' +
    ' - the repository being unavailable\n' +
    ' - or missing push permission for the user configured via the [Git credentials on your CI environment](https://github.com/semantic-release/semantic-release/blob/master/docs/usage/ci-configuration.md#authentication)',
  semanticRelease: true
}npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! semantic-release-deploy-key-test@1.0.0 semantic-release: `semantic-release`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the semantic-release-deploy-key-test@1.0.0 semantic-release script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/circleci/.npm/_logs/2019-12-15T19_05_59_408Z-debug.log

Exited with code exit status 1
```

**Comment by juliuscc** [comment]
Am I doing something wrong? If so, I would love to update the docs so that it is more clear how to do this, as there are no explicit docs for deploy keys.

**Comment by juliuscc** [comment]
Also thanks for answering quickly! I use semantic-release a lot and love your contributions to the community! ❤️ 🚀

**Comment by pvdlg** [comment]
semantic-release needs to be able to push git tags, so you need to configure authentication so that the command `git push --dry-run <repository.url from package.json> HEAD:master` is successful.
I don't know if deploy keys allows to that...Maybe you can experiment with deploy keys without semantic-release and when you find the way to make it work you can report and I can see if something has to be changed in semantic-release. 

Just a guess, maybe try with the `repository.url` in your `package.json` in git format like `git@github.com:owner/repo.git` or maybe ssh format like `ssh://github.com/owner/repo.git`. Not sure how each version of `git` CLI decide to use the ssh keys or not.

**Comment by juliuscc** [comment]
Yes I will try it and come back soon

**Comment by thompsondt** [comment]
@juliuscc any updates on this one? I'm tempted to try the deploy keys method.

Looking at the docs I'm a bit puzzled about why it's necessary to commit the private key to the repository. I'm on GitLab and expecting that I can pass my private key into the CI environment using an environment variable. Then creating the private key file on the fly.

**Comment by juliuscc** [comment]
Yes!

I have tried a couple of things:

## Trying suggestions from @pvdlg 

1. I deactivated all local ssh-keys so that I knew if this deploy key is the key that makes it work. I tested this by trying to push to my repo, which did not work.
2. I added this deploy key to my ssh-agent.
3. It works to do a regular `git push` in my repo.
4. I updated the `repository.url` in my `package.json` to `git@github.com:juliuscc/semantic-release-deploy-key-test.git`.
5. I ran `git push --dry-run git@github.com:juliuscc/semantic-release-deploy-key-test.git HEAD:master` successfully.
6. I ran the same command but without --dry-run successfully.
7. I got the same error as before in CircleCI.

The ouptut is:
```

> semantic-release-deploy-key-test@1.0.0 semantic-release /home/circleci/repo
> semantic-release

[12:41:54 PM] [semantic-release] › ℹ  Running semantic-release version 15.13.31
[12:41:54 PM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[12:41:54 PM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[12:41:54 PM] [semantic-release] › ✔  Run automated release from branch master
[12:41:55 PM] [semantic-release] › ✖  The command "undefined" failed with the error message ERROR: The key you are authenticating with has been marked as read only.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists..
[12:41:55 PM] [semantic-release] › ✖  EGITNOPERMISSION Cannot push to the Git repository.
semantic-release cannot push the version tag to the branch master on the remote Git repository with URL git@github.com:juliuscc/semantic-release-deploy-key-test.git.

This can be caused by:

    * a misconfiguration of the repositoryUrl (https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#repositoryurl) option
    * the repository being unavailable
    * or missing push permission for the user configured via the Git credentials on your CI environment (https://github.com/semantic-release/semantic-release/blob/master/docs/usage/ci-configuration.md#authentication)

SemanticReleaseError: Cannot push to the Git repository.
    at module.exports (/home/circleci/repo/node_modules/semantic-release/lib/get-error.js:6:10)
    at run (/home/circleci/repo/node_modules/semantic-release/index.js:79:11)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async module.exports (/home/circleci/repo/node_modules/semantic-release/index.js:170:22)
    at async module.exports (/home/circleci/repo/node_modules/semantic-release/cli.js:55:5) {
  name: 'SemanticReleaseError',
  code: 'EGITNOPERMISSION',
  details: '**semantic-release** cannot push the version tag to the branch `master` on the remote Git repository with URL `git@github.com:juliuscc/semantic-release-deploy-key-test.git`.\n' +
    '\n' +
    'This can be caused by:\n' +
    ' - a misconfiguration of the [repositoryUrl](https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#repositoryurl) option\n' +
    ' - the repository being unavailable\n' +
    ' - or missing push permission for the user configured via the [Git credentials on your CI environment](https://github.com/semantic-release/semantic-release/blob/master/docs/usage/ci-configuration.md#authentication)',
  semanticRelease: true
}npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! semantic-release-deploy-key-test@1.0.0 semantic-release: `semantic-release`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the semantic-release-deploy-key-test@1.0.0 semantic-release script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/circleci/.npm/_logs/2020-01-01T12_41_55_325Z-debug.log

Exited with code exit status 1
```

## Comments from @thompsondt 
I agree that the process for uploading a deploy key with CircleCI is complex, but I think that is another issue. The documented process is quite different depending on CI. I think they could probably be more similar. That is another issue I think because it works for regular ssh-keys. This is a specific problem for deploy keys I think.

**Comment by pvdlg** [comment]
Can you upgrade to v15.13.32 or higher and provide the logs again? v15.13.32 fixes a bug that display `undefined` rather than the failing command.

**Comment by juliuscc** [comment]
Yes here is the output after updating to v15.13.32:

```

> semantic-release-deploy-key-test@1.0.0 semantic-release /home/circleci/repo
> semantic-release

[8:57:31 AM] [semantic-release] › ℹ  Running semantic-release version 15.14.0
[8:57:31 AM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[8:57:31 AM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[8:57:31 AM] [semantic-release] › ✔  Run automated release from branch master
[8:57:32 AM] [semantic-release] › ✖  The command "git push --dry-run git@github.com:juliuscc/semantic-release-deploy-key-test.git HEAD:master" failed with the error message ERROR: The key you are authenticating with has been marked as read only.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists..
[8:57:32 AM] [semantic-release] › ✖  EGITNOPERMISSION Cannot push to the Git repository.
semantic-release cannot push the version tag to the branch master on the remote Git repository with URL git@github.com:juliuscc/semantic-release-deploy-key-test.git.

This can be caused by:

    * a misconfiguration of the repositoryUrl (https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#repositoryurl) option
    * the repository being unavailable
    * or missing push permission for the user configured via the Git credentials on your CI environment (https://github.com/semantic-release/semantic-release/blob/master/docs/usage/ci-configuration.md#authentication)

SemanticReleaseError: Cannot push to the Git repository.
    at module.exports (/home/circleci/repo/node_modules/semantic-release/lib/get-error.js:6:10)
    at run (/home/circleci/repo/node_modules/semantic-release/index.js:79:11)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async module.exports (/home/circleci/repo/node_modules/semantic-release/index.js:176:22)
    at async module.exports (/home/circleci/repo/node_modules/semantic-release/cli.js:55:5) {
  name: 'SemanticReleaseError',
  code: 'EGITNOPERMISSION',
  details: '**semantic-release** cannot push the version tag to the branch `master` on the remote Git repository with URL `git@github.com:juliuscc/semantic-release-deploy-key-test.git`.\n' +
    '\n' +
    'This can be caused by:\n' +
    ' - a misconfiguration of the [repositoryUrl](https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#repositoryurl) option\n' +
    ' - the repository being unavailable\n' +
    ' - or missing push permission for the user configured via the [Git credentials on your CI environment](https://github.com/semantic-release/semantic-release/blob/master/docs/usage/ci-configuration.md#authentication)',
  semanticRelease: true
}npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! semantic-release-deploy-key-test@1.0.0 semantic-release: `semantic-release`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the semantic-release-deploy-key-test@1.0.0 semantic-release script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/circleci/.npm/_logs/2020-01-03T08_57_32_342Z-debug.log

Exited with code exit status 1
```

**Comment by pvdlg** [comment]
Thanks.
So it's clearly the command `git push --dry-run git@github.com:juliuscc/semantic-release-deploy-key-test.git HEAD:master` that fails. You mentioned earlier that you ran this command successfully. Did you ran it on the CI where semantic-release runs? I don't see it in https://circleci.com/gh/juliuscc/semantic-release-deploy-key-test/18

**Comment by juliuscc** [comment]
No, I ran it in my local machine. And then I did it with the original key, and not the unencrypted encrypted key. I can try using the encrypted key and following the same steps as CircleCI does, or do you want me to try to run the command `git push --dry-run git@github.com:juliuscc/semantic-release-deploy-key-test.git HEAD:master` in CircleCI?

**Comment by pvdlg** [comment]
At the risk of stating the obvious, semantic-release needs to have the command `git push --dry-run git@github.com:juliuscc/semantic-release-deploy-key-test.git HEAD:master` to work where it runs. The fact it works somewhere else is not going to change that.

The problem is that for some reason your keys are not working on CircleCi and that's not related to semantic-release.

**Comment by juliuscc** [comment]
Yes that is correct. I tried to run `git push --dry-run git@github.com:juliuscc/semantic-release-deploy-key-test.git HEAD:master` on CircleCI instead of `npm run semantic-release` and I get the same error

```
ERROR: The key you are authenticating with has been marked as read only.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Exited with code exit status 128
```
https://circleci.com/gh/juliuscc/semantic-release-deploy-key-test/20

I will try to make it work and add a description in the docs. This would be great for enterprise solutions.

**Comment by pvdlg** [comment]
Thanks! It seems it's something specific to CircleCI. Maybe CircleCI setup some read only ssh keys for you and `git` end up using those rather than the deploy key you are setting up.
