### ISSUE TITLE
Feature: Add configuration file path option

### ISSUE THREAD

**Issue by aslafy-z** [semantic-release/semantic-release#1403]
## New feature motivation

I need to run semantic-release but my configuration file is in a subdirectory of the git repository.

## New feature description

Allow users to set configuration file path. 

## New feature implementation

Add a `--config-path` CLI option that reference the configuration file and skip cosmiconfig if it's set.

Another way would allowing user to set cosmiconfig's `searchFrom` variable from the search method, instead of forcing `cwd`. `--config-path` could become `--config-dir`.

**Comment by dominykas** [comment]
You can use https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#extends

**Comment by aslafy-z** [comment]
Perfect, thanks! I just opened a PR at https://github.com/cycjimmy/semantic-release-action/pull/8 to implement this option.
