### ISSUE TITLE
Update mem package to >=4.0.0

### ISSUE THREAD

**Issue by gempain** [semantic-release/semantic-release#1408]
As advised by Npm, can `mem` be updated to a version higher than `4.0.0` ?
https://www.npmjs.com/advisories/1084

Thanks a lot, and keep up the great work !

**Comment by pvdlg** [comment]
That is not one of our direct dependency. There is nothing that can be done here. It has to be updated in the project that defines the dependency.

**Comment by gempain** [comment]
Yep, sorry, my mistake, it's actually `semantic-release > @semantic-release/npm > npm > libnpx >  yargs > os-locale > mem`.
