### ISSUE TITLE
Passing --branch or --branches no longer works in version 16

### ISSUE THREAD

**Issue by JoA-MoS** [semantic-release/semantic-release#1409]
## Current behavior

When passing a branch name via the cli such as the following where `setup-semantic-release` is my branch name.

```
semantic-release --no-ci --dry-run --debug --branches setup-semantic-release
```

Also seeing the same behavior specifying the branches via `release.config.js` 

```
module.exports = {
  branches: 'setup-semantic-release',
}
```
or
```
module.exports = {
  branches: [{name: 'setup-semantic-release'}],
}
```
The output:

```
[3:29:23 PM] [semantic-release] » ×  ERELEASEBRANCHES The release branches are invalid in the `branches` configuration.
A minimum of 1 and a maximum of 3 release branches are required in the branches configuration (https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#branches).

This may occur if your repository does not have a release branch, such as master.

Your configuration for the problematic branches is [].

{ AggregateError:
    SemanticReleaseError: The release branches are invalid in the `branches` configuration.
        at module.exports (~/AppData/Roaming/nvm/v10.17.0/node_modules/semantic-release/lib/get-error.js:6:10)
        at Object.entries.reduce (~/AppData/Roaming/nvm/v10.17.0/node_modules/semantic-release/lib/branches/index.js:44:19)
        at Array.reduce (<anonymous>)
        at module.exports (~/AppData/Roaming/nvm/v10.17.0/node_modules/semantic-release/lib/branches/index.js:34:46)
    at module.exports (~\AppData\Roaming\nvm\v10.17.0\node_modules\semantic-release\lib\branches\index.js:66:11)
    at process._tickCallback (internal/process/next_tick.js:68:7) name: 'AggregateError' }
```

## Expected behavior

A user should be able to specify 1 to 3 branches via the `branches` property or via the cli

## Environment

- **semantic-release** version: 16.0.1
- CI environment: --no-ci
- Plugins used: 
```
 verifyConditions: [
    '@semantic-release/changelog',
    '@semantic-release/git',
    '@semantic-release/npm',
  ],
  prepare: [
    '@semantic-release/changelog',
    '@semantic-release/npm',
    '@semantic-release/git',
  ],
  publish: ['@semantic-release/npm'],
```
>this is based off an older config

- **semantic-release** configuration: can't provide at this time
- CI logs: Same as above

> As a note it seems that the [cli test](https://github.com/semantic-release/semantic-release/blob/3739ab5f34454321aad2bf36f3a5ec03da004d33/test/cli.test.js#L30)  could be better updated as it currently tests passing the branches parameter as master and next but i believe those are the defaults and could lead to false positives...

**Comment by pvdlg** [comment]
Does the branch you configure exists in the remote repo?

**Comment by JoA-MoS** [comment]
I think you may be right, although I thought I tested that. It could also be I had some old version of something in my node modules. It seems to have cleared itself up.  Closing the Issue.
