### ISSUE TITLE
verifyConditions plugins should be a list or one

### ISSUE THREAD

**Issue by bahmutov** [semantic-release/semantic-release#141]
right now it allows single plugin, but I would rather have a list of plugins - each runs after the previous succeeds. Will make writing and using plugins composable

**Comment by bahmutov** [comment]
For example I implemented Node version check in https://github.com/bahmutov/condition-node-version but had to check for travis env too because I cannot combine the default plugin with this one

**Comment by boennemann** [comment]
Hey Gleb,

this is supported for verification plugins as of 4.2.0. You simply pass the plugins as an array (https://github.com/semantic-release/semantic-release/commit/700ec9d4).

Best,
Stephan

**Comment by bahmutov** [comment]
:cool:
