### ISSUE TITLE
Allow for a release trigger without generating a changelog

### ISSUE THREAD

**Issue by Bram-Zijp** [semantic-release/semantic-release#1414]
## New feature motivation

When in a test phase, you wanna release using CI/CD solutions without generating a changelog or odd commit names.

## New feature implementation

Add a commit message prefixed on a way like `release(x): test this and that` to trigger a release without generating changelog content

**Comment by gr2m** [comment]
I don't understand what you are trying to do. Can you please share an example?

**Comment by Bram-Zijp** [comment]
@gr2m
Well when you are testing stuff out and you wanna release stuff automatically in your  CI/CD solution, triggering the release with commit messages like `fix(test): try this and that`, is suboptimal. I wan't to trigger releases without having to resort to the `fix/feat/BREAKING_CHANGE` commit messages.

**Comment by gr2m** [comment]
why do you want to trigger a release at all if you are still testing?

**Comment by Bram-Zijp** [comment]
Good point, I found linking packages locally a chore on Windows. Also, I just created a new npm repo at which I wanted to release all my modules to through CI/CD. I ended up writing messages like `fix: release to new cluster`.

**Comment by gr2m** [comment]
> Good point, I found linking packages locally a chore on Windows

You can npm install using a github GitHub repository/branch URL directly

>  I just created a new npm repo at which I wanted to release all my modules to through CI/CD

I'm not sure what you mean by that. Do you want to create the releases to test your CI/CD release setup?

**Comment by Bram-Zijp** [comment]
Thanks for the tip!!

I want to release the latest version to a new npm repo which is defined in environment variables in my CI/CD solution. Thinking about it longer, I should just login locally to the npm repo and run `npm publish`

**Comment by pvdlg** [comment]
> I ended up writing messages like `fix: release to new cluster`.

Why would you want to make a release if no code was changed?
If some code changed it should be either a `fix` or a `feature`.

> I want to release the latest version to a new npm repo which is defined in environment variables in my CI/CD solution. Thinking about it longer, I should just login locally to the npm repo and run npm publish

I wouldn't recommend to do that as it will create issues later. Doing so you would release a version on npm without having created a corresponding tag in your repo. When you will run semantic-release later on it will likely fail is it won't be aware of those versions because there is no tag in the repo.

But again I still don't understand why you would want to make a release if you didn't modify the code since the last release.

**Comment by Bram-Zijp** [comment]
To release the same version to a new npm repo mainly. Also to test the same version but with different code/contents, one not in use by anyone else/production apps, without resorting to linking local modules/git hosted modules.

**Comment by pvdlg** [comment]
I would strongly advise against releasing the same version to a different npm repo. You want to be sure that a given version correspond to a certain codebase state. Having two version of the same package in different place will certainly create issues as you won't have anyway to know what code is actually running, depending on where the package come from.

If you want to release test code and unfinished things then you should use pre-releasaes: https://github.com/semantic-release/semantic-release/blob/master/docs/recipes/pre-releases.md

**Comment by Bram-Zijp** [comment]
@pvdlg i was migrating from one Kubernetes cluster to another and with that, my npm repo. I could get away with bumping versions to the latest and last release as my codebase is relatively small. Ideally one would migrate all released versions/the volume which contains the npm repo data at whole.
