### ISSUE TITLE
Plugins docs do not specify the name of the plugins file

### ISSUE THREAD

**Issue by bionicles** [semantic-release/semantic-release#1424]
## New feature motivation

React apps don't need to be published on NPM so I need to disable the npm plugin and thus need a plugins configuration but it's unclear from plugins.md what the file name should be

## New feature description

Please document in plugins.md which file name to use to make the plugins configuration 

## New feature implementation

1 line of markdown in plugins.md

**Comment by pvdlg** [comment]
The docs already mention everything about the various way to configure semantic-release: https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#configuration-file

Your question is also answered in the FAQ: https://github.com/semantic-release/semantic-release/blob/master/docs/support/FAQ.md#can-i-skip-the-release-to-the-npm-registry
