### ISSUE TITLE
[Question] Commit messages and triggers

### ISSUE THREAD

**Issue by emirot** [semantic-release/semantic-release#1427]
## New feature motivation

I thought an action will occur after each commit following the angular convention. It worked for me for feat` and `fix`. However, I've tried `docs` but  it didn't create a release.
Only the 3 ones explained in the doc will do a release ? 
I thought any of https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#type or is this configurable ?

## New feature description

Would be great to make that clear in the documentation

## New feature implementation

Add that in the doc

**Comment by gr2m** [comment]
There is a clear mapping between fix, feat, and BREAKING CHANGE to the semantic version number x.y.z: breaking.feature,fix. If you only fix documentation, that should trigger an update to your documentation, but not a new version of your library. I wonder why you'd want that? Could you explain your use case?

The commits are analyzed using the https://github.com/semantic-release/commit-analyzer plugin, which is part of semantic-release by default. You can override its setting as documented here: https://semantic-release.gitbook.io/semantic-release/usage/plugins#plugin-options-configuration

It would look like this

```json
{
  "plugins": [
    ["@semantic-release/commit-analyzer", {
      // your custom config here
    }],
    "@semantic-release/release-notes-generator",
    "@semantic-release/github",
    "@semantic-release/git"
  ],
  "preset": "angular"
}
```

**Comment by pvdlg** [comment]
Specifically the option that defines which commit triggers which type of release is `releaseRules`: https://github.com/semantic-release/commit-analyzer#configuration

**Comment by emirot** [comment]
Thanks you @gr2m & @pvdlg ! both of your answers was exactly what I was looking for.

**Comment by pvdlg** [comment]
Closing the issue then
