### ISSUE TITLE
missing marked peer dependency

### ISSUE THREAD

**Issue by ZebraFlesh** [semantic-release/semantic-release#1429]
#1244 has reoccurred

**Comment by gr2m** [comment]
if you or anyone really could submit a Pull Request to https://github.com/mikaelbr/marked-terminal (similar to https://github.com/mikaelbr/marked-terminal/pull/54), that'd be great. We cannot do much on our side to fix that, just track the issue

**Comment by rfgamaral** [comment]
@gr2m If I'm not mistaken that change was [already done](https://github.com/mikaelbr/marked-terminal/blob/v4.0.0/package.json) and `semantic-release` needs to update `marked-terminal` to the latest v4. Right?

**Comment by gr2m** [comment]
Hmm yes looks like it. Curious that we didn't get a pull request for the new version yet. I'll update it manually
