### ISSUE TITLE
Breaking Change triggered with chore() command.

### ISSUE THREAD

**Issue by safaiyeh** [semantic-release/semantic-release#1431]
## Current behavior
• Used chore(docs), commit had "Breaking Change" string. I added a Breaking Change section to my README.
• Triggered major version.

https://github.com/react-native-community/cookies/pull/21

## Expected behavior
• chore command should never be a breaking change.

## Environment

- **semantic-release** version: ^15.14.0
- CI environment: CircleCI
- Plugins used: "@semantic-release/git": "^7.0.18"
- **semantic-release** configuration: https://github.com/react-native-community/cookies/pull/21 
- CI logs: https://app.circleci.com/jobs/github/react-native-community/cookies/89/parallel-runs/0/steps/0-106

**Comment by pvdlg** [comment]
that's an issue with one of our dependency, [conventional-changelog](https://github.com/conventional-changelog/conventional-changelog).
It can easily be reproduced with [conventional-commits-parser](https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-commits-parser) by running the CLI and copy/pasting your commit.
The result contains:
```json
  "notes": [
    {
      "title": "Breaking change",
      "text": "warning\n* Update typo"
    }
  ]
```
which indicate a breaking change note.

Can open an issue over there? Thanks.

**Comment by pvdlg** [comment]
@safaiyeh have you opened an issue with conventional-changelog?

**Comment by pvdlg** [comment]
Closing as no answer provided
