### ISSUE TITLE
Pre-Releases for Pull Requests

### ISSUE THREAD

**Issue by Xiphe** [semantic-release/semantic-release#1433]
## New feature motivation

As a maintainer of a collaborative project I don't want to be a bottleneck.
Therefore I want to enable others to use & test a change that is still under development/discussion (in a PR) as early as possible.

I therefore want to release each commit on every branch as a pre-release (except for `master`). Even if there is a PR open for that branch.

## New feature description

Currently, semantic release refuses to publish a new version on CI, when a PR is open for that branch.
(Funny enough, when I close the PR and re-run the CI, a version is being released)

## New feature implementation

I'm unsure what cases are to be guarded by the `isPr` check. But I strongly assume that we can not simply remove it. So we might need to introduce a new configuration option to allow releasing of branches even though the run was triggered in a PR.

## Bonus Points

- As a PR author I would really like to receive a comment on my PR when a pre-release has been filed.
- As a maintainer, I may not want to include all pre-release change-logs in my github release overview

## Meta

- Not sure I'f this already is possible somehow (In that case I'd love to contribute a receipt once I've understood how)
- Maybe having releases with unreviewed code from people I don't know is also a really bad idea for OSS projects. I'm viewing this from a internal project perspective where I trust all contributors

**Comment by gr2m** [comment]
I think pre-releases via semantic-release is not the right approach here. What I use in my projects is https://github.com/apps/pika-cia. It provides an `npm install`-able URL and a URL to directly import a bundled version for browsers, it's pretty great:

https://github.com/octokit/core.js/pull/34/checks?check_run_id=408214165

So if someone submits a pull request, even from a fork, they can directly use their version and do not need to wait for me to merge & release it

**Comment by pvdlg** [comment]
When you create a pull request, most CI do 2 things:
- A PR build: the merge of the head branch with the base branch specified in the pull request
- A branch build: regular build of the base branch, as if there was no PR

semantic-release will be skipped only in the first build. So you might want to make sure the second build does happens in your CI. See docs for Travis as an example: https://docs.travis-ci.com/user/pull-requests/#double-builds-on-pull-requests

The other reason to skip semantic-release on PR builds is a security issues with authentication tokens on PR coming from a forked repo.
CIs won't provide the secret environment variable for PR builds that come from a forked repo, so we can't run semantic-release on those. The reason is that anyone could just fork the repo, change the code to add `console.log(process.env.NPM_TOKEN)`, open a PR  and access your credentials. To avoid that CIs do not provide those variables on such PRs.

**Comment by Xiphe** [comment]
@gr2m Awesome! Thanks for the tipp with Pika. I really like that approach for OSS projects!

I wouldn't consider this a silver bullet though, I really like the flexibility of semantic release where I can publish to my own registry, use it on different CI env, use custom plugins etc.

**Comment by Xiphe** [comment]
@pvdlg thanks for the feedback! Most TravisCI configurations [i've seen] and CircleCI for example just triggers one build (there are [feature-requests](https://discuss.circleci.com/t/trigger-build-on-pr-and-commit-to-a-branch/24023) though). So for some users this check is not preventing *additional releases* but its preventing *any* releases.

I second your concerns about the security implications for OSS projects. For these I would advise to not release PRs from forked branches. Most CI providers I know of also support not passing secrets to these builds. 

For internal/private projects though this concern is not relevant since I trust all contributors.

**Comment by pvdlg** [comment]
> @pvdlg thanks for the feedback! Most TravisCI configurations [i've seen] and CircleCI for example just triggers one build (there are feature-requests though). So for some users this check is not preventing additional releases but its preventing any releases.

What prevent you to change your CI config to run a regular build on the feature branch?

**Comment by Xiphe** [comment]
I'm using CircleCi. And I meant to say "Most **Jenkins CI** configurations [i've seen] just trigger one build." Sorry for the typo.

**Comment by pvdlg** [comment]
And CircleCI can't run a regular build on a feature branch even if there is a PR opened?

**Comment by Xiphe** [comment]
https://discuss.circleci.com/t/trigger-build-on-pr-and-commit-to-a-branch/24023

**Comment by pvdlg** [comment]
We can't make a release during the PR build because:
- Authentication might not be available
- The commit that is build is not in the history of the repo, it's a "virtual" commit created by the CI resulting of the merge of the head branch with the base branch specified in the pull request. We can't tag this commit and we can't use that tag later on to figure out what commits were added.

I would suggest to use either:
- use a CI that can build any branch independently of a PR being opened
- wait for Circle CI to implement that (it seems to be a basic feature supported by any CI)
- Configure Circle CI to make the regular branch build (at the expense of not having a PR build anymore it seems)

It doesn't seems there is anything that can be done in semantic-release?

**Comment by Xiphe** [comment]
> It doesn't seems there is anything that can be done in semantic-release?

I find it strange that semantic-release behaves differently on different CI providers. If you consider that a problem of the CI providers, nothing can be done here.

---

I'm currently tinkering around with 

1. `unset`-ing the CircleCI environment variables `env-ci` uses to check if the build is a PR before running semantic-release. (once that is done, releases are filed without problem). 
2. using a dynamic `release.config.js` that wont use `@semantic-release/github` unless on `master` in order to not spam the github releases
3. still semantic-release creates git-tags for each pre-release which might also become spammy on bigger projects.

Anyways thanks for your help and feedback. I will update this thread with my findings for documentation reasons.

**Comment by Xiphe** [comment]
Now using this config

```js
// release.config.js
const { branch } = require('env-ci')();

const DEFAULT_BRANCH = 'master';

module.exports = {
  branches: [DEFAULT_BRANCH, { name: '*', prerelease: true }],
  plugins: [
    '@semantic-release/commit-analyzer',
    '@semantic-release/release-notes-generator',
    '@semantic-release/npm',
    branch === DEFAULT_BRANCH && '@semantic-release/github',
  ].filter(Boolean),
};
```

and 

```bash
unset CIRCLE_PR_NUMBER; unset CIRCLE_PULL_REQUEST; unset CI_PULL_REQUEST; npx semantic-release || true
```

works well enough for me.

**Comment by pvdlg** [comment]
Just be careful about how CircleCI build a PR branch. If the head commit is not the same as the remote and is instead a merge of the head branch with the base branch, semantic-release won't be able to tag it.

**Comment by Xiphe** [comment]
I'll update this if I find issues in that direction but I have not experienced issues in that direction in the past year or so (I used a custom build script doing s.th. similar).

Another thing that does not feel 100% clean and is related to this topic


Given my default branch is on `v1.0.0`
And I have a branch `next-thing` creating pre-releases
And I committed a feature addition to the `next-thing` branch (`feat: new stuff`)
And `v1.1.0-next-thing.1` has been pre-released

When I then need to fix a bug on the `new stuff` inside the `next-thing` feature
Then I need to commit that as a `fix: better new stuff` in order to trigger a new pre-release `v1.1.0-next-thing.2`

But that also causes the bugfix to appear in the changelog of the `master` once `next-thing` is merged. I find that strange because the bug never existed on master.

A possible solution to this is using squash merges, but that comes with its own drawbacks...

**Comment by pvdlg** [comment]
This is something that has been reported several time.
Changelog reflect what's in the branch history, so a commit is included whether it was included in another release before.
Handling cases like that would be pretty complex I think, we would need to figure out which commit to filter from the changelog (`fix` would be out but not `feat`? What about other commit convention?).

**Comment by Xiphe** [comment]
Totally agree. What I did previously (remember context is every PR gets pre-releases) is to not tag pre-releases at all and use the commit hash as part of the version instead of a counter (`v1.1.0-next-thing.45695b9`). That way a commit to a branch including any releasing commit triggers a updated pre-release.

This supports two senarios currently not possible with semantic release:

1. Using non-conventional commits for fixes in a pre-release branch (that trigger releases but do not appear in changelogs). I would consider this sub-optimal because the commit causing the changelog is incomplete.
2. Rebasing/squashing fixes directly to the feature commit inside the pre-release branch. (This is currently not possible with semantic release [iirc.] because it would create duplicated tags where on of them is on a detached HEAD
