### ISSUE TITLE
Last commit broke tests 

### ISSUE THREAD

**Issue by aslafy-z** [semantic-release/semantic-release#1434]
## Current behavior

Tests are broken

## Expected behavior

Tests should pass

## Environment

- **semantic-release** version: 17.0.0

## Lead

Here one commit that broke some tests, by replacing aggressively `from ` to `= require(`.

https://github.com/semantic-release/semantic-release/commit/ef1b8a0b910b81070a600c8c772434ec345812dd

**Comment by pvdlg** [comment]
Where is the problem? All the tests are passing...

**Comment by pvdlg** [comment]
I'm guessing what you refer to is what's fixed in https://github.com/semantic-release/semantic-release/commit/bc97537c9771afe2477d8337ee9c4d5f382d33c9

**Comment by aslafy-z** [comment]
You are right. Sorry for my early and incorrect reaction. I was looking at the renovate update and seen these errors in the diff without taking time to understand it. Thank for your awesome job!

**Comment by pvdlg** [comment]
Thanks for reporting it
