### ISSUE TITLE
 How to run certain plug-ins in different parts of the CI / CD?

### ISSUE THREAD

**Issue by max10rogerio** [semantic-release/semantic-release#1441]
## Current behavior

how to run release in different parts on my ci / cd?

Today on my ci/cd, i run the command `yarn semantic-release` and works fine!

I build the TS project and generate the `/dist` folder

I need to generate the `CHANGELOG.md`, using [semantic-release/changelog](https://github.com/semantic-release/changelog), adn move this changelog file into the `/dist` folder, and then zip folder and upload it to `github`.

I already do the part of uploading to github, but without the `CHANGELOG.md` file

## Expected behavior

Run certain plugins in differents parts on CI/CD

Example:
- run `semantic-release/changelog` for create the changelog file
- my CI/CD manipulate this changelog file
- run `semantic-release` to create tag and release-notes

## Environment

- **semantic-release** version: ^15.13.31
- CI environment: circleCI
- Plugins used: `@semantic-release/commit-analyzer`, `@semantic-release/release-notes-generator`, `@semantic-release/github`
- **semantic-release** configuration: https://gist.github.com/max10rogerio/fa4b16fe44840bdeeb3df998b0d4a05a
- CI logs:

**Comment by pvdlg** [comment]
According to the config you linked you don't use `@semantic-release/changelog`. Are you referring to https://github.com/semantic-release/changelog ?

Also why would want to upload the CHANGELOG.md to gitHub? The changelog is included as part of the GitHub release.

**Comment by max10rogerio** [comment]
I want the changelog file inside the dist folder

**Comment by pvdlg** [comment]
If you want to generate a CHANGELOG.md you gonna have to use `@semantic-release/changelog`. It's not part of the config you linked.

**Comment by max10rogerio** [comment]
as I said in the example, I want to generate the changelog using semantic-release / changelog and move it into the dist folder

Would it be possible to do something like this?

**Comment by pvdlg** [comment]
Yes it is possible, that's the goal of `@semantic-release/changelog`.
You say you want to use `@semantic-release/changelog` but as I said you didn't set it in your config. If you want to use a plugin you have to define it in your config.

**Comment by pvdlg** [comment]
@max10rogerio does adding `@semantic-release/changelog` to your `plugins` config solved your problem?

**Comment by max10rogerio** [comment]
yes! But I don't know move changelog to `/dist` folder (generated by TS build), because I don't know run `semantic-release` plugin in differents steps on my CI/CD.

**Comment by pvdlg** [comment]
You can define where the changelog is created with `changelogFile` option : https://github.com/semantic-release/changelog#configuration
