### ISSUE TITLE
semantic-release does not find latest tag on beta branch

### ISSUE THREAD

**Issue by gr2m** [semantic-release/semantic-release#1442]
## Current behavior

`semantic-release` does not find last tag `v3.0.0-beta.1` when run on the beta branch. Instead it finds `v2.2.0` which is the last tag on the master branch.

I did rebase `beta` on master, but I deleted and re-created the `v3.0.0-beta.1` tag. So I assumed this should just work?

## Expected behavior

It should publish `v3.0.0-beta.2`

## Environment

- **semantic-release** version: 17.0.0
- CI environment: GitHub Actions
- Plugins used: _default_
- **semantic-release** configuration: _defualt_
- CI logs: https://github.com/octokit/plugin-rest-endpoint-methods.js/runs/420238746?check_suite_focus=true#step:7:67

**Comment by gr2m** [comment]
Oh I think I have to update the git notes, too?

```
git notes --ref semantic-release show v3.0.0-beta.1
error: no note found for object 3774640897ac670d6382b50c551c0dd373ca8b08.
```

**Comment by gr2m** [comment]
How do I update the sha that `v3.0.0-beta.1` is pointing to in git notes?

**Comment by pvdlg** [comment]
`git notes --ref semantic-release add -f -m '{"channels":["beta"]}' v3.0.0-beta.1`
`git push origin refs/notes/semantic-release`

**Comment by gr2m** [comment]
FYI I had to use `--force` for the push

```
git push origin refs/notes/semantic-release
To github.com:octokit/plugin-rest-endpoint-methods.js.git
 ! [rejected]        refs/notes/semantic-release -> refs/notes/semantic-release (fetch first)
error: failed to push some refs to 'git@github.com:octokit/plugin-rest-endpoint-methods.js.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

I wonder if we there is a good place to put that information? I keep rebasing `beta` on top of `master` out of habbit. Maybe in the FAQs?

**Comment by travi** [comment]
I haven't followed through to confirm it really works the way i would expect, but based on https://github.blog/changelog/2019-12-04-expanded-branch-protection-rules/, it should now be possible to protect a branch but still allow it to be deleted when finished with it. I wonder if protecting `beta` could prevent this type of situation.

**Comment by gr2m** [comment]
I have it protected, but allow `push --force` to allow it to be rebased on master. But I will remove that setting now, really have to remind myself not to do that anymore

**Comment by pvdlg** [comment]
> I wonder if we there is a good place to put that information? I keep rebasing beta on top of master out of habbit. Maybe in the FAQs?

You add this kind of info to https://github.com/semantic-release/semantic-release/blob/master/docs/support/troubleshooting.md
