### ISSUE TITLE
How to see verbose output from semantic-release?

### ISSUE THREAD

**Issue by bahmutov** [semantic-release/semantic-release#145]
We are trying to setup semantic release against a private npm registry and it seems the semantic release is hanging. How can we run the semantic-release with verbose logging on?

**Comment by boennemann** [comment]
Hey @bahmutov,

because it's so tightly coupled to npm I just made it inherit the npm loglevel.
The way I do this with Travis is to set the environment variable `npm_config_loglevel=verbose` and let the build run again.

Let me know how the private npm registry goes!

Best,
Stephan
