### ISSUE TITLE
[semantic-release] ✖  An error occurred while running semantic-release: Error: Cannot find module '[secure]'

### ISSUE THREAD

**Issue by Touseefyousuf** [semantic-release/semantic-release#1452]
## Current behavior
Error: Cannot find module '[secure]'

When executing the following command 
npx semantic-release --no-ci -r <Repo_Location>

## Environment  CI/Jenkins

- **semantic-release** version: 
- CI environment: Jenkins
- Plugins used: 
- **semantic-release** configuration: 
{
  "scripts": {
    "semantic-release": "semantic-release"
  },
  "devDependencies": {
    "@semantic-release/commit-analyzer": "^6.3.3",
    "@semantic-release/git": "^7.0.18",
    "semantic-release": "^15.13.30",
    "semantic-release-docker": "^2.2.0"
  },
  "release": {
    "plugins": [
      "@semantic-release/commit-analyzer",
      "@semantic-release/release-notes-generator"
    ]
  }
}

- CI logs: 
 Require stack:
14:40:37  - /home/jenkins/agent/workspace/test_master/noop.js
14:40:37      at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
14:40:37      at resolveFileName (/root/.npm/_npx/22/lib/node_modules/semantic-release/node_modules/resolve-from/index.js:29:39)
14:40:37      at resolveFrom (/root/.npm/_npx/22/lib/node_modules/semantic-release/node_modules/resolve-from/index.js:43:9)
14:40:37      at module.exports (/root/.npm/_npx/22/lib/node_modules/semantic-release/node_modules/resolve-from/index.js:46:47)
14:40:37      at loadPlugin (/root/.npm/_npx/22/lib/node_modules/semantic-release/lib/plugins/utils.js:51:82)
14:40:37      at /root/.npm/_npx/22/lib/node_modules/semantic-release/lib/plugins/index.js:17:37
14:40:37      at Array.reduce (<anonymous>)
14:40:37      at module.exports (/root/.npm/_npx/22/lib/node_modules/semantic-release/lib/plugins/index.js:14:34)
14:40:37      at module.exports (/root/.npm/_npx/22/lib/node_modules/semantic-release/lib/get-config.js:92:35)
14:40:37      at processTicksAndRejections (internal/process/task_queues.js:97:5) {
14:40:37    code: 'MODULE_NOT_FOUND',
14:40:37    requireStack: [
14:40:37      '/home/jenkins/agent/workspace/test_master/noop.js'
14:40:37    ]
14:40:37  }
14:40:37  Error: Cannot find module '[secure]'

**Comment by pvdlg** [comment]
Are you sure it's your whole config? You have `@semantic-release/git` and `semantic-release-docker` in your dependencies but those are not used in your configuration.

In any case the problem happens when semantic-release load the plugins. So you must have something in one of your plugin that reference `test_master/noop.js`.  I don't think it's `@semantic-release/commit-analyzer` or `@semantic-release/release-notes-generator`. Those are used by a lot of people and loads properly.

**Comment by Touseefyousuf** [comment]
Thanks for the reply.
The json files is the same as i was using
while debugging the issue i found it the issue was due to incorrect credential.
Executing npx semantic-release --no-ci -r <Repo_Location> with proper credentials in jenkins pipeline worked.

**Comment by KillDozerX2** [comment]
Just a comment, don't forget to install the changelog and git plugins.
This happened to me as well.
