### ISSUE TITLE
Hooking the semantic versioning to artifactory.

### ISSUE THREAD

**Issue by Touseefyousuf** [semantic-release/semantic-release#1455]
I want to release my build images  in jenkins Ci pipeline to be automatically deployed in Artifactory and versions maintained automatically.
Tried seaching but could not get it working
Any help would be appreciated on what is the configuration /steps needed to be done.
My current configuration look like this

```json
{
  "scripts": {
    "semantic-release": "semantic-release"
  },
  "devDependencies": {
    "@semantic-release/commit-analyzer": "^6.3.3",
    "semantic-release": "^17.0.2"
  },
  "release": {
    "plugins": [
      "@semantic-release/commit-analyzer",
      "@semantic-release/release-notes-generator"
    ]
  }
}
```

**Comment by travi** [comment]
the recommended way to publish to a different registry is to use the configuration capabilities of npm itself by setting the registry in an `.npmrc` file in your project. if that is not an option, the npm plugin for semantic-release does provide some additional configuration options: https://github.com/semantic-release/npm#npm-configuration

**Comment by Touseefyousuf** [comment]
1)Does semantic versioning provide any environemntal variable for the released version that can be used in further steps in jenkins pipeline?
2)Tried running it with following configuration added 

 "release": {
    "plugins": [
      "@semantic-release/commit-analyzer",
      "@semantic-release/release-notes-generator"
    ],
	"verifyConditions": {
      "path": "semantic-release-docker",
      "registryUrl": "artifacts.XXXX.com:7999"
    },
    "publish": [
      {
        "path": "semantic-release-docker",
        "name": "artifacts.XXXXX.com:7999/XXXXX/build-report-test"
      }
    ]
  }
}

But to could not acjieve any success.

**Comment by pvdlg** [comment]
Does semantic versioning provide any environemntal variable for the released version that can be used in further steps in jenkins pipeline?

=> No. All the steps related to releasing should be run via semantic-release plugins.


You are not reporting a bug asking for support. The proper place to do that is  [Spectrum](https://spectrum.chat/semantic-release) so other users can help you.
If you questions there please be more descriptive and provide more details such:
- What workflow you try to achieve
- What is your config
- The semantic-release logs
- What doesn't work the way you want it to work

**Comment by caiodelgadonew** [comment]
Yo @Touseefyousuf did you manage to make it work?
