### ISSUE TITLE
[Need Help] Bump the version in two branches simultaneously in Jenkins

### ISSUE THREAD

**Issue by ajaij** [semantic-release/semantic-release#1459]
**Git Strategy I'm Following:**

`Development` branch is my base, all the features & bug fixes are done by creating a branch from development, then **git squash** using github PR & back to the development branch.

Now for production deployment a release branch is created from development branch in the following format `rel-<date>-<month>-<year>`. 

**Method I have integrated semantic-release in Jenkins:**
When a production deployment happens using jenkins, I'm checking out to development branch and executing the following code for the version bump and release management.

`GH_TOKEN=xxx npx semantic-release -b development --debug`

**Problem:**
 If any hotfix has to be done after the release, then I'm doing the fix directly in the release branch and cherry picking the same to development branch. If I re-deploy jenkins prod env it will checkout to development branch & semantic-release create new commit list, now the problem is once a release branch is created next sprint changes will be push into development so the un-released commits will also be added to the release notes.

**Question:**
 Any suggestions to handle this scenario, because semantic-release will do version bump to one branch and not multiple branches simultaneously.

**Comment by pvdlg** [comment]
The goal of semantic-release is to automate the decision of making a release and to release code as soon as possible, which is when the code of a PR passes the tests and get merged. Your workflow seems to try to work against that.
Can you explain what's the goal of this workflow?
Why not just use the [GitHub flow](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/github-flow)?
What's the point of having a `rel-<date>-<month>-<year>`? semantic-release creates a tag for each release, so this branch seems redundant with the version tags.

**Comment by ajaij** [comment]
So we are using github flow, the way we work is **development** branch acts as our base or master branch and any new changes or fixes are done by creating a branch out from development using & github flow its merged back. The goal is always to use development as our base for all and to avoid merging the changes into dedicated branch like **master** which always gets deployed in the CI.

If you can point me to the proper workflow that semantic-release goals aligns kindly share it, will have a look at those.

**Comment by pvdlg** [comment]
> If you can point me to the proper workflow that semantic-release goals aligns kindly share it, will have a look at those.

We recommend the GitHub flow.

> So we are using github flow, the way we work is development branch acts as our base or master branch and any new changes or fixes are done by creating a branch out from development & using github flow its merged back. The goal is always to use development as our base for all and to avoid merging the changes into dedicated branch like master which always gets deployed in the CI.

Yes you use the GitHub flow for managing code changes. But what I'm confused about is:
- Why don't you just run semantic-release on you base branch (`development`) to make a release whenever something is merged
- What is the point of the `rel-<date>-<month>-<year>` branch?

That's why I asked those question in my previous comment.

**Comment by ajaij** [comment]
Basically `rel-<date>-<month>-<year>` acts as our release branch, once the sprint changes are completed code freeze is done and a release branch is created with the above mentioned format.

Now, simultaneously QA will be testing in the release branch and developers start to push next sprint changes into the `development` branch.

semantic-release need to run on a manual trigger instead of every merge, hence we had to create a release branch, aggregate all the fixes and deploy with a single version bump. Hope this clarifies your doubt why I have created a release branch.

The main problem would be how to handle the scenario if some hotfix have to be done & correct app version is applied in both release & base branch.

**Comment by pvdlg** [comment]
> semantic-release need to run on a manual trigger instead of every merge, hence we had to create a release branch, aggregate all the fixes and deploy with a single version bump. Hope this clarifies your doubt why I have created a release branch.

The whole concept of semantic-release is to do continuous delivery. Which mean publishing automatically when a commit is pushed to `master` branch.
If you want to release version for QA tests I would recommend to use pre-releases: https://github.com/semantic-release/semantic-release/blob/master/docs/recipes/pre-releases.md 

If you don't want to automate the release trigger and want to manage that manually I would recommend to not use semantic-release. There is other tools with more limited scope that would automate the publishing of the package but not automate the release decision.
