### ISSUE TITLE
GitHub Enterprise Support

### ISSUE THREAD

**Issue by jrwebdev** [semantic-release/semantic-release#146]
I've been looking into what it would take to get this up and running with GitHub Enterprise - as far as I can see there are a couple of minor issues preventing it working out of the box:

1. `parse-github-repo-url` in `lib/verify.js` does not recognise non-GitHub URLs, therefore it returns an error that the repository field in package.json is malformed. Maybe this check could be skipped if `githubUrl` is specified in the config?
2. The ability to specify a `pathPrefix` to pass to `node-github`, given that GitHub Enterprise APIs are accessed via `/api/v3/[endpoint]` - see https://github.com/mikedeboer/node-github/pull/106. Maybe an extra config option could be added - `githubApiPathPrefix` - for this?

Happy to submit a PR if these are changes are ok

**Comment by hbetts** [comment]
@jrwebdev I wonder if #104 would resolve the first issue.

**Comment by boennemann** [comment]
I would love to see support for GHE.
I think we can remove the parse-github-repo-url check altogether, as that's also required for the GitLab PR to work #77.
Good to know that a pathPrefix is required for the node-github library. That should be added as an option.

Happy to accept PRs for this :)
