### ISSUE TITLE
Trigger a release from external sources

### ISSUE THREAD

**Issue by felipecassiors** [semantic-release/semantic-release#1466]
I use `semantic-release` [to release a Vagrant box](https://github.com/felipecassiors/ubuntu1804-4dev) to Vagrant Cloud (which is versioned with [semver.org](https://semver.org), just like `npm`). 

However, there are dependencies on the project that doesn't have the version number written somewhere as `package.json`. Sometimes the base box gets updated due to regular maintenance, sometimes I would want to simply re-release it, to have a more up-to-date box. After all, a simple `sudo apt-get dist-upgrade` in a matter of days could bring us a lot of packages upgraded.

This is different from the other issues because a new release with no fixes (or features) shouldn't bump the `patch` or `minor` indeed. However, we have the `build-number`, which in my opinion is exactly why it exists. R: https://semver.org/#spec-item-10

Example: 
Current version: `2.0.1`
Next version triggered by external sources: `2.0.1+1`, `2.0.1+2` and on.

This way I could set a kind of webhook to trigger a CI in Travis every time one of my dependencies get updated, or to set a cron job to build it every week if no new versions coming from GitHub.

It could be an environment variable or a CLI option I think.

**Comment by gr2m** [comment]
I use patch releases for cases such as this, semantic-release does not support build-number suffixes

**Comment by felipecassiors** [comment]
Yes, me too for now. This is the kind of commit I do currently to trigger a new release (with `patch` bump): https://github.com/felipecassiors/ubuntu1804-4dev/commit/ad35d18b1d84daec0f1ae344cfd3d3d623cbbb8b

However that doesn't seems right, after all I didn't fixed nothing.

**Comment by gr2m** [comment]
I agree it does not seem right, but it's a trade off between the complexity of the tool and the workflow. I'd always take a understandable workaround over creating techincal debt.

If it was possible to generate the next version with a plugin, then I'd suggest to do that, but it's not possible today as far as I know. It's core to the `semantic-release` package itself

**Comment by pvdlg** [comment]
The part after the `+` is for metadata only> Per the spec:
> Build metadata MUST be ignored when determining version precedence.

That means `2.0.1`, `2.0.1+1` and `2.0.1+2` are the same version from a semantic versioning perspective so they should contain the exact same artifact.
If I understand correctly that's not case for you as updating your dependencies will change the final artifact you are releasing. 

So, following the spec means that after updating your dependencies you should to release a `2.0.2` version and not a `2.0.1+1` so using a `fix` commit is correct from a release versioning perspective.
I would strongly recommend you to not stop using the metadata part of the version the way you currently do and to make a new patch release when upgrading your dependencies.

Regarding the semantic around the term `fix` for a dependency update, it is indeed not ideal. When you upgrade dependencies it might be to fix something, or add a feature or improve the performances. Sometimes you upgrade dependencies just as a good practice without knowing if it's going to have an actual impact on your project. As result it's very difficult to decide if the commit is a `fix`, `perf` or `feat`.
I think there is a legitimate case to be made to support a commit type such as `deps` which would describe commits that only update dependencies without having to specify the reason for the upgrade.

I would encourage you to open an issue with https://github.com/conventional-commits/conventionalcommits.org to make that explain that case.
