### ISSUE TITLE
CLI prerelease flag

### ISSUE THREAD

**Issue by skorodumoviktor** [semantic-release/semantic-release#1469]
## New feature motivation

It would be nice to have an option to trigger a pre-release flag using CLI. In my project, I want to trigger prerelease publishing via the GitLab-ci file inside a script field.

## New feature implementation

I see it like `semantic-release --branches BRANCH_NAME --prerelease`

**Comment by pvdlg** [comment]
semantic-release supports making pre-releases base on the branch the release is made from: https://github.com/semantic-release/semantic-release/blob/master/docs/recipes/pre-releases.md.

What would this option achieve that cannot be currently done? Can you explain what use case it would solve?

**Comment by skorodumoviktor** [comment]
> semantic-release supports making pre-releases base on the branch the release is made from: https://github.com/semantic-release/semantic-release/blob/master/docs/recipes/pre-releases.md.
> 
> What would this option achieve that cannot be currently done? Can you explain what use case it would solve?

Thank you @pvdlg for your comment.

Yes, I know about this way of making a prerelease branch. But in my case I want to pass this flag alongside with branch name directly via terminal script inside gitlab-ci file.  I’m doing so because I don’t want to edit the .releaserc file every time I create a new branch and want it to be a prerelease type. 
In our workflow we create a different branch for each issue or feature. Sometimes changes are made inside our internal packages but should be tested in applications. So in such cases we need to publish a specific version of these packages. Before using semantic release we published these branches like so: x.x.x-rc-branchname.x. simply by creating a new tag. But for now we have to specify brunch name for each branch inside .releaserc file and some of us finds it annoying) so as a workaround of this issue may be using cli but every time we’ll try it a release will be created but we want it to be a prerelease. That’s why I’m missing the prerelease flag in cli.

I hope you would get my point)

**Comment by pvdlg** [comment]
You can configure the `branches` option with a glob: https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#branches

This way you can have certain pattern of branch that would be automatically detected as a pre-release branch.

For example:
```
{
  "branches": ["master", {"name": 'rc-*', "prerelease": true}]
}
```

So any branch that begins with `rc-` will be considered a prerelease branch and a prerelease will be made when you commit to it.

**Comment by skorodumoviktor** [comment]
> You can configure the `branches` option with a glob: https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#branches
> 
> This way you can have certain pattern of branch name to be automatically detected as a pre-release branch.
> 
> For example:
> 
> ```
> {
>   "branches": ["master", {"name": 'rc-*', "prerelease": true}]
> }
> ```
> 
> So any branch that begins with `rc-` will be considered a prerelease branch and a prerelease will be made when you commit to it.

I know about this feature but it’s not working somehow. I tried different configurations and every time I use glob in my config semantic just throws an error saying I didn’t specify any release branches. That’s the story for another issue I suppose, but I decided to try my luck with CLI first. 
I can send my configs here as soon as I reach my computer. Maybe you can say what I’m doing wrong.

P.S Thanks for the answer!)

**Comment by skorodumoviktor** [comment]
@pvdlg OK I don't know what happened but I managed to prerelease using glob the way you showed me: 
```
{
  "branches": ["master", {"name": 'rc-*', "prerelease": true}]
}
```
although I tried it earlier...
closing this issue though

Thank you very much for your help!!!
