### ISSUE TITLE
Releasing a backport.

### ISSUE THREAD

**Issue by tthew** [semantic-release/semantic-release#147]
Imagine our @latest points at `v2.0.0`

We would like to backport and release a patch for the previous minor version; e.g our last minor release was `v1.6.x` the last patch on that minor release was `v1.6.2` and we would like to make a `v1.6.3` release.

What's the best way to approach this scenario?

**Comment by boennemann** [comment]
Hey @tthew,

there is a gist that describes this: https://gist.github.com/boennemann/54042374e49c7ade8910
Let me know if that works for you.

Best,
Stephan

**Comment by tthew** [comment]
@boennemann awesome. Exactly what I was looking for :) thanks!

**Comment by boennemann** [comment]
Awesome, thank you :)
