### ISSUE TITLE
Breaking change detection?

### ISSUE THREAD

**Issue by ZebraFlesh** [semantic-release/semantic-release#1475]
Has something changed with how breaking changes are detected by default? Looking back through my git commit history, it looks like `BREAKING CHANGE` used to trigger new major version, but now I am required to use `BREAKING CHANGE:` (with a trailing colon). I don't recall a release note item about this, but perhaps I missed it? Or is it a regression?

**Comment by pvdlg** [comment]
We use [conventional-changelog/conventional-changelog](https://github.com/conventional-changelog/conventional-changelog) to parse commits.
If a change happened it's over there. I would invite you to read their commit history and look at their changelog file to figure out.
