### ISSUE TITLE
Is it possible to update major (and possibly minor) versions upon release?

### ISSUE THREAD

**Issue by lucianposton** [semantic-release/semantic-release#1478]
Can semantic-release or its github plugin update major version tags per github's semantic versioning recommendation at https://help.github.com/en/actions/building-actions/about-actions#versioning-your-action ?

![screenshot-2020-03-03T02:37:52 411Z](https://user-images.githubusercontent.com/646121/75737590-bef10280-5cc5-11ea-93ec-862398c9a4ea.png)

e.g. when releasing `v2.1.5`, it should move the existing `v2` version from `v2.1.4` to `v2.1.5`. This appears to be a common paradigm wrt versioning github actions (even though moving tags around like that doesn't sit right with me).

If this is not currently possible, is there any plan to add this functionality to semantic-release or the semantic-release/github plugin?

**Comment by pvdlg** [comment]
Can you provide context? What are you trying to do? What is you workflow/config? How semantic-release is related to GitHub action is your case?

**Comment by lucianposton** [comment]
> Can you provide context?

@pvdlg The context is github actions development following the semantic versioning/release recommendations in the above github help doc in https://github.com/semantic-release/semantic-release/issues/1478#issue-574379094.

> What are you trying to do?

I'm trying to utilize `semantic-release` and `@semantic-release/github` as best as possible to build a CI/release workflow (https://help.github.com/en/actions if you're not familiar) that automates releases published to github's releases tab in a manner that follows semantic versioning and release recommendations in the above github help doc in https://github.com/semantic-release/semantic-release/issues/1478#issue-574379094.

> What is you workflow/config?  How semantic-release is related to GitHub action is your case?

I'm making the general case for github actions development using semantic-release in a way that aligns with existing versioning/release practices in the github actions dev ecosystem and with the semantic versioning recommendations in the above github help doc in https://github.com/semantic-release/semantic-release/issues/1478#issue-574379094.

Such a use case could be a repo where releases are handled by a CI workflow with a release step that essentially just does `semantic-release --branch master` with the `@semantic-release/github` plugin upon each github `push` event e.g. something like the following github workflow and `.releaserc`.

```yaml
on:
    push:
jobs:
    semantic-release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: # Your favorite action that calls semantic-release
```
```json
{
  "plugins": [
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    "@semantic-release/git",
    "@semantic-release/github"
  ]
}
```
I can build one if it would help you visualize the issue.

With that config and that github workflow that runs on each github `push` event, you get semantic versions as expected, `v1.0.0`, `v1.0.1`, etc on the github's release tab thanks to the `@semantic-release/github` plugin.

So far, so good. What's missing thus far is step 2 from the github's semantic release recommendations in their help doc in https://github.com/semantic-release/semantic-release/issues/1478#issue-574379094. **I expected the `@semantic-release/github` plugin would implement this functionality as the functionality is officially github recommended for semanticaly versioned releases, hence opening this question/issue to verify whether it is or not.**

![screenshot-2020-03-03T20:20:33 925Z](https://user-images.githubusercontent.com/646121/75816104-307a9080-5d5a-11ea-9794-6c1b4057eef3.png)

---

Some more background: Looking through some github actions, you'll see that they follow the recommendation of changing the major version release tag, e.g. `v1`, to point to the latest semantic release, e.g. `v1.1.3`, then `v.1.1.4`, then `v1.2.0` as they release new versions. This way when a workflow depends on `@v1` of an action, they will get the latest semantic release with major version `1`.

Here are some official github actions following this pattern, as described in the help article in the 1st post:
- https://github.com/actions/checkout/releases
- https://github.com/actions/setup-ruby/releases
- https://github.com/actions/create-release/releases
- https://github.com/actions/stale/releases

**Comment by pvdlg** [comment]
Thanks for the clarification. The plugin `@semantic-release/github` is meant to be used with any project that is hosted on GitHub. What you are asking is something specific to GitHub action development, which is not part of `@semantic-release/github` scope.

The functionalities specific to Github actions (moving a `v1`, `v2`, etc.. tag and maybe more in the future) could be implemented in a new plugin specific to GitHub actions.
Alternatively you can use https://github.com/semantic-release/exec to run a command to move the `vx` tag.

**Comment by lucianposton** [comment]
Thanks for the answer.

**Comment by pvdlg** [comment]
If you were to develop a plugin to implement such feature, we'd be happy to add it to https://github.com/semantic-release/semantic-release/blob/master/docs/extending/plugins-list.md

**Comment by travi** [comment]
just spotted this project that seems like it would be helpful for this use case: https://github.com/Actions-R-Us/actions-tagger
