### ISSUE TITLE
should use `branch` or `branches` in the release config ?

### ISSUE THREAD

**Issue by michellechsy** [semantic-release/semantic-release#1483]
## Current behavior

Currently, we are using the release.config.js to set up the semantic release for our project (with version 15.13.24), while in the configuration, we use the `branch` to define the branch which should be used for versioning, it's fine when we only build versions based on master branch. However, since we have separate our release branch once the features were released (e.g. 'release' branch), we will need to base on our release branch to create hotfix versions, in that case, we must change the release.config.js in release branch to make the `branch` to release branch name, which is a bit annoying. 

## Expected behavior

Based on the doc of this repo wiki (https://semantic-release.gitbook.io/semantic-release/usage/configuration#branches), there's an attribute `branches` instead of `branch`, however, when I used it in our project, it did not work. And also checked the source code of the 'semantic-release' package, it uses `branch`. So can anyone tell whether I should use `branch` or `branches`?

## Environment

- **semantic-release** version: 15.13.24
- CI environment: GitLab Runner
- Plugins used: 
@semantic-release/commit-analyzer
@semantic-release/release-notes-generator
@semantic-release/changelog
@semantic-release/npm
@semantic-release/gitlab
@semantic-release/git

- **semantic-release** configuration: 
![image](https://user-images.githubusercontent.com/7827768/76200716-11ce3b00-622d-11ea-821e-3af55f5de69f.png)

- CI logs: always said I'm using the 'master' branch when I used `branches`

**Comment by pvdlg** [comment]
You are using an outdate version. the change was made in https://github.com/semantic-release/semantic-release/releases/tag/v16.0.0

**Comment by michellechsy** [comment]
@pvdlg Thanks!! Will try with that version.
