### ISSUE TITLE
[Question] Publishing package to Artifactory

### ISSUE THREAD

**Issue by emirot** [semantic-release/semantic-release#1494]
Hi There,

I was looking in publishing package to artifactory and found:
 https://github.com/semantic-release/semantic-release/blob/ef1b8a0b910b81070a600c8c772434ec345812dd/docs/support/FAQ.md#can-i-use-semantic-release-to-publish-a-package-on-artifactory

Is it only for npm packages ? What should I add to push language agnostic packages ? Mostly docker images.

**Comment by pvdlg** [comment]
See https://github.com/semantic-release/semantic-release/blob/ef1b8a0b910b81070a600c8c772434ec345812dd/docs/support/FAQ.md#can-i-use-semantic-release-to-publish-non-javascript-packages

You will need to use a plugin for the type or artifact you want to publish or use the the https://github.com/semantic-release/exec plugin
