### ISSUE TITLE
Release causes two git commits

### ISSUE THREAD

**Issue by markjlaney** [semantic-release/semantic-release#1514]
Hello!

I have a question. I'm using an internal CI solution that is triggered every time that I push a commit. So when I merge develop into master, that will run a build. Then, during the build, semantic-release creates a new commit with the changelog. This triggers my build again. Is there any way that I can have this all take place with one git commit?

**Comment by gr2m** [comment]
> Is there any way that I can have this all take place with one git commit?

I don't think so 🤔 But the commit created by semantic release includes `[skip ci]` in its commit message, which is supported by all the CI providers, maybe you could add that feature to your custom CI solution?

**Comment by abdelrahmanahmed** [comment]
@gr2m not support by github action till now, so i added this condition until they support this 
` if: "!contains(github.event.head_commit.message, 'skip ci')"`

@markjlaney as @gr2m said, add a custom condition in your CI and check the commit message if it contains `[skip ci]`

**Comment by markjlaney** [comment]
Thanks for the tip @gr2m. I worked with our provider to get the support we need. It works great, thanks!
