### ISSUE TITLE
Document Development Process

### ISSUE THREAD

**Issue by hbetts** [semantic-release/semantic-release#152]
I am looking for a doc on how to work with the `semantic-release` transpiled code base for the purpose of developing an enhancement (In particular #150).

Right now I'm trying to run `semantic-release` locally in a test project with `node-debug` to step through my code, but having little luck (Ran into issues using `npm link`, then tried `npm install ../path`, only to encounter other issues, tried pushing build artifacts to github, and finally, for no known apparent reason, tried `npm link` again and it worked).

**Comment by boennemann** [comment]
Hey @hbetts,

I saw you opened a few issues and PRs and, even though it might not be the most satisfying answer, I'll try my best to review them after the holidays. I'm super sorry, but I currently don't have the time I'd like to have to document all of these things.

I'm trying to find a better way to maintain semantic-release, especially by it being a group effort. I've written a few thoughts down here: https://github.com/semantic-release/project-management/issues/1 and I'll try to address them, and reach out to people, in the new year.

All the best and thanks so much for your contributions,
Stephan

**Comment by mistycaseyward12** [comment]
Why
