### ISSUE TITLE
Separate repository paths for npm.com and npm.pkg.github.com

### ISSUE THREAD

**Issue by Skitionek** [semantic-release/semantic-release#1538]
## New feature motivation

I would like to be able to publish public package to npm and name-scoped version to github registry (scope is required).

## New feature description

Possibility of patching config on plugin basis gives more flexibility and possibly solves other issues with configuration.

## New feature implementation

To do so each plugin configuration can expose interface to locally overwrite values in used config.

## Used workaround

I have ended up with ugly workaround in my package.json:

```json
	"publishConfig": {
		"access": "public"
	},
	"release": {
		"plugins": [
			"@semantic-release/npm",
			[
				"@semantic-release/exec",
				{
					"prepare": "echo 'registry=https://npm.pkg.github.com/OWNER' > .npmrc",
					"publish": "echo 'registry=https://npm.pkg.github.com/OWNER' > .npmrc"
				}
			],
			"@semantic-release/github",
			[
				"@semantic-release/exec",
				{
					"prepare": "rm .npmrc",
					"publish": "rm .npmrc"
				}
			]
		]
	},
```

I couldn't find any documentation that this functionality is already provided.

**Comment by gr2m** [comment]
You can set the registry URL in your package.json:

```json
  "publishConfig": {
    "registry":"https://npm.pkg.github.com/"
  },
```

See https://help.github.com/en/packages/using-github-packages-with-your-projects-ecosystem/configuring-npm-for-use-with-github-packages#publishing-a-package-using-publishconfig-in-the-packagejson-file

**Comment by Skitionek** [comment]
Assuming package name is not scoped ("~~name: @user/package-name~~" but simply "name: package-name"). Setting is as you mentioned will prevent @semantic-release/github from working correctly (it only allows scoped packages).

**Comment by gr2m** [comment]
I'm sorry I don't follow. What keeps you from setting the `publishConfig.registry` setting only on scoped packages, but not on unscoped ones?

**Comment by Skitionek** [comment]
I have got fixated on idea of publishing package to two npm repositories on one go.
It is not anyhow actually needed so I am closing this issue.

Thank you for fast response.
