### ISSUE TITLE
setup error

### ISSUE THREAD

**Issue by yesvods** [semantic-release/semantic-release#155]
I caught errors below when inited my project.
➜  jsLibrary  semantic-release-cli setup
{ [Error: ENOENT: no such file or directory, open './package.json']
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: './package.json' }

version
npm: 3.3.12
node: 5.3.0

**Comment by boennemann** [comment]
The semantic-release-cli operates on existing projects. I looks like there is no `package.json` present in your current folder.

Should this keep failing for you, even with a package.json please reopen this issue on the cli repo's issue tracker: https://github.com/semantic-release/cli

Thank you!
