### ISSUE TITLE
Try to save up one byte in commit message

### ISSUE THREAD

**Issue by Ardeshir81** [semantic-release/semantic-release#1556]
## New feature motivation

To open up **1** extra character for commit title

## New feature description

Semantic release uses two parentheses to tell about scope of commit.
Wouldn't it be nice if another notation used to occupy only one byte?
e.g.:
`feat,pencil: added something`
`fix-pen: fixed something`
`perf@pencil: broke something`
etc...

I would have even argued about that `space` after `:` if it wasn't for human readability

## New feature implementation

:open_mouth:

**Comment by gr2m** [comment]
semantic-release uses https://github.com/semantic-release/commit-analyzer by default. There are lots of options available, via https://github.com/conventional-changelog/conventional-changelog. I'm pretty sure you can configure the commit message parsing to your likening :)

**Comment by Ardeshir81** [comment]
Thanks!
I didn't know about that much
Thank you very much :flower:
