### ISSUE TITLE
Could not get repository on Travis CI error

### ISSUE THREAD

**Issue by knowbody** [semantic-release/semantic-release#156]
I'm trying to set up the semantic release in my current project, after: 

```
semantic-release-cli setup
``` 

I get:

<img width="632" alt="screen shot 2015-12-29 at 13 36 39" src="https://cloud.githubusercontent.com/assets/3802023/12035114/3f68b284-ae31-11e5-9bc7-9772e7edacdf.png">

Travis CI has permissions to the GH repo.

**Comment by christiansakai** [comment]
me too +1

**Comment by christiansakai** [comment]
@knowbody I figured out the issue. I need to setup my Travis CI account first. After I set it up to be synced with the related github repo, it works

**Comment by boennemann** [comment]
It looks like that there is no TravisCI account existing, but I agree that the error message isn't very helpful. Please reopen this on CLI https://github.com/semantic-release/cli so we can address it there.

Thanks for your reports.

**Comment by knowbody** [comment]
@christiansakai what do you mean by:

>  I need to setup my Travis CI account first

I have the Travis CI set up and all the repos are synced...

@boennemann thanks! I'll reopen it on the CLI issues
