### ISSUE TITLE
[GitHub Actions] "cannot push the version tag to the branch master on the remote Git repository with URL https://x-access-token:[secure]@github.com/[repository].js.git

### ISSUE THREAD

**Issue by gr2m** [semantic-release/semantic-release#1560]
## Current behavior

Starting today, semantic-release fails when run from a GitHub Action. See issue created since today by semantic-release from a GitHub Action: https://github.com/issues?q=is%3Aopen+is%3Aissue+label%3Asemantic-release+created%3A%3E2020-05-21+author%3Aapp%2Fgithub-actions

It looks to me as if `git push` using the `https://x-access-token:` prefix is no longer possible.

I've contacted support and will update this issue. Please use the thumbs up emoji reaction if you experience the same problem

## Environment

- **semantic-release** version: 17.0.7
- CI environment: GitHub Actions
- Plugins used: default
- **semantic-release** configuration: default
- CI logs: https://github.com/octokit/request-error.js/runs/700370387?check_suite_focus=true#step:6:20

**Comment by jakobrosenberg** [comment]
Thanks for the notification @gr2m.

**Comment by gr2m** [comment]
I was informed that the problem might also be related to the active incident:
https://www.githubstatus.com/incidents/6tcfpztf6j9m

**Comment by C0ZEN** [comment]
@gr2m the way this project handle the denial of services is amazingly cool. Nice work here and thank you for time given to this issue.

**Comment by ericsciple** [comment]
Sorry for the disruption. There is an active incident related to the GITHUB_TOKEN permissions. Related to https://github.com/actions/checkout/issues/254 - private repos are failing to clone.

**Comment by C0ZEN** [comment]
The release was successfully for me.

**Comment by gnarea** [comment]
Same here. :tada: Thanks once again @gr2m for looking into this and for pinging those of us outside your organisations!

**Comment by gr2m** [comment]
thanks for reporting back. The problems seems to be resolved :) Great job GitHub DevOps folks 👏
