### ISSUE TITLE
Question: keywords to trigger patch release

### ISSUE THREAD

**Issue by hamzahamidi** [semantic-release/semantic-release#1561]
Hi thank you for this amazing repository.
I have a question please.
What are the keywords in commit message to trigger a patch release aside from the fix keyword?
Thank you

**Comment by gr2m** [comment]
See https://github.com/semantic-release/commit-analyzer, it's highly configurable

**Comment by gr2m** [comment]
oh sorry, I've misread your question. By default, it's just `fix`. But you can configure other prefixes yourself as documented in the plugin's repository linked above
