### ISSUE TITLE
Fast-forward to a specific semantic-release version

### ISSUE THREAD

**Issue by sseekamp0** [semantic-release/semantic-release#1579]
## New feature motivation

Hello,
I'm not sure if it's already available or not, but it would be nice if semantic-release allowed us to update our version manually (a.k.a fast forward to a specific version).

After an hour of looking I haven't been able to find a way to update my to a specified version.

The application that I'm trying to implement semantic-release on is already at 2.1.3. Semantic-release tries to publish 1.0.0 every time even though there are already tags in my GitLab repository for 2.1.3. Is there already a way to do this? Or would this be a new feature?

## New feature description

Fast-forward versions on demand for users integrating semantic-release into an existing project.

**Comment by travi** [comment]
make sure that the commit at the point that your previous version was published from is tagged in git with the version that it was published as. also, ensure that the version number is preceded with a `v`, so in your case, the tag should be `v2.1.3`. if that exists, semantic-release should increment from there to determine the next version

**Comment by sseekamp0** [comment]
That was it. Thank you @travi. My mistake.
