### ISSUE TITLE
CircleCi prereleases

### ISSUE THREAD

**Issue by poteirard** [semantic-release/semantic-release#1584]
## Current behaviour

I'm trying to setup prereleases as it describes [here](https://github.com/semantic-release/semantic-release/blob/master/docs/recipes/pre-releases.md#publishing-pre-releases) but I'm getting this message and it's not triggering publish:

> [9:22:45 AM] [semantic-release] › ℹ  This test run was triggered on the branch undefined, while semantic-release is configured to only publish from master, beta, therefore a new version won’t be published.

## Expected behaviour

I added a breaking change in my `beta` branch ([PR](https://github.com/zopaUK/react-components/pull/529)) and I was expecting to publish a beta version automatically.

## Environment

- **semantic-release** version: 17.1.0
- CI environment: CircleCi
- Plugins used: 
```
    '@semantic-release/commit-analyzer',
    '@semantic-release/release-notes-generator',
    '@semantic-release/changelog',
    '@semantic-release/npm',
    '@semantic-release/git',
    '@semantic-release/github',
```
- **semantic-release** configuration: https://github.com/zopaUK/react-components/blob/de6dc05aed036a66e65c7ee30f1961f18f3cfbaa/.circleci/config.yml

**Comment by gr2m** [comment]
Is this resolved by https://github.com/semantic-release/semantic-release/pull/1521?

**Comment by poteirard** [comment]
Yes it works now after updating semantic-release! Thank you <3 !
