### ISSUE TITLE
Commit message format description for perf is not consistent across documentation

### ISSUE THREAD

**Issue by saniaalex** [semantic-release/semantic-release#1585]
## Current behavior

In ReadMe , perf is said to do a major version update but the github FAQ doc says that perf does a patch version update. Which of these is accurate?

## Expected behavior

I had commits with fix, feat and perf the same PR and the merge updated the minor version. My understanding is that the highest type is picked, meaning a major version update is picked over a minor version update. I was expecting the major version to get updated as the commits had perf but looks like only minor version got updated contributed by feat commit.

Attaching screenshots with conflicting docs-
<img width="949" alt="Screen Shot 2020-06-25 at 10 39 14 AM" src="https://user-images.githubusercontent.com/15204574/85743292-e97e2580-b6d1-11ea-9c87-4dbd1e0cdf9a.png">
<img width="933" alt="Screen Shot 2020-06-25 at 10 39 42 AM" src="https://user-images.githubusercontent.com/15204574/85743335-f3078d80-b6d1-11ea-9d53-ad4544c86725.png">

## Environment

- **semantic-release** version: 
- CI environment: 
- Plugins used: 
- **semantic-release** configuration: 
- CI logs:

**Comment by travi** [comment]
the bit about the section you highlight from the readme that may be a little confusing is that the type is `perf`, but the body also includes `BREAKING CHANGE: `. in this case the `BREAKING CHANGE: ` takes precedence over the `perf` type. a breaking change can be applied to any commit type, including ones that would not normally trigger a release at all, like `chore`.

**Comment by saniaalex** [comment]
> the bit about the section you highlight from the readme that may be a little confusing is that the type is `perf`, but the body also includes `BREAKING CHANGE: `. in this case the `BREAKING CHANGE: ` takes precedence over the `perf` type. a breaking change can be applied to any commit type, including ones that would not normally trigger a release at all, like `chore`.

@travi thanks for the response. So basically then perf is a patch release and the description in the image is just saying that BreakingChange takes precedence over it. Is that correct?

**Comment by travi** [comment]
> perf is a patch release and the description in the image is just saying that BreakingChange takes precedence over it. Is that correct?

correct. in that particular case, the commit type really doesnt matter because `BREAKING CHANGE: ` takes precedence over all of them.

**Comment by saniaalex** [comment]
> > perf is a patch release and the description in the image is just saying that BreakingChange takes precedence over it. Is that correct?
> 
> correct. in that particular case, the commit type really doesnt matter because `BREAKING CHANGE: ` takes precedence over all of them.

Thanks!
