### ISSUE TITLE
(Documentation Contribution) Add Recipe For Jenkins CI Configuration

### ISSUE THREAD

**Issue by kopal2212** [semantic-release/semantic-release#1586]
We have adopted the Semantic Release in our projects with Git Workflow **with Jenkins as CI**. I would like to contribute to this documentation https://semantic-release.gitbook.io/semantic-release/recipes/recipes for Jenkins(Since for now it's just limited to CircleCI 2.0, Travis CI and GitLab CI).
Let me know if I can open a pull request for the same.
@gr2m @pvdlg 
Thanks.

**Comment by gr2m** [comment]
Thank you Kopal, documentation pull requests are the best pull requests :) We would very much appreciate a pull request

**Comment by kopal2212** [comment]
Thanks, @gr2m. I have opened a pull request for the same. #1591
