### ISSUE TITLE
First time setup with non GH enterprise fails

### ISSUE THREAD

**Issue by Steven-Harris** [semantic-release/semantic-release#1590]
## Current behavior
When I run `npx semantic-release-cli setup` the cli tries to validate the unset github repo url of 'undefined'.

## Expected behavior

Setup runs like normal

## Environment

- **semantic-release** version: "^17.1.1"
- CI environment: "5.2.1"
- Plugins used: none
- **semantic-release** configuration: n/a
- CI logs
>Are you using GitHub Enterprise? No
ERR! semantic-release Error: GitHub repository URL is invalid: https:undefined.git
ERR! semantic-release     at module.exports (C:/Users/SteHarris/AppData/Local/Yarn/Data/global/node_modules/semantic-release-cli/src/lib/repository.js:69:11)
ERR! semantic-release     at processTicksAndRejections (internal/process/task_queues.js:89:5)
ERR! semantic-release     at module.exports (C:/Users/SteHarris/AppData/Local/Yarn/Data/global/node_modules/semantic-release-cli/src/index.js:85:5)
ERR! semantic-release  Error: GitHub repository URL is invalid: https:undefined.git
ERR! semantic-release     at module.exports (C:/Users/SteHarris/AppData/Local/Yarn/Data/global/node_modules/semantic-release-cli/src/lib/repository.js:69:11)
ERR! semantic-release     at processTicksAndRejections (internal/process/task_queues.js:89:5)
ERR! semantic-release     at module.exports (C:/Users/SteHarris/AppData/Local/Yarn/Data/global/node_modules/semantic-release-cli/src/index.js:85:5) {
ERR! semantic-release   stack: 'Error: GitHub repository URL is invalid: https:undefined.git\n    ' +
ERR! semantic-release     'at module.exports ' +
ERR! semantic-release     '(C:/Users/SteHarris/AppData/Local/Yarn/Data/global/node_modules/semantic-release-cli/src/lib/repository.js:69:11)\n' +
ERR! semantic-release     '    at processTicksAndRejections ' +
ERR! semantic-release     '(internal/process/task_queues.js:89:5)\n    at module.exports ' +
ERR! semantic-release     '(C:/Users/SteHarris/AppData/Local/Yarn/Data/global/node_modules/semantic-release-cli/src/index.js:85:5)' 
ERR! semantic-release }

**Comment by ScottChapman** [comment]
Is there any work around for this? We are looking to deploy this in our GHE and this would kind of be a bit of a blocker...

**Comment by mario-jerkovic** [comment]
@Steven-Harris have you managed to find a solution?

**Comment by gethari** [comment]
Facing the same

**Comment by mkermani144** [comment]
For me, the solution was to add `repository` to my `package.json`:

```json
{
  "...": "...",
  "repository": {
    "type": "git",
    "url": "<repository-url>"
  }
}
```

**Comment by hitshydev** [comment]
@mkermani144 it worked for me while using a self-hosted Gitlab instance. I added `https://gitlab.my-instance.com/repo.git` to `package.json` as `repository.url`.
