### ISSUE TITLE
Deploying build artifact to github without source code

### ISSUE THREAD

**Issue by karadikidd** [semantic-release/semantic-release#1597]
## Current behavior

I'm trying to understand if it is possible to publish new releases to github without the source code.
I have some custom binaries which are being published using "assets" but I wonder if I can omit the source code archives from publishing as well.

## Expected behavior

Only the files configured under `assets` get published, without the source code.
Preferably using some key in the `publish` step. 

## Environment

- **semantic-release** version: 17.1.1
- CI environment: GitHub Actions
- Plugins used: @semantic-release/commit-analyzer, @semantic-release/release-notes-generator, @semantic-release/github
- **semantic-release** configuration: 
```
"release": {
    "branches": "master",
    "verifyConditions": [
      "@semantic-release/github"
    ],
    "publish": [
      [
        "@semantic-release/github",
        {
          "assets": [
            {
              "path": "path to some file",
              "label": "some name"
            },
            {
              "path": "path to some other file",
              "label": "some other name"
            }
          ]
        }
      ]
    ],
    "success": [
      "@semantic-release/github"
    ],
    "fail": [
      "@semantic-release/github"
    ]
  }
```
- CI logs: NA

**Comment by gr2m** [comment]
The source code assets are added automatically by GitHub, they are not coming from semantic-release. There is no way to disable them, I'm afraid
