### ISSUE TITLE
@semantic-release/github 404 with valid token

### ISSUE THREAD

**Issue by DanielTamkin** [semantic-release/semantic-release#1612]
## Current behavior

semantic-release goes about it's business, however once it comes to the check of `@semantic-release/github` it hard fails. Stating a 404 error prevented it any further. The master branch is not in a protected state. I set this so to debug _why_ this plugin was not working.
![image](https://user-images.githubusercontent.com/9532762/89078687-7a3bc700-d34a-11ea-831f-b5797b44ecdd.png)

## Expected behavior

Publish the release to github using `@semantic-release/github`

## Environment

- **semantic-release** version: 17.0.4
- CI environment: GitHub Actions
- Plugins used: @semantic-release/github
- **semantic-release** configuration: [package.json](https://github.com/DanielTamkin/release-test/blob/master/package.json)
- CI logs: [GitHub Action logs](https://github.com/DanielTamkin/release-test/runs/933641723?check_suite_focus=true)

**Comment by DanielTamkin** [comment]
Could not find a related Issue / PR across the semantic-release org. I gather the 404 is either a bad API url or the GitHub masking if it's a true bad auth so not to give away the validity of the repos existence.

**Comment by DanielTamkin** [comment]
Found some more info on this. Looks to be an issue with @octokit/request.js right now; [This issue points](https://github.com/octokit/request.js/issues/214) directly to the exact error presented. Very interesting. Hope a fix is found on that end that results in no breaking on this end.

**Comment by gr2m** [comment]
Looks like the problem is the trailing `/` in your repository name

https://github.com/DanielTamkin/release-test/runs/933641723?check_suite_focus=true#step:7:98

Try to update https://github.com/DanielTamkin/release-test/blob/master/package.json#L7 and see if it works then. We use a package to normalize the `"repository"` value, I'd expect it to remove a trailing slash, but maybe it doesn't

**Comment by DanielTamkin** [comment]
Thank you @gr2m ! works fine now. So so happy to get this tech working. Thanks a million

**Comment by gr2m** [comment]
Thanks for confirming!
