### ISSUE TITLE
Prevent commenting on PRs

### ISSUE THREAD

**Issue by AnassZaki** [semantic-release/semantic-release#1619]
## New feature motivation
In most cases, I don't want the run to start commenting on each Pull request introduced in the release.

## New feature description
Pass a flag or a config that prevents semantic-release from commenting on each Pull Request added to the release.

**Comment by travi** [comment]
please see https://github.com/semantic-release/github#options for details on disabling the comments

**Comment by oliveira-alexdias-wex** [comment]
@travi I have the following `.releaserc` file but I am still getting PR comments.

![image](https://github.com/semantic-release/semantic-release/assets/107505668/efd4d710-8890-411a-b666-b59ca0b4a737)

Any tips on how to disable it?

```
{
    "branches": ["main"],
    "plugins": [
		"@semantic-release/commit-analyzer", 
		"@semantic-release/release-notes-generator",
		"@semantic-release/changelog",
		"@semantic-release/github",
		["@semantic-release/exec", {
			"prepareCmd": "echo ${nextRelease.version} > version.txt"
		}],
		["@semantic-release/git", {
			"assets": ["version.txt"],
			"message": "chore(release): ${nextRelease.version} [skip ci]",
			"successComment": false
		}]
	]
}
```

**Comment by travi** [comment]
@oliveira-alexdias-wex please do not ping maintainers directly for support questions.

> Any tips on how to disable it?

note that the link to the documentation above is for the github plugin. it looks like you've applied the config to the git plugin instead.
