### ISSUE TITLE
Unclear Request Error feedback

### ISSUE THREAD

**Issue by mhartington** [semantic-release/semantic-release#1627]
## Current behavior

While adding semantic release to a project, I'm getting HTTP Request errors with reports of 404 when publishing with the github plugin. Not sure if it's related to my config or what, but there doesn't seem to be any actionable output.

## Expected behavior

If there is an error, suggested results should be printed out in order to help resolve the issue.

## Environment

- **semantic-release**     "semantic-release": "^17.1.1",
- CI environment: Github Actions
- Plugins used: 

```
      "@semantic-release/changelog",
      "@semantic-release/npm",
      "@semantic-release/github",
      "@semantic-release/git"
```

- **semantic-release** configuration: [here](https://github.com/ionic-team/ionic-storage/blob/main/package.json#L74-L102)
- CI logs: [here](https://github.com/ionic-team/ionic-storage/runs/1062765780?check_suite_focus=true#step:6:77)

**Comment by gr2m** [comment]
closing in favor of https://github.com/semantic-release/github/issues/283
