### ISSUE TITLE
Race condition on monorepo

### ISSUE THREAD

**Issue by guumaster** [semantic-release/semantic-release#1628]
## Current behavior

(NOTE: I'm reporting this here instead of monorepo plugin because the task of pushing tags and notes is done here and not in the plugins)

We are using `semantic-release` with the plugin `semantic-release-monorepo`. Our configuration for each component is fairly simple (see below):

The problem comes when running this on CI pipelines for multiple components of the monorepo. If you run this in parallel for component A, B and C, when component A push a tags (and notes) to git, component B and C fails to push due to being outdated. 

I'm calling it a "race condition" because it only happens when some commits trigger more than one component at the same time. On these cases, the firsts components (maybe one or two, depending how long each one takes) get published correctly, and all others after that fails. But it fails on pushing git notes (not release notes) and not on pushing tags.

## Expected behavior

Publish git tag and git notes without getting outdated commit.

## Environment

- **semantic-release** version: 17.1.1
- CI environment: GitlabCI
- Plugins used: semantic-release-monorepo
- **semantic-release** configuration:
```
"dependencies": {  
  "semantic-release": "17.1.1",  
  "semantic-release-monorepo": "7.0.2"  
},  
"release": {  
  "extends": "semantic-release-monorepo",  
  "plugins": [  
    "@semantic-release/commit-analyzer",  
    "@semantic-release/release-notes-generator"  
  ]  
}
```

- CI logs:
```
2:06:34 PM] [semantic-release] An error occurred while running semantic-release: { Error: Command failed with exit code 1: git push https://[secure]@github.com/MY_USER/MY_REPO.git refs/notes/semantic-release
To https://github.com/MY_USER/MY_REPO.git
 ! [rejected]          refs/notes/semantic-release -> refs/notes/semantic-release (fetch first)
error: failed to push some refs to 'https://[secure]@github.com/MY_USER/MY_REPO.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
    at makeError (/builds/__MY_REPO__/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/builds/__MY_REPO__/node_modules/execa/index.js:114:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  shortMessage:
   'Command failed with exit code 1: git push https://[secure]@github.com/MY_USER/MY_REPO.git refs/notes/semantic-release',
  command:
   'git push https://[secure]@github.com/MY_USER/MY_REPO.git refs/notes/semantic-release',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr:
   'To https://github.com/MY_USER/MY_REPO.git\n ! [rejected]          refs/notes/semantic-release -> refs/notes/semantic-release (fetch first)\nerror: failed to push some refs to \'https://[secure]@github.com/MY_USER/MY_REPO.git\'\nhint: Updates were rejected because the remote contains work that you do\nhint: not have locally. This is usually caused by another repository pushing\nhint: to the same ref. You may want to first integrate the remote changes\nhint: (e.g., \'git pull ...\') before pushing again.\nhint: See the \'Note about fast-forwards\' in \'git push --help\' for details.',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false }
```

**Comment by travi** [comment]
at this time, `semantic-release` officially _does not_ support monorepos. there is an [open issue](https://github.com/semantic-release/semantic-release/issues/193) tracking comments around the desire to add support, but there are no immediate plans to move forward with that at this time. the complexity that you mention is one of the complexities influencing that decision.

while `semantic-release-monorepo` is not an official plugin, i can see from its readme that using `--concurrency 1` is suggested in order to avoid this issue. if you intend to use `semantic-release` with a monorepo, you are a bit on your own for working around things like this that are not official features.

**Comment by guumaster** [comment]
We are not using `lerna`, that parameter doesn't apply in our case. Thanks for replying, I'll be tracking that other issue.

**Comment by JoA-MoS** [comment]
semantic-release-plus but as for the race condition you should run the release tasks in series rather than in parallel and all with the same shared workspace.

**Comment by hashilbasheer** [comment]
i have the similar issue with github action and helm chart repo.
