### ISSUE TITLE
Is there a way to publish on github and npm at the same time?

### ISSUE THREAD

**Issue by roggervalf** [semantic-release/semantic-release#1631]
This is a question since I would like to do this, but right now I'm doing it only to npm and for github registry I have to do it manually, so I would like to know if this is possible. Thanks for maintaining this package.

**Comment by gr2m** [comment]
I was looking into that a while ago but found that there is not really a good use case for it. You can use the `@semantic-release/npm` plugin to publish to either the npm registry or GitHub's registry, I don't see a reason why you would want to publish to both?

**Comment by roggervalf** [comment]
Hi @gr2m, thank you for the quick response. Yeah I'm using this plugin, I've been publishing my package also to Github's registry to make my package also available for this. I think I could close this for now.
