### ISSUE TITLE
Gravatar icon to add to the email of semantic-release-bot

### ISSUE THREAD

**Issue by pspkurara** [semantic-release/semantic-release#1633]
## New feature motivation

I'm using Git Extensions and there I see a Gravatar icon depending on the email
It exists in github-bot but not in semantic-release-bot
This is like the standard mechanism of the Git system, so I hope you will support it.

## New feature description

https://gravatar.com/
Used as an icon in certain software :+1: 

## New feature implementation

1. Register your email address in  Gravatar! (Semantic-release-bot@martynus.net)
2. Set icons in Gravatar! (It's easy to understand, so I recommend the same as the twitter icon in semantic-release)
3. Enjoy!

description: https://gravatar.com/support/how-to-sign-up/

**Comment by gr2m** [comment]
Done: http://www.gravatar.com/avatar/1c87c08320b0f71012b42d1259e51de9 <img src="http://www.gravatar.com/avatar/1c87c08320b0f71012b42d1259e51de9">

Thanks!

**Comment by pspkurara** [comment]
awesome! it was reflected! thx man!
