### ISSUE TITLE
Wrong comments for function addNote

### ISSUE THREAD

**Issue by virgilwashere** [semantic-release/semantic-release#1634]
https://github.com/semantic-release/semantic-release/blob/9635f50da67f252ef1d495d8b2c7cc3a7cde717c/lib/git.js#L321-L327

The `addNote` function has the same description as `getNote`

Suggest
https://github.com/semantic-release/semantic-release/blob/9635f50da67f252ef1d495d8b2c7cc3a7cde717c/lib/git.js#L321
 should be something like:

```suggestion
* Add JSON note to a given reference.
```

**Comment by travi** [comment]
thanks for pointing this out. would you like to submit a PR to make the change?

**Comment by ashishsantikari** [comment]
Can I submit a PR? I see, this is not reflected on the master branch.

**Comment by gr2m** [comment]
@ashishsantikari sure 👍🏼

**Comment by ashishsantikari** [comment]
@gr2m https://github.com/semantic-release/semantic-release/pull/1833
