### ISSUE TITLE
Accept BREAKING CHANGE"S" as major release trigger

### ISSUE THREAD

**Issue by vis97c** [semantic-release/semantic-release#1635]
## New feature motivation

Currently to trigger a major release it is required to add BREAKING CHANGE to the body while this is not a problem there are moments where we could be adding more than a change. So i think it would be nice to accept this plural "BREAKING CHANGES", this would also prevent minor releases when we include the "s" at the by accident. I experienced this a lot, maybe because english is not my first language and i forgot to write the keyword as singular.

## New feature description

This requires the commit analyzer to check wheter or not there is "BREAKING CHANGE" | "BREAKING CHANGES" present in the commit body

## New feature implementation

I haven't check the code but it looks like an "or" could do the trick.

**Comment by travi** [comment]
we use https://github.com/conventional-changelog/conventional-changelog to parse commits. requests to make any adjustments to how commits are parse would need to be proposed there.

you could also consider tools like [commitizen](https://commitizen.github.io/cz-cli/) and/or [commitlint](https://commitlint.js.org/) to help avoid problems like the one you mention.

**Comment by vis97c** [comment]
Ok, thanks for the advice. I'm closing the issue then
