### ISSUE TITLE
Use prefix in commit messages in all repository & release/tag only one folder from repository. It is possible?

### ISSUE THREAD

**Issue by patrjam** [semantic-release/semantic-release#1637]
Hi,

I have repository structure something like this:
```
project-repository
│   README.md
│   package.json   
│   ... 
└───my-developed-package
│   │   README.md
│   │   ...
└───someAnotherFolder
│   │   ...
└───src
│   └───subFolder
│   │   someClass.js
│   │   │   ...
```

I use `semantic-release` for autorelease package, but for me is not clear/ didn't find my case.
I always want use prefixes `perf/feat/fix` in commit messages, but want release only folder `my-developed-package`. 

I use this configuration file `.releaserc` :
```
{
    branches: ["master"],
    plugins: [
        "@semantic-release/commit-analyzer",
        "@semantic-release/release-notes-generator",
       [
           "@semantic-release/changelog",
            {
                "changelogFile": ".my-developed-package/CHANGELOG.md",
                "changelogTitle": "# Semantic Versioning Changelog"
            }
       ],
       ["@semantic-release/npm", {
            "npmPublish": true, 
            "pkgRoot": "./my-developed-package"
    }],
        ["@semantic-release/gitlab", {
            "gitlabUrl": "xxx",
    }],
          "@semantic-release/git"
    ]
}
```

But If I change something out of `my-developed-package` folder and use commit message with prefix, `semantic-release` always release new version of my package without no changes, but it is tagged as new version.

What Iam doing wrong, what type of configuration is missing, or its standard behavior of `semantic-release`?

Thank you for your answer.

**Comment by travi** [comment]
semantic-release is intended for use cases where the package and repository are 1:1. there are open requests for monorepo support, which touch on the needs you mention. you could follow and contribute to those discussions, but semantic-release does not support this type of a use case today.
