### ISSUE TITLE
EINVALIDNEXTVERSION  (out of range) when releasing on maintenance branch 

### ISSUE THREAD

**Issue by alvarosaburido** [semantic-release/semantic-release#1642]
Hello, I'm having an issue on my [library](https://github.com/alvarosaburido/vue-dynamic-forms) when trying to release a new feature or fixing a bug on the `default` `0.x` branch (maintenance)

## Current behavior

-  Default Branch `0.x` 
-  There is no  `master` 
-  `next` branch releases `1.x.x` correctly when PR is open against it.

If I merge any feat, bugfix  to `0.x` I get the following [error](https://github.com/alvarosaburido/vue-dynamic-forms/runs/1175093358?check_suite_focus=true
)

```
[6:58:35 AM] [semantic-release] › ✖  EINVALIDNEXTVERSION The release `0.5.0` on branch `0.x` cannot be published as it is out of range.
Based on the releases published on other branches, only versions within the range >=1.0.0 <1.0.0 can be published from branch 0.x.

The following commits are responsible for the invalid release:

    * Merge pull request #111 from alvarosaburido/update-deps-nuxt-demo (6aecdfa)
    * feat(deps): update demo nuxt dependencies (4fba838)
    * Merge pull request #108 from alvarosaburido/update-rollup-deps (9b0b27a)
    * feat(deps): updated deps for. rollup (850460c)
    * Merge pull request #105 from alvarosaburido/migrate-0x-build-system-to-rollup (6e32d98)
    * feat(build): migrate build system to rollup 0.x (338c637)

Those commits should be moved to a valid branch with git merge (https://git-scm.com/docs/git-merge) or git cherry-pick (https://git-scm.com/docs/git-cherry-pick) and removed from branch 0.x with git revert (https://git-scm.com/docs/git-revert) or git reset (https://git-scm.com/docs/git-reset).

A valid branch could be next.

```
## Expected behavior

- Any PR against `0.x` should  trigger a `0.x` release, example `0.5.0` in this case
- Any PR against `next` should  continue to trigger a `1.x` release, example `1.3.0`

## Environment

- **semantic-release** version: 17.1.2
- CI environment: Github Actions https://github.com/marketplace/actions/action-for-semantic-release
- Plugins used: None
- **semantic-release** configuration: [.github/release.yml](https://github.com/alvarosaburido/vue-dynamic-forms/blob/0.x/.github/workflows/release.yml), [.github/semantic.yml](https://github.com/alvarosaburido/vue-dynamic-forms/blob/0.x/.github/semantic.yml) and  in package.json: 
```
"release": {
    "branches": [
      "0.x",
      "next"
    ]
  },
```
- CI logs: https://github.com/alvarosaburido/vue-dynamic-forms/runs/1175093358?check_suite_focus=true

I'm not sure if it's something related to this repo itself or to the [Github Action](https://github.com/cycjimmy/semantic-release-action), please let me know to move it if necessary.

If you need any other `log` or info let me know.

Thank you very much in advance!

**Comment by travi** [comment]
versions prior to v1.0.0 are not supported by semantic-release. please see [this FAQ](https://semantic-release.gitbook.io/semantic-release/support/faq#can-i-set-the-initial-release-version-of-my-package-to-0-0-1)

**Comment by alvarosaburido** [comment]
@travi oh, I learned something new, didn't know about the `0.0.x` limitation. Thanks  for pointing me to the correct direction

Before closing the  issue, what would happen if  I add a breaking change on the `main`  branch  (previous `0.x`) to force it to go to 1.x.x, `next`  branch currently goes for `1.5.1`. It would take the next 1.6.0 or directly a 2.x.x version?

**Comment by travi** [comment]
this is a little bit of a unique situation because you'll be adding the `v1.0.0` tag after your `next` branch was started, so i'm hesitant to suggest the exact behavior and end up being wrong. if you want to know the version that will be published before it actually happens, your best bet would be to use the [`--dry-run` flag](https://semantic-release.gitbook.io/semantic-release/usage/configuration#dryrun). also note that your update to the default branch wont be recognized until you merge (be sure not to rebase or otherwise rewrite history) into your `next` branch

**Comment by travi** [comment]
also, since you've mentioned default branch names that are not `master`, please be aware of the current state of https://github.com/semantic-release/semantic-release/issues/1581

**Comment by alvarosaburido** [comment]
Thanks for the help @travi, sorry for  the stack of questions haha, 

`your best bet would be to use the --dry-run flag.` I should add this one to the `.github/release.yml`? If  I understand correctly the docs it will show me what would be the next release version without actually publishing anything to npm.

**Comment by travi** [comment]
> I should add this one to the .github/release.yml?

you can add it to the cli command, wherever you are executing the `semantic-release` command.

> If I understand correctly the docs it will show me what would be the next release version without actually publishing anything to npm.

correct
