### ISSUE TITLE
options to support not using `git notes`

### ISSUE THREAD

**Issue by aquariuslt** [semantic-release/semantic-release#1646]
### Background

I want to use `semantic-release` in company's internal git server to standardize inner scope npm package release flow.

The paint-point for internal git server is **not support git notes(and no support plan in future)** and `semantic-release` using git notes features,.

So if `semantic-release` support options to disable `git notes` usage, I can easily integrate the release flow.

## New feature description

support options to disable `git notes`, which will not call `getNotes()` and `addNotes()` command. 

cli arguments (options) like below:

```
--wo-notes

Will skip git notes checking and updating command
```

**Comment by gr2m** [comment]
I'm afraid that won't be possible, we use `git notes` for the multi-branch release feature, there is no way to disable that.

**Comment by greg0ire** [comment]
It would be great to be able to disable it, because even if your server supports git notes, then you might stumble on https://github.com/semantic-release/semantic-release/issues/1479 even if you are not using multi-branch releases
