### ISSUE TITLE
Allow overriding the generated major minor and patch version number.

### ISSUE THREAD

**Issue by Goobles** [semantic-release/semantic-release#1653]
## New feature motivation
I am using semantic release to generate releases/changelogs on Github for Salesforce Managed Packages, which are created on their platform. The problem is: the Salesforce platform generates the version number, I do not have control over this. I know this technically breaks SemVer's specification. Sometimes it happens that the version Salesforce generates doesn't match the version number semantic-release generates.

I have a script that publishes a new version, this script returns the new version that was just published on the Salesforce platform.

Right now I have a setup where I have to edit the previous release tag in git to a version right before the one salesforce would generate, when they are out of sync.

There is currently no way for me to just plug in the externally generated version number into semantic-release's configuration

## New feature implementation

Allow overriding the newly created major, minor and patch versions in the "Verify release" step.

**Comment by gr2m** [comment]
You might be able to do that be replacing the default https://github.com/semantic-release/commit-analyzer#readme plugin with your own implementation. See the plugin docs at https://semantic-release.gitbook.io/semantic-release/usage/plugins

**Comment by Goobles** [comment]
Yes, I could replace the default commit analyzer, that way I can choose if the release is minor, major or patch, but I cannot specify which version number should be used. Sometimes version numbers are skipped by the external system. This is what causes them to be out of sync.

**Comment by gr2m** [comment]
I see. My gut feeling is that your use case is out of scope of semantic-release. It's too much of an edge case, I fear the changes would be profound and affect the entire architecture. If you like, you can take a stab and see if the changes could be implemented easily, without affecting the existing plugin architecture, for a better base of discussion?

**Comment by travi** [comment]
> My gut feeling is that your use case is out of scope of semantic-release.

i can't help but to think pretty strongly along these lines as well. semantically bumping the version from the previous version is a very core purpose of semantic-release. to be able to set the version arbitrarily defeats that purpose. semantic-release isn't intended for use as a generic release automation tool, but as a very specifically focused one. 

you may be better off using pieces like conventional-changelog independently of semantic-release.

**Comment by Goobles** [comment]
I already thought it wouldn't be a fit for this project.

I will probably make a fork to suit my specific needs
