### ISSUE TITLE
No tag/release found and defaults to v1.0.0

### ISSUE THREAD

**Issue by pathurs** [semantic-release/semantic-release#1658]
## Current behavior

Detects previous tag/release.

## Expected behavior

Detects no tags/releases

## Environment

- **semantic-release** version: ^17.1.2
- CI environment: GitHub Actions
- Plugins used:         
    "@semantic-release/changelog": "^5.0.1",
    "@semantic-release/commit-analyzer": "^8.0.1",
    "@semantic-release/error": "^2.2.0",
    "@semantic-release/git": "^9.0.0",
    "@semantic-release/github": "^7.1.1",
    "@semantic-release/npm": "^7.0.6",
    "@semantic-release/release-notes-generator": "^9.0.1",
- **semantic-release** configuration: https://github.com/Colonise/Config
- CI logs: https://github.com/Colonise/Config/runs/1238083633?check_suite_focus=true#step:8:54

I had a very similar issue previously: #880 

The difference being the tags' commits do exist.

**Comment by gr2m** [comment]
The tags in the repository seem to be detached from the `master` branch, that's why semantic-release cannot find them. For example the latest tag `v3.9.1` points to the commit 3aeff03, but that commit does not exist in the `master` branch

**Comment by pathurs** [comment]
Thanks, that makes total sense.
