### ISSUE TITLE
NPM automation token fails on whoami check

### ISSUE THREAD

**Issue by SheepFromHeaven** [semantic-release/semantic-release#1661]
## Current behavior
Currently the npm api does not seem to allow to us the whoami command with the npm automation token. It only works with the 2FA auth token. This one on the other hand will not work for CI/CD publishing.

## Expected behavior
I am able to have 2FA active and publish my package with the automation token. Not being blocked by the whoami check.

## Environment

- **semantic-release** version: 17.2.1
- CI environment: Github Actions
- Plugins used: @semantic-release/npm
- **semantic-release** configuration: none
- CI logs: 
With 2FA Token: https://github.com/SheepFromHeaven/easy-components/runs/1269576071?check_suite_focus=true
With automation token: https://github.com/SheepFromHeaven/easy-components/runs/1269520250?check_suite_focus=true

**Comment by travi** [comment]
Thank you for raising this issue. We are already tracking this at https://github.com/semantic-release/npm/issues/277, so I'm going to close this one in favor of that one. Please subscribe to that issue to get updates.
