### ISSUE TITLE
Migrate to Renovate bot

### ISSUE THREAD

**Issue by HonkingGoose** [semantic-release/semantic-release#1663]
## Current behavior

There is no working dependency management bot active in this repository.
Updates are a manual process.

You used to have the Greenkeeper bot, but that is non-functional now.

## Expected behavior

The Renovate bot is running on the repository.
Updates are managed by a bot again.

The project has chosen the Renovate bot which offers the following benefits:
- It supports the JavaScript package ecosystem.
- It supports  Yarn v1.
- It offers ways to reduce the amount of noise you get from pull requests.
- Can group mono repository packages into one pull request.
- Can be installed as a GitHub Marketplace app into this repository.

## References:

[Greenkeeper bot homepage with message that Greenkeeper bot is deprecated](https://greenkeeper.io/)
[Renovate bot documentation](https://docs.renovatebot.com/)

## Quick checklist for your reference:

- [ ] Remove Greenkeeper app from this repository.
- [x] Close remaining Greenkeeper pull requests.
- [ ] Remove Greenkeeper badge from README.
- [x] Install Renovate bot app from the GitHub marketplace.
- [ ] Create a `renovate.json` file that points to the shared config that you made.
- [ ] Optional: add badge for new Renovate bot to README.

**Comment by gr2m** [comment]
Yes we are planning on doing that /cc @travi 

We'd like to use renovate as @travi has experience with it. Would you like to help us out with the migration?

**Comment by HonkingGoose** [comment]
I sure would like to help. :)

I'm just starting with my Renovate journey, but I can at least try to help.

The Renovate team is also super helpful, so we can always ask them for help if we get stuck.

**Comment by gr2m** [comment]
we all learn as we go :) I don't think there is a lot that we can break here, so let's go 🚀

**Comment by HonkingGoose** [comment]
Do you want to experiment on a fork, or do you want to try it on the real repo?

**Comment by gr2m** [comment]
you can send a pull request to the real repo. I'd make sure that @travi reviews it. And as you say, when in doubt, we can always reach out to the renovate team, they have been very responsive in the past to my requests as well

**Comment by HonkingGoose** [comment]
> you can send a pull request to the real repo. 

Okay!

To get started: Install the Renovate bot into this repository.
The bot will then open a "on-boarding pull request", it won't open any "real" pull request until after the Renovate configuration is done to your liking.

I can then target the "on-boarding" branch with pull requests to adjust the configuration.
We can also plan out the configuration for the bot on that pull request.

**Comment by gr2m** [comment]
sounds good 👍🏼

**Comment by gr2m** [comment]
there we go: https://github.com/semantic-release/semantic-release/pull/1664

**Comment by HonkingGoose** [comment]
I think this issue can be closed now, as you're using the Renovate bot now. 😄 

I've noticed that Renovate bot does not always auto-merge updates properly.
You can get help with fixing this at the Renovate discussions forum: https://github.com/renovatebot/renovate/discussions

**Comment by gr2m** [comment]
Thanks for all your help @HonkingGoose!
