### ISSUE TITLE
Invalid parsing of some URLs with a custom port

### ISSUE THREAD

**Issue by arthurchaloin** [semantic-release/semantic-release#1670]
## Current behavior

The current regular expression that is used to parse repository URLs does not handle custom ports properly.

For example, given the URL `git@localhost:2080/git/test.git`, the regexp will ouput the following groups:

auth: `git`
host: `localhost`
path: `2080/git/test.git`

If the URL works out of the box, this codepath will be skipped and it will still work.
However, given a case where the URL needs to be converted to HTTP(s) with basic auth information, it will create an invalid URL : `https://git@localhost/2080/git/test.git`.

## Expected behavior

The port should be parsed correctly. This can be done easily by customising the regexp a little, like I did in #1671.

## Environment

- **semantic-release** version: 17.2.1, `master`
- CI environment: not relevant
- Plugins used: not relevant
- **semantic-release** configuration: not relevant
- CI logs: not relevant

**Comment by gr2m** [comment]
resolved via https://github.com/semantic-release/semantic-release/pull/1671
