### ISSUE TITLE
PSA: npm attempts to git commit on publish in node >= 15.0.0 / npm <= 7.0.6 

### ISSUE THREAD

**Issue by ahmadnassri** [semantic-release/semantic-release#1675]
## PSA for folks using Node 15 or npm 7

in node `14.x.x` / npm `6.x.x` the `@semantic-release/npm` "prepare" step attempts to increment the version number in `package.json` using the `npm version` with the argument `--no-git-tag-version` to prevent npm from attempting to commit and tag the version.

https://github.com/semantic-release/npm/blob/493fbad4e2bff62603854a49c670bc70ec895fb7/lib/prepare.js#L10-L17

however, in `npm >= 7.0.0` this was broken, and later [fixed in `7.0.6`](https://github.com/npm/cli/releases/tag/v7.0.6)

npm 7 was also [bundled with node >= 15.0.0](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V15.md#2020-10-20-version-1500-current-bethgriggs) and at the time of writing, the latest version of node: `15.0.1` still ships with npm ` 7.0.3`

**Comment by gr2m** [comment]
Thanks for the heads up Ahmad!

**Comment by ahmadnassri** [comment]
@gr2m appologies if this was not the best place (repo) to post this, I thought about putting it under `semantic-release/npm` but figured this one will get more visibility when people come searching for issues ...

**Comment by travi** [comment]
Closing since this shouldnt be impacting folks anymore. Thanks again for the heads up at the time!
