### ISSUE TITLE
git ls-remote command fails in v17.2.3 - Error: Repository not found.

### ISSUE THREAD

**Issue by draconteus** [semantic-release/semantic-release#1695]
## Current behavior

When I run `npx semantic-release` locally, I get the following error:
```
Error: Command failed with exit code 128: git ls-remote --heads git://github.com/Company/Repo.git
```

For GitHub authentication, a unique SSH key is used and configured in SSH config file to be used for github.com host.
It works if I set GITHUB_TOKEN env var.
The repo is under the Company's namespace, but I have admin privileges to the Repo.

## Expected behavior

It can successfully do a dry-run without any access token using my SSH credential file.

## Environment
- OS: MacOS
- **semantic-release** version: 17.2.3
- Plugins used: see them in the config
- **semantic-release** configuration:
```
"release": {
    "plugins": [
      "@semantic-release/commit-analyzer",
      "@semantic-release/release-notes-generator",
      "@semantic-release/npm",
      "@semantic-release/github",
      [
        "@semantic-release/git",
        {
          "message": "ci(release): update version to ${nextRelease.version} in package*.files"
        }
      ]
    ]
  },
```

Downgrading does not solved the problem.

**Comment by travi** [comment]
> It works if I set GITHUB_TOKEN env var.

is there a reason you are attempting to _not_ set this variable? the `@semantic-release/github` plugin, which you have in your config, requires an access token to communicate with the github api. the github api is not accessible with only ssh.

**Comment by draconteus** [comment]
> is there a reason you are attempting to _not_ set this variable? the `@semantic-release/github` plugin, which you have in your config, requires an access token to communicate with the github api. the github api is not accessible with only ssh.

I did not want to expose it all the time, nor delete it from the history file. Only sometimes I use it locally.

The failing git command was a little bit misleading.  Now I can see if I use ssh protocol in the repo url (`ssh://git@github.com/Company/repo.git`), I receive the error for the missing token env var
```
[9:41:28 AM] [semantic-release] › ✖  ENOGHTOKEN No GitHub token specified.
A GitHub personal token (https://github.com/semantic-release/github/blob/master/README.md#github-authentication) must be created and set in the GH_TOKEN or GITHUB_TOKEN environment variable on your CI environment.
```

Thanks, I close this.

**Comment by CoolmhanSmith** [comment]
I have also this error. I want someone to help me
![err](https://user-images.githubusercontent.com/80696407/119909470-eb123680-bf8f-11eb-9f17-1689c429385d.png)
