### ISSUE TITLE
Inserting `original-command && semantic-release pre` will break projects' builds on Windows

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [semantic-release/semantic-release#17]
This won't work on projects being built on Windows; I suspect you'll have to set up a hybrid shell-script and batch-file flow … or something like that.

(I ran into this issue a while back when trying to port some of my own work to build on Windows. I don't have a Windows machine handy to provide specific advice with, though.)

**Comment by johann-sonntagbauer** [comment]
Think i ran into the same problem. First invastigation showed that some lib for parsing the git refs is relying on path-object npm module. That module is not os independent. I try to get in contact with the guy and try to find a solution. First attempt would be to use https://github.com/sindresorhus/slash to convert the paths into a common representation. christophwitzko/path-object/issues/1

**Comment by boennemann** [comment]
ping @christophwitzko

**Comment by christophwitzko** [comment]
Hi @johann-sonntagbauer,

this should be fixed in `git-refs@1.1.3`.
It would be awesome if you could try to reproduce the problem again.

regards
Christoph

**Comment by johann-sonntagbauer** [comment]
Will try in the afternoon, thx for fast response.

**Comment by johann-sonntagbauer** [comment]
@christophwitzko works like a charm. THX a lot.

**Comment by christophwitzko** [comment]
@johann-sonntagbauer cool, thank you :relaxed: :+1:

**Comment by boennemann** [comment]
@ELLIOTTCABLE Just so I understand this correctly. Using `&&` doesn't work on windows? If that's the case it would still be broken with the new setup/cli.

How would we work around this?

**Comment by johann-sonntagbauer** [comment]
@boennemann only as background information:
my problem was related to path generation on windows. That part was fixed by @christophwitzko in path-object. 

'&&' should work on windows. `echo "test" && echo "tada"` works as expected.

**Comment by boennemann** [comment]
@johann-sonntagbauer Thanks for the clarification!
