### ISSUE TITLE
semantic-release push a release to undefined branch

### ISSUE THREAD

**Issue by nodece** [semantic-release/semantic-release#1703]
## Current behavior

I guess semantic-release has been updated recently, in my project, semantic-release push a release to undefined branch.

semantic-release should push a release to master branch.

This is my Github Actions: https://github.com/casbin/node-casbin/runs/1469054944.

## Expected behavior

semantic-release should push a release to master branch.

## Environment

- **semantic-release** version: 17.2.3
- CI environment: GitHub Actions
- Plugins used: npm, git, github, changelog
- **semantic-release** configuration: https://github.com/casbin/node-casbin/blob/master/.releaserc.json
- CI logs: https://github.com/casbin/node-casbin/runs/1469054944

**Comment by abbottdev** [comment]
I've just had the same issue!
