### ISSUE TITLE
toml.decoder.TomlDecodeError: This float doesn't have a leading digit 

### ISSUE THREAD

**Issue by neelasha-09** [semantic-release/semantic-release#1705]
Hi Team,

I'm trying to load multiple  toml files in the python script as below:
```
config_data = toml.load("./config/default-connector.toml")
es_secret_data = toml.load(r"./secrets/elasticsearch-password.toml")
cb_secret_data = toml.load(r"./secrets/couchbase-password.toml")
```

The script works fine when I ignore  to load  the file : `"config_data = toml.load("./config/default-connector.toml")" `
But when i try to load the file `config_data = toml.load("./config/default-connector.toml")` , it fails with error:

```
Traceback (most recent call last):
  File "py-search.py", line 51, in <module>
    config_data = toml.load("./config/default-connector.toml")
  File "build/bdist.linux-x86_64/egg/toml/decoder.py", line 134, in load
  File "build/bdist.linux-x86_64/egg/toml/decoder.py", line 514, in loads
toml.decoder.TomlDecodeError: This float doesn't have a leading digit (line 6 column 1 char 64)
```

Also the issue is intermittent, it works at times and it works on some environments.
Could you please check ?

steps to install toml
```
git clone https://github.com/uiri/toml.git
cd toml
python setup.py install
 ```
**Python version : Python 2.7.5**

**Comment by gr2m** [comment]
I'm sorry but what has this to do with semantic-release?
