### ISSUE TITLE
Current Logo in SVG?

### ISSUE THREAD

**Issue by bromso** [semantic-release/semantic-release#1714]
Do you have the current logo in SVG format available? :)

https://gblobscdn.gitbook.com/spaces%2F-LGsE7zdvzHI5cG-XV6p%2Favatar.png

**Comment by gr2m** [comment]
I don't think so. But would be nice if someone could create one! I only found a PNG version:
https://github.com/semantic-release/semantic-release.github.io/blob/master/logo.png

We could add an SVG to this repository's assets/ folder

**Comment by bromso** [comment]
@gr2m : Ok. I used the current logo as a reference, even thou it was very low res and made it into a SVG.

I don't have any rights to commit or push anything. So I put the logo I recreated in a shared Google Drive folder.

https://drive.google.com/drive/folders/11pkgY4U3r5jWi1LMj1hkD3guNIJ5Ug8K?usp=sharing

**Comment by gr2m** [comment]
if you like, you can send a pull request and add the file to this folder: https://github.com/semantic-release/semantic-release/tree/master/media That way your account will be credited with the contribution in the git history?

**Comment by bromso** [comment]
Sure thing! 😃 

https://github.com/semantic-release/semantic-release/pull/1715
