### ISSUE TITLE
Get next semantic-release version

### ISSUE THREAD

**Issue by Clumsy-Coder** [semantic-release/semantic-release#1716]
## New feature motivation

I needed to get the next semantic-release version to store into a ENV variable in github-actions (to be used for another purpose).

I used command `yarn semantic-release -d | grep 'Release note' | grep -Po "(\d+)\.(\d+)\.(\d+)"` to extract the next version.

using plugin:
- @semantic-release/commit-analyzer
- @semantic-release/release-notes-generator

It'd be nice to use a simple semantic-release command to obtain the next version.

## New feature description

Run command `yarn semantic-release --nextVersion`

Ex: 
- before running command, the version is `1.1.16`
- after running command, output is `1.1.17`

NOTE: should also work if there's no changes in the next semantic-version

**Comment by gr2m** [comment]
I think this is a duplicate of https://github.com/semantic-release/semantic-release/issues/753

**Comment by Clumsy-Coder** [comment]
Closing due to duplicate Issue
