### ISSUE TITLE
How to revert a release?

### ISSUE THREAD

**Issue by tusharmath** [semantic-release/semantic-release#172]
I by mistake made a FEATURE release without adding the `breaking changes` comment. This is not something that I do, a lot of people when shifting to this project will make this mistake. How should someone be handling this problem?

**Comment by destroyerofbuilds** [comment]
I'd be curious how this should be done as I've made the same mistake.

I wonder whether we could just rely on the normal `git revert` workflow to make a `revert` commit and then update `commit-analyer` to treat commits starting with `revert` as a patch.

Relevant code: https://github.com/semantic-release/commit-analyzer/blob/master/src/index.js#L20

@tusharmath does that seem reasonable?

**Comment by therealklanni** [comment]
@tusharmath @destroyerofbuilds you will have to unpublish the version on npm:

```
npm unpublish <pkg>@<semver>
```

Then from there, I'm not 100% sure how to handle the semantic-release aspect. Maybe try @destroyerofbuilds 's suggestion, but it might be better to just rewrite the commit.

**Comment by hbetts** [comment]
@therealklanni as you mention, just unpublishing the change might be problematic. If you are on version 1, and submit a breaking change, you end up with version 2 on the npm registry. You then unpublish version 2 from npm. The next time you submit a breaking change, `semantic-release` will try to publish version 2 again, and will fail.

**Comment by tusharmath** [comment]
@hbetts  if `semantic-release` gets the latest of both the `published` and `unpublished` and then release with the same version but a different `build` may be?
