### ISSUE TITLE
Cannot disable CI checks in shareable configurations

### ISSUE THREAD

**Issue by dominykas** [semantic-release/semantic-release#1728]
## Current behavior

`ci: false` defined in the _shareable_ configuration is not respected.

This is because the `options.ci` is normalized into `options.noCi` _before_ applying `extends`: https://github.com/semantic-release/semantic-release/blob/da75a9c60a632f75b2b45856e407c1f3dfa9fa14/lib/get-config.js#L30-L32 and the rest of the code checks only `options.noCi` (at least in the places I checked).

Workaround: add `noCi: true` in the shareable configuration.

## Expected behavior

- Should be OK to set `ci: false` in the shareable configuration - happy to PR this.
- Alternatively, [documentation should be updated](https://semantic-release.gitbook.io/semantic-release/usage/configuration#ci) to reflect that - happy, but not _too_ happy, to PR this as well.

## Environment

- **semantic-release** version: latest

**Comment by gr2m** [comment]
Thank you for reporting this problem!

A pull request to fix it would be very welcome
