### ISSUE TITLE
Exceptions in bin/semantic-release are swallowed silently

### ISSUE THREAD

**Issue by tzimmermann** [semantic-release/semantic-release#1734]
We just ran into a failing CircleCI pipeline, which was in the end caused by https://github.com/semantic-release/semantic-release/issues/1694 as it turned out.
Really tough one to figure out, as we did not change anything in the semantic-release set up, but we apparently added a new CircleCI job context, which contained an env variable value containing a `(` character, which triggered https://github.com/semantic-release/semantic-release/issues/1694.

However, it took way longer than necessary to find this root cause, as semantic-release was failing with exit code 1, but not printing **any** output to the console (not even with `--debug`).

In our case, it would probably have helped to see the exception that is silently swallowed here:

https://github.com/semantic-release/semantic-release/blob/21c151f167960ffa9f43069bc109900ebf57aed3/bin/semantic-release.js#L43

**Comment by gr2m** [comment]
I agree, let's log the error. Would you like to send a PR?
