### ISSUE TITLE
Greenkeeper is being replaced by Snyk

### ISSUE THREAD

**Issue by jsoref** [semantic-release/semantic-release#1738]
## Current behavior

> ☝️ Important announcement: Greenkeeper will be saying goodbye 👋 and passing the torch to Snyk on June 3rd, 2020! Find out how to migrate to Snyk and more at greenkeeper.io

![image](https://user-images.githubusercontent.com/2119212/104967255-e968ae80-59b0-11eb-8aa5-0ecdfd3ce55d.png)

## Expected behavior

No complaints/warnings from Greenkeeper/Snyk in various places

## Environment

Just browsing the root of this repo shows the badge:
![image](https://camo.githubusercontent.com/c8f1e4aef56c7284a4674542302fd243152b4a8131f833944cf096838aa9fb10/68747470733a2f2f6261646765732e677265656e6b65657065722e696f2f73656d616e7469632d72656c656173652f73656d616e7469632d72656c656173652e737667)

But, there are also PRs where Greenkeeper is warning about the migration.

**Comment by gr2m** [comment]
Thanks! We are migrating to renovate, currently blocked by https://github.com/semantic-release/semantic-release/pull/1699#issuecomment-731413750 maybe you could help with that?
