### ISSUE TITLE
Apply tag and publish the package separately

### ISSUE THREAD

**Issue by jayjoshi-crest** [semantic-release/semantic-release#1753]
As far as I read the documentation of semantic-release, it does many things in sequence.
It applies the tag in the commit and publish it to the Github releases.

Q: Is it possible to separate those 2 steps somehow?

*  In 1st stage, I only want to apply tag
*  In 2nd stage, I want to publish the artifact to Github.

**Comment by gr2m** [comment]
You could do just the 1st stage by removing the `@semantic-release/github` plugin. But once the tag exist, semantic-release would not be able to run to do the 2nd stage.

Why do you want to separate the two? Is there something you want to do in between?

**Comment by jayjoshi-crest** [comment]
That solves my problem. Thanks for the support.!
