### ISSUE TITLE
not accepting any token

### ISSUE THREAD

**Issue by rattkin** [semantic-release/semantic-release#1756]
I created Variable 'GL_TOKEN' in CI/CD variables (gitlab), but the job does not try to use it.
I generated the value for token under my personal access tokens, or on repository level, but the key was last used: never

I tried reading past issues, which I found plenty, but nothing works. I tried setting several tokens on several places in our gitlab.

I also get this error message in the job log:
```
✖  Failed step "verifyConditions" of plugin "@semantic-release/github"
ENOGHTOKEN No GitHub token specified.
```
Sometimes, I get this message in the job log:
```
✖  An error occurred while running semantic-release: Error: Command failed with exit code 128: git ls-remote --heads https://[secure]@gitlab.example.com
remote: HTTP Basic: Access denied
```

As I understand gitlab, each CI/CD job should have a temporary token during the pipeline run, why do I need to set anything for semantic-release?

**Comment by rattkin** [comment]
I also tried following this guide: https://docs.gitlab.com/ee/ci/examples/semantic-release.html (except the npm of course, I just want to get versioning)

**Comment by gr2m** [comment]
did you configure semantic-release as described here: https://docs.gitlab.com/ee/ci/examples/semantic-release.html#configure-semantic-release? It looks like the `@semantic-release/github` plugin is still loaded

make sure to run `semantic-release --debug` to get more output for debugging

**Comment by rattkin** [comment]
> did you configure semantic-release as described here: https://docs.gitlab.com/ee/ci/examples/semantic-release.html#configure-semantic-release? It looks like the `@semantic-release/github` plugin is still loaded
> 
> make sure to run `semantic-release --debug` to get more output for debugging

Thank you you are correct! The debug output confirms, that the plugin are indeed default:
```
plugins: [
    '@semantic-release/commit-analyzer',
    '@semantic-release/release-notes-generator',
    '@semantic-release/npm',
    '@semantic-release/github'
  ],
```
I thought I had plugins configured in package.json, but upon closer inspection I realized I put them in the wrong property (repository, instead of release)

Thanks!
