### ISSUE TITLE
deprecated npmconf?

### ISSUE THREAD

**Issue by gr2m** [semantic-release/semantic-release#176]
during `npm install` of a package which with semantic-release in its dependency, I see this warning:

```
WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
```

not sure if there is anything you can do about it, I find the deprecation rather confusing

**Comment by hbetts** [comment]
It looks like `npmconf` was just deprecated two weeks ago: https://github.com/npm/npmconf/commit/22827e4038d6eebaafeb5c13ed2b92cf97b8fb82

The `npmconfig` module is used here: https://github.com/semantic-release/semantic-release/blob/032b49369696113807563ea1d932af9e42606c4b/bin/semantic-release.js#L44

We will need to use `npm` programmatically to fetch config information: https://www.npmjs.com/package/npm#using-npm-programmatically

**Comment by hbetts** [comment]
Change up for review in #177

**Comment by jhabdas** [comment]
Bump

**Comment by jhabdas** [comment]
warning semantic-release > npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm

**Comment by gr2m** [comment]
We are planning a little semantic-release hackday in which I hope we get to address that issue or at least prepare the project to onboard more maintainers. Stay tuned :)

**Comment by vanduynslagerp** [comment]
We could use this package https://github.com/kevva/npm-conf maybe ?
