### ISSUE TITLE
migrate from spectrum to github discussions

### ISSUE THREAD

**Issue by travi** [semantic-release/semantic-release#1764]
just wanting to capture the details that we will need to handle when we make the move. please add any details that i may be forgetting.

## Known Steps

* Update our documentation for getting help
  * https://github.com/semantic-release/semantic-release#get-help
  * Any others?
* Enable migration on the spectrum community (description below)

> ## Migrate your community elsewhere
> Enabling this setting will redirect your community and channel pages to your community's website.
>
> Existing conversations will stay accessible on Spectrum at their current URLs, but no new members can join and no new conversations can be created.
> 
> We recommend redirecting to a page that explains why users were redirected from Spectrum. For example, you can include a query param in your community website setting (e.g. community.acme.com/?spectrum=true) to show a special notice to users arriving there.

## Open Questions

* Do we want to simply enable discussions in the `semantic-release` repo, or at some more broad level?
* Do we want to seed specific categories before opening up the discussions?
* Do we want to simply migrate Spectrum to point directly at the discussions page, or some explanation page, like spectrum suggests?
* I don't think we can migrate the Spectrum content, but it should remain available. Do we want to link to it for historical purposes?

**Comment by gr2m** [comment]
> * Do we want to simply enable discussions in the `semantic-release` repo, or at some more broad level?

Yeah let's enable it in this repo only. But we can setup issue templates in all repositories which include a link to the discussion for general questions, leaving issues for actionable bug reports and agreed upon feature requests

> * Do we want to seed specific categories before opening up the discussions?

No need, we can adjust categories later

> * Do we want to simply migrate Spectrum to point directly at the discussions page, or some explanation page, like spectrum suggests?
> * I don't think we can migrate the Spectrum content, but it should remain available. Do we want to link to it for historical purposes?

I don't care about these two. If it's not much effort why not, but I wouldn't put too much work into either

**Comment by travi** [comment]
> Yeah let's enable it in this repo only.

I got went ahead and enabled them and posted the default intro message from going through the set up process.

> I don't care about these two. If it's not much effort why not, but I wouldn't put too much work into either

yeah, i don't want to put much effort into this area either. i did attempt to enable the migration that is built into spectrum, but got a server error. i'll try it again soon, but i don't imagine features like that are getting much attention. i may end up just posting a pinned post there and calling it good enough.

**Comment by Mandymoore680** [comment]
????

**Comment by travi** [comment]
i still havent been successful with enabling the migrate option on spectrum, but i did pin a simple post mentioning the move and directing folks to the new discussions: https://spectrum.chat/semantic-release/general/discussions-have-been-moved-to-github~24ad830c-d757-4d6f-bb3b-f44418150a8d

**Comment by gr2m** [comment]
I think that's good enough. We can close the issue now I think

**Comment by travi** [comment]
> we can setup issue templates in all repositories which include a link to the discussion for general questions

i think this is the one remaining task that still seems worth completing. since this is more involved than just updating for the discussions piece, maybe it deserves its own issue, but i'm closing this one as long as we keep that piece on our radar

**Comment by gr2m** [comment]
sounds like a good use case for an @octoherd script :) Here is a follow up issue: https://github.com/semantic-release/semantic-release/issues/1787
