### ISSUE TITLE
missing marked peer dependency

### ISSUE THREAD

**Issue by ZebraFlesh** [semantic-release/semantic-release#1765]
## Current behavior

Similar to #1429, semantic-release 17.3.7 is complaining about a missing peer dependency: 
```bash
% npm install --save-dev semantic-release
npm WARN marked-terminal@4.1.0 requires a peer of marked@>=0.4.0 <2.0.0 but none is installed. You must install peer dependencies yourself.

+ semantic-release@17.3.7
added 611 packages from 964 contributors and audited 3296 packages in 21.842s
```

Are consumers of semantic-release expected to install `marked` on their own? (This seems weird.)

## Expected behavior

`npm install --save-dev semantic-release` successfully installs with no warnings.

## Environment

- **semantic-release** version: 17.3.7
- CI environment: N/A
- Plugins used: N/A
- **semantic-release** configuration: N/A
- CI logs: N/A

**Comment by travi** [comment]
I don't understand how this would happen in this case. `semantic-release` defines a direct dependency on `marked` with a range of `^1.0.0`, as you can see [here](https://github.com/semantic-release/semantic-release/blob/8ea81ae6c9e1752f9823f019ea7a72b6a36100f2/package.json#L40). that entire range falls within the range shown in that warning.

for the `semantic-release` project itself, i confirmed that no peer incompatibility warning for `marked`/`marked-terminal` is listed when running `npm ls`. `npm ls marked` currently gives `1.2.8` and `npm ls marked-terminal` currently gives `4.1.0`, both as direct dependencies.

where you are seeing the problem you mention, do the above `npm ls` commands show more versions of `marked` or `marked-terminal` than those that are the direct dependencies of `semantic-release`?

**Comment by ZebraFlesh** [comment]
That is _insanely_ weird. I agree I don't see how it's even possible and further agree that `semantic-release` has a correct set of dependencies. Give me a day or two to track this down again -- I've got semantic-release in a few dozen repos and I forget exactly which one was the offender.

**Comment by ZebraFlesh** [comment]
I regenerated my package-lock.json file and now everything is magically good. Strange, but fixed. Closing and moving on.
