### ISSUE TITLE
Not updating changes of package.json or CHANGELOG.md

### ISSUE THREAD

**Issue by juancarlosjr97** [semantic-release/semantic-release#1780]
Dependencies:
* "@semantic-release/changelog": "^5.0.1",
* "@semantic-release/exec": "^5.0.0",
* "@semantic-release/git": "^9.0.0",
* "semantic-release": "^17.3.7",

`.releaserc`

```
{
    "branches": "main",
    "repositoryUrl": "https://github.com/juancarlosjr97/documentation-ims",
    "debug": "true",
    "plugins": [
      "@semantic-release/commit-analyzer",
      "@semantic-release/release-notes-generator",
      "@semantic-release/npm",
      "@semantic-release/github",
      [
        "@semantic-release/changelog",
        {
          "changelogFile": "CHANGELOG.md"
        }
      ],
      [
        "@semantic-release/git",
        {
          "assets": ["package.json", "CHANGELOG.md"],
          "message": "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
        }
      ]
    ]
  }

```

### Issue

Neither the `package.json` nor the `CHANGELOG.md` gets updated, but nothing fails, it creates the tag and the release successfully.

I am using GitHub Actions, I tested initially with the the `${{ secrets.GITHUB_TOKEN }}` then I created a personal token with full permissions (everything enabled) and it did not work either.

**Comment by travi** [comment]
i'm going to move this into a discussion, since that is where we are hoping to direct support discussions like this one going forward
