### ISSUE TITLE
Support *.cjs configs

### ISSUE THREAD

**Issue by opiation** [semantic-release/semantic-release#1814]
## New feature motivation

When attempting to use `semantic-release` with a ESM-written package (`"type": "module"`) and node with ES modules enabled, a plain `release.config.js` config fails understandably given the tool is written with `require()`s.  Renaming the config to `release.config.cjs` does not work as the version of `cosmicconfig` used by `semantic-release` does not search for `.cjs` files.  Thus, only the `json` config options are available.

Updating the `cosmicconfig` dependency to v7.0.0 would allow one to use `semantic-release` developing a package implicitly in ES modules (`--experimental-modules`).

## New feature description

Supports `*.cjs` file extensions like `release.config.cjs` for configuring `semantic-release`.

## New feature implementation

Update `cosmicconfig` dependency to v7.0.0 which [adds support for `*.cjs` file extensions](https://github.com/davidtheclark/cosmiconfig/blob/main/CHANGELOG.md#700).

**Comment by travi** [comment]
please double check the version of `semantic-release` that you are using. the current version of `cosmiconfic` that is depended on by `semantic-release` is already `v7.0.0`:

https://github.com/semantic-release/semantic-release/blob/6013a5633ecb71aac80f7b68b8e7250c5c58f7c0/package.json#L29

**Comment by opiation** [comment]
My apologies, @travi.  I could have sworn that I looked at `master` but must have still been looking at the v17.3.0 tag.  You're correct that `cosmicconfig` was indeed updated recently ([v17.3.6](https://github.com/semantic-release/semantic-release/releases/tag/v17.3.6)).  I've updated my local version to use v17.3.9 however, `.cjs` still is not read.

My config:

```js
// release.config.cjs

const releaseRules = [
  { type: 'docs', release: 'patch' }
]

const gitOptions = {
  assets: ['CHANGELOG.md', 'dist/**/*', 'package.json']
}

module.exports = {
  plugins: [
    ['@semantic-release/commit-analyzer', { releaseRules }],
    '@semantic-release/release-notes-generator',
    '@semantic-release/changelog',
    '@semantic-release/npm',
    ['@semantic-release/git', gitOptions]
  ]
}
```


```sh
$ yarn run semantic-release --debug --dry-run

[11:22:25 AM] [semantic-release] › ℹ  Running semantic-release version 17.3.9                                                                                                                  
  semantic-release:config load config from: undefined +0ms 
```

^^^ I've omitted the remainder of the output as the `undefined` config seems sufficient to indicate this _might_ be a bug.  Given that possibility, I'll include some more details to save time.

```sh
$ node --version
v14.15.4

$ echo $NODE_OPTIONS
--experimental-modules --experimental-vm-modules --max-old-space-size=4096

$ yarn --version
1.22.10
```

Using Ubuntu 18.04.5 LTS

Let me know if any additional information is needed or if I've misread any documentation about using `cjs` configs.

**Comment by travi** [comment]
this seems like a valid request and we want to make sure that `semantic-release` isn't blocking this capability. however, we may not get a chance to investigate deeply right away. 

if you could help us investigate, it would really help this be resolved more quickly. our usage of `cosmiconfig` is here: https://github.com/semantic-release/semantic-release/blob/21c151f167960ffa9f43069bc109900ebf57aed3/lib/get-config.js#L24. if you identify a problem with our usage, please start a PR suggesting the change that would fix our usage and we'll be happy to work through additional details there.

**Comment by opiation** [comment]
Sure thing!  Here's what I've found briefly so far...

In `lib/get-config.js`, `cosmicconfig()` is invoked with `CONFIG_NAME` as the `moduleName` (from the [cosmicconfig API][cc-api]) and `CONFIG_FILES` is provided as explicit `searchPlaces`.

https://github.com/semantic-release/semantic-release/blob/f25c3527dfac2341d799f46dc860f2581cd468cd/lib/get-config.js#L11
https://github.com/semantic-release/semantic-release/blob/f25c3527dfac2341d799f46dc860f2581cd468cd/lib/get-config.js#L12-L20
According to the `cosmicconfig` docs however, the module name, in this case `"release"` is used to create the default set of search places.

> This is used to create the default searchPlaces and packageProp.

By providing the `searchPlaces` explicitly with `CONFIG_FILES`, these defaults are overwritten, thus excluding the `.cjs` variants that are now supported by `cosmicconfig`.

For reference, the default `searchPlaces` [can be found here][cc-search-places] (inlined below).

```js
[
  'package.json',
  `.${moduleName}rc`,
  `.${moduleName}rc.json`,
  `.${moduleName}rc.yaml`,
  `.${moduleName}rc.yml`,
  `.${moduleName}rc.js`,
  `.${moduleName}rc.cjs`,
  `${moduleName}.config.js`,
  `${moduleName}.config.cjs`,
]
```

Based on the current implementation and the defaults generated by `cosmicconfig`, it seems likely the best course of action is to remove the explicit `searchPlaces` option and rely on `cosmicconfig`'s defaults which would include `.cjs` variants.

I might have time to test this locally and/or submit a PR but thought I'd at least share these findings here in case anyone has time to do so.

[cc-api]: https://github.com/davidtheclark/cosmiconfig#cosmiconfig-1
[cc-search-places]: https://github.com/davidtheclark/cosmiconfig#searchplaces

**Comment by opiation** [comment]
I was able to test this locally in the end and removing the `searchPlaces` works as I expected and described above.  I'll submit a PR shortly.

**Comment by opiation** [comment]
To anyone interested, submitted PR #1815 and it is pending review.
