### ISSUE TITLE
Fix(Documentation): Change link to Angular's Contribution guidelines instead of Angular.js's Developers guide.

### ISSUE THREAD

**Issue by koiralakiran1** [semantic-release/semantic-release#1816]
[This section](https://github.com/semantic-release/semantic-release/blob/master/README.md#commit-message-format) in the documentation mentions that `semantic-release` uses **Angular's Commit message convention** **by default** and it links to Angular JS's Developers guidelines (https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#-git-commit-guidelines).

But as mentioned in [this section]( https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-angular#angular-convention) of `conventional-changelog-angular` (used as default parser by both `commit-analyzer` and `release-notes-generator`), I think the link in the documentation should point to https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-format instead.

**Comment by gr2m** [comment]
Agreed 👍🏼 would you like to send a pull request?

**Comment by koiralakiran1** [comment]
Sure @gr2m
