### ISSUE TITLE
BREAKING CHANGE doesn't work on merge commits?

### ISSUE THREAD

**Issue by tusharmath** [semantic-release/semantic-release#182]
List of commits — https://github.com/tusharmath/Multi-threaded-downloader/commits/master
I have added a merge commit - `2d7940b8db8352b9c33907c0b1d681fe7e1651bc` which is not creating a breaking release.

**Comment by hbetts** [comment]
@tusharmath 

So I took the contents of the merge commit you provided just to verify that `conventional-commits-parser` (The parser used by `semantic-release`), can handle the message format:

```
 parser = require('conventional-commits-parser')
{ [Function: conventionalCommitsParser] sync: [Function: sync] }
> parser.sync('Merge pull request #42 from tusharmath/develop\nBREAKING CHANGE: public api uses promises\nDevelop')
{ type: null,
  scope: null,
  subject: null,
  header: 'Merge pull request #42 from tusharmath/develop',
  body: null,
  footer: 'BREAKING CHANGE: public api uses promises\nDevelop',
  notes:
   [ { title: 'BREAKING CHANGE',
       text: 'public api uses promises\nDevelop' } ],
  references: [],
  revert: null }
```

Which is does. Next, taking a look at your Travis-CI logs, I notice this in the build logs:

```
"You cannot publish over the previously published version 0.3.0." : mt-downloader
```

It does seem the call to `semantic-release` in your build is trying to publish a new major version, but the npm registry is rejecting it. Though the npm website says the last version was 0.2.11, npm registry thinks 0.3.0 has already been published.

Therefore I ran `npm info mt-downloader`, to see which versions npm knows about. In their time list I see `'0.3.0': '2016-01-29T15:02:41.725Z'`. So the npm registry does think it has a 0.3.0 already. Though the version list seen via `npm info` does not show 0.3.0.

Perhaps you published a 0.3.0, and then unpublished it?

Here's an npm issue related to publishing previously published versions: https://github.com/npm/npm/issues/9266

**Comment by tusharmath** [comment]
> It does seem the call to semantic-release in your build is trying to publish a new major version, but the npm registry is rejecting it

Major version means `1.0.0` right? Then why is it trying to publish `0.3.0`

**Comment by hbetts** [comment]
Major version as interpreted by npm, and the general npm community, is defined as the first non-zero number. So for your project, which is currently 0.2.11, the major version is 2. The next major version for your project would be 0.3.0.

Documentation here: https://github.com/npm/node-semver#caret-ranges-123-025-004

Specifically this line:

```
Many authors treat a 0.x version as if the x were the major "breaking-change" indicator.
```

**Comment by tusharmath** [comment]
Wow! I din't know this. Thanks a ton for providing that link. I got confused because when I ran `npm run semantic-release` locally, it gave the following result —

```

> mt-downloader@ semantic-release /Users/tushar.mathur/Documents/Projects/Multi-threaded-downloader
> semantic-release pre && npm publish && semantic-release post

semantic-release WARN pre semantic-release didn’t run on Travis CI and therefore a new version won’t be published.
semantic-release WARN pre You can customize this behavior using "verifyConditions" plugins: git.io/sr-plugins
semantic-release ERR! pre Determined version 1.0.0 as "latest". Not publishing in debug mode. { type: 'major', version: '1.0.0' }

npm ERR! Darwin 15.2.0
npm ERR! argv "/Users/tushar.mathur/.nvm/versions/node/v5.1.0/bin/node" "/Users/tushar.mathur/.nvm/versions/node/v5.1.0/bin/npm" "run" "semantic-release"
npm ERR! node v5.1.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! mt-downloader@ semantic-release: `semantic-release pre && npm publish && semantic-release post`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mt-downloader@ semantic-release script 'semantic-release pre && npm publish && semantic-release post'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mt-downloader package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     semantic-release pre && npm publish && semantic-release post
npm ERR! You can get their info via:
npm ERR!     npm owner ls mt-downloader
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/tushar.mathur/Documents/Projects/Multi-threaded-downloader/npm-debug.log
```

So I have two questions —

1. Why is the result different `1.0.0` when I run it locally?
2. How do I make this release using this module?

**Comment by tusharmath** [comment]
Kind of gave up on expecting a response.

**Comment by hbetts** [comment]
@tusharmath I'm sorry I wasn't able to respond sooner.

I really can't explain the difference between `semantic-release` executed in `travis-ci`, versus executed locally. I'm still in the process of learning `semantic-release` myself.

Based on your repository, it looks like you've been successfully making releases using `semantic-release` for several days now. Hopefully that implies that your setup is working well for you now, and my hope is that `semantic-release` is being helpful, and not a burden.

**Comment by tusharmath** [comment]
@hbetts I had to manually make that release.

This module makes a great impact in the way I write git commits and makes me think about releases first rather than thinking about it later. There are still quite a few undocumented "gotchas" such has — greenkeeper.io integration and using npm-dist tags or proper integration with ghooks etc.

Though I understand they are not a part of `semantic-release` as module but are relevant from a concept point of view.
