### ISSUE TITLE
Projects using semantic-release

### ISSUE THREAD

**Issue by alecxe** [semantic-release/semantic-release#183]
Please consider improving documentation and add a list of projects using `semantic-release`. This would help newcomers to see how is that used in real world. Thanks.

**Comment by hbetts** [comment]
@alecxe could you please be more specific about what changes you feel should be made to the documentation?

I do feel `semantic-release` could describe an ideal setup in greater detail. I had issues myself getting my first project setup with `semantic-release`.

**Comment by alecxe** [comment]
@hbetts sure, sorry for not providing details. 

I just mean would be nice to link the projects that are already set to use semantic-releasing. For example [this project](https://github.com/tlvince/eslint-plugin-jasmine) really helped me to set up the release for [this project](https://github.com/alecxe/eslint-plugin-protractor). Actual working example seriously helped to get things started..

Hope it makes sense. Thanks.

**Comment by DavidWells** [comment]
This project is another good example: https://github.com/kentcdodds/starwars-names

**Comment by jimthedev** [comment]
We use it on [Commitizen](https://github.com/commitizen/cz-cli)

**Comment by luftywiranda13** [comment]
[generator-bunny](https://github.com/luftywiranda13/generator-bunny) 🐰

**Comment by pvdlg** [comment]
Documentation has been improved in #593

Let us know if that helps enough. Otherwise all semantic-release projects use semantic-release and can be used as an example
