### ISSUE TITLE
How to run semantic-release as a Docker command-line application?

### ISSUE THREAD

**Issue by finn-christiansen** [semantic-release/semantic-release#1846]
I want to run semantic-release without the need to setup node locally. I want to run semantic release in docker but without executing `git pull` in the container.

desired functionality:

I want to run the following command inside a git-repository on any machine that has docker as single dependency:

```
docker run --rm -it \
    --env GH_TOKEN=xxx \
    --env REPOSITORY_URL=yyy \
    -v $(pwd)/.git:/usr/src/app/.git \
    my-semantic-release:latest
```

Dockerfile

```
FROM node:14-alpine

RUN apk add --no-cache git

WORKDIR /usr/src/app

RUN npm install semantic-release @semantic-release/exec

CMD npx semantic-release \
    --no-ci \
    --repository-url $REPOSITORY_URL
```

This works, but unfortunately, git modifies my `.git` folder in the Docker container. This leads to permission problems if I run docker locally after executing sematic-release inside the docker container.

I know that I can fix the permissions afterward with `sudo chown ... && sudo chmod ...` but this doesn't seem like a best practice solution. Additionally, I could simply make a copy of the `.git`-folder inside the container. This way, only the copy will be modified and my "local" `.git`-folder stays untouched. But this also seems not like a clean solution.

Is someone using a similar setup and knows a clean solution for this?

**Comment by bigbrozer** [comment]
You can add `USER_ID` and `GROUP_ID` as new ENV in the Dockerfile. Then, add an ENTRYPOINT which creates a user using these uid and gid and execute semantic-release as this user. When running the container at host, ensure you set `USER_ID` and `GROUP_ID` to the uid and gid of your *real* user (`docker run -e ...`). This will map the permissions on the host inside the container and avoid issues you are encountering.
