### ISSUE TITLE
deprecate release-notes-generator and use conventional-changelog v1

### ISSUE THREAD

**Issue by stevemao** [semantic-release/semantic-release#190]
Hi there

release-notes-generator is a tiny wrapper of conventional-changelog to fix a bug in the old version. Now that conventional-changelog has reached v1 and its features and API has dramatically improved. There is also [conventional-github-releaser](https://github.com/stevemao/conventional-github-releaser) which uses conventional-changelog to make GitHub releases. Please ask me any questions. Thanks.

**Comment by stevemao** [comment]
Also conventional-changelog is broken down into smaller modules. Some related tools such as [conventional-recommended-bump](https://github.com/stevemao/conventional-recommended-bump) and [conventional-commits-detector](https://github.com/stevemao/conventional-commits-detector) is using the internal module of conventional-changelog. I believe these can greatly improve semantic-release.

**Comment by hbetts** [comment]
@stevemao some what ironic, I've been working on [semantic-release-github-releaser](https://github.com/hbetts/semantic-release-github-releaser), which uses `conventional-github-releaser` under the hood (`src/index.js`). `semantic-release-github-releaser` is meant to replace the GitHub release code pulled out into a pluggable module as part of my work in #150 

I would also like to use `conventional-recommended-bump` to replace [commit-analyzer](https://github.com/semantic-release/commit-analyzer) which will help to solve some of the [issues](https://github.com/semantic-release/commit-analyzer/issues/3) that have arisen with it. You may be interested in: https://github.com/semantic-release/commit-analyzer/issues/11

All of this, though, depends on @boennemann and @christophwitzko, the maintainers of `semantic-release`.

On a side note, @stevemao, one of my major goals is to bring GitLab support to `semantic-release`. Would there by a `conventional-gitlab-releaser` in the future (Now that GItLab has Release pages as well)?

**Comment by hbetts** [comment]
Actually I think we can entirely deprecate the `analyzeCommits` plugin point and just use `conventional-recommended-bump`. It already has built-in preset, and support for custom presets. No need for anyone to create their own commit analyzer.

**Comment by stevemao** [comment]
@hbetts Yes.

**Comment by stevemao** [comment]
conventional-changelog really needs to be bumped. The old version is very buggy and causes a lot of problems.  @boennemann @christophwitzko if you guys are too busy I'm very happy to maintain this module. Thanks.

**Comment by stjohnjohnson** [comment]
@hbetts @stevemao is there anything users can do to swap out to use conventional-recommended-bump?

**Comment by hbetts** [comment]
@stjohnjohnson as noted [here](https://github.com/semantic-release/commit-analyzer/issues/11#issuecomment-270049779), you can write your own `analyzeCommits` plugin.

**Comment by vanduynslagerp** [comment]
The new [commit-analyzer](https://github.com/semantic-release/commit-analyzer) and [release-notes-generator](https://github.com/semantic-release/release-notes-generator) plugins both use the last version of `conventional-changelog`.
The `conventional-changelog` are also configurable.

Feel free to re-open if the new plugins doesn't fulfill your requirements.
