### ISSUE TITLE
GitHub actions example fails

### ISSUE THREAD

**Issue by nicktalb** [semantic-release/semantic-release#1903]
## Current behavior

NPM authentication fails

## Expected behavior

NPM authentication succeeds

## Resolution

It looks like the correct environment variable to set is `NODE_AUTH_TOKEN` rather than `NPM_TOKEN` and this has fixed my workflow (see https://github.com/emerson-eps/eslint-config/pull/14/files)

**Comment by nicktalb** [comment]
It looks like the same issue exists in the semantic-release-cli README example:
https://github.com/semantic-release/cli/blob/master/README.md#github-actions

**Comment by gr2m** [comment]
> It looks like the correct environment variable to set is `NODE_AUTH_TOKEN` rather than `NPM_TOKEN`

Are you sure this is not unique to your repository? This would fail thousands of times across tons of repository, including hundreds of my own. It worked with `NPM_TOKEN` for along, long time now

**Comment by nicktalb** [comment]
I'm not sure how this could be repository specific. I don't have a `.npmrc` file and the pipeline is generic.

Every example I have seen documents that you must use `NODE_AUTH_TOKEN`. See for example documentation of the [setup-node action](https://github.com/actions/setup-node#usage) and [GitHub actions guide for building and testing Node.js](https://docs.github.com/en/actions/guides/building-and-testing-nodejs#installing-dependencies).

How sure are you that `NPM_TOKEN` works? `NPM_TOKEN` seems to be the convention for the repository secret name and `NODE_AUTH_TOKEN` is required for the environment variable. `NPM_TOKEN` failed for me and it works with the documented `NODE_AUTH_TOKEN`.

My working pipeline for publishing using semantic-release is [here](https://github.com/emerson-eps/eslint-config/blob/main/.github/workflows/node.js.yml). It's a shared ESLint config repo so not much to it.

If you're sure `NPM_TOKEN` works as the environment variable can you point me to a pipeline/repo using it so that I can compare? The differences I currently see between this example and my pipeline are Node 12 v Node 14 and setup-node@v1 v setup-node@v2. I initially suspected the setup-node action but I have also see setup-node@v1 pipelines using `NODE_AUTH_TOKEN` and have found no reference to such a breaking change.

**Comment by nicktalb** [comment]
OK, I see `NPM_TOKEN` is used in [semantic-release](https://github.com/semantic-release/semantic-release/blob/master/.github/workflows/release.yml) and [oktokit.js](https://github.com/octokit/octokit.js/blob/main/.github/workflows/release.yml) release workflows.

I suspect the reason this did not work for me is that I have defined the `registry-url` which as documented [here](https://docs.github.com/en/actions/guides/building-and-testing-nodejs#example-using-a-private-registry-and-creating-the-npmrc-file) creates a `.npmrc` file with `NODE_AUTH_TOKEN` in it so it needs to be defined. I guess without the `.npmrc` and explicit registry URL `NPM_TOKEN` gets picked up, so perhaps removing the `registry-url` would allow it to work with `NPM_TOKEN`.

It might be worth updating the example to more closely match the `setup-node` examples to avoid these subtleties.
