### ISSUE TITLE
Bad grammar in "The automated release is failing"  message

### ISSUE THREAD

**Issue by HonkingGoose** [semantic-release/semantic-release#1917]
## Current behavior

We just got a automated release alert from our `semantic-release` bot: https://github.com/renovatebot/renovate/issues/9885 and I noticed there's a bit of bad grammar in the text message.

Relevant snippet of text from the bot message:

> If you are not sure how to resolve this, here is some links that can help you:
> 
>     - Usage documentation
>     - Frequently Asked Questions
>     - Support channels

## Expected behavior

I would have expected the message to say:

If you are not sure how to resolve this, here **are** some links that can help you:

## Environment

I'll do my best to provide the information.

- **semantic-release** version: 17.4.2
- CI environment: GitHub Actions, see https://github.com/renovatebot/renovate/blob/main/.github/workflows/build.yml
- Plugins used: "@semantic-release/exec": "5.0.0",
- **semantic-release** configuration: https://github.com/renovatebot/renovate/blob/main/.releaserc
- CI logs: I don't have the log, but I don't think that matters for this issue. 😄

**Comment by viceice** [comment]
The is not much we can do, as semantic-release doesn't pass the error to the issue. it was an npmjs.com outage

https://status.npmjs.org/incidents/vnj96yz3xvzr

**Comment by HonkingGoose** [comment]
Hi @viceice This issue is about the bad grammar. 😉 

I'm not talking about the fact that `semantic-release` does not pass on the **503** error from npmjs to the "The automated release is failing" issue text, though that problem maybe deserves a separate issue to discuss?

**Comment by viceice** [comment]
Sure, but that full issue message is completly generated by semantic-release, so no config in this repo.

So yo know a config option to chnage those message? Otherwise we need to push that upstream.

**Comment by HonkingGoose** [comment]
I'm sorry @viceice, but I really do not understand your post, sorry! 🙈 
Let's see if we can clarify this together. 😉 

---

> Sure, but that full issue message is completly generated by semantic-release, so no config in this repo.
> 
> So yo know a config option to chnage those message?

I have no idea what this means, sorry!

---

Just checking we're on the same page: we're now in the `semantic-release` repo, not in the `renovate` repo. 😉 

> Otherwise we need to push that upstream.

I think I **am**  upstream with the grammar bug report (`semantic-release`). If I'm not in the correct place to report this bug, please let me know and I'll file the bug in the correct place.

**Comment by HonkingGoose** [comment]
Turns out I'm in the wrong place!

https://github.com/semantic-release/github/blob/master/lib/get-fail-comment.js#L32-L35

Closing this issue now.

Sorry for the noise!

**Comment by viceice** [comment]
> I'm sorry @viceice, but I really do not understand your post, sorry! 🙈
> Let's see if we can clarify this together. 😉
> 
> > Sure, but that full issue message is completly generated by semantic-release, so no config in this repo.
> > So yo know a config option to chnage those message?
> 
> I have no idea what this means, sorry!
> 
> Just checking we're on the same page: we're now in the `semantic-release` repo, not in the `renovate` repo. 😉
> 
> > Otherwise we need to push that upstream.
> 
> I think I **am** upstream with the grammar bug report (`semantic-release`). If I'm not in the correct place to report this bug, please let me know and I'll file the bug in the correct place.

🙈  Written with closed 👀 .

Yes, as you found, we have no control over that issue message produced by `semantic-release`.

I tried to asked you, if you know a config option to change that message, but i'm pretty sure there is currently no option.
So If we like to change something, we need to open an issue at `semantic-release` (upstream) repo.

**Comment by HonkingGoose** [comment]
> 🙈 Written with closed 👀 .

Sorry for the crossed wires and confusion!

> I tried to asked you, if you know a config option to change that message, but i'm pretty sure there is currently no option.
> So If we like to change something, we need to open an issue at `semantic-release` (upstream) repo.

Oh you meant if we could change that message to something else ourselves. I don't think we can as well.

I think this is the source of the message: https://github.com/semantic-release/github/blob/master/lib/get-fail-comment.js#L32-L35

I've opened a issue (in hopefully the correct place!): https://github.com/semantic-release/github/issues/366

**Comment by viceice** [comment]
Thanks , sounds like the right repo. 👍
