### ISSUE TITLE
Deletes "version" from package.json

### ISSUE THREAD

**Issue by pensierinmusica** [semantic-release/semantic-release#195]
Hi,

When I have an existing project that is already pulished on npm, with several commits and versions, I've noticed that running `semantic-release-cli setup` in its home folder deletes the `"version"` field from `package.json`.

Is this normal / desired?

Thanks, cheers!

**Comment by stevemao** [comment]
https://github.com/semantic-release/semantic-release#why-is-the-packagejsons-version-not-updated-in-my-repository

> Why is the package.json’s version not updated in my repository?
The npm docs even state:
The most important things in your package.json are the name and version fields. Those are actually required, and your package won’t install without them. – npm docs
While this entirely true the version number doesn’t have to be checked into source control. semantic-release takes care of the version field right before npm publish uses it – and this is the only point where it really is required.

**Comment by pensierinmusica** [comment]
Thanks, I actually read that. It wasn't entirely clear to me though that it deletes the version field when it exists. I thought it would simply ignore it. Maybe this point could be clarified in the readme...

Cheers!

**Comment by stevemao** [comment]
I agree it's not so clear.... And the project looks unmaintained. I don't know if they still accept PRs.

**Comment by pensierinmusica** [comment]
Mmm, looks like there have been commits up until last month, so I'd say hope is not lost ;)

**Comment by boennemann** [comment]
semantic-release-cli >= 2 set's it to the placeholder "0.0.0-development"

**Comment by pensierinmusica** [comment]
Hi @boennemann, is this mentioned in the docs?

**Comment by khankuan** [comment]
@pensierinmusica im on v3.0.0. It seems like `package.json` got updated correctly after the release. Unfortunately that creates a change in package.json and the file needs to be pushed again.
