### ISSUE TITLE
No tokens

### ISSUE THREAD

**Issue by RWOverdijk** [semantic-release/semantic-release#197]
Hi, I'm seeing this:

> semantic-release ERR! init No github token specified. ENOGHTOKEN
> semantic-release ERR! init No npm token specified. ENONPMTOKEN

[source](https://travis-ci.org/SpoonX/aurelia-api#L328)

However, the cli has configured tokens for travis visibly:

> Environment Variables
GH_TOKEN 
••••••••••••••••
NPM_TOKEN

Is this a bug, or just me messing up somewhere?

**Comment by boennemann** [comment]
Hey @RWOverdijk,

the CLI only uploads the tokens if you chose the TravisCI option. It seems like you didn't do that, because they were logged to the terminal instead.

The Travis log also doesn't show that these variables get declared.

Please upload the tokens manually, or rerun the cli flow while choosing the TravisCI option.

Best,
Stephan

**Comment by RWOverdijk** [comment]
@boennemann I did select that option, they weren't logged to the terminal.

```
? Is the GitHub repository private? No
? What is your npm registry? https://registry.npmjs.org/
? What is your npm username? rwoverdijk
? What is your npm email? r.w.overdijk@gmail.com
? What CI are you using? Travis CI
? What kind of `.travis.yml` do you want? Create no `.travis.yml`
```

In the options above I chose "Create no .travis.yml" because I already created it last time I run the command.

**Comment by RWOverdijk** [comment]
Update... Even if I specify the token in travis, it still says I didn't.

**Comment by boennemann** [comment]
Ahh, sorry. Now I see where this is coming from. This is a Pull Request build and encrypted environment aren't exposed to those by Travis.

Everything should be fine on branches, especially on your master branch where releases will happen.

Best,
Stephan

**Comment by RWOverdijk** [comment]
@boennemann So, as soon as I merge you mean? (which makes sense, I don't think I want to publish on PRs)

**Comment by boennemann** [comment]
If you can see the two tokens created here https://travis-ci.org/SpoonX/aurelia-api/settings, then everything should be working fine after the merge :)

**Comment by crobinson42** [comment]
@boennemann Hey there - I have a project that's public but under an organization name - It seems the cli isn't able to find the project on Travis due to the different username/organization name prefix (my theory). Anyways - I looked at the travis logs and it's showing the missing github/npm token so semantic-release doesn't proceed. Any quick pointer on how to manually recreate what semantic-release does with these tokens? Thanks!

```
Is the GitHub repository private? No
? What is your npm registry? https://registry.npmjs.org/
? What is your npm username? coryrobinson42
? What is your npm email? coryrobinson42@gmail.com
? What is your GitHub username? crobinson42
? What CI are you using? Travis CI
ERR! semantic-release Could not get repository on Travis CI.
ERR! semantic-release { file: 'not found' }
```

https://travis-ci.org/pizza-rolls/node-api-server/builds/160954581

```
semantic-release ERR! init No github token specified. ENOGHTOKEN
semantic-release ERR! init No npm token specified. ENONPMTOKEN
```

**Comment by marvin-aoanan** [comment]
Is there an option to set github & npm to "FALSE"? I don't want to publish it in those two, I only want to push it to gilabCI?

**Comment by gr2m** [comment]
Use the [plugins configuration](https://semantic-release.gitbook.io/semantic-release/usage/configuration#plugins), remove the npm and github plugin:

https://semantic-release.gitbook.io/semantic-release/usage/configuration#plugins

**Comment by marvin-aoanan** [comment]
I am getting this error:
semantic-release ERR! init No github token specified. ENOGHTOKEN
semantic-release ERR! init No npm token specified. ENONPMTOKEN

package.json file:
`{
  "name": "semantic-release-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 0",
    "version": "npx semantic-release --no-ci"
  },
  "repository": {
    "type": "git",
    "url": "git@git.plaingaming.net:branding-projects/semantic-release-test.git"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@semantic-release/commit-analyzer": "^8.0.1",
    "@semantic-release/release-notes-generator": "^9.0.1",
    "semantic-release": "^8.0.1"
  },
  "release": {
    "plugins": [
      "@semantic-release/commit-analyzer",
      "@semantic-release/release-notes-generator",
      [
        "@semantic-release/npm",
        {
          "npmPublish": false
        }
      ],
      "@semantic-release/changelog",
      "@semantic-release/git"
    ],
    "branch": "master"
  }
}
`

gitlab-ci.yml file:
`stages:
  - release

release:
  image: node:10-buster-slim
  stage: release
  before_script:
    - apt-get update && apt-get install -y --no-install-recommends git-core ca-certificates
    - npm install --progress false semantic-release @semantic-release/gitlab
  script:
    - npx semantic-release
  only:
    - master

release:
  image: node:12-buster-slim
  stage: release
  before_script:
    - apt-get update && apt-get install -y --no-install-recommends git-core ca-certificates
    - npm install --progress false semantic-release @semantic-release/gitlab
  script:
    - npx semantic-release
  only:
    - master`
