### ISSUE TITLE
Error: SyntaxError: Unexpected token '.'

### ISSUE THREAD

**Issue by leckylao** [semantic-release/semantic-release#1981]
## Current behavior

The Github Action was working perfectly for a while, and today it suddenly comes with this SyntaxError from nowhere. Any new PR would have this error and failed but the last commit on master branch was working. I've checked there's no code and repo changes related to it

Any idea is welcome. 

> Run cycjimmy/semantic-release-action@v2
> 
>   with:
> 
>     extra_plugins: @semantic-release/changelog
> 
>   @semantic-release/github
> 
>   @semantic-release/commit-analyzer
> 
>   @semantic-release/release-notes-generator
>   
> 
>   env:
> 
>     GITHUB_TOKEN: ***
> 
> added 2 packages, and audited 3 packages in 469ms
> 
> 
> found 0 vulnerabilities
> 
> Error: SyntaxError: Unexpected token '.'

## Expected behavior

> Run cycjimmy/semantic-release-action@v2
> added 2 packages in 0.219s
> [3:03:14 AM] [semantic-release] › ℹ  Running semantic-release version 17.4.3
> [3:03:14 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/github"
> [3:03:14 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/changelog"
> [3:03:14 AM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
> [3:03:14 AM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
> [3:03:14 AM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/changelog"
> [3:03:14 AM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/github"
> [3:03:14 AM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/github"
> [3:03:14 AM] [semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/github"
> [3:03:14 AM] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/github"
> [3:03:17 AM] [semantic-release] › ℹ  This test run was triggered on the branch fix/contract-compile-warning, while semantic-release is configured to only publish from 1.x, 2.x, release, rc, therefore a new version won’t be published.

## Environment

- **semantic-release** version: Tried both 17.4.4 and 17.4.3
- CI environment: Github Action
- Plugins used: @semantic-release/changelog
            @semantic-release/github
            @semantic-release/commit-analyzer
            @semantic-release/release-notes-generato
- **semantic-release** configuration: 

> {
>   plugins: [
>     "@semantic-release/commit-analyzer",
>     "@semantic-release/github",
>     "@semantic-release/release-notes-generator",
>     "@semantic-release/changelog"
>   ],
>   branches: [
>     {name: '1.x', range: '1.x', channel: '1.x'},
>     {name: '2.x', range: '2.x', channel: '2.x'},
>     {name: 'release'},
>     {name: 'rc', channel: 'rc', prerelease: 'rc'},
>   ]
> }

**Comment by cedroid09** [comment]
Same thing, got this error too on Gitlab.

**Comment by goir** [comment]
we're having the same problem in a gitlab context.

```
$ npx semantic-release
/usr/local/lib/node_modules/semantic-release/node_modules/marked/src/marked.js:158
          const prevRenderer = extensions.renderers?.[ext.name];
                                                    ^
SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/semantic-release/index.js:2:16)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
```

**Comment by cedroid09** [comment]
Downgrade to the previous major version release:
`- npm install -g semantic-release@16 @semantic-release/gitlab`

Workaround until this is fixed.

**Comment by TadeuszMiesowicz** [comment]
> Downgrade to the previous major version release:
> `- npm install -g semantic-release@16 @semantic-release/gitlab`
> 
> Workaround until this is fixed.

thx, works with github actions too

**Comment by inian** [comment]
This is the workaround which worked for me if you are using Github actions https://github.com/supabase/storage-api/commit/215b17801732aa42ea63dbb68903cca11bc960b0

**Comment by sparanoid** [comment]
This is caused by your environments not supporting optional chaining for the following code:

```js
const prevRenderer = extensions.renderers?.[ext.name];
```

You can upgrade your CI environments to Node.js 14 or later to resolve this issue. For GitHub Actions:

```yaml
      - uses: actions/setup-node@v2
        with:
          node-version: 16
```

**Comment by GooBall** [comment]
> This is caused by your environments not supporting optional chaining for the following code:
> 
> ```js
> const prevRenderer = extensions.renderers?.[ext.name];
> ```
> 
> You can upgrade your CI environments to Node.js 14 or later to resolve this issue. For GitHub Actions:
> 
> ```yaml
>       - uses: actions/setup-node@v2
>         with:
>           node-version: 16
> ```

Can confirm this works (I went to node 14 from 12).

**Comment by varl** [comment]
Node 14.x became the active LTS in April 2021 and according to the [node support policy](https://github.com/semantic-release/semantic-release/blob/master/docs/support/node-support-policy.md) only the latest LTS is supported.

As far as I can tell the behavior here is technically correct, and what's missing is a major bump to 18.0.0 that updates the `engines`[1] and generates a release for the bump to node 14[2].

It would be nice if this was reverted from 17.x releases, and pushed to 18.x.

---

[1] https://github.com/semantic-release/semantic-release/blob/master/package.json#L73
[2] https://github.com/semantic-release/semantic-release/releases/tag/v17.0.0

**Comment by lapa182** [comment]
> Node 14.x became the active LTS in April 2020 and according to the [node support policy](https://github.com/semantic-release/semantic-release/blob/master/docs/support/node-support-policy.md) only the latest LTS is supported.
> 
> As far as I can tell the behavior here is technically correct, and what's missing is a major bump to 18.0.0 that updates the `engines`[1] and generates a release for the bump to node 14[2].
> 
> It would be nice if this was reverted from 17.x releases, and pushed to 18.x.
> 
> [1] https://github.com/semantic-release/semantic-release/blob/master/package.json#L73
> [2] https://github.com/semantic-release/semantic-release/releases/tag/v17.0.0

In theory v12 it's still LTS and the policy doesn't say "active" since a bunch of users needs to support other users in v12, but agree if a change it's a "breaking change" it should bump to 18.x, this way if we can limit to install only changes from 17.x.

**Comment by varl** [comment]
> In theory v12 it's still LTS and the policy doesn't say "active" since a bunch of users needs to support other users in v12, but agree if a change it's a "breaking change" it should bump to 18.x, this way if we can limit to install only changes from 17.x.

I'm not an expert in NodeJS release semantics, nor in how the `semantic-release` devs interprets "LTS", so I cannot argue the theory

The [NodeJS Release](https://github.com/nodejs/Release#release-schedule) working group uses "LTS" only for the "Active Long Term Support" version, so in their lingo, Node 12 is in "Maintenance" and Node 14 is in "LTS":

> There are three phases that a Node.js release can be in: 'Current', '**Active Long Term Support (LTS)'**, and 'Maintenance'

For what it's worth, I thought that Node 12.x was "technically LTS" up until an hour ago and I started reading fine print.

:shrug:

**Comment by portellaa** [comment]
hey @leckylao check out this comment https://github.com/cycjimmy/semantic-release-action/issues/69#issuecomment-862207060

**Comment by james-gonzalez** [comment]
This fixed it for me: (GitLab CI)

```yaml
  image: node:16
  script:
    - npm install -g semantic-release @semantic-release/gitlab @semantic-release/changelog @semantic-release/git
    - npx semantic-release
```

**Comment by kkaulen** [comment]
This error is due to a breaking change in marked.js, which is a dependency of semantic-release.
They are aware of this:
https://github.com/markedjs/marked/issues/2106
And it seems as it was fixed already:
https://github.com/markedjs/marked/pull/2109

**Comment by Adiii717** [comment]
Having the same issue on `node:10` in Gitlab.

Using Node version `14.x` or `16.x` resolve the issue
```
release:
  stage: release
  image: node:16
  .
  .
```

**Comment by chemelli74** [comment]
Seems I have the same token error but on a different file:

```
/usr/local/lib/node_modules/npm/node_modules/@npmcli/config/lib/definitions/definitions.js:2244
    const ciName = ciInfo.name?.toLowerCase().split(' ').join('-') || null
                               ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/config/lib/definitions/index.js:1:21)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
```

Let me know if you prefer a fresh issue

**Comment by travi** [comment]
Upgrade to a supported version of node and semantic-release

**Comment by inyong1** [comment]
> Seems I have the same token error but on a different file:
> 
> ```
> /usr/local/lib/node_modules/npm/node_modules/@npmcli/config/lib/definitions/definitions.js:2244
>     const ciName = ciInfo.name?.toLowerCase().split(' ').join('-') || null
>                                ^
> 
> SyntaxError: Unexpected token '.'
>     at wrapSafe (internal/modules/cjs/loader.js:915:16)
>     at Module._compile (internal/modules/cjs/loader.js:963:27)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
>     at Module.load (internal/modules/cjs/loader.js:863:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
>     at Module.require (internal/modules/cjs/loader.js:887:19)
>     at require (internal/modules/cjs/helpers.js:74:18)
>     at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/config/lib/definitions/index.js:1:21)
>     at Module._compile (internal/modules/cjs/loader.js:999:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
> ```
> 
> Let me know if you prefer a fresh issue

same here
```
/home/aps/.nvm/versions/node/v20.12.2/lib/node_modules/npm/node_modules/@npmcli/config/lib/definitions/definitions.js:2276
const ciName = ciInfo.name?.toLowerCase().split(' ').join('-') || null
                          
SyntaxError: Unexpected token '.'
```

how to fix this?
