### ISSUE TITLE
Can't parse change on Travis but can on local machine

### ISSUE THREAD

**Issue by ghaiklor** [semantic-release/semantic-release#200]
Hi. If I'm running semantic-release locally it prints the following:

``` shell
 ~/L/P/cursor   master   npm run semantic-release

> kittik-cursor@0.0.0-semantic-release semantic-release /Users/ghaiklor/Library/Projects/cursor
> semantic-release pre && npm publish && semantic-release post

semantic-release WARN pre semantic-release didn’t run on Travis CI and therefore a new version won’t be published.
semantic-release WARN pre You can customize this behavior using "verifyConditions" plugins: git.io/sr-plugins
semantic-release ERR! pre Determined version 3.1.0 as "latest". Not publishing in debug mode. { type: 'minor', version: '3.1.0' }
```

But if running on Travis CI:

``` shell
$ npm run semantic-release
> kittik-cursor@0.0.0-semantic-release semantic-release /home/travis/build/kittikjs/cursor
> semantic-release pre && npm publish && semantic-release post
semantic-release ERR! commits The commit the last release of this package was derived from is not in the direct history of the "master" branch.
semantic-release ERR! commits This means semantic-release can not extract the commits between now and then.
semantic-release ERR! commits This is usually caused by force pushing, releasing from an unrelated branch, or using an already existing package name.
semantic-release ERR! commits You can recover from this error by publishing manually or restoring the commit "ab2b7d1bdee818855569eced566f8d59576a2eb2".
semantic-release ERR! pre Failed to determine new version.
semantic-release ERR! pre ENOTINHISTORY Commit not in history
```

How can it be fixed ?

**Comment by ghaiklor** [comment]
@boennemann any thoughts ?

**Comment by boennemann** [comment]
Are you sure the local branch is exactly the same as the one running on Travis?

This error is usually caused by force-pushing, see: https://github.com/semantic-release/semantic-release/issues/132

**Comment by ghaiklor** [comment]
@boennemann yeah, I'm sure. All what I do with master branch is merging with dev.

**Comment by ghaiklor** [comment]
@boennemann so what the procedure for restoring the commit ? Can I do this without losing my changes ?

**Comment by finom** [comment]
The same bullshit there.  Have no idea why does it appear. I even tried to publish a package manually but this gives no progress.

**Comment by ahmadnassri** [comment]
same issue here? how to resolve this?

**Comment by sgimeno** [comment]
You can solve it by manually publishing a version and then re-building on Travis or restore the commit meaning you need to push force again :/

**Comment by vanduynslagerp** [comment]
Travis pulls only 50 commit commits from the history. So the commit that was used for the last release is more than 50 commit back, `semantic-release` will not find it.
See https://docs.travis-ci.com/user/customizing-the-build#Git-Clone-Depth
