### ISSUE TITLE
Add `cache` to workflows using `actions/setup-node`

### ISSUE THREAD

**Issue by oscard0m** [semantic-release/semantic-release#2010]
## New feature motivation
`setup-node` GitHub Action just released a new option to add cache to steps using it.

You can find the details here: https://github.blog/changelog/2021-07-02-github-actions-setup-node-now-supports-dependency-caching/

## New feature description
- Add cache to workflows using actions/setup-node
- Remove other cache steps (if they exist) in the job.
   - ⚠️ Before removing (https://github.com/bahmutov/npm-install), check what it does and if it's safe to remove it or there should be extra work to do after adding native `setup-node` cache 

## New feature implementation
Something like this: https://github.com/semantic-release/semantic-release/pull/2008 but considering existing cache steps.

**Comment by gr2m** [comment]
@travi and I discussed the exact thing the other day. We would like to remove the `bahmutov/npm-install` action as we repeatedly had problems with it in the past and use the new `cache: npm` option instead. So PRs for all repos would be very welcome.

**Comment by travi** [comment]
thanks for the help with this, @oscard0m! i plan to try out your octoherd script on a couple of my other orgs soon, too

**Comment by oscard0m** [comment]
> thanks for the help with this, @oscard0m! i plan to try out your octoherd script on a couple of my other orgs soon, too

You're welcome! 😉

If you need help running it, let me know. Also, feel free to open an issue if you find any bug or not covered use-case.
