### ISSUE TITLE
$BUILD_LEADER not set if there is no matrix

### ISSUE THREAD

**Issue by gr2m** [semantic-release/semantic-release#205]
Hey, I wonder if we could set `$BUILD_LEADER` to true if there is no test matrix? I usually put something like this in my repos into `after_success`:

```
- if [[ $BUILD_LEADER = YES ]]; echo "running coverage" && then npm run test:coverage && npm run test:coverage:upload; fi
```

and just realized it’s not run at all if a repo has no test matrix :)

**Comment by boennemann** [comment]
Here is a quick-solution that is probably unrelated to the problem you want to fix.
Run coverage for every build, coveralls correctly handles that :)

The `BUILD_LEADER` variable was originally set by the python script `travis_after_all`, while the js version that is used in "next" does no longer set it.

I'll leave this open if someone wants to add it.
