### ISSUE TITLE
raise the minimum required version of node

### ISSUE THREAD

**Issue by travi** [semantic-release/semantic-release#2054]
node v10 is now end-of-life, so we should not continue to support it. in addition, many of our dependencies have been updated to be ESM-only and can no longer be `require`d. 

### The plan

* require a minimum node version of the latest LTS, currently 14.17
* attempt to make the core `semantic-release` package ESM only, based on an initial assessment from @gr2m 

### Additional tasks

* ensure `engines-strict` is enforced in the CI of each project to reduce the cases where incompatible dependencies are installed outside of our supported range ([example](https://github.com/semantic-release/semantic-release/blob/88e423b8286cfe852d8348d174e621c1e39e42d8/.github/workflows/test.yml#L36))

### Projects to update

- [x] #2055
- [x] https://github.com/semantic-release/commit-analyzer/issues/244
- [x] https://github.com/semantic-release/error/issues/169
- [x] https://github.com/semantic-release/github/issues/394
- [x] https://github.com/semantic-release/npm/issues/380
- [x] https://github.com/semantic-release/release-notes-generator/issues/259

### Pull Requests welcome

Please pick any of the issues of the list above that is not yet assigned, we really appreciate your help 💐

**Comment by gr2m** [comment]
We decided to go ahead and start releasing beta versions of `semantic-release` so that we can set `peerDependencies` for `semantic-release` in the plugins to `>=18.0.0-beta.1`

**Comment by gr2m** [comment]
All done w00p
