### ISSUE TITLE
ENOCHANGE on first publish

### ISSUE THREAD

**Issue by ryan-kimber** [semantic-release/semantic-release#208]
If there have been no previous publishes, semantic-release will still fail with ENOCHANGE if the commit analyzer returns no changes.

Wouldn't a better behaviour be to publish v1.0.0 regardless?

**Comment by thiagofelix** [comment]
The reason why it raises ENOCHANGE is not because there have been no previous publishes.
It is actually because there isn't any relevant commit on your history.

The default implementation uses [conventional-changelog](https://github.com/ajoslin/conventional-changelog) style of commits.

So it makes sense to refuse to publish when it is not possible to tell the next release version or generate proper changelog document.

Lastly, dealing with the special condition of "never published before" would add unnecessary complexity IMO =)

**Comment by tusharmath** [comment]
I think then there should be a separate command to make the initial release. Its quite cumbersome other wise because semantic-release deletes the version from package.json.  Any thoughts?

**Comment by thiagofelix** [comment]
Well, it is a bit cumberstome yes.
But you need to start using conventional-changelog since the beggining, and make sure you have feat/fix commits by the time you release you package.

Because if you don't have feat/fix to release, what are u release them ? =p

**Comment by ryan-kimber** [comment]
For an initial release, it can be a bit of a pain - the change log isn't
really appropriate. That is, we're releasing a new library, it's supposed
to be v1.0 - I probably don't want every commit tracked in a change log and
I probably don't want to have to list a 'breaking change' or list of
individual features - I just want it to become 1.0.0.

This should be default behaviour (not even a separate switch on the command
line) so that it doesn't require separate handling in a CI process. The
first time I merge code to master, I should be able to run
semantic-release, it should see that there's no previous version, and it
should create a 1.0.

Once a 1.0.0 is out there, the change-log and auto-versioning makes sense.

**Comment by voidberg** [comment]
I'm in the same situation, I haven't used conventional-changelog from the beginning and now semantic-release won't do the first release, even with a new feat. What would be the solution in this case (ignoring removing the repo and doing a one time big import of all the code as a feature)?

**Comment by ryan-kimber** [comment]
In my use-case, I renamed my modules. That will work, but it's a
frustrating solution.

Another option you could explore (but I haven't tried this), is to push a
new version of your module to NPM (and make it your 'latest' or custom
equivalent) and use a semantic-formatted version name that doesn't conflict
with your existing naming. Once you've done that, semantic-release *might*
behave.

**Comment by pvdlg** [comment]
`semantic-release` will make the initial release, as soon there is at least a commit that trigger a release (by default `fix`, `feat`). This is the intended behavior.
For the first commit on your repo you can for example use `feat: Initial release`. That will trigger release `1.0.0`.

If you have a repo with several commits and some releases already done before configuring `semantic-release` everything should work smoothly as soon as `semantic-release` is configured and you start using formatted commits.

`semantic-release` starts version at `1.0.0` and it's a design chose. The whole point of `semantic-release` being to remove  the connection between human emotions and version numbers by following semver.
