### ISSUE TITLE
Can't install version 17.4.5: peer dependencies are incorrect

### ISSUE THREAD

**Issue by kaiyoma** [semantic-release/semantic-release#2086]
## Current behavior

Installing this package fails with pnpm:

```
ERROR  semantic-release: marked-terminal@4.1.1 requires a peer of marked@^1.0.0 || ^2.0.0 but version 3.0.0 was installed.
```

## Expected behavior

The package should install.

## Environment

- **semantic-release** version: 17.4.5

**Comment by travi** [comment]
thanks for the report @kaiyoma. we added `engine-strict` to our ci checks to avoid situations like this, but didnt realize that there is a bug with npm that prevents the expected failure with `npm ci`. 

i've begun the process of reverting and updated the check to instead use `npx ls-engines`: https://github.com/semantic-release/semantic-release/pull/2087. i'll close this issue, but you can follow there for progress

**Comment by kaiyoma** [comment]
@travi Sounds good, thanks for the quick response!
