### ISSUE TITLE
Artifactory Integration

### ISSUE THREAD

**Issue by thiagofelix** [semantic-release/semantic-release#213]
Hi All.

Can I have this issue here to track [RTFACT-9773](https://www.jfrog.com/jira/browse/RTFACT-9773)?
So people experiencing the same problem when working with Artifactory can follow along the status of the bug.

This problem pretty much prevents the usage of semantic-release with Artifactory because of #8.
Artifactory do not expose gitHead on their local repository, and consequently all commits are published/released regardless if it contains relevant changes or not.

**Comment by jbcpollak** [comment]
@thiagofelix I also ran into issue #300 with Artifactory - do you have a workaround for that?

**Comment by vampolo** [comment]
Ran on the same problem and verified that `npm view mypackage@latest --registry=JFROG | grep gitHead` returns empty. Any workaround?

**Comment by paulkenney** [comment]
It seems that https://github.com/semantic-release/semantic-release/issues/8 broke this library for use Artifactory users. Has anyone looked into reverting that refactoring or at least making is so that if gitHead is not provided (as is the case with Artifactory) then the less efficient method is used which queries GitHub for tags?

**Comment by Starefossen** [comment]
+1 for support for Artifactory!

**Comment by vampolo** [comment]
For what it is worth i tried to contact Artifactory support to let them know about this problem. They seemed unresponsive.

**Comment by FezVrasta** [comment]
Any chance to perform the work suggested by @paulkenney?

Are PRs accepted for this?

**Comment by jbcpollak** [comment]
I solved this problem by switching to go-semantic-release and letting npm
handle the deployment step

**Comment by FezVrasta** [comment]
Do you know if there's a Lerna integration for it?

**Comment by jbcpollak** [comment]
I haven't done it yet, but I looked into that a little bit. My solution was going to be something like this:

```
#!/bin/bash
~/semantic-release -vf
export VERSION=$(cat .version)
lerna publish --repo-version ${VERSION} --yes
```

There are a lot of useful command line switches on the lerna publish command: https://github.com/lerna/lerna#commands

Hope that helps.

**Comment by pvdlg** [comment]
I think should be solved by https://github.com/semantic-release/semantic-release/pull/453, which is in `semantic-release@8.1.0` currently release on the `next` dist-tag.
Could you give `semantic-release@8.1.0` a try and let us know if that solve the issue ?
