### ISSUE TITLE
Signed tags

### ISSUE THREAD

**Issue by Conaclos** [semantic-release/semantic-release#214]
Hi!

I'm currently signing each tag (GPG signing) by default.

Is there any solution to force semantic-release to use the command `git tag -s` instead of a github token?
Of course, I run semantic-release on local.

Thanks.

**Comment by destroyerofbuilds** [comment]
`semantic-release` would still need your GitHub token to push an update to your project's Releases page. 

Otherwise, it would be nice to have signed tags. Would go really well with the recent release of signature verification released by GitHub.

**Comment by Conaclos** [comment]
@destroyerofbuilds Thanks for your relevant reply ;)
