### ISSUE TITLE
Seeing oddities with this recent release around dependencies

### ISSUE THREAD

**Issue by travi** [semantic-release/semantic-release#2148]
Seeing oddities with this recent release around dependencies. We use a CI/CD template that was working until 4 days ago in-line with the 18.0.0 release. Can't quite put my finger on why this isn't working properly as it seemingly can find the intended packages, but we end up in issues with dependancies. Cleared the cache to no avail, we should be pinning anyway so gone and done so. 

We're using Docker in CI/CD and running fresh installs release 

**NodeJS** **Version**: 16.5

This is the script we were using to do our releases:

```
before_script:
  - npm install semantic-release
  - npm install @semantic-release/commit-analyzer
  - npm install @semantic-release/release-notes-generator
  - npm install @semantic-release/gitlab
  - npm install @semantic-release/changelog
  - npm install @semantic-release/git
```

We had to pin the following packages:

```
1. @semantic-release/commit-analyzer
2. @semantic-release/release-notes-generator
3. @semantic-release/gitlab
4. @semantic-release/git
```

All of the above packages resulted in the following error:

```
$ npm install @semantic-release/git
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: newstore-import-poller@0.0.1
npm ERR! Found: semantic-release@17.4.7
npm ERR! node_modules/semantic-release
npm ERR!   semantic-release@"^17.4.7" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer semantic-release@">=18.0.0" from @semantic-release/git@10.0.0
npm ERR! node_modules/@semantic-release/git
npm ERR!   @semantic-release/git@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /root/.npm/eresolve-report.txt for a full report.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-09-21T22_15_14_622Z-debug.log
```

Hope this helps rather than confusing anything! Let me know if you need a hand with anything, but fairly new with `npm`!

_Originally posted by @triwats in https://github.com/semantic-release/semantic-release/issues/2146#issuecomment-924437166_

**Comment by travi** [comment]
@triwats this failure is legitimate because you are installing packages that are defined to be incompatible due to peer dependencies. the original breaking change for this round of updates released semantic-release core and the packages that it directly depends on. we are still in the process of updating the remaining official plugins.

from the list you provided, the changelog and git plugins have been released with the changes to make them compatible, but the gitlab plugin is still outstanding.

it is your responsibility to ensure that your dependency tree is valid, and peer dependencies are part of that tree that needs to be valid. `npm ls` is an effective tool to ensure that your tree is valid as it will exit non-zero for a tree with unmet peer dependencies. verifying with `npm ls` is less necessary with npm v7 because it attempts to handle peer dependencies automatically and will fail with an error like the one you reported above if the tree is invalid.

until all plugins that you are using have been updated, you can either continue to use the previous versions that are compatible with each other, or you can help us move any remaining ones that you use forward by submitting a PR like [this one](https://github.com/semantic-release/github/pull/397/files) against the plugin(s) that you still need updated.

**Comment by triwats** [comment]
@travi - first off thanks for moving this and moving it to a new issue and then doing a follow up! 

For my understanding, I'm still not sure on the issue for this project in this case or what root cause is, is this just to fall in line behind an LTS release? When you say:

> the original breaking change for this round of updates released semantic-release core

Is that the specific upgrade to Node 14?

Looks like @greg0rie has put in a fix in this case here, thanks for that!
https://github.com/semantic-release/gitlab/commit/36d1665bb297258ec69d6573f9d793f46d3edb2a

I'll try again with this unpinned and see if it now passes, as I believe the maintainers have rolled out most changes already, if not I will aim to roll my sleeves up. Thanks for the work on this all!

Regardless, I think we can close this.

**Comment by travi** [comment]
> I'm still not sure on the issue for this project in this case or what root cause is, is this just to fall in line behind an LTS release? When you say:
> 
> > the original breaking change for this round of updates released semantic-release core

the important point is that we released the core `semantic-release` package along with _some_ of the official plugins. the packages define peer dependency requirements that need to be satisfied for npm v7 to succeed with installation. the packages that were released later, also define peer dependency requirement, which were not compatible with the newly released ones. until those were also updated, there was not a compatible combination without installing older versions of the packages that had recent releases. `npm ls` can help identify this situation.

since the other packages have been released at this point, your problem should be solved, so i will close this issue. feel free to reopen if you are still seeing problems.
