### ISSUE TITLE
Deployment without npm registry

### ISSUE THREAD

**Issue by leifg** [semantic-release/semantic-release#215]
Hello there,

I am currently using semantic release for one of my libraries ([leifg/formulon](https://github.com/leifg/formulon) if you're interested).

But I also use it for a frontend project which is not released on the npm registry ([leifg/formulon-frontend](https://github.com/leifg/formulon-frontend)). I just replaced `npm publish` with `npm run deploy` and it works perfectly.

I ran into the problem that the CI system expects an NPM_TOKEN and fails if it doesn't. An easy workaround is just to set the env variable to something irrelevant but I don't feel that this is a good solution.

Is there a better way?

**Comment by marcusnielsen** [comment]
I think lots of people don't want to publish to npm for apps, but still want the semver for tracking releases internally. 

I'm glad I found this question and its hot-fix solution! 👍

**Comment by jwright04** [comment]
Just ran across this which works nicely: https://github.com/finom/last-release-git
