### ISSUE TITLE
Fix typo in release note for `v18.0.0`

### ISSUE THREAD

**Issue by HonkingGoose** [semantic-release/semantic-release#2153]
## Current behavior

The name of your package has a typo in the release notes for `v18.0.0`

> An increasing amount of dependencies required a node version higher than the Node 10 version supported by `semantic-relase@17`.

See the release note here: https://github.com/semantic-release/semantic-release/releases/tag/v18.0.0

## Expected behavior

Change `semantic-relase@17` -> `semantic-release@17`

## Environment

- **semantic-release** version: Doesn't matter.
- CI environment: Doesn't matter.
- Plugins used: Doesn't matter.
- **semantic-release** configuration: Doesn't matter.
- CI logs: Doesn't matter.

**Comment by travi** [comment]
fixed. thank you for the heads up!

**Comment by HonkingGoose** [comment]
Thank you for the quick fix @travi! ❤️
