### ISSUE TITLE
Option to force publish

### ISSUE THREAD

**Issue by gavriguy** [semantic-release/semantic-release#216]
I think we should add an option to force publish to npm;
I experienced an issue with my Travis setup that made me skip a BREAKING CHANGE update. (it was my fault I accidentally turn off the travis pull trigger). The problem that after discovering my error I couldn't publish an update and i had to revert my repo and re-commit my change causing my git history to look wired (without a reason - my problem wasn't in the code itself)

I would love to hear your thoughts on the matter.

**Comment by pvdlg** [comment]
@gavriguy can you clarify what do you mean by force publish?
If you mean `npm publish -f` it's not supported anymore: http://blog.npmjs.org/post/77758351673/no-more-npm-publish-f

I'm not sure I understand the relation between the Travis job not running and the need to force publish...Can you clarify?

If the release didn't happen because of an issue on Travis, I would suggest to just restart the job on Travis after your configuration is fixed. Would that solve your issue?

**Comment by gavriguy** [comment]
Sorry It's been I while so I don't remember exactly the issue I had. Your suggestion sounds like a good solution.
Closing this issue as I'm not sure how to reproduce it anymore

**Comment by AnandChowdhary** [comment]
@pvdlg Do you think we can re-open this issue? The use case to "force" a Semantic Release would be in cases where there are no commits or non-semantic commits that shouldn't trigger a release, but we want to manually say "do a patch release anyway". Or is there already an option to skip the commit analysis and "force" a new release?

**Comment by dominykas** [comment]
This can easily be achieved via a custom plugin, e.g. something trivial like this:

```

exports.analyzeCommits = (pluginConfig, context) => {

    return context.env.FORCE_PUBLISH;
};
```


You'll probably want to add some validation, etc for valid values and maybe some logging, but that's the gist of it.

**Comment by ringerc** [comment]
For other readers, note that the `FORCE_PUBLISH` value here is assumed to be a valid semantic-release type `major`, `minor` or `patch`.

You cannot use this to, say, attempt to force semantic-release to create a new release without incrementing the version, if you're trying to abuse pre-commit labels to do post-release sub-patch releases for a patch version.
