### ISSUE TITLE
Getting ENEEDAUTH with valid token.

### ISSUE THREAD

**Issue by dimitrisfasoulas** [semantic-release/semantic-release#2167]
I have 2 different repo's that use semantic-release inside a Jenkin pipeline to release to a private repository.

Recently one of them started failing with ENDEEDAUTH, even though NPM_TOKEN is a set and is a valid token.

Upon further investigation (packagelock.json), I found out that the failing repo uses @semantic-release/npm 7.1.3 (which has npm 7 as a dependency), while the repo that was working had @semantic-release/npm 7.0.10 (npm ^6.14.9).

I pinned the version to 7.0.10 and publish started working again.

I decided to install latest version of semantic but it still fails.
## Current behavior

Publish fails with ENEEDAUTH even though a valid NPM_TOKEN is set.

## Expected behavior

Publish should not fail

## Environment

- **semantic-release** version: "^18.0.0"
"@semantic-release/changelog": "^6.0.0",
"@semantic-release/git": "^10.0.0",
- CI environment: Jenkins
- Plugins used: release-notes-generator, changelog, npm, git
- **semantic-release** configuration: https://gist.github.com/dimitrisfasoulas/07a5338cee20bf5d980dbc98a2cd8801
- CI logs: 

17:16:03  [5:16:03 PM] [semantic-release] › ℹ  Running semantic-release version 18.0.0
17:16:03  [5:16:03 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/changelog"
17:16:03  [5:16:03 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/npm"
17:16:03  [5:16:03 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/git"
17:16:03  [5:16:03 PM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
17:16:03  [5:16:03 PM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
17:16:03  [5:16:03 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/changelog"
17:16:03  [5:16:03 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/npm"
17:16:03  [5:16:03 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/git"
17:16:03  [5:16:03 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/npm"
17:16:03  [5:16:03 PM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/npm"
17:16:05  [5:16:05 PM] [semantic-release] › ✔  Run automated release from branch pipeline-test on repository ssh://git@privatehost.com:7999/reponame.git
17:16:05  [5:16:05 PM] [semantic-release] › ✔  Allowed to push to the Git repository
17:16:05  [5:16:05 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/changelog"
17:16:05  [5:16:05 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/changelog"
17:16:05  [5:16:05 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/npm"
17:16:05  [5:16:05 PM] [semantic-release] [@semantic-release/npm] › ℹ  Verify authentication for registry https://artifactory.privatehost.com:8443/artifactory/api/npm/npm-local/
17:16:05  [5:16:05 PM] [semantic-release] [@semantic-release/npm] › ℹ  Reading npm config from /mnt/sdb1/buildmaster-agent/workspace/Front_End_a.m.m.o._pipeline-test/.npmrc
17:16:05  [5:16:05 PM] [semantic-release] [@semantic-release/npm] › ℹ  Wrote NPM_TOKEN to /mnt/sdb1/tmp/c8fafd3286e673fab580f41a4bc02bba/.npmrc
17:16:05  [5:16:05 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/npm"
17:16:05  [5:16:05 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/git"
17:16:05  [5:16:05 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/git"
17:16:05  [5:16:05 PM] [semantic-release] › ℹ  Found git tag v2.7.1 associated with version 2.7.1 on branch pipeline-test
17:16:05  [5:16:05 PM] [semantic-release] › ℹ  Found 2 commits since last release
17:16:05  [5:16:05 PM] [semantic-release] › ℹ  Start step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
17:16:05  [5:16:05 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: fix: [XX-00] Testing node lts latest npm
17:16:05  [5:16:05 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is patch
17:16:05  [5:16:05 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: fix: [XX-00] Testing node lts latest npm
17:16:05  [5:16:05 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is patch
17:16:05  [5:16:05 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analysis of 2 commits complete: patch release
17:16:05  [5:16:05 PM] [semantic-release] › ✔  Completed step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
17:16:05  [5:16:05 PM] [semantic-release] › ℹ  The next release version is 2.7.2-0pipelinetest.1
17:16:05  [5:16:05 PM] [semantic-release] › ℹ  Start step "generateNotes" of plugin "@semantic-release/release-notes-generator"
17:16:05  [5:16:05 PM] [semantic-release] › ✔  Completed step "generateNotes" of plugin "@semantic-release/release-notes-generator"
17:16:05  [5:16:05 PM] [semantic-release] › ℹ  Start step "prepare" of plugin "@semantic-release/changelog"
17:16:05  [5:16:05 PM] [semantic-release] [@semantic-release/changelog] › ℹ  Update /mnt/sdb1/buildmaster-agent/workspace/Front_End_a.m.m.o._pipeline-test/CHANGELOG.md
17:16:05  [5:16:05 PM] [semantic-release] › ✔  Completed step "prepare" of plugin "@semantic-release/changelog"
17:16:05  [5:16:05 PM] [semantic-release] › ℹ  Start step "prepare" of plugin "@semantic-release/npm"
17:16:05  [5:16:05 PM] [semantic-release] [@semantic-release/npm] › ℹ  Write version 2.7.2-0pipelinetest.1 to package.json in /mnt/sdb1/buildmaster-agent/workspace/Front_End_a.m.m.o._pipeline-test
17:16:05  v2.7.2-0pipelinetest.1
17:16:06  [5:16:05 PM] [semantic-release] › ✔  Completed step "prepare" of plugin "@semantic-release/npm"
17:16:06  [5:16:05 PM] [semantic-release] › ℹ  Start step "prepare" of plugin "@semantic-release/git"
17:16:06  [5:16:06 PM] [semantic-release] [@semantic-release/git] › ℹ  Found 3 file(s) to commit
17:16:07  [5:16:06 PM] [semantic-release] [@semantic-release/git] › ℹ  Prepared Git release: v2.7.2-0pipelinetest.1
17:16:07  [5:16:06 PM] [semantic-release] › ✔  Completed step "prepare" of plugin "@semantic-release/git"
17:16:07  [5:16:06 PM] [semantic-release] › ℹ  Start step "generateNotes" of plugin "@semantic-release/release-notes-generator"
17:16:07  [5:16:06 PM] [semantic-release] › ✔  Completed step "generateNotes" of plugin "@semantic-release/release-notes-generator"
17:16:07  [5:16:07 PM] [semantic-release] › ✔  Created tag v2.7.2-0pipelinetest.1
17:16:07  [5:16:07 PM] [semantic-release] › ℹ  Start step "publish" of plugin "@semantic-release/npm"
17:16:07  [5:16:07 PM] [semantic-release] [@semantic-release/npm] › ℹ  Publishing version 2.7.2-0pipelinetest.1 to npm registry on dist-tag pipeline-test
17:16:08  
17:16:08  > @scope/package@2.7.2-0pipelinetest.1 prepublishOnly
17:16:08  > third-party-licenses -p
17:16:08  npm notice 
17:16:08  npm notice 📦  @scope/package@2.7.2-0pipelinetest.1
17:16:08  npm notice === Tarball Contents === 
17:16:08  npm notice 35B     __mocks__/fileMock.js                                         
17:16:08  npm notice 20B     __mocks__/styleMock.js                                        
17:16:08  npm notice 27B     .eslintignore                                                 
17:16:08  npm notice 358B    .eslintrc.js                                                  
17:16:08  npm notice 165B    .prettierrc.js                                                
17:16:08  npm notice 9.8kB   CHANGELOG.md                                                  
17:16:08  npm notice 5.1kB   Jenkinsfile                                                   
17:16:08  npm notice 292B    README.md                                                     
17:16:08  npm notice 507B    commitlint.config.js                                          
17:16:08  npm notice 3B      cypress.json                                                  
17:16:08  npm notice 154B    cypress/fixtures/example.json                                 
17:16:08  npm notice 356B    cypress/integration/e2e.spec.ts                               
17:16:08  npm notice 718B    cypress/plugins/index.js                                      
17:16:08  npm notice 838B    cypress/support/commands.js                                   
17:16:08  npm notice 670B    cypress/support/index.js                                      
17:16:08  npm notice 137B    cypress/tsconfig.json                                         
17:16:08  npm notice 1.1MB   dist/569.js                                                   
17:16:08  npm notice 857.4kB dist/693.js                                                   
17:16:08  npm notice 67B     dist/693.js.LICENSE.txt                                       
17:16:08  npm notice 294B    dist/906.js                                                   
17:16:08  npm notice 104.1kB dist/assets/OpenSans-Bold.ttf                                 
17:16:08  npm notice 96.9kB  dist/assets/OpenSans-Regular.ttf                              
17:16:08  npm notice 157.0kB dist/index.js                                                 
17:16:08  npm notice 788B    dist/index.js.LICENSE.txt                                     
17:16:08  npm notice 1.7kB   index.css                                                     
17:16:08  npm notice 3.9kB   index.css.map                                                 
17:16:08  npm notice 807B    jest.config.js                                                
17:16:08  npm notice 36B     jestImports.ts                                                
17:16:08  npm notice 319B    mfe.config.ts                                                 
17:16:08  npm notice 4.4kB   package.json                                                  
17:16:08  npm notice 682B    release.config.js                                             
17:16:08  npm notice 343B    sonar-project.properties                                      
17:16:08  npm notice 1.1kB   src/__tests__/App.test.tsx                                    
17:16:08  npm notice 349B    src/__tests__/index.local.test.tsx                            
17:16:08  npm notice 965B    src/App.tsx                                                   
17:16:08  npm notice 148B    src/assets/styles/index.css                                   
17:16:08  npm notice 98B     src/assets/styles/index.local.css                             
17:16:08  npm notice 175B    src/dependecies.ts                                            
17:16:08  npm notice 234B    src/index.html                                                
17:16:08  npm notice 502B    src/index.local.tsx                                           
17:16:08  npm notice 375B    src/index.ts                                                  
17:16:08  npm notice 1.2kB   src/mutation-observer.ts                                      
17:16:08  npm notice 764B    src/single-spa-bootstrap.ts                                   
17:16:08  npm notice 429B    tsconfig.json                                                 
17:16:08  npm notice 1.0kB   utils/generateSingleSpaEntryFile.ts                           
17:16:08  npm notice 354B    utils/getAssetPatterns.ts                                     
17:16:08  npm notice 390B    utils/getLicensesPattern.ts                                   
17:16:08  npm notice 148B    utils/prepare.ts                                              
17:16:08  npm notice 56B     utils/tsconfig.json                                           
17:16:08  npm notice 2.4kB   webpack.config.ts                                             
17:16:08  npm notice 105B    webpack.tsconfig.json                                         
17:16:08  npm notice === Tarball Details === 
17:16:08  npm notice name:          @scope/package                          
17:16:08  npm notice version:       2.7.2-0pipelinetest.1                                          
17:16:08  npm notice filename:      @scope/package-2.7.2-0pipelinetest.1.tgz
17:16:08  npm notice package size:  657.6 kB                                                       
17:16:08  npm notice unpacked size: 2.3 MB                                                         
17:16:08  npm notice shasum:        3c7ee82476b42842e60bb79035bd6cfd7fe4b154                       
17:16:08  npm notice integrity:     sha512-EFFXljDR+Gu1V[...]3AWALs4XDyQeg==                       
17:16:08  npm notice total files:   52                                                             
17:16:08  npm notice 
17:16:08  npm ERR! code ENEEDAUTH
17:16:08  npm ERR! need auth This command requires you to be logged in.
17:16:08  npm ERR! need auth You need to authorize this machine using `npm adduser`
17:16:08  
17:16:08  npm ERR! A complete log of this run can be found in:
17:16:08  npm ERR!     /home/buildmaster-agent/.npm/_logs/2021-10-01T15_16_08_639Z-debug.log
17:16:08  [5:16:08 PM] [semantic-release] › ✖  Failed step "publish" of plugin "@semantic-release/npm"
17:16:08  [5:16:08 PM] [semantic-release] › ✖  An error occurred while running semantic-release: Error: Command failed with exit code 1: npm publish /mnt/sdb1/buildmaster-agent/workspace/Front_End_a.m.m.o._pipeline-test --userconfig /mnt/sdb1/tmp/c8fafd3286e673fab580f41a4bc02bba/.npmrc --tag pipeline-test --registry https://artifactory.privatehost.com:8443/artifactory/api/npm/npm-local/

**Comment by gr2m** [comment]
I think others had similar problems in the past on Jenkins. Can you look through past issues? Can you make sure that `NPM_TOKEN` is indeed exposed in the build, by logging out the first few characters or similar, before running `semantic-release`? Can you run `semantic-release --debug` and share the logs?
