### ISSUE TITLE
Handling un-published version

### ISSUE THREAD

**Issue by Raathigesh** [semantic-release/semantic-release#219]
I pushed to npm with version 1.0.0 and then un-published it. Now npm does not allow to re-publish again with the same version but semantic-release is trying and failing. How to handle this ?

**Comment by tusharmath** [comment]
@Raathigesh Bottom line is —
> NEVER UNPUBLISH, use deprecate instead. 

But since you did, you should just delete the equivalent git tag `1.0.0` and then try again.

**Comment by Raathigesh** [comment]
> But since you already did, you should just delete the equivalent git tag 1.0.0 and then try again.

But the issue would be semantic-release will again determine the version as 1.0.0 but npm would not allow to publish again with the same version.

> Even if a package version is unpublished, that specific name and version combination can never be reused. - [Npm Docs](https://docs.npmjs.com/cli/unpublish)

Is there a workaround to this issue? May be publish the next version (v1.0.1) manually and then use semantic-release after that so it would determine the version correctly going forward ?

**Comment by tusharmath** [comment]
Oh yes! Sorry about that, you will also need to revert your npm dist-tag to the version just before your published `1.0.0`.

**Comment by Raathigesh** [comment]
Thanks for the info. Closing the issue.

**Comment by Moezalez** [comment]
This is not working for me. The tag is deleted, still can't republish

**Comment by tusharmath** [comment]
@Moezalez which tag are you talking about here — on npm or on git? You need to delete both.

**Comment by Moezalez** [comment]
@tusharmath all tags are deleted. Git and npm. Still can't publish over previously published packages. 

I think it might be related to this: 
http://blog.npmjs.org/post/77758351673/no-more-npm-publish-f

> If you publish foo@1.2.3, you can still un-publish foo@1.2.3. But then, you will not be able to publish something else to that same package identifier and version.

I really just want sermver to figure out that this version is not available anymore and use the next version, so basically `2.2.0` instead of `2.1.0`.

**Comment by tusharmath** [comment]
@Moezalez Yeah that's a nasty one. I have faced this issue too. You will have to make a FAKE `feat` commit to go to the next version.
