### ISSUE TITLE
What is the message format for a feature being removed?

### ISSUE THREAD

**Issue by gajus** [semantic-release/semantic-release#224]
I understand that the commit message footer must have the `BREAKING CHANGE` message. But what type ought to be used?, `feat`?

**Comment by tusharmath** [comment]
Perf.

On Mon, May 16, 2016, 8:04 PM Gajus Kuizinas <notifications@github.com>
wrote:

> I understand that the commit message footer must have the BREAKING CHANGE
> message. But what type ought to be used?, feat?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/semantic-release/semantic-release/issues/224>
>
-- 
Regards,
Tushar Mathur.
www.tusharm.com

**Comment by gajus** [comment]
What is the logic?

It has nothing to do with performance. We are removing one feature because it duplicates with lodash functionality (as an example).

**Comment by nephridium** [comment]
It depends on what kind of version bump the change warrants. Have a look at https://github.com/conventional-changelog/conventional-changelog-angular/blob/master/convention.md#type - `BREAKING CHANGES` (with any prefix), `feat`, `fix` or `perf` will be shown in the changelog and will bump major, minor, patch or no version number, respectively. (Or you can get the straight dope on what is handled from the source: https://github.com/semantic-release/commit-analyzer/blob/master/src/index.js)

If you're replacing an app function with a lodash function you could prefix `refactor` (or anything else you prefer) if it's not significant for the changelog or `fix`/`feat` if you want a version bump.

**Comment by pvdlg** [comment]
Closing as the question was answered by @nephridium.
