### ISSUE TITLE
More prefixes?

### ISSUE THREAD

**Issue by nephridium** [semantic-release/semantic-release#225]
What do you think about adding more prefixes, e.g. `major`, `minor`, `patch` for the explicit folks and `feature`, `bugfix` for people who like to write longer words ;) - If we cover most common wordings it might be easier for people to get into **semantic-release** without learning special keywords.

**Comment by hbetts** [comment]
@nephridium the prefixes used by `semantic-release` are encoded in `commit-analyzer`.

There is already a discussion there about extending the list of available commit types: https://github.com/semantic-release/commit-analyzer/issues/12

**Comment by elliotttf** [comment]
In case anyone else needs to support additional prefixes, I've written [a module](https://www.npmjs.com/package/semantic-release-conventional-commits) that duplicates the behavior of the commit analyzer that ships with semantic release but also allows configuring release behavior more granularly.

For the maintainers: I'm happy to work with you on including this functionality in commit-analyzer if there's interest – given semantic-release/commit-analyzer#11 and semantic-release/commit-analyzer#12 though it's not clear to me that this is actually desired for the project.

**Comment by benjamincharity** [comment]
I have successfully used https://github.com/leonardoanalista/cz-customizable to define custom scopes. It also has the ability to set custom scopes and override which scopes trigger version number changes. An example config:

```javascript
'use strict';

module.exports = {

  types: [
    {value: 'feat',     name: 'feat:     A new feature'},
    {value: 'fix',      name: 'fix:      A bug fix'},
    {value: 'docs',     name: 'docs:     Documentation only changes'},
    {value: 'style',    name: 'style:    Changes that do not affect the meaning of the code\n            (white-space, formatting, missing semi-colons, etc)'},
    {value: 'refactor', name: 'refactor: A code change that neither fixes a bug nor adds a feature'},
    {value: 'perf',     name: 'perf:     A code change that improves performance'},
    {value: 'test',     name: 'test:     Adding missing tests'},
    {value: 'chore',    name: 'chore:    Changes to the build process or auxiliary tools\n            and libraries such as documentation generation'},
    {value: 'revert',   name: 'revert:   Revert to a commit'},
    {value: 'WIP',      name: 'WIP:      Work in progress'}
  ],

  scopes: [
    {name: 'Button'},
    {name: 'Input'},
    {name: 'InputMessages'},
    {name: 'Search'},
    {name: 'SCSS'},
    {name: 'CI'},
    {name: 'Dependencies'},
    {name: 'Demo'},
  ],

  // it needs to match the value for field type. Eg.: 'fix'
  /*
  scopeOverrides: {
    fix: [
      {name: 'merge'},
      {name: 'style'},
      {name: 'e2eTest'},
      {name: 'unitTest'}
    ]
  },
  */

  allowCustomScopes: true,
  allowBreakingChanges: ['feat', 'fix']

};
```

**Comment by vanduynslagerp** [comment]
The commit analyzer and release generator plugins allow to select the  conventional-changelog preset to use and even allow to overwrite any properties.
See [commit-analyzer#release-rules](https://github.com/semantic-release/commit-analyzer#release-rules) and [release-notes-generator#parser-options](https://github.com/semantic-release/release-notes-generator#parser-options).

Feel free to re-open if it doesn't fit your needs
