### ISSUE TITLE
Fetching latest release from npm is error prone

### ISSUE THREAD

**Issue by leifg** [semantic-release/semantic-release#229]
I ran into the problem, that the version was always calculated wrong (pretty much returning major in all cases).

I found out that for some reasons some releases did not hava a gitHead attribute set on npm (in my case version 2.2.1 of https://registry.npmjs.org/formulon).

It then fell back to a way earlier version all the time.

As a workaround I used the module [last-release-git-tag](https://github.com/semantic-release/last-release-git-tag) to fetch the latest version.

**Comment by davemachado** [comment]
Clean install of sementic-release throws deprecated errors, could be similar to this issue. Thoughts?

**Comment by motiz88** [comment]
Related issue: #256. There's another workaround in https://github.com/semantic-release/semantic-release/issues/256#issuecomment-239678516, plus a reference to the `npm` bug that's causing this.
