### ISSUE TITLE
This test run was triggered on the branch origin/dev

### ISSUE THREAD

**Issue by JooperGe** [semantic-release/semantic-release#2291]
`This test run was triggered on the branch origin/dev, while semantic-release is configured to only publish from master, dev, therefore a new version won’t be published.`

I got this when my Jenkins was triggered by a push on dev, but semantic-release runs fine on my mac locally, any ideas how to fix this?

**Comment by JooperGe** [comment]
@ashwin-netomi 
do you have a dev branch on your remote git repo?


by the way, this is my configure:
    "@semantic-release/git": "^10.0.1",
    "semantic-release": "^18.0.0",

**Comment by ashwin-netomi** [comment]
@JooperGe
This is the error message. and yes I do have my remote git repo
  This test run was triggered on the branch origin/develop-clone, while semantic-release is configured to only publish from develop-clone, therefore a new version won’t be published.

Running semantic-release version 18.0.1 and ^19.0.0.

**Comment by JooperGe** [comment]
@ashwin-netomi 
I solved this by pushing my local ‘dev’ branch to the remote repo, nothing else.
:satisfied:

**Comment by mkermani144** [comment]
This was the solution for me:
https://github.com/semantic-release/semantic-release/issues/2322#issuecomment-1069398964
