### ISSUE TITLE
Semantic Release dep `marked` has a high vulnerability in the version Semantic uses.

### ISSUE THREAD

**Issue by tyler-dunkel** [semantic-release/semantic-release#2334]
## Current behavior

![image](https://user-images.githubusercontent.com/7192733/150041617-4c92eeea-ee79-426a-b5d3-1e0770a97e59.png)

## Expected behavior

No vulnerabilities reported through semantic release deps

## Environment

- **semantic-release** version: `17.4.4`

**Comment by travi** [comment]
Please upgrade to the latest release
