### ISSUE TITLE
Can I use it on a closed project not published on npm?

### ISSUE THREAD

**Issue by willgm** [semantic-release/semantic-release#234]
I would like to use this project to have a decent and automatic change log with semver, but in a closed project not published on `npm`. Is it possible?

**Comment by finom** [comment]
I just made [a plugin for it](https://github.com/finom/last-release-git).

**Comment by pvdlg** [comment]
Yes this is now a supported workflow with [git](https://github.com/semantic-release/git) and [npm](https://github.com/semantic-release/npm) plugins.
You can check the doc in those repo for more details.
