### ISSUE TITLE
Impossible to debug/run semantic-release in CI runner

### ISSUE THREAD

**Issue by y-nk** [semantic-release/semantic-release#2340]
## Current behavior

I'm having issues regarding authentication of my runner (semantic-release:get-git-auth-url) part.

When trying locally, even with `--no-ci --dry-run` i can read from the log that there's a 1st try in ssh, which succeeds because my workstation has my own ssh keys.

That said, there's no ssh keys in my CI runner, so the debug log is quite different. I've a failed attempt at ssh try (which sounds correct), and after that the fallback to https also fails for some reason.

The error mentioned is `An error occurred while running semantic-release: Error: Command failed with exit code 128: git ls-remote --heads https://x-access-token:[secure]@github.com/[org]/[repo]` for which i've tried both the token provided by Github Actions (as seen in the [semantic-release release workflow](https://github.com/semantic-release/semantic-release/blob/2c30e268f9484adeb2b9d0bdf52c1cd909779d64/.github/workflows/release.yml#L22) as well as [the CI recipes](https://github.com/semantic-release/semantic-release/blob/master/docs/recipes/ci-configurations/github-actions.md)) **and** a Github Personal Access Token (stored in secrets, called `secrets.GH_PAT`). 

## Expected behavior

I guess, working or at least debuggable 🤷‍♂️ 

## Environment

- CI environment: Github Actions
- **semantic-release** version: 19.0.2
- **semantic-release** configuration: 
```
module.exports = {
  branches: ['develop'],
  plugins: [
    '@semantic-release/commit-analyzer',
    '@semantic-release/release-notes-generator',
    ['@semantic-release/npm', { npmPublish: false }],
    '@semantic-release/changelog',
    ['@semantic-release/git', {
      assets: ['package.json', 'CHANGELOG.md'],
    }],
  ],
};
```

**Comment by y-nk** [comment]
Looking at source, i also found that `GH_TOKEN` has priority over `GITHUB_TOKEN` and does not set the username to be `x-access-token` which means that, in a github action.

https://github.com/semantic-release/semantic-release/blob/2c30e268f9484adeb2b9d0bdf52c1cd909779d64/lib/get-git-auth-url.js#L64-L67

Is it supposed to be that way?

|---|---|---|
| env var name | token value used | computed url |
|---|---|---|
| GH_TOKEN | Action Token | https://{token}@github.com |
| GH_TOKEN | Personal Token | https://{token}@github.com |
| GITHUB_TOKEN | Action Token | https://x-access-token:{token}@github.com |
| GITHUB_TOKEN | Personal Token | https://x-access-token:{token}@github.com |

This matrix sounds reasonably correct, although the comment...

[```
GitHub Actions require the "x-access-token:" prefix for git access
```](https://github.com/semantic-release/semantic-release/blob/2c30e268f9484adeb2b9d0bdf52c1cd909779d64/lib/get-git-auth-url.js#L65)

...seems to suggest that having an env var such as `GH_TOKEN` would end up failing in the CI runner (only).

**Comment by y-nk** [comment]
I've found a way to print the `${{ secrets.GITHUB_TOKEN }}` and started brute force debugging. I've been using the super convenient [tmate action](https://github.com/marketplace/actions/debugging-with-tmate) to get a terminal in my runner in no time.

**The following is debugged directly by ssh'ing inside the runner** :

| env var name | token value used | computed url | login in runner successful? | login in workstation successfull?
|---|---|---|---|---|
| GH_TOKEN | Action Token | https://{token}@github.com | ❌ | ❌ |
| GH_TOKEN | Personal Token | https://{token}@github.com | ❌ | 🟢 |
| GITHUB_TOKEN | Action Token | https://x-access-token:{token}@github.com | ❌ | ❌ |
| GITHUB_TOKEN | Personal Token | https://x-access-token:{token}@github.com | ❌ | 🟢 |

From this testing, it appears that :

- `GITHUB_TOKEN` never works → i would have expected the login to work, at least, even though my repo is private and the main branch is protected. The error given by GitHub is `remote: Invalid username or password.` so that's pretty clear.

- `GH_PAT` works only in my workstation. This is where i'm loosing it, because i'm running _exactly_ the same command from the same git repo. At this point the only difference is that my runner runs a `ubuntu-latest` and my workstation runs macOS.

<details>
<summary>Runner logs</summary>

```
$ GH_TOKEN=ghs_{{ secrets.GITHUB_TOKEN }} npm run release -- --debug

semantic-release:get-git-auth-url SSH key auth failed, falling back to https. +2s
[4:50:49 AM] [semantic-release] › ✖  An error occurred while running semantic-release: Error: Command failed with exit code 128: git ls-remote --heads https://[secure]@github.com/[org]/[repo].git
remote: Invalid username or password.
```

```
$ GH_TOKEN=ghp_{{ secrets.GH_PAT }} npm run release -- --debug

semantic-release:get-git-auth-url SSH key auth failed, falling back to https. +2s
[4:52:28 AM] [semantic-release] › ✖  An error occurred while running semantic-release: Error: Command failed with exit code 128: git ls-remote --heads https://[secure]@github.com/[org]/[repo].git
remote: Invalid username or password.
```

```
$ GITHUB_TOKEN=ghs_{{ secrets.GITHUB_TOKEN }} npm run release -- --debug

semantic-release:get-git-auth-url SSH key auth failed, falling back to https. +2s
[4:54:39 AM] [semantic-release] › ✖  An error occurred while running semantic-release: Error: Command failed with exit code 128: git ls-remote --heads https://x-access-token:[secure]@github.com/[org]/[repo].git
remote: Invalid username or password.
```

```
$ GITHUB_TOKEN=ghp_{{ secrets.GH_PAT }} npm run release -- --debug

semantic-release:get-git-auth-url SSH key auth failed, falling back to https. +2s
[4:56:12 AM] [semantic-release] › ✖  An error occurred while running semantic-release: Error: Command failed with exit code 128: git ls-remote --heads https://x-access-token:[secure]@github.com/[org]/[repo].git
remote: Invalid username or password.
```

</details>

<details>
<summary>Workstation logs</summary>

```
$ GH_TOKEN=ghs_{{ secrets.GITHUB_TOKEN }} npm run release -- --debug --no-ci --dry-run

semantic-release:get-git-auth-url SSH key auth failed, falling back to https. +2s
[12:05:08 PM] [semantic-release] › ✖  An error occurred while running semantic-release: Error: Command failed with exit code 128: git ls-remote --heads https://[secure]@github.com/[org]/[repo].git
remote: Support for password authentication was removed on August 13, 2021. Please use a personal access token instead.
```

```
$ GH_TOKEN=ghp_{{ secrets.GH_PAT }} npm run release -- --debug --no-ci --dry-run

semantic-release:get-git-auth-url SSH key auth failed, falling back to https. +3s
semantic-release:get-tags found tags for branch develop
```

```
$ GITHUB_TOKEN=ghs_{{ secrets.GITHUB_TOKEN }} npm run release -- --debug --no-ci --dry-run

semantic-release:get-git-auth-url SSH key auth failed, falling back to https. +2s
[12:09:33 PM] [semantic-release] › ✖  An error occurred while running semantic-release: Error: Command failed with exit code 128: git ls-remote --heads https://[secure]@github.com/[org]/[repo].git
remote: Support for password authentication was removed on August 13, 2021. Please use a personal access token instead.
```

```
$ GITHUB_TOKEN=ghp_{{ secrets.GH_PAT }} npm run release -- --debug --no-ci --dry-run

semantic-release:get-git-auth-url SSH key auth failed, falling back to https. +3s
semantic-release:get-tags found tags for branch develop
```

</details>

**Comment by y-nk** [comment]
Since none of the `GITHUB_TOKEN` thing were working, i decided to focus on `GH_TOKEN` and a `GH_PAT`. With further debug I've narrowed it down to this:

I've added a console.log in `index.js` to verify that the repositoryUrl was properly computed:

```
options.repositoryUrl = await getGitAuthUrl({...context, branch: {name: ciBranch}});
console.log('resolved repository url', options.repositoryUrl.split('').join(' '));
```

From there i could see that the very next command was the one failing, with an error thrown:

```
[5:32:12 AM] [semantic-release] › ✖  An error occurred while running semantic-release: Error: Command failed with exit code 128: git ls-remote --heads https://[secure]@github.com/[org]/[repo].git
remote: Invalid username or password.
```

Looking closer at the log, i should have known because the stack trace mentions:

```
at makeError (/home/runner/work/repo/node_modules/semantic-release/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/home/runner/work/repo/node_modules/semantic-release/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async getBranches (/home/runner/work/repo/node_modules/semantic-release/lib/git.js:66:11)
```

So it's clear that the failure comes from:

https://github.com/semantic-release/semantic-release/blob/2c30e268f9484adeb2b9d0bdf52c1cd909779d64/lib/git.js#L66

which means it's a git related issue.

Workstation: `git version 2.30.1 (Apple Git-130)`
Runner: `git version 2.34.1`

Trying to execute the command directly:

```
runner@fv-az144-561:~/work/repo$ git ls-remote --heads https://[secure]@github.com/EkoCommunications/AmityConsole.git
Password for 'https://[secure]@github.com':
```

...which isn't sound at all. I tried few combinations, and none worked so far.

**Comment by y-nk** [comment]
Hopefully there's a `git@2.34.1` on brew, and running the command with the same version works 🤯 

```
/u/l/C/g/2/bin ❯❯❯ ./git --version
git version 2.34.1
/u/l/C/g/2/bin ❯❯❯ ./git ls-remote --heads https://[secure]@github.com/[org]/[repo].git
a1b2c3d4	refs/heads/develop
```

Since Github actions runner also have `gh` installed, I tried the other way around:

```
runner@fv-az144-561:~/work/repo$ gh auth login
? What account do you want to log into? GitHub.com
? What is your preferred protocol for Git operations? HTTPS
? Authenticate Git with your GitHub credentials? No
? How would you like to authenticate GitHub CLI? Paste an authentication token
Tip: you can generate a Personal Access Token here https://github.com/settings/tokens
The minimum required scopes are 'repo', 'read:org'.
? Paste your authentication token: ****************************************
- gh config set -h github.com git_protocol https
✓ Configured git protocol
✓ Logged in as y-nk
```

...and subsequent commands using the given token are working fine.

**Comment by y-nk** [comment]
```
persist-credentials: false
```

f*** me. I think it'd be beneficial to really explain in details what are the consequences in the docs.

**Comment by gr2m** [comment]
> it'd be beneficial to really explain in details what are the consequences in the docs

PRs welcome
