### ISSUE TITLE
Allow missing release branches if a prerelease branch exists

### ISSUE THREAD

**Issue by oprypkhantc** [semantic-release/semantic-release#2345]
## Current behavior

If there's no stable branch in the repository, it throws, even a prerelease branch exists and is properly configured:
```
[10:01:29 AM] [semantic-release] › ✖  An error occurred while running semantic-release: TypeError: Cannot read property 'name' of undefined
    at module.exports (/action/node_modules/@semantic-release/github/lib/get-fail-comment.js:19:10)
    at module.exports (/action/node_modules/@semantic-release/github/lib/fail.js:28:74)
    at async fail (/action/node_modules/@semantic-release/github/index.js:64:3)
    at async validator (/action/node_modules/semantic-release/lib/plugins/normalize.js:34:24)
    at async /action/node_modules/semantic-release/lib/plugins/pipeline.js:37:34
    at async /action/node_modules/semantic-release/lib/plugins/pipeline.js:31:3
    at async Object.pluginsConf.<computed> [as fail] (/action/node_modules/semantic-release/lib/plugins/index.js:80:11)
    at async callFail (/action/node_modules/semantic-release/index.js:235:7)
    at async module.exports (/action/node_modules/semantic-release/index.js:264:7)
    at async run (/action/entrypoint.js:57:18) {
  pluginName: '@semantic-release/github'
}
```

## Expected behavior

If there's no stable branch in the repository but a prerelease branch exists, create a prerelease.

## Environment

- **semantic-release** version: 17.4.0 (unchanged in latest)
- CI environment: GH Actions
- Plugins used: ['@semantic-release/commit-analyzer', '@semantic-release/release-notes-generator', '@semantic-release/changelog', '@semantic-release/git', '@semantic-release/github']
- **semantic-release** configuration: default
- CI logs:

**Comment by travi** [comment]
i dont think this is a use case that we would want to support. pre-releases are intended to be branches created from an existing mainline for getting feedback on unstable progress, with the intention of merging back into the mainline once stabilized for promotion. supporting an orphan pre-release branch would enable a workflow that is not intended to be supported.

i would be supportive of a more descriptive error or documentation updates to clarify, though.

**Comment by oprypkhantc** [comment]
@travi

I initially created the issue & implemented the change thinking that creating a `master` branch would result in the first release getting created. That's not the case, sorry about that.

Although a smaller issue still exists:

 - a repository is created from a template
 - first few commits get pushed/merged. I don't think it's reasonable/safe to assume those are stable, hence shouldn't result in a stable version (1.0.0) getting published. That's why I name the default (and only) branch in the template as `alpha` - so that unless the developer explicitly creates the `master` branch, no stable release is going to get published
 - few more commits get pushed/merged, possibly into a `beta` branch
 - after some time `master` branch is manually created and pushed, resulting in a stable 1.0.0 release

Of course I can create one more branch in the template - `master`. That's exactly what I did (now knowing it doesn't result in a stable release published right away). However that's still not perfect as it might confuse the developers who are used to `master` being the main (or default) branch, and they might end up pushing/merging into `master` instead of `alpha`. This is especially relevant given the fact there's no such thing as the default branch in git itself, so no visual indication for the developers whatsoever.

I admit this is a much smaller issue than I initially thought, although I think still worth addressing, especially given the low fix cost.

**Comment by travi** [comment]
it is not the responsibility of semantic-release to protect your team from not understanding your own release process. if you have chosen to use semantic-release for coordination of your releases, it is your team's responsibility to understand how to use it properly. semantic-release simply works on top of your git workflow and executes the history of the branch. how you interact with git to manage your branches is up to your use of git itself and other tools, like your hosting service. if you want to prevent direct pushes to your mainline branch on github, for example, you can define branch protection.

> especially given the low fix cost.

the checks that are built into semantic-release are intended to encourage the intended use of the tool and ideally guide users back toward the intended use when straying away from it. removing a check because of the desire to enable an unsupported use case takes us further from that goal, not closer to it.

**Comment by oprypkhantc** [comment]
> it is not the responsibility of semantic-release to protect your team from not understanding your own release process.

I mean.. this tool is made for developers, and developers are people who make mistakes. It's the main reason strictly typed languages and say.. branch protection rules even exist. To prevent people from making mistakes where possible.

> the checks that are built into semantic-release are intended to encourage the intended use of the tool and ideally guide users back toward the intended use when straying away from it. removing a check because of the desire to enable an unsupported use case takes us further from that goal, not closer to it.

You're contradicting yourself. First you say that the developers should know how to use the tool and it's their problem if they don't, then you say you ideally want to guide users and encourage the intended  use (by literally forcing it).

Regardless, thanks. We'll live with that.
