### ISSUE TITLE
[Feature Request] split release steps

### ISSUE THREAD

**Issue by gotson** [semantic-release/semantic-release#2349]
Hi,

i'd like to know if it's possible to run only some [steps](https://github.com/semantic-release/semantic-release#release-steps) when running `semantic-release` ?

Let me clarify with an example:
- If a release happens, i need to build specific artifacts for specific OSes. Those would run in different jobs in Github Action, using a different OS.
- I don't want to build those artifacts all the time, only when a release happens, so i need to have `semantic-release` ran before to make sure a release would happen.
- I need the new version number for those jobs also, as this is required in the packaging.
- The packaging is done on specific OS, but not the actual release.

I would need to be able to run something like that:
```
                                     ┌───────────────┐
                                     │ package win   ├───────────────┐
                                     └─▲─────────────┘               │
                                       │                             │
┌────────┐     ┌─────────────────┬─────┘                           ┌─▼──────────────┐
│        │     │                 │        ┌───────────────┐        │                │
│  test  ├────►│ release prepare ├────────►package linux  ├────────► release publish│
│        │     │                 │        └───────────────┘        │                │
└────────┘     └─────────────────┴─────┐                           └─▲──────────────┘
                                       │                             │
                                     ┌─▼────────────┐                │
                                     │package macos ├────────────────┘
                                     └──────────────┘
```

Is it possible to run only specific steps of the release flow, cache the previous steps state, and execute the last steps afterwards ?

_Originally posted by @gotson in https://github.com/semantic-release/semantic-release/discussions/2331_

**Comment by seebeen** [comment]
Hello, I saw that you closed this issue. Did you solve the problem you were having?

**Comment by gotson** [comment]
> Hello, I saw that you closed this issue. Did you solve the problem you were having?

yeah, i stopped using this tool which tries to do everything but is inflexible :D

I am using jReleaser now.
