### ISSUE TITLE
🎁 Thank you 💟 

### ISSUE THREAD

**Issue by adriens** [semantic-release/semantic-release#2356]
# 👉 Wait What ? 😸 

Just a fun ticket to thank you for your work and documentation. We are now using your project on a daily basis, and we wanted to share some content with you.

# 🎁 Gifts

- 🐦 [Dedicated Tweet](https://twitter.com/rastadidi/status/1491285171785854978)
- 🎥 [Video demo](https://youtu.be/Er-W5J5ky7Q)
- 🔖  [linkedIn post](https://www.linkedin.com/posts/adrien-sales_releaser-mieux-avec-les-commits-conventionels-activity-6897052945259610112-8fBA)

Thanks again for the great tool.

Kind regards,
Adrien

**Comment by gr2m** [comment]
Merci beaucoup 😃

**Comment by adriens** [comment]
[Article DEV.to écrit par le lead dev de semantic-release](https://dev.to/gr2m/automate-npm-releases-using-semantic-release-510c)
