### ISSUE TITLE
[feature request] Filter commit by path

### ISSUE THREAD

**Issue by bogaertg** [semantic-release/semantic-release#2377]
### Discussed in https://github.com/semantic-release/semantic-release/discussions/2316

<div type='discussions-op-text'>

<sup>Originally posted by **bogaertg** January  4, 2022</sup>
Hello,

I made a pull request to add the possibility to filter commit by path
Does someone can review my [pull request](https://github.com/semantic-release/semantic-release/pull/2315) ?</div>

**Comment by travi** [comment]
> But please do not double ping us. We get to it when we get to it.
