### ISSUE TITLE
Release picks wrong version when several previous (pre)releases share same HEAD

### ISSUE THREAD

**Issue by Tlepel** [semantic-release/semantic-release#2415]
### Discussed in https://github.com/semantic-release/semantic-release/discussions/2414

<div type='discussions-op-text'>

<sup>Originally posted by **Tlepel** April 12, 2022</sup>
Hi everyone!

In my project there are 3 branches: `production`, `development` and `beta`. We've only recently started releasing on the alpha branch, in addition to the releases on the beta and production branches where we've been releasing for a few years now.

We've released a version to the alpha branch, let's say `v2.2.0-development.3`, which worked perfectly fine. However, when all seemed well we merged the alpha branch to beta and tried to release there. We don't use merge commits for this, so the `v2.2.0-beta.1` tag was created on the same commit as the `v2.2.0-development.3` tag. Now we've pushed a few commits to the beta branch that fixed some issues on that branch, and tried to release that. However, the tag that was generated was `v2.2.0-development.4` instead of `v2.2.0-beta.2`..

I checked the git notes to see if it went wrong there, and I tried to adapt it to reflect the situation, but that didn't change the version at all; none of these options worked:

```
{"channels": ["development","beta"]}
{"channels": ["beta"]}
{"channels": ["development"]}
```

### Schematic:

```
|
* - v2.2.0-development.1
|
* - v2.2.0-development.2
|
* - v2.2.0-development.3, v2.2.0-beta.1
| \
*  \   - v2.2.0-development.4 (on development branch)
|   |
|   *  - v2.2.0-development.4 (on beta branch, should be v.2.2.0-beta.2)
```

### Setup:

```js
branches: [
  'production',
  {
    name: 'beta',
    prerelease: true,
  },
  {
    name: 'development',
    prerelease: true,
  },
],
```

Can anyone help me out and see what we're doing wrong here?</div>

It seems like the current implementation doesn't account for multiple tags/versions using the same git-commit.

**Comment by codezomb** [comment]
Any update here? We're seeing the same thing. Release branches of stable, beta, and alpha. Alpha is released first and the git notes show the proper channel. When alpha `1.3.0-alpha.9` is promoted to beta (using `git push alpha:beta`) a new release is created for beta (`1.3.0-beta.1`), and the git notes show are updated to the beta channel. The next alpha release tries to create the previous version (`1.3.0-alpha.9`, which already exists) and ultimately fails.

**Comment by Tlepel** [comment]
I wrote a fix for this issue in #2416, but it's still waiting for approval before it can be merged.. I think the maintainers are mainly focusing on other projects so it might take a while before this gets to a release.

**Comment by Ga13Ou** [comment]
Any news about this issue?

**Comment by frnode** [comment]
I have same issue... Anyone if we can work around the problem temporarily?
thank you
