### ISSUE TITLE
upgrade dependency find-versions

### ISSUE THREAD

**Issue by ITler** [semantic-release/semantic-release#2424]
The current release of semantic-release (19.0.2) uses `find-versions` 4.x as a dependency. This library is indicated by github's dependabot to have security vulnerabilities originating in the required `semver-regex` library, which has version 3.1.2.

Could you please consider updating to `find-versions` 5.x which currently uses a good `semver-regex` version (4+)

**Comment by travi** [comment]
this has been resolved by https://github.com/semantic-release/semantic-release/releases/tag/v20.0.0
