### ISSUE TITLE
Don't publish for private packages?

### ISSUE THREAD

**Issue by jpnelson** [semantic-release/semantic-release#244]
For https://github.com/atlassian/lerna-semantic-release, there'd be a use case where we don't want to publish private packages. Is this behaviour that would be accepted in a PR?

If not, we'll just build it in lerna-semantic-release

**Comment by metasean** [comment]
Related to #234

**Comment by aberonni** [comment]
+1 I see there is a hotfix in #215 but I haven't looked into it
