### ISSUE TITLE
Semantic-Release does not pick up existing tags after repo migration

### ISSUE THREAD

**Issue by xenon-dev** [semantic-release/semantic-release#2501]
### Current behavior

We migrated a project-repo from gitlab.com to a self-hosted GitLab Community Edition.
GitLab CI for versioning worked flawlessly and we created 17 tags succesfully.
Existing tags (all were lightweight tags, not annotated ones), were also migrated, new sha's were automatically assigned and the relationship between tags and their relating commits seems fine. All tags are in the branch we are interested in at the moment (staging). ArgoWorkflows takes over the missing CI part vom GitLab now.

"previousTag" is "null"

additional information:
- also new, manually created tags in new repo were not picked up
- we do not use channels as of yet
- we do not use annotated tags as of yet (we write the changelogs to a changelog.md file)
- locally executing semantic-release without a pipeline works for old repo (gitlab.com)
- locally executing semantic-release without a pipeline works for new repo (gitlabCE)
- we "fixed" the issue by just deleting the existing tags as the application has not reached production grade as of yet
- we searched all the issues we could find, neither downgrading until v15.0.0, nor cloning differently fixed the issue
- git depth 1 was the standard, but also "0" or "1200" yielded no working results
- we think that either the way gitLab creates the tags after migration or the newly generated sha's are the root cause

### Expected behavior

- Existing tags within the branch should be A. found and B. used to generate a new version according to semantic-versioning rules

- "previousTag" should be "v1.0.0-staging.17"
- no new version tag with a version smaller than the newest should be created (wanted: "v1.0.0-staging.18", not "v1.0.0-staging.1"

-  No error messages should come up mentioning an already existing tag, which then can not be written

### `semantic-release` version

v19.0.3

### CI environment

Argo CD (--no-ci)

### Plugins used

@semantic-release/exec
@semantic-release/git
@semantic-release/gitlab
@semantic-release/changelog

and of course the default ones, like the "analyzer"

### `semantic-release` configuration

    Installation and execution:
   ```
  npm install  @semantic-release/exec @semantic-release/git @semantic-release/gitlab @semantic-release/changelog
 && npx semantic-release  --no-ci --extends ./release_staging.config.json
```

```
$cat release_staging.config.json

{
  "plugins": [
    "@semantic-release/commit-analyzer",
    [
        "@semantic-release/exec",
        {
            "analyzeCommitsCmd":  "echo ${lastRelease.version} > version"
        }
    ],
    "@semantic-release/release-notes-generator",
    [
      "@semantic-release/changelog",
      {
        "changelogFile": "./public/staging/CHANGELOG.md"
      }
    ],
    [
      "@semantic-release/exec",
      {
         "verifyReleaseCmd": "echo ${nextRelease.version} > version"
      }
    ],
    [
      "@semantic-release/git",
      {
        "assets": ["./public/staging/CHANGELOG.md"],
        "message": "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
      }
    ]
  ],
  "branches":[
      "main",
      {
          "name": "dev",
          "prerelease": "dev"
      },
      {
          "name": "staging",
          "prerelease": "staging"
      }
  ],
  "repositoryUrl": "git@gitlab.com:lgln/team3d/agisoft-metashape-containerized.git"
}
```

### CI logs

[pipe-amc-9jntz-init-1728027208.log](https://github.com/semantic-release/semantic-release/files/9061305/pipe-amc-9jntz-init-1728027208.log)

Relevant lines:
[15:25:17] [semantic-release] » i  No git tag version found on branch staging
[15:25:17] [semantic-release] » i  No previous release found, retrieving all commits
[15:25:17] [semantic-release] » i  Found 1068 commits since last release

![image (14)](https://user-images.githubusercontent.com/84480131/177708797-96f8ccf3-93a4-4b4b-9b2d-6e295bcbd04d.png)
![image (13)](https://user-images.githubusercontent.com/84480131/177708809-64d0df05-f913-4210-9593-cc9248f5ff13.png)

Checking existing tags in branch "staging", annotated "tag" tag .18 just for testing purposes and .19 as a standard, manual lightweight tag.

**Comment by travi** [comment]
semantic-release uses information from both tags and notes. you likely need to follow https://semantic-release.gitbook.io/semantic-release/support/troubleshooting#release-not-found-release-branch-after-git-push-force

**Comment by xenon-dev** [comment]
Mh the troubleshooting guide says:
`After a git history rewrite due to a git push --force, the git tags and notes referencing the commits that were rewritten are lost.`

(Because we are not using notes in any way as of yet, I will ignore that part)

We used the UI job from GitLab CE to import a project which was exported beforehand (by another gitLab instance). I can not imagine, that gitLab uses "git push --force" internally to push into a newly created project, there would be just no reason to do that, would it?

And if we see the tags inside the branches and the all have a corresponding commit sha which definately exists, are we not in the clear? What I can not really understand by the approach to let the existing tags point to the commits again manually, is that, where is the difference to what gitLab already has done automatically?

Could this be automated in anyway without us having to write some sort of shell-script that goes through every possible existing tag and do the force push at the end (which we even can not do, because the stage does not allow a force push, just merge request workflow).

And why is the analyzer plugin finding all the tags, but the next plugin in the chain is not?

Please clarify a bit more, right now, I can not seem to get my head around the proposed fix.

**Comment by BitFis** [comment]
@xenon-dev I ran into a similar issue, and found that semantic-releases uses notes. It creates a note for every version.
**But only prereleases require notes**. Releasing / tagging versions without `prerelease: true` works without notes.

example:
after a v2.0.0-beta.1 release the notes look as following:
```bash
$ git notes --ref semantic-release show v2.0.0-beta.1
{"channels":["beta"]}
```
you can updated / add those notes to also support the unset channel as following:
```bash
$ git notes --ref semantic-release add -f -m '{"channels":["beta", null]}' v2.0.0-beta.1
Overwriting existing notes for object df9e2ca6fd1b8be8c72691fada8167ff30826e38
```
and then for CICD / aka. push it to the repo, update the remote semantic-releases notes:
```bash
$ git push origin refs/notes/semantic-release
...
```

**Comment by xenon-dev** [comment]
I see, that makes it a lot clearer, not we are the ones that could or could not be using notes, but semantic-release itself to track where the tags belongs to. Still do not get why it is not enough that the tag is reachable through the branch, but the way to update this is a lot clearer.

So long story short: While migrating tags and commits are copied over, but notes are not. Seems to me like an gitLab Issue, not the fault of semantic-release, it is just the victim of this missing information. Thanks for clarification, after reading through the troubleshooting guide I got it.
