### ISSUE TITLE
Use external data sources for commit type

### ISSUE THREAD

**Issue by vincent-herlemont** [semantic-release/semantic-release#2515]
### New plugin motivation

Currently, we can only [customize](https://github.com/semantic-release/commit-analyzer#options) the parsing of the commits in order to change the update commit type.
It could be interesting to use external data sources to provide the commit type, like the issues label for GitLab/GitHub.

### Third-party documentation

The plugin allows overriding of the function of commit analyzing which takes into an argument the context (commit name, branch name etc.) and must return the [commit type](https://github.com/angular/angular/blob/main/CONTRIBUTING.md#type) ) `feat`, `fix`, etc.) with the breaking change boolean.

**Comment by travi** [comment]
semantic-release acts specifically on commits and knows nothing about the vcs host or even the concept of PRs (other than the commits that result from accepting them into the release branch) at the point of evaluating the changes. this is a core behavior that we currently have no intention to make available to plugins. 

i can understand the desire, but accomplishing such behavior would be outside the scope of semantic-release. one way that something along these lines could be accomplished might be to automate updating the PR title on github based on the external information you are referring to. then when the PR is merged, that PR title is suggested as the subject of the squash commit that would be evaluated by semantic-release.
