### ISSUE TITLE
npm publish failing on travis

### ISSUE THREAD

**Issue by ColinEberhardt** [semantic-release/semantic-release#253]
Apologies for the vague issue, but I've been scratching my head for a while, but am at a loss. I've used semantic-release in the past, with success, but just cannot get it set up this time!

The repo is here:

https://github.com/ColinEberhardt/json-transformer

Setup successfully via the CLI:

```
$ semantic-release-cli setup
? Is the GitHub repository private? No
? What is your npm registry? https://registry.npmjs.org/
? What is your npm username? colineberhardt
? What is your npm email? ceberhardt@scottlogic.com
? What is your npm password? ***********
? What is your GitHub username? colineberhardt
? What is your GitHub password? ********
? What CI are you using? Travis CI
? What kind of `.travis.yml` do you want? Single Node.js version.
```

But when npm publish runs via travis, it fails:

```
npm ERR! publish Failed PUT 403
npm ERR! Linux 3.13.0-40-generic
npm ERR! argv "/home/travis/.nvm/versions/node/v4.4.7/bin/node" "/home/travis/.nvm/versions/node/v4.4.7/bin/npm" "publish"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.9
npm ERR! code E403
npm ERR! you do not have permission to publish "json-transformer". Are you logged in as the correct user? : json-transformer
npm ERR! 
```

(https://s3.amazonaws.com/archive.travis-ci.org/jobs/142453036/log.txt)

I'm sure my credentials are correct. Any ideas how I can debug this further?

**Comment by ColinEberhardt** [comment]
Aaarrghh ... so the name I was publishing to was already taken. The `Are you logged in as the correct user?` message is really misleading.

**Comment by DianaSuvorova** [comment]
I am glad I found this. The error message is a bit confusing indeed. Although I understand that correctly detecting the cause might be a bit challenging. But adding it as a suggestion  `Are you logged in as the correct user or are you the owner of the npm package` would save me a bit time.

In addition to that I was only able to see this error msg if running Travis on node v8. Any version below 8 gives no readable error but rather `ELIFECYCLE code`. This might be completely different issue.

**Comment by vanduynslagerp** [comment]
`you do not have permission to publish "json-transformer". Are you logged in as the correct user? : json-transformer` is an `npm` message. It comes from `npm publish`, so there is no much we can do in `semantic-release`.

But we are planning to improve log messages: #438

`semantic-release` now require Node 8. All release task will be skipped if the Travis job run on a version lower than 8. So you need to have at least one Travis job running Node 8.

Your feedback is much appreciated. We'll keep your comment in mind to improve logs and documentation.

**Comment by DianaSuvorova** [comment]
@vanduynslagerp , that makes sense.
As for node version 8 requirements - this makes sense as well. The problem I see with that is that `.travis.yml` generated by `semantic-release-cli setup` the default list of node version does not include 8. So it took me sometime to figure out what's going on. 

```language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '7'
  - '6'
  - '4'
before_script:
  - npm prune
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
```

**Comment by vanduynslagerp** [comment]
Yes indeed. We've open an issue for that: semantic-release/cli#126 :)
