### ISSUE TITLE
yargs update in semantic-release 19.0.4 is broken

### ISSUE THREAD

**Issue by mscharley** [semantic-release/semantic-release#2533]
### Current behavior

Semantic release crashes without parsing arguments correctly.

### Expected behavior

Run a release.

### `semantic-release` version

19.0.4

### CI environment

CircleCI

### `semantic-release` configuration

```json
{
  "branches": ["main"],
  "plugins": [
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    "@semantic-release/npm",
    "@semantic-release/github"
  ]
}
```

### CI logs

```
$ semantic-release

Run automated package publishing

Usage:
semantic-release [options] [plugins]

Options
  -b, --branches        Git branches to release from                     [array]
  -r, --repository-url  Git repository URL                              [string]
  -t, --tag-format      Git tag format                                  [string]
  -p, --plugins         Plugins                                          [array]
  -e, --extends         Shareable configurations                         [array]
      --ci              Toggle CI verifications                        [boolean]
      --debug           Output debugging information                   [boolean]
  -d, --dry-run         Skip publishing                                [boolean]
  -h, --help            Show help                                      [boolean]
  -v, --version         Show version number                            [boolean]

Plugins
      --verify-conditions                                                [array]
      --analyze-commits                                                 [string]
      --verify-release                                                   [array]
      --generate-notes                                                   [array]
      --prepare                                                          [array]
      --publish                                                          [array]
      --success                                                          [array]
      --fail                                                             [array]

Cannot read properties of undefined (reading 'length')
(node:532) Warning: "version" is a reserved word.
Please do one of the following:
- Disable version with `yargs.version(false)` if using "version" as an option
- Use the built-in `yargs.version` method instead (if applicable)
- Use a different option key
https://yargs.js.org/docs/#api-reference-version
(Use `node --trace-warnings ...` to show where the warning was created)

Exited with code exit status 1
```

**Comment by Th3S4mur41** [comment]
Facing the same issue in multiple repositories after the update to 19.0.4

**Comment by Kampfmoehre** [comment]
Having the same issue since dependabot updated from 19.0.3 to 19.0.4, example action that failed: https://github.com/droidsolutions/semantic-release-nuget/runs/7970368200?check_suite_focus=true
On the other repo it runs without problems though:
https://github.com/droidsolutions/semantic-release-update-file/runs/7970326101?check_suite_focus=true

**Comment by travi** [comment]
Thank you for the reports and apologies for the problems. We'll have to investigate why our test suite did not catch the problem. Do any of you think you have anything unique about your release process that might be different from standard semantic-release usage in case the problem is not universal?

I've reverted the yargs upgrade in #2534, which resulted in publishing [19.0.5](https://www.npmjs.com/package/semantic-release/v/19.0.5)

**Comment by Kampfmoehre** [comment]
I don't think I'm using anything special, just `npx semantic-release` with default config extended by GitHub plugin and slightly modified branches config.

**Comment by mscharley** [comment]
We're definitely not doing anything unusual either, my entire configuration is exactly as above, we're just swapping to use the main branch and a pretty standard set of basic plugins.

**Comment by travi** [comment]
interestingly, i have found that some of my projects had successful releases with v19.0.4, including but not limited to ( have not seen evidence of failure across my projects):
* https://github.com/form8ion/babel-preset/releases/tag/v1.6.95: https://github.com/form8ion/babel-preset/runs/7961685691?check_suite_focus=true#step:6:12
* https://github.com/form8ion/javascript/releases/tag/v8.5.0: https://github.com/form8ion/javascript/runs/7966175993?check_suite_focus=true#step:5:11

these projects also simply use `npx semantic-release` from github actions and have no custom config. i'm curious what might be different that resulted in problems from multiple folks but not in a manner that it consistently fails in all cases.

**Comment by mscharley** [comment]
The one variation I can find in my setup is that we us an npm script: `npm run semantic-release` where the npm script is just:

```json
{
  "scripts": {
    "semantic-release": "semantic-release"
  }
}
```

Other than that, the configuration is in `.releaserc` with contents as per the original ticket.

**Comment by mscharley** [comment]
The only other thing I can think of is that this is an ESM project with `"type": "module"` in my package.json. It feels irrelevant, but depending on what you're doing for eg. loading from `package.json`, then maybe not.

**Comment by Th3S4mur41** [comment]
Maybe this could help. Those are very similar repository with identical release config and almost identical package.json. One failed while this other one was successful.
https://github.com/ATOS-Actions/actions/runs/7962473374?check_suite_focus=true
https://github.com/ATOS-Actions/download-release-artifact/runs/7962445399?check_suite_focus=true
