### ISSUE TITLE
Scoped Package failing to publish release notes

### ISSUE THREAD

**Issue by kentcdodds** [semantic-release/semantic-release#257]
I'm preparing to give a training that includes semantic-release and I'm struggling to get things working well with a scoped package. Here's my [test repo](https://github.com/kentcdodds/tmp-starwars-names) and the corresponding [travis build](https://travis-ci.org/kentcdodds/tmp-starwars-names). In the build, you'll see the output:

``` console
semantic-release ERR! post Failed to publish release notes. { [Error: {"message":"Validation Failed","errors":[{"resource":"Release","code":"custom","field":"tag_name","message":"tag_name is not a valid tag"},{"resource":"Release","code":"custom","message":"Published releases must have a valid tag"},{"resource":"Release","code":"invalid","field":"target_commitish"}],"documentation_url":"https://developer.github.com/v3/repos/releases/#create-a-release"}]
semantic-release ERR! post   message: '{"message":"Validation Failed","errors":[{"resource":"Release","code":"custom","field":"tag_name","message":"tag_name is not a valid tag"},{"resource":"Release","code":"custom","message":"Published releases must have a valid tag"},{"resource":"Release","code":"invalid","field":"target_commitish"}],"documentation_url":"https://developer.github.com/v3/repos/releases/#create-a-release"}',
semantic-release ERR! post   code: 422 }
```

You'll notice from [the commits](https://github.com/kentcdodds/tmp-starwars-names/commits/master) that I've tried quite a few different things. At first I didn't realize that this was a `post` error. I thought that it wasn't actually publishing versions, but then I realized that it is indeed publishing versions, but it's not publishing release notes to GitHub.

Any idea what the problem is here? The default `tag` for releases is `latest` which is what I want. Help appreciated!

**Comment by gund** [comment]
I have somewhat similar problem, it publishes new version to NPM but fails to publish release notes to Github (despite token is fine) with next error:
```
semantic-release ERR! post Failed to publish release notes. { [Error: {"message":"Validation Failed","errors":[{"resource":"Release","code":"already_exists","field":"tag_name"}],"documentation_url":"https://developer.github.com/v3/repos/releases/#create-a-release"}]
semantic-release ERR! post   message: '{"message":"Validation Failed","errors":[{"resource":"Release","code":"already_exists","field":"tag_name"}],"documentation_url":"https://developer.github.com/v3/repos/releases/#create-a-release"}',
semantic-release ERR! post   code: 422 }
```

I can see that the message is `Release` + `already_exists` + `tag_name` so seems like it tries to release with same version however NPM version was updated with new one.

Is there any option to enable verbose/debug mode to see which version it is trying to push to Github?

Thanks

**Comment by cdaringe** [comment]
@kentcdodds, did you ever resolve this?

**Comment by cdaringe** [comment]
oh... that's weird. i just tagged on [another commit](https://github.com/Tripwire/octagon/commit/b890a683f40fda8b08fc8209e491e451bdbec1ef) that made it work.  maybe is was that i was not in the proper directory?  go figure.

**Comment by kentcdodds** [comment]
I never got it to work. I just went with a non-scoped package... I wonder if it'd work if I update to the latest version of `semantic-release`. In any case, it's not currently a problem for me, so I'll go ahead and close this.

**Comment by kelkes** [comment]
I've got the same problem. Trying to publish release notes for a private scoped packages

```
Generating changelog from  to HEAD...
Parsed 5 commits.
semantic-release ERR! post Failed to publish release notes. { [Error: {"message":"Validation Failed","errors":[{"resource":"Release","code":"custom","field":"tag_name","message":"tag_name is not a valid tag"},{"resource":"Release","code":"custom","message":"Published releases must have a valid tag"},{"resource":"Release","code":"invalid","field":"target_commitish"}],"documentation_url":"https://developer.github.com/v3/repos/releases/#create-a-release"}]
semantic-release ERR! post   message: '{"message":"Validation Failed","errors":[{"resource":"Release","code":"custom","field":"tag_name","message":"tag_name is not a valid tag"},{"resource":"Release","code":"custom","message":"Published releases must have a valid tag"},{"resource":"Release","code":"invalid","field":"target_commitish"}],"documentation_url":"https://developer.github.com/v3/repos/releases/#create-a-release"}',
semantic-release ERR! post   code: 422,
semantic-release ERR! post   status: 'Unprocessable Entity',
semantic-release ERR! post   headers:
semantic-release ERR! post    { server: 'GitHub.com',
semantic-release ERR! post      date: 'Mon, 13 Feb 2017 13:33:55 GMT',
semantic-release ERR! post      'content-type': 'application/json; charset=utf-8',
semantic-release ERR! post      'content-length': '386',
semantic-release ERR! post      connection: 'close',
semantic-release ERR! post      status: '422 Unprocessable Entity',
semantic-release ERR! post      'x-ratelimit-limit': '5000',
semantic-release ERR! post      'x-ratelimit-remaining': '4918',
semantic-release ERR! post      'x-ratelimit-reset': '1486993406',
semantic-release ERR! post      'x-oauth-scopes': 'repo, read:org, user:email, repo_deployment, repo:status, write:repo_hook',
semantic-release ERR! post      'x-accepted-oauth-scopes': '',
semantic-release ERR! post      'x-github-media-type': 'github.v3; format=json',
semantic-release ERR! post      'access-control-expose-headers': 'ETag, Link, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval',
semantic-release ERR! post      'access-control-allow-origin': '*',
semantic-release ERR! post      'content-security-policy': 'default-src \'none\'',
semantic-release ERR! post      'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
semantic-release ERR! post      'x-content-type-options': 'nosniff',
semantic-release ERR! post      'x-frame-options': 'deny',
semantic-release ERR! post      'x-xss-protection': '1; mode=block',
semantic-release ERR! post      'x-github-request-id': 'xxx' }
````

**Comment by felixcrive** [comment]
Same for me

`semantic-release ERR! post Failed to publish release notes. { [Error: {"message":"Not Found","documentation_url":"https://developer.github.com/enterprise/2.8/v3"}]
semantic-release ERR! post   message: '{"message":"Not Found","documentation_url":"https://developer.github.com/enterprise/2.8/v3"}',
semantic-release ERR! post   code: 404 }`

**Comment by toverux** [comment]
Why this issue has been closed? :) I'm having this problem for a while, and I'm tagging manually for now.

**Comment by kentcdodds** [comment]
This was closed because it's not directly affecting me and I'm not going to work on fixing it. If you want to fix the issue, feel free. I'll go ahead and re-open it.

**Comment by toverux** [comment]
Thanks, I'll see if I can help on this, I like this tool and I'd be happy to see it generating the changelogs.

**Comment by toverux** [comment]
Oh, strange, I've just published the 1.0 version of [mitmadness/UnityInvoker](https://github.com/mitmadness/UnityInvoker) and... that worked, the changelog has been generated. This is a scoped package too so... Are we certain that this bug is tied to scoped names?
Will comment again if I encounter the bug on the next release.

**Comment by vaidik** [comment]
Experiencing the same issue. I have a private repo and I didn't want to publish my package on npm. So I have removed the `npm publish` command from the `semantic-release` script. Could that be causing any issue?

**Comment by pvdlg** [comment]
A lot of semantic-release version has been released since this bug was opened.
Is this issue still happening with the last release ?

If yes, could you provide a link to the CI job on which the publish failed ?

**Comment by maxcnunes** [comment]
I had that error `{"resource":"Release","code":"already_exists","field":"tag_name"}` as well. In my case the `package.json`-`repository.url` was pointing to the wrong project.

**Comment by kentcdodds** [comment]
I don't think this is an issue any longer.

**Comment by zeidlos** [comment]
Still is an issue. :(

**Comment by silmarasilva** [comment]
I fixed it by changing the tag version: tag: ver-${{ github.sha }}

**Comment by patsevanton** [comment]
How are changed you code for fix error? Somebody have example without error?
