### ISSUE TITLE
Scoped package wrong version bump

### ISSUE THREAD

**Issue by peteyy** [semantic-release/semantic-release#258]
We'we had a commit with a fix with the following message:
- `fix(errorHandler): emit, 500 handling and joi message (#17)`

We have semantic-release set up on the project and it bumped the major version for this commit. We are using npmjs.com-s scoped private packages.

Our release looks like this (only the additional message was added):
https://www.dropbox.com/s/ulfymqa5940oup6/Screenshot%202016-07-11%2011.30.49.png?dl=0

**Comment by krishna-koushik** [comment]
I have a similar problem but for me lately my fix(): messages are generating minor version instead of fix version.

`npm run semantic-release

> @meltwater/output-manager-api@0.0.0-semantic-release semantic-release /home/ubuntu/output-manager-api
> semantic-release pre && npm publish && semantic-release post

+ @meltwater/output-manager-api@1.19.0
Generating changelog from v1.18.0 to HEAD...
Parsed 1 commits.`

**Comment by pvdlg** [comment]
Is this issue still happen on the latest release ?
If yes could you provide a link to the CI job that fails to do the release ?
