### ISSUE TITLE
MAJOR Version bump after MINOR or PATCH update

### ISSUE THREAD

**Issue by AliSajid** [semantic-release/semantic-release#2586]
### Current behavior

Hi. I am trying to create a workflow for my rust projects and semantic release is extremely helpful. However, the Rus ecosystem depends heavily on v1.0.0 being "stable". I am developing a CLI and even when I have a minor or patch change, and it is reflected in `commit_analyzer` output, the next release is automatically 1.0.0.

### Expected behavior

I would expect 0.0.1 to go to 0.1.0 on a minor release

### `semantic-release` version

17.1.1

### CI environment

Github Actions

### Plugins used

@semantic-release/exec@5.0
@semantic-release/git@9.0
semantic-release-rust@1.0.0-alpha.8

### `semantic-release` configuration

https://github.com/CogDisResLab/gainful_key/blob/main/.releaserc.yml

### CI logs

https://pipelines.actions.githubusercontent.com/serviceHosts/192894dd-b9ca-4ee0-8726-518efeb131f3/_apis/pipelines/1/runs/22/signedlogcontent/2?urlExpires=2022-10-06T17%3A34%3A55.8684245Z&urlSigningMethod=HMACV1&urlSignature=S97VgXxJTHFhPmYL4SjPb6dbDBQiIrsTvUBt%2B08SDqY%3D

**Comment by travi** [comment]
Please see https://semantic-release.gitbook.io/semantic-release/support/faq#can-i-set-the-initial-release-version-of-my-package-to-0.0.1
