### ISSUE TITLE
I have some perf(*) commits but new version is not released.

### ISSUE THREAD

**Issue by safareli** [semantic-release/semantic-release#261]
I have added some `perf` commits which imho should bump PATCH  version, but new version is not released.  [build](https://travis-ci.org/safareli/free/builds/145354727), [merged PR](https://github.com/safareli/free/pull/18)

**Comment by hbetts** [comment]
@safareli you may want to look into the following issue semantic-release/commit-analyzer#3

Whether a version is released is decided by `commit-analyzer` and there's an on-going discussion over there on how to support other commit types like `perf`.

**Comment by safareli** [comment]
Thanks

**Comment by pensierinmusica** [comment]
@safareli take a look here: https://www.npmjs.com/package/cz-changelog

**Comment by safareli** [comment]
This solved my issue

---

package.json
```json
{
  "release": {
    "analyzeCommits": "./misc/releaseAnalyzeCommits
  }
}
```

misc/releaseAnalyzeCommits
```js
const conventionalRecommendedBump = require('conventional-recommended-bump')

module.exports = (options, parserOpts, cb) => conventionalRecommendedBump(
  Object.assign({}, options, { preset: 'angular' }),
  parserOpts,
  (err, res) => cb(err, res != null ? res.releaseAs : res)
)
```

**Comment by kumarharsh** [comment]
The snippet is a bit outdated. In `conventional-recommended-bump`, the `res.releaseAs` property is apparently renamed to `res.releaseType` now.
