### ISSUE TITLE
Docs: incorrect phrasing about "best practice" and 0.X.Y versions

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [semantic-release/semantic-release#2639]
It seems from https://github.com/semantic-release/semantic-release/issues/1507#issuecomment-671514974 that the reason for closing #1507 was more that it's too big of an ask for the maintenance team. I'd also like to amplify @jcornaz's https://github.com/semantic-release/semantic-release/issues/1507#issuecomment-605420041:

> @gr2m, @travi, Since that FAQ states "it's not considered a good practice", could it provide sources about that?
> 
> Right now, the links provided by the FAQ are:
> 
> * a blog post that indeed seems to be written by someone who doesn't like `0.y.z` versions
> * the semantic versioning specification that says to start version at `0.1.0`
>   * By the way, the title of the FAQ is incorrect, semantic versioning starts at `0.1.0`, not `0.0.1`
>   * And fun fact, even semantic versioning specification itself started at `0.1.0`: https://semver.org/spec/v0.1.0.html
> 
> Unless other sources are provided, I don't see a reason to favor a random blog post over an official specification.
> 
> Could you maybe provide more sources of your statement? Or maybe reword the FAQ answer, so that we understand that it is an opinionated point of view that `semantic-release` takes?
> 
> And of course, don't forget to remove the link to the semantic versioning specification in that FAQ. Since it says the opposite, it only adds to the confusion ;-)

Semver itself allows for -and even seems to encourage!- a leading 0 per https://semver.org/#how-should-i-deal-with-revisions-in-the-0yz-initial-development-phase:

> The simplest thing to do is start your initial development release at 0.1.0 and then increment the minor version for each subsequent release.

Can we update the docs to not put down the idea of a 0.1.0?

```diff
## Can I set the initial release version of my package to 0.0.1?

- This is not supported by semantic-release as it's not considered a good practice, mostly because [Semantic Versioning](https://semver.org/) rules applies differently to major version zero.
+ This is not supported by semantic-release. [Semantic Versioning](https://semver.org/) rules apply differently to major version zero and supporting those differences is out of scope.
```

**Comment by Ryangr0** [comment]
Since the original ticket has been closed for further feedback after the decision was made not to support semver properly, I will complain here. What a crazy twist... So now my terrible app that's still under heavy development, starts off at 1.0.0 from the moment I push my first commit to main. I feel like everybody can intuitively understand that that's not desired behavior. I am upset.

**Comment by travi** [comment]
> So now my terrible app that's still under heavy development, starts off at 1.0.0 from the moment I push my first commit to main. I feel like everybody can intuitively understand that that's not desired behavior.

as is clarified in the discussion, semantic-release is opinionated about how to approach situations like this. that isnt necessarily not supporting the spec properly when the spec offers multiple ways to handle it. as documented in [that section of the FAQ](https://semantic-release.gitbook.io/semantic-release/support/faq#can-i-set-the-initial-release-version-of-my-package-to-0.0.1), our recommended approach for that is the following:

> If your project is under heavy development, with frequent breaking changes, and is not production ready yet we recommend [publishing pre-releases](https://semantic-release.gitbook.io/semantic-release/recipes/release-workflow/pre-releases#publishing-pre-releases).
