### ISSUE TITLE
[Question] How next-major works

### ISSUE THREAD

**Issue by oliveirarafa** [semantic-release/semantic-release#2640]
Well, when I use semantic-release on next-major branches it creates a new major version for my lib. Like v2.0.0, v3.0.0. 

Anyone knows why the default behavior it this? For my use case it is desirable to make it possible so the users can install my next-major versions.

I managed to make my next-major branch create versions like v2.0.0-next-major.1 (etc) using the prerelease setting but I need include a breaking change right at the first release or else I get a v1.4.5-next-major. 

Without using this everytime I run my pipeline with semantic-release and a new breaking commit the version gets bumped to 3, 4, 5...

**Comment by r4j4h** [comment]
There is a pull request that might affect logic that is affecting this behavior more towards what you are expecting, although I am not convinced it will fix your exact issue unfortunately. https://github.com/semantic-release/semantic-release/pull/2416

**Comment by oliveirarafa** [comment]
Ok. Thank you!

**Comment by Tlepel** [comment]
If I understand the issue correctly, I think you can tweak this behaviour using the `@semantic-release/commit-analyzer` plugin: https://github.com/semantic-release/commit-analyzer

Here you could add a type `'major-fix'` or `'major-release'` with `'release': 'major'`, or perhaps it's better to use a scope `major-release` to each commit that triggers a new release. Let me know if that solves your problem!
