### ISSUE TITLE
Github Actions CI - Genera an error

### ISSUE THREAD

**Issue by okarook** [semantic-release/semantic-release#2647]
### Current behavior

<img width="1030" alt="image" src="https://user-images.githubusercontent.com/4731245/211103021-0c0c0280-9770-41c2-88a3-d56e13479309.png">

### Expected behavior

This should to work

### `semantic-release` version

^19.0.5

### CI environment

cycjimmy/semantic-release-action@v2

### `semantic-release` configuration

```
"plugins": [
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    "@semantic-release/changelog",
    "@semantic-release/github",
    "@semantic-release/npm",
    "@semantic-release/git"
  ],

```
### CI logs

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/runner/work/_actions/cycjimmy/semantic-release-action/v2/node_modules/semantic-release/index.js
require() of ES modules is not supported.
require() of /home/runner/work/_actions/cycjimmy/semantic-release-action/v2/node_modules/semantic-release/index.js from /home/runner/work/_actions/cycjimmy/semantic-release-action/v2/src/index.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename /home/runner/work/_actions/cycjimmy/semantic-release-action/v2/node_modules/semantic-release/index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /home/runner/work/_actions/cycjimmy/semantic-release-action/v2/node_modules/semantic-release/package.json.

**Comment by travi** [comment]
cycjimmy/semantic-release-action is not supported by this team. you will need to reach out the the maintainers of that action for support around this. it is likely that this is related to [today's release](https://github.com/semantic-release/semantic-release/releases/tag/v20.0.0) that transitions the core package to ESM-only.
