### ISSUE TITLE
Support for non-nodejs project?

### ISSUE THREAD

**Issue by cybertk** [semantic-release/semantic-release#267]
I have used **semantic-release** for months. It saves me much time. I'd say it's a very awesome project with an excellent idea(kill all humans).

Is there any plan to support non-Node.js project?

**Comment by dalelotts** [comment]
I would like to use this to `publish` (java and node projects) to a private binary repository, not npm. (S3 in one case, artifactory in the other) but it does not look like that is supported...yet. 😄

**Comment by pvdlg** [comment]
Since version [`11.0.0`](https://github.com/semantic-release/semantic-release/releases/tag/v11.0.0) semantic-release can be used to release any type of project independently of the language.
It requires to create plugins.

Version `11.0.0` is available on the `@next` dist-tag.

**Comment by cybertk** [comment]
Cool, will have a try!
