### ISSUE TITLE
Document the start version (v1.0.0 or v0.1.0)

### ISSUE THREAD

**Issue by gajus** [semantic-release/semantic-release#268]
It is not clear what is the initial version that is going to get published.

According to http://semver.org/#how-should-i-deal-with-revisions-in-the-0yz-initial-development-phase:

> **How should I deal with revisions in the 0.y.z initial development phase?**
> The simplest thing to do is start your initial development release at 0.1.0 and then increment the minor version for each subsequent release.

Therefore, one would expect that semantic-release would start with v0.1.0.

However, it appears that the first version that gets released is v1.0.0.

**Comment by vrtxf** [comment]
read http://semver.org "faq" section

**Comment by gajus** [comment]
@vrtxf The quote is from FAQ section of http://semver.org. You will need to be more specific.

Regardless, this was a suggestion to improve docs.
