### ISSUE TITLE
Support of calver

### ISSUE THREAD

**Issue by fdubost** [semantic-release/semantic-release#2705]
### New feature motivation

Some teams in my company use the calver convention instead of semver. We want to globally migrate to semantic-release (we have an homemade tool for now) but we can't because it only support semver.

### New feature description

Adding the possibility to select additional versioning convention in the configuration like calver

### New feature implementation

Having a factory of versioning convention and using [`calver` package](https://www.npmjs.com/package/calver)

**Comment by travi** [comment]
while we recognize that there are other versioning schemes than semver, semantic-release is specifically targeted at enabling projects to use semver effectively more easily. semantic-release is not a generic workflow tool. sorry, but this request is not in line with the goals of this project
