### ISSUE TITLE
Transient failure with parallel publishing in a mono repo

### ISSUE THREAD

**Issue by randymarsh77** [semantic-release/semantic-release#2715]
### Current behavior

Context:
I'm using a GitHub action matrix to run (up to) 22 parallel build/publish jobs in a mono repo. (Recently switched from a serial build, so now this issue occurs). I was on an older version (17), but the problematic code/behavior looks the same in the latest version (which I'm updating too to verify the problem still occurs, though it might be a while before this many parallel runs occur again in order to test this).

Problem:
At some point, semantic-release fetches `refs/notes`. At a later point, semantic-release tries to push to `refs/notes` *after* another job has pushed `refs/notes`. This attempt fails. However, there are no other commits pushed, only a parallel release that had pushed notes.

The actual error and crashing (calling) line is:
https://github.com/semantic-release/semantic-release/blob/1775ed80b9a97d58842b0c56f394ba76b14bcf22/index.js#L208

Which simply is trying to push:
```
await execa('git', ['push', repositoryUrl, `refs/notes/${GIT_NOTE_REF}`], execaOptions);
```

```
    ' ! [rejected]          refs/notes/semantic-release -> refs/notes/semantic-release (fetch first)\n' +
    "error: failed to push some refs to 'REDACTED'\n" +
    'hint: Updates were rejected because the remote contains work that you do\n' +
    'hint: not have locally. This is usually caused by another repository pushing\n' +
    'hint: to the same ref. You may want to first integrate the remote changes\n' +
    "hint: (e.g., 'git pull ...') before pushing again.\n" +
    "hint: See the 'Note about fast-forwards' in 'git push --help' for details.",
```

Now, the broken release is in this state:
- A tag has been pushed
- A package and release has not been published
- Each build in this state needs to be manually fixed and retried

Suggestion:
The attempted release has a unique tag/format, so it seems like some "pull --rebase" (just for re-fetching notes) attempt and retry might avoid the issue while being safe enough to fail on a real conflict. Even a pull on `refs/notes` right before adding the note would probably be enough to *minimize* the scope of the race for most practical use.

### Expected behavior

Not failing with an avoidable error and leaving the release in a broken state.

### `semantic-release` version

17.3.3

### CI environment

GitHub Actions (Enterprise)

### Plugins used

Using a few plugins (mentioned below), but the problematic code is in the primary semantic-release project.

### `semantic-release` configuration

```
{
	branches: ['master'],
	tagFormat: 'REDACTED-${version}',
	plugins: [
		[
			'filtered-commit-analyzer',
			{
				preset: 'angular',
				filterRules: {
					scope: 'REDACTED|all',
				},
			},
		],
		[
			'@semantic-release/exec',
			{
				prepareCmd: 'yarn pack --filename dist.tgz',
				publishCmd:
					'yarn publish-nuget-package-if-necessary --version-override ${nextRelease.version}',
			},
		],
		[
			'@semantic-release/github',
			{
				successComment: false,
				failComment: false,
				failTitle: false,
				assets: [{ path: 'dist.tgz', label: 'Distribution' }],
			},
		],
	],
}
```

### CI logs

Relevant log posted, other logs have too much to redact, but, can process/post if needed.

**Comment by randymarsh77** [comment]
FWIW, I added `git fetch origin refs/notes/semantic-release` before invoking `semantic-release` and the jobs seemed less prone to that race condition, but I eventually got the same failure, so it seems like some retry behavior might be in order.

**Comment by travi** [comment]
semantic-release does not officially support monorepos. enabling parallel execution like you describe would require extensive redesign of the project and is not planned because it is not necessary for supported use cases

**Comment by randymarsh77** [comment]
I can appreciate the need to triage only relevant and priority work for supported use cases. However, I don't think this failure condition is constrained to "mono repos" / unsupported use-cases. For example, if publishing a pre-release or channel version from a separate branch is possible, then it is up to the consumer to avoid a concurrent CI job for these branches.

I also think there might be alternative ways to avoid this failure that don't require changing the expectations of what is officially supported in terms of monorepos or parallel execution. For example, if the release configuration allowed customization of the destination notes, then a project could avoid a conflict in `refs/notes/semantic-release`. Alternatively, allowing a plugin to configure "note management" might be another option. Though, admittedly these seem pretty heavy handed and overly complex when a simply retry of creating the note would very self contained. (Even opting-in to this behavior via a feature flag / environment would further mitigate any risk to it.)

As it stands, I think I can work around the problem in full by adding a little more complexity to my CI pipeline, but I'd be happy to write and submit this patch if any of these options were directions you'd be interested in.
