### ISSUE TITLE
Changes are not detected

### ISSUE THREAD

**Issue by MoeSattler** [semantic-release/semantic-release#276]
semantic release does not detect changes for some reason:
https://travis-ci.org/travelperk/case-converter/jobs/153565553

As you can see, the commit which was build contained a `fix`. Still, semantic-release did not find any changes.

**Comment by boennemann** [comment]
Doesn't look right indeed.
What happens if you run `npm run semantic-release` locally? (runs in debug mode automatically)

**Comment by Moezalez** [comment]
`semantic-release didn’t run on Travis CI and therefore a new version won’t be published.`

I guess I have to modify it to run it locally.

**Comment by boennemann** [comment]
That's the expected output, because it was run locally ;)
But did it detect a new version before that? Maybe just send me the entire output/screenshot, so I can have a look :)

**Comment by Moezalez** [comment]
<img width="1170" alt="screen shot 2016-08-19 at 16 49 57" src="https://cloud.githubusercontent.com/assets/8615251/17813781/04aaf490-662d-11e6-86f8-dce0d27ade1a.png">

**Comment by Moezalez** [comment]
<img width="1137" alt="screen shot 2016-08-19 at 16 51 36" src="https://cloud.githubusercontent.com/assets/8615251/17813829/3f75e67a-662d-11e6-883c-148bea8bf38b.png">

**Comment by boennemann** [comment]
Okay so `npm info case-converter gitHead` returns `1ec9488803ff8f1845b07a949908fde13bc84e63`, which is your latest commit: https://github.com/travelperk/case-converter/commit/1ec9488803ff8f1845b07a949908fde13bc84e63.

semantic-release uses this information from the npm registry to find the differing commits. 
Your manual release might have fixed things now, even though I'm still not sure what's been broken.

If you do `git commit -m 'fix: dummy commit' --allow-empty` on your master branch and then run `npm run semantic-release` right after that it should now correctly detect a new patch release.

Can you confirm this?
Run `git reset HEAD^` to remove this test commit again.

**Comment by Moezalez** [comment]
<img width="1170" alt="screen shot 2016-08-19 at 19 30 46" src="https://cloud.githubusercontent.com/assets/8615251/17818350/7ec62860-6643-11e6-809c-fbbcd6574933.png">

**Comment by Ian-Rossi-aimtheory** [comment]
Hi @MoeSattler, how did you get around this? Your last screenshot here looks like it was still failing to determine version. I have the same issue where I haven't yet gotten an initial versioning to take place. Thanks for any info you have.

**Comment by MoeSattler** [comment]
@Ian-Rossi-aimtheory I dropped semantic release

**Comment by Ian-Rossi-aimtheory** [comment]
@MoeSattler OK, that is actually helpful. What did you do instead? I'm interested. Thanks.

**Comment by Ian-Rossi-aimtheory** [comment]
@MoeSattler Perhaps you'll consider reopening this. @boennemann Perhaps you could reopen it? Because I am just getting started with SR and I cannot get past this. I have never released my demo app with SR, so what's saying in the error message doesn't make much sense. I just need to get a first release going? How do I do that?

**Comment by Ian-Rossi-aimtheory** [comment]
Thanks @MoeSattler . @boennemann I am facing the same issue as @MoeSattler.  If you can help me get over this hump, I would really appreciate it as I would love to be able to use SR to deliver my nodejs projects. This is the error I am facing. It seems like a chicken/egg scenario. I am dropping efforts to use SR at this time, due to this blocker, but would love to be unblocked and really be able to use SR. Thanks.
```
semantic-release ERR! commits The commit the last release of this package was derived from is not in the direct history of the "master" branch.
semantic-release ERR! commits This means semantic-release can not extract the commits between now and then.
semantic-release ERR! commits This is usually caused by force pushing, releasing from an unrelated branch, or using an already existing package name.
semantic-release ERR! commits You can recover from this error by publishing manually or restoring the commit "ebd22468e45c8749026458a5432abf456965183d".
semantic-release ERR! commits Here is a list of branches that still contain the commit in question: 
semantic-release ERR! commits  * * (detached from 7b10008)
semantic-release ERR! pre Failed to determine new version.
semantic-release ERR! pre ENOTINHISTORY Commit not in history

npm ERR! Linux 3.13.0-101-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "semantic-release"
npm ERR! node v0.10.48
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE
npm ERR! @cc/node-hello-world@1.0.0 semantic-release: `semantic-release pre && npm publish && semantic-release post`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @cc/node-hello-world@1.0.0 semantic-release script 'semantic-release pre && npm publish && semantic-release post'.
npm ERR! This is most likely a problem with the @cc/node-hello-world package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     semantic-release pre && npm publish && semantic-release post
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs @cc/node-hello-world
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls @cc/node-hello-world
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/jenkins_home/workspace/node-pipeline-feature-deploy/npm-debug.log
Build step 'Execute shell' marked build as failure
Finished: FAILURE
```

**Comment by Bigous** [comment]
Does anybody has any hint?
