### ISSUE TITLE
Failed step success of plugin @semantic-release/github

### ISSUE THREAD

**Issue by Abeinevincent** [semantic-release/semantic-release#2762]
### Current behavior

I am getting an error: failed success of plugin @semantic-release/github when I push to github using Github Actions

### Expected behavior

Its should be able to build successfully

### `semantic-release` version

21.0.1

### CI environment

Github Actions

### `semantic-release` configuration

My yaml file is: 
name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: '*'

jobs:
  quality:
    name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['14.x', '16.x', '18.x']
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test --ci --coverage --maxWorkers=2

      - name: Build
        run: yarn build

  publish:
    runs-on: ubuntu-latest
    if: ${{github.ref == 'refs/heads/master'}}
    needs: [quality]
    permissions:
      packages: write
      contents: write 
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

          
      - run: npm ci
      - run: npm run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

### CI logs

name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: '*'

jobs:
  quality:
    name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['14.x', '16.x', '18.x']
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test --ci --coverage --maxWorkers=2

      - name: Build
        run: yarn build

  publish:
    runs-on: ubuntu-latest
    if: ${{github.ref == 'refs/heads/master'}}
    needs: [quality]
    permissions:
      packages: write
      contents: write 
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

          
      - run: npm ci
      - run: npm run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

**Comment by Abeinevincent** [comment]
I fixed the issue my self and the error was because my token didnt have permisison to close an issue on github yet the only existing issue was because my workflow was failing and upon running successfully, I needed the issue closed to erase the error. I did fix it by providing the permission to close issues in the permissions section:
`...
permissions:
      issues: write
...
`

**Comment by travi** [comment]
the required permissions for a github token are listed at https://github.com/semantic-release/github#github-authentication. while restricting permissions more narrowly is recommended, those required permissions are included in the defaults granted to the GITHUB_TOKEN provided automatically to a github action, so these details are primarily provided for folks taking the step to narrow those permissions.
