### ISSUE TITLE
Error: Cannot find module 'babel/register'

### ISSUE THREAD

**Issue by finom** [semantic-release/semantic-release#278]
```
Error: Cannot find module 'babel/register'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/finom/Dropbox/sync/my/github/matreshka_refactoring/node_modules/semantic-release/bin/semantic-release.js:8:5)
    at Module._compile (module.js:556:32)

    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
```

The error is caused by the following really smelly code instead of showing me real error.

``` js
try {
  require('../dist')
} catch (err) {
  if (err.code === 'MODULE_NOT_FOUND') {
    require('babel/register')
    require('../src')
  } else {
    console.log(err)
  }
}
```

UPD. The issue appeared because I have used wrong path at `release.analyzeCommits`.

**Comment by justmoon** [comment]
Had the same issue. For me it was the fact that `condition-circle` wasn't installed.

Recommended solution: Only put a `require.resolve('../dist')` statement inside of the `try {}` block. Right now, if there is a "module not found" error anywhere in semantic-release, it'll give this cryptic error message. If you put only `require.resolve` in the try-catch block, then it will only trigger if `../dist` *itself* is not found, not any of its dependencies.

Something like:
``` js
function checkModule (path) {
  let distAvailable = false
  try {
    require.resolve('../dist')
    return true
  } catch (err) {
    if (err.code === 'MODULE_NOT_FOUND') {
      return false
    } else {
      throw new Error('Unexpected error while resolving ../dist:' + err)
    }
  }
}

if (checkModule('../dist')) {
  require('../dist')
} else {
  require('babel/register')
  require('../src')
}
```

**Comment by Ridermansb** [comment]
Same error for me.. and I don`t set analyzeCommits path..

I use circle-ci ...
https://circleci.com/gh/Ridermansb/vue-gmaps/8

```
"release": {
    "verifyConditions": "condition-circle"
  },
  "config": {
    "commitizen": {
      "path": "./node_modules/cz-conventional-changelog"
    }
  }
```

**Comment by finom** [comment]
@justmoon the error means that somewhere semantic-release code requires non-existent module.

**Comment by pvdlg** [comment]
The code mentioned is not part of `semantic-release` anymore. The Module not found is expected if the referenced plugin is not accessible.

Is this issue still happening ? Or can we close it?

**Comment by pvdlg** [comment]
Closing due to lack of response. Please re-open if it's still an issue.

**Comment by okonet** [comment]
I use TravisCI with `npx travis-deploy-once "semantic-release"` and just hit this as well. 

https://travis-ci.org/okonet/react-simple-focus-within/jobs/422469781

**Comment by okonet** [comment]
Probably this one is a wrong one for me after all. See https://github.com/semantic-release/travis-deploy-once/issues/87
