### ISSUE TITLE
Warn user about nonexistent gitHead returned by npm-registry-client

### ISSUE THREAD

**Issue by finom** [semantic-release/semantic-release#280]
I have spent a day on trying to fix weird behavior of the semantic-release (eg empty releases, releasing on "chore" etc). The thing I finally figured out is that the NPM Registry API doesn't return `gitHead` [for some of versions](http://registry.npmjs.org/matreshka) and [last-release-npm](https://github.com/semantic-release/last-release-npm/blob/next/src/index.js#L42) does not check its existence (this is general issue so I decided to create an issue there).

The reason was the way I publish my library. I compile everything to npm/ folder and publish it from there.   NPM doesn't know about git repository. As dirty solution for my problem I copy .git folder from root to npm/.git before publish.

**Comment by finom** [comment]
A solution looks similar to this:

```js
const { gitHead } = data.versions[version];
    
    if(!gitHead) {
      return cb(new SemanticReleaseError(
`NPM registry does not contain "gitHead" in latest package version data.
It's probably because somebody is made publish outside of repository folder.`,
      'ENOGITHEAD'))
    }
    
    cb(null, {
      version,
      gitHead,
      get tag () {
        npmlog.warn('deprecated', 'tag will be removed with the next major release')
        return npm.tag
      }
    })
```

(not doing pull req because have no time to make tests)

**Comment by vrtxf** [comment]
Could this be related to your issue ?
https://github.com/semantic-release/last-release-npm/pull/87

**Comment by finom** [comment]
Not sure.

**Comment by coderbyheart** [comment]
This could be fixed by fetch the commit id from GitHub for the tag detected by `last-release-npm`

**Comment by finom** [comment]
Nice to see the project to be maintained.
