### ISSUE TITLE
feat: achieve SLSA levels

### ISSUE THREAD

**Issue by patelniketm** [semantic-release/semantic-release#2802]
### New feature motivation

- SLSA L1 provides how the package was built
- This could be stepping stone for SLSA L2 (signed provenance and build) and L3 (hardened build system)
- This provides confidence on using tamper proof release with signature verification

### New feature description

NPM has support for SLSA provenance. Adding this provenance could provide documented build process. This could be first step to get secured supply chain. And signing build could provide way to verify those signatures. Hardened build system can also be achieved to keep things on tight loop.

https://slsa.dev/spec/v1.0/levels

**Comment by patelniketm** [comment]
cc @travi

**Comment by travi** [comment]
> NPM has support for SLSA provenance.

we are well aware of this. we were part of the private beta to ensure it would work with tools like semantic-release. our documentation [includes details about enabling provenance](https://github.com/semantic-release/npm/#npm-provenance) when using semantic-release.

we're already leveraging provenance for publishing, which is configured here: https://github.com/semantic-release/semantic-release/blob/fa133f2a9df956b89cd2a7062b18f151ffb56e6c/package.json#L121

the result of this is shown at https://www.npmjs.com/package/semantic-release#provenance and can be verified with `npm audit signatures`, which is a step that we perform in all of our workflows, such as https://github.com/semantic-release/semantic-release/blob/fa133f2a9df956b89cd2a7062b18f151ffb56e6c/.github/workflows/test.yml#L55

could you help me understand what steps you are suggesting we take that we are not already performing?

**Comment by travi** [comment]
i'm closing this in favor of #2913 since publishing with slsa level 2 is already accomplished through existing use of the npm cli provenance flag.
