### ISSUE TITLE
Semantic-release permanently broken (reading the incorrect version), cannot get it to release a new version

### ISSUE THREAD

**Issue by paambaati** [semantic-release/semantic-release#2810]
### Discussed in https://github.com/semantic-release/semantic-release/discussions/2788

<div type='discussions-op-text'>

<sup>Originally posted by **paambaati** May  7, 2023</sup>
Many months ago, I migrated the default branch of my repo from `master` to `main`, and ever since then, semantic-release has never been the same.

I keep going back to the troubleshooting guide and do all the steps, but the release process is now permanently broken and has become unreliable when applying manual fixes.

Example workflow run that reports the wrong version – https://github.com/paambaati/codeclimate-action/actions/runs/4905711649/jobs/8759663416

The dry run keeps picking up the last commit as `v3.2.0` when in fact, `v4.0.0` was released by semantic-release (see https://github.com/paambaati/codeclimate-action/actions/runs/4777730343/jobs/8493671186). I've also followed the troubleshooting guide to recreate my tags and ref notes, with no luck.

```bash
# REFER: https://github.com/semantic-release/semantic-release/blob/master/docs/support/troubleshooting.md#release-not-found-release-branch-after-git-push---force
git tag --delete v4.0.0
git push --delete origin v4.0.0
git tag v4.0.0 cdbb31e9cece505753becbfccc7ab64665a4cca5 # Commit that created the release
git notes --ref semantic-release add -f -m '{"channels":[null]}' v4.0.0
git push --force origin refs/notes/semantic-release
```

EDIT: Additional information as I continue to debug this –

Looks like `git tag --merged main` returns only a few tags.

```bash
git tag --merged main

v1.0.0
v2.2.5
v2.2.6
v3.1.0
```

The above steps no longer work either, and I'm at my wits' end. I'd really appreciate if someone can help fix this for good.</div>

**Comment by travi** [comment]
please do not open duplicate issues/discussions. closing in favor of https://github.com/semantic-release/semantic-release/discussions/2788
