### ISSUE TITLE
How can I release a major version?

### ISSUE THREAD

**Issue by cameronroe** [semantic-release/semantic-release#282]
I need to manually push a 1.0. How can I do this with semantic-release? My builds currently run on travis, it's creating v0.2.0 v0.3.0 etc.

**Comment by vrtxf** [comment]
read the documentation for "breaking changes"

**Comment by crobinson42** [comment]
@cameronroe Is this still an 'open' issue?

A major release is triggered when a commit message contains the string "`BREAKING CHANGES`".

**Comment by cameronroe** [comment]
Okay, thanks. Closing now.
