### ISSUE TITLE
prelease branch seems to be creating major new release, what if I would like my prerelease to be more flexible and start with a new minor release instead of major?

### ISSUE THREAD

**Issue by hpe-ykoehler** [semantic-release/semantic-release#2847]
Assuming one respect the semantic version rules, a new version of software should be based on content, as such, if I have my main is at 1.0.0, and I want to create a prerelease alpha on it, right now semantic-release seems to force me to increase the major (2.0.0-alpha.1) which imply a breaking change, but I may not plan any breaking change in my software, but likely new feature, could I instruct that my prerelease should start as a minor new release (1.1.0-alpha.1) ?

**Comment by travi** [comment]
the pre-release workflow already supports what you describe. if this is not the behavior you are seeing, please provide a public minimal reproduction

**Comment by travi** [comment]
> so the documentation would be wrong? [semantic-release.gitbook.io/semantic-release/recipes/release-workflow/pre-releases](https://semantic-release.gitbook.io/semantic-release/recipes/release-workflow/pre-releases)
> 
> says here initial relese is 1.0.0, creation of prerelease beta starts at 2.0.0 (not 1.1.0)
> 
> "We now decide to work on a future major release,"

the documentation is not wrong, but possibly not obvious. the pre-release workflow bases the version bumps on the commit convention the same way it does in the normal release workflow. if you look at the details of the example commit, you can see that it is a commit that includes a breaking change, which would result in a major version bump.

**Comment by travi** [comment]
closing, as i assume this has been answered, but please feel free to respond if more clarification is needed

**Comment by hpe-ykoehler** [comment]
@travi that is actually kind of what I would have expected, will do some testing locally to confirm then, I am not a native English person, as such, I may have misread the documentation or misunderstood it.
