### ISSUE TITLE
Generating a CHANGELOG.md file

### ISSUE THREAD

**Issue by olalonde** [semantic-release/semantic-release#289]
Would be nice if this module would also generate a CHANGELOG.md file on every new version

**Comment by crobinson42** [comment]
+1 I noticed in `standard-version` (https://www.npmjs.com/package/standard-version) In the FAQ it says this package, `semantic-release` generates changelogs...:

> FAQ
> How is standard-version different from semantic-release?
semantic-release is a fully automated library/system for versioning, changelog generation, git tagging, and publishing to the npm registry.

**Comment by crobinson42** [comment]
I am not getting any CHANGELOG.md in my projects, either.

**Comment by boneskull** [comment]
@crobinson42 It does--in a GitHub release.

**Comment by crobinson42** [comment]
And how?

**Comment by boneskull** [comment]
@crobinson42 No, it doesn't make a `CHANGELOG.md`.  It puts the changelog in the GitHub release description.

**Comment by boneskull** [comment]
(I responded to the "`semantic-release` generates changelogs" quote)

**Comment by crobinson42** [comment]
Ahh. My misunderstanding! Thanks for clarifying..

**Comment by uglow** [comment]
https://github.com/leonardoanalista/corp-semantic-release generates changelogs and works for non-GitHub repositories.

**Comment by develar** [comment]
This feature request contradicts the idea of semantic release. To apply changed `CHANGELOG.md` additional commit is required. So, imagine —  on each your `fix` or `feat` commit will  be created yet another synthetic commit. And your log will be littered with it.

It is exactly why version not presented in the `package.json`.

Also, sometimes you will change GitHub release notes to add contributors/some additional notes.

So, it is bad idea :) You or use semantic release (release often) or not (sporadic releases and angry users (if your project is active).

**Comment by honzajavorek** [comment]
My project uses Sem Rel and follows the practice of having the changelog in GitHub Releases. However, I'd like to have a way to dynamically generate also a file with the changelog to attach it to my dynamically generated docs. Sometimes it's easier to scan, search and follow a single page then to interact with click-heavy UI, such as GitHub Releases. What would be the best approach to do this? Should I write my own tool and take the contents from GitHub Releases, or can I leverage Sem Rel for this somehow?

**Comment by levithomason** [comment]
You can generate a changelog from your issues and PRs with a curl call using https://github.com/levithomason/github-changelog-api. Human curated changelogs are always best but this can be an alright stop-gap.

**Comment by pvdlg** [comment]
This feature has been implemented via https://github.com/semantic-release/git plugin
