### ISSUE TITLE
Add interactive set up for travis.yml

### ISSUE THREAD

**Issue by tlvince** [semantic-release/semantic-release#29]
Similar to `travis setup [component]`, it'd be nice if the [travis.yml configuration](https://github.com/boennemann/semantic-release#ci-server) could be scripted, perhaps part of `semantic-release setup`.

**Comment by boennemann** [comment]
Sorry for the late reply, this is a very good idea and I keep thinking about how to make this right.

My current thinking is that it doesn't make sense to bloat semantic-release too much, so maybe a seperate cli and core would make sense, so we can build all the things™ into the cli (e.g. dependencies necessary for travis and other services, argument parsers, abbrev) and have a very lean core that gets installed way more often.

I'd like to collect ideas here, so please write down yours and feedback here.

Best,
Stephan

**Comment by boennemann** [comment]
Here we go: https://github.com/semantic-release/cli

**Comment by tlvince** [comment]
<3
