### ISSUE TITLE
BREAKING CHANGE: not triggering a Major version release

### ISSUE THREAD

**Issue by crobinson42** [semantic-release/semantic-release#292]
I made a commit that included `BREAKING CHANGE:` in the commit message and I didn't get any publish. In fact, no other commits after that point trigger a publish!

https://github.com/crobinson42/string-format-validation/commit/d4879320fb22243fb0a346a972150a4d98e51f3d

RE:
> https://github.com/semantic-release/semantic-release#major-breaking-release

**Comment by KarstenBuckstegge** [comment]
FYI:`fix` commits don't seem to trigger major version bumps even with a `BREAKING CHANGE` text in the commit body.
