### ISSUE TITLE
Tracking issue for conventional-changelog preset updates

### ISSUE THREAD

**Issue by travi** [semantic-release/semantic-release#2929]
### My release workflow is broken with an error about conventional-changelog-*

new versions of conventional-changelog presets were released over the weekend with breaking changes. these updates were properly released as major versions, but you may be installing the latest version as part of your release pipeline.

Note: if you are using the default angular preset through the core package without installing independently, you should not be experiencing problems because the previous major is still defined as the installed dependency in that situation

### What can i do to fix my release pipeline?

you will need to specify a version or version range for the preset package that you are installing. for example, if you are installing with npm before executing, you could update like:

```diff
- npm install -g semantic-release conventional-changelog-conventionalcommits
+ npm install -g semantic-release conventional-changelog-conventionalcommits@6
```

### What will the semantic-release team do to handle this issue going forward?

this is a breaking change for us too. this is a change to how presets are loaded and we will be updating to handle the change. however, we want to make sure we handle the update properly, so we are not making the change immediately. we will likely treat this change as a breaking change for our consumers by dropping support for loading the presets that used the previous loading approach. 

### Other issues exposed by this situation

we are seeing feedback about some other issues that need attention that arent directly related to this issue, but are exposed/highlighted by this situation. we are paying attention to that feedback, but will need to follow up on those issues after the primary complications are addressed. 

* #2932 

### How can i help?

if you are looking to resolve problems with your releases, focus on specifying the version of the preset you are loading. however, if you would like to help us investigate these issues, we welcome you help and participation in the conversation.

**Comment by efr-devgod** [comment]
We have discovered that 2 days ago, https://www.npmjs.com/package/conventional-changelog-conventionalcommits released a breaking version, version 7.0.0. The "fix/workaround" for us was to hard code version 6.1.0. We haven't yet dug into the specific changes, but I hope this helps anyone else looking into the issue.

**Comment by vytautas-pranskunas-** [comment]
watching

**Comment by vitorf7** [comment]
Ahh let me check my company's GitHub actions workflows to see if this fixes the reason why all of a sudden our flows stopped creating new tags and releases

**Comment by travi** [comment]
a new beta version is available as a result of this wip pr: https://github.com/semantic-release/semantic-release/pull/2934

we would appreciate if folks that are impacted by this change would give the beta a try to help give us confidence that we've fully handled the changes. install with `npm install semantic-release@beta` or use with `npx` as `npx semantic-release@beta`.

**Comment by marksie1988** [comment]
Just tested with the beta and this has fixed it for me 👍 thanks for that.

**Comment by fin-gal** [comment]
Using beta also solved the problem on my side, thank you so much!
