### ISSUE TITLE
Add plugin semantic-release-pub

### ISSUE THREAD

**Issue by zeshuaro** [semantic-release/semantic-release#2975]
### New plugin motivation

- There isn't an existing plugin for publishing [Dart](https://dart.dev/tools/pub/publishing) or [Flutter](https://docs.flutter.dev/packages-and-plugins/developing-packages#publish) packages onto the [pub.dev](https://pub.dev/) registry.
- Created the plugin [semantic-release-pub](https://github.com/zeshuaro/semantic-release-pub) which supports:
  - Updating the package version.
  - Uploading the package onto the registry.

### Third-party documentation

- Docs: https://dart.dev/tools/pub/automated-publishing
- Example workflow using the plugin: https://github.com/zeshuaro/google_api_headers/actions/runs/6249991527/job/16967868618

**Comment by travi** [comment]
Thanks for letting us know. If you'd like to create a PR for our docs to list your plugin in the list of community plugins, that would be welcome
