### ISSUE TITLE
Support extending ESM based configurations

### ISSUE THREAD

**Issue by dominykas** [semantic-release/semantic-release#3036]
### New feature motivation

`semantic-release` now supports ESM in pretty much every context, except for `--extends`.

### New feature description

Accept `*.mjs` files in `--extends`.

### New feature implementation

I was playing along to see if conceptually I can make it work, and it seems I can - https://github.com/semantic-release/semantic-release/pull/3037

**Comment by travi** [comment]
i totally support moving this forward, but want to note that using a `.cjs` extension to continue using commonjs config is an option as a workaround in the meantime.

**Comment by dominykas** [comment]
My PR does add an explicit test that `.cjs` extension works. It did not need any code changes.
