### ISSUE TITLE
Documentation: link to sentimental versioning leads to nowhere

### ISSUE THREAD

**Issue by tbriot** [semantic-release/semantic-release#3066]
### Current behavior

In the online [documentation](https://semantic-release.gitbook.io/semantic-release/), in the 'How does it work' section, there is a link to: http://sentimentalversioning.org/. This domain name is for sale.

![image](https://github.com/semantic-release/semantic-release/assets/26529814/3986a5b7-f1b9-4adf-bbad-2c618f80c184)

![image](https://github.com/semantic-release/semantic-release/assets/26529814/ea5a8227-8af3-4816-8991-1d420d7fd137)

### Expected behavior

Link should point to a webpage explaining what **sentimental versioning** is.

Maybe this link should point to: https://github.com/dominictarr/sentimental-versioning

### `semantic-release` version

v22.0.8

### CI environment

n/a

### Plugins used

n/a

### `semantic-release` configuration

n/a

### CI logs

n/a

**Comment by sheerlox** [comment]
Thanks for reporting the issue @tbriot!

Redirecting to https://github.com/dominictarr/sentimental-versioning#readme (with the added `#readme`) looks good.

Would you be willing to make a PR?

**Comment by tbriot** [comment]
> Thanks for reporting the issue @tbriot!
> 
> Redirecting to https://github.com/dominictarr/sentimental-versioning#readme (with the added `#readme`) looks good.
> 
> Would you be willing to make a PR?

I will.
