### ISSUE TITLE
Semantic Release cannot find my plugins?

### ISSUE THREAD

**Issue by yamikuronue** [semantic-release/semantic-release#308]
I installed a couple of plugins from github:

```
"devDependencies": {
    "@yamikuronue/commit-analyzer": "yamikuronue/commit-analyzer",
    "@yamikuronue/release-notes-generator": "yamikuronue/release-notes-generator",
```

And configured release to use them:

```
 "release": {
    "analyzeCommits": "@yamikuronue/commit-analyzer",
    "generateNotes": "@yamikuronue/release-notes-generator"
  }
```

But (after I tinkered with semantic-release's code so it would give me the real error, thanks to issue #278 ) I'm getting:

```
Error: Cannot find module '@yamikuronue/commit-analyzer'
```

I double-checked that it's installed. Why can't it find it?

**Comment by yamikuronue** [comment]
So... is this project abandoned or what? There's all this information on the front page about how it's got a plugin architecture, but all the promoted plugins are listed as "please implement", and I can't get help with installing my own basic plugins?

**Comment by janppires** [comment]
Can it be because you package is not published on npm? 

This plugin works fine and is configured in a similar way: https://www.npmjs.com/package/@krux/condition-jenkins

**Comment by yamikuronue** [comment]
Probably? But how am I supposed to test it before I publish?

Also I probably did scoped packages wrong, I've learned more about them in the three months since my last comment

**Comment by janppires** [comment]
@yamikuronue, I mean, `yamikuronue/commit-analyzer` and `yamikuronue/release-notes-generator` packages! You can use `npm publish` on each package to publish, and then you can use  them as dependencies for the `release. analyzeCommits` and `release. generateNotes`.

Cheers,

=)

**Comment by yamikuronue** [comment]
But I don't want to put anything in npm unless I know it works. And I can't test that it works if, as you say, I can't load it until it's in npm.

**Comment by pvdlg** [comment]
If you don't want to deploy to npm and still test your plugins, you could reference them as dependencies with their github url. See [package.json#github-urls](https://docs.npmjs.com/files/package.json#github-urls).
This way when running `npm install` you packages will be downloaded directly from their Github repo rather than npm.
