### ISSUE TITLE
[Bug] release.config.js not found by default 22.0.9

### ISSUE THREAD

**Issue by askidelskiy** [semantic-release/semantic-release#3089]
### Current behavior

https://github.com/semantic-release/semantic-release/pull/3072 Introduces the following breaking change:

`Meta config files (i.e. config.js and similar) are not looked for in the current working directory anymore. Instead, it looks in the .config subfolder.`

Therefore `release.config.js` in the working directory is not picked up, breaking release flow for all repositories that didn't store their configs in `.config` or specified the config location

### Expected behavior

Attempt to fetch config files from working directory so that existing users have time to switch to using `.config` folder. Or another workaround that would enable using currently existing config files without restructuring repositories.

### `semantic-release` version

22.0.9

### CI environment

GHA

### Plugins used

`git`
`github`
`changelog`

### `semantic-release` configuration

```JavaScript
module.exports = {
    "branches": [
        {name: "main"},
        {name: 'qa', prerelease: true},
        {name: 'internal', prerelease: true}
    ],
    ...
}
```

### CI logs

```
code: 'ERELEASEBRANCHES',
      details: 'A minimum of 1 and a maximum of 3 release branches are required in the [branches configuration](https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#branches).\n' +
        '\n' +
        'This may occur if your repository does not have a release branch, such as `master`.\n' +
        '\n' +
        'Your configuration for the problematic branches is `[]`.',
```

**Comment by travi** [comment]
thanks for reporting!

> #3072 Introduces the following breaking change:
> 
> `Meta config files (i.e. config.js and similar) are not looked for in the current working directory anymore. Instead, it looks in the .config subfolder.`

i read that in the release notes of v9 of cosmiconfig, but misinterpreted it to only apply specifically to use of a `.config.js` file and didnt think it would apply to a `release.config.js` file. 

since it is indeed a breaking change for our users, the upgrade has been reverted in https://github.com/semantic-release/semantic-release/releases/tag/v22.0.10. we will be upgrading to that version, but it will be released as a major version to account for the breaking change.

**Comment by gr2m** [comment]
so sorry I accidentally reverted the revert, I'm gonna .. revert
