### ISSUE TITLE
Semantic release latest version required Node JS 18.17.0 but documentation still says 18.0.0.

### ISSUE THREAD

**Issue by hpe-ykoehler** [semantic-release/semantic-release#3106]
### Current behavior

documentation says requirement is NodeJS 18
https://semantic-release.gitbook.io/semantic-release/support/node-version

### Expected behavior

documentation to say NodeJS 20 is not the requirement

### `semantic-release` version

22.0.12

### CI environment

linux

### `semantic-release` configuration

no need

### CI logs

no log

**Comment by travi** [comment]
What are you referring to as "new tool"? Are you seeing an error from semantic-release?

**Comment by hpe-ykoehler** [comment]
Sorry, bad wording, when I try to install semantic-release on NodeJS 18 installation I now get the following:

```
[Pipeline] sh
22:01:10  + semantic-release
22:01:11  [semantic-release]: node version ^18.17 || >=20.6.1 is required. Found v18.16.0.
22:01:11  
22:01:11  See https://github.com/semantic-release/semantic-release/blob/master/docs/support/node-version.md for more details and solutions.
[Pipeline] }
```

... ha, after re-reading the error msg, I now realize my mistake, it is 18.6 that was no more supported, not 18 itself.

**Comment by hpe-ykoehler** [comment]
Reopening because the documentation says:
```
semantic-release is written using the latest [ECMAScript 2017](https://www.ecma-international.org/publications/standards/Ecma-262.htm) features, without transpilation which requires Node version 18.0.0 or higher.
```

**Comment by travi** [comment]
Ah, sure. Would you be willing to send a PR to update that detail in the docs?

**Comment by hpe-ykoehler** [comment]
Yes, I may be able to find the time to do this, unclear when, will try to find time.

**Comment by travi** [comment]
we'll be releasing a new major version soon that raises the minimum requirement further. i've updated this detail in the docs to align with that, so no need to update in the short term with the current requirement. 

i'm going to close this issue as resolved, pending that being promoted. thank you for the reminder about getting this back in sync with current requirements

**Comment by hpe-ykoehler** [comment]
ok make sense.
