### ISSUE TITLE
Docs: Wrong redirect by clicking [Getting-started]

### ISSUE THREAD

**Issue by viniciusteixeiradias** [semantic-release/semantic-release#3114]
### Current behavior

When clicking "Getting Started" in the following [link](https://semantic-release.gitbook.io/semantic-release/#documentation), the user is redirected to [here](https://github.com/semantic-release/semantic-release/blob/master/docs/usage/getting-started.md#getting-started), but I believe the correct redirect would be [this](https://semantic-release.gitbook.io/semantic-release/usage/getting-started).

### Expected behavior

When clicking on "Getting Started" redirect to: [this link](https://semantic-release.gitbook.io/semantic-release/usage/getting-started)

### `semantic-release` version

master

### CI environment

N/A

### `semantic-release` configuration

.

### CI logs

.

**Comment by travi** [comment]
should be fixed now. thanks for the report!
