### ISSUE TITLE
straddling multiple CI providers / test suites (e.g. Travis + AppVeyor) ?

### ISSUE THREAD

**Issue by jokeyrhyme** [semantic-release/semantic-release#319]
For many of our projects we need to verify that code executes as expected in both Windows (on AppVeyor) and macOS / Linux (on Travis). There are other build-systems, too, beyond these 2 CIs that merit consideration.

semantic-release so far seems like it deals with the case of using a single CI extremely well, which is very exciting.

I'm curious about how we might go about integrating multiple test suites across multiple CI providers?

Some examples:
- Travis pass + AppVeyor fail = no release
- Travis fail + AppVeyor pass = no release
- Travis pass + AppVeyor pass = release, go go go!

**Comment by terales** [comment]
You can check [GitHub statuses](https://developer.github.com/v3/repos/statuses/) of commits and run release on the last build if all other checks are already passed.

**Comment by destroyerofbuilds** [comment]
This is a case where moving `semantic-release` out of the CI and into a GitHub App (as proposed by @gr2m ) may be the way to go (Would allow `semantic-release` to observe all CIs, and wait until all CIs report pass on the `master` branch commit)

**Comment by gr2m** [comment]
> This is a case where moving semantic-release out of the CI and into a GitHub App (as proposed by @gr2m ) may be the way to go

just to clarify, I don't plan to replace the current `semantic-release` CLI tool with a GitHub app, it will just be another option, the two might even work together

**Comment by destroyerofbuilds** [comment]
> just to clarify, I don't plan to replace the current semantic-release CLI tool with a GitHub app, it will just be another option, the two might even work together

I think it would be kind of cool to see `semantic-release` evolve over time into something that could be executed within a CI, or independently, such as in a cron job, or as a service for a GitHub App.

Inspiration comes from how `renovate` is both a CLI tool **and** used to power a GitHub app.

**Comment by pvdlg** [comment]
Let's continue the discussion in #585

**Comment by Almenon** [comment]
I ran into the exact same issue - [arepl-backend](https://github.com/almenon/arepl-backend) has two CI's: travis and appveyor (travis for python and appveyor for node)

For now I'll just try enabling it on travis.
