### ISSUE TITLE
support for LTS, multiple majors, or service patches?

### ISSUE THREAD

**Issue by cdaringe** [semantic-release/semantic-release#320]
hi all:

are there mechanisms to support LTS versions or service patches with semantic-release?  the docs say "no you can't release a specific version--that's the point", which is all fine and good, but we need to be able to support multiple versions.

any solutions?

thanks!

**Comment by cdaringe** [comment]
even if's unofficial, does anyone else in the community have a strategy for this?

**Comment by boennemann** [comment]
Hey @cdaringe,

this is totally possible and here is how: https://gist.github.com/boennemann/54042374e49c7ade8910

Thanks,
Stephan
