### ISSUE TITLE
Fetch branches in parallel

### ISSUE THREAD

**Issue by spencer-shupe-qhr** [semantic-release/semantic-release#3241]
### New feature motivation

Semantic Release fetches necessary branches in serial. This can take quite a while if you have many branches that match your release configuration. For example, a large repository that configures `"branches": ["main", { "name": *, "prerelease": true }]` can see the setup of semantic release take multiple minutes. Managing stale branches is a reasonable work around in many cases once this is discovered.

### New feature description

Request branches in parallel. Batch them if necessary to avoid too many concurrent requests.

### New feature implementation

Replace https://github.com/semantic-release/semantic-release/blob/master/lib/branches/index.js#L20C9-L20C20 with a map, for example https://github.com/sindresorhus/p-map

I expect this would have already been done if it is as easy as it sound. On the off chance it is as easy as it sounds I would be interested in contributing.

**Comment by travi** [comment]
the intended use of pre-release branches is for them to be rare and infrequent. matching that many branches as pre-releases is outside of the intended use of that workflow and unlikely to be high enough priority to get investment from our team any time soon. 

> Managing stale branches is a reasonable work around

if you choose to continue matching that many branches, i think this is your best option. you can even configure your repository to remove branches automatically after merging
