### ISSUE TITLE
Screwed up my semver repo, how to fix it? (validation failed)

### ISSUE THREAD

**Issue by PatrickHeneise** [semantic-release/semantic-release#328]
```
semantic-release ERR! post Failed to publish release notes. { [Error: {"message":"Validation Failed","errors":[{"resource":"Release","code":"custom","field":"tag_name","message":"tag_name is not a valid tag"},{"resource":"Release","code":"custom","message":"Published releases must have a valid tag"},{"resource":"Release","code":"invalid","field":"target_commitish"}],"documentation_url":"https://developer.github.com/v3/repos/releases/#create-a-release"}]
semantic-release ERR! post   message: '{"message":"Validation Failed","errors":[{"resource":"Release","code":"custom","field":"tag_name","message":"tag_name is not a valid tag"},{"resource":"Release","code":"custom","message":"Published releases must have a valid tag"},{"resource":"Release","code":"invalid","field":"target_commitish"}],"documentation_url":"https://developer.github.com/v3/repos/releases/#create-a-release"}',
semantic-release ERR! post   code: 422 }
```

I had some issues with the master branch and semantic-release told me to revert back to a certain commit, I tried that, but that one didn't successfully build, so I created a new release/tag myself and got to this new error. Any ideas/suggestions on how to fix this issue? The release/tag I created manually follows the semver pattern, so I don't see why I get a validation error.

**Comment by PatrickHeneise** [comment]
Any hints where to start debugging this?

**Comment by MoeSattler** [comment]
Regarding the initial issue:
Looks like at some point Semantic-Release didn't find the commit corresponding to the last release. 
Did you force push or roll back at some point ? 

You say you created a release/tag, did you also publish to npm? 
Make sure your tag has the `v` as in  `v1.2.3` and not `1.2.3`. 

Usually the only way to recover from those issues is to publish to npm manually to have a new anchor point.

**Comment by PatrickHeneise** [comment]
I am currently publishing manually, which is a PITA. I removed all releases and tags from GitHub, but it seems npm is holding some information about the releases in the cache as well.

And yes, I did roll back / force push at some point, but don't remember where.

**Comment by travi** [comment]
i ended up seeing this error in one of my repos, but was able to resolve it. see more detail in #199

**Comment by PatrickHeneise** [comment]
I wish it would just be a wrong `repository` attribute in package.json, but it's not that :(
