### ISSUE TITLE
 Update file extensions to include .mjs on configuration docs page

### ISSUE THREAD

**Issue by dustin-ruetz** [semantic-release/semantic-release#3323]
## Problem Description

- The https://semantic-release.gitbook.io/semantic-release/usage/configuration#configuration-file documentation mentions using the `.js` and `.cjs` file extensions for the semantic-release configuration file, but there's no mention of the `.mjs` file extension.
- ES Module syntax is the future of JavaScript and has been both standardized and widespread for quite awhile now, so it'd be great to clearly communicate to users that semantic-release supports it.

## Problem Screenshot

<img width="1244" alt="Screenshot of https://semantic-release.gitbook.io/semantic-release/usage/configuration#configuration-file showing how docs page is missing the .mjs file extension" src="https://github.com/semantic-release/semantic-release/assets/26169612/e5645008-a34a-4d34-90fd-0f69c089eb63">

## Suggested Solution

- My local testing indicates that semantic-release knows how to interpret `.mjs` config files, both in the auto-detected repo root location as well as a custom path passed to the `--extends` flag via the CLI command.
- Given that semantic-release can already use `.mjs` files, in my opinion the best course of action would be to update this section of the documentation in three places:
  1. Mention that the `.releaserc` file can have an optional `.mjs` extension.
  2. Mention that the `release.config` file can have an `.mjs` extension.
  3. Include a `release.config.mjs` example code snippet demonstrating the `export default {}` ES Module syntax.

## Pull Request

https://github.com/semantic-release/semantic-release/pull/3322

**Comment by travi** [comment]
i think it is ok to include this update since it is true that it is missing. however, since it isnt semantic-release that directly chooses the valid extensions, i think it would be even more appropriate to link to the [cosmiconfig docs](https://www.npmjs.com/package/cosmiconfig) since that is what we leverage under the covers and actually determines the supported formats
