### ISSUE TITLE
why is release name set from commit message?

### ISSUE THREAD

**Issue by gr2m** [semantic-release/semantic-release#34]
see https://github.com/gr2m/moment.parseFormat/releases/tag/v1.0.0

"v1.0.0: chore: follow semver" should just be "v1.0.0". Is this a bug or by design?

**Comment by boennemann** [comment]
To be honest I haven't figured this one out yet. It's the very same request every time and sometimes GH includes the commit message, sometimes not :/

What would you preferred title look like?

**Comment by gr2m** [comment]
just v1.0.0 :) Details are in the release body

**Comment by boennemann** [comment]
This is now set explicitly https://github.com/semantic-release/semantic-release/blob/next/src/post.js#L28
