### ISSUE TITLE
Generate historical release notes

### ISSUE THREAD

**Issue by MatthewJohn** [semantic-release/semantic-release#3409]
### New feature motivation

I realise, this might be geared towards the release-notes-generator, but also presume that it wouldn't be possible without some changes to semantic-release, but..
If a project moves to semantic-release and has historic commits that follow the correct formatting and has previous tags, it would be great if the release notes file could be completely generated from scratch, including the releases that had not been generated with semantic-release.

### New feature description

I'm not entirely certain of the functional changes that would need to be made, but some way to regenerate the whole release notes file (perhaps with a given flag).
This would analyse all previous tags and commit messages and update the release notes with this content.

**Comment by travi** [comment]
We do not have plans to add this functionality directly to semantic-release, but you should be able to get close if you look into conventional-changelog
