### ISSUE TITLE
The FAQ url provided is wrong

### ISSUE THREAD

**Issue by Dun-sin** [semantic-release/semantic-release#3413]
### Current behavior

![image](https://github.com/user-attachments/assets/ca4a78bb-cb51-4495-b323-46c13de31626)

### Expected behavior

Should lead to this instead -> https://github.com/semantic-release/semantic-release/blob/master/docs/support/FAQ.md

### `semantic-release` version

"^24.0.0"

### CI environment

GitHub Action

### `semantic-release` configuration

![image](https://github.com/user-attachments/assets/2318a30b-591e-4137-aae8-f64fa32990a1)

### CI logs

nil

**Comment by travi** [comment]
could you provide more detail about where the incorrect link is located? please feel free to suggest a change directly by opening a PR

**Comment by Dun-sin** [comment]
> could you provide more detail about where the incorrect link is located? please feel free to suggest a change directly by opening a PR

Got it will open a PR, but basically the bot creates an issue when a job fails on github with suggestions of what you could do to fix them and it has a FAQ, link in there which is what's wrong

**Comment by travi** [comment]
> basically the bot creates an issue when a job fails on github with suggestions of what you could do to fix them and it has a FAQ

ah, i follow now. in that case, the links that need to be updated should be located here: https://github.com/semantic-release/github/blob/7f079f7567f0dcbd7d3a98b415de5a29b0520d40/lib/get-fail-comment.js#L2-L4

**Comment by Dun-sin** [comment]
> > basically the bot creates an issue when a job fails on github with suggestions of what you could do to fix them and it has a FAQ
> 
> ah, i follow now. in that case, the links that need to be updated should be located here: https://github.com/semantic-release/github/blob/7f079f7567f0dcbd7d3a98b415de5a29b0520d40/lib/get-fail-comment.js#L2-L4

Awesome, thanks for the info, super helpful. Will be raising a PR now😁
