### ISSUE TITLE
Add support for starting from version 0.y.z in the configuration

### ISSUE THREAD

**Issue by DrSAS** [semantic-release/semantic-release#3435]
### New feature motivation

Hello,

I’m currently working on a project and exploring the possibility of starting our versioning from `0.y.z` instead of jumping straight to `1.0.0`. To the best of my knowledge, semantic-release doesn’t currently offer an option to begin versioning from `0.y.z` through its configuration.

I believe this feature could be quite valuable for projects that are still in the early stages of development, where starting at `1.0.0` might not be the most appropriate. Adding this flexibility could better accommodate different development scenarios and make semantic-release even more versatile.

https://semver.org/spec/v2.0.0.html#how-should-i-deal-with-revisions-in-the-0yz-initial-development-phase

Thank you!

### New feature description

A new line in the config file, like `initialVersion`, when `0.x.y` may be setted and applied.

**Comment by travi** [comment]
it is intentional that we do not support pre-v1.0.0 versions. we recommend use of pre-releases instead: https://semantic-release.gitbook.io/semantic-release/support/faq#can-i-set-the-initial-release-version-of-my-package-to-0.0.1
