### ISSUE TITLE
This test run was triggered by a pull request... so cant release

### ISSUE THREAD

**Issue by jakelacey2012** [semantic-release/semantic-release#346]
Basically I do :) 

Awesome project btw.

Basically I think there should be an option to enable this... However not as a normal release but as a release candidate, do we think this is possible? ..I would love to contribute just point me in the right direction :)

**Comment by morten-kirstein** [comment]
I'm getting the same error. So I'm interested in this as well :)

**Comment by codekiln** [comment]
The docs could be a lot clearer on this point. I'm new to `semantic-release` and from everything I've read I'm getting the sense that people who are using it are manually merging pull requests locally into master on their own computer and then using a push to master to do the release via the cli. 

There must be something I'm missing, but I can't find contrary evidence to that so far.

**Comment by gr2m** [comment]
> Basically I think there should be an option to enable this... However not as a normal release but as a release candidate, do we think this is possible?

Yes that is possible :) 

1. What you want to do is create a branch like `rc`.
2. In the package.json file, add a `"publishConfig"` key, and set it to `"publishConfig": {"tag": "rc"}`. See [publishConfig docs](https://docs.npmjs.com/files/package.json#publishconfig) for more options
3. Merge all pull requests you want to release into that branch.

For example, `semantic-release` itself releases with a `next` tag by default, and only after we tested the `@next` release on some repositories, we set the version to `@latest`: https://github.com/semantic-release/semantic-release/blob/42456a32b316c2879fc667323817c4cf11ee8e90/package.json#L73-L75

@codekiln We don’t merge locally ever, the main benefit of semantic-release is that we can just merge pull requests and the release happens automatically. Does my comment above help you? We are always happy for any help we can get to improve the documentation, you have a much better perspective on it than us who know semantic-release inside out :)

**Comment by pvdlg** [comment]
Release from a PR is not possible as it require to have access to the various authorization token (`GH_TOKEN`, `NPM_TOKEN`). Environment variable [are not available for build triggered by a PR from a forked repository](https://docs.travis-ci.com/user/environment-variables/#Defining-encrypted-variables-in-.travis.yml).

Please see #563 for a proposal regarding pre-release and dist-tags. Feedback welcome over there!
