### ISSUE TITLE
verifyConditions to release without CI

### ISSUE THREAD

**Issue by andresmijares** [semantic-release/semantic-release#350]
I having some delay which setting the C.I process in place, also, I using a private repo, I wonder if there is a verifyConditions plugin to exec semantic release from my terminal and make a release without passing through a C.I Process.

Any ideas?

**Comment by kumarharsh** [comment]
I think the devs have mentioned something regarding that here: https://github.com/semantic-release/semantic-release#can-i-run-this-on-my-own-machine-rather-than-on-a-ci-server

**Comment by jeongsd** [comment]
how can i use https://github.com/semantic-release/semantic-release#can-i-run-this-on-my-own-machine-rather-than-on-a-ci-server ?

package.json
```json
"scripts": {
  "semantic-release": "semantic-release pre&& npm publish && semantic-release post"
},
"devDependencies": {
  "semantic-release": "^6.3.2"
},
"release": {
  "debug": false
}
```

result
```sh
semantic-release ERR! pre semantic-release didn’t run on Travis CI and therefore a new version won’t be published.
semantic-release ERR! pre You can customize this behavior using "verifyConditions" plugins: git.io/sr-plugins
```

**Comment by ankur-birdeye** [comment]
Hey team, I am also facing the same issue. Can anyone help here
