### ISSUE TITLE
data['dist-tags'][npm.tag] - Cannot read property 'latest' of undefined

### ISSUE THREAD

**Issue by Sly777** [semantic-release/semantic-release#352]
Hey all,

github: https://github.com/Sly777/React-UI-Debugger
travis CI: https://travis-ci.org/Sly777/React-UI-Debugger
semantic-release: ^6.3.2

basically i'm trying to publish package as first release to public by using semantic-release & travis CI but it doesn't work. I'm getting these errors below.

it's giving error on travis CI
```
/home/travis/build/Sly777/React-UI-Debugger/node_modules/@semantic-release/last-release-npm/dist/index.js:29
    var version = data['dist-tags'][npm.tag];
                                   ^
TypeError: Cannot read property 'latest' of undefined
```

after i got this error, i tried to run "npm dist-tag ls" on local but that time i got error like this 

```
npm ERR! dist-tag ls Couldn't get dist-tag data for react-ui-debugger
npm ERR! Darwin 16.3.0
npm ERR! argv "/Users/xxxx/.nvm/versions/node/v6.9.1/bin/node" "/Users/xxxx/.nvm/versions/node/v6.9.1/bin/npm" "dist-tag" "ls"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code E403

npm ERR! Registry returned 403 for GET on https://registry.npmjs.org/-/package/react-ui-debugger/dist-tags
npm ERR!
```

package.json
```
{
  "name": "react-ui-debugger",
  "version": "0.0.0-development"
}
```

Also i pushed "latest" tag on github. 

What's your opinion? What do you suggest?

**Comment by kumarharsh** [comment]
When I ran this:
```
npm dist-tag ls react-ui-debugger
```

and I got a response:
```
npm http request GET https://registry.npmjs.org/-/package/react-ui-debugger/dist-tags
npm http 200 https://registry.npmjs.org/-/package/react-ui-debugger/dist-tags
latest: 0.0.4
```

**edit**: Looking at the log output in your case, NPM is giving a 403 response, which means that maybe your npm is not correctly setup?

**Comment by meszaros-lajos-gyorgy** [comment]
I have the same for my repo here: https://github.com/meszaros-lajos-gyorgy/workspace
Interestingly it works fine on my other branches, for example: https://github.com/meszaros-lajos-gyorgy/split-article

I have tried re-creating the repo 3 times now with no success.

I have semantic-release-cli and commitizen installed globally and I first run this:

`semantic-release-cli setup`

which produced no errors. Then I run:

`commitizen init cz-conventional-changelog --save-dev --save-exact`

also without any issues. But travis is not creating a release, nor any tags.

Have I missed to setup something?

**Comment by meszaros-lajos-gyorgy** [comment]
Is it possible, that a package with the same name (workspace) was once owned by someone else?

https://registry.npmjs.org/workspace

According to the received json, the package has been unpublished, so npm says, I'm good to go with claiming: https://www.npmjs.com/package/workspace

Can you guys confirm @Sly777's solution at https://stackoverflow.com/a/41700557/1806628 ?

Note: on my other components I didn't have to do that to make the code work.

**Comment by meszaros-lajos-gyorgy** [comment]
I created a new repo and double checked the availability against npm registry. I also didn't enable the repo in travis, I simply let the semantic-release-cli to set it up. My repo contained the same code, that I linked in my previous comment and it worked without any problem, even when using commitizen from the start.

**Comment by pvdlg** [comment]
A lot of new version of `semantic-release` have been released since this issue has been opened.
Could you confirm if it's still happening with the last version of `semantic-release` ?

**Comment by pvdlg** [comment]
Closing due to lack of response. Please re-open if the problem is still happening
