### ISSUE TITLE
support bun runtime

### ISSUE THREAD

**Issue by ianzone** [semantic-release/semantic-release#3527]
### New feature motivation

It happens that some projects are using [setup-bun action](https://github.com/oven-sh/setup-bun), and prefer not to add another `actions/setup-node`

### New feature description

detect `engines.bun` in `package.json` and use `bun` as runtime.

**Comment by travi** [comment]
Semantic-release works for many package managers and it would be unrealistic for us to support the associated runtimes for each of them in addition to node. Your release step should probably be a separate job anyway, so you can limit your use of setup-node to that job
