### ISSUE TITLE
Support dry run on publish, regardless of branch?

### ISSUE THREAD

**Issue by AlmaasAre** [semantic-release/semantic-release#356]
would be nice to have something like `npm run semantic-release --dry-run` which could be run in the CI to see what version would be published, and if everything's set up correctly

**Comment by marcbachmann** [comment]
`semantic-release pre --debug=true` shows information about the setup and the version
 
```
$ semantic-release pre --debug=true
semantic-release WARN pre semantic-release didn’t run on Travis CI and therefore a new version won’t be published.
semantic-release WARN pre You can customize this behavior using "verifyConditions" plugins: git.io/sr-plugins
semantic-release ERR! pre Determined version 12.2.0 as "latest". Not publishing in debug mode.
```

Maybe we can do a small change to that script so the version gets logged to stdout.
```
$  semantic-release pre --debug 2> /dev/null
{"type": "minor", "version": "12.2.0"}
```

Warnings should go to `stderr` and the json to `stdout`.
An additional command which is more explicit would be even better.
