### ISSUE TITLE
Support branch specific releases

### ISSUE THREAD

**Issue by thekalinga** [semantic-release/semantic-release#360]
Currently semantic release only supports one release per repository.

But the problem with approach is that developing plugins for frameworks like angular thats compatible with multiple major releases forces plugin authors to use one repository per version.

i.e if an angular plugin needs to support angular 2, angular 4 & angular 5, the plugin author needs to maintain multiple repositories tho most of the code across all these repositories would remain the same.

Since all changes within a major version are guaranteed not to have any breaking changes, the plugin author can chose to use a single repo & create one branch per version, but a different published artifact name.

An example setup
--
> Assuming that latest version of `Angular` is `v5`

A single `ngx-cool-plugin` repo can have three branches.

1. `master` (compatible with latest version of `Angular 5`)
2. `ng4` (compatible with latest version of `Angular 4`)
3. `ng2` (compatible with latest version of `Angular 2`)

As part of the build, each branch would create a npm artifact whose is of this format `ng{version number}-cool-plugin` thats compatible with the latest release within the major release of angular.

Eg., `ng2` branch artifact would be named `ng2-cool-plugin` and is compatible with the latest release of Angular2. Similarly, `ng4` branch artifact would be named `ng4-cool-plugin`

`master` branch will create a npm artifact whose name is `ng5-cool-plugin` thats compatible with the latest version of Angular, which is `Angular 5`

This kind of workflow will make most of the plugin authors life really simple & have a single repository where they deal with all the problems with a single plugin

**Comment by boennemann** [comment]
Hey @thekalinga,

thanks for opening this issue. I'm happy to tell you that this use case is entirely covered by semantic-release.

This gist (also linked in the README) contains the steps required to set it up: https://gist.github.com/boennemann/54042374e49c7ade8910

Best,
Stephan

**Comment by thekalinga** [comment]
@boennemann What you mentioned assumes that there is no version conflict.

But in my case `ng2-cool-plugin` & `ng4-cool-plugin` can have their own versions

**Comment by thekalinga** [comment]
@boennemann Is this still an issue that's already addressed/should this issue be re-opened?

**Comment by thekalinga** [comment]
@boennemann Would you mind answering the query plz

**Comment by Nargonath** [comment]
@thekalinga I don't think than your current use case work with the aforementioned gist example. It seems to allow only minor and fix semver bumps.
