### ISSUE TITLE
should "perf" commits trigger a bugfix release?

### ISSUE THREAD

**Issue by jedwards1211** [semantic-release/semantic-release#370]
I don't see evidence that this has been discussed elsewhere...

Typically I want perf commits to trigger a bugfix release because they are a significant improvement but don't add new API or breaking changes.

However, unlike bug fixes, they don't alter behavior, excluding performance.

But this is where conventional changelog gets ambiguous.  A performance improvement can be considered a bug fix if performance is so bad as to be a bug.  It can be considered refactoring if it's not that significant.  It can be considered a feature if it enables usage that was previously unfeasible.

In retrospect, I would rather just decorate my commit messages with `[major]`, `[minor]`, or `[bugfix]`, and have `semantic-release` respond to those tags, rather than `feat`, `fix`, and `BREAKING CHANGE`...

**Comment by vanduynslagerp** [comment]
The releases rules are now completely customizeable: see [commit-analyzer#release-rules](https://github.com/semantic-release/commit-analyzer#release-rules)

In addition the `perf` commit now trigger a `patch` release in accordance with the last angular conventions.
