### ISSUE TITLE
GitHub Enterprise: Could Not Access GitHub Repository

### ISSUE THREAD

**Issue by Snugug** [semantic-release/semantic-release#375]
In my `package.json`, I have the following configuration:

```json
"release": {
    "githubUrl": "<host>",
    "githubApiPathPrefix": "/api/v3/"
  }
```

This should map to the options for using GitHub Enterprise. Our GHE instance requires authentication using SSH. I've added a `GH_TOKEN`, but am getting "Bad Credentials" when attempting to run `semantic-release` from my CI.

With this same setup, attempting to run `semantic-release-cli` I'm getting "Could Not Access GitHub Repository" so I'm assuming it's something to do with not actually picking up my GHE URLs and API prefix.

**Comment by CapitanRedBeard** [comment]
@Snugug, I'm facing the same problem. Have you found a work around or should I start looking into working on a PR? Thanks!

**Comment by jlengstorf** [comment]
For `semantic-release-cli`, I found an [option in the source code](https://github.com/semantic-release/cli/blob/master/src/lib/github.js#L73) (`--ghepurl`) that lets you specify the GHE URL:

```sh
semantic-release-cli setup --gh-token=<GH_TOKEN> --npm-token=<NPM_TOKEN> --ghepurl=<GHE_API_URL>
```

Not sure about the `package.json` part, unfortunately.

**Comment by jlengstorf** [comment]
@Snugug @CapitanRedBeard I chased this down further and isolated the `condition-travis` repo as the culprit: public Travis and GitHub endpoints are hard-coded.

I created an enterprise-friendly version here: https://github.com/jlengstorf/condition-travis-enterprise

**Caveat: this only works for single-run Travis builds. If you're running in a matrix, this will most likely cause issues for you.**
