### ISSUE TITLE
[package-name]@next

### ISSUE THREAD

**Issue by crobinson42** [semantic-release/semantic-release#381]
I'm trying to understand the correct flow for publishing a @next (or any other tag name), I currently feel I'm doing something wrong as I just had a package published to v0.0.0 when attempting to use the tag name @next.

The "lastest" package has been published from `master` branch and that should persist. I pulled another branch, `develop`, and wish to publish that branch on the `[package-name]@next` tag to the npm registry. Here's what I did the `develop` branch `package.json`

package.json
```json
{
...
  "publishConfig": {"tag": "next"},
  "release": {
    "branch": "develop"
  },
...
}
```

What I got was a `[package-name]@0.0.0` published with a reference from the `@next` tag pointing to `v0.0.0`?

```
$ npm view event-sky

{ name: 'my-package',
  description: '...',
  'dist-tags': { latest: '0.1.4', next: '0.0.0' },
  versions:
   [ '0.0.0-development',
     '0.0.0',
     '0.1.0',
     '0.1.1',
     '0.1.2',
     '0.1.3',
     '0.1.4' ],
.....
```

**Comment by nanovazquez** [comment]
Hey @crobinson42. In each branch, you need to configure:

* The tag you want to use in the `publishConfig` field.
* The branch target in the `release` field (otherwise _semantic-release_ won't publish in the branch)
* The `npm publish` script with the tag you set in the `publishConfig` field.

In your case:

### master branch

**package.json**
```js
{
  ...
  "scripts": {
    ...
    "semantic-release": "semantic-release pre && npm publish --tag=stable && semantic-release post"
  },
  "release": {
    "branch": "master"
  },
  "publishConfig": {
    "tag": "stable"
  },
  ...
}
```

### develop branch

**package.json**
```js
{
  ...
  "scripts": {
    ...
    "semantic-release": "semantic-release pre && npm publish --tag=next && semantic-release post"
  },
  "release": {
    "branch": "develop"
  },
  "publishConfig": {
    "tag": "next"
  },
  ...
}
```

Hope it helps.

**Comment by crobinson42** [comment]
@nanovazquez Thank you, that helps a lot!

**Comment by jbcpollak** [comment]
how do you do this without having to modify package.json each time you merge from develop to master? Is there a way to specify the release and publishConfig parameters from the commandline?

**Comment by SpikeO** [comment]
@jbcpollak it seems that you can add parameters in the CLI https://semantic-release.gitbooks.io/semantic-release/content/docs/usage/configuration.html#configuration

**Comment by mvpspl619** [comment]
@SpikeO @jbcpollak Unfortunately, the docs says that the plugin options cannot be passed via CLI. So I'm not sure if it's possible to pass `publishConfig` args to CLI
> Note: Plugin options cannot be defined via CLI arguments and must be defined in the configuration file.

https://semantic-release.gitbooks.io/semantic-release/content/docs/usage/configuration.html#configuration

**Comment by Thatkookooguy** [comment]
I created an npm library to update semantic-release package.json fields **before** semantic-release runs on travis.

If anyone wants to use it, it should solve this problem: https://www.npmjs.com/package/@kibibit/branch-it
