### ISSUE TITLE
how to use semantic-release with multiple node versions

### ISSUE THREAD

**Issue by cyberhck** [semantic-release/semantic-release#384]
let's say I'm testing against multiple versions of nodejs, so that'll mean `after_success` hook will be called multiple times, what is the proper way of using `semantic-release` in this case?

**Comment by hbetts** [comment]
@cyberhck you may want to look at bahmutov/ci-publish#2 for a possible solution.

**Comment by bahmutov** [comment]
The easiest way to control this is to use plugin https://github.com/bahmutov/condition-node-version

**Comment by cyberhck** [comment]
Looks like we don't need any of those after all, semantic release already uses deploy_once and it waits for all the builds to pass before releasing a version. We can just use as it is, everything will work fine.

I think it's best to close this issue now.
