### ISSUE TITLE
optimization: if you update the readme, it does a patch bump on NPM 

### ISSUE THREAD

**Issue by faceyspacey** [semantic-release/semantic-release#392]
## Motivation:

currently you have to do a fake `fix` commit just to update documentation on NPM. There needs to be a better solution for this. My idea is simply if the readme is updated, do a patch bump an publish to NPM.

**Comment by faceyspacey** [comment]
or perhaps just an option called `bump` that lets you force re-publishing whenever you need.

**Comment by vanduynslagerp** [comment]
The releases rules are now completely customizeable: see [commit-analyzer#release-rules](https://github.com/semantic-release/commit-analyzer#release-rules)

Here is a config that would trigger a `patch` release for commits that starts with `docs(readme)`:
```json
{
  "release": {
    "analyzeCommits": {
      "preset": "angular",
      "releaseRules": [
        {type: 'docs', scope: 'readme', release: 'patch'}
      ]
    }
  }
}
```
Feel free to re-open if you can't configure it the way you want.
