### ISSUE TITLE
Cannot write multiple scopes

### ISSUE THREAD

**Issue by LeonardoGentile** [semantic-release/semantic-release#396]
I'm not sure if this is by design (the definition of semantic releases commits messages).
I've tried to write a commit header like this: 
`feat(scope1, scope2): message whatever`
That made the the release failed: ENOCHANGE.

After some debugging it appears that the underlaying `conventional-commits-parser/index.js` (line 9) uses this regex: `/^(\w*)(?:\(([\w\$\.\-\* ]*)\))?\: (.*)$/` to match the type, scope and message.

But that regex did not match with my header so the parser could not get the commit type => fail.

I know this is not strictly related with semantic release but with one of its dependencies but shouldn't this be a configuration option? 

If this is already please feel free to close this issue.

**Comment by vanduynslagerp** [comment]
In the current version the default[commit-analyzer](https://github.com/semantic-release/commit-analyzer) uses the default configuration of `conventional-changelog`.

You can use [sr-commit-analyzer](https://github.com/vanduynslagerp/sr-commit-analyzer) and [sr-release-notes-generator](https://github.com/vanduynslagerp/sr-release-notes-generator) that allow you to customize the parser options.

We are working on making those 2 plugins the default ones, but it's not completely done yet.
Currently you can use those 2 plugins by following the documentation in their readme (basically installing the plugins and adding the configuration in your `package.json`).

**Comment by vanduynslagerp** [comment]
Those two plugins are now the default ones. You can now customize the parser regex.
Feel free to re-open if that doesn't fit your needs.
