### ISSUE TITLE
add `[verification skip]` commit message command

### ISSUE THREAD

**Issue by christophwitzko** [semantic-release/semantic-release#40]

**Comment by ariporad** [comment]
I'll try this.

**Comment by ariporad** [comment]
Should having `[verification skip]` in a single commit be sufficient to prevent verification of the whole release (I could see this being a problem for things like the next branch, where there are hundreds of commits).

**Comment by pvdlg** [comment]
The `verifyRelease` step applies to the entire release and consist in verifying that the release type (`patch`, `minor`, `major`) corresponds to the content of the release.
The content of the release can be verified in many different ways: commits, changes in tests, changes in dependencies, changes in API etc...

I don't think a `[verification skip]` commit message make much sense as the `verifyRelease` step is not executed per commit but for the entire release.

What was the original goal of this feature request?

**Comment by pvdlg** [comment]
Closing per previous comment. Feel free to comment further if you disagree.
