### ISSUE TITLE
No tokens with TravisCI option

### ISSUE THREAD

**Issue by olstenlarck** [semantic-release/semantic-release#401]
Info:
- ArchLinux
- v6.3.6
- tested node versions: 4, 6, 8
- Travis Normal (not Pro, not Enterprise)

Seen only one issue with such problem, but his problem is understandable. Here is different.

I has all things around gnome keyring, has password for the keyring, cli setup flow had no problems, but it seems it doesn't upload the tokens to the Travis?

<details>
 <summary>Inappropriate image</summary>
  <img src="https://user-images.githubusercontent.com/5038030/28252368-361a702e-6a9a-11e7-9988-f3334c87e7c3.png">
</details>

<hr>

<img src="https://user-images.githubusercontent.com/5038030/28252369-36350f9c-6a9a-11e7-9294-cd79e78df95e.png">

**Comment by tunnckoCore** [comment]
The whole point that i may consider return back to using Travis is if really `semantic-release` do that thing automatically, otherwise i'll stay with CircleCI.

**Comment by tunnckoCore** [comment]
Manually added the tokens and again.

![2017-07-17-03 07 12_1280x1024_scrot](https://user-images.githubusercontent.com/5038030/28252517-17f8ae3c-6a9d-11e7-8eb4-077472bc86ab.png)

![2017-07-17-03 08 32_1280x1024_scrot](https://user-images.githubusercontent.com/5038030/28252518-17fbd648-6a9d-11e7-86fb-f4f94f011272.png)

**Comment by tunnckoCore** [comment]
Seems that v4.3.5 works, but only on node 4. On node 6 it fails to load `validate-npm-package-license` (which seems to exist in `normalize-package-data` which is used here)

**Comment by elricsfate** [comment]
Any update on getting this working with Travis @charlike ? I'd like to implement this in a client's environment on a private repo. 

Also if I'm not mistaken, shouldn't the token be implemented in Travis with secure environment variables? It's an option under settings. 

Does this package somehow handle that differently? 

@charlike

**Comment by pvdlg** [comment]
Closing as it seems to be a missing token issue and/or an npm/CI install with the CI config.

I you still experience the problem, please open a new issue, with the configuration step you went through, and a link to the cI build that failed.
