### ISSUE TITLE
Document test setup for scenario test

### ISSUE THREAD

**Issue by gr2m** [semantic-release/semantic-release#413]
Follow up for https://github.com/semantic-release/semantic-release/pull/408#issuecomment-322029479, ping @zetaron

The scenario tests need a local CouchDB to be in admin party mode (no admin user configured) and be accessible at port `15986`. I’m pretty sure that is the default port when running CouchDB with Docker. I’m no Docker expert though, if someone could give this a try, I’d appreciate it  <3

**Comment by zetaron** [comment]
According to the [docker hubs page on couchdb](https://hub.docker.com/_/couchdb/) the default port is: 5984

I'll see to test this on the coming weekend.

**Comment by zetaron** [comment]
Currently the registry start script either expects to either be run on Travis (if) or to have the `couchdb` binary installed on the host (else).
https://github.com/semantic-release/semantic-release/blob/12b35396d88d37de8000d7838b41de9f2b276f80/test/registry/start.sh#L10-L26

The `stop.sh` script also assumes that it is able to `kill` the started couchdb instance.
https://github.com/semantic-release/semantic-release/blob/12b35396d88d37de8000d7838b41de9f2b276f80/test/registry/stop.sh#L4-L11

It would be required to modify these two scripts to allow the use of docker for running couchdb.
Maybe it's an option to check for docker and if it's available use it to run the couchdb instance.

While trying to test the setup with docker, I was able to use the official couchdb image from the docker hub but then ran into timeout issues with the scenario tests.
I feel that I lack the knowledge to configure couchdb or to modify the current scenario setup, maybe someone who's a little more involved could take a look.

**Comment by gr2m** [comment]
Thanks for giving it a try! I’ll try to give it a look my self, it’s on my list of things I want to work on next for semantic-release

**Comment by pvdlg** [comment]
We could move to https://github.com/npm/npm-docker-couchdb. That would simplify our code and it would make it work on any OS. Currently we rely on a bash script to start couchdb, so it would work only on Mac OS and Linux.
That would also allow us to run our test on a Windows CI, which would quite nice to verify everything work as expected there.

**Comment by gr2m** [comment]
@pvdlg sounds great! 

@zetaron wanna give this a try?

**Comment by zetaron** [comment]
Will certainly do! Unfortunately we are so close to a deadline, that it'll take me some time to get to it.

On October 15, 2017 10:42:27 PM GMT+02:00, Gregor Martynus <notifications@github.com> wrote:
>@pvdlg sounds great! 
>
>@zetaron wanna give this a try? 
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/semantic-release/semantic-release/issues/413#issuecomment-336740058

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by gr2m** [comment]
no worries :) Good luck with the project. Shall we ping you again on some specific day?

**Comment by zetaron** [comment]
When I don't get to it within the next 14 days, it would be great if you could ping me :)

Thanks for the patience and pushing the project forward! I really appreciate it. 

On October 16, 2017 9:53:38 PM GMT+02:00, Gregor Martynus <notifications@github.com> wrote:
>no worries :) Good luck with the project. Shall we ping you again on
>some specific day? 
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/semantic-release/semantic-release/issues/413#issuecomment-337017072

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by pvdlg** [comment]
For information I added [mock-server](http://www.mock-server.com/) to the tests. And I use Docker to start it.
See [mockserver.js](https://github.com/semantic-release/semantic-release/blob/caribou/test/helpers/mockserver.js).

So we could do something similar for [npm-docker-couchdb](https://github.com/npm/npm-docker-couchdb).

In addition there is an authentication issue that would be great to solve:
Currently with https://github.com/npm/npm-registry-couchapp and the Docker version the only way to authenticate is with email / password (See [this](https://github.com/semantic-release/semantic-release/blob/caribou/src/lib/publish-npm.js#L21) code). While with the regular npm registry we authenticate with just a Token.

Ideally we should authenticate the same way with the local registry that it's done with the regular npm registry. I don't know how we can make [npm-registry-couchapp](https://github.com/npm/npm-registry-couchapp) to accept a token based authentication...So if you have an idea that would be awesome!

**Comment by zetaron** [comment]
@pvdlg might be a stupid question to ask but why does the code you reference care about modification of the `.npmrc` at all?
The important bit is the modification of the `package.json` and related files to use the new package version. 
I'd also assume most systems either already have a `.npmrc` or it would be easy to set up before running semantic-release.

Therefore I'd suggest to just remove the auth setup from code and add it to the tests setup code as an implementation detail cared for before running the actual integration suite. 

If there are compatibility concerns for current users I'd mark the feature as deprecated and still move the test specific email auth setup while leaving the NPM_TOKEN code. This should not change the current coverage (for this piece of code) as the production code is skipped in favor or the email auth setup which only gets run while testing and the actual production code stays untested.

**Comment by pvdlg** [comment]
> might be a stupid question to ask but why does the code you reference care about modification of the .npmrc at all?

Because this is the only way to make a release from a CI environment unfortunately.
`npm publish` doesn't support passing the authentication parameters as a parameter or with an environment variable. The only way is to set entry like `//<registry_url>/:_authToken=<token>`

In order to not display the token in the config of a repo we pass it via the CI environment variable and we write `//<registry_url>/:_authToken=${NPM_TOKEN}` in the `.npmrc`.  `npm` will replace `${NPM_TOKEN}` by the environment variable value at runtime.

> I'd also assume most systems either already have a .npmrc or it would be easy to set up before running semantic-release.

On a local machine yes. It's setup with `npm login`. On a CI no, the authentication will not be part of the `.npmrc` file. Having it would require to set it in the repo and therefore exposing the auth token to everyone.

> Therefore I'd suggest to just remove the auth setup from code and add it to the tests setup code as an implementation detail cared for before running the actual integration suite.

As mentioned above, updating or creating `.npmrc` with the auth information is mandatory to release from a CI environment. We want `semantic-release` to take care of that so a user just has to add the NPM_TOKEN environment variable to Travis (in the Settings UI). We don't want the user to have to run an additional command in the CI build to update the file.

**Comment by pvdlg** [comment]
All the integration tests runs on Docker now.
We should just document somewhere that contributor need install Docker on their machine to run the tests.
