### ISSUE TITLE
v7.0.2 is not published on NPM

### ISSUE THREAD

**Issue by vanduynslagerp** [semantic-release/semantic-release#417]
Re [comment](https://github.com/semantic-release/semantic-release/issues/411#issuecomment-322964177).
You might already be aware, but just in case, v7.0.2 is not published on NPM.

**Comment by luftywiranda13** [comment]
@vanduynslagerp it's currently not tagged as `latest` but `next`. if you want to have v7.0.2 now, you can install it by running `npm install semantic-release@7.0.2 --save-dev` or `npm install semantic-release@next`

**Comment by boennemann** [comment]
Sorry for this. 7.0.2 is now published as latest.

`npm install semantic-release` or `npm install semantic-release@latest` will work now.
