### ISSUE TITLE
What is the intended dist-tags workflow?

### ISSUE THREAD

**Issue by godber** [semantic-release/semantic-release#419]
Using the default npm task `semantic-release`:

```
        "semantic-release": "semantic-release pre && npm publish && semantic-release post",
```

How am I supposed to use `npm dist-tags` to set the latest package version?

My first try was to change the `npm publish` step to publish to something other than `latest` ... like this:

```
        "semantic-release": "semantic-release pre && npm publish --tag dev && semantic-release post",
```

this step works, but then when I go to build a second time it looks like it gets the wrong version because I get the error:

```
"You cannot publish over the previously published version 1.0.4." : teraslice-top
```

Travis output: https://travis-ci.org/godber/teraslice-top/jobs/266393912#L345

Perhaps this is just a bug in finding the latest version.  I will look at that possibility.

**Comment by godber** [comment]
Ok, adding the tag to `package.json` and using the default `semantic-release` task works as desired.


The snippet added would look something like this:

```
...
    "publishConfig": {
      "tag": "dev"
    }
...
```

I suppose the docs could be a little more explicit on this topic, I didn't put two and two together until I re-read it a few times.

**Comment by blakedietz** [comment]
I agree this could be better documented.

**Comment by gr2m** [comment]
Could you send a PR to start a discussion?

**Comment by pvdlg** [comment]
I'm not against clarify the docs at all, but please note this is not a semantic-release option but an npm one.

Also the dist-tag management will change quite a lot with #563 that I hope to complete in the next couple of weeks.
