### ISSUE TITLE
How to use semantic-release to publish compiled assets to npm?

### ISSUE THREAD

**Issue by psyrendust** [semantic-release/semantic-release#422]
At work we have a private org on npmjs and we are publishing the compiled assets to npm, so that users and build systems don't have to install any unnecessary dependencies. I'm currently using this bash script to accomplish this:

```shell
#!/usr/bin/env bash

set -e

bump=${1:-patch}

echo "[release] using: $bump"

dir=$(pwd)
scripts="$dir/scripts"
build="$dir/build"
pub="$dir/publish"

echo "[release] cleaning"
if [ -d $build ]; then
  rm -rf $build
fi

if [ -d $pub ]; then
  rm -rf $pub
fi

echo "[release] creating $pub"
mkdir -p "$pub"

echo "[release] get new version number"
cp package.json _package.json
npm --no-git-tag-version version ${bump} &>/dev/null
tagname="v$(node $scripts/getVersion)"
mv -f _package.json package.json

echo "[release] create release branch: release-${tagname}"
git checkout -b "release-${tagname}" master

echo "[release] bump version and create tag"
npm version $bump -m "chore(release): %s"

echo "[release] git push package bump"
git push origin "release-${tagname}"

echo "[release] git push tag: $tagname"
git push refs/tags/${tagname}

echo "[release] npm install & build"
npm install

echo "[release] create package.json for publish"
node $scripts/cleanPackage > $pub/package.json

echo "[release] copy binaries"
cp $build/Release/* $pub/

echo "[release] change to publish dir"
cd $pub

echo "[release] publish to npm"
npm publish
```

This does the following:

1. Creates a new folder called `publish`.
2. Bumps the `package.json`.
3. Does a `npm install`, which also does a build.
4. Saves a copy of the `package.json` in the `publish` folder
    1. Removes `dependencies` & `devDependencies`
    2. Updates the `"main"` field to point to the resource in the root of the package.
    3. Updates the `"name"` field by prepending our `@org` name to the package.
5. Copies all compiled assets from the 'Release' folder to the root of the `publish` folder.
6. Changes directory to the `publish` folder.
7. Runs `npm publish` from the `publish` folder.

Does anyone have any suggestions of how I could accomplish the same task with `semantic-release`?

**Comment by benjamincharity** [comment]
Add your build steps and publish command between the pre/post steps:

```bash
yarn run semantic-release-pre # This way sematic-release is still managing your versions
yarn run build # This is where you build/copy/package/etc so all files are together
yarn publish dist/
yarn run semantic-release-post
```

So the only real changes to your flow are:

- Step 2 no longer needs to happen
- Step 6 isn't needed. You can pass a directory to the publish command so you don't need to cd in (`yarn publish dist/`)
- Reorganize your steps a bit to match the above pattern

**Comment by vanduynslagerp** [comment]
Thanks a lot @benjamincharity for the detailed explanation!
@psyrendust does that solve your issue?

**Comment by psyrendust** [comment]
@vanduynslagerp that'll work, thanks!

**Comment by jrgcubano** [comment]
I'm facing the same issue... The version does not increase: 

- npm run semantic-release-pre
- npm run build (create dist)
- npm run publish-npm (npm publish ./dist)
- npm run semantic-release-post

https://github.com/MallorcaJS/mallorca-ng/blob/master/.travis.yml

Some advice?

**Comment by benjamincharity** [comment]
Hmm I'm not entirely sure... Our builds look pretty similar. Bump the package, run a rollup build, copy `package.json` over and run publish.

Here are my publish steps if it helps. Maybe something will jump out to you that I'm missing..

- [CircleCI publish script](https://github.com/GetTerminus/terminus-ui/blob/master/tooling/ci/publish.sh)
- [Build script](https://github.com/GetTerminus/terminus-ui/blob/master/tooling/build.js)

**Comment by jrgcubano** [comment]
Nice @benjamincharity. Thanks a lot!

```code
...
script:
  - npm test
  - npm run semantic-release-pre
  - npm run build  
after_success:
  - npm run publish-npm
  - npm run semantic-release-post**
...
```

**Comment by abalad** [comment]
@jrgcubano In your current Travis configuration, is not it generating this error below for you?

`semantic-release ERR! pre Not running in Travis after_success hook`

Because I have the following settings in my travis.yml and when it generates wheel this error is returned to me
```
before_script:
  - npm prune
  - npm run lint
  - npm run test
script:
  - npm run semantic-release-pre
  - npm run compile
after_success:
  - npm run publish
  - npm run semantic-release-post
  - npm run build:showcase
```
