### ISSUE TITLE
semantic-release 8.0.0 : semantic-release ERR! pre Error

### ISSUE THREAD

**Issue by jy95** [semantic-release/semantic-release#424]
Hello,

I have started an little projet and I decided to use semantic-release 8.0.0 with [semantic-git-commit-cli](https://github.com/JPeer264/node-semantic-git-commit-cli).

I have added commits with different tags (feat, fix , test , docs , CI) but each time, I got this message on travis CI :

```cmd
semantic-release ERR! pre Failed to determine new version.
semantic-release ERR! pre ENOCHANGE There are no relevant changes, so no new version is released.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! torrent-files-library@0.0.0-development semantic-release: `semantic-release pre && npm publish && semantic-release post`
npm ERR! Exit status 1
npm ERR! 
```

To help you, here are my [travis.yml](https://github.com/jy95/torrent-files-library/blob/master/.travis.yml) and my latest  [build report](https://travis-ci.org/jy95/torrent-files-library/builds/268788818)

Thanks for your work.

PS: I read this https://github.com/semantic-release/semantic-release/issues/192 but I though I was fixed in this release ...

**Comment by JPeer264** [comment]
A custom [commitAnalyzer](https://www.npmjs.com/package/sgc-commit-analyzer) was written to detect those changes. This should close this issue.

**Comment by jy95** [comment]
thanks ... it seems the changelog generator doesn't handle this extended angular format.

Can someone modify the original module that handles this : https://github.com/conventional-changelog/conventional-changelog/tree/c146f2a67ac8127423fe24cc0cbe304cfa637fe3/packages/conventional-changelog-angular to handle this ?
