### ISSUE TITLE
semantic-release post fails to publish release notes.

### ISSUE THREAD

**Issue by kasunkv** [semantic-release/semantic-release#425]
I've been trying to setup semantic-release in to one of my projects and failed with the above error. So i created a new repository to make sure this is not something related to my previous project. 

I have this new github repository https://github.com/kasunkv/sem-rel
I used semantic-release-cli to set the initial configuration for semantic-release. The setup process went without any issues. Then i used commitizen  and cz-conventional-changelog for my commit conventions. The package.json and the travis.yml files look like this.

**package.json**
```
{
  "name": "sem-rel",
  "version": "0.0.0-development",
  "description": "Sample project to test semantic releases",
  "main": "index.js",
  "scripts": {
    "commit": "git cz",
    "semantic-release": "semantic-release pre && npm publish && semantic-release post"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/kasunkv/sem-rel.git"
  },
  "keywords": [
    "semantic",
    "release"
  ],
  "author": "Kasun Kodagoda",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/kasunkv/sem-rel/issues"
  },
  "homepage": "https://github.com/kasunkv/sem-rel#readme",
  "config": {
    "commitizen": {
      "path": "cz-conventional-changelog"
    }
  },
  "devDependencies": {
    "commitizen": "^2.9.6",
    "cz-conventional-changelog": "^2.0.0",
    "semantic-release": "^7.0.2"
  }
}
```
**.travis.yml**
```
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
before_script:
  - npm prune
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/

```

The commits i made can be seen here: https://github.com/kasunkv/sem-rel/commits/master

When i did the initial build with travis, the release went without any issues. the `semantic-release pre` and `semantic-release post` commands was successful and a new release got created in github.

But when i did some more commits to change the version number and then run the build, the `semantic-release post` step fails with the following error message.

```
+ sem-rel@1.0.0
semantic-release WARN invalid config loglevel="notice"
semantic-release ERR! post Failed to publish release notes. { [Error: {"message":"Reference already exists","documentation_url":"https://developer.github.com/v3/git/refs/#create-a-reference"}]
semantic-release ERR! post   message: '{"message":"Reference already exists","documentation_url":"https://developer.github.com/v3/git/refs/#create-a-reference"}',
semantic-release ERR! post   code: 422,
semantic-release ERR! post   status: 'Unprocessable Entity',
semantic-release ERR! post   headers: 
semantic-release ERR! post    { server: 'GitHub.com',
semantic-release ERR! post      date: 'Tue, 29 Aug 2017 15:13:11 GMT',
semantic-release ERR! post      'content-type': 'application/json; charset=utf-8',
semantic-release ERR! post      'content-length': '121',
semantic-release ERR! post      connection: 'close',
semantic-release ERR! post      status: '422 Unprocessable Entity',
semantic-release ERR! post      'x-ratelimit-limit': '5000',
semantic-release ERR! post      'x-ratelimit-remaining': '4588',
semantic-release ERR! post      'x-ratelimit-reset': '1504020483',
semantic-release ERR! post      'x-oauth-scopes': 'repo, read:org, user:email, repo_deployment, repo:status, write:repo_hook',
semantic-release ERR! post      'x-accepted-oauth-scopes': '',
semantic-release ERR! post      'x-github-media-type': 'github.v3; format=json',
semantic-release ERR! post      'access-control-expose-headers': 'ETag, Link, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval',
semantic-release ERR! post      'access-control-allow-origin': '*',
semantic-release ERR! post      'content-security-policy': 'default-src \'none\'',
semantic-release ERR! post      'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
semantic-release ERR! post      'x-content-type-options': 'nosniff',
semantic-release ERR! post      'x-frame-options': 'deny',
semantic-release ERR! post      'x-xss-protection': '1; mode=block',
semantic-release ERR! post      'x-runtime-rack': '0.369359',
semantic-release ERR! post      'x-github-request-id': 'A098:0DF5:27EED9A:579E468:59A58486' } }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sem-rel@0.0.0-development semantic-release: `semantic-release pre && npm publish && semantic-release post`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sem-rel@0.0.0-development semantic-release script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2017-08-29T15_13_11_189Z-debug.log
```

This was the exact same error i got on my other project. I can not figure out what i am doing wrong here. Some help would be much appreciated.
Travis Build: https://travis-ci.org/kasunkv/sem-rel

**Comment by gr2m** [comment]
This is very curious indeed. Thanks for reporting this issue 👍 

The problem is that it tries to publish version 1.0.0 but the tag `v1.0.0` already exists on github. Is it possibile that either commitizen or cz-conventional-changelog does create the git tag and you pushed it up togethere with your commits?

**Comment by kasunkv** [comment]
Yes the tag `v1.0.0` already exists. And that release was pushed  by travis using semantic-release when i ran the build for the first time. But if you look at the sample repository, there are 2 more commits which are features, that should increment the version number to `v1.2.0` but that is not happening. semantic-release tries to push v1.0.0 to github repository and therefore throwing this error. It seems semantic-release does not pickup the commit properly right? if so the version should have been updated to v1.2.0

**Comment by kasunkv** [comment]
@gr2m I would really appreciate if i can get some assistance on this issue. I tried everything i could think of and still no luck.

**Comment by gr2m** [comment]
I’m really sorry, I’m in between jobs right now and I have to focus on that transition, things will get better soon though.

My next step is to create a bare bone repository that has no dependencies but semantic-release and has the npm "test" script just return `exit 0` so it will always pass on travis, and use that as a minimal test case to reproduce the problem that you have seen. If you could set that up and invite me as collaborator to that would be helpful.

**Comment by pvdlg** [comment]
@kasunkv I looked a bit more at this issue and it seems the version `1.0.0` was published on npm from the commit https://github.com/kasunkv/sem-rel/commit/e35192366c0e26eaf87ed6bd2679906e0323eaa6 which is the last commit on your master branch.

But the github release and the git tag was created with the commit https://github.com/kasunkv/sem-rel/commit/8865499212f105ba708e12a09f0f7c7135ed4bdb which 4 commit behing the one used for the npm release.

It seems that somehow the order of event was:
- Commit https://github.com/kasunkv/sem-rel/commit/8865499212f105ba708e12a09f0f7c7135ed4bdb => release on github + tag but no release on npm
- Commit https://github.com/kasunkv/sem-rel/commit/e35192366c0e26eaf87ed6bd2679906e0323eaa6 release on npm but release on github failed

This is probably because you forgot to add `npm publish` in your release command in between those commits.

The situation should solve itself automatically on the next commit you push on your master branch.
Let us know if that works

**Comment by kasunkv** [comment]
Yes, that is what has happened. Having said that, does semantic-release must have a npm publish step included in it to work properly.? Because, the first time i faced this issue was on a different project that i am working on [kasunkv/owasp-zap-vsts-task](https://github.com/kasunkv/owasp-zap-vsts-task) . This is not a npm package. The releases to VSTS happens on a different build system. I only wanted to have semantic releases on GitHub with release notes. That's why in the sample project i created, i did not include npm publish in the semantic release step. When that didn't work, i tried adding npm publish to check if that had something to do with the changes. But if you check the commit history, if everything works as expected it should have incremented the version number since i have pushed another commit with a feature commit tag  to trigger a version increment. So the order in that case is (first commit on the top)

- Commit [kasunkv/sem-rel@ecf820f6a](https://github.com/kasunkv/sem-rel/commit/ecf820f6a1757be94e6a5d83e27d529a3538a0bc) => Initial Commit - No Build
- Commit [kasunkv/sem-rel@7fb10643](https://github.com/kasunkv/sem-rel/commit/7fb10643df902c168dde9118ab92a09515394432) => feat(hello): - Build Failed
- Commit [kasunkv/sem-rel@6dce8ed68](https://github.com/kasunkv/sem-rel/commit/6dce8ed68c64cbfe79c88079de8c04b000b2a7c7) => chore(build): - v1.0.0 was released. No npm publish
- Commit [kasunkv/sem-rel@6dce8ed68](https://github.com/kasunkv/sem-rel/commit/8865499212f105ba708e12a09f0f7c7135ed4bdb)  => feat(method) - Version Increment Failed. No npm publish
- Commit [kasunkv/sem-rel@f698f4fd5](https://github.com/kasunkv/sem-rel/commit/f698f4fd54b869081f5304618c5c5234a702d618)  => feat(method) - Version Increment Failed. No npm publish
- Commit [kasunkv/sem-rel@b853ce1f2](https://github.com/kasunkv/sem-rel/commit/b853ce1f2d606d35b96da2cfaf5506d43c994ee5) => chore(build) - Version Increment Failed. No npm publish
- Commit [kasunkv/sem-rel@e35192366](https://github.com/kasunkv/sem-rel/commit/e35192366c0e26eaf87ed6bd2679906e0323eaa6) =>chore(config) - Version Increment Failed. npm publish included.

If my understanding is correct and assuming npm publish is not required for semantic releases. at the commit [kasunkv/sem-rel@6dce8ed68](https://github.com/kasunkv/sem-rel/commit/8865499212f105ba708e12a09f0f7c7135ed4bdb) the v1.1.0 should have been released to GitHub and at the commit [kasunkv/sem-rel@f698f4fd5](https://github.com/kasunkv/sem-rel/commit/f698f4fd54b869081f5304618c5c5234a702d618) the v1.2.0 should have been released.

Am i right on this assumption?

**Comment by pvdlg** [comment]
`semantic-release` for now rely on packages published on npm to figure out the commit that was used to make the previous release. So without publishing to npm we can't determine which commit to analyze when determining the next release.

We have plans to allow this type of scenario, and possibly to handle other type of platform than npm. But we're not there yet... We have a plugin to determine the last version released based on git tags here https://github.com/semantic-release/last-release-git-tag but it requires some work.
