### ISSUE TITLE
Customizable commit-analyzer and release-notes-generator plugins

### ISSUE THREAD

**Issue by vanduynslagerp** [semantic-release/semantic-release#427]
I became a big fan of `semantic-release` recently and I experimented with it by creating a [commit-analyzer](https://github.com/vanduynslagerp/sr-commit-analyzer) and a [release-notes-generator](https://github.com/vanduynslagerp/sr-release-notes-generator) plugin.
Those plugins offer (I believe/hope) several improvements over the defaults ones and maintain full backward compatibility (switching would be totally transparent).
Some of these improvements were outlined in #411.

I'm willing to contribute those improvements back to semantic-release, but I'm not sure what's the best way to do so, hence this post.
I could:
- open a few PRs to the default plugins with the improvements you'd like to get
- or just reference those plugins in the semantic-release readme file
- make any modifications that you'd like in those plugins and push a PR to semantic-release to use them as default

Or frankly anything else. I'd just like to be useful and help the semantic-release project.

You can check out those 2 plugins here: [sr-commit-analyzer](https://github.com/vanduynslagerp/sr-commit-analyzer) and [sr-release-notes-generator](https://github.com/vanduynslagerp/sr-release-notes-generator).

Here is a list of the added features and improvements:
- Allow to use any [conventional-changelog](https://github.com/conventional-changelog/conventional-changelog) preset (`angular`, `eslint`, custom one...)
- Allow to customize [the rules](https://github.com/vanduynslagerp/sr-commit-analyzer#release-rules) used to determine the type of release in the `commit-analyzer` directly in the `package.json` config or within a npm module
- Allow to override any `conventional-changelog` preset attribute (useful if you want to use an existing preset with a small change, for example a different ordering of the commits in the changelog or a different parsing regexp)
- Replace [tapjs](https://github.com/tapjs/node-tap) by [avajs](https://github.com/avajs/ava)
- A lot more unit and integration tests
- Full documentation in the readme file
- Use Node 8 features (no transpilation necessary as semantic-release require Node 8 now)
- Use a more strict [eslint](https://github.com/vanduynslagerp/eslint-config-pretty) config and [prettier](https://github.com/prettier/prettier)

Those plugins would solve currently opened issues around changing which type of commits trigger a release and using a commit format other than `angular`.

I used those plugins on several projects and they are stable by now.
In any case I'm willing to continue to maintain those plugins (whatever the form they take) and to create more things around `semantic-release` (like something to add a comment to a PR letting you know what release will be triggered when you merge the PR).

Any feedback/guidance welcome.

/cc @gr2m

**Comment by gr2m** [comment]
Hey @vanduynslagerp, that all sounds great, thanks for offering to contribute them back to core!

These are pretty massive changes, I’ll need some time to review them. It’s not that they aren’t great, it’s all about the fact that we take over responsibility and maintainership over for these, too. Would you be willing to join the maintainers team to help out with that?

Upfront, two things:

- please keep in [standard](https://github.com/standard/standard). It’s not that we think the rules are better, it’s the fact that we discussions about coding styles is one less discussion we can have :) I haven’t use prettier yet but there is [prettier-standard](https://github.com/sheerun/prettier-standard), would that be an option?
- I’m very familiar with tap myself so I would prefer to keep that. I'm always happy to be convinced about how ava is better :) I care less about features, and more about simplicity and contributor friendliness. And if we introduce ava to the default plugins, we should use it in all semantic-release packages. Would you be willing to help with that transition?

**Comment by vanduynslagerp** [comment]
Hello @gr2m !

> These are pretty massive changes, I’ll need some time to review them. It’s not that they aren’t great, it’s all about the fact that we take over responsibility and maintainership over for these, too. Would you be willing to join the maintainers team to help out with that?

Yes, I'd be really happy to join the maintainers team !

> please keep in standard. It’s not that we think the rules are better, it’s the fact that we discussions about coding styles is one less discussion we can have :) I haven’t use prettier yet but there is prettier-standard, would that be an option?

[Prettier](https://github.com/prettier/prettier) is an amazing tool that I would highly recommend. It solves the endless discussions about formating and really improves productivity. Prettier can take care of the formatting rules (usually opinionated) and let [eslint](https://github.com/eslint/eslint) take care of the "potential bug" type of rules (usually not opinionated). The problem I see with [standard](https://github.com/standard/standard) is that it prevent to use some very useful rules from plugins like [eslint-plugin-import](https://github.com/benmosher/eslint-plugin-import), [eslint-plugin-node](https://github.com/mysticatea/eslint-plugin-node), [eslint-plugin-promise](https://github.com/xjamundx/eslint-plugin-promise) or [eslint-plugin-ava](https://github.com/avajs/eslint-plugin-ava). 

That said, I have no problems switching to [prettier-standard](https://github.com/sheerun/prettier-standard).

> I’m very familiar with tap myself so I would prefer to keep that. I'm always happy to be convinced about how ava is better :) I care less about features, and more about simplicity and contributor friendliness. And if we introduce ava to the default plugins, we should use it in all semantic-release packages. Would you be willing to help with that transition?

[Ava](https://github.com/avajs/ava) syntax is exactly the same as Tap so the change would be completely transparent and shouldn't impact contributors. Ava is a lot faster, produces more informative error output, supports all the last JS syntax out of the box (including async await) and has many [other advantages](https://github.com/avajs/ava#why-ava).
I'm totally willing to take care of the transition to Ava for each semantic-release repository (it should be really fast and pretty transparent). In addition I was under the impression that this transition was already [underway](https://github.com/semantic-release/travis-deploy-once/commit/c30fe65691e9e53d37fcc4c79ded193732127253).

**Comment by vanduynslagerp** [comment]
Hello,
I did a some research/attempt to use [prettier-standard](https://github.com/sheerun/prettier-standard). It turns out it's a formatter but not a linter. So it doesn't provide a way to actually lint (in the sense of enforcing a format during the CI).

So here is the options that I see so far:

### 1/ Use `standard` just the way it's used on other `semantic-release` repo
Pro:
- Simple, we don't have to change anything on other repo to harmonize

Con:
- We lose the auto-formatting feature of `prettier` (prettier is more contributor friendly I think)
- We enforce only the "loose" format of `standard` (in the sense that the same code can be formatted multiple way and still be valid for `standard`. For example `standard` does not enforce the line length. With prettier, 1 AST = 1 output).
- We lose the ability to enforce "potential bug" type of rules that are not part of `standard`

### 2/ Use `eslint` + `eslint-config-standard` + `eslint-config-prettier`
Pro:
- Nicer and stricter `prettier` formatting (for example, enforce a max line length, adapt the format to fit in the max length) well integrated with every IDE, less controversial formatting as the "opinionated" choices of prettier are based on open source code analysis to determine the most common patterns used out there
- Non formatting rules stays are the same as the one currently set on the others `semantic-release` repo
- We use directly `eslint` with all the latest features rather than the `standard` wrapper
- Ability to, someday if we choose to, to add more "potential bug" type of rules

Con:
- We need to add one config file (`.eslintrc`) on each repo that contains `{extends: ['standard', 'prettier'], plugins: ['standard', 'prettier']}`

Solution 2 seems to be more contributor friendly to me (try prettier for a couple days, you won't go back, I promise :-)). But that's just my opinion.

If we choose option 2, I can make a PR on each repo. If we choose solution 1, I can live with it :-)

**Comment by gr2m** [comment]
Thanks for the research, Pierre, this is great input 👍 I’ll try to get @boennemann’s thoughts on this. I’m okay with either.

**Comment by vanduynslagerp** [comment]
Another thing I'd like to do is to update the code to es6 now that we require Node 8.
The `prettier`/`eslint` solution would allow to mostly automate that (open file and save would autofix) and we could enforce es6 usage (force using `const`/`let` instead of `var`, enforce using `async`/`await` or `Promise` if we choose to etc...). On the other hand `standard` allow to use es6 features but doesn't enforce it (you can still push code using `var` for example).

**Comment by gr2m** [comment]
that would be great :) 

I really don’t mind the loose rules of `standard`. Problems with syntax that could have been enforced with stronger eslint rules is not a problem we have

**Comment by vanduynslagerp** [comment]
> Problems with syntax that could have been enforced with stronger eslint rules is not a problem we have

What I meant is that after migrating everything to es6, if someone opens a PR with some code that use `var` for example, then you'll have to check visually in the diff to make sure to not introduce inconsistencies, and ask that person to use `const`/`let`, because `standard` won't tell you.

**Comment by gr2m** [comment]
yes, I don’t think that will be much of a problem, I haven’t seen that become much of a problem in any other projects I’m involved in that is using standard, but I have seen endless discussions about around jshint / eslint configurations :) Hence the preference to just go with standard

**Comment by gr2m** [comment]
All right, @vanduynslagerp, let’s do it :) 

I hope to find a bit of time to work on semantic-release on Friday / Saturday, that’s when I can review your pull requests. If you could help us with transforming to es6 and setting up the linting (eslint + eslint-config-standard + eslint-config-prettier) that’d be ace.

I’ll invite you to the team in moment. Welcome 🙌

**Comment by vanduynslagerp** [comment]
Awesome ! I'll try to start that ASAP, but most likely PR will show up only this Saturday/Sunday. Thanks !

**Comment by vanduynslagerp** [comment]
[commit-analyzer](https://github.com/semantic-release/commit-analyzer) and [release-notes-generator](https://github.com/semantic-release/release-notes-generator) are now the default plugins in `semantic-release@8.0.1`
