### ISSUE TITLE
Improve plugin logs

### ISSUE THREAD

**Issue by pvdlg** [semantic-release/semantic-release#438]
Sometimes it's quite difficult to understand why a release is not happening because the default plugins are not logging.

For example it would be helpful to get logs for:
- The list of commit analyzed
- The type of release determined for each commit and info regarding why a release type is triggered
- What make the verification fails
- Which build is determined to be the leader

We could just add a logger to each plugin or we could pass a logger from `semantic-release` to each plugin in the `config` object.
The second option might be better so we can have more consistency in the logging.

It should solve #432

Thoughts @gr2m ?

**Comment by gr2m** [comment]
have you tried setting `npm_config_loglevel`? `semantic-release` is currently using the same log library as npm itself, so you can set `npm_config_loglevel=verbose` to get more logs

I’ve used it myself in the past but moved over to the much simpler and more widely adapted [debug](https://www.npmjs.com/package/debug) package. I’d be happy to transition to that and use it across all core packages as well as recommending it to be used by plugin developers

**Comment by vanduynslagerp** [comment]
Yes there is log on the main `semantic-release` but not on the plugin themselves.
For example we don't log details about how the build leader is determined. And we have a few issues on the tracker that could benefit from that.

[debug](https://www.npmjs.com/package/debug) is great but it's really for debug logs (like you don't want to log that systematically).
In most cases we have bug report with a problem that already happen (someone linking the travis build log for example). So it would be helpful to log systematically.

`npmlog` seems ok and do the job. But we can change to something else.

My idea was for `semantic-release` to create the logger, set the loglevel and pass it to each plugin. So each plugin can easily log stuff without having to import a logger and dealing with all that.

Regarding the log level, it seems a bit confusing to me to use npm loglevel param in `.npmrc` (I just learn it exists actually).
Maybe we can do `info` by default and `debug` if the `--debug` arg is passed to `semantic-release`.
As we run primarily on CI, I don't think having "too much detailed" logs is a problem as it doesn't impact the user (contrary to a cli tool you use on your terminal).

I'll continue to work on the general "refreshing" of the repo and I'll make a PR for the logging (that would be easier to show what I mean and discuss it).

**Comment by gr2m** [comment]
I’m okay with passing a logger to the semantic-release plugins 👍 

A problem I run into with `npmlog` is that if I set the loglevel to verbose or silly, it also affects the other npm commands like `npm install` and `npm test`. The log becomes huge and travis eventually cuts it off. Setting `DEBUG=semantic-release*` or `DEBUG=semantic-release:plugin-name*` would only affect semantic-release.

We could pass in a `.log` method to the plugins that is `require('debug')(`semantic-release:${pluginName}`)`

**Comment by vanduynslagerp** [comment]
> A problem I run into with npmlog is that if I set the loglevel to verbose or silly, it also affects the other npm commands like npm install and npm test. The log becomes huge and travis eventually cuts it off. Setting DEBUG=semantic-release* or DEBUG=semantic-release:plugin-name* would only affect semantic-release.

Sounds nasty. Let's avoid `npmlog` then.

> We could pass in a .log method to the plugins that is require('debug')('semantic-release:plugin-name')
Yes this is exactly what I was thinking.

The problem with `debug` is that it's on or off (no `error`, `info`, `debug` level). It monitors execution time and seems really dev oriented.
I think we need at least:
- Error: token missing, npm registry inaccessible etc
- info: build leader determination, commit analyze and other info users can need to understand what's going
- debug: Very specific things mostly for us to solve issues

[log4js-node](https://github.com/nomiddlename/log4js-node) seems widely used. But didn't search extensively (it seems there is a lot of logging libraries).
We can also add [chalk](https://github.com/chalk/chalk) which allow to make pretty sweet and readable logs. I like colors :)

**Comment by gr2m** [comment]
I don’t know, we could just log errors directly using `console.log`. I’ve used different libraries in the past that support different loglevels and especially in teams (and even more so in open source projects with a higher fluctuation rate) people are confused about what level to use when, so ending up with `debug` and simple name spaces is a good balance.

I like chalk for logs, too :) `debug` gives you colorful logs by default ;)

**Comment by vanduynslagerp** [comment]
I was thinking something along those lines:
```js
// src/utli/logger.js
function getLogger(namespace){
  return {
    log() {
      console.log(`${chalk.magenta(namespace)} ${chalk.white(Array.prototype.slice.call(arguments).join())}`);
    },
    error() {
      console.error(`${chalk.magenta(namespace)} ${chalk.red(Array.prototype.slice.call(arguments).join())}`);
    }
  }
}

// in semantic-release
const logger = getLogger('condition-travis');
// Then pass logger to condition-travis plugin

logger.log('This is an informative message');
logger.error('Something wrong, please do something about it');
```

The output look like that:
![simple-logs](https://user-images.githubusercontent.com/3250552/30574781-4c01747a-9cca-11e7-8e8d-e52101d3ffbe.jpg)

* No loglevel to deal with.
* `info` for informative logs so the user know what `semantic-release` is doing (like "we are going to release make a patch release", "Releasing v1.0.1", etc..).
* `error` so user know something went wrong and he has to fix something (like "Please set NPM_TOKEN. You can find more information here: <link to doc>").
* `info` and `error` are pretty explicit, so it avoid the situation of contributors wondering what level to use.
* Very easy to mock for unit test to check that we log appropriately.

Then we can use [debug](https://github.com/visionmedia/debug) for actual debug log (ie for developers looking to fix a bug), that will be activated only if we pass the `--debug` arg or set the `DEBUG` environment variable. `debug` can be used for stuff like ("executing function XXX, going in code branch YYY").
No need to pass the `debug` instance to the plugin, as the `DEBUG` environment variable is set in `semantic-release`. So the plugin can import `debug` and use it directly.

Looking around on different popular projects it seems this approach (`console` for log and error + `debug` for dev debugging) is quite common.

**Comment by gr2m** [comment]
okay sounds good to me 👍 

I think `console.error` is just an alias for `console.log` these days, at least in node, so you can just use `console.log` for both

**Comment by vanduynslagerp** [comment]
[console.error](https://nodejs.org/api/console.html#console_console_error_data_args) logs on `stderr` while [console.log](https://nodejs.org/api/console.html#console_console_log_data_args) logs on `stdout`.

[console.info](https://nodejs.org/api/console.html#console_console_info_data_args) is an alias of `console.log` (and probably pretty much every variant).

Not sure anymore make a distinction between `stdout` and `stderr` though...

**Comment by gr2m** [comment]
you are right, maybe they changed it back ¯\\\_(ツ)\_/¯
