### ISSUE TITLE
ENOCHANGE There are no relevant changes – although commit is `fix: ...`

### ISSUE THREAD

**Issue by gr2m** [semantic-release/semantic-release#439]
here is an example of a recent build of semantic-release itself:
https://travis-ci.org/semantic-release/semantic-release/builds/276689252#L2191

**Comment by vanduynslagerp** [comment]
This was due to the release being published on npm during previous build, but the github release not being published due to a bug fixed since then.
So the `There are no relevant changes` message was correct.
