### ISSUE TITLE
Cannot find module 'node-uuid'

### ISSUE THREAD

**Issue by Qard** [semantic-release/semantic-release#444]
I just tried using semantic-release on a new module and it did the first release fine, but when I try to add any further commits I just get this error. Any idea why?

```sh
Error: Cannot find module 'node-uuid'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/travis/build/Qard/semverio/node_modules/travis-ci/node_modules/request/lib/auth.js:4:12)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
```

https://travis-ci.org/Qard/semverio/jobs/279336355#L1305-L1315

**Comment by vanduynslagerp** [comment]
I saw this problem happening a few times on Travis (independently of semantic-release). It seems to be related to the way the npm cache is handled.
It should be solve if you remove the purge the cache on the Travis UI and restart the build.

I would recommend to remove the cache directive in your `travis.yml`.

In addition you can add a retry on the install step like this:
```yml
install:
  - travis_retry npm install
```

**Comment by hbetts** [comment]
As an alternative, it may be best to just remove `npm prune`.

`npm` version 5 automatically creates a lockfile, and uses that lockfile when installing your project's dependencies.

`npm prune` is actually unnecessary when using npm version 5.

`npm` version 5 will always make sure your `node_modules` directory matches your `package-lock.json` file exactly.

**Comment by gr2m** [comment]
> remove npm prune

Yeah there are some updates due for the CLI, we can remove `npm prune` now. And instead of caching node_modules, we’ll cache `~/.npm`

Can we close this issue?

**Comment by boneskull** [comment]
Thanks `gr2m`, I ran in to this as well.

**Comment by hbetts** [comment]
>  And instead of caching node_modules, we’ll cache ~/.npm

With npm version 5 you can still cache `node_modules/`.

npm version 5 will modify the contents of `node_modules/` to ensure it matches the `package-lock.json` lockfile.

**Comment by boneskull** [comment]
@hbetts It's worth noting that to get rid of the problem entirely, I had to not only remove `npm prune` but also the cache of `node_modules`.  Maybe I can put the cache back; there doesn't seem to be a way to reset it manually?

**Comment by hbetts** [comment]
> It's worth noting that to get rid of the problem entirely, I had to not only remove npm prune but also the cache of node_modules. 

That seems really strange. Maybe I'm being overly optimistic about npm's ability to update an existing `node_modules` directory in-place to match a `package-lock.json` file?

Also, maybe I'm making an incorrect assumption here. Do you have a `package-lock.json` file in your repository?

Since you're using Travis CI you can manually clear the cache following these instructions - https://docs.travis-ci.com/user/caching/#Clearing-Caches

**Comment by gr2m** [comment]
I’ve seen the core npm CLI developers themselves recommend to not cache node_modules, but ~/.npm instead, so that’s what I’m doing and recommend others to do, too

**Comment by boneskull** [comment]
iarna writes:

> @boneskull I would have always cached ~./npm as well, but yeah npm@5 is fast enough that skipping node_modules is ok now.

This seems to imply that if you *aren't* using npm@5, then keep caching `node_modules`.

**Comment by pvdlg** [comment]
This issue doesn't seem to be related to `semantic-release` directly, but to npm/Travis/cache good practice.
Feel free to re-open you want to propose/request a change in `semantic-release`
