### ISSUE TITLE
Proposal regarding the node 8 limitation

### ISSUE THREAD

**Issue by pvdlg** [semantic-release/semantic-release#445]
Recently `semantic-release` moved to support only Node 8 or above (See [why-does-semantic-release-require-node-version--8](https://github.com/semantic-release/semantic-release#why-does-semantic-release-require-node-version--8)).

The workaround proposed [here](https://github.com/semantic-release/semantic-release#why-does-semantic-release-require-node-version--8) and [there](https://github.com/semantic-release/semantic-release/blob/12b35396d88d37de8000d7838b41de9f2b276f80/bin/semantic-release.js#L15) is to use `npx` but that doesn't solve the issue as `npx` is just a tool to run locally installed packages as global ones (basically allow to run `npm my-local-package` rather than `npm node_modules/.bin/my-local-package`). That doesn't allow to run Node 8 only package on an older version of node.
So this should be removed.
A solution that would allow to run Node 8 package on older version is [babel-node](https://babeljs.io/docs/usage/cli/#babel-node) but it's not recommended for production, and it doesn't provide polyfill for Node 8 API, it only transpile and polyfill Javascript features.
And it would't work either as the Node version is checked [here](https://github.com/semantic-release/semantic-release/blob/caribou/bin/semantic-release.js#L8).

In addition supporting only Node 8 creates some additional frictions for users:
- In a build with multiple node versions, `semantic-release` will be executed on each job, but will exit right away if it's not Node 8 and display an error. The error is expected and should be ignored but it might be confusing
- Require to create an extra Node 8 job in (rare) cases the CI doesn't already have one configured
- Forces to set in the `package.json` to `{"engines" : ""node": ">=4"}` in order to be installed by `yarn` (see #442)

All that can certainly be dealt with by users, but it adds on the cognitive load to use `semantic-release` as it requires for users to understand some of the internal mechanisms related to the interaction between `semantic-release` and the CI : CI commands run for every version of Node in the build, semantic-release exit right away with an error on every jobs but one, elect a build leader to figure out which one should not exit etc....

An alternative solution would be to use [babel-register](https://babeljs.io/docs/usage/babel-register/), it would allow to preserve the compatibility with Node 4, without creating much complexity for maintainer and contributors.
Here is how it would work.

Add on top of [bin/semantic-release.js](https://github.com/semantic-release/semantic-release/blob/caribou/bin/semantic-release.js):
```js
require('babel-register)({only: ['.src', '@semantic-release/*']}); // Transpile only sources and plugins
require('babel-polyfill);
```
And in `package.json`:
```json
"babel": {
  "presets": [
    ["env", {
      "targets": {
        "node": "current" // Transpiled only what's required by the currently running node
      }
    }]
  ]
}
```
And that's it !
The benefits:
- When executing `semantic-release` it would be transparently transpiled to support the currently running Node version (so that would skip transpilation when `semantic-release` is running on node)
- Allow to use all the last JS features, including `async/await`
- No additional build steps

According to the quick tests I did, the performance impact is negligible, ~200ms on Node4 and nonexistent on Node 8. Anyway most of `semantic-release` run time is spent on I/O (github API, npm registry, git commands etc..).
The only shortcoming is that the Node API released after 4 wouldn't be available. I checked the code and the only Node > 4 API we use is [promisify](https://nodejs.org/api/util.html#util_util_promisify_original) that can be replaced by [pify](https://github.com/sindresorhus/pify).

/cc @gr2m

**Comment by gr2m** [comment]
I must admit I’m probably one of the few people who still haven’t worked with Babel much :) I love the project and their maintainers though, so definitely open to it. I usually try to avoid to to limit the amount of tooling to a minimum, but you make a good case for it here.

One thing that I fear (maybe for no reason, I don’t know): what happens when errors occur? How good are error stacks from transpiled code? 

It’s not only about making semantic-release run in versions less than Node 8, if we keep supporting them officially, there will be an overhead for us as maintainers to keep them working. We have to test in all the node versions and people will report bugs. The alternative is to make it easier for people to setup semantic-release correctly, which feels like a documentation overflow. It will also cause a support overhead for sure, I’m not sure if one outweighs the other.

To be fair, if we say "just use npx" it’s basically the same problem. But it feels like less overhead for us than introducing babel. But We should add it to our CI tests, because at least for me, it didn’t work: https://github.com/semantic-release/semantic-release/pull/414#issuecomment-330004885

Node 8 becomes the official LTS version next month. Node 4 remains in maintenance until April 2019. I feel like focussing on the LTS version is good practise.

So yeah, I’m undecided

**Comment by vanduynslagerp** [comment]
> To be fair, if we say "just use npx" it’s basically the same problem. But it feels like less overhead for us than introducing babel. But We should add it to our CI tests, because at least for me, it didn’t work: #414 (comment)

"use npx" doesn't works. npx doesn't transpile or simulate node 8. This is why I made this proposal actually. If `npx` was making node 8 packages works on node 4 that would be a no brainer... From above 
> The workaround proposed [here](https://github.com/semantic-release/semantic-release#why-does-semantic-release-require-node-version--8) and [there](https://github.com/semantic-release/semantic-release/blob/12b35396d88d37de8000d7838b41de9f2b276f80/bin/semantic-release.js#L15) is to use `npx` but that doesn't solve the issue as `npx` is just a tool to run locally installed packages as global ones (basically allow to run `npm my-local-package` rather than `npm node_modules/.bin/my-local-package`). That doesn't allow to run Node 8 only package on an older version of node.
So this should be removed.

**Comment by gr2m** [comment]
> "use npx" doesn't works. npx doesn't transpile or simulate node 8. This is why I made this proposal actually :) If npx was making node 8 packages works on node 4 that would be a no brainer :)

`npx -p node@8 npm run semantic-release` should install and run in node 8, at least that’s how it’s advertised as far as I know ¯\\\_(ツ)\_/¯ I guess we have to change how we check for the node version to make it work

```
$ node -v
v4.8.3
$ npx -v
9.6.0
$ npx -p node@8 node -v
v8.3.0
```

**Comment by vanduynslagerp** [comment]
Ohhhhhh....my bad....I misunderstood the trick completely. `npx -p node@8` actually install node 8 as an npm package and runs it. I totally missed that.

So I don't understand the problem in [#414-comment](https://github.com/semantic-release/semantic-release/pull/414#issuecomment-330004885) then...

I searched for more info in `npx` and I didn't find any example mentioning that you can install node like that. Would you mind sharing the docs mentioning that ?

**Comment by gr2m** [comment]
oh you are right, it’s actually not documented, I’ve just seen Kat tweet about it. I’ll open an issue on the npx repository

**Comment by vanduynslagerp** [comment]
👍 If we manage to make it work that would be awesome.
Maybe we'll have to remove the test on `process.version` in the code ? But that ok I guess.

**Comment by gr2m** [comment]
The problem is that process.version returns the wrong version when run a an executable file instead of running it with `node file.js`

Here is a test script "funk.js"

```js
#!/usr/bin/env node
console.log('\nprocess.version ==============================')
console.log(process.version)
```

And a test

```
$ npx -p node@8 node funk.js 

process.version ==============================
v8.3.0
$ npx -p node@8 ./funk.js 

process.version ==============================
v4.8.3
```

I dunno if there is a workaround for this

**Comment by vanduynslagerp** [comment]
In the case of `npx -p node@8 ./funk.js` I wonder if it runs it on node 8 with the wrong `process.version` or it runs in node 4.

If it's only the `process.version`, maybe we can just remove the test in our code.

Maybe a better workaround is to make `semantic-release` to work as a global package.
I think we almost there, we just need to revisit the way we load custom plugins when running as global.

**Comment by gr2m** [comment]
> In the case of npx -p node@8 ./funk.js I wonder if it runs it on node 8 with the wrong process.version or it runs in node 4.

It runs in node 4, I tested it

**Comment by vanduynslagerp** [comment]
Shouldn't the command be `npx -p node@8 node ./funk.js` instead ?

**Comment by gr2m** [comment]
`npx -p node@8 ./funk.js` works after `chmod +x funk.js`, but it does not use the node version that npx set, but is using the system node

**Comment by vanduynslagerp** [comment]
Ideally we should be able to handle all the steps in one command (something that would do pre, publish and post).
Then we could do `npx -p node@8 semantic-release`.

**Comment by gr2m** [comment]
Agree :)

**Comment by vanduynslagerp** [comment]
We'll have to think about how to do that. But in the meantime I think we can close this issue once we have modified the doc :)

**Comment by pvdlg** [comment]
So it seems the `npx` trick is a bit shaky...Also npxing Node 8 to run a command is not really documented...

Once #524 get merged we could recommend to run `semantic-release` globally.

That would allow to go back to `{"engines" : ""node": ">=8"}` everywhere. The `>=4` trick was implemented because yarn refused to install incompatible version.
If we recommend to install globally then `yarn` users could do something like this:
```
after_success:
  - yarn global add semantic-release && semantic-release
```
This way if the Node version is <8 the installation will fail but not stop the build as the failure occur in `after_success`. Or maybe better:
```
after_success:
  - yarn global add semantic-release && semantic-release || true
```
Or:
```
if [[ `node -v | egrep -o '[0-9|\.]+'` > 9* ]]; then yarn global add semantic-release -g && semantic-release; fi
```
For npm <5 users:
```
after_success:
  - npm install semantic-release -g && semantic-release
```
For npm 5 users:
```
after_success:
  - npx semantic-release
```

**Comment by gr2m** [comment]
Sounds all good to me 👍 

Basically if folks us `yarn` and they want to test in node < 8, they don’t install semantic-release as devDependency, but install it globally as part of their CI? That’s a decent workaround :)

**Comment by pvdlg** [comment]
Should be good after #593

We just need to set the `engines.node` back to `>=8`

**Comment by pvdlg** [comment]
All orga packages have been update to require Node >=8.3
