### ISSUE TITLE
Error in Travis CI: Cannot find module 'request-promise-core/configure/request2'

### ISSUE THREAD

**Issue by sukazavr** [semantic-release/semantic-release#448]
Details are here: https://travis-ci.org/sukazavr/qum/builds/280588536
Do you need some additional information?

**Comment by vanduynslagerp** [comment]
It seems to be a duplicate of https://github.com/semantic-release/semantic-release/issues/444

Can you try to apply one the solutions proposed there ?

**Comment by sukazavr** [comment]
@vanduynslagerp i'm on my way

**Comment by vanduynslagerp** [comment]
Awesome! Thanks so much for the reactivity!

**Comment by sukazavr** [comment]
@vanduynslagerp yeah! It helped! Thank you so much for the help and blazing fast reaction 👍
