### ISSUE TITLE
New shearable config: APM

### ISSUE THREAD

**Issue by shroudedcode** [semantic-release/semantic-release#456]
I'm currently developing an Atom package and thinking about publishing it with `semantic-release`. APM's `publish` command is already [quite easy to use](http://flight-manual.atom.io/hacking-atom/sections/publishing/#publish-your-package), but I would like to have [Travis CI](https://travis-ci.org/) do the publishing for me, so that I can make changes and accept pull requests without having to worry about publishing.

Does anyone have experience with using `semantic-release` to publish to APM?

**Comment by pvdlg** [comment]
`apm` is not currently supported unfortunately. But that's something we'll consider in the future. I cannot tell when though...

**Comment by pvdlg** [comment]
Once #515 will be merged and released, it will be possible to customize the release process via plugins.
We would need to create an `apm` plugin similar to https://github.com/semantic-release/npm.

The plugin would have to:
- Verify the authentication to the `apm` registry
- Retrieve the last version published (for a given dist-tag if `apm` support dist-tags)
- Publish a given version

Would you know by any change where to find documentation about how to do that with `apm`?
Would you be interested in developing such plugin?

**Comment by shroudedcode** [comment]
@pvdlg [Here](https://github.com/shroudedcode/semantic-release-apm) it is.

**Comment by pvdlg** [comment]
Looks good. Let me know if you need any help!

**Comment by shroudedcode** [comment]
@pvdlg @gr2m Could you please take a look at [this issue](https://github.com/shroudedcode/semantic-release-apm/issues/4)? I need some feedback and help.

*(I already tagged you on the issue but don't know whether you were notified.)*

**Comment by keplersj** [comment]
With #553 merged in and published what is needed to have a shareable APM config published as discussed here https://github.com/shroudedcode/semantic-release-apm/issues/4#issuecomment-353410272? I'm very interested in rolling this out to many of the AtomLinter packages.

ref: https://github.com/AtomLinter/Meta/issues/18
cc: @Arcanemagus

**Comment by shroudedcode** [comment]
> I'm very interested in rolling this out to many of the AtomLinter packages.

@keplersj I'm really excited to see interest from one of the most popular Atom package organizations on this. It would be great if we could make automated deployment the standard in the Atom community.

**Comment by Arcanemagus** [comment]
Oooo, this is going to be _amazing_ if we can use that as full protection can finally be enabled on the `master` branch while still letting collaborators publish releases!

**Comment by pvdlg** [comment]
Work in progress in semantic-release/apm-config#1.

**Comment by pvdlg** [comment]
[`@semantic-release/apm-config`](https://github.com/semantic-release/apm-config/releases/tag/v1.0.0) has been release!

@ Arcanemagus that would be awesome if [Atom Linter](https://github.com/AtomLinter) would use Semantic-release! Do not hesitate to ping me if you have any question or need help with the config!
