### ISSUE TITLE
Hardcoded fallbackTags dist-tag

### ISSUE THREAD

**Issue by pvdlg** [semantic-release/semantic-release#459]
The `fallbackTags` is hardcoded to `next` [here](https://github.com/semantic-release/semantic-release/blob/caribou/src/index.js#L34). It's used [there](https://github.com/semantic-release/last-release-npm/blob/master/index.js#L27).

It seems that when we configure a dist-tag in `publishConfig` or `.npmrc` and there is no published release on that dist-tag yet, we fallback to the last release on `latest` but only if the dist-tag configured is `next`. Should we always fallback to `latest`, no matter the dist-tag configured?

Am I missing something?

/cc @gr2m

**Comment by gr2m** [comment]
Hmm I don’t see any reason not to :)
