### ISSUE TITLE
Pass lastRelease, nextRelease and commits to release-note-generator

### ISSUE THREAD

**Issue by pvdlg** [semantic-release/semantic-release#460]
The commit used for the last release is now determined based on the metadata in the npm registry or the git tag.
By default `conventional-changelog-core` use the last git tag.

That can create issues if there is discrepancies between the npm registry and the git tags, as the main `semantic-release` and the `release-notes-generator` plugin use different algorithm to determine the last release commit. Also there is no point in doing the job twice for determining the last release and retrieving the commits or figuring out the new version.

In addition passing `nextRelease` and `commits` might be useful for other plugin implementations.

**Comment by gr2m** [comment]
+1 on this, sounds great 👍
