### ISSUE TITLE
Manually called npm publish, and now my versions are messed up

### ISSUE THREAD

**Issue by meodai** [semantic-release/semantic-release#464]
Sorry to create an issue for that.

I called `npm publish` by mistake in my local repository. This totally messed up my versions on NPM: https://github.com/meodai/color-names Even after editing my git tag's it continues to count up around v0.1.0

Can anyone help me with this?

**Comment by pvdlg** [comment]
It seems you have discrepancy between between your git tags and npm releases.
The last git tag in your repo is `3.8.4` but the last npm release is `3.8.2`.

So you have two options:
1. Delete the git tags `3.8.3` and `3.8.4` and re-run a Travis job. That would trigger a new release using `3.8.2` as the last one
2. Do a manual release from the git tag `3.8.4` (checkout tag `3.8.4`, set your `package.json` version to `3.8.4` and run `npm publish`)

1 would work only if you use `semantic-release@8.1.2` which is the latest release currently available only on the `next` dist-tag.

**Comment by pvdlg** [comment]
@meodai did that solve your issue?

**Comment by meodai** [comment]
@pvdlg I did thanks you.

**Comment by pvdlg** [comment]
No you are not the only one :)
There is quite some confusion on how `semantic-release` works internally and how to recover from situation like that.
#458 should improve the situation when it lands, as it would offer a recovery scenario based on tags and the error logged by `semantic-release` would indicate the steps to follow.
We also need to work on the documentation.
Any contribution is well appreciated !
