### ISSUE TITLE
Out of sync npm version and git release tag

### ISSUE THREAD

**Issue by johnnyBira** [semantic-release/semantic-release#467]
I originally started experimenting setting up semantic release as part of my Pipelines CI on bitbucket, once I got my first release working I decided to start fresh with a clean git history (lots of trial and error commits to the master branch that I'd rather do without).

After creating a new repo and pointing to the same NPM package from before I realise the previously published package already has a release version from my previous experiments, causing the release to fail do to conflicting version numbers.

My question is if there is any way to make semantic release start bumping it's versions from the latest released version of an existing NPM package. I Tried adding the latest version as a tag to my last commit but this didn't do any good. Are there any other factors that semantic release take into account when calculating the next version that I need to alter?

Thank you,
/John

**Comment by pvdlg** [comment]
> Are there any other factors that semantic release take into account when calculating the next version that I need to alter?

Currently semantic-release, get the last version published on npm, look for the commit used to make this release and search for it in the git history.
If there is commit referenced in the `gitHead` property of the last release found on npm then we search for a tag.
#458 will change that a bit, allowing to search for a tag even if there is a `gitHead` in the npm last release when it;s not found in the git history.
 
> I Tried adding the latest version as a tag to my last commit but this didn't do any good.
That should work when #458 lands.

In the meantime the best you can do is a manual release:
- locally change the version manually in your `package.json`
- Run `npm publish`
- Create a git tag and push it to origin
- Create the Github release

**Comment by johnnyBira** [comment]
Thank you for clarifying @pvdlg. I'll give this a shoot.

**Comment by pvdlg** [comment]
> I'll give this a shoot.

Let us know how it goes!
