### ISSUE TITLE
Can't make semantic-release work~

### ISSUE THREAD

**Issue by mamboer** [semantic-release/semantic-release#469]
hi, 
I wanna integrate semantic-release with an existing project [hexo-renderer-scss](https://github.com/mamboer/hexo-renderer-scss), and i had followed the guides in the README also this post https://ciphertrick.com/2017/04/10/automate-package-publishing-nodejs-semantic-release/, but still with no luck while the travis builds are fine.

![image](https://user-images.githubusercontent.com/85879/31382222-85140bb2-ade9-11e7-8df2-64ef7ab88f23.png)

**Comment by pvdlg** [comment]
Could you provide a link to the Travis job in which `semantic-release` fails to publish a new version ? You screenshot doesn't show the `semantic-release` logs.

**Comment by mamboer** [comment]
@pvdlg hi, this's the latest builds https://travis-ci.org/mamboer/hexo-renderer-scss/builds/285981654

**Comment by pvdlg** [comment]
Looking at the logs, in particular this [line](https://travis-ci.org/mamboer/hexo-renderer-scss/jobs/285981655#L1051) it seems it's similar to #444

You should remove the cache in Travis or you can find alternative solution in #444

**Comment by mamboer** [comment]
@pvdlg Thanks so much, i disable the cache and it works.
