### ISSUE TITLE
Commits that merge pull requests in release notes.

### ISSUE THREAD

**Issue by ryansmith94** [semantic-release/semantic-release#471]
Hey, I've noticed recently that if I create a merge commit with a Commitizen commit message, Semantic Release doesn't use that in the release notes. However, it does recognise the commit message in some way because it creates the correct release.

Any idea what could be causing this?

**Comment by gr2m** [comment]
can you point to an example? Or tell us the steps to reproduce it with expected / actual behavior? That’d be very helpful :)

**Comment by pvdlg** [comment]
Both the commit parsing and the release-note generation is handled by [https://github.com/conventional-changelog/conventional-changelog](conventional-changelog) which handle the merge commits: [mergepattern](https://github.com/conventional-changelog/conventional-changelog/blob/master/packages/conventional-commits-parser/README.md#mergepattern).

The way it should work is that the commits referenced by the merge will be analyzed and used for the release note.
So for example if your Merge commit message is:
```
Merge Pull Request #xxx from <repo>/<branch>
fix: This is a fix
feat: This is a feature
```
Then `semantic-release` would analyze and include in the release note 2 commits:
* `fix: This is a fix`
* `feat: This is a feature`

As mentioned by @gr2m it would be helpful to have more information. Especially, what do you mean by "if I create a merge commit with a Commitizen commit message". My understanding is that merge commits are created automatically when you merge a branch.

**Comment by ryansmith94** [comment]
Hey guys, thanks for the quick replies, sorry that I've been so slow to reply here.

### Re @gr2m reply:
#### Steps to reproduce the error
1. Create a pull request in a repository with Semantic Release and Travis.
1. Click "Merge pull request" to "Create a merge commit".
1. Change the short commit description to "fix(scope): Message". This is what I mean by "a merge commit with a Commitizen commit message".
1. Delete the long commit description.
1. Click "Confirm merge".
1. Wait for the Travis CI build to finish on the master branch.
1. View the releases for the Github repository.

#### Expected Behaviour
A new patch release is created with release notes that contain details of the fix based on the short commit description above.

#### Actual Behaviour
A new patch release is created without details of the fix in the release notes.

### Re @pvdlg reply:
Thanks for the links and explanation of how it should work, I'm going to have a look at the links now.

**Comment by ryansmith94** [comment]
To be clear I'm creating the merge commit instead of squashing because I want the author to retain credit for their code. I'm using a Commitizen (conventional) commit message so that Semantic Release is able to make a new release of the correct type (patch/minor/major), because the commits within the PR don't use Commitizen (conventional) commit messages, hence they would not enable Semantic Release to make a new release.

**Comment by ryansmith94** [comment]
I just tried using the default short commit description that Github provides, then tried setting the long commit description to "fix(scope): Message", but that didn't actually make a release.

**Comment by pvdlg** [comment]
I'm not 100% sure how Github handle Merge commit, but it seems it includes the original message from the commits you are merging in addition of what you enter in the commit description during the merge. So in that case `semantic-release` will use the original commit message, which is the expected behavior.

Could you share the repo url you are using? So we can verify exactly the commit message generated by Github in your case?

**Comment by ryansmith94** [comment]
Yeah the repo URL is https://github.com/xAPI-vle/moodle-logstore_xapi.

- An example of a PR that I merged would be xAPI-vle/moodle-logstore_xapi#139.
- The merge commit for that PR is [3b599d4](https://github.com/xAPI-vle/moodle-logstore_xapi/commit/3b599d4c27f195db4fbf4972105291d7af1ef79f).
- The release was [v2.1.5](https://github.com/xAPI-vle/moodle-logstore_xapi/releases/tag/v2.1.5).

The release notes for that release were originally generated to be the following.
> <a name="2.1.5"></a>
> ## [2.1.5](https://github.com/xAPI-vle/moodle-logstore_xapi/compare/v2.1.4...v2.1.5) (2017-10-11)

**Comment by pvdlg** [comment]
`semantic-release` analyze commit on the build branch (`master` in your case). The commit are retrieved with `git log`.
Looking at the commit history of the master branch I see the commit https://github.com/xAPI-vle/moodle-logstore_xapi/commit/3b599d4c27f195db4fbf4972105291d7af1ef79f but I don't see the commits that were part of the PR xAPI-vle/moodle-logstore_xapi#139

So `semantic-release` behave as expected:
- It finds a `fix` commit and determine a `patch` release has to be done
- Publish the version `2.1.5`
- Do a Github release for `2.1.5` including the fix commit

`semantic-release` has no way to know that https://github.com/xAPI-vle/moodle-logstore_xapi/commit/3b599d4c27f195db4fbf4972105291d7af1ef79f is a merge commit of several other commits.

It seems that what you do, when you merge the PR, erase the other commits references.
In effect, according to the commit history of your repo, it's like if you were doing a squash.

I'm not extremely knowledgeable on the specificities of Github when doing a "Merge pull request" and modifying the message. But I can tell you that if you do a "Merge pull request" without editing the message, Github create a "Merge commit" that is recognized by `semantic-release`. In such case `semantic-release` will consider all the commits that are part of the merge commit.

If you want to preserve the commits messages from your contributors, I would advise to:
- Inform contributors that you are using a commit convention (for example [angular](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit))
- Add some tooling to enforce the commit format (for example https://github.com/marionebl/commitlint or https://gitcop.com/)
- Merge your PR with "Merge pull request" or "Rebase and merge"

**Comment by ryansmith94** [comment]
#### Re "So semantic-release behave as expected"
I don't really understand why it creates the correct release using that commit message in xAPI-vle/moodle-logstore_xapi@3b599d4, but doesn't use the commit message for the release notes, that certainly wasn't what I had expected.

#### Re: according to the commit history of your repo, it's like if you were doing a squash
That's not correct. The commits from the PR are in the master branch commit history.

#### Re: Advise
I think forcing people to use a commit convention in order to make a PR would create an unnecessary barrier for contributors to climb, some of which in our case will be using Github for the first time. Most of the pull requests would probably have to be resubmitted with correct commit messages.

I think the only solution here, would be pushing an empty commit with the correct format into the pull request which isn't ideal.

**Comment by pvdlg** [comment]
> I don't really understand why it creates the correct release using that commit message in xAPI-vle/moodle-logstore_xapi@3b599d4, but doesn't use the commit message for the release notes, that certainly wasn't what I had expected.

The commit https://github.com/xAPI-vle/moodle-logstore_xapi/commit/3b599d4, with commit message `fix(AssignmentGraded): Corrects actor format. (#139 - thanks @Nicosoft)` is in the release note for `2.1.5`. 
I don't understand what you mean by "but doesn't use the commit message for the release notes" ?

> That's not correct. The commits from the PR are in the master branch commit history.

Yes. My bad, I didn't went far enough in the master history.

When you merge the PR xAPI-vle/moodle-logstore_xapi#139 and modify the message it result in pushing to `master` the commits:
- `Update AssignmentGraded.php` => Not recognized by `semantic-release` as a valid commit message => ignored by `semantic-release`
- `Function change` => Not recognized by `semantic-release` as a valid commit message => ignored by `semantic-release`
- `fix(AssignmentGraded): Corrects actor format. (#139 - thanks @Nicosoft)` => Contains no reference to the other commits. => `semantic-release` has no way to know it's a merge of `Update AssignmentGraded.php` and `Function change` => `semantic-release` analyze it as a regular commit

> I think forcing people to use a commit convention in order to make a PR would create an unnecessary barrier for contributors to climb, some of which in our case will be using Github for the first time. Most of the pull requests would probably have to be resubmitted with correct commit messages.

There is tools like https://github.com/commitizen/cz-cli that can help with that

> I think the only solution here, would be pushing an empty commit with the correct format into the pull request which isn't ideal.

If you would do so, only this empty commit would be analyzed by `semantic-release` and included in the release note.

`semantic-release` can only use commits it can analyze. All the commits that are not formatted in a way that `semantic-release` can parse will be ignored. I don't see a way to workaround that. But if you have a suggestion we will certainly consider it!

What you can try is to format your merge commit like this:
```
fix(AssignmentGraded): Corrects actor format. (#139 - thanks @Nicosoft)
- Update AssignmentGraded.php (link to commit)
- Function change (link to commit)
```
Only `fix(AssignmentGraded): Corrects actor format. (#139 - thanks @Nicosoft)` will be included in the release note but the commit will reference to the other commits.

**Comment by ryansmith94** [comment]
> The commit xAPI-vle/moodle-logstore_xapi@3b599d4, with commit message fix(AssignmentGraded): Corrects actor format. (#139 - thanks @Nicosoft) is in the release note for 2.1.5.
I don't understand what you mean by "but doesn't use the commit message for the release notes" ?

It's only there because I edited the release notes to contain that, notice that it doesn't have the commit link that it would have had if Semantic Release had included it. I posted the [original release notes before my edit above](https://github.com/semantic-release/semantic-release/issues/471#issuecomment-337920380).

> There is tools like https://github.com/commitizen/cz-cli that can help with that

Thanks, we actually use that elsewhere, but we only expect our internal engineers to use it.

> If you would do so, only this empty commit would be analyzed by semantic-release and included in the release note.

Yeah like I said, it's not ideal, but it does workaround the issue.

**Comment by ryansmith94** [comment]
Nice! Good digging @pvdlg! 👍 Thanks for taking your time to figure that out.

That's awesome, I'll subscribe to #460. Yeah it would seem that not using that `--no-merge` would be the only way to keep the two things consistent. 

Awesome, thanks @pvdlg!

Is there a workaround right now that would allow me to turn off the `no-merge` flag until #460 is resolved?

**Comment by ryansmith94** [comment]
Hey guys, any thoughts on whether there is a workaround right now to pass the no-merge flag down?

**Comment by pvdlg** [comment]
Sorry I missed the question the first time.

I checked and there is no workaround at that moment, as we don't let this option to be configured at the moment.
I'm working on the fix for #460.

**Comment by ryansmith94** [comment]
No worries 😄 Ok. That's awesome, thanks 👍

**Comment by gr2m** [comment]
hey @ryansmith94, #460 has been resolved via #480, you can use the new version by setting the semantic-release version to "^9.0.0"  in your package.json. Can we close this issue?

**Comment by ryansmith94** [comment]
Hey @gr2m, awesome nice work guys! 👍  yeah I already upgraded this morning ([Renovate](renovateapp.com) is awesome - I would recommend it). Yeah I think this issue can be closed, I've not tested it, but looking at the code in #480 (src/index and lib/github-release) it appears to be resolved :smile: I'll reopen if I noticed the problem persists.

**Comment by pvdlg** [comment]
This issue will be completely solve only after we merge https://github.com/semantic-release/release-notes-generator/pull/34 and update the `release-notes-generator` version in `semantic-release`.

**Comment by ryansmith94** [comment]
Okay thanks @pvdlg. I'll reopen this issue until that is merged then.

**Comment by ryansmith94** [comment]
Haha sorry, I just saw that PR got merged, closing again :smile:
