### ISSUE TITLE
Command is exiting on Circle CI without any messages

### ISSUE THREAD

**Issue by DeividasK** [semantic-release/semantic-release#474]
Node version: 8.7.0

**Actual behaviour:**
Running  `./node_modules/.bin/semantic-release pre` on circle ci exits without any messages or error codes.

**Expected behaviour:**
Running  `./node_modules/.bin/semantic-release pre` should output some messages.

`--loglevel verbose` and `--loglevel silly` do not output anything either.

I have managed to use `semantic-release` commands (both `pre` and `post`) locally to publish a package. However, the same commands fail silently on circle when I SSH to circle and follow the same steps I did locally to publish a package. However, on circle `semantic-release` or, more accurately, `./node_modules/.bin/semantic-release pre` exits without any messages or error codes. I can't even get the "command not found" error when I type in random things.

I made sure that all of the same packages are installed on circle.

Any ideas what is happening here?

**Comment by pvdlg** [comment]
That's very strange indeed. Could you share the link to the CircleCi job with the problem ?

**Comment by DeividasK** [comment]
Can't do this, because it is a private repo.

**Comment by pvdlg** [comment]
Ok.
Can you clarify what do you mean by "I can't even get the "command not found" error when I type in random things." ?

**Comment by DeividasK** [comment]
You can find my attempts to run the command below:

![image](https://user-images.githubusercontent.com/9297294/31777959-513bf570-b4e7-11e7-9f28-e51930e15e51.png)

**Comment by DeividasK** [comment]
Hmm, that may be it (because I did this with `semantic-release` command locally), thanks! Will double check this on circle.

**Comment by DeividasK** [comment]
I've checked this in circle, but this didn't change the situation.

![image](https://user-images.githubusercontent.com/9297294/31783420-183cba48-b4f6-11e7-802d-41205b31d43d.png)

Let me know if there's something else you can think of for me to try (I've also opened a support ticket with circle).

**Comment by pvdlg** [comment]
It seems the command return 1, but because it's ran with yarn it doesn't log anything. This is because for now we are using npmlog.

Can you try to run `npm run semantic-release` instead of `yarn run semantic-release` ?

**Comment by DeividasK** [comment]
Here's the output of running `npm run semantic-release` (`semantic-release pre && npm publish && semantic-release post`):

![image](https://user-images.githubusercontent.com/9297294/31809086-f6bd0aa8-b56d-11e7-8a62-ec2206c2dd9b.png)

**Comment by kumarharsh** [comment]
Upgrading from 6.x to latest 8.2.2 is giving me this error:
https://travis-ci.org/kumarharsh/graphql-for-vscode/jobs/292268485

![image](https://user-images.githubusercontent.com/760112/31966885-c6897726-b929-11e7-9cfe-6aaee5191509.png)

I am running node 8.7.0
![image](https://user-images.githubusercontent.com/760112/31966926-e599a5e6-b929-11e7-90f1-e5de9953dc6c.png)

**Comment by pvdlg** [comment]
@kumarharsh can you try to remove `npm prune` ?

**Comment by pvdlg** [comment]
@DeividasK we have just release [v9.0.0](https://github.com/semantic-release/semantic-release/releases/tag/v9.0.0) with a lot of changes, including more logs.

It's released on the `next` dist-tag so you would have to specify `"semantic-release": "^9.0.0"` in your `package.json`.

With this new version, your npm script as to be `semantic-release` instead of `semantic-release pre && npm publish && semantic-release post`.

Could try with this version and let us know if that solve the issue? And if not could you provide the logs?

**Comment by DeividasK** [comment]
@pvdlg thanks for the update!

I've changed my circle CI build to do `semantic-release` instead of `yarn semantic-release` (which runs the predefined script) and it works fine.

So it seems that `semantic-release` script does not seem to be necessary (?), because when I run that `semantic-release pre` part of the script just outputs help commands and finishes.

Personally I consider this issue to be closed.

**Comment by pvdlg** [comment]
Thanks for the feedback!
