### ISSUE TITLE
package-lock.json version field not updated on pre

### ISSUE THREAD

**Issue by aliatsis** [semantic-release/semantic-release#476]
When running `semantic-release pre`, the `version` field in `package.json` is properly updated to the new version. However, the `version` field in `package-lock.json` is not updated.

If the `package.json` and `package-lock.json` versions are not the same, the next time an `npm install` is run in this package, it will create an unstaged change in the repository to fix the mismatch in `package-lock.json`.

Ideally, `semantic-release pre` should write the new version to `package-lock.json` as well, similar to how it currently works for `npm-shrinkwrap.json`.

**Comment by pvdlg** [comment]
`semantic-release` is meant to run on a CI environment. Each time the CI run it download the a fresh repo.
Can you clarify in which scenario this problem happen? Why would you run `npm install` on the CI after the build is done and the release happened ?

**Comment by aliatsis** [comment]
I guess the use case I was describing with `npm install` is only an issue if you push the version changes from CI, then pull locally.

Nevertheless, shouldn't the npm published `package-lock.json` match the published package version when the package is installed into a dependent?

**Comment by pvdlg** [comment]
> I guess the use case I was describing with npm install is only an issue if you push the version changes from CI, then pull locally.

The version change in `package.json` is not meant to be pushed on git. On the git repo it should stay `0.0.0-dev`.

> Nevertheless, shouldn't the npm published package-lock.json match the published package version when the package is installed into a dependent?

No because the `package-lock.json` is not part of the package published on npm.

**Comment by aliatsis** [comment]
ah ok thanks for the help. no issue here then.
