### ISSUE TITLE
Improve troubleshooting documentation

### ISSUE THREAD

**Issue by zeke** [semantic-release/semantic-release#482]
We set up semantic-release a while back on https://github.com/electron/electron-i18n, and it's mostly been good. But we've seen a few hiccups.

We're [currently](https://github.com/electron/electron-i18n/blob/c8daca18b8036ea7f78a23dd567ad90f877ab6fe/package.json#L30) on `semantic-release": "^7.0.2"` which today resolves to 7.0.2

Was expecting a release to happen when we landed https://github.com/electron/electron-i18n/pull/123, but never saw a master-branch build for it show up on Travis:

<img width="1085" alt="screen shot 2017-10-25 at 12 17 00 pm" src="https://user-images.githubusercontent.com/2289/32022386-139b3e30-b98b-11e7-9f04-b87a7ec37f33.png">

Looking at the build logs, I saw this output:

```
2.40s$ npm run semantic-release
> electron-i18n@0.0.0-development semantic-release /home/travis/build/electron/electron-i18n
> semantic-release pre && npm publish && semantic-release post
semantic-release WARN invalid config loglevel="notice"
[Travis Deploy Once]: Success at attempt 1. All 1 jobs passed.
semantic-release ERR! commits The commit the last release of this package was derived from is not in the direct history of the "master" branch.
semantic-release ERR! commits This means semantic-release can not extract the commits between now and then.
semantic-release ERR! commits This is usually caused by force pushing, releasing from an unrelated branch, or using an already existing package name.
semantic-release ERR! commits You can recover from this error by publishing manually or restoring the commit "0c15b40ae552b0172ebc5113467e08999089edbf".
semantic-release ERR! pre Failed to determine new version.
semantic-release ERR! pre ENOTINHISTORY Commit not in history
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-i18n@0.0.0-development semantic-release: `semantic-release pre && npm publish && semantic-release post`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-i18n@0.0.0-development semantic-release script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2017-10-25T19_29_56_932Z-debug.log
```

I cherry-picked the missing commit mentioned above and pushed to master, but it still failed.
So I manually changed the version number in package.json, ran `npm publish`, then reverted the package.json change with `git checkout package.json`.

So we got a release out manually to npm, but no corresponding GitHub Release. So I'm not sure if semantic-release will be able to recover the next time we land semantic changes on master. I will report back as we find out.

cc @codebytere @jkleinsc

**Comment by pvdlg** [comment]
We have implemented a new mechanism in [v8.2.0](https://github.com/semantic-release/semantic-release/releases/tag/v8.2.0) that allow you to recover more easily from the `ENOTINHISTORY`.

See #458 for more details.

The first log you mentioned seems to be a build that happened on the `release-bump` branch and your build branch is configured to be `master`. So it's expected that `semantic-release` doesn't do a release in that case.

**Comment by zeke** [comment]
> The first log you mentioned seems to be a build that happened on the release-bump branch 

You're right. I have edited the original post to remove that tangential detail. Thanks!

**Comment by gr2m** [comment]
can you try with the latest semantic-release version please?

**Comment by zeke** [comment]
Yeah looks like we're back on track. Thanks for the quick responses.

Where would be a good place to document the process for debugging release failures? I can take a shot at that.

**Comment by pvdlg** [comment]
We started that here: https://github.com/semantic-release/semantic-release/blob/caribou/TROUBLESHOOTING.md

Any help would be much appreciated :-)

Just for information we are working on some changes in this PR #480. It's part of a general effort to make `semantic-release` more seamless to use and easier to troubleshoot.

**Comment by pvdlg** [comment]
@zeke should we close this issue? Or would you like to keep it open as a reminder if you are still interested in adding more info in https://github.com/semantic-release/semantic-release/blob/caribou/TROUBLESHOOTING.md?

**Comment by zeke** [comment]
Yeah let's keep it open. I will try to get to it! :)

**Comment by pvdlg** [comment]
Should be fixed by #594

**Comment by zeke** [comment]
Thanks @pvdlg! Sorry for my poor opensourcepersonship here. 😅

**Comment by pvdlg** [comment]
No worries. I was updating the whole documentation anyway.

There is a lot of issues, related to documentation or not that [needs help](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+user%3Asemantic-release+archived%3Afalse+label%3A%22help+wanted%22) if you are interested.
