### ISSUE TITLE
Customize release/publish via plugins

### ISSUE THREAD

**Issue by pvdlg** [semantic-release/semantic-release#484]
Currently `semantic-release` is really tied to npm publish and Github releases, but ideally we should be able to support any platform.

A good solution for that would be to use our plugin mechanism.
In order to support any publish/release type we could add a new type of Plugins, `publish`, that would a pipeline (similar to `verifyConditions` and `verifyRelease`).

We would create the following plugins:
- `npm-publish` that would:
    - Receive the `nextRelease` as parameter
    - Read the npm conf from `package.json` and `.npmrc`
    - Update the version in `package.json` and `npm-shrinkwrap.json`
    - Call `npm publish`
- `github-release` that would:
    - Receive the release `notes` and the `nextRelease`
    - Get the github configuration and auth from `package.json` and environment variables
    - Publish a release, create a tag and optionally upload binaries files to github release

That would completely remove npm and github dependencies in the main `semantic-release`.

The configuration would look like this:
```json
"release": {
  "publish": ["@semantic-release/npm-publish", "@semantic-release/github-release", "other-plugin"]
}
```
We could use by default `@semantic-release/npm-publish` and `@semantic-release/github-release`.

That would allow to solve the numerous issues that request to use `semantic-release` without publishing on npm. It would also allow to easily create plugins for anything else: [apm](https://github.com/atom/apm), Github Pages, Gitlab, Bitbucket etc...

We could even create a simple plugin that just run command set in the configuration.

**Comment by gr2m** [comment]
That sounds super awesome 👍

**Comment by pvdlg** [comment]
There is only one downside: We won't be able to check the NPM and Github token before calling the `npm-publish` and the `github-release` plugin.
So in case of a misconfiguration (for example the NPM token is set but not the Github one) the npm publish would happen but not the github release.

Not sure if we can find a clean solution for that. That's quite a edge case though.

If it's a problem we could check for the NPM and Github token in semantic-release if the `npm-publish` or the `github-release` plugin are configured.

**Comment by gr2m** [comment]
Maybe we can make additional plugins for [verifyConditions](https://github.com/semantic-release/semantic-release#verifyconditions) and make them part of core as well, in which we check that the provided `NPM_TOKEN`/`GH_TOKEN` are valid, and if either isn't, the release will not happen with a helpful error message?

**Comment by ryansmith94** [comment]
This sounds awesome guys. The plugin mechanism you've made is pretty great and it seems perfect to reuse it here 👍

**Comment by ryansmith94** [comment]
In the case of the token issues, is it possible for plugins to throw a common error (like the SemanticReleaseError) that can be caught safely here and then continue to run the other plugins?

**Comment by ryansmith94** [comment]
Ah sorry I misunderstood the issue. Sounds like the plugin idea would be best. Something like `publishConditions` where they all have to be met in order to run the "publish" plugins.

**Comment by pvdlg** [comment]
Working on the implementation, one challenge I'm facing is how to avoid/limit plugins interdependencies and limit redundancy. 

For example with npm we would have 3 plugins:
- `verify-conditions-npm`:
  - check `NPM_TOKEN`
  - Add `NPM_TOKEN` to `npmrc` if not already there
  - Call the registry to make sure the auth works
- `last-release-npm`:
  - check `NPM_TOKEN`
  - Add `NPM_TOKEN` to `npmrc` if not already there
  - Do the stuff we currently do in `last-release-npm`
- `publish-npm`:
  - check `NPM_TOKEN`
  - Add `NPM_TOKEN` to `npmrc` if not already there
  - Update `package.json` and Call `npm publish`

The problem is we repeat 3 times the `NPM_TOKEN` check and the `npmrc`.

In order to avoid that we could do it only in `verify-conditions-npm`. But that would make `last-release-npm` and `publish-npm` dependant on `verify-conditions-npm` which kind of defeat the purpose of plugins...

A solution would be to support "multi-plugins".
Instead of returning an async function, a plugin could return an object with multiple async function, each to be use for a specific plugin type. `semantic-release` would handle both plugins that returns an async function (as of now) and the one returning a "multi-plugin".

In the `npm` example we could create a new plugin `@semantic-release/npm` that would handle the 3 plugins mentioned above. this new would look like that:
```js
// File: lib/set-npm-auth.js
module.exports = () => {
  // check if npmrc has auth setup for the registry
  // If not check NPM_TOKEN and set up the auth in npmrc
};
```
```js
// File: index.js
let verified = false;

module.exports = {
  verifyConditions(pluginConfig, {pkg, options}, cb) {
    // Call set-npm-auth.js
    // Check we can authenticate to the registry
    verified = true;
  },
  getLastRelease(pluginConfig, {pkg, options}, cb) {
    if (!verified) {
      // Call set-npm-auth.js
    }
    // Do the last-release-npm stuff
  },
  publish(pluginConfig, {pkg, options}, cb) {
    if (!verified) {
      // Call set-npm-auth.js
    }
    // Do the npm publish stuff
  },
};
```

The default semantic-release configuration would look like that:
```json
"release": {
  "analyzeCommits": "@semantic-release/commit-analyzer",
  "verifyConditions":["@semantic-release/conditions-travis", "@semantic-release/npm"],
  "getLastRelease": "@semantic-release/npm",
  "generateNotes" : "@semantic-release/release-notes-generator",
  "publish": ["@semantic-release/npm", "@semantic-release/github"]
}
```

`semantic-release` users could opt for different plugins like this:
```json
"release": {
  "verifyConditions":["@semantic-release/conditions-travis", "verify-npm-another-way"],
  "getLastRelease": "get-last-release-another-way",
  "generateNotes" : "@semantic-release/release-notes-generator",
  "publish": ["@semantic-release/npm", "@semantic-release/github"]
}
```
In this situation the `publish` part of our plugin would still work, even though the `verifyConditions` wasn't called.

The "multi-plugin" solution would be a more elegant way to handle plugin interdependencies as it would:
- Allow to have multiple related plugins sharing some code (the `lib/set-npm-auth.js`)
- Allow to have multiple related plugins sharing a state (the `verified` value)
- Allow users to opt-in/out of some plugins

The constraint for "multi-plugin" is that they have to even if not all their su-plugin have been called. For example, the `getLastRelease` function of the npm multi-plugin has to work even if the `verifyConditions` function hasn't been called.
Sub-plugins have to work individually but can provide extra features if they are use with some their other sub-plugin (in the example above the "extra feature" is to not check and setup the npm auth multiple times).

Not directly related we should support shortcut for plugins name in the config, for example we should allow to use `"verifyConditions":["travis", "npm"]"` instead of `"verifyConditions":["@semantic-release/conditions-travis", "verify-npm-another-way"]`

Feedback welcome !

**Comment by gr2m** [comment]
> The problem is we repeat 3 times the NPM_TOKEN check and the npmrc update.

I don't think that is actually a problem, if the logic is all contained in one library that all plugins depend on. Another possibility is to have a state that is shared across all plugins, so `verify-conditions-npm` could set `state.npmToken` and then the others would depend on `npmToken` to be set.

> Not directly related, but we should also support shortcuts for plugins name in the config, for example we should allow to use "verifyConditions":["travis", "npm"]" instead of "verifyConditions":["@semantic-release/conditions-travis", "@semantic-release/npm"]

I think the long version is much clearer, I wouldn't shorten it :) At least lets start with the long form and we can discuss if we want to support the short form later?

**Comment by pvdlg** [comment]
> I don't think that is actually a problem, if the logic is all contained in one library that all plugins depend on.

I agree, that was my original though. It's just that we are going to read the `.npmrc` 3 times. But that's really not a big deal. It's a matter a ms, so not relevant.

> At least lets start with the long form and we can discuss if we want to support the short form later?

OK

> Another possibility is to have a state that is shared across all plugins, so verify-conditions-npm could set state.npmToken and then the others would depend on npmToken to be set.

I'm not sure it's a good idea, because that would create a lot of dependencies between plugins. And with third parties plugin (not maintained by us) that can get out of control quickly. For example if another plugin that to run before didn't set a variable due to a bug, then we have a broken plugin that can't be fixed until the dependent is fixed.
Having a state in a "multi-plugin" module create also additional complexity but at least this complexity is limited within the module...

All the scenario of interdependent plugins that can think of are related to verifying a config/auth in a plugin then doing something that require this config/auth to be set in another plugin.
Maybe it doesn't worth to add some complexity, and the 3 plugins using a common library is enough. So yeah I'm undecided...

**Comment by buehler** [comment]
What if...
The plugins can export a list of prerequisites? So actually a list of predicate-functions that return a boolean. So the first step of the core would be: Gather all those predicates and run them. If all return true, do the rest of the stuff. If a predicate fails, throw an error with the name of the plugin (and maybe with a description of the error?)

**Comment by gr2m** [comment]
@buehler we already have that with [verifyConditions](https://github.com/semantic-release/semantic-release#verifyconditions) I think? Or what is there anything missing?

@pvdlg I gave it all some more thought tonight and overall this all makes a lot of sense. I’d move forward with the "multi-plugin" idea. It also makes sense e.g. for `analyzeCommits` and `generateNotes`, both currently depend on `conventional-changelog`.

I think a default configuration like this would make a lot of sense: 

```
"release": {
  "verifyConditions": [
    "@semantic-release/travis", 
    "@semantic-release/npm",
    "@semantic-release/github"
  ],
  "getLastRelease": "@semantic-release/npm",
  "analyzeCommits": "@semantic-release/conventional-changelog",
  "verifyRelease": [
    "@semantic-release/lts"
  ],
  "generateNotes" : "@semantic-release/conventional-changelog",
  "publish": [
    "@semantic-release/npm", 
    "@semantic-release/github"
  ]
}
```

`analyzeCommits`, `getLastRelease` and `generateNotes` are clear, they only can have one value. But `verifyConditions`, `verifyRelease` and `publish` are arrays. What happens if  I set `"verifyConditions": ["./script/my-custom-verification-plugin"]`? Will it replace the default plugins, or add to it? I’d say they replace the default values, and if I want to keep them, I have to list them explicitly. 

In my example above I’ve added `verifyRelease` because I think we will need a default verification to support LTS/legacy version releases.

I’m no longer sure about `generateNotes`. At least for our github/npm default, release notes are only relevant for GitHub. Maybe we should move the logic there? Can you think of examples where for example we would want to publish to a GitHub release and another platform which would also include the release notes? Would it want the exact same release notes or maybe different ones per target? I don’t know.

> in case of a misconfiguration (for example the NPM token is set but not the Github one) the npm publish would happen but not the github release. Not sure if we can find a clean solution for that. That's quite a edge case though.

It's actually not an edge case at all. I run into the problem that a package got released but the GitHub release was not created quite a bit. I wish we already had a built-in verifiy plugin for both npm & github today. They plugins would not only check if the respective tokens are set, but also if the tokens include authorization to make the respective releases.

**Comment by pvdlg** [comment]
> @pvdlg I gave it all some more thought tonight and overall this all makes a lot of sense. I’d move forward with the "multi-plugin" idea.

Agreed. I'm on it!

> It also makes sense e.g. for analyzeCommits and generateNotes, both currently depend on conventional-changelog.

I'm not sure about that. They both depends on `conventional-changelog-parser`, but share almost no code in common other than loading the presets and calling the parser. They also do not depends on each other in a any way (sharing a state wouldn't provide any benefit), so I'm not sure there is any benefit in merging those two.

> What happens if I set "verifyConditions": ["./script/my-custom-verification-plugin"]? Will it replace the default plugins, or add to it? I’d say they replace the default values, and if I want to keep them, I have to list them explicitly.

Yes it will replace the default and will not concatenate the array with the default. In that situation only `my-custom-verification-plugin` will be executed.

> In my example above I’ve added verifyRelease because I think we will need a default verification to support LTS/legacy version releases.

Agreed. We need to specify how that would work. Maybe `lts` is not the ideal name as the plugin would allow to  handle `lts`, `latest` and `next`.

> I’m no longer sure about generateNotes. At least for our github/npm default, release notes are only relevant for GitHub. Maybe we should move the logic there? Can you think of examples where for example we would want to publish to a GitHub release and another platform which would also include the release notes? Would it want the exact same release notes or maybe different ones per target? I don’t know.

Currently the plugin generate releases note that works for Github, Gitlab and BitBucket.
I think we should keep `generateNotes` as is as it would allow folks to replace it by a custom plugin. This way they can customize the release note but still use our future Github release plugin.
If we remote the `generateNotes` plugin folks would who want a different release note would have to write a plugin that do both the release note and the release on Github/Gitlab/Bitbucket. 

Ideally, instead of a `github` plugin we should do a `repository` plugin that would do verifications and make the release on Github, Gitlab or Bitbucket based on the repository URL.

> It's actually not an edge case at all. I run into the problem that a package got released but the GitHub release was not created quite a bit. I wish we already had a built-in verify plugin for both npm & github today. They plugins would not only check if the respective tokens are set, but also if the tokens include authorization to make the respective releases.

Yes. That will be solved by the "multi-plugin" design.

**Comment by FuzzOli87** [comment]
The ability to customize the publish/release would be a huge plus. That means we could use it to version app docker images for instance!

**Comment by pvdlg** [comment]
> The ability to customize the publish/release would be a huge plus. That means we could use it to version app docker images for instance!

Even with the customization of the publish/release, `semantic-release` will still require to have a `package.json` to defined the dependency and the npm script and to read some configuration.

But the reliance on a `package.json` should't be too hard to eliminate.
The release of docker image seems to be an interesting use case to cover. Could you provide a bit more information on such workflow, so that would help us to define the next steps to support it. In particular:
- How the release is done? If possible could you provide a link to the documentation explaining how to make the release?
- And example of a docker project

Thanks !

**Comment by FuzzOli87** [comment]
@pvdlg I don't have much in the way of documentation since it's pretty theoretical. However, the huge benefit in my opinion is the automation of release-notes creation and tagging on GitHub. If I'm creating an Node webserver for example, those can be crucial and makes it easier for developers to keep track of their work.

In that sense, I don't think the dependence on a package.json file is a big deal, at least since I'm imagining just Node applications at the moment.

As far as releasing docker images, I imagine this is CI/CD dependent so I'm going to talk about using Codefresh.

It works like most other CI/CDs, it watches a repo, does things when changes happen. It also allows us to dynamically create environment variables that it can then use when creating the final image before pushing it to a image repository.

So I imagine that being able to configure the "publish" step so that instead of publishing to NPM, it would run a custom script and pass things like the new version information, which we can then use to create an environment variable so that when Codefresh is ready to create the image, it would tag the final image with the version that semantic-release created.

Being able to handle the metadata in some way(maybe the publish step instead writes a file) after doing everything else like updating github etc would open the door to many types of uses.

I'll try and emulate this through a Dockerfile to use as an example soon.

**Comment by pvdlg** [comment]
> So I imagine that being able to configure the "publish" step so that instead of publishing to NPM, it would run a custom script and pass things like the new version information, which we can then use to create an environment variable so that when Codefresh is ready to create the image, it would tag the final image with the version that semantic-release created.

This is the type of detail I'd be interested about. I don't know anything about Codefresh or how to publish a Docker image.
Ideally I'd like to make the plugin system flexible enough to handle such case. So that would be helpful to know which type of script would have to be run, with which param.
So I can make sure the plugin system will allow to create a plugin to handle such case.

This type of release could be done with either a dedicated plugin or a generic plugin that run script. I just want to be sure we pass enough information to the custom plugin or if we create a generic script plugin that we have a way to pass the correct information to it.

**Comment by FuzzOli87** [comment]
@pvdlg 

To create a Docker image to be released to a Docker repository, it's a simple matter of running a command ```docker build -t <imagename>:<tag> .``` So, for example ```docker build -t test-app:1.2.4 .``` Then to publish it it's just a matter of running ```docker publish test-app:1.24``` and thats it! That is the process Codefresh goes through.

So, the plugin can be many things. It can be dedicated to execute these commands, or just a generic plugin that passes in meta data like the new version semantic-release came up with and any other relevant information and I can use that information to create a file that then Codefresh could use to extract tag information from, or heck I can even create new environment variables that Codefresh can use when tagging the image.

The most important information for the publishing of docker images would be the version number. Then we can do with the information whatever we want as a generic plugin or it opens the door for developers to write custom plugins for certain CI/CDs etc.

**Comment by pvdlg** [comment]
Here's an update on the progress.

Initial PR for `npm` and `github` plugins:
- https://github.com/semantic-release/npm/pull/1
- https://github.com/semantic-release/github/pull/1

Modifications for `semantic-release` to use these new plugin will follow shortly.

**Comment by raix** [comment]
I'm currently trying to follow along adding support for vs code extensions and meteor packages:
* [semantic-release-meteor](https://github.com/raix/semantic-release-meteor)
* [semantic-release-vsce](https://github.com/raix/semantic-release-vsce)

Question would it be possible to load a release config from the cli?

@pvdlg Looking forward to the mods :)

**Comment by felixfbecker** [comment]
Is it possible to already try out the GitHub release binary publishing? Currently using semantic-release v8 with vsce for vscode extensions.

**Comment by pvdlg** [comment]
We just release `semantic-release@10.0.0` on the dist-tag `next` that include the possibility to configure the publish plugins (by default npm and github).
I'm not sure what you mean by "binary publishing". If you mean the possibility to publish file in the Github release, see https://github.com/semantic-release/github#assets-option

If you mean publishing with something else than npm or github, that is possible with a custom publish plugin.

**Comment by felixfbecker** [comment]
Yes, I mean "assets". GitHub calls that "binaries":

![image](https://user-images.githubusercontent.com/10532611/33102106-1f6ae850-ced0-11e7-8f11-2c825e3557e5.png)

**Comment by pvdlg** [comment]
Ok, in that you can use `semantic-release@10.0.0` with the configuration here: https://github.com/semantic-release/github#assets-option

Let us know if that works for you!

**Comment by felixfbecker** [comment]
I'll definitely try it out!

**Comment by felixfbecker** [comment]
@raix very interested in sematic-release-vsce! Is it usable already?

**Comment by felixfbecker** [comment]
If anyone is interested, I published https://github.com/felixfbecker/semantic-release-docker to release docker images to Docker Hub

**Comment by kumarharsh** [comment]
@felixfbecker there is https://github.com/kumarharsh/semantic-release-visualstudio-marketplace-version which you might be interested in.

**Comment by simlu** [comment]
I can't find where any documentation on how to use this to only publish to github (and not npm). Ideally this would be a cli option to disable npm release. How do I achieve this?

Basically I want to run `semantic-release-cli setup`, but not publish to npm.

**Comment by kopax** [comment]
- Can I publish on Gitlab and use a Gitlab and a Github repository ?

So far I want only gitlab, maybe github later when we go open source, I don't understand how to do it.

**Comment by pvdlg** [comment]
I would suggest to not comment on unrelated closed issue as your questions probably won't be addressed this way. Please see our [get help section](https://github.com/semantic-release/semantic-release#get-help) to find support.
