### ISSUE TITLE
Consider a Node LTS Policy

### ISSUE THREAD

**Issue by destroyerofbuilds** [semantic-release/semantic-release#485]
I'd like to continue the discussion we started in the GitLab support issue regarding Node LTS support - https://github.com/semantic-release/semantic-release/issues/37#issuecomment-332071036

Would y'all consider adopting an LTS policy to help provide assurance to users, including corporate users, that `semantic-release` will be able to successfully release a new version of a project while running `semantic-release` on an LTS version of Node?

**Comment by gr2m** [comment]
We can commit to the Node LTS schedule starting with Node 8 becoming LTS in 5 days (Oct 31). We will not add support for versions smaller than Node 8

**Comment by gr2m** [comment]
To add our motivation behind it: we also have only so much time to maintain the project. Limiting support to just Node 8 has very small impact for this project specifically, but quite a big impact on code maintainability overhead

**Comment by destroyerofbuilds** [comment]
@gr2m if `semantic-release` were to adopt an LTS policy, it would mean supporting an LTS for 30 months (Two and a half years). 

Would y'all be comfortable with that?

Because of an early OpenSSL EOL it would mean supporting Node 8 until December 2019.

**Comment by gr2m** [comment]
if that means it would unblock you from joining forces with gitlab support, then yes :)

**Comment by pvdlg** [comment]
As mentioned in #445 my personal preference would be to use `babel-register` and `babel-polyfill` as it makes life easier for both maintainers and users.

You can see an exemple in semantic-release/cli#146, specifically this [commit](https://github.com/semantic-release/cli/pull/146/commits/8d1c32f1704477ed4d219e6340a5e13b9bcee41c).
As you can see it's as simple as 2 lines of code and 3 dependencies.
The only constraints is that we can't use Node API added after version 4, but the only one we use is [promisify](https://nodejs.org/api/util.html#util_util_promisify_original).

I frankly don't have a strong opinion on that and I use Node 8 everywhere anyway.
But if not supporting Node 4 or 6 or anything version is a problem for folks, which is totally understandable, then it's a good solution that works for everyone.

**Comment by destroyerofbuilds** [comment]
> if that means it would unblock you from joining forces with gitlab support, then yes :)

It would be a long-term impediment to my own personal ability to contribute, yes.

May I submit a Pull Request for a Node LTS policy in the README file, with the caveat that it takes effect starting with Node 8 LTS?

**Comment by gr2m** [comment]
yes, okay with me 👍 thanks!

**Comment by destroyerofbuilds** [comment]
@gr2m can you please assign the issue to me and apply any appropriate labels?

**Comment by gr2m** [comment]
done 👍
