### ISSUE TITLE
How to disable npm publish for v9

### ISSUE THREAD

**Issue by ryansmith94** [semantic-release/semantic-release#487]
Is there anyway to just disable the `npm publish` step in v9? I've been looking through e2a8a5c and I can't seem to find anyway to turn it off.

**Comment by gr2m** [comment]
it's currently not possible, but @pvdlg is exploring it at https://github.com/semantic-release/semantic-release/issues/484, can we take the discussion there?

**Comment by ryansmith94** [comment]
Yeah sure thanks @gr2m 👍
