### ISSUE TITLE
Publish v9.x releases to npm?

### ISSUE THREAD

**Issue by dwiyatci** [semantic-release/semantic-release#498]
Soon to be expected? :)

**Comment by pvdlg** [comment]
It's already published in the dist-tag `next`. You can use with `"semantic-release": "^9.1.0"` in your `package.json`.

Before publishing on the `latest` dist-tag, I think It's probably better to implement #484 first to avoid breaking build that do not use npm.

**Comment by dwiyatci** [comment]
Ahh. Sorry, my bad. Got it now! 👌 

Feel free to close this once the `latest` dist-tag is published.

**Comment by pvdlg** [comment]
We will update #411 once we release on `latest`. Feel free to subscribe to this issue.
