### ISSUE TITLE
sh: 1: semantic-release: not found

### ISSUE THREAD

**Issue by stoffern** [semantic-release/semantic-release#499]
```
> semantic-release pre && npm publish && semantic-release post
sh: 1: semantic-release: not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! app@0.0.0-development semantic-release: `semantic-release pre && npm publish && semantic-release post`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the app@0.0.0-development semantic-release script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
```

What am i doing wrong? `semantic-release` is in the package.json and i have cleared the Travis cache..
Same error..

**Comment by pvdlg** [comment]
Could you provide a link to your repo? Or at least your `package.json` and `travis.yml` ?

**Comment by stoffern** [comment]
https://github.com/stoffern/universal-app

**Comment by gr2m** [comment]
it runs `yarn` instead of `npm install` and I don’t know why ... I'm not familiar with yarn but can there be a reason that it doesn't install `semantic-release` from the dev dependencies? 

Can you add `npm ls semantic-release` to `before_script` to see if it gets installed?

**Comment by pvdlg** [comment]
I think Travis use `yarn` if it finds a `yarn.lock` file but no `package-lock.json`.

But if I install with `yarn install` and run `npm run semantic-release` it works... Not how installing with `yarn` is causing the issue.

**Comment by stoffern** [comment]
I think the answer may be here: https://github.com/yarnpkg/yarn/issues/2739
Trying to set it into development mode on Travis..

**Comment by gr2m** [comment]
I looked for `NODE_ENV=production` but it doesn't look like your travis build set this environment variable

**Comment by stoffern** [comment]
removing yarn.lock and generating package-lock.json seems to fix it..
Yet there is a new error:

```
WARN invalid config loglevel="notice"
[Travis Deploy Once]: There is only one job for this build.
npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.
```

**Comment by pvdlg** [comment]
It's not an error, just warning from `npm. You are using a `prepublish` script [here](https://github.com/stoffern/universal-app/blob/master/package.json#L9) and that's a deprecated feature. You should replace it by `prepare` or `prepublishOnly `.

See https://docs.npmjs.com/misc/scripts#prepublish-and-prepare

**Comment by stoffern** [comment]
thanks 😉 
Yet there seems to be a problem using yarn. I will close this for now but it may be reopened if more people get this error in the future..
