### ISSUE TITLE
Make "Failed to determine new version." error more descriptive

### ISSUE THREAD

**Issue by gr2m** [semantic-release/semantic-release#50]
You never should `git push -f` to master, we know, but it might happen anyway. If semantic-release cannot "determine new version" because the git commit hash it uses for it's range of commits to be parsed, then it could provide a better error message, with probably a link to FAQ on how to manually release a new version in such cases?

Here's  an example
https://travis-ci.org/hoodiehq/pouchdb-hoodie-api/jobs/72318979#L5137

**Comment by boennemann** [comment]
The error is happening when extracting the commits: https://github.com/semantic-release/semantic-release/blob/next/src/lib/commits.js

I think there are more reasons why this could fail, so it would be better to explicitly test if the hash is in the history first. `git branch -a --contains ${hash}`

(I haven't fully thought this through, but maybe this also opens up the opportunity to recover from this error by checking if a git tag with the same version number, but a different hash, exists. We could try to parse again from there.)

Do you want to send a PR for this (ignore the git tag thing for now), or should I do it once there is some time left?

**Comment by gr2m** [comment]
I won't have time anytime soon. First come, first PR'd :) And the problem is well described now, anyone could come in and try to fix it

**Comment by remy** [comment]
How would you go about testing this if someone like me wanted to try to fix it?

**Comment by remy** [comment]
Sorry, more specifically, I'm only getting the error in travis, when I dry-run on my local machine, it doesn't produce this error

**Comment by boennemann** [comment]
I've now added the helpful error message: https://github.com/semantic-release/semantic-release/commit/5cc7da6035e22660848c7960c9d18e6df1b7b0eb#diff-c82ff4edea7a03060298416c6d869999R29

I figured "recovering" from the error is not reliably doable.
