### ISSUE TITLE
Semantic Release GitHub App - done

### ISSUE THREAD

**Issue by olstenlarck** [semantic-release/semantic-release#501]
Heya :wave: (https://github.com/apps/semantic-release-app)

After the recent problems with `semantic-release` that i had and was (and actually partially still am) totally blocked to continue my work... Just happened to start a Probot Github App from scratch. And, actually it is pretty easy to get started with that fun framework and I built it in no time and almost in no lines - around 150 lines.

I initially was thinking that everything could be done in the app, but it can't, because unfortunately NPM registry does not support publishing from API, but only from `npm publish` which in turn force us to have package in every project that will do that (actually what that package does currently).

So, finally it turns out that the only thing that we can handle is Github releasing, which is what my Probot app currently does and totally works. So in this case we can just remove everything related to Github from both `semantic-release-cli` and `semantic-release` and just require users to activate the Github app. The only thing that we'll need github credentials (username+password or token) is to auth in travis - but should be updated to require them only if Travis CI is selected, otherwise just not even touching and asking for Github related things.

You can see it on https://github.com/tunnckoCore/semantic-release-app currently and need some more organization job & writing tests, but nothing more. We also need place to host it. Probably we'll be able to ask Probot org to host it when we wrote at least some tests.

/cc @gr2m @boennemann & others

**Comment by gr2m** [comment]
Thanks @olstenlarck, I have lots of thoughts on a semantic-release GitHub app, but didn't get to put it into a document yet :( hopefully soon! I'm a big fan of Probot, too. I’m a contributor myself and build some tooling around it. I’ll try to have a look at your app tomorrow 👍

**Comment by olstenlarck** [comment]
Great! It seems to work fantastic https://github.com/olstenlarck/probot-test/releases! :tada: :taco: 

It's already pretty well organized and is good to read :)

**Comment by olstenlarck** [comment]
Anyone can try it https://github.com/apps/semantic-release-app - it's live now :)

**Comment by gr2m** [comment]
hey Charlike I didn’t get to the app today I’m afraid. 

Could you please add a note to the description that it’s not an official app from semantic-release and maybe add a link to this issue here? I just don’t want folks to be confused, because it looks somewhat official but it’s not (yet) ;)

**Comment by olstenlarck** [comment]
O yea yea, sorry.

**Comment by felixfbecker** [comment]
Instead of a GitHub app, wouldn't it make more sense to have a Travis deploy provider?

**Comment by olstenlarck** [comment]
Not so. GitHub is most widely used and CIs are more different per project and self preferences. If we have such app, then we only need to handle the npm part in the `semantic-release` package. Which also means lower dependencies and codebase.

**Comment by destroyerofbuilds** [comment]
@olstenlarck is the app no longer there?

I'd really like to see an app like this to further lower the barrier to automated releases. With an integrated app, no need for people to create release stages in their CI, or configure GitHub tokens.

Just register the app, and done!

**Comment by olstenlarck** [comment]
Actually yea, it's up but is called `new-release` currently (damn, should change it's description too, just forgot that). Because to not confusions with the Semantic Release team and etc stuff. Also it is good works perfectly currently with `new-release` npm package :) Few packages are autoreleased with both of them :)

That's it https://github.com/apps/new-release. As about https://www.npmjs.com/package/new-release - it needs only $NPM_TOKEN to exist as global ENV in the CI, which is pretty enough. You can see some example CircleCI config in [triage-new-issues app](https://github.com/tunnckoCore/triage-new-issues/blob/master/.circleci/config.yml).

Travis in anyway isn't good. Or i'm just not aware of some way to set global env (as like it is possible in CircleCi), you always should add it per project which is too much for me.

**Comment by destroyerofbuilds** [comment]
CC @rarkins

@olstenlarck, cc'd Rhys, as he currently has the [release](https://github.com/apps/release) app to provide a very similar service (Though I don't think it actually does anything at the moment).

I'd love to eventually check out your project. As I noted earlier, it'd be nice if all I had to do was just add an app and be done.

At the moment I think the only concern I have is whether there's feature parity between `new-release` and `semantic-release`.

If not, it would seem like a great opportunity to share core functionality between the too for ensuring a consistent developer experience.

**Comment by olstenlarck** [comment]
Yup, core behind both are almost the same. And trying to get some more little time to finish all the things.

> cc'd Rhys, as he currently has the release app to provide a very similar service (Though I don't think it actually does anything at the moment).

Ha! Cool, didn't noticed that, because i'm not active last week.

**Comment by olstenlarck** [comment]
Just to share how cool is everything and that the Github app and `new-release` works great together.

It's just fantastic to woke up that way in the morning :hear_no_evil: Check out last few releases of https://github.com/tunnckoCore/hela-config-tunnckocore/releases which are totally automated ;]

![2017-12-04-10 26 17_1280x1024_scrot](https://user-images.githubusercontent.com/5038030/33542953-cda2a20c-d8dd-11e7-9eff-a91a2d2e7cb6.png)
![2017-12-04-10 26 46_1280x1024_scrot](https://user-images.githubusercontent.com/5038030/33542952-cd7b9e32-d8dd-11e7-8b1b-065292ab63fb.png)

**Comment by gr2m** [comment]
Hey @olstenlarck I’m glad you got your app working, I’ll definitely check it out myself over the holidays :) I’ll close the issue as it’s not an open bug or feature request, but please feel free to keep commenting updates so that folks interested in it can subscribe to the issue and stay up-to-date :)

**Comment by olstenlarck** [comment]
Great to hear that :) Yea, no problem. When it is really ready we can discuss more things (missing things, etc) about it and eventually adjust both things - most users, sadly use Travis, so we must do something for this (i totally don't have welling to mess with Travis; at least until their package is good). It would be great if this community can use the app, so i'm also open to rename it once everything is clear.

**Comment by felixfbecker** [comment]
> most users, sadly use Travis

@olstenlarck curious why you think it's sad most users use travis?

**Comment by olstenlarck** [comment]
Cuz, definitely, CircleCI has enormous speed and advantages. Or at least i feel it and see it that way.

**Comment by felixfbecker** [comment]
I work with both intensively and from my experience they are roughly the same.

But Circle has some really annoying aspects especially in the context of semantic release. They don't build PR merge commits, but only the branch tips, and share the builds between different PRs from the same head commit. That prevents you from using something like commitlint to lint the commit messages included in a PR to make sure they conform to conventional commit style before merging, which is essential to semantic-release. There is no way to figure out what commits are part of this PR build because there is not a 1:1 mapping between builds and PRs.

**Comment by olstenlarck** [comment]
Agree. But I more think that such things like `commitlint` must be done before commiting phase, so it's totally impossible to even commit if you don't follow community rules - read the READMEs, docs, contributing guides and then consider everything other, otherwise you are just not welcome. :laughing: Sorry, but i can't do much if you can't read :D 

It's just my mindset. So, in short, that aspect of CircleCI is not a problem for me.

**Comment by felixfbecker** [comment]
Of course, commitlinting should be done before committing, code linting should be done before linting (best in the editor), tests should be run before committing, etc etc. But people can always circumvent it (and sometimes it's just not worth the time). Commit with `--no-verify` and no git hooks are run. Make a commit in GitHub's online editor and nothing will be checked. Every check you may have locally in a git hook must be replicated in CI to prevent bad things from ever getting into master. That's why CI is used to run tests - otherwise we could just say "remember to run everything locally". _Remembering doesn't scale_.

**Comment by olstenlarck** [comment]
Agree. But the CI still runs all of my jobs that I run locally so... I don't need github apps for this.
