### ISSUE TITLE
Timeout because other job is still pending

### ISSUE THREAD

**Issue by gr2m** [semantic-release/semantic-release#502]
... while it is not? Might have been a Travis hiccup?

https://travis-ci.org/octokit/fixtures/jobs/296603407#L1739

**Comment by pvdlg** [comment]
It's really weird how it jumped from attempt 2 to 112....
It seems the job was running for a while but the logs were lost.

**Comment by gr2m** [comment]
I dunno, I’ll close the issue, we can investigate it if it happens again
