### ISSUE TITLE
making the step of githubRelease optional

### ISSUE THREAD

**Issue by coolgod** [semantic-release/semantic-release#507]
Our company is using semantic-release internally, it's a very good tool.
We're trying to use it in a more customized way, so we don't really want to publish the release notes to github.

I think it's better to make this step optional?
https://github.com/semantic-release/semantic-release/blob/caribou/src/index.js#L57

**Comment by pvdlg** [comment]
This should be the case soon :-)
See #484

**Comment by gr2m** [comment]
@coolgod I’d suggest you subscribe to the #484 issue that Pierre mentioned, once it’s released, try to build a custom plugin for it and create a follow up issue if you run into any trouble :)
