### ISSUE TITLE
How to run  [ npm publish --acess public] in the new version

### ISSUE THREAD

**Issue by abalad** [semantic-release/semantic-release#510]
How to pass the parameter --access public in this new version of semantic-release, because before I needed to perform the following command to publish the version:

`npm publish dist / --access public`

**Comment by pvdlg** [comment]
You can set the `access` to `public` in your `package.json`:
```json
  "publishConfig": {
    "access": "public"
  },
```

If you want to limit what's included in the published package (i.e. include only the `dist` directory) you can configure that in the `files` property of you `package.json`:
```json
"files": ["dist"]
```

**Comment by abalad** [comment]
@pvdlg Thanks, I did not know these package.json keys. I'll use them right now ;)

**Comment by pvdlg** [comment]
@abalad does that solve your issue?

**Comment by abalad** [comment]
@pvdlg Solved yes you can close it ;) Thx.
