### ISSUE TITLE
Is it possible to configure a branch<->dist-tag mapping?

### ISSUE THREAD

**Issue by jeffijoe** [semantic-release/semantic-release#511]
For example, I'd like all commits on `master` to be released as `latest` on npm, and commits on `next` branch be released as `next` tag on npm.

Is this possible?

Great tool by the way! 👍

**Comment by jeffijoe** [comment]
@pvdlg thank you! That makes perfect sense! 👍 

How about supporting pre-releases, such as `1.0.0-alpha.4`? Is there a pending proposal for this?

**Comment by pvdlg** [comment]
There is several issues opened with more or less related questions. Feel free to search in the issue tracker.

**Comment by pvdlg** [comment]
Duplicate of #563.

Feedback welcome in #563. Thanks !

**Comment by pvdlg** [comment]
Feedback welcome in #563. Thanks !
