### ISSUE TITLE
Generate Release Notes failing with 404?

### ISSUE THREAD

**Issue by ryan-kimber** [semantic-release/semantic-release#513]
Any help would be greatly appreciated.

We have other projects that are working just fine. This is on semantic-release@9.1.1.

Semantic-release is finding the right 'next' tag in NPM and properly publishing to NPM, but then fails with a 404 when writing the release notes to GitHub. I've done a side-by-side comparison of settings and log messages for our working repos and this one, but I can't see any difference.

>2017-11-14T22:35:01.617Z semantic-release:publish-npm Publishing on npm
>2017-11-14T22:35:01.617Z semantic-release:publish-npm cmd: 'npm publish'
>2017-11-14T22:35:01.617Z semantic-release:publish-npm stdout: '+ @formhero/fh-cors-middleware@1.2.1'
>2017-11-14T22:35:01.617Z semantic-release:publish-npm stderr: ''
>2017-11-14T22:35:01.617Z semantic-release:publish-npm code: 0
>[Semantic release]: Call plugin generate-notes
>2017-11-14T22:35:01.624Z semantic-release:release-notes-generator version: '1.2.1'
>2017-11-14T22:35:01.625Z semantic-release:release-notes-generator host: 'github.com'
>2017-11-14T22:35:01.625Z semantic-release:release-notes-generator owner: 'formhero'
>2017-11-14T22:35:01.625Z semantic-release:release-notes-generator repository: 'fh-cors-middleware'
>2017-11-14T22:35:01.625Z semantic-release:release-notes-generator previousTag: '478833c2ff671a7d301d2e55e4218a9e8f66f0aa'
>2017-11-14T22:35:01.625Z semantic-release:release-notes-generator currentTag: undefined
>2017-11-14T22:35:01.699Z semantic-release:github-release Github host: undefined
>2017-11-14T22:35:01.699Z semantic-release:github-release Github port: undefined
>2017-11-14T22:35:01.699Z semantic-release:github-release Github protocol: null
>2017-11-14T22:35:01.699Z semantic-release:github-release Github pathPrefix: null
>2017-11-14T22:35:01.699Z semantic-release:github-release release owner: 'formhero'
>2017-11-14T22:35:01.699Z semantic-release:github-release release repo: 'fh-cors-middleware'
>2017-11-14T22:35:01.699Z semantic-release:github-release release name: 'v1.2.1'
>2017-11-14T22:35:01.699Z semantic-release:github-release release branch: 'develop'
>2017-11-14T22:35:01.722Z semantic-release:github-release Create git tag 'refs/tags/v1.2.1' with commit '8f1c9771bc4e4deb25bf3da93118dc6e2163c8e1'
>[Semantic release]: An error occurred while running semantic-release: { [Error: {"message":"Not Found","documentation_url":"https://developer.github.com/v3/git/refs/#create-a-reference"}]
  message: '{"message":"Not Found","documentation_url":"https://developer.github.com/v3/git/refs/#create-a-reference"}',
  code: 404,
  status: 'Not Found',
  headers: 
   { server: 'GitHub.com',
     date: 'Tue, 14 Nov 2017 22:35:01 GMT',
     'content-type': 'application/json; charset=utf-8',
     'content-length': '106',
     connection: 'close',
     status: '404 Not Found',
     'x-ratelimit-limit': '5000',
     'x-ratelimit-remaining': '4999',
     'x-ratelimit-reset': '1510702501',
     'x-oauth-scopes': 'repo',
     'x-accepted-oauth-scopes': '',
     'x-github-media-type': 'github.v3; format=json',
     'access-control-expose-headers': 'ETag, Link, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval',
     'access-control-allow-origin': '*',
     'content-security-policy': 'default-src \'none\'',
     'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
     'x-content-type-options': 'nosniff',
     'x-frame-options': 'deny',
     'x-xss-protection': '1; mode=block',
     'x-runtime-rack': '0.037174',
     'x-github-request-id': 'EB1C:2B72:1C567:491B0:5A0B6F95' } }

**Comment by pvdlg** [comment]
`semantic-release` try to create the tag `1.2.1` on the repo `formhero/fh-cors-middleware` referencing the commit `8f1c9771bc4e4deb25bf3da93118dc6e2163c8e1` on branch `develop`

Can you verify if the commit `8f1c9771bc4e4deb25bf3da93118dc6e2163c8e1` exists on the repo `formhero/fh-cors-middleware` on branch `develop` ?

**Comment by ryan-kimber** [comment]
My apologies, but we've deleted the repository and renamed the project to get around this issue. 

If we have it happen again on another repo, I'll add another ticket.
