### ISSUE TITLE
Scope package not publishing on Travis

### ISSUE THREAD

**Issue by rodoabad** [semantic-release/semantic-release#521]
Travis Job: https://travis-ci.org/at-scale/mock-react-components/jobs/306197164
Package: https://github.com/at-scale/mock-react-components
Name:   `@at-scale/mock-react-components`
Org: https://www.npmjs.com/org/at-scale

```
language: node_js
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
os:
    - linux
    - osx
node_js:
    - '8'
after_success:
  - yarn run semantic-release
branches:
    except:
      - /^v\d+\.\d+\.\d+$/
```

When I run locally, it seems fine.

```
$ yarn run semantic-release
yarn run v1.0.1
$ semantic-release pre && npm publish && semantic-release post
semantic-release WARN pre semantic-release didn’t run on Travis CI and therefore a new version won’t be published.
semantic-release WARN pre You can customize this behavior using "verifyConditions" plugins: git.io/sr-plugins
semantic-release ERR! pre Determined version 1.0.0 as "latest". Not publishing in debug mode. { type: 'initial', version: '1.0.0' }
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by pvdlg** [comment]
The error you get is `npm ERR! You must sign up for private packages : @at-scale/mock-react-components`. See https://travis-ci.org/at-scale/mock-react-components/jobs/306197163#L547

Have you set the `NPM_TOKEN` environment variable in your CI? Is the user associated with this token is allowed to publish on your npm org?

**Comment by rodoabad** [comment]
> To publish a public scoped package, you must specify --access public with the initial publication.

Does this mean I have to edit my script first and modify it to...

```
    "semantic-release": "semantic-release pre && npm publish --access public && semantic-release post"
```

**Comment by pvdlg** [comment]
I'd suggest to add that to your `package.json` instead:
```json 
 "publishConfig": {
    "access": "public"
  }
```

**Comment by rodoabad** [comment]
Good suggestion. Thanks. I've been meaning to use public scoped packages for awhile now.
