### ISSUE TITLE
EINVALIDNPMTOKEN with valid token.

### ISSUE THREAD

**Issue by ryansmith94** [semantic-release/semantic-release#533]
Hey, using the token I have in my local .npmrc file in the `NPM_TOKEN` environment variable on CircleCI, but I'm getting `EINVALIDNPMTOKEN`. Running `npm whoami` locally with that token is working fine.

https://circleci.com/gh/LearningLocker/xapi-service/237

**Comment by ryansmith94** [comment]
Config in package.json
```
  "release": {
    "verifyConditions": [
      "@semantic-release/github"
    ]
  }
```
Dev Deps
```
"@semantic-release/github": "2.0.0",
"@semantic-release/npm": "2.0.0",
"semantic-release": "11.0.0"
```

**Comment by ryansmith94** [comment]
Reverted back to Semantic Release 10 and I'm still seeing the issue 😢

**Comment by pvdlg** [comment]
I see in the Circle logs that it uses `yarn`. That should work, but you still need to have `npm` in the path. Do you know if Circle still install `npm` when you are using `yarn`?

Can you start another run with version `11.0.0` and setting the environment variable `DEBUG` to `semantic-release:*` ?

**Comment by ryansmith94** [comment]
Yeah npm is installed, we're just using the Node 8.8.0 Docker Image, that hasn't changed since our upgrade to Semantic Release 11. I have a [build with Semantic Release 10 working fine in CircleCI](https://circleci.com/gh/LearningLocker/xapi-activities/50).

Yeah sure, two minutes.

**Comment by pvdlg** [comment]
In [11.0.0](https://github.com/semantic-release/semantic-release/releases/tag/v11.0.0) we changed the plugin API.
If you use custom plugin, make sure they have been updated for the new API.

**Comment by ryansmith94** [comment]
https://circleci.com/gh/LearningLocker/xapi-service/245

**Comment by pvdlg** [comment]
Not much more info unfortunately.... Do you have to connect with ssh to check what's in the .npmrc ?

**Comment by ryansmith94** [comment]
Okay, connected with SSH, the .npmrc file is being created incorrectly as
```

//registry.npmjs.org/:_authToken = ${NPM_TOKEN}
```

**Comment by pvdlg** [comment]
Can you check if you have another `.npmrc` in the home directory ?
If it's the case it might have a different value there. And the `.npmrc` in the home will take precedence over the one in the project I think.

**Comment by ryansmith94** [comment]
There's no .npmrc in the home directory. I can confirm that correcting the .npmrc works. Seems to me that there is something trying to pipe `//registry.npmjs.org/:_authToken = ${NPM_TOKEN}` that into the .npmrc file and maybe the `${...}` syntax isn't supported in CircleCI.

**Comment by ryansmith94** [comment]
Hmmm having said that `echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc` works fine.

**Comment by pvdlg** [comment]
With `//registry.npmjs.org/:_authToken = ${NPM_TOKEN}` in the `.npmrc`, what happen when you run `npm whoami` ?

**Comment by pvdlg** [comment]
Is it possible that somehow `NPM_TOKEN ` is available when you debug with ssh but it's not when `semantic-release` runs?

**Comment by ryansmith94** [comment]
Okay running `npm whoami` with `//registry.npmjs.org/:_authToken=${NPM_TOKEN}` in the .npmrc correctly returns my username. Maybe, this works when I used Semantic Release 10 though.

**Comment by pvdlg** [comment]
There is no differences between 10 and 11 I can think of that would explain a different behavior regarding the npm auth... So I don't really understand yet what cause the problem...

**Comment by ryansmith94** [comment]
`await execa('npm', ['whoami']);` is successful when running the following in Node.

```js
const execa = require('execa');
execa('npm', ['whoami']).then(() => console.log('success')).catch((err) => console.error('error', err))
```

**Comment by ryansmith94** [comment]
Interesting that `name` is undefined here.
```
  semantic-release:config name: undefined +0ms
  semantic-release:config branch: 'master' +0ms
  semantic-release:config repositoryUrl: 'git+https://github.com/LearningLocker/xapi-service.git' +0ms
  semantic-release:config analyzeCommits: undefined +0ms
  semantic-release:config generateNotes: undefined +0ms
  semantic-release:config verifyConditions: [ '@semantic-release/github', '@semantic-release/npm' ] +0ms
  semantic-release:config verifyRelease: undefined +1ms
  semantic-release:config publish: undefined +0ms
```

**Comment by pvdlg** [comment]
The debug log is still there but we don't use the `name` config anymore. So it's normal.

**Comment by pvdlg** [comment]
In the Circle step in which you run `semantic-release`, can you try to run that:
`echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc && npm whoami` ?

**Comment by ryansmith94** [comment]
https://circleci.com/gh/LearningLocker/xapi-service/248

**Comment by pvdlg** [comment]
`condition-circle` will break things if it doesn't adapt to the new plugin API of 11.

So if you remove `condition-circle` out of the equation, does it works ?

**Comment by ryansmith94** [comment]
Still broken 😞 https://circleci.com/gh/LearningLocker/xapi-service/251

**Comment by ryansmith94** [comment]
Interestingly I don't see anything logged by the function I wrote.

```
'use strict'
const log = require('debug')('condition');
const spawn = require('cross-spawn');
const { join } = require('path');
const safeEnv = require('safe-env');
const SemanticReleaseError = require('@semantic-release/error');

module.exports = async (pluginConfig, { options: { branch } }) => {
  const script = join(__dirname, 'condition-circle-refs.sh');
  spawn.sync(script, [], { stdio: 'inherit' });

  if (process.env.CIRCLECI !== 'true') {
    throw new SemanticReleaseError('Not running on Circle CI');
  }

  if (branch !== process.env.CIRCLE_BRANCH) {
    throw new SemanticReleaseError(
      `Running on '${process.env.CIRCLE_BRANCH}' not '${branch}'`
    );
  }
};

```

**Comment by pvdlg** [comment]
In your custom plugin `condition-circle.js` can you check if `NPM_TOKEN` is properly set ?
Here is an example of code that would avoid revealing your token:
```js
console.log('Check NPM_TOKEN ' + process.env.NPM.substring(0, 4) === '<the first 4 characters of your token>')
```

**Comment by pvdlg** [comment]
If the npm `verifyConditions` runs first and fail, your custom plugin won't even be called. Maybe that's why?

By the way the custom script to fix packed repo is not required anymore. `semantic-release` handle that now.

**Comment by pvdlg** [comment]
I might have an idea... I pushed so changes on `https://github.com/semantic-release/npm/tree/userconfig`.

Could you try to configure in your `package.json`:
```json
"devDependencies": {
  "@semantic-release/npm": "semantic-release/npm#userconfig"
}
```

And see if that solve the issue ?

**Comment by ryansmith94** [comment]
Sure 👍

**Comment by ryansmith94** [comment]
Same result https://circleci.com/gh/LearningLocker/xapi-service/260

**Comment by pvdlg** [comment]
:( When you shh to the box, do you the expected token with `echo $NPM_TOKEN` ?

**Comment by pvdlg** [comment]
I also added some debug log in the branch https://github.com/semantic-release/npm/tree/userconfig.

Can you restart the build that uses the `userconfig` branch with the environment variable DEBUG=semantic-release:* ?

Just to make sure what is the error reported by `npm whoami`

**Comment by pvdlg** [comment]
One more thing. can you set the npm loglevel to verbose [here](https://github.com/LearningLocker/xapi-service/blob/master/.circleci/config.yml#L15) ?

**Comment by pmowrer** [comment]
I've encountered the same problem and I think it has to do with running `semantic-release` via `yarn`. It works fine running it as `npx semantic-release`.

**Comment by ryansmith94** [comment]
Hey guys, sorry for the late reply, I was on holiday today. I can confirm that running it with `npm` instead of `yarn` solves the issue. https://circleci.com/gh/LearningLocker/xapi-service/266?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by pvdlg** [comment]
It should be solved by semantic-release/npm#9

For informations it comes from this issue: npm/npm#18426

**Comment by ryansmith94** [comment]
Wow awesome!!! Thanks guys, amazing work as usual, really appreciate it! 👍

I'll create a PR for the condition-circle plugin later today for other Circle users, if it's not merged in the next day or so I'll fork their repo and publish it to npm. In the meantime, I'm using the snippet below.

```
      - deploy:
          name: Semantic Release
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
               yarn semantic-release || true;
            fi
```

**Comment by pvdlg** [comment]
Can you confirm it works with `yarn` now?

**Comment by ryansmith94** [comment]
https://github.com/bahmutov/condition-circle/pull/5
