### ISSUE TITLE
Links to commits in release notes use git+https: protocol

### ISSUE THREAD

**Issue by gr2m** [semantic-release/semantic-release#539]
[![image](https://user-images.githubusercontent.com/39992/33414833-f0833294-d547-11e7-87de-e20201119fce.png)](https://github.com/semantic-release/semantic-release/releases/edit/v11.0.1)

**Comment by gr2m** [comment]
Thanks for reporting the issue!

**Comment by pvdlg** [comment]
This is happening because that project uses version 12: https://github.com/okonet/lint-staged/blob/fcb774b1ff46bf072e77b757a6b1133bb72b596c/.travis.yml#L24

After upgrading to the latest version 15 it will works.

**Comment by okonet** [comment]
We had a reason to pin the version although I can not remember what it was

**Comment by pvdlg** [comment]
Version is really old (we are version 15) and many fixes/features have been added since then. We might consider delivering fixes for the previous major release (e.g. version 15 when we release 16) but we won't maintain a version that is so old as 12....

**Comment by okonet** [comment]
That’s understandable. I’m going to upgrade to latest and see if it still works for us.
