### ISSUE TITLE
npm enterprise: workaround bug where registry returns "500 not found"

### ISSUE THREAD

**Issue by gr2m** [semantic-release/semantic-release#54]
https://github.com/semantic-release/semantic-release/blob/next/src/lib/last-release.js#L13 needs to be
`if (err && (err.statusCode === 404 || /not found/.test(err.message.toLowerCase()))) return cb(null, {});`

That fixes it.

**Comment by ariporad** [comment]
This will move to semantic-release/last-release-npm with #57, so I'm going to open an issue about it there

**Comment by ariporad** [comment]
Closing this because it's
