### ISSUE TITLE
Getting "not a Travis user" on travis enterprise

### ISSUE THREAD

**Issue by SimenB** [semantic-release/semantic-release#540]
I'm not sure if this is the correct repo. Maybe https://github.com/semantic-release/condition-travis, but I'm not sure at which step in the process this is failing... I'll be happy to open up an issue there if that's the correct place!

I'm currently trying to get this to work with GH enterprise, Travis enterprise and Artifactory.
I _think_ I'm passed issues with GH and Artifactory (at least I got errors with them previously, while I'm now just getting an error just mentioning Travis).

Maybe related to https://github.com/pwmckenna/node-travis-ci/issues/18? I'm not sure.

Potentially relevant parts of the log from travis:

```
Setting environment variables from repository settings
$ export NPM_TOKEN=[secure]
$ export ARTIFACTORY_CONTEXT=https://artifacts.schibsted.io/artifactory
$ export ARTIFACTORY_NPM_SECRET=[secure]
$ export [secure]=[secure]
$ export ARTIFACTORY_USER=[secure]
$ export AWS_ACCOUNT_NAME=infra-pro
$ export SPT_ENGPROD_REPORT_KEY=[secure]
$ export SPT_ENGPROD_REPORT_SECRET=[secure]

Setting environment variables from .travis.yml
$ export GITHUB_URL=https://github.schibsted.io
$ export GITHUB_PREFIX=/api/v3
$ export NPM_USERNAME=$ARTIFACTORY_USER
$ export NPM_PASSWORD=$ARTIFACTORY_NPM_SECRET
$ export NPM_EMAIL=$ARTIFACTORY_USER
$ export GH_TOKEN=[secure]
```

```
$ yarn semantic-release --debug
yarn run v1.3.2
$ /home/travis/build/simen-bekkhus/test-semantic-release/node_modules/.bin/semantic-release --debug
  semantic-release:get-version-head Check if the current working directory is a git repository +0ms
  semantic-release:get-version-head cmd: 'git rev-parse --git-dir' +1ms
  semantic-release:get-version-head stdout: '.git' +2ms
  semantic-release:get-version-head stderr: '' +0ms
  semantic-release:get-version-head code: 0 +0ms
  semantic-release:config name: undefined +0ms
  semantic-release:config branch: 'master' +1ms
  semantic-release:config repositoryUrl: 'git@github.schibsted.io:simen-bekkhus/test-semantic-release.git' +0ms
  semantic-release:config analyzeCommits: undefined +0ms
  semantic-release:config generateNotes: undefined +0ms
  semantic-release:config verifyConditions: undefined +0ms
  semantic-release:config verifyRelease: undefined +0ms
  semantic-release:config publish: undefined +0ms
[Semantic release]: Load plugin @semantic-release/npm
[Semantic release]: Load plugin @semantic-release/github
[Semantic release]: Load plugin @semantic-release/condition-travis
[Semantic release]: Load plugin @semantic-release/npm
[Semantic release]: Load plugin @semantic-release/commit-analyzer
[Semantic release]:[39m Load plugin @semantic-release/release-notes-generator
[Semantic release]: Load plugin @semantic-release/npm
[Semantic release]: Load plugin @semantic-release/github
[Semantic release]: Run automated release from branch master
[Semantic release]: Call plugin verify-conditions
[Semantic release]: Verify authentication for registry https://artifacts.schibsted.io/artifactory/api/npm/npm-local/
[Semantic release]: Wrote NPM_USERNAME, NPM_PASSWORD and NPM_EMAIL to .npmrc.
[Semantic release]: An error occurred while running semantic-release: 'not a Travis user'
error Command failed with exit code 1.
```

**Comment by pvdlg** [comment]
The error come from the Travis API...which doesn't give very detailed errors...

Can you make sure you added your Github repo to Travis?

**Comment by SimenB** [comment]
>Can you make sure you added your Github repo to Travis?

How so? The output here is from Travis. Should I specify the travis api url in some environment variable?

**Comment by pvdlg** [comment]
You have to enable your Github repo on Travis. See https://docs.travis-ci.com/user/getting-started/#To-get-started-with-Travis-CI

**Comment by SimenB** [comment]
I have the build running on travis already, Travis is building on every commit, and `Travis CI` is in the repo's settings.

![image](https://user-images.githubusercontent.com/1404810/33451395-3724e928-d60f-11e7-872f-84f0f627831d.png)

**Comment by pvdlg** [comment]
Is the `GITHUB_TOKEN` you are using is the associated with the Github user who is an owner of the repo?

**Comment by SimenB** [comment]
Yes, with the following permissions: `read:org, read:user, repo, user:email`.

**Comment by pvdlg** [comment]
Are you using Travis Pro or Travis Enterprise (with a custom URL) ?
If you are using Travis Enterprise we are not supporting yet.

Please open an issue on https://github.com/semantic-release/condition-travis for that.
We would like to support Travis Enterprise, but we do not have an instance to test so it would be quite difficult for us to add this feature.

Would like to help us and contribute with a PR? We would would give you guidance and help regarding the specifics of `semantic-release`.

**Comment by SimenB** [comment]
>If you are using Travis Enterprise we are not supporting yet.

Ah, that's it! Much sadness.

>Would like to help us and contribute with a PR?

Sure!

**Comment by SimenB** [comment]
https://github.com/semantic-release/condition-travis/issues/100
