### ISSUE TITLE
Cannot finding repo id of organization repo?

### ISSUE THREAD

**Issue by IniZio** [semantic-release/semantic-release#542]
I attempted `semantic-release-cli setup` on a organization repo, and filled the npm account and github account with my personal username. However it returns error that the repo id is not found. But if i try the setup on a personal repo it works fine.

**Comment by pvdlg** [comment]
Does your user have write access to the repo?

**Comment by IniZio** [comment]
Yes, I was the creator of the organizaion.

**Comment by pvdlg** [comment]
Do you have more details about the error ? Could you copy and paste the output of the CLI.

**Comment by IniZio** [comment]
My [package.json](https://github.com/clippedjs/clipped/blob/develop/package.json).

**Comment by pvdlg** [comment]
What is the error you get from the CLI ?

**Comment by pvdlg** [comment]
Duplicate of #380

**Comment by IniZio** [comment]
Resolved by revoking and granting access github oauth for Travis. Thanks for the help :pray:
