### ISSUE TITLE
Links in GH release points to list of commits, not single commit

### ISSUE THREAD

**Issue by SimenB** [semantic-release/semantic-release#543]
I just set up semantic-release, and while the release worked great (I'm so in love with this concept, thanks for creating such an awesome tool!), the generated release on github is a tiny bit off.

https://github.com/jest-community/eslint-plugin-jest/releases/tag/v21.4.1

If you click the commit link, it links to a list of repo commits starting at that commit, instead of the commit itself.

The issue (I think) is that the url is commit_s_/ instead of just commit/ (singular). I tried finding where in the code the URL is made, but couldn't find it 🙁 Happy to send a PR!

On a related note, would it be possible to write a CHANGELOG.md to the root of the package before publish, so it's included in the npm package? I don't need it in my source code, but would be sweet if it was included so people working offline could still see the changelog 🙂 (I can open up a separate issue if you want).

**Comment by pvdlg** [comment]
> The issue (I think) is that the url is commit_s_/ instead of just commit/ (singular). I tried finding where in the code the URL is made, but couldn't find it

I can reproduce. I'll check that out.

> On a related note, would it be possible to write a CHANGELOG.md to the root of the package before publish, so it's included in the npm package? I don't need it in my source code, but would be sweet if it was included so people working offline could still see the changelog

yes => https://github.com/semantic-release/git
