### ISSUE TITLE
Feature: Allow passing plugin options to CLI

### ISSUE THREAD

**Issue by pmowrer** [semantic-release/semantic-release#550]
It's possible to pass plugins via the CLI, only the plugins cannot have any configuration which isn't terribly useful. This could be resolved with either:

1) A "config path" option, allowing for passing a path to a file that returns the JSON format used in `package.json` (perhaps with `package.json` as the option's default).

2) When passing a plugin via the CLI, only set the config object's `path` property and don't throw away the rest of the config set for that plugin (from `package.json`).

I think the ability to pass plugin options to the CLI would relatively easily allow sharing plugin configs   (#549 ). The problem is, since there are so many plugins, any custom configuration gets verbose and tedious to share across projects. For example, [to use the `semantic-release-monorepo` "multi-plugin"](https://github.com/Updater/semantic-release-monorepo#usage
):  

```json
{
  "release": {
    "analyzeCommits": "semantic-release-monorepo",
    "generateNotes": "semantic-release-monorepo",
    "getLastRelease": "semantic-release-monorepo",
    "publish": ["semantic-release-monorepo/npm", "semantic-release-monorepo/github"]
  }
}
```
If this configuration could be passed via the CLI, we can create a wrapper binary over `semantic-release`, e.g. `semantic-release-monorepo`, encoding the plugin's default configuration. As an example, [the binary for `semantic-release-github-pr`](https://github.com/Updater/semantic-release-github-pr/blob/master/bin/semantic-release-github-pr.js), another "multi-plugin" (with custom "verifyConditions" and "publish" plugins):

```js
const args = argv
  .slice(2)
  .concat([
    '--verify-conditions=@semantic-release/github',
    `--publish=${resolve(__dirname, '../index.js')}`,
]);
```

Equivalent:
```bash
semantic-release-github-pr
```

```bash
semantic-release --verify-conditions='@semantic-release/github' --publish='index.js'
```

The only problem with it is now you can't configure either of "verifyConditions" or "publish" via `package.json`.

**Comment by pvdlg** [comment]
I'm currently looking at a way to simplify the configuration, but I'm not sure what the right solution is yet.

Some plugin parameters (and future core parameters) are complex objects (like [github#assets](https://github.com/semantic-release/github#assets)) that couldn't be passed via CLI. It would be confusing to have some parameters accepted in the CLI and some other that are not.

Also I don't think wrapping the CLI is the right approach. You should instead call `semantic-release` via API:
```js
const semanticRelease = require('semantic-release');

const options = {branch: 'master'};
await semanticRelease(options);
```

On a side note, what you do in`semantic-release-github-pr` is something we are thinking to implement. But that will not work for PR that are made from a forked repo, as the environment variables will [not be available on the CI](https://docs.travis-ci.com/user/environment-variables/#Defining-encrypted-variables-in-.travis.yml).

> Encrypted environment variables are not available to pull requests from forks due to the security risk of exposing such information to unknown code.

If you'd make the environment variables available for PR coming from forked repo, anyone could make a fork and open a PR that does `console.log(process.env.GH_TOKEN)` and obtain access to your Github account by looking at the CI logs.

**Comment by phukcingprivacy** [comment]
microsoft.com/Acct

**Comment by pmowrer** [comment]
> Also I don't think wrapping the CLI is the right approach. 

Wrapping the CLI is an approach that most closely achieves what we're trying to achieve in the aforementioned examples and given the current state of `semantic-release`. In that sense, it's "right" for us, but we try to avoid using such language as it typically isn't very constructive. I think it'd be more constructive discussing the relative merits (pros/cons) of each approach and determine when appropriate.

What do you think are the pros (if any) and cons of the proposed approaches?


> You should instead call semantic-release via API

With the aforementioned tools wrapping `semantic-release`, we're trying to achieve the following:

1. Same interface as `semantic-release` CLI (such that you can pass `--dry-run` and other options).
    * Wrapping CLI: ✅ 
    * Using API: ❌

2. Picking up configurations options from `package.json`.
    * Wrapping CLI: ❌
    * Using API: ✅ 

For our current use-case, the first requirement is slightly more important and is why we went with the wrapped CLI approach. But, it's not perfect which is why I've opened this ticket.

**Comment by pvdlg** [comment]
I was trying to propose a solution to your use case and I'm sorry that my choice of word appeared non constructive. That wasn't the intention.

The objective of the CLI is to be used by users and on the CI, while the objective of the API is to allow integrations. API is usually a more convenient choice as it allows to do some pre-processing and to pass a complex object as the options. In addition it avoid having to spawn a sub-process and it makes it easier to handle errors, as the API throws typed exceptions with messages, while the CLI just return `0` or `1` with some logs on `stdout` and `stderr`.

You can use the API and still pass any parameter (such as `--dry-run`). This can be achieved by parsing the arguments passed to your CLI and pass them to the API along with some other pre-determined parameters. This is basically what the `semantic-release` CLI is doing in [cli.js](https://github.com/semantic-release/semantic-release/blob/caribou/cli.js).

You can use libraries like https://github.com/tj/commander.js or https://github.com/yargs/yargs to parse `process.argv`. This way you can allow your users to set any options via CLI.

This could be something along those lines:
```js
const semanticRelease = require('semantic-release');
const program = require('commander');
const {merge} = require('lodash');

const predefinedOptions = {...};
program
// Optionally defined the set options that are allowed, or let the user set any parameters, display a custom, a custom help etc...
.parse(process.argv);

try {
  await semanticRelease(merge(program.opts(), predefinedOptions));
} catch(err) {
  // Handle errors
}
```
This way you can, if you choose to, limit the options the users can set, or add new ones, or display different help message, or do any pre-processing/validation on the options passed by the user,  etc...

With the API `semantic-release` will create the options object by merging the following in that order of priority:
- `options` passed to the API
- option sets in the first configuration file found (`package.json` or a dotfile at the root of the repo)
- default options

**Comment by pmowrer** [comment]
> You can use the API and still pass any parameter (such as --dry-run). This can be achieved by parsing the arguments passed to your CLI and pass them to the API along with some other pre-determined parameters. This is basically what the semantic-release CLI is doing in cli.js.

Having to re-implement/copy the CLI when creating a binary has some serious drawbacks. It's duplicated code with a brittle coupling to the version of `semantic-release` from which it was lifted.
It becomes more difficult to maintain such a binary because any changes to `semantic-release`'s CLI implementation must be copied/adapted for each binary.

**Comment by pmowrer** [comment]
> 2. When passing a plugin via the CLI, only set the config object's path property and don't throw away the rest of the config set for that plugin (from package.json).

@pvdlg Is there a particular reason it currently works like this? ☝️ 

E.g.:

```bash
semantic-release --publish="moduleA"
```
The above command sets the plugin config for the `publish` command to the string "moduleA". What if it instead set the plugin config for `publish` to `{ path: "moduleA" }`? Things would work exactly the same, only it would allow any plugin configuration from `package.json` to be merged [using `defaults` here](https://github.com/semantic-release/semantic-release/blob/0c67ba517fd6dd42959ee263ad50a6c7c30d57af/lib/get-config.js#L10). It would make using plugins from the CLI much more useful as you'd at least have a means to be able to configure them.

**Comment by pvdlg** [comment]
I'm not I understand what you are proposing. Can you provide an example with the command you want to execute, the `package.json` config and the expected result?

**Comment by pmowrer** [comment]
Sure! 

A plugin can be set two different ways in `package.json`:

1. `String`: The module name to use as the plugin. Does not allow passing plugin configuration options.
2. `Object`: The `path` property is the module name. Allows passing plugin configuration options.

When using the CLI, only the first way of configuring a plugin is currently supported.

Let's say we have this `package.json`:

```json
{
  "release": {
    "analyzeCommits": {
      "preset": "angular"
    }
  }
}
```

And we invoke `semantic-release` via the CLI in the following way:

```bash
semantic-release --analyze-commits="alternative-analyze-commits"
```

Because `analyzeCommits` is set to a string, the configuration in `package.json` will have no effect. `semantic-release` will effectively be run with the following config:

```json
{
  "release": {
    "analyzeCommits": "alternativeAnalyzeCommits"
  }
}
```

### Proposal
If passing `--analyze-commits="alternative-analyze-commits"` instead was mapped into `{ path: "alternative-analyze-commits" }`, any additional plugin options defined in `package.json` would be merged into that object.

```json
{
  "release": {
    "analyzeCommits": {
      "path": "alternativeAnalyzeCommits",
      "preset": "angular"
    }
  }
}
```

**Comment by pvdlg** [comment]
> Having to re-implement/copy the CLI when creating a binary has some serious drawbacks.

You can call the API, passing any CI arguments with 1 line of code:
```js
await require('semantic-release')(require('minimist')(process.argv.slice(2)));
```

> It's duplicated code with a brittle coupling to the version of semantic-release from which it was lifted.

It's not really a duplication of code. The coupling is no more brittle with one solution or the other, as a change in the API will come with a change in the CLI and vice-versa. It would be a breaking change in both case.

In addition this solution allow to customize more if you choose to:
- You can restrict some options
- You can parse options passed to your CLI in any custom way in order to make some validations
- You can display a custom help message

> If passing --analyze-commits="alternative-analyze-commits" instead was mapped into { path: "alternative-analyze-commits" }, any additional plugin options defined in package.json would be merged into that object.

I imagine that would be a problem for plugin that can be defined as an `Array`? Or at least it would incur a lot of complexity to handle those cases.

In addition that would allow to create inconsistencies. If the configuration set `analyzer-1` as the `analyzeCommits` plugin and sets options specific to this plugin. If you call the CLI with `--analyze-commits="analyzer-2"` you will end up passing to `analyzer-2` an option that is meant to `analyzer-1`, which probably not what a user want to do.

Overriding the entire value of `analyzeCommits` when using `--analyze-commits="analyzer-2"` is the expected behavior. This is because the intent of the CLI options is to enable/disable plugins, and that mean overriding the entire value so it works for plugins defined as `Array`.

`publish: ["publish-1", "publish-2", "publish-3"]` has to become `publish: ["publish-1", "publish-2"]` when we pass the options `--publish=publish-1,publish-2`.

If you want to use `semantic-release` with a predefined set of plugins and options you have 2 choices:
1. Use the API with the one liner I provided
2. Use a shareable config module once a good solution is found for #549 and it's implemented

The CLI options to choose the plugin are there mostly for historical reasons. When those options where introduced there was only a limited number of plugins and none of them had options.
We kept those options as a convenience to only enable/disable plugins.
The JS API has been added in [v9.0.0](https://github.com/semantic-release/semantic-release/releases/tag/v9.0.0) to allow the integration use case, as the number of plugin and option grew.

**Comment by pmowrer** [comment]
> You can call the API, passing any CI arguments with 1 line of code:

> await require('semantic-release')(require('minimist')(process.argv.slice(2)));

This isn't an equivalent solution. Unless everything in `cli.js` is copied, the binary won't behave the same (no help output, debug probably won't work the same, exit codes need to be configured). The desired behavior is for a binary like `semantic-release-github-pr` to work exactly the same as `semantic-release`, only with a different set of pre-defined plugins. That's the crux of this entire issue.

> I imagine that would be a problem for plugin that can be defined as an Array? Or at least it would incur a lot of complexity to handle those cases.

Fair point, its a scenario I didn't consider. But, easily addressed by allowing the `path` property to accept an array.

> Overriding the entire value of analyzeCommits when using --analyze-commits="analyzer-2" is the expected behavior. This is because the intent of the CLI options is to enable/disable plugins, and that mean overriding the entire value so it works for plugins defined as Array.

> publish: ["publish-1", "publish-2", "publish-3"] has to become publish: ["publish-1", "publish-2"] when we pass the options --publish=publish-1,publish-2.

This would be solved by above suggestion.

> In addition that would allow to create inconsistencies. If the configuration set analyzer-1 as the analyzeCommits plugin and sets options specific to this plugin. If you call the CLI with --analyze-commits="analyzer-2" you will end up passing to analyzer-2 an option that is meant to analyzer-1, which probably not what a user want to do.

This is basically what I was looking for when asking "Is there a particular reason it currently works like this?". I agree changing it could be confusing, but in my opinion it's equally confusing the way it works now. I don't see a strong reason why it should work this way, but "historical reasons" makes sense.

> Use a shareable config module once a good solution is found for #549 and it's implemented

Looking forward to this then! 😄

**Comment by pvdlg** [comment]
> Looking forward to this then! 😄

Should wee close this issue and follow up in #549? Feedback welcome regarding the proposal I made over in #549.

**Comment by pmowrer** [comment]
Sure! The first suggestion in the first post of this thread is a variation on the "CLI extends" feature that you propose in #549.

> 1. A "config path" option, allowing for passing a path to a file that returns the JSON format used in package.json (perhaps with package.json as the option's default).
