### ISSUE TITLE
last-release-git-tag using invalid merge option?

### ISSUE THREAD

**Issue by ryansmith94** [semantic-release/semantic-release#559]
Hey got this error in CircleCI https://circleci.com/gh/HT2-Labs/semantic-release/9

Here is my config https://github.com/HT2-Labs/semantic-release/blob/master/scripts/public-circleci-lib.js
Here is my package.json https://github.com/HT2-Labs/semantic-release/blob/master/package.json

**Comment by pvdlg** [comment]
After doing some test the `--merge` option has been added in git `2.7.0`, which is a quite old version. The last one is `2.15.1`.

According to [Circle CI docs](https://circleci.com/docs/1.0/build-image-trusty/) the git version installed is `2.14.2`.

Can you check which version of git is running on your Circle CI build with `git --version`?

**Comment by ryansmith94** [comment]
Interesting, yeah sure.

**Comment by ryansmith94** [comment]
So CircleCI is using 2.1.4 apparently https://circleci.com/gh/HT2-Labs/semantic-release/10

**Comment by ryansmith94** [comment]
Going to try using Circle's pre-built Node image instead, I'm sure that'll have a newer version of Git.

**Comment by ryansmith94** [comment]
I was wrong, still using 2.1.4 😞

**Comment by ryansmith94** [comment]
Just made my own plugin instead https://github.com/HT2-Labs/semantic-release/blob/master/plugins/getLastRelease.js

**Comment by pvdlg** [comment]
On regular Circle CI builds it seems git 2.14.2 is installed: https://circleci.com/gh/pvdlg/test-circleci/42

I'm re-opening as it's important to find a solution that works on all CI, including the one with very old git CLI. CircleCI should update their images to march their docs, but it's possible other CIs out there provide only an old version of git. git [2.7.0](https://github.com/git/git/releases/tag/v2.7.0) is "only" 2 years old after all.

**Comment by ryansmith94** [comment]
Oh okay @pvdlg, I wasn't going to worry you guys with it, I thought it was just an issue with my particular setup.

**Comment by pvdlg** [comment]
The problem happens with Circle CI 2.0 and their docker images as it comes with a very old `git`. Surprisingly with Circle CI 1.0, the git version installed is recent (`2.14.2`).

It would be a good idea to open an issue/PR with [circleci-images](https://github.com/circleci/circleci-images) to update git to the version they mention in their docs. Would you take care of that?

I found a good workaround in semantic-release/git#6 to avoid using the `--merge` option of `git tag` so we might want to use so we won't have the problem anymore, whether CircleCi update their image or not.

**Comment by ryansmith94** [comment]
Hey @pvdlg, wow that's interesting. Yeah sure, I'll raise an issue over there, thanks for digging into this, really appreciate it.

Brilliant, yeah might be a good idea to avoid the merge in the meantime. When I create the issue I'll link back here 👍

**Comment by ryansmith94** [comment]
Alright they're not going to update it https://github.com/circleci/circleci-images/issues/128#issuecomment-351780040

**Comment by pvdlg** [comment]
> Alright they're not going to update it circleci/circleci-images#128 (comment)

: ( It was worth trying!

I released semantic-release/git#6 so it should work with git `2.1.4` now

**Comment by ryansmith94** [comment]
Yeah definitely worth trying.

Awesome, thanks @pvdlg, I'll give that a go 👍

**Comment by ryansmith94** [comment]
Hey @pvdlg, the last commit in the semantic-release/git repo didn't create a new release because of an invalid NPM token on Travis. https://travis-ci.org/semantic-release/git/jobs/316572537#L630

**Comment by pvdlg** [comment]
Thanks for the heads up. It's fixed now and a new version has been released

**Comment by ryansmith94** [comment]
No worries. Yeah it's all working great thanks @pvdlg 👍
