### ISSUE TITLE
Decouple version determiner from npm registry

### ISSUE THREAD

**Issue by tlvince** [semantic-release/semantic-release#56]
[Last release](https://github.com/semantic-release/semantic-release/blob/77349fcdf193467967fa4a85daf2ee3fa812779b/src/lib/last-release.js) is currently determined by consulting the npm registry. As mentioned (out of band), this could be made more flexible by looking at Git tags (for example).

A use case for this could be in situations where the `npm publish` step is undesirable. This seems to resonate with some of the discussion in #51.

**Comment by juristr** [comment]
:+1:

**Comment by boennemann** [comment]
This is something I'd love to see. We could introduce another plugin hook "getLastRelease", leave the current implementation as default, and provide a git-tag based implementation.

Anyone up for takling this one?

**Comment by ariporad** [comment]
I'd love to try... I'm a little busy, But I'll try to get to it today or
tomorrow.
ᐧ

**Comment by boennemann** [comment]
@ariporad This sounds fantastic, do you want to chat about it some more on gitter first?

**Comment by boennemann** [comment]
Alright, @ariporad will take a stab at implementing this :+1: 

1. [ ] Add a "getLastRelease" plugin hook to semantic-release
2. [ ] Move lib/last-release.js to https://github.com/semantic-release/last-release-npm and make it the default
3. [ ] Implement https://github.com/semantic-release/last-release-git-tag

:tada:

**Comment by ariporad** [comment]
Number 1 is fixed in #57.

**Comment by tlvince** [comment]
:+1:
