### ISSUE TITLE
Migration guide

### ISSUE THREAD

**Issue by rarkins** [semantic-release/semantic-release#562]
I think it would be useful to document a migration guide beyond what is in the automatically generated BREAKING CHANGES sections of releases. Right now master is actually three major releases ahead of npmjs's "latest" (v11 vs v8) and it's certainly not clear to me regarding the upgrade path or process.

I'll summarise here the BREAKING CHANGES between latest and next, as it's hopefully useful:

v9.0.0

- Semantic-Release must now be executed with semantic-release instead of semantic-release pre && npm publish && semantic-release post.
- The semantic-release command now returns with exit code 0 on expected exception (no release has to be done, running on a PR, gitHead not found, other CI job failed etc...). It only returns with 1 when there is an unexpected error (code error in a plugin, plugin not found, git command cannot be run etc..).
- Calling the semantic-release command with unexpected argument(s) now exit with 1 and print an help message.
- Semantic-Release does not rely on npmlog anymore and the log level cannot be configured. Debug logs can be activated with CLI option --debug or with environment variable DEBUG=semantic-release:*
- The CLI options --debug doesn't enable the dry-run mode anymore but activate the debugs. The dry run mode is now set with the CLI command --dry-run or -d.
semantic-release pre && npm shrinkwrap && semantic-release post
- If you depend on npm shrinkwrap, you have to run it before semantic-release now. You can set "presemantic-release": "npm shrinkwrap" in your package.json file

v10.0.0

- githubToken, githubUrl and githubApiPathPrefix have to be set at the github plugin level. They can be set via GH_TOKEN, GH_URL and GH_PREFIX environment variables.
- the npm parameter is no longer passed to plugins. We recommend using npm-conf to read out information from the .npmrc file.

v11.0.0

- pkg and env are not passed to plugin anymore.
- Plugins relying on a package.json must verify the presence of a valid package.json and load it.
- Plugins can use process.env instead of env.
- Each plugin is expected to return an async function or a Promise returning function. The callback parameter is not passed to plugins anymore.

I think we could simplify it a lot if:
1. Breaking changes are listed if they are breaking for the *user*, or breaking for *plugin authors*
2. Plugin authors are diligent in listing accurate versions of semantic-release in peerDependencies

That way, if I'm a user without plugins then I just skim for any breaking changes for users. If I also use plugins, then I can essentially still skip the breaking plugins changes and wait until the plugins I use publish a new version supporting the latest semantic-release as a peer dependency.

**Comment by pvdlg** [comment]
Thanks for the proposal!
A migration guide is generally a good idea, however in this case the migration will be very in easy in most cases:

For users using the default settings (the very large majority):
- `semantic-release pre && npm shrinkwrap && semantic-release post` => `semantic-release` in `package.json` `scripts`

For users using custom plugins:
- Make sure the plugins are updated

For users with a non officially supported configuration or workaround (i.e stuff that rely on exit code, `semantic-release` running in the non expected Travis step, wrapping scripts etc...):
- All the breaking change entries in the release notes are relevant and it's not really possible to identify all the possible cases. Plus they are not supported in the first place....

Do you think it would be sufficient to add a `Migration` section to each release note with something like that 👇?

> If you are using `semantic-release` with the default configuration created by `semantic-release-cli setup`, please update your `package.json` `scripts` from `semantic-release pre && npm shrinkwrap && semantic-release post` => `semantic-release`

> If you are using a custom plugin, please make sure with the its author that its updated for the new `semantic-release` version

**Comment by pvdlg** [comment]
I added a short Migration guide to the  [v9.0.0](https://github.com/semantic-release/semantic-release/releases/tag/v9.0.0) and [v11.0.0](https://github.com/semantic-release/semantic-release/releases/tag/v11.0.0) releases.

Please re-open if you'd like a to add something to the releases description or a more detail documentation. PR welcome for a documentation!

**Comment by jcane86** [comment]
@pvdlg hiya, thanks for the guides, I was looking at that too.

Just a quick heads up, the one for 9.0 looks wrong, it says to keep the npm script unchanged, when it should be "release" : "semantic-release",? 

Thanks!

**Comment by pvdlg** [comment]
Ooops...Thanks for catching that up!
It's fixed now!
