### ISSUE TITLE
New plugin: Gitlab

### ISSUE THREAD

**Issue by pvdlg** [semantic-release/semantic-release#565]
Supercede #77 and #37

With the new plugin architecture Gitlab can be supported with a plugin similar to [github](https://github.com/semantic-release/github).

**Comment by pvdlg** [comment]
Looking at the [Gitlab doc for release](https://docs.gitlab.com/ee/workflow/releases.html#releases) it seems Gitlab doesn't have something similar to [Github releases](https://help.github.com/articles/about-releases/). Instead it seems the recommended way is to create a git tag with the release note as the body of the commit associated with the tag. This is exactly what the [git plugin](https://github.com/semantic-release/git) does.

Therefore, is there really a need for a specific Gitlab plugin ? Or should we just write a recipe explaining how to configure the git plugin for Gitlab?

The configuration could be something like that:
```json
{
  "release": {
    "verifyConditions": [ "@semantic-release/changelog",  "@semantic-release/git"],
    "getLastRelease": "@semantic-release/git",
    "publish": ["@semantic-release/changelog", "@semantic-release/git"]
  }
}
```

Or with `npm`:
```json
{
  "release": {
    "verifyConditions": [ "@semantic-release/changelog", "@semantic-release/npm", "@semantic-release/git"],
    "getLastRelease": "@semantic-release/git",
    "publish": ["@semantic-release/changelog", "@semantic-release/npm", "@semantic-release/git"]
  }
}
```

With the environment variable `GIT_CREDENTIALS ` set with a [Gitlab personal token](https://docs.gitlab.com/ce/user/profile/personal_access_tokens.html) value.

As Travis is not compatible with Gitlab, that would be possible once #578 lands.

@destroyerofbuilds, @johann-sonntagbauer as you know Gitlab better, would that works?

**Comment by johann-sonntagbauer** [comment]
The specific gitlab plugin was necessary because of the validation logic. I don't remember the details, but the git URL was parsed and validated to be a valid github based URL.  If that validation rule is relaxed now, your configuration solution is valid.

**Comment by pvdlg** [comment]
The repository URL is retrieve [here](https://github.com/semantic-release/semantic-release/blob/caribou/lib/get-config.js#L48), and its used [Git plugin](https://github.com/semantic-release/git) and in [Release note generator plugin](https://github.com/semantic-release/release-notes-generator). Both plugins accept Gitlab URLs (and include unit tests verifying that).
So it should work then.

Do you have by any chance a repo handy on which you could test that config after #578 lands?
Do not hesitate to ping me for help with the `semantic-release` config.

If it works as expected, we can change this issue to "Write a recipe for Gitlab" and link your test repo here to help write the doc.

**Comment by johann-sonntagbauer** [comment]
sorry we moved away from semantic release and now use a big monorepo which suites our development workflow better. Time is currently a limiting factor but I will try to setup some test repository.

**Comment by pvdlg** [comment]
After some tests it turns out the GitLab release description is not the same as the tag message.
The release message can be set only by API for now. See https://gitlab.com/gitlab-org/gitlab-ce/issues/20587

I when ahead and created a [GitLab plugin](https://github.com/semantic-release/gitlab/pull/1) and [shareable config](https://github.com/semantic-release/gitlab-config/pull/1).

I'll write some doc in the main repo as well.

**Comment by pvdlg** [comment]
Would a GilLab user could try out the [plugin](https://github.com/semantic-release/gitlab/pull/1) and [shareable config](https://github.com/semantic-release/gitlab-config/pull/1)?
No one is really experience with GitLab in the team, so that would be great if we could get feedback from an experienced user.

Thanks!

**Comment by keplersj** [comment]
I should be able to test it out soon. My startup does CD on GitLab for a few of our projects.

**Comment by pvdlg** [comment]
Awesome! Let us know how it goes.
Do you need to have the plugin available on npm? OR can you just reference it in your `package.json` with `"semantic-release/gitlab#initial-release"` ?

**Comment by keplersj** [comment]
I should be able to reference by tag.

**Comment by pvdlg** [comment]
We now have:
- [GitLab plugin](https://github.com/semantic-release/gitlab)
- [GitLab shareable config](https://github.com/semantic-release/gitlab-config)
- [GitLab CI recipe](https://github.com/semantic-release/semantic-release/blob/caribou/docs/recipes/gitlab-ci.md)

So `semantic-release` should officially support GitLab!

As usual, feedback always welcome~

**Comment by kbrandwijk** [comment]
If so, so should the CLI...
