### ISSUE TITLE
Is it possible to publish a directory with the latest version of semantic-release?

### ISSUE THREAD

**Issue by benjamincharity** [semantic-release/semantic-release#570]
Currently my build process packages all needed files up into a `dist/` directory. In the past, I simply split the semantic-release commands to handle publishing a directory like this successfully:

```bash
yarn run semantic-release-pre
yarn run build
yarn publish dist/
yarn run semantic-release-post
```

Since 9.x the command is not multipart so I lost this ability.

Using the `files` array in my `package.json` does not solve the issue (it simply includes `dist/` into my published directory rather than making `dist/` the actual publish directory).

I've been beating my head against this for the majority of today with no luck. I cannot be the only one here who isn't just running a publish command from their root dir... I'm currently dead in the water as far as releases go.. Any ideas/suggestions would be greatly appreciated.

---

- I cannot run `semantic-release` from the `dist/` dir since it's dependencies don't exist there.
- I cannot use NPMs `files` option (this includes files - I want to _only_ publish the contents of a dir).
- I've tried using the assets section of the new config but my entire directory is published:

```json
      {
        "path": "@semantic-release/npm",
        "assets": [
          "dist/**/*.{js|css|scss|ts|map}"
        ]
      },
```

---

semantic-release: 11.0.2
node: 8.4.0
yarn: 1.3.2
npm: 5.6.0
OS X Sierra

My `package.json` with currently broken publish:

```json
{
  "name": "@terminus/ui",
  "version": "0.0.0-development",
  "description": "Terminus UI Library",
  "main": "./bundles/ui.umd.js",
  "typings": "./ui.d.ts",
  "author": "@terminus",
  "license": "MIT",
  "repository": {
    "type": "git",
    "url": "https://github.com/GetTerminus/terminus-ui.git"
  },
  "engines": {
    "node": ">= 8.0.0",
    "npm": ">= 5.0.0",
    "yarn": ">= 1.0.0"
  },
  "scripts": {
    "//=> Section: Documentation": "",
    "predocs": "yarn run docs:toc",
    "docs": "yarn run docs:ts && yarn run docs:scss",
    "docs:scss": "node ./node_modules/.bin/nucleus --config config.nucleus.json",
    "docs:ts": "./node_modules/.bin/compodoc -p src/lib/tsconfig.compodoc.json -d docs/typescript --hideGenerator --toggleMenuItems all --theme stripe",
    "docs:toc": "doctoc --title '**Table of Contents**' --maxlevel 4 ./README.md",
    "//=> Section: Development": "",
    "serve": "lite-server -c=tooling/bs-config.json --open false",
    "prestart": "yarn run build && yarn run build-demo && yarn run build-scss",
    "start": "concurrently \"yarn run build:watch\" \"yarn run build-demo:watch\"",
    "//=> Section: Build": "",
    "build": "./node_modules/.bin/gulp generate:build --gulpfile tooling/gulpfile.js",
    "build:watch": "onchange 'src/lib/**/*.ts' 'src/lib/**/!(helpers).scss' 'src/lib/**/*.html' -- yarn run build",
    "build-demo": "cd src/demo && ng build --prod",
    "build-demo:watch": "cd src/demo && ng serve --port 4300 --preserve-symlink --progress false",
    "build-scss": "./node_modules/.bin/gulp compile-sass-dev --gulpfile tooling/gulpfile.js",
    "build-scss:watch": "onchange 'src/lib/**/*.scss' -- ./node_modules/.bin/gulp compile-sass-dev --gulpfile tooling/gulpfile.js",
    "build-test": "tsc -p src/lib/tsconfig.spec.json",
    "build-test:watch": "tsc -p src/lib/tsconfig.spec.json -w",
    "//=> Section: Cleanup": "",
    "clean:lib": "./node_modules/.bin/gulp clean-generated-files --gulpfile tooling/gulpfile.js",
    "clean:demo:node_modules": "cd src/demo rm -rf node_modules && yarn install",
    "clean:lib:node_modules": "rm -rf node_modules && yarn install",
    "//=> Section: Yarn Management": "",
    "demo-yarn-install": "cd src/demo && yarn install",
    "prefresh-yarn-install": "rm -rf node_modules && cd src/demo && rm -rf node_modules",
    "fresh-yarn-install": "yarn install && yarn run demo-yarn-install",
    "postfresh-yarn-install": "cd src/demo && yarn link @terminus/ui",
    "update:angular:ui": "yarn add @angular/animations@latest @angular/cdk@latest @angular/core@latest @angular/forms@latest @angular/material@latest @angular/platform-browser@latest @angular/router@latest --exact && yarn add @angular/cli@latest @angular/common@latest @angular/core@latest @angular/compiler@latest @angular/compiler-cli@latest @angular/platform-browser@latest @angular/platform-browser-dynamic@latest @angular/http@latest @angular/http@latest @angular/flex-layout@latest -D --exact",
    "update:angular:demo": "cd src/demo && yarn add @angular/animations@latest @angular/common@latest @angular/compiler@latest @angular/core@latest @angular/flex-layout@latest @angular/forms@latest @angular/http@latest @angular/material@latest @angular/platform-browser@latest @angular/platform-browser-dynamic@latest @angular/router@latest @angular/cdk@latest --exact && yarn add @angular/cli@latest @angular/compiler-cli@latest @angular/language-service@latest -D --exact",
    "update:angular": "yr update:angular:ui && yr update:angular:demo",
    "//=> Section: Integration": "",
    "preintegration": "yarn run build && cd integration && yarn run clean && yarn install",
    "integration": "yarn run integration:aot && yarn run integration:jit",
    "integration:jit": "cd integration && yarn run e2e",
    "integration:aot": "cd integration && yarn run e2e:aot",
    "//=> Section: Linting": "",
    "lint:ts": "./node_modules/.bin/tslint --fix --project src/lib/tsconfig.json",
    "lint:ts-spec": "./node_modules/.bin/tslint --fix --project src/lib/tsconfig.spec.json",
    "lint:scss": "./node_modules/.bin/stylelint 'src/lib/**/*.scss' --fix",
    "lint": "yarn run lint:ts && yarn run lint:scss",
    "markdown:test-links": "./node_modules/.bin/markdown-link-check ./README.md",
    "//=> Section: Setup": "",
    "setup": "node ./tooling/setup.js",
    "//=> Section: Testing": "",
    "pretest": "yarn run build-test",
    "test": "concurrently \"yarn run build-test:watch\" \"karma start karma.conf.js\"",
    "pretest:ci": "yarn run build-test",
    "test:ci": "karma start karma.conf.js --single-run --code-coverage --sauceLabs",
    "//=> Section: Tooling": "",
    "commitmsg": "validate-commit-msg",
    "validate:circleci": "circleci config validate -c .circleci/config.yml",
    "cm": "./node_modules/.bin/git-cz",
    "todo": "./node_modules/.bin/notes -x node_modules/ -x out-tsc/ -x dist/ -x coverage/ -x src/demo/ -x integration/ -x docs/ -x .DS_Store -x README.md -x src/lib/helpers.scss",
    "precommit": "lint-staged",
    "lint-staged": "lint-staged"
  },
  "lint-staged": {
    "src/lib/**/*.spec.ts": [
      "lint:ts-spec",
      "git add"
    ],
    "src/lib/**/*!(.(spec|mock)).ts": [
      "lint:ts",
      "git add"
    ],
    "src/lib/**/*.scss": [
      "lint:scss",
      "git add"
    ]
  },
  "config": {
    "loglevel": "verbose",
    "commitizen": {
      "path": "./node_modules/cz-customizable"
    },
    "cz-customizable": {
      "config": "./tooling/cz-config.js"
    }
  },
  "release": {
    "verifyConditions": [
      "condition-circle",
      "@semantic-release/changelog",
      "@semantic-release/npm",
      "@semantic-release/git",
      "@semantic-release/github"
    ],
    "getLastRelease": "@semantic-release/npm",
    "publish": [
      "@semantic-release/changelog",
      {
        "path": "@semantic-release/npm",
        "assets": [
          "dist/**/*.{js|css|scss|ts|map}"
        ]
      },
      "@semantic-release/git",
      "@semantic-release/github"
    ]
  },
  "dependencies": {
    "@angular/animations": "5.1.1",
    "@angular/cdk": "5.0.1",
    "@angular/core": "5.1.1",
    "@angular/forms": "5.1.1",
    "@angular/material": "5.0.1",
    "@angular/platform-browser": "5.1.1",
    "@angular/router": "5.1.1"
  },
  "devDependencies": {
    "@angular/cli": "1.6.0",
    "@angular/common": "5.1.1",
    "@angular/compiler": "5.1.1",
    "@angular/compiler-cli": "5.1.1",
    "@angular/flex-layout": "2.0.0-beta.12",
    "@angular/http": "5.1.1",
    "@angular/platform-browser-dynamic": "5.1.1",
    "@compodoc/compodoc": "1.0.5",
    "@semantic-release/changelog": "1.0.0",
    "@semantic-release/git": "2.0.0",
    "@semantic-release/github": "2.2.3",
    "@semantic-release/npm": "2.3.1",
    "@types/jasmine": "2.8.2",
    "@types/node": "8.5.0",
    "autoprefixer": "7.2.3",
    "camelcase": "4.1.0",
    "code-notes": "1.0.4",
    "codelyzer": "4.0.2",
    "commitizen": "2.9.6",
    "concurrently": "3.5.1",
    "condition-circle": "2.0.1",
    "core-js": "2.5.3",
    "cz-customizable": "5.2.0",
    "del": "3.0.0",
    "doctoc": "1.3.0",
    "execa": "0.8.0",
    "glob": "7.1.2",
    "global": "4.3.2",
    "gulp": "gulpjs/gulp#4.0",
    "gulp-better-rollup": "2.0.0",
    "gulp-cli": "1.4.0",
    "gulp-concat": "2.6.1",
    "gulp-postcss": "7.0.0",
    "gulp-print": "2.0.1",
    "gulp-remove-empty-lines": "0.1.0",
    "gulp-replace": "0.6.1",
    "gulp-sass": "3.1.0",
    "gulp-sourcemaps": "2.6.1",
    "gulp-strip-json-comments": "2.1.0",
    "hammerjs": "2.0.8",
    "husky": "0.14.3",
    "jasmine-core": "2.8.0",
    "karma": "1.7.1",
    "karma-chrome-launcher": "2.2.0",
    "karma-cli": "1.0.1",
    "karma-coverage": "1.1.1",
    "karma-coverage-istanbul-reporter": "1.3.0",
    "karma-html-reporter": "0.2.7",
    "karma-jasmine": "1.1.1",
    "karma-jasmine-html-reporter": "0.2.2",
    "karma-mocha-reporter": "2.2.5",
    "karma-remap-coverage": "0.1.4",
    "karma-sauce-launcher": "1.2.0",
    "karma-sourcemap-loader": "0.3.7",
    "karma-typescript": "3.0.8",
    "lint-staged": "6.0.0",
    "lite-server": "2.3.0",
    "lodash.clonedeep": "4.5.0",
    "markdown-link-check": "3.1.5",
    "merge-files": "0.1.1",
    "node-sass": "4.7.2",
    "node-sass-import": "1.1.1",
    "nucleus-styleguide": "1.1.1",
    "onchange": "3.3.0",
    "remap-istanbul": "0.9.5",
    "replace-in-file": "3.0.0",
    "require-dir": "0.3.2",
    "rimraf": "2.6.2",
    "rollup": "0.52.1",
    "rollup-plugin-commonjs": "8.2.6",
    "rollup-plugin-node-resolve": "3.0.0",
    "rollup-plugin-uglify": "2.0.1",
    "rxjs": "5.5.5",
    "sass-lint": "1.12.1",
    "sass-module-importer": "1.4.0",
    "scssfmt": "1.0.2",
    "semantic-release": "11.0.2",
    "stylelint": "8.3.1",
    "stylelint-order": "0.8.0",
    "systemjs": "0.20.19",
    "tslint": "5.8.0",
    "typescript": "2.6.2",
    "validate-commit-msg": "2.14.0",
    "zone.js": "0.8.18"
  }
}
```
Here is what is output: https://unpkg.com/@terminus/ui@1.1.4/

**Comment by benjamincharity** [comment]
I even tried to fork `@semantic-release/npm` to add my own `dist/` option but the npm command just fails now `An error occurred while running semantic-release: { Error: Command failed: npm publish dist/` so no go :/

**Comment by pvdlg** [comment]
In your config it seems your are trying to publish with the `git`, `github` and `npm` plugin. You are configuring `assets` in the `npm` plugin which is not an option that exists for this plugin.

Can you clarify what you are trying to publish where ?
Are you trying to commit the content the of `dist` ? Or only build the tarball with `dist` as the root?

I didn't check but running `semantic-release` from `dist` should work: `cd dist && semantic-release`

**Comment by benjamincharity** [comment]
Sorry, yeah I'd gotten to just trying random things..

I just need to publish the contents of `dist/` to NPM.

Previously my release was handled like so:

```bash
yarn run semantic-release-pre

// My build step packages all files etc (including the package.json) into the `dist/` directory.
yarn run build

npm publish dist/

yarn run semantic-release-post
```

My release object now looks like this:

```
  "release": {
    "verifyConditions": [
      "condition-circle",
      "@semantic-release/changelog",
      "@semantic-release/npm",
      "@semantic-release/git"
    ],
    "getLastRelease": "semantic-release-npm",
    "publish": [
      "@semantic-release/changelog",
      "@semantic-release/npm",
      "@semantic-release/git"
    ]
  },
```

Trying to run semantic release from `dist/` throws this error: `semantic-release: command not found` and trying to install it globally really seems to make CircleCI go nuts (over 400,000 lines of output)

**Comment by pvdlg** [comment]
In your  circle config`config.yml` just call `cd dist && npm run semantic-release`

**Comment by pvdlg** [comment]
If you want to install `semantic-release` globally do `npm i -g semantic-release` and not `npm i -g semantic-release-cli`. `semantic-release-cli` is used to set up the configuration.

**Comment by blakedietz** [comment]
`cd dist && npm run semantic-release` doesn't work @pvdlg.

**Comment by benjamincharity** [comment]
Hmm still not having any luck.  I needed sudo for the semantic-release install: `sudo npm i -g semantic-release`. But I still get the 'command not found' error. I've tried running `npm run semantic-release from dist and from my root and from my circle ci config file.

I created an NPM script `"semantic-release": "semantic-release"` and tried `cd dist && yarn run semantic-release` in my circle ci config. But that gives me `error Command failed with exit code 1.`

**Comment by blakedietz** [comment]
Seems like you would need to run `cd dist && ../node_modules/.bin/semantic-release pre && ...`.

**Comment by pvdlg** [comment]
> cd dist && npm run semantic-release doesn't work @pvdlg.

I just tried locally and it works for me. Can add more details? What do you meant exactly by "doesn't work"? Can you provide the error message or a link or your build?

**Comment by pvdlg** [comment]
In your `package.json`:
```json
"devDependencies": {
  "semantic-release": "^11.0.0"
},
"script": {
  "semantic-release": "semantic-release"
}
```
In your Circle config:
```yaml
- run:
  command: cd dist && npm run semantic-release
```

Make sure the `dist` directory exists before `cd dist && npm run semantic-release` is executed.

**Comment by pvdlg** [comment]
> Seems like you would need to run cd dist && ../node_modules/.bin/semantic-release pre && ....

I don't see why. `npm` or `yarn` can run scripts defined in a `package.json` from a parent directory.

**Comment by blakedietz** [comment]
`@pvdlg Are you installing `semantic-release` globally?

Here's the output for the deploy when I'm doing that from the circle box.
```
circleci@a17ba19938b9:~/repo/build$ npm run semantic-release

> blake-dietz-ts-ui-2@1.0.0 semantic-release /home/circleci/repo/build
> semantic-release pre && npm publish && semantic-release post

sh: 1: semantic-release: not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! blake-dietz-ts-ui-2@1.0.0 semantic-release: `semantic-release pre && npm publish && semantic-release post`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the blake-dietz-ts-ui-2@1.0.0 semantic-release script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/circleci/.npm/_logs/2017-12-19T02_35_02_632Z-debug.log```

**Comment by pvdlg** [comment]
@blakedietz

No it's installed locally.
I'm running exactly the config from https://github.com/semantic-release/semantic-release/issues/570#issuecomment-352621488

If you use `yarn` I remember there was an issue with older version of `semantic-release`. You should `^11.0.0` in your `package.json` as mentioned above.

**Comment by blakedietz** [comment]
@pvdlg not using yarn, but I was using an older version before reading this thread. That command was hydrated from earlier. I'll try your configs out with the latest version of `semantic-release`.

**Comment by blakedietz** [comment]
@pvdlg Thanks for the heads up that helped. I'm using npm 5.5.1 and these are the configs based upon yours that I used that worked.

```
  "name": "blake-dietz-test",
  "version": "0.0.0-development",
  "description": "A ui-library for creating applications consistent with the TSheets style guidelines.",
  "main": "./src/index.js",
  "scripts": {
    "build": "npm run build:es2015 && npm run build:es2015modules && npm run build:copy-files",
    "build:copy-files": "babel-node ./scripts/copy-files.js",
    "build:es2015": "NODE_ENV=production BABEL_ENV=es babel ./src --out-dir ./build",
    "build:es2015modules": "NODE_ENV=production BABEL_ENV=modules babel ./src/index.js --out-file ./build/index.es.js",
    "build:storybook": "build-storybook -c .storybook -o .out",
    "commit": "git-cz",
    "deploy:storybook": "storybook-to-ghpages",
    "ci-deploy:storybook": "git config --global user.email $GH_EMAIL && git config --global user.name $GH_NAME && storybook-to-ghpages",
    "lint": "eslint . --cache && echo \"eslint: no lint errors\"",
    "postrelease": "npm publish build --tag next",
    "prebuild": "rimraf build",
    "prettier": "find . -name \"*.js\" | grep -v -f .eslintignore | xargs prettier --write",
    "storybook": "start-storybook -p 9001 -c .storybook",
    "test": "echo \"Error: no test specified\" && exit 1",
    "semantic-release": "semantic-release"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/blakedietz/blake-dietz-tsheets-ui-test.git"
  },
  "keywords": [
    "material design",
    "material-ui",
    "react",
    "react-component",
    "theme",
    "tsheets"
  ],
  "author": "",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/blakedietz/blake-dietz-tsheets-ui-test/issues"
  },
  "homepage": "https://github.com/blakedietz/blake-dietz-tsheets-ui-test",
  "devDependencies": {
    "@semantic-release/changelog": "1.0.0",
    "@semantic-release/git": "2.0.0",
    "@semantic-release/github": "2.2.3",
    "@semantic-release/npm": "2.3.1",
    "@storybook/react": "^3.2.17",
    "@storybook/storybook-deployer": "^2.2.0",
    "babel-cli": "^6.26.0",
    "babel-core": "^6.26.0",
    "babel-eslint": "^8.0.3",
    "babel-plugin-transform-dev-warning": "^0.1.0",
    "babel-plugin-transform-object-assign": "^6.22.0",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-preset-env": "^1.6.1",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-1": "^6.24.1",
    "commitizen": "^2.9.6",
    "condition-circle": "^2.0.1",
    "cz-conventional-changelog": "^2.1.0",
    "eslint": "^4.12.1",
    "eslint-config-airbnb": "^16.1.0",
    "eslint-config-prettier": "^2.9.0",
    "eslint-plugin-babel": "^4.1.2",
    "eslint-plugin-import": "^2.8.0",
    "eslint-plugin-jsx-a11y": "^6.0.2",
    "eslint-plugin-prettier": "^2.3.1",
    "eslint-plugin-react": "^7.5.1",
    "fs-extra": "^5.0.0",
    "jest": "^21.2.1",
    "prettier": "^1.9.1",
    "rimraf": "^2.6.2",
    "semantic-release": "11.0.2"
  },
  "dependencies": {
    "material-ui": "^1.0.0-beta.22",
    "react": "^16.2.0",
    "react-dom": "^16.2.0"
  },
  "config": {
    "loglevel": "verbose",
    "commitizen": {
      "path": "node_modules/cz-conventional-changelog"
    }
  },
  "release": {
    "verifyConditions": [
      "condition-circle",
      "@semantic-release/changelog",
      "@semantic-release/npm",
      "@semantic-release/git",
      "@semantic-release/github"
    ]
  }
}
```

**Comment by blakedietz** [comment]
@benjamincharity does my config help?

**Comment by pvdlg** [comment]
@blakedietz,

a few unrelated problems in your config:
- You are setting some plugins in `verifyConditions` but not for `publish` and `getLastRelease` so it doesn't make sense as those plugin won't be used. `verifyConditions` just verify that everything is ok for this plugins to be used in `publish` and `getLastRelease`
- `run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc` is unnecessary as it's already done by the `npm` plugin
- You might want to configure you `devDependencies` to `"semantic-release": "^11.0.2"` instead of `"semantic-release": "11.0.2"` so you will fixes and non breaking features automatically
- `"@semantic-release/npm": "2.3.1"` and `"@semantic-release/github": "2.2.3"` are unnecessary as they are already dependencies of `semantic-release` 
- `run: cd build && ../node_modules/.bin/semantic-release` can be replaced by `run: cd build && npm run semantic-release` so the `package.json` in your `build` directory (the one published) will be used

**Comment by blakedietz** [comment]
@pvdlg thanks for your recommendations! Seriously, you were super fast! A lot of that previous cruft was from other tutorials about the older version of semantic-release, glad to clean it all up! Everything worked except for

> run: cd build && ../node_modules/.bin/semantic-release can be replaced by run: cd build && npm run semantic-release so the package.json in your build directory (the one published) will be used

due to the same reasons that I had mentioned earlier.

**Comment by pvdlg** [comment]
> due to the same reasons that I had mentioned earlier.

Ok, good to know. Somehow locally for me, `npm` is capable of running the script has expected from a sub-directory. Don't know what the different is. Anyway if it works, all good!

**Comment by benjamincharity** [comment]
Thanks for the crazy fast responses guys! 🙏 

Ok, it feels like I'm getting very close.. I'm failing now on the changelog generation but I'm not really sure why. I can survive with the changelogs simply living in the Github releases if needed.  But looking at @blakedietz's config, it seems like this should work:

```bash
[Semantic release]: Wrote version 1.1.7 to package.json
[Semantic release]: Publishing version 1.1.7 to npm registry
+ @terminus/ui@1.1.7[Semantic release]: Add package.json to the release commit
[Semantic release]: Found 1 file(s) to commit
[Semantic release]: An error occurred while running semantic-release: { Error: Command failed: git commit -m chore(release): 1.1.7 [skip ci]

<a name="1.1.7"></a>
## [1.1.7](https://github.com/GetTerminus/terminus-ui/compare/v1.1.6...v1.1.7) (2017-12-19)


### Bug Fixes

* **CI:** try running yarn install with no token generation ([450733b](https://github.com/GetTerminus/terminus-ui/commit/450733b))


On branch master
Your branch is up-to-date with 'origin/master'.
Untracked files:
	../coverage/

nothing added to commit but untracked files present

    at Promise.all.then.arr (/home/circleci/ci-build/node_modules/execa/index.js:236:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
  code: 1,
  killed: false,
  stdout: 'On branch master\nYour branch is up-to-date with \'origin/master\'.\nUntracked files:\n\t../coverage/\n\nnothing added to commit but untracked files present\n',
  stderr: '',
  failed: true,
  signal: null,
  cmd: 'git commit -m chore(release): 1.1.7 [skip ci]\n\n<a name="1.1.7"></a>\n## [1.1.7](https://github.com/GetTerminus/terminus-ui/compare/v1.1.6...v1.1.7) (2017-12-19)\n\n\n### Bug Fixes\n\n* **CI:** try running yarn install with no token generation ([450733b](https://github.com/GetTerminus/terminus-ui/commit/450733b))\n\n\n\n',
  timedOut: false }
Exited with code 1
```

Build if it helps: https://circleci.com/gh/GetTerminus/terminus-ui/1103

**Comment by benjamincharity** [comment]
I'm also not entirely sure what the difference is between the git and github plugins. I noticed both in the shared config above so I tried adding both to mine with the same error as above

**Comment by pvdlg** [comment]
Have you check the documentation in the README.md of each plugin? Everything should be there.
If the doc is not clear let us know.

The error you have is because you use the `changelog` plugin to create/update a `CHANGELOG.md` file and the `git` plugin to commit it. But you create it in a directory that is in the `.gitignore` so when doing the commit, there is an error because there is nothing to commit.

**Comment by benjamincharity** [comment]
I have. I've spent much more time configuring semantic-release (old version and new version) than any other resource or tool. The benefit of semantic-release, when working, is great enough for me to spend this time so far. The docs are pretty good if you are setting it up for the first time and want to use it as-is. But as soon as a specific need arises, like wanting to release a specific directory, things seem to get a bit hairy. Please don't take this as negatives, I'm very grateful for the work that has been done on this tool 🙏 

---

Hmm ok, yeah that definitely sounds like an issue..

Even without the changelog plugin, I see the same error. I'm assuming that this is because semantic-release is still trying to create a release commit in this ignored directory? So it seems that the Git part of SR needs to be run in my root, but the NPM part of SR needs to run inside my dist which is ignored.

Is tracking my dist the most simple solution?

**Comment by pvdlg** [comment]
> I'm assuming that this is because semantic-release is still trying to create a release commit in this ignored directory? So it seems that the Git part of SR needs to be run in my root, but the NPM part of SR needs to run inside my dist which is ignored.

Yes. If you don't need to push a commit then, just don't use the `git` plugin.
If you use the `github` plugin it will create a Github Release with the changelog.

> Is tracking my dist the most simple solution?

Probably not. The simple solution is to not package from a subdirectory. Doing create a lot of complexity (besides semantic-release). It forces you to copy your `package.json`, `README.md`, `CHANGELOG.md` etc... in the `dist` directory. In addition I imagine it forces to to take in account the different paths when you `require` in your JS files.
The more common way to handle that is to specify in your `package.json` what you want to include in the release with the `files` property.
You can find more details in this blog post: log.npmjs.org/post/165769683050/publishing-what-you-mean-to-publish

**Comment by benjamincharity** [comment]
I originally was using the standard way of defining which files to publish. I just ran into a lot of issues trying to build my project into my src dir, cleaning up files, organizing my npm package files etc. It just ended up being way easier to build everything into a specific dir. Copying a few files is a one-liner and paths aren't an issue (the build is generated from src and just simply specifies an output dir).

NPM makes it easy to include files in your release, but afaict we have no control over the organization. I've even seen other library maintainers resorting to listing out every individual file in their files array

---

Either way, removing the changelog and git plugins got me back to releasing so I will close this issue. 

I am **very** grateful for your help here!

**Comment by pvdlg** [comment]
Thanks for the positive attitude :) Much appreciated!

I'm going to spend a bit more time to figure out if it's possible to add a new option to the `npm` plugin to do the packaging from a sub-directory.
I'm not really sure how npm works in such case (does it use the `package.json` at the repo root, or the one on the sub-directory? What about `npm-shrinkwrap.json`? Does it includes the `CHANGELOG.md` and `README.md` at the root? Does it interpret the `.npmignore` and `files` property relative to the repo root or to the sub-directory? etc... ).

**Comment by blakedietz** [comment]
@pvdlg I think it's all just based upon the directory you give to publish. It's up to you to copy the necessary files over into the directory that you're publishing. See https://github.com/mui-org/material-ui/blob/v1-beta/scripts/copy-files.js for an example of a package publishes a built directory and the associated scripts.

**Comment by benjamincharity** [comment]
Of course! I'm grateful to not have the ability to screw up my version numbers now ;)

---

Yep, once my `package.json`, `README.md` etc is moved into my `dist` dir I can run `npm publish dist/` from the root directory.

I haven't directly used an `.npmignore` or `npm-shrinkwrap.json`, but I would assume those would need to be manually moved also.

Also, I believe publishing a directory is something done instead of the files array rather than using both.

**Comment by pvdlg** [comment]
@benjamincharity is semantic-release/npm#23 helps to solve your use case better?
