### ISSUE TITLE
Latest version?

### ISSUE THREAD

**Issue by kbrandwijk** [semantic-release/semantic-release#579]
On the releases tab, I see 11.2.0 as latest version. However, on npmjs, I see 11.0.3 as latest version. Especially for a library to support automatic release management, it seems weird to me that there is a version mismatch going on...

**Comment by pvdlg** [comment]
Duplicate of #577

**Comment by pvdlg** [comment]
See https://github.com/semantic-release/semantic-release/issues/577#issuecomment-354334044

**Comment by kbrandwijk** [comment]
Sorry... missed that one...
