### ISSUE TITLE
Releasing fails on Travis: Object does not exist

### ISSUE THREAD

**Issue by schickling** [semantic-release/semantic-release#582]
I'm not sure whether this is a temporary problem with Travis/Github but running `semantic-release` seems to fail for the last couple of commits for [this repo](https://github.com/graphcool/graphql-schema-cache).

Travis Logs: https://travis-ci.org/graphcool/graphql-schema-cache/jobs/323572780#L535-L560

Error message:

```
+ graphql-schema-cache@0.3.4[Semantic release]: An error occurred while running semantic-release: { [Error: {"message":"Object does not exist","documentation_url":"https://developer.github.com/v3/git/refs/#create-a-reference"}]
  message: '{"message":"Object does not exist","documentation_url":"https://developer.github.com/v3/git/refs/#create-a-reference"}',
  code: 422,
  status: 'Unprocessable Entity',
  headers: 
   { server: 'GitHub.com',
     date: 'Sun, 31 Dec 2017 14:47:59 GMT',
     'content-type': 'application/json; charset=utf-8',
     'content-length': '118',
     connection: 'close',
     status: '422 Unprocessable Entity',
     'x-ratelimit-limit': '5000',
     'x-ratelimit-remaining': '4769',
     'x-ratelimit-reset': '1514733880',
     'x-oauth-scopes': 'repo, read:org, user:email, repo_deployment, repo:status, write:repo_hook',
     'x-accepted-oauth-scopes': '',
     'x-github-media-type': 'github.v3; format=json',
     'access-control-expose-headers': 'ETag, Link, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval',
     'access-control-allow-origin': '*',
     'content-security-policy': 'default-src \'none\'',
     'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
     'x-content-type-options': 'nosniff',
     'x-frame-options': 'deny',
     'x-xss-protection': '1; mode=block',
     'x-runtime-rack': '0.129699',
     'x-github-request-id': '8B72:16655:A81291E:11CEBEF1:5A48F89E' } }
```

**Comment by pvdlg** [comment]
It seems the problem happen when we check for the existence of the tag on GitHub. If the tag doesn't exists the GitHub API is supposed to return a 404 status and not a 422.

Can you enable the debug logs with the environment variable `DEBUG` set to `semantic-release:*` and re-run your build?

**Comment by schickling** [comment]
Thanks, I'll manually recover by adding the tag to Git.

Here is a build using the `DEBUG` env var set: https://travis-ci.org/graphcool/graphql-config-extension-graphcool/builds/323760453

**Comment by pvdlg** [comment]
> Thanks, I'll manually recover by adding the tag to Git.

The is an error different than the `422 Unprocessable Entity` you add previously.

It seems everything works now: https://travis-ci.org/graphcool/graphql-config-extension-graphcool/jobs/323763719#L547 so I imagine the `422 Unprocessable Entity` was a temporary error on the GitHub API side.

Can you confirm everything works as expected now?

**Comment by schickling** [comment]
Yes, after manually adding and pushing the missing git tag, everything worked!
