### ISSUE TITLE
Add a CircleCI option in the CLI setup

### ISSUE THREAD

**Issue by schickling** [semantic-release/semantic-release#588]
We've recently adopted `semantic-release ` for most of our open-source packages and it has been amazing. Before, we've been mostly using CircleCI but since TravisCI seems to be best supported by this package, we've been moving over to Travis. Unfortunately, we've seen 3-10x slowdowns (!!!) compared to CircleCI and would love to move back.

The only thing that's holding us back at the moment is, that we don't want to add the `condition-circle` dependency and configuration to all of our repositories (in order to keep them minimal).

Given that more and more people are looking to move over to CircleCI, it would be great if CircleCI would be supported out of the box by `semantic-release` (i.e. `semantic-release-cli setup` configures CircleCI and there's a CircleCI plugin shipped by default without the need to install any further package besides `semantic-release`).

Thanks so much & happy new year! 🎆

**Comment by kbrandwijk** [comment]
I have just tested this with `semantic-release` 12.0.0 (the first CI agnostic version), and everything seems to run smoothly without needing the `condition-circle` plugin.
However, I think this issue is still relevant to provide better support for Circle CI on the `semantic-release-cli`.

**Comment by pvdlg** [comment]
A recipe for Circle CI will be added in #573. But indeed it would be great to have the cli offering the Circle CI choice and generating the config file

**Comment by kbrandwijk** [comment]
I already have this working locally, so I'll submit a PR to the cli for this. The only issue is the fact that you need to create an API token on Circle CI. Two forum issues on CircleCI about using GH tokens for authentication have been dead for over a year now.

**Comment by pvdlg** [comment]
Can you do something to what we do with GitHub and NPM in the CLI? And ask the users for their CircleCI user/password and authenticate with that?

**Comment by kbrandwijk** [comment]
Unfortunately, the only way to authenticate against the CircleCI API is using an API token that the user has to created on CircleCI. No GH token or username/password authentication possible...

**Comment by kbrandwijk** [comment]
@pvdlg I think the only thing I can do for now is use keytar like for Github password to store the API token after asking it once. Would that be a good idea?

**Comment by pvdlg** [comment]
That's quite unfortunate the API is sot flexible. It seems that what you propose is the only solution...

@gr2m any thoughts?

**Comment by gr2m** [comment]
thanks for the testing and the PR @kbrandwijk @schickling. I reviewed the PR at #167 and code-wise it looks good. I don’t have a CircleCI setup to test it out and don’t have the time to do so, but I trust you that it works :) 

Would you be interested in joining the semantic-release community and help out with all things related to CircleCI? Neither Pierre nor I do have a lot of experience with it, so it would be very helpful to have you (and other folks interested) to take ownership of making sure that semantic-release works great with it.

We don’t have a lot of processes in place yet, but I’d setup a new Team and invite you both to it, so we can mention in in related issues / PRs and give you write access to all relevant repos, so you can create pull requests from branches instead of forks, among other things.

Let me know if you are interested  :)

**Comment by kbrandwijk** [comment]
@gr2m Sounds great, I'm interested! I'm looking to improve on the workflow some more by making it possible to add the `semantic-release` step to an existing configuration as well, for example. So count me in.

**Comment by gr2m** [comment]
@kbrandwijk sorry for the delay! https://github.com/semantic-release/cli/pull/167 is merged 🎉 And I’ve invited you to the newly created @semantic-release/CircleCI team :) It currently has write access to the `cli` repository and I’ll give it access to all repos as needed

Yay, welcome to the team! Hope we can chat some time soon!

Can we close this issue now?

**Comment by kbrandwijk** [comment]
Great! I haven't seen the invite yet though. It normally shows up right away. And yes, as far as I'm concerned, this can be closed now. Do you have a Slack channel?

**Comment by gr2m** [comment]
sorry my fault, you should have gotten it now :)

**Comment by kbrandwijk** [comment]
Yep, thanks!
