### ISSUE TITLE
Cannot run semantic-release script

### ISSUE THREAD

**Issue by hoodwink73** [semantic-release/semantic-release#599]
## Current behavior

Run `npm run semantic-release` 

**Error**:

```
Semantic release]: An error occurred while running semantic-release: %O /Users/arijit/Documents/Playground/gs-semantic-release-github/node_modules/semantic-release/lib/plugins/normalize.js:9
  const {path, ...config} = isString(pluginConfig) || isFunction(pluginConfig) ? {path: pluginConfig} : pluginConfig;
               ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/arijit/Documents/Playground/gs-semantic-release-github/node_modules/semantic-release/lib/plugins/index.js:4:19)
```

## Expected behavior

The script should proceed with validation, creating logs and publishing.

## Environment

- **semantic-release** version: ^11.0.2 
- Plugins used: Using default plugins 
- **semantic-release** configuration: no external configuration 
-  node v8.0
-  npm v5.0.1

**Comment by pvdlg** [comment]
It seems the [Object spread properties](http://node.green/#ESNEXT-candidate--stage-3--object-rest-spread-properties-object-spread-properties) feature require a version slightly higher than `8.0.x`.

It should work if you install a more recent Node 8 version (like `8.6.0`).

We should update the documentation to mention we require that version.

**Comment by hoodwink73** [comment]
Thanks Pierre 

This is awesome work. I appreciate the effort that went into this project to combine the scattered ideas into an end to end semantic release workflow.

**Comment by hoodwink73** [comment]
There are frameworks which are yet to adopt newer versions of node. Can we transpile the dist code with babel to help older versions of node run `semantic-release`?

**Comment by pvdlg** [comment]
Yes but it a choice to support only certain version of Node. You can find the reasons and solutions there: https://semantic-release.gitbooks.io/semantic-release/content/docs/support/node-version.html

**Comment by kbrandwijk** [comment]
@pvdlg Regarding the nvm solution in the docs, from the `nvm` docs it seems that you need to run `nvm use` after `nvm install` to actually use that version.

**Comment by pvdlg** [comment]
I tested on Travis and locally, `nvm install 8` does install and use it. Do you see a different behavior?
