### ISSUE TITLE
BREAKING CHANGE does not trigger a release when in title

### ISSUE THREAD

**Issue by frank-long** [semantic-release/semantic-release#608]
BREAKING CHANGE does not trigger a release when in the title, it only works when in the description, this is different to the example in the docs Readme and also different to how fix and feat  work see the logs below

Found version 3.0.0 of package my-test with dist-tag latest
[Semantic release]: Found 1 commits since last release
[Semantic release]: Call plugin analyze-commits
[Semantic release]: Analyzing commit: BREAKING CHANGE: my title

My Description
[Semantic release]: The commit should not trigger a release
[Semantic release]: Analysis of 1 commits complete: no release
[Semantic release]: There are no relevant changes, so no new version is released.

**Comment by frank-long** [comment]
I'm using 12.2.2 of sematic-release

**Comment by frank-long** [comment]
I think this is the default behaviour for angular config.... closing

**Comment by luftywiranda13** [comment]
@frank-long yes it is. Clearly inconsistency in the docs.<br />
People write `BREAKING CHANGE` in the body/description of commit to trigger releasing a major version, not in the title.
