### ISSUE TITLE
[docs] travis-ci config recommendation is risky

### ISSUE THREAD

**Issue by travi** [semantic-release/semantic-release#609]
## Current behavior

the [current recommendation](https://semantic-release.gitbooks.io/semantic-release/content/docs/recipes/travis.html#single-node-job-configuration) for configuring travis-ci suggests listing `npm run semantic-release` as a step under the `script` stage of the `.travis.yml` (after the `npm test` step).

```yml
script:
- npm test
- npm run semantic-release
```

Unfortunately, even if the `npm test` step exits with non-zero, [the default behavior for travis](https://github.com/travis-ci/travis-ci/issues/1066) is to continue executing the remaining steps in the `script` stage. The `script` stage fails overall, but not until all steps have been executed.

This means that a version of a package would be released even if `npm test` fails.

## Expected behavior

The script to release a new package version should not be run if `npm test` fails. Before I started using semantic-release, I always used to configure the `preversion` npm script to run `npm test` to ensure this wouldn't happen. However, since semantic-release runs in a CI environment, that step should have already happen (and I should be able to assume that the build would stop if a failure occurred), so I've stopped doing that to avoid running that script twice.

## Environment
Some of the important bits of the build output:

```
$ npm test

... 

The command "npm test" exited with 1.
$ npm run semantic-release

The command "npm run semantic-release" exited with 0.

Done. Your build exited with 1.
```

## Suggested Change

Is there a reason not to recommend running semantic-release in the `deploy` stage instead of the `script` stage? That seems to be the action we actually are taking anyway. Plus, if the `script` stage fails, the `deploy` stage should not happen.

```yml
deploy:
  provider: script
  skip_cleanup: true
  script: npm run semantic-release
```

**Comment by pvdlg** [comment]
Whaow I'm shocked to see that! I was convinced that in the `script` phase any failure would prevent other step to run. That really sounds like a bug in Travis to me...Most CI work that way.

We indeed need to change the documentation (and the config of semantic-release repos!).

We could run `semantic-release` in the `after_success` but if `semantic-release` fails the build doesn't fail, so users are not aware of the problem.

Using `deploy` seems to be the best solution, however when doing so I have the message `!!! Script support is experimental !!!`. So if it's a beta thing maybe it's not that great for now.

An other solution is to keep it in script but do `npm run test && semantic-release`. But it's not really elegant and can be complex for users having multiple scripts in the `script` phase.

Not sure what the best solution is, but I'm leaning toward the `deploy` step as suggested by @travi

**Comment by travi** [comment]
>  I was convinced that in the script phase any failure would prevent other step to run. That really sounds like a bug in Travis to me...Most CI work that way.

same here until my team member noticed a failure that still continued on to publish today. he found the issue thread that i linked above and it seems like most would agree that it is unexpected, but they dont seem very interested in changing it. I expected it to work as if the steps were separated by `&&`, but instead appears to behave like `;`

my team has been using the `script` deploy provider successfully for several tasks for quite a while, but i only thought to go that route as part of our conversation today after running into this issue. 

i used to to the `after_success` stage, but we definitely had cases where we would be unaware of failed publishes.

i just went through the process of moving a bunch of projects over to use the `script` stage instead of `after_success`, but it looks like ill be needing to go back and give the `deploy` stage a try now. i think that one should at least accomplish the the desired goal.

**Comment by pvdlg** [comment]
We should probably change the ASAP to avoid user to end up in the same situation.

I'm definitely interested to get feedback from you regarding the `deploy` step.

@gr2m what do you think about changing the doc to recommend using the `deploy` step as proposed by @travi ?

**Comment by gr2m** [comment]
wow I also did not know that! 0_o

Yeah let’s use deploy for now. Eventually using stages will probably be the best thing to do, but for now let’s make sure we replace the current recommendation

Thanks @travi 🙇

**Comment by travi** [comment]
> I'm definitely interested to get feedback from you regarding the deploy step.

Anything in particular that you're interested in beyond the fact that it's been working well for us for other tasks?

**Comment by pvdlg** [comment]
> Anything in particular that you're interested in beyond the fact that it's been working well for us for other tasks?

I'm just concern about the fact Travis says it's experimental.

**Comment by travi** [comment]
it is unfortunate that it still prints that message in the output, but its been available as a provider for quite a while. i don't understand why they would still consider it experimental. theres [not much to it](https://github.com/travis-ci/dpl/blob/master/lib/dpl/provider/script.rb) and hasnt been touched since [Apr 21, 2016](https://github.com/travis-ci/dpl/commit/7c69daec97e1b7e261f7705c38fac3af4a38343a#diff-1c6ad0d4f864c8bfb7d1e62b8afef0f4).

it is an option to [submit another provider to travis](https://github.com/travis-ci/dpl#writing-and-testing-a-new-deployment-provider-and-new-functionality) if a `semantic-release` provider would be preferred longer term.

**Comment by felixfbecker** [comment]
The reason Travis works like that is so that you can still see the result of tests even if e.g. linting failed. Imo the docs should just use `after_success` again or build stages.

**Comment by travi** [comment]
A big part of the previous recommendation to use `after_success` was because semantic-release used to exit with non-zero for non-failure scenarios. Since `after_` steps don't fail the build, it was important to run from there. That problem has been fixed, so it seems less valuable to recommend an approach that wouldn't notify on failure as the only recommendation that doesn't require the added complexity of stages.

**Comment by pvdlg** [comment]
The reason we started to recommend to `script` instead of `after_success` was to fail builds when the release fail so the user will be aware of the problem. It was requested in #569.

We had several releases that didn't happen in the semantic-release repos and we weren't aware of it because the build didn't fail. So it turns out it's quite useful to have the build failing.

The PR #610 specifies:
> It's recommended to run the `semantic-release` command in the [Travis `deploy` step](https://docs.travis-ci.com/user/customizing-the-build/#The-Build-Lifecycle) so if an error occurs the build will fail and Travis will send a notification.

Even with the experimental warning there is more benefits to use `deploy` (or other solution that fails the build on error). Not sure if it worth mentioning `after_success`. I'd rather keep the documentation simple and less confusing for new comers. Advanced users can customize.

> A big part of the previous recommendation to use after_success was because semantic-release used to exit with non-zero for non-failure scenarios. Since after_ steps don't fail the build, it was important to run from there. That problem has been fixed, so it seems less valuable to recommend an approach that wouldn't notify on failure as the only recommendation that doesn't require the added complexity of stages.

Yes exactly.
