### ISSUE TITLE
Pre.js unit test are very broken.

### ISSUE THREAD

**Issue by ariporad** [semantic-release/semantic-release#61]
As I discovered with lots and lots of debugging while working on #60, the unit tests for pre.js (test/specs/pre.js) are badly broken.

With the old commit-analyzer API, the commit-analyzer would be called, and could trigger a release, even if no commits were present. For this reason, no body realized that pre.js was not actually stubbing `child_process`, the commit-analyzer was being called anyway.

Well, with the new API, the commit-analyzer is only called when needed, so the mocking has to work. Unfortunately, it doesn't.

I'm not really sure how the tests should be redone, AFAIK, proxyquire sandboxes the module, so the mock won't trickle down into commit.js. So I decided to open this to discuss it.

cc @boennemann

**Comment by boennemann** [comment]
Thanks for catching this very nasty bug! I didn't realize nested stubbing isn't possible, but after reading the docs it makes a lot of sense.

I addressed this now by wrapping the proxyquire calls into each other: https://github.com/semantic-release/semantic-release/commit/5cc7da6035e22660848c7960c9d18e6df1b7b0eb#diff-b2fc167aa2bf97d4559ff48a142cf3e4R6
