### ISSUE TITLE
Proposal: CLI argument to retrieve the version that will ultimately be published

### ISSUE THREAD

**Issue by kimsagro1** [semantic-release/semantic-release#612]
# Feature request

## New feature motivation

I am currently using semantic-release to publish a non-JavaScript package. In my scenario (and I imagine other non-javascript scenarios) I need to know what the published version will be BEFORE my build as the version number needs to be stamped into the produced assets during build.

Currently I am having to run semantic-release twice.. Once in `dry-run` mode to parse the version number from the output and the other after the build and test to do the actually release.

This is working, however parsing the cli output is brittle and tied to the output text.

It would be nice to have a cli option that simply outputs the next version number.

## New feature description

The change would need to be made in semantic-release by adding a cli argument that outputs the results of `getNextVersion`

**Comment by pvdlg** [comment]
Would the answer to [this FAQ](https://semantic-release.gitbooks.io/semantic-release/content/docs/support/FAQ.html#how-can-i-use-a-npm-build-script-that-requires-the-packagejsons-version-) would help?

**Comment by kimsagro1** [comment]
Thanks for your response, @pvdlg however I am publishing a non-javascript package so I do not have a `package.json`, I'm invoking `semantic-release` via an `npx` call.

**Comment by pvdlg** [comment]
Do you have by any change a link to your repo and your build scripts? I'm curious to know more about non Javascript project and in which circumstances they might need the version in their build script.
Getting to know more would allow us to come up with the best solution for this type of scenario.

**Comment by kimsagro1** [comment]
I cannot link to my repository as it is private, but basically in the `.net` world, we build out libraries via the following command

> dotnet build /p:AssemblyVersion=1.2.3.4

We pass the version number as part of the build process. The produced assets (in this case `*.dll` files) will them have the version number stamped into them.

We then need the version number again when packaging the assets for release

> dotnet pack /p:AssemblyVersion=1.2.3.4

This will then produce a release package `MyProject.1.2.3.4.nuget` which then gets deployed to github / nuget.

So contrary to the JavaScript world where the version number doesn't appear to be needed during the build phase only the release, we need it during both.

**Comment by pvdlg** [comment]
What is your semantic-release configuration? What plugin do you use to publish?

Maybe you could use the [exec plugin](https://github.com/semantic-release/exec) to run `dotnet build /p:AssemblyVersion=1.2.3.4` and `dotnet pack /p:AssemblyVersion=1.2.3.4` in the publish step before other plugins.

The exec plugin allow to run custom command and give you the possibility to pass the value in the semantic-release context, such as version.

**Comment by pvdlg** [comment]
The best would be what you mentioned at the end of the last comment. The `exec` plugin is probably a more simple solution creating a plugin if you have to just execute one or 2 shell commands.

You can create a shareable configuration similar to [apm-config](https://github.com/semantic-release/apm-config) if you'd like to.

Running the build twice (once for test and once for release) might seems inefficient, but here is a few things to consider:
- Most build scripts will take a few seconds or a few dozen of seconds, so the general impact on the total CI runtime will not be that big. Plus the extra build will happen only when a release is actually required.
- Everything in PR will not trigger a release not an extra build.
- If you test in multiple environments (for example Windows 64 bit + Windows 32 bits + Linux + different versions of .Net) you will need to configure multiple CI jobs. That mean you will probably use something like [Travis Build Stages](https://docs.travis-ci.com/user/build-stages) and configure one job per environment/version + 1 job to make the release. In such situation will have to make a build specifically for the release step anyway, as the release job will have to run after all other are successful.

**Comment by kimsagro1** [comment]
Thanks for your patience and response, I will go down the path you suggested. Feel free to close this proposal out.

**Comment by pvdlg** [comment]
Awesome! Let us know how it goes. You can ping me if you need help.

**Comment by mynkow** [comment]
@kimsagro1 how it went? Did you manage to complete your task? I am trying to do the same but I am not able to find your contribution. Please advise!
