### ISSUE TITLE
custom deploy to GitHub release branch

### ISSUE THREAD

**Issue by abhishek199-dhn** [semantic-release/semantic-release#614]
## Use case
Currently, I'm developing a library (private repo) and I need to publish and release it over GitHub (without npm publish). The master branch contains the source code and the release branch contains only the build files.
And the release is made from release branch containing zip files(assets) and changelogs. 

## Release WorkFlow
- git checkout master
- created a **build** folder containing files to publish
- **commit** and **push** the build folder to **release** branch (using [deploy-to-git](https://github.com/finom/deploy-to-git) package to push the code to release branch)
- create a **git release** from **release** branch with assets and changelog.md files using semantic release.

## Current behavior
package.json
```
{
  "name": "di-ui-component-lib",
  "version": "1.0.0-next",
  "description": "UI Component Library",
  "main": "./src/library/index.js",
  "private": true,
  "scripts": {
    ...
    "build": "yarn build:es2015 && yarn build:es2015modules && yarn build:copy-files && yarn build:umd:dev && yarn build:umd:prod",
    "deploy": "deploy-to-git",
    "semantic-release": "cross-env GH_TOKEN=__TOKEN__ semantic-release --no-ci",
    "commitmsg": "commitlint -e $GIT_PARAMS"
  },
  "config": {
    "deployToGit": {
      "repository": "git@github.com:DeepIntent/di-component-lib.git",
      "branch": "release",
      "folder": "build",
      "script": "yarn run build",
      "commit": "feat(auto-commit-bot): v $npm_package_version",
      "user": {
        "email": "abhishek@deepintent.com",
        "name": "abhishek199-dhn"
      }
    }
  },
  "release": {
    "branch": "release",
    "verifyConditions": [
      "@semantic-release/git"
    ],
    "getLastRelease": "@semantic-release/git",
    "publish": [
      {
        "path": "@semantic-release/npm",
        "npmPublish": false,
        "tarballDir": "dist"
      },
      {
        "path": "@semantic-release/git",
        "message": "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}",
        "assets": [
          "dist/**"
        ]
      }
    ]
  },
  "peerDependencies": {
    "bootstrap": "^4.0.0-beta.3",
     "react": "16.2.0",
      "react-dom": "16.2.0"
  },
  "devDependencies": {
    "@commitlint/cli": "^6.0.2",
    "@commitlint/config-conventional": "^6.0.2",
    "@semantic-release/git": "^2.0.2",
    "assets-webpack-plugin": "^3.5.1",
    "babel-cli": "^6.26.0",
    "babel-core": "^6.25.0",
    "babel-eslint": "8.2.1",
    "babel-jest": "22.1.0",
    "babel-loader": "^7.1.1",
    "babel-plugin-flow-runtime": "0.15.0",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-plugin-typecheck": "^3.9.0",
    "babel-polyfill": "^6.23.0",
    "babel-preset-env": "1.6.1",
    "babel-preset-flow": "^6.23.0",
    "babel-preset-react": "^6.24.1",
    "babel-preset-react-hmre": "^1.1.1",
    "babel-preset-stage-0": "^6.24.1",
    "babel-register": "^6.24.1",
    "babel-runtime": "^6.23.0",
    "bootstrap": "^4.0.0-beta.3",
    "browser-sync": "2.23.5",
    "browser-sync-webpack-plugin": "^1.2.0",
    "case-sensitive-paths-webpack-plugin": "^2.1.1",
    "colors": "^1.1.2",
    "compression-webpack-plugin": "^1.0.1",
    "concurrently": "^3.5.0",
    "config": "1.29.2",
    "conventional-changelog-cli": "^1.3.5",
    "copy-webpack-plugin": "4.3.1",
    "cross-env": "5.1.3",
    "css-loader": "^0.28.4",
    "debug": "^3.1.0",
    "deploy-to-git": "^0.1.5",
    "dotenv": "^4.0.0",
    "enzyme": "3.3.0",
    "enzyme-adapter-react-16": "1.1.1",
    "eslint": "4.15.0",
    "eslint-config-airbnb": "16.1.0",
    "eslint-formatter-pretty": "^1.3.0",
    "eslint-friendly-formatter": "^3.0.0",
    "eslint-import-resolver-webpack": "^0.8.3",
    "eslint-plugin-babel": "^4.1.2",
    "eslint-plugin-compat": "2.1.0",
    "eslint-plugin-flowtype": "^2.39.1",
    "eslint-plugin-flowtype-errors": "3.3.7",
    "eslint-plugin-import": "2.8.0",
    "eslint-plugin-jest": "21.6.2",
    "eslint-plugin-jsx-a11y": "^6.0.2",
    "eslint-plugin-promise": "^3.6.0",
    "eslint-plugin-react": "7.5.1",
    "extract-text-webpack-plugin": "^3.0.0",
    "faker": "^4.1.0",
    "file-loader": "^1.1.5",
    "flow-bin": "0.63.1",
    "flow-copy-source": "^1.2.1",
    "flow-runtime": "0.16.0",
    "flow-typed": "2.2.3",
    "font-awesome": "^4.7.0",
    "fs-extra": "^5.0.0",
    "glob": "^7.1.2",
    "glob-all": "^3.1.0",
    "html-webpack-include-assets-plugin": "^1.0.2",
    "html-webpack-plugin": "^2.29.0",
    "http-server": "0.11.1",
    "husky": "^0.14.3",
    "identity-obj-proxy": "^3.0.0",
    "image-webpack-loader": "^3.3.1",
    "jest": "22.1.1",
    "jest-cli": "22.1.1",
    "jsdom": "11.5.1",
    "last-release-git": "^0.0.3",
    "node-sass": "4.7.2",
    "preload-webpack-plugin": "2.2.0",
    "purify-css": "1.2.6",
    "purifycss-webpack": "^0.7.0",
    "raf": "^3.3.2",
    "react-dev-utils": "5.0.0",
    "react-hot-loader": "3.1.3",
    "react-router": "^4.1.1",
    "react-router-dom": "^4.1.1",
    "react-syntax-highlighter": "^6.0.4",
    "react-test-renderer": "16.2.0",
    "rimraf": "^2.6.1",
    "sass-loader": "^6.0.6",
    "semantic-release": "^12.2.2",
    "shelljs": "0.8.0",
    "size-limit": "^0.14.0",
    "style-loader": "0.19.1",
    "sw-precache-webpack-plugin": "^0.11.4",
    "url-loader": "^0.6.2",
    "validate-commit-msg": "^2.14.0",
    "webpack": "3.10.0",
    "webpack-bundle-analyzer": "2.9.2",
    "webpack-dashboard": "1.0.2",
    "webpack-dev-server": "2.11.0",
    "webpack-manifest-plugin": "^1.3.2"
  },
  "dependencies": {
    "classnames": "^2.2.5",
    "daterangepicker": "^2.1.25",
    "history": "^4.7.2",
    "jquery": "^3.2.1",
    "jsonpath": "^1.0.0",
    "jss": "^9.5.1",
    "jss-camel-case": "^6.0.0",
    "jss-compose": "^5.0.0",
    "jss-default-unit": "^8.0.0",
    "jss-nested": "^6.0.1",
    "jss-preset-default": "4.0.1",
    "jss-props-sort": "^6.0.0",
    "jss-vendor-prefixer": "8.0.0",
    "lodash": "^4.17.4",
    "moment": "^2.19.3",
    "prop-types": "^15.6.0",
    "react-jss": "8.2.1"
  },
  "devEngines": {
    "node": ">=6.9.0",
    "npm": ">=3.10.7",
    "yarn": ">=1.2.1"
  },
  "engines": {
    "npm": ">=3.10.7",
    "node": ">=6.9.0"
  },
  "publishConfig": {
    "access": "restricted",
    "tag": "next"
  }
}

```
Commands executed
```
git checkout master
git pull origin master
yarn run deploy # created a build folder +  build the library  + pushes to release branch
yarn run semantic-release --dry-run
```
Gives error:- 

```
[Semantic release]: Load plugin verifyConditions from @semantic-release/git
[Semantic release]: Load plugin getLastRelease from @semantic-release/git
[Semantic release]: Load plugin analyzeCommits from @semantic-release/commit-analyzer
[Semantic release]: Load plugin generateNotes from @semantic-release/release-notes-generator
[Semantic release]: Load plugin publish from @semantic-release/npm
[Semantic release]: Load plugin publish from @semantic-release/git
[Semantic release]: This test run was triggered on the branch master, while semantic-release is configured to only publish from release, therefore a new version won’t be published.
✨  Done in 0.77s.

```
Semantic-release requires the checkout branch to be release but mostly these commands will be executed from the master or any other branch except release as release branch will not have these files and required node modules.

But even if I change the semantic-release branch to master and make a release from master it gets executed but throws EGITNOPERMISSION error. (just to test out the workflow).

I have set GH_TOKEN and have set up SSH keys.
```
$ cross-env GH_TOKEN=__TOKEN__ semantic-release --no-ci --dry-run --debug
  semantic-release:get-version-head Check if the current working directory is a git repository +0ms
  semantic-release:get-version-head cmd: 'git rev-parse --git-dir' +1ms
  semantic-release:get-version-head stdout: '.git' +1ms
  semantic-release:get-version-head stderr: '' +0ms
  semantic-release:get-version-head code: 0 +0ms
  semantic-release:config options values: [ 'branch',
  semantic-release:config   'repositoryUrl',
  semantic-release:config   'verifyConditions',
  semantic-release:config   'getLastRelease',
  semantic-release:config   'publish',
  semantic-release:config   'ci',
  semantic-release:config   'debug',
  semantic-release:config   'dryRun' ] +0ms
  semantic-release:config name: undefined +0ms
  semantic-release:config branch: 'master' +0ms
  semantic-release:config repositoryUrl: 'git+https://github.com/DeepIntent/di-component-lib.git' +0ms
  semantic-release:config analyzeCommits: undefined +0ms
  semantic-release:config generateNotes: undefined +0ms
  semantic-release:config verifyConditions: [ '@semantic-release/git' ] +0ms
  semantic-release:config verifyRelease: undefined +1ms
  semantic-release:config publish: [ { path: '@semantic-release/npm',
  semantic-release:config     npmPublish: false,
  semantic-release:config     tarballDir: 'dist' },
  semantic-release:config   { path: '@semantic-release/git',
  semantic-release:config     message: 'chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}',
  semantic-release:config     assets: [ 'dist/**' ] }
[Semantic release]: Load plugin verifyConditions from @semantic-release/git
[Semantic release]: Load plugin getLastRelease from @semantic-release/git
[Semantic release]: Load plugin analyzeCommits from @semantic-release/commit-analyzer
[Semantic release]: Load plugin generateNotes from @semantic-release/release-notes-generator
[Semantic release]: Load plugin publish from @semantic-release/npm
[Semantic release]: Load plugin publish from @semantic-release/git
[Semantic release]: Run automated release from branch master
[Semantic release]: Call plugin verify-conditions
[Semantic release]: Verify authentication for repository git+https://github.com/DeepIntent/di-component-lib.git
Password for 'https://__TOKEN__@github.com': 
[Semantic release]: EGITNOPERMISSION The git credentials doesn't allow to push on the branch master of git+https://github.com/DeepIntent/di-component-lib.git.
```

I have tried re-generating GH_TOKEN but no luck. Can the above flow be achieved using semantic-release? If you have any other better way of doing it please let me know.

**Comment by pvdlg** [comment]
What you try to achieve with a `master` branch and a release branch cannot be achieve as of now. semantic-release analyze the commit present on the current branch to make the release.
So you need both the code to release and the commits that created it, to be on the same branch.

What you can do is use semantic-release to make releases on master, and use the [exec plugin](https://github.com/semantic-release/exec) as an additional `publish` step to use whatever solution to push to another branch.

For example [here](https://github.com/pvdlg/uprogress/blob/master/package.json#L147) I use `gh-pages` to publish the generated docs to the `gh-pages` branch.

Regarding the `EGITNOPERMISSION` error the `GH_TOKEN` environment variable should be a GitHub personal token. You should probably not use `cross-env GH_TOKEN=__TOKEN__ semantic-release` as you would have your token in clear in your `package.json`. Even if your project is private, it doesn't seems really secure.

Did you make sure the token has push access to your repo? As it's a probably a private repo, you will need to check "Full control of private repositories".

**Comment by gr2m** [comment]
fyi I rephrased the title to better represent what you try to achieve, please correct me if I got it wrong. The original sounded like you just wanted to disable the publish to npm, but I think the actual challenge is the custom deploy to a branch

**Comment by abhishek199-dhn** [comment]
> Regarding the EGITNOPERMISSION error the GH_TOKEN environment variable should be a GitHub personal token. You should probably not use cross-env GH_TOKEN=__TOKEN__ semantic-release as you would have your token in clear in your package.json. Even if your project is private, it doesn't seems really secure.

Noted!

>Did you make sure the token has push access to your repo? As it's a probably a private repo, you will need to check "Full control of private repositories".

yeah, it has the required access(Full control of private repositories) and I have tried setting up SSH keys too.
Magically the same token worked with the semantic release once(it didn't ask any password at that time) and I was able to see the change logs and commits but after that, I was not able to make it work. 
And that password which it asks during authentication is also not consistent.
sometimes it asks for it 
> Password for 'https://__TOKEN__@github.com': 

and sometimes it directly shows 
> [Semantic release]: EGITNOPERMISSION The git credentials doesn't allow to push on the branch master of git+https://github.com/DeepIntent/di-component-lib.git.

**Comment by pvdlg** [comment]
In order to check the permission to the repo we are using `git push --dry-run https://<GH_TOKEN>@github.com/<owner>/<repo>.git HEAD:master`.

Can you try to run that on your CI to see if you get an error? You have to replace <GH_TOKEN>, <owner> and <repo> in the command.

**Comment by abhishek199-dhn** [comment]
@pvdlg 

>In order to check the permission to the repo we are using git push --dry-run https://<GH_TOKEN>@github.com/<owner>/<repo>.git HEAD:master.
Can you try to run that on your CI to see if you get an error? You have to replace <GH_TOKEN>, and in the command?

The push command works as expected and gives no error.

>Also what is the Git URL configured in your package.json in the repository property?
```
"repository": {
    "type": "git",
    "url": "https://github.com/DeepIntent/di-component-lib.git"
  }
```

**Comment by pvdlg** [comment]
If `git push --dry-run https://<GH_TOKEN>@github.com//.git HEAD:master` works when you run it directly in the CI there is no reason it doesn't work when it's ran by semantic-release. So there must be a difference in the configuration you reported in this issue and your actual configuration.

You can try with semantic-release version 12.4.1 or 13.1.0 that would give more informations in the logs.

**Comment by abhishek199-dhn** [comment]
okay, I will a try to the new version and verify it.

**Comment by huchenme** [comment]
same here

```
+ git push --dry-run origin HEAD:master
Everything up-to-date
[Pipeline] sh
[BUILD] Running shell script
+ npx semantic-release
[Semantic release]: Load plugin verifyConditions from @semantic-release/changelog
[Semantic release]: Load plugin verifyConditions from @semantic-release/git
[Semantic release]: Load plugin analyzeCommits from @semantic-release/commit-analyzer
[Semantic release]: Load plugin generateNotes from @semantic-release/release-notes-generator
[Semantic release]: Load plugin publish from @semantic-release/changelog
[Semantic release]: Load plugin publish from @semantic-release/npm
[Semantic release]: Load plugin publish from @semantic-release/git
$ ssh-agent -k
unset SSH_AUTH_SOCK;
unset SSH_AGENT_PID;
echo Agent pid 32731 killed;
[ssh-agent] Stopped.
[Semantic release]: EGITNOPERMISSION The git credentials doesn't allow to push on the branch master.
```

Is it related to `execa`?

**Comment by pvdlg** [comment]
@huchenme The command that is executed is `git push --dry-run https://<GH_TOKEN>@github.com//.git HEAD:master`, not `git push --dry-run origin HEAD:master`.
It's most likely a problem with your token/credentials or the configuration of the `repositoryUrl`.

**Comment by pvdlg** [comment]
It seems the problem happens when you have multiple sub-path in the repository URL.
For example `https://gitlab.com/owner/repo.git` works while `https://gitlab.com/group/owner/repo.git` doesn't.

This will be solved once IonicaBizau/git-url-parse#53 get released.

**Comment by pvdlg** [comment]
@huchenme can you confirm what is your repository URL? To be sure it will be solved by IonicaBizau/git-url-parse#53.

@abhishek199-dhn as you are using a GitHub repo I don't think it's related to IonicaBizau/git-url-parse#53. Can you confirm if your problem is solved? Did you try with the latest `13.x.x`?

Thanks

**Comment by pvdlg** [comment]
That should be fixed in `v13.1.4`. @huchenme, @abhishek199-dhn can you confirm that works for you?
Thanks

**Comment by abhishek199-dhn** [comment]
@pvdlg 
```v13.1.4.``` works for me finally, Thanks.
But I still stuck to make a release from master branch to release branch with the changelogs.
I'm using release branch as npm registry to pull the npm package from git using tags. So Basically I'm pushing all the build code to release branch such that if someone pulls the lib package they get the build code instead of the source code.

>What you can do is use semantic-release to make releases on the master, and use the exec plugin as an additional publish step to use whatever solution to push to another branch.

In this case, I have to make a git release from the master branch and then again make a git release from release branch.

**Comment by pvdlg** [comment]
@abhishek199-dhn I read your comments in this issue several times and I fail to understand what you are trying to achieve and what's the purpose.

`semantic-release` runs on your CI which trigger a job when a commit is pushed on a branch. `semantic-release` needs to be run by the job triggered on that branch because it needs to analyze the commits made there since the last release.

You can use the `@semantic-release/git` plugin to push artifacts to your repo on the branch that triggered the CI job. This is what I would recommend to do. 

You can also use the `@semantic-release/exec` plugin to run a command that do whatever you'd like.

If you'd like to propose a new feature you can use the [feature request template](https://github.com/semantic-release/semantic-release/issues/new?template=feature-request.md).
If you'd like to propose a new plugin you can use the [plugin request template](https://github.com/semantic-release/semantic-release/issues/new?template=plugin-request.md).

In both case you would have to explain in details what the feature/plugin is and why it would be beneficial. In both case it would have to provide benefits for for commonly adopted patterns or release workflow.

**Comment by pvdlg** [comment]
@abhishek199-dhn I'm going to go ahead and close this issue as it seems stale.

Feel free to reopen a new feature request including and explanation of the benefits it would bring.
Keep in mind that semantic-release needs to analyze the commits done since the last release to determine the next version and make the release, so it has to run on a branch that include those commits.
