### ISSUE TITLE
Proposal: Success/Fail notification

### ISSUE THREAD

**Issue by pvdlg** [semantic-release/semantic-release#627]
This is a proposal to add the `success` and `fail` plugin hook to alert users when a release is successful or failed.

Benefits:
- Alert the user when a problem happen during the release. Currently the only way for user to know a problem happened is to rely on the CI job failure notifications.
- Allow to give more detailed information to users when a release fails. Currently users have to look at the CI logs to figure out what happened.
- Allow to deliver notifications for successful releases that contains information about all the `publish` plugin that ran, therefore allowing to send a message that contains the link to the github release, the npm package etc...

**Add a return value to `publish` hook**

The `publish` hooks could return an object with information related to the release that the plugin did, such as an URL, or additional information.

**`succes` hook**
Accept an Array of plugins (similar to the `publish` hook). Each one would be called by the core, when the release is successful an would be passed the same information as the `publish` hook + an Array of releases. Each release in the Array would be the return value of the `publish` hooks + some additional info such as the plugin that did the release.

**`fail` hook**
Would be called if the release fails and would be passed an Array of SemanticReleaseErrors.

**Add `detailedMessage` to `@sematnic-release/error`**
When throwing a `SemanticReleaseError` the core and plugins would add the `detailedMessage` that would contains:
- A detailed and user friendly explanation of the problem
- Possible solutions
- Links to documentation and help

This detailed error could be used by the `fail` hook to generate a user friendly and helpful message.

**GitHub plugin `fail` hook**
Open an issue with the detailedMessage of each error that happened

**GitHub plugin `success` hook**
Add a comment on each issue/PR that was closed by the release, with a link to each release (on npm, GitHub, Atom etc...).
Add a list of links to the GitHub releases (i.e the npm package or Atom package link, or info about the compiled files pushed to the repo by the `git` plugin)

**Gitter plugin with `fail` and `success` hook**
Post a message on a Gitter chat with information about the releases.

**Slack plugin with `fail` and `success` hook**
Post a message on a Slack chat with information about the releases.

**Comment by gr2m** [comment]
This all sounds great to me! For finding PRs/issues to comment on to notify contributors about the release of their changes, see the implementation of https://github.com/release-notifier/release-notifier

**Comment by pvdlg** [comment]
> This all sounds great to me! For finding PRs/issues to comment on to notify contributors about the release of their changes, see the implementation of https://github.com/release-notifier/release-notifier

Yep I checked it out! Actually I have something a bit more complete in mind:
- Do a GitHub issue search for each commit in the release to retrieve each associated PR
- Parse each PR found to find issues references (like `Fix #XX` or `Close #XX`)
- Add a comment to each issues closed by one of the PR found

I would also parse the commit message content to find issues closed by the commit directly.

The idea is similar though, it would rely on `context.github.search.issues({q: commit.sha})`, just dig a bit deeper.

That would be useful as a lot of folks open an issue or follow one, but don't necessarly follow the associated PR.

**Comment by gr2m** [comment]
yeah I think that is all within scope for the release-notifier app, too. I talked with @zeke, we can extract the logic into a reusable library that could be used by both, the release notifier and a semantic-release notifier plugin

**Comment by pvdlg** [comment]
Ok. I have the code for parsing issues (that detect `Fix #XX`) ready to be released soon.
That would work with GitHub, GitLab and BitBucket and would recognize all the different `Fix` patterns (`Fix`, `Fixes`, `Closes` etc..) plus the referenced without a keyword, plus the users mentions.

I found several library doing that but they are either unmaintained or cannot implement features mentioned above.

What would be left to do would be to make the calls to the logic of GitHub API call => Parse => GitHub API call etc...

**Comment by gr2m** [comment]
let me know if I can help with using the GitHub API :)
