### ISSUE TITLE
Doesn't fail gracefully on 404 response from registry

### ISSUE THREAD

**Issue by mattmazzola** [semantic-release/semantic-release#632]
## Current behavior

I have semantic-release configured to a custom registry and the `get-last-release` plugin tries to get the last version published in order to know what the next version should be; however, this registry returns different body than the official npm registry (text rather than empty json) causing semantic-release to fail at parsing the body.

Example:

**Custom registry returns 404 with text/html**
Request: `GET http://bbnpm.azurewebsites.net/non-existent-package`
Response: 404 The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.`

**Official registry returns 404 with application/json**
Request: `GET https://registry.npmjs.org/non-existent-package`
Response: `{}`

This could be blamed on the custom registry that they don't return same response as official thus breaking API; however, neither of them respect the `Accept` header so it's probably not spec'd. 
Either way, semantic release should have enough information to determine there is no last version because of the return code 404.  It also could look at the `Content-Type` header to know how/when to parse the body.

The custom registry looks like: http://www.verdaccio.org/ but I'm not very familiar with that.

## Expected behavior

If the return code is 404 it should assume the package doesn't exist and no try to parse the body.

## Environment

- **semantic-release** version: "semantic-release": "^12.4.1",
- CI environment: Travis
- Plugins used: none
- **semantic-release** configuration: https://github.com/mattmazzola/library-starter-test
- CI logs: https://travis-ci.org/mattmazzola/library-starter-test/builds/335824651#L2830

**Comment by pvdlg** [comment]
Yes this is one of the numerous problems we had trying to integrate with various npm registries. As there is no specifications, all "npm compatible" registries have different behavior.

For this reason and others we don't use the npm registry anymore to retrieve the last release. We now rely on Git tags. See semantic-release/semantic-release#613.

This PR has been released in the `@next` dist-tag. You can use it with semantic-release `13.0.0`.

**Comment by pvdlg** [comment]
I'm going to go ahead and close this issue as the `getLastRelease` plugin doesn't exist anymore in `semantic-release@13.0.0` so the problematic code is not there anymore.

I recommend to upgrade to `semantic-release@13.0.0` which available on the `@next` dist-tag.
