### ISSUE TITLE
[Semantic release]: There is no previous release, the next release version is 1.0.0

### ISSUE THREAD

**Issue by negamaxi** [semantic-release/semantic-release#633]
## Current behavior
Trying to make my first patch release, but get `[Semantic release]: There is no previous release, the next release version is 1.0.0` and next to it `release already exists` error from GitHub. 1.0.0 release already exists and was published with semantic-release 6 hours ago.

## Expected behavior
It seems like https://github.com/semantic-release/semantic-release/commit/d0b304e240002ed22f1d30b866260f6582518938 makes semantic-release to use git tags for next release calculation, therefore I was expecting a new patch release.

## Environment

- **semantic-release** version: latest with npx
- CI environment:  Travis
- Plugins used: 
- **semantic-release** configuration: 
```json
{
  "verifyConditions": "@semantic-release/github",
  "publish": [
    {
      "path": "@semantic-release/exec",
      "cmd": "sh pre-build.sh ${nextRelease.version} && yarn build --linux --win --mac -p never && sh post-build.sh"
    },
    {
      "path": "@semantic-release/github",
      "assets": "dist/*"
    }
  ]
}
```
- CI logs: 
https://travis-ci.org/pathephone/pathephone-desktop/builds/336226977#L2143

**Comment by pvdlg** [comment]
The commit you are referencing has been released in semantic-release 13.0.0 on the `next` dist-tag.
As you use semantic-release with `npx semantic-release` you are using the last version on the `lastest` dist-tag which is 12.x.x.

That meant the last release is determined based on the npm registry. You can see that in the logs:
> [Semantic release]: No version found of package pathephone-desktop found on https://registry.npmjs.org/
> [Semantic release]: No previous release found, retrieving all commits

So when this CI job ran, you were using the default npm plugin for the `getLastRelease` plugin. As there is no version of your module on npm, semantic-release determined it the very first release and included all commits and released version 1.0.0.

If you don't want to release on the npm registry, you can look at this [FAQ](https://semantic-release.gitbooks.io/semantic-release/content/docs/support/FAQ.html#can-i-skip-the-release-to-the-npm-registry).

If you want to use Git tags for retrieving the last version (you should if you don't publish on npm), you need to configure the `@sematnic-release/git` plugin for `getLastRelease`. Or you can use `semantic-release@13` that will do that automatically.

**Comment by negamaxi** [comment]
@pvdlg Nice! Thanks!

**Comment by pvdlg** [comment]
Don't hesitate to ping me on the [Gitter chat](https://gitter.im/semantic-release/semantic-release) if you need help to setup your project, or if you have questions.
