### ISSUE TITLE
Can not push to npm

### ISSUE THREAD

**Issue by lapanoid** [semantic-release/semantic-release#64]
npm ERR! Linux 3.13.0-40-generic
npm ERR! argv "/home/travis/.nvm/versions/io.js/v3.1.0/bin/iojs" "/home/travis/.nvm/versions/io.js/v3.1.0/bin/npm" "publish"
npm ERR! node v3.1.0
npm ERR! npm  v2.14.0
npm ERR! code ENEEDAUTH
npm ERR! need auth auth required for publishing
npm ERR! need auth You need to authorize this machine using `npm adduser`
npm ERR! Please include the following file with any support request:
npm ERR!     /home/travis/build/lapanoid/presentation/npm-debug.log
npm ERR! Linux 3.13.0-40-generic
npm ERR! argv "/home/travis/.nvm/versions/io.js/v3.1.0/bin/iojs" "/home/travis/.nvm/versions/io.js/v3.1.0/bin/npm" "run" "semantic-release"
npm ERR! node v3.1.0
npm ERR! npm  v2.14.0
npm ERR! code ELIFECYCLE
npm ERR! olo-proj@ semantic-release: `semantic-release pre && npm publish && semantic-release post`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the olo-proj@ semantic-release script 'semantic-release pre && npm publish && semantic-release post'.
npm ERR! This is most likely a problem with the olo-proj package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     semantic-release pre && npm publish && semantic-release post
npm ERR! You can get their info via:
npm ERR!     npm owner ls olo-proj
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /home/travis/build/lapanoid/presentation/npm-debug.log

**Comment by gr2m** [comment]
@lapanoid did you run `npm publish` locally on your machine? Or is that an error log from Travis? If it's the latter, did you use `semantic-release-cli setup` as described here?
https://github.com/semantic-release/semantic-release#setup

**Comment by lapanoid** [comment]
This is travis https://travis-ci.org/lapanoid/presentation, I did semantic-release-cli setup without any errors

**Comment by boennemann** [comment]
@lapanoid Thanks for reporting this. Having a look at your `package.json` showed that you're running `semantic-release@3.x`, which isn't compatible with the way the cli sets up your tokens and auth. This is why the cli automatically installs the 4.x, or "next" branch of `semantic-release`.

Updating `semantic-release` to `^4.1.1` in you package.json should immediately fix this.

Please report back :)

Best,
Stephan

**Comment by boennemann** [comment]
Just to document this here: 4.x is now on the "latest" dist-tag, which means this should no longer happen in the future :)

**Comment by lapanoid** [comment]
@boennemann Everything works great, thanks!

**Comment by boennemann** [comment]
:+1: Thanks for letting us know :)
