### ISSUE TITLE
EGITNOPERMISSION The git credentials doesn't allow to push on the branch master

### ISSUE THREAD

**Issue by R0oma1n** [semantic-release/semantic-release#643]
Hello, 

I have that issue when I tried semantic-release in my gitlab pipeline.
I use docker in my pipeline.
It's ok when I try it in local. 

Here is my issue : 

Running with gitlab-runner 10.4.0 (857480b6)
  on gitlab-runner1 (46d5eb2d)
Using Docker executor with image node:8.9.4-stretch ...
Using docker image sha256:c50c3419f0550e99b775c049e3f31a9ebfa99d6850ad7379de88d5638d5a6f47 for predefined container...
Pulling docker image node:8.9.4-stretch ...
Using docker image node:8.9.4-stretch ID=sha256:a264e6327bde43a91637d5b980c0fdc707c8593f6d6caecc4c54b5f621164f39 for build container...
Running on runner-46d5eb2d-project-2-concurrent-0 via db6d21c67388...
Fetching changes...
Removing node_modules/
Removing yarn.lock
HEAD is now at 5e77a70 fix(add): handle decimal numbers addition
From https://gitlab.integration.*******/*******/release-test
   5e77a70..1fafd59  master     -> origin/master
Checking out 1fafd599 as master...
Skipping Git submodules setup
$ echo $GITLAB_TOKEN
LL7gL*****************
$ export GIT_USERNAME=**********
$ export GIT_EMAIL=**********

$ yarn install
yarn install v1.3.2
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
Done in 17.93s.
$ yarn release --debug
yarn run v1.3.2
$ semantic-release --debug
2018-02-06T15:20:01.284Z semantic-release:config options values: [ 'branch',
  'repositoryUrl',
  'tagFormat',
  'verifyConditions',
  'getLastRelease',
  'createGitTag',
  'publish',
  'gitlabUrl',
  'ci',
  'debug' ]
2018-02-06T15:20:01.285Z semantic-release:config name: undefined
2018-02-06T15:20:01.285Z semantic-release:config branch: 'master'
2018-02-06T15:20:01.285Z semantic-release:config repositoryUrl: 'https://gitlab-ci-token:[secure]@gitlab.**********/********/release-test.git'
2018-02-06T15:20:01.285Z semantic-release:config analyzeCommits: undefined
2018-02-06T15:20:01.285Z semantic-release:config generateNotes: undefined
2018-02-06T15:20:01.285Z semantic-release:config verifyConditions: [ '@semantic-release/gitlab', '@semantic-release/git' ]
2018-02-06T15:20:01.286Z semantic-release:config verifyRelease: undefined
2018-02-06T15:20:01.286Z semantic-release:config publish: [ { path: '@semantic-release/npm', npmPublish: false },
  '@semantic-release/git',
  '@semantic-release/changelog',
  '@semantic-release/gitlab' ]
[Semantic release]: Load plugin verifyConditions from @semantic-release/gitlab
[Semantic release]: Load plugin verifyConditions from @semantic-release/git
[Semantic release]: Load plugin analyzeCommits from @semantic-release/commit-analyzer
[Semantic release]: Load plugin generateNotes from @semantic-release/release-notes-generator
[Semantic release]: Load plugin publish from @semantic-release/npm
[Semantic release]: Load plugin publish from @semantic-release/git
[Semantic release]: Load plugin publish from @semantic-release/changelog
[Semantic release]: Load plugin publish from @semantic-release/gitlab
[Semantic release]: EGITNOPERMISSION The git credentials doesn't allow to push on the branch master.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: Job failed: exit code 1

**Comment by pvdlg** [comment]
Is your repository publicly accessible? Do you have a link? That would help with the troubleshooting.

Can you provide the following in from your `package.json`:
- The `release`  property content
- The `repository` property content

**Comment by pvdlg** [comment]
Also can you try to manually run the following command in your ci: `git push --dry-run https://gitlab-ci-token:$GITLAB_TOKEN@<server>/<owner>/release-test.git HEAD:master`.
You have to replace `<server>` and `<owner>` with the value of your repo URL. For some reason in your logs its replaced by ******.

**Comment by trollr** [comment]
Have the same issue for https://<user>:<password>@... authentication with bitbucket

**Comment by pvdlg** [comment]
It seems the problem happens when you have multiple sub-path in the repository URL.
For example `https://gitlab.com/owner/repo.git` works while `https://gitlab.com/group/owner/repo.git` doesn't.

This will be solved once IonicaBizau/git-url-parse#53 get released.

**Comment by R0oma1n** [comment]
git push --dry-run https://gitlab-ci-token:$GITLAB_TOKEN@<server>/<owner>/release-test.git HEAD:master works ! 

The system worked after using the command, I do not have the problem anymore and I don't know why
Thanks for your help
