### ISSUE TITLE
v13.x on npm public registry

### ISSUE THREAD

**Issue by bhavin137** [semantic-release/semantic-release#644]
I have a custom plugin for checking last release at our organisation, and was trying to update it according to the breaking changes in v13. But npm registry still seems to be on v12.4.1 (as of this writing), and since we avoid installing npm packages from git as a best practice, I was wondering when the latest release is going to be pushed to the npm registry

Thanks

PS: Thank you for the great tool! It comes in very useful for our agile workflow :)

**Comment by gr2m** [comment]
it’s published using the `@next` dist-tag. You can see it with

```
$ npm info semantic-release@next version
13.1.3
```

you can instal it with `npm install semantic-release@next`

You can find out more about dist-tags at https://docs.npmjs.com/cli/dist-tag

**Comment by pvdlg** [comment]
You can also see on the README which version is available on which dist-tag:
![2018-02-07_10-08-34](https://user-images.githubusercontent.com/3250552/35923687-f1d86adc-0bee-11e8-8b08-c796bfc9e3d1.png)
