### ISSUE TITLE
semantic-release --no-ci logs [secure]ecure][[secure]9[secu...

### ISSUE THREAD

**Issue by gr2m** [semantic-release/semantic-release#646]
## Current behavior

```
$ ./node_modules/.bin/semantic-release --no-ci
[secure]ecure][[secure]9[secure]0[secure]m[secure][[secure]S[secure]e[secure]m[secure]a[secure]n[secure]t[secure]i[secure]c[secure] [secure]r[secure]e[secure]l[secure]e[secure]a[secure]s[secure]e[secure]][secure]:[secur....
```

## Expected behavior

should only mask sensitive tokens

## Environment

- **semantic-release** version: 13.1.3, 12.4.1
- Plugins used: none
- **semantic-release** configuration: 
  ```json
  "release": {
    "publish": [
      "@semantic-release/npm",
      {
        "path": "@semantic-release/github",
        "assets": [
          "dist/*"
        ]
      }
    ]
  }
  ```
- CI logs: does not apply

**Comment by gr2m** [comment]
problem is that the regex resulting from this line

https://github.com/semantic-release/semantic-release/blob/cbf57851fbf84502bf408a19b8008d226432edf7/lib/hide-sensitive.js#L4

ends up with a value like this `/123reducted|||456reducted/g`. I’ll look into it

**Comment by pvdlg** [comment]
I had the same issue and I remember I fixed it by adding `.filter(Boolean)` as well. No idea why it's not there.

So yeah looks to be the right fix!

**Comment by gr2m** [comment]
Great. If anyone wants to help out, please go ahead :) Happy to have someone new submit this pull request. I can do it otherwise on Friday
