### ISSUE TITLE
Need help with --dry-run option.

### ISSUE THREAD

**Issue by DianaSuvorova** [semantic-release/semantic-release#655]
I am trying to run semantic-release locally and dry

`npm run semantic-release --dry-run`

```
 eslint-plugin-react-redux@0.0.0-development semantic-release /Users/diana.suvorova/Dev/eslint-plugin-react-redux
> semantic-release

[Semantic release]: Load plugin verifyConditions from @semantic-release/npm
[Semantic release]: Load plugin verifyConditions from @semantic-release/github
[Semantic release]: Load plugin verifyConditions from @semantic-release/condition-travis
[Semantic release]: Load plugin getLastRelease from @semantic-release/npm
[Semantic release]: Load plugin analyzeCommits from @semantic-release/commit-analyzer
[Semantic release]: Load plugin generateNotes from @semantic-release/release-notes-generator
[Semantic release]: Load plugin publish from @semantic-release/npm
[Semantic release]: Load plugin publish from @semantic-release/github
[Semantic release]: Run automated release from branch master
[Semantic release]: Call plugin verify-conditions
[Semantic release]: Verify authentication for registry https://registry.npmjs.org/./
[Semantic release]: Verify Github authentication
[Semantic release]: ENOTRAVIS semantic-release didn’t run on Travis CI and therefore a new version won’t be published.
You can customize this behavior using "verifyConditions" plugins: git.io/sr-plugins
```

It doesn't seem like it runs it dry. Any suggestions?

`node -v: v8.9.1`
`npm view semantic-release version: 12.4.1`

Thanks!

**Comment by pvdlg** [comment]
It seems you are using the `@semantic-release/condition-travis` plugin which is deprecated. You should remove it from your configuration.

**Comment by DianaSuvorova** [comment]
OK, what is a correct way of deleting a plugin? and do I need to install anything instead?

**Comment by pvdlg** [comment]
Can you provide you semantic-release configuration?

**Comment by DianaSuvorova** [comment]
I wish I knew where to find them. It was generated by semnatic-release-cli. `npm run semantic-release` seems to magically know what to do.

**Comment by DianaSuvorova** [comment]
the repo is https://github.com/DianaSuvorova/eslint-plugin-react-redux

**Comment by pvdlg** [comment]
It would be a `release` property in your `package.json` or in a `releaserc` file. If you just set up semantic-release with `semantic-release-cli` then there is no configuration set and the default one is used.

The `ENOTRAVIS` comes from the  `@semantic-release/condition-travis` which used to used by default. It's used anymore since version 12.0.0.

So I guess you are using an older version. I see from your `package.json` that you are using version `11.0.2`.

I was confused because you mention version `12.4.1` in this issue.

You should upgrade to version `12.4.1`

**Comment by DianaSuvorova** [comment]
Got it, yes, thanks for the explanation. removing `./node_modules/@semantic-release` + `npm install` fixed the issue.

Thanks a bunch!
