### ISSUE TITLE
Support Q: One off `npm publish`

### ISSUE THREAD

**Issue by DianaSuvorova** [semantic-release/semantic-release#656]
Is there a way for me to do a `npm publish` for an arbitrary version.
I understand that `normal` way is to update `package.json` and run `npm publish`. 
Although I see that semantic-release is able to publish stuff to npm without updating package.json. Version stays at `0.0.0-development`. Would I confuse semantic-release if I update it to something else?

I wonder what is a recommend way for such one-off manual publish.

Thanks!

**Comment by pvdlg** [comment]
As mentioned in our [contributing guidelines](https://github.com/semantic-release/semantic-release/blob/caribou/CONTRIBUTING.md#using-the-issue-tracker):
> The issue tracker is the channel for [bug reports](#bug-report), [features requests](#feature-request) and [submitting pull requests](#submitting-a-pull-request) only. Please use the [Support](docs/support/README.md) and [Get help](README.md#get-help) sections for support, troubleshooting and questions.

Those two FAQ seems to answer your question:
- [Why is the package.json’s version not updated in my repository?](https://github.com/semantic-release/semantic-release/blob/caribou/docs/support/FAQ.md#why-is-the-packagejsons-version-not-updated-in-my-repository)
- [Can I manually trigger the release of a specific version?](https://github.com/semantic-release/semantic-release/blob/caribou/docs/support/FAQ.md#can-i-manually-trigger-the-release-of-a-specific-version)

I'm closing the issue as it's a support question. If the 2 FAQs linked above doesn't help, I invite you to use the proper support channels for further support questions.

**Comment by pvdlg** [comment]
> Would I confuse semantic-release if I update it to something else?

You can do release manually as long as a tag is created. semantic-release determine the last version released with Git tags to analyze commits between then and now. 
If you do a manual release, just create the git tag with a proper semver version as a name.
