### ISSUE TITLE
NPM Package Released but Release Notes & Code tagging not done on GITHUB REPO

### ISSUE THREAD

**Issue by bjavaid** [semantic-release/semantic-release#658]
## Current behavior

When I run the code locally then no error is generated and package shows the release notes properly.

Following error generated on travis during semantic release

`[Semantic release]: An error occurred while running semantic-release: { HttpError: {"message":"Object does not exist","documentation_url":"https://developer.github.com/v3/git/refs/#create-a-reference"}
    at IncomingMessage.response.on (/home/travis/build/BlueEastCode/bluerain-os/node_modules/@octokit/rest/lib/request/request.js:73:18)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1055:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  name: 'HttpError',
  code: 422,
  status: undefined,
  headers: 
   { server: 'GitHub.com',
     date: 'Sun, 11 Feb 2018 08:26:41 GMT',
     'content-type': 'application/json; charset=utf-8',
     'content-length': '118',
     connection: 'close',
     status: '422 Unprocessable Entity',
     'x-ratelimit-limit': '5000',
     'x-ratelimit-remaining': '4963',
     'x-ratelimit-reset': '1518339769',
     'x-oauth-scopes': 'repo, read:org, user:email, repo_deployment, repo:status, write:repo_hook',
     'x-accepted-oauth-scopes': '',
     'x-github-media-type': 'github.v3; format=json',
     'access-control-expose-headers': 'ETag, Link, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval',
     'access-control-allow-origin': '*',
     'content-security-policy': 'default-src \'none\'',
     'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
     'x-content-type-options': 'nosniff',
     'x-frame-options': 'deny',
     'x-xss-protection': '1; mode=block',
     'x-runtime-rack': '0.044387',
     'x-github-request-id': 'CD26:23E3C:15518A7:256D51C:5A7FFE41' } }`

## Expected behavior

It should tag the code on github and publish the release notes. I doubled checked my GH_TOKEN value; delete the existing one added again on travis. The same GH_TOKEN and NPM _TOKEN works without any issue locally.

## Environment

- **semantic-release** version: 12.4.1
- CI environment: Travis
- Plugins used: Default
- **semantic-release** configuration: https://github.com/BlueEastCode/bluerain-os/blob/master/package.json#L43
- CI logs: https://travis-ci.org/BlueEastCode/bluerain-os/jobs/340069126

**Comment by pvdlg** [comment]
I wonder if it's one of these cases in which the GitHub API respond with random error code described in #607.

Is this issue happens systematically? Or is it just once in a while?

The error happens when the GitHub plugin try to create the Git tag. This has been removed in semantic-release `13.0.0` which is published in the `@next` dist-tag. The git tag is now created with the `git` CLI.

Moving to `^13.0.0` would improve the situation I think

**Comment by bjavaid** [comment]
This may be due the number of APIs requests per second. Somehow this is working only one of our repositories on github and failing for all remaining repositories.

Previously I was getting this issue with version 8.0.0 so I upgraded the version to 12.4.1 but issue still exist (as you mentioned in the plugin:github).

Let me try with the next release 13.0.0 and I will post the result here.

**Comment by pvdlg** [comment]
> The CI pipeline triggered after applying the tag on code produce the following debug log which is showing failing of github plugin.

The logs you provide doesn't include any failure. It just says that semantic-release has nothing to do on a job triggered by a tag, which is expected. It exists before running any plugin.

Also how I can generate the release notes of my previous releases?

You can try running https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog locally.

**Comment by jourdain** [comment]
I am running into a similar issue from time to time. But on my end, it is `npm` who time out but still produce the release. And then, because `npm` supposedly failed, semantic-release does not finish its job on github. I there anyway to generate the tag/change-log after the fact? Even manually?

[NPM release 6.3.8](https://www.npmjs.com/package/vtk.js)
[Github releases (missing 6.3.8 and a couple others](https://github.com/Kitware/vtk-js/releases)

Thanks for such a great tool!

```
[Semantic release]: The release type for the commit is patch
[Semantic release]: Analysis of 10 commits complete: patch release
[Semantic release]: The next release version is 6.3.8
[Semantic release]: Call plugin verify-release
[Semantic release]: Call plugin generateNotes
[Semantic release]: Call plugin publish
[Semantic release]: Wrote version 6.3.8 to package.json
[Semantic release]: Publishing version 6.3.8 to npm registry
[Semantic release]: An error occurred while running semantic-release: { Error: Command failed: npm publish ./. --registry https://registry.npmjs.org/
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! publish Failed PUT 504
npm ERR! Unexpected token < in JSON at position 0
npm ERR! <html><body><h1>504 Gateway Time-out</h1>
npm ERR! The server didn't respond in time.
npm ERR! </body></html>
npm ERR! 
npm ERR! 
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2018-03-07T00_29_15_789Z-debug.log
    at Promise.all.then.arr (/home/travis/build/Kitware/vtk-js/node_modules/execa/index.js:236:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  code: 1,
  killed: false,
  stdout: '',
  stderr: 'npm ERR! registry error parsing json\nnpm ERR! registry error parsing json\nnpm ERR! registry error parsing json\nnpm ERR! publish Failed PUT 504\nnpm ERR! Unexpected token < in JSON at position 0\nnpm ERR! <html><body><h1>504 Gateway Time-out</h1>\nnpm ERR! The server didn\'t respond in time.\nnpm ERR! </body></html>\nnpm ERR! \nnpm ERR! \n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /home/travis/.npm/_logs/2018-03-07T00_29_15_789Z-debug.log\n',
  failed: true,
  signal: null,
  cmd: 'npm publish ./. --registry https://registry.npmjs.org/',
  timedOut: false }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vtk.js@0.0.0-semantically-release semantic-release: `semantic-release`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vtk.js@0.0.0-semantically-release semantic-release script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2018-03-07T00_29_15_827Z-debug.log
```

**Comment by travi** [comment]
@jourdain looks like a case what i reported in https://github.com/semantic-release/npm/issues/54 rather than a github issue. i've only noticed it happen once, so i'm keeping my eye out for more cases but havent pursued very far yet.
