### ISSUE TITLE
Inclusion of default github implementation for new 'success' and 'failure' hooks may be a breaking change

### ISSUE THREAD

**Issue by smoorhouse11** [semantic-release/semantic-release#664]
If a user is not using any github plugin features in their project in semantic-release version 13.2, the release will suddenly fail when upgrading to 13.3. If the user doesn't have GitHub authentication configured for the project, semantic-release will fail with ENOGHTOKEN.

**Comment by pvdlg** [comment]
Yes you're right, I didn't think about this situation. We should change the last few releases to be major.

We need to make the following changes:
- 13.3.0 => 14.0.0
- 13.3.1 => 14.0.1
- 13.4.0 => 14.1.0

We would have to do the following step for each release to rename:
- Checkout the tag with `git checkout tags/v<old_version>`
- Push the new tag with `git tag <old_version> <new_version>` and `git push origin --tags`
- Set the version in `package.json`
- Publish on npm with `npm publish`
- Deprecate the wrong release on npm with `npm deprecate semantic-release@<old_version> "Replaced by release <new_version>"`
- Modify the GitHub release to reference the new tag
- Delete the old tag with `git push --delete origin <old_version>`

Then we need to add the breaking change description and migration guide to the `14.0.0` release.

Or for simplicity sake we can just rename 13.4.0 to 14.0.0 and just remove 13.3.0 and 13.3.1.

@gr2m does that sounds good to you?

**Comment by pvdlg** [comment]
Or maybe even better, we could:
- make a fix commit that set `false` to the default `fail` and `success` plugins => release 13.4.1
- Deprecate on npm the version 13.3.0, 13.3.1 and 13.4.0
- make a breaking change that re-enable `@semantic-release/github` as the default for `success` and `fail` => release a clean `14.0.0`

That seems a lot simpler to do so.

**Comment by gr2m** [comment]
I'd keep it simple and 

> Or for simplicity sake we can just rename 13.4.0 to 14.0.0 and just remove 13.3.0 and 13.3.1.

then deprecate `13.3.0` and `13.3.1`

**Comment by pvdlg** [comment]
Doing what I mentioned in my [second comment](https://github.com/semantic-release/semantic-release/issues/664#issuecomment-365125391) seems even more simple as we don't have to change any tag or release notes. So if we go for simplicity maybe that's a better choice.

**Comment by gr2m** [comment]
sounds good 👍

**Comment by cyntss** [comment]
was this implemented? im using version 15.1.3 in GitlabCI and it keeps breaking asking for a Github token, that seems to be because of the Success/Fail notifications

**Comment by pvdlg** [comment]
Yes it was implemented and it's included in 15.1.3.
What is your semantic-release configuration? Are you using https://github.com/semantic-release/gitlab-config ?

**Comment by cyntss** [comment]
@pvdlg it is working now after reading: https://github.com/semantic-release/semantic-release/pull/668

I had to set to false the success and fail options:

```
verifyConditions:
  - '@semantic-release/npm'
  - '@semantic-release/gitlab'
publish:
  - '@semantic-release/npm'
  - '@semantic-release/gitlab'
success: false
fail: false
```

**Comment by pvdlg** [comment]
Awesome! Thanks for the feedback!
