### ISSUE TITLE
Error when using --tag-format with CLI

### ISSUE THREAD

**Issue by naerion89** [semantic-release/semantic-release#666]
Hi,

I use semantic-release with the following command : on ubuntu :  

yarn release --branch xxxx --no-ci --tag-format "test-${version}"

i have the follwing error : 

[Semantic release]: ETAGNOVERSION Invalid `tagFormat` option.
The tagFormat (https://github.com/semantic-release/semantic-release/blob/caribou/docs/usage/configuration.md#tagformat) option must contain the variable version exactly once.

Your configuration for the tagFormat option is test-.

{ AggregateError: 
    SemanticReleaseError: Invalid `tagFormat` option.
        at module.exports (/scop/node_modules/semantic-release/lib/get-error.js:6:10)
        at module.exports (/scop/node_modules/semantic-release/lib/verify.js:26:17)
        at <anonymous>
    at module.exports (/scop/node_modules/semantic-release/lib/verify.js:30:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) name: 'AggregateError' }
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

The variable ${version} is replaced by his value (""). So i want to escape the variable with "/"

yarn release --branch xxxx --no-ci --tag-format "test-/${version}"

but i got this error after tag creation : 

[Semantic release]: The release type for the commit is minor
[Semantic release]: Analysis of 3 commits complete: minor release
[Semantic release]: The next release version is 1.1.0
[Semantic release]: Call plugin verify-release
[Semantic release]: Call plugin generateNotes
[Semantic release]: Create tag test-1.1.0
[Semantic release]: Call plugin publish
[Semantic release]: Wrote version 1.1.0 to package.json
[Semantic release]: An error occurred while running semantic-release: { Error: Command failed: npm config get tag
Error: Failed to replace env in config: ${version}
    at /usr/local/lib/node_modules/npm/lib/config/core.js:417:13
    at String.replace (<anonymous>)
    at envReplace (/usr/local/lib/node_modules/npm/lib/config/core.js:413:12)
    at parseField (/usr/local/lib/node_modules/npm/lib/config/core.js:391:7)
    at /usr/local/lib/node_modules/npm/lib/config/core.js:334:17
    at Array.forEach (<anonymous>)
    at Conf.add (/usr/local/lib/node_modules/npm/lib/config/core.js:333:23)
    at ConfigChain.addEnv (/usr/local/lib/node_modules/npm/node_modules/config-chain/index.js:207:15)
    at Conf.addEnv (/usr/local/lib/node_modules/npm/lib/config/core.js:358:30)
    at load_ (/usr/local/lib/node_modules/npm/lib/config/core.js:107:8)
    at Conf.<anonymous> (/usr/local/lib/node_modules/npm/lib/config/core.js:96:5)
    at emitOne (events.js:116:13)
    at Conf.emit (events.js:211:7)
    at ConfigChain._resolve (/usr/local/lib/node_modules/npm/node_modules/config-chain/index.js:281:34)
    at ConfigChain.add (/usr/local/lib/node_modules/npm/node_modules/config-chain/index.js:259:10)
    at Conf.add (/usr/local/lib/node_modules/npm/lib/config/core.js:340:27)
/usr/local/lib/node_modules/npm/lib/npm.js:61
      throw new Error('npm.load() required')
      ^

Error: npm.load() required
    at Object.get (/usr/local/lib/node_modules/npm/lib/npm.js:61:13)
    at process.errorHandler (/usr/local/lib/node_modules/npm/lib/utils/error-handler.js:205:18)
    at emitOne (events.js:116:13)
    at process.emit (events.js:211:7)
    at process._fatalException (bootstrap_node.js:374:26)

    at makeError (/scop/node_modules/execa/index.js:169:9)
    at Promise.all.then.arr (/scop/node_modules/execa/index.js:274:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  code: 7,
  stdout: '',
  stderr: 'Error: Failed to replace env in config: ${version}\n    at /usr/local/lib/node_modules/npm/lib/config/core.js:417:13\n    at String.replace (<anonymous>)\n    at envReplace (/usr/local/lib/node_modules/npm/lib/config/core.js:413:12)\n    at parseField (/usr/local/lib/node_modules/npm/lib/config/core.js:391:7)\n    at /usr/local/lib/node_modules/npm/lib/config/core.js:334:17\n    at Array.forEach (<anonymous>)\n    at Conf.add (/usr/local/lib/node_modules/npm/lib/config/core.js:333:23)\n    at ConfigChain.addEnv (/usr/local/lib/node_modules/npm/node_modules/config-chain/index.js:207:15)\n    at Conf.addEnv (/usr/local/lib/node_modules/npm/lib/config/core.js:358:30)\n    at load_ (/usr/local/lib/node_modules/npm/lib/config/core.js:107:8)\n    at Conf.<anonymous> (/usr/local/lib/node_modules/npm/lib/config/core.js:96:5)\n    at emitOne (events.js:116:13)\n    at Conf.emit (events.js:211:7)\n    at ConfigChain._resolve (/usr/local/lib/node_modules/npm/node_modules/config-chain/index.js:281:34)\n    at ConfigChain.add (/usr/local/lib/node_modules/npm/node_modules/config-chain/index.js:259:10)\n    at Conf.add (/usr/local/lib/node_modules/npm/lib/config/core.js:340:27)\n/usr/local/lib/node_modules/npm/lib/npm.js:61\n      throw new Error(\'npm.load() required\')\n      ^\n\nError: npm.load() required\n    at Object.get (/usr/local/lib/node_modules/npm/lib/npm.js:61:13)\n    at process.errorHandler (/usr/local/lib/node_modules/npm/lib/utils/error-handler.js:205:18)\n    at emitOne (events.js:116:13)\n    at process.emit (events.js:211:7)\n    at process._fatalException (bootstrap_node.js:374:26)\n',
  failed: true,
  signal: null,
  cmd: 'npm config get tag',
  timedOut: false,
  killed: false,
  pluginName: '@semantic-release/npm' }
{ Error: Command failed: npm config get tag
Error: Failed to replace env in config: ${version}
    at /usr/local/lib/node_modules/npm/lib/config/core.js:417:13
    at String.replace (<anonymous>)
    at envReplace (/usr/local/lib/node_modules/npm/lib/config/core.js:413:12)
    at parseField (/usr/local/lib/node_modules/npm/lib/config/core.js:391:7)
    at /usr/local/lib/node_modules/npm/lib/config/core.js:334:17
    at Array.forEach (<anonymous>)
    at Conf.add (/usr/local/lib/node_modules/npm/lib/config/core.js:333:23)
    at ConfigChain.addEnv (/usr/local/lib/node_modules/npm/node_modules/config-chain/index.js:207:15)
    at Conf.addEnv (/usr/local/lib/node_modules/npm/lib/config/core.js:358:30)
    at load_ (/usr/local/lib/node_modules/npm/lib/config/core.js:107:8)
    at Conf.<anonymous> (/usr/local/lib/node_modules/npm/lib/config/core.js:96:5)
    at emitOne (events.js:116:13)
    at Conf.emit (events.js:211:7)
    at ConfigChain._resolve (/usr/local/lib/node_modules/npm/node_modules/config-chain/index.js:281:34)
    at ConfigChain.add (/usr/local/lib/node_modules/npm/node_modules/config-chain/index.js:259:10)
    at Conf.add (/usr/local/lib/node_modules/npm/lib/config/core.js:340:27)
/usr/local/lib/node_modules/npm/lib/npm.js:61
      throw new Error('npm.load() required')
      ^

Error: npm.load() required
    at Object.get (/usr/local/lib/node_modules/npm/lib/npm.js:61:13)
    at process.errorHandler (/usr/local/lib/node_modules/npm/lib/utils/error-handler.js:205:18)
    at emitOne (events.js:116:13)
    at process.emit (events.js:211:7)
    at process._fatalException (bootstrap_node.js:374:26)

    at makeError (/scop/node_modules/execa/index.js:169:9)
    at Promise.all.then.arr (/scop/node_modules/execa/index.js:274:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  code: 7,
  stdout: '',
  stderr: 'Error: Failed to replace env in config: ${version}\n    at /usr/local/lib/node_modules/npm/lib/config/core.js:417:13\n    at String.replace (<anonymous>)\n    at envReplace (/usr/local/lib/node_modules/npm/lib/config/core.js:413:12)\n    at parseField (/usr/local/lib/node_modules/npm/lib/config/core.js:391:7)\n    at /usr/local/lib/node_modules/npm/lib/config/core.js:334:17\n    at Array.forEach (<anonymous>)\n    at Conf.add (/usr/local/lib/node_modules/npm/lib/config/core.js:333:23)\n    at ConfigChain.addEnv (/usr/local/lib/node_modules/npm/node_modules/config-chain/index.js:207:15)\n    at Conf.addEnv (/usr/local/lib/node_modules/npm/lib/config/core.js:358:30)\n    at load_ (/usr/local/lib/node_modules/npm/lib/config/core.js:107:8)\n    at Conf.<anonymous> (/usr/local/lib/node_modules/npm/lib/config/core.js:96:5)\n    at emitOne (events.js:116:13)\n    at Conf.emit (events.js:211:7)\n    at ConfigChain._resolve (/usr/local/lib/node_modules/npm/node_modules/config-chain/index.js:281:34)\n    at ConfigChain.add (/usr/local/lib/node_modules/npm/node_modules/config-chain/index.js:259:10)\n    at Conf.add (/usr/local/lib/node_modules/npm/lib/config/core.js:340:27)\n/usr/local/lib/node_modules/npm/lib/npm.js:61\n      throw new Error(\'npm.load() required\')\n      ^\n\nError: npm.load() required\n    at Object.get (/usr/local/lib/node_modules/npm/lib/npm.js:61:13)\n    at process.errorHandler (/usr/local/lib/node_modules/npm/lib/utils/error-handler.js:205:18)\n    at emitOne (events.js:116:13)\n    at process.emit (events.js:211:7)\n    at process._fatalException (bootstrap_node.js:374:26)\n',
  failed: true,
  signal: null,
  cmd: 'npm config get tag',
  timedOut: false,
  killed: false,
  pluginName: '@semantic-release/npm' }

i use npm  5.6.0 and node 8.9.4

This is my package.json 

``` json
{
  "name": "xxxxx",
  "version": "1.1.0",
  "scripts": {
    "release": "semantic-release",
    "commit": "commit"
  },
  "release": {
    "verifyConditions": [
      "@semantic-release/gitlab",
      "@semantic-release/git"
    ],
    "getLastRelease": "@semantic-release/git",
    "createGitTag": "@semantic-release/git",
    "publish": [
      {
        "path": "@semantic-release/npm",
        "npmPublish": false
      },
      {
        "path": "@semantic-release/git",
        "message": "chore(release): release ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
      },
      "@semantic-release/changelog",
      "@semantic-release/gitlab"
    ],
    "success": "",
    "fail": "",
    "gitlabUrl": "https://gitlab.integration.scop.lille.tis"
  },
  "devDependencies": {
    "@commitlint/cli": "^6.1.0",
    "@commitlint/config-conventional": "^6.1.0",
    "@commitlint/prompt-cli": "^6.1.0",
    "husky": "^0.15.0-rc.8",
    "semantic-release": "^13.4.0",
    "@semantic-release/changelog": "^1.1.0",
    "@semantic-release/git": "^3.1.0",
    "@semantic-release/gitlab": "^2.1.0",
    "@semantic-release/npm": "^3.1.0"
  },
  "husky": {
    "hooks": {
      "commit-msg": "commitlint -e $GIT_PARAMS"
    }
  }
}
```

Can you help me ?
Regards
Gaetan

**Comment by pvdlg** [comment]
This is because your OS expand whats inside`${}` as if it was an environment variable. As the `version` environment variable is probably not set, semantic-release receive `test-` from your OS.

You have to escape the `$` like that `semantic-release --tag-format test-\${version}`

**Comment by naerion89** [comment]
yes i already did it but now i have the following error 

stderr: 'Error: Failed to replace env in config: ${version}\n at /usr/local/lib/node_modules/npm/lib/config/core.js:417:13\n at String.replace ()\n at envReplace (/usr/local/lib/node_modules/npm/lib/config/core.js:413:12)\n at parseField (/usr/local/lib/node_modules/npm/lib/config/core.js:391:7)\n at /usr/local/lib/node_modules/npm/lib/config/core.js:334:17\n at Array.forEach ()\n at Conf.add (/usr/local/lib/node_modules/npm/lib/config/core.js:333:23)\n at ConfigChain.addEnv (/usr/local/lib/node_modules/npm/node_modules/config-chain/index.js:207:15)\n at Conf.addEnv (/usr/local/lib/node_modules/npm/lib/config/core.js:358:30)\n at load_ (/usr/local/lib/node_modules/npm/lib/config/core.js:107:8)\n at Conf. (/usr/local/lib/node_modules/npm/lib/config/core.js:96:5)\n at emitOne (events.js:116:13)\n at Conf.emit (events.js:211:7)\n at ConfigChain._resolve (/usr/local/lib/node_modules/npm/node_modules/config-chain/index.js:281:34)\n at ConfigChain.add (/usr/local/lib/node_modules/npm/node_modules/config-chain/index.js:259:10)\n at Conf.add (/usr/local/lib/node_modules/npm/lib/config/core.js:340:27)\n/usr/local/lib/node_modules/npm/lib/npm.js:61\n throw new Error('npm.load() required')\n ^\n\nError: npm.load() required\n at Object.get (/usr/local/lib/node_modules/npm/lib/npm.js:61:13)\n at process.errorHandler (/usr/local/lib/node_modules/npm/lib/utils/error-handler.js:205:18)\n at emitOne (events.js:116:13)\n at process.emit (events.js:211:7)\n at process._fatalException (bootstrap_node.js:374:26)\n',
failed: true,
signal: null,
cmd: 'npm config get tag',
timedOut: false,
killed: false,
pluginName: '@semantic-release/npm' }

**Comment by pvdlg** [comment]
This error doesn't seems related. It happens when we execute `npm config get tag` to retrieve the npm dist-tag configured.

What happen if you run `npm config get tag` manually in your project?

Can you provide the configuration in your `.npmrc` and `publishConfig` in your `package.json`?

**Comment by pvdlg** [comment]
It seems npm is trying to do something with `${version}` but I can't figure out how what you pass in `--tag-format` ends up meddling with `npm`.

**Comment by pvdlg** [comment]
I think I found out. It seems you have `tag=test-${version}` in your `.npmrc`.

`tag` in `.npmrc` is for npm dist-tag, it has nothing to do with the Git tag format.

You should remove that from `.npmrc`.

Please let us know if that solve the issue.

**Comment by pvdlg** [comment]
@pvdlg did the suggestions above solved your issue?

**Comment by pvdlg** [comment]
I'm going to close this issue, feel free to re-open if the problem persist.

**Comment by Sriharsha9676** [comment]
Hi @pvdlg actually i have lost semantic release commits form github so its taking old version has last release and throwing and error
Error: Command failed with exit code 128: git tag 1.30.0 c653a7629b24d2f0510272f13c297b32188c9cab
fatal: tag '1.30.0' already exists

how to solve this actually it should release 1.31.25 but its failing the pipile line

**Comment by paulakfleck** [comment]
Like mentioned by @adamboxman , the doc should be updated. Also, a few examples would be nice (on all tags)

**Comment by travi** [comment]
> the doc should be updated

PRs are welcome and your perspective is helpful for adjusting the documentation to include details in a way that would have helped you
