### ISSUE TITLE
git repository url forcefully converted to https

### ISSUE THREAD

**Issue by brokenmass** [semantic-release/semantic-release#667]
# Bug report

## Current behavior

I'm trying to release a project hosted on gitlbab. 
I'm using ssh agent for the git operations and I'm providing a GL_TOKEN env variable for the gitlab release.
the repository.url is in the package.json is in the form `git@hostname:group/project.git`

Unluckily semantic-release always convert the repo url to `https://hostname/group/project.git` unless it's explicitly using the `http` protocol (https://github.com/semantic-release/semantic-release/blob/caribou/lib/get-git-auth-url.js#L23) and tries to use the GL_TOKEN for authentication. 

As my gitlab is using http protocol the `https://hostname/group/project.git` endpoint is invalid and the release fails at the `verifyAuth` step (https://github.com/semantic-release/semantic-release/blob/caribou/lib/git.js#L89) as that will call `git  push --dry-run https://hostname/group/project.git HEAD:${branch}`

I don't see the reason why the semantic-release should forcefully use an http/https endpoint when git protocol (with ssh credential) is available

If i change the repository.url to `http://hostname/group/project.git` then everything works correctly (but ssh agent is not used)

## Expected behavior

The git operations should be performed suing the git url (hence using the ssh key) while still be able to call the gitlab api using the provided GL_TOKEN

## Environment

- **semantic-release** version: 13.4
- CI environment: jenkins but can reproduce locally
- Plugins used: npm, git, gitlab
- **semantic-release** configuration: 
```
"release": {
    "branch": "master",
    "debug": true,
    "verifyConditions": [
      "@semantic-release/git",
      "@semantic-release/gitlab"
    ],
    "publish": [
      {
        "path": "@semantic-release/npm",
        "npmPublish": false,
        "tarballDir": "artifacts"
      },
      "@semantic-release/git",
      "@semantic-release/gitlab"
    ],
    "success": [],
    "fail": [],
    "gitlabUrl": "http://someip"
  },
```

**Comment by pvdlg** [comment]
Yes we didn't plan for scenario. If one the environment variable within `GIT_CREDENTIALS`, `GH_TOKEN`, `GITHUB_TOKEN`, `GL_TOKEN` or `GITLAB_TOKEN` is set then we convert the repository url to https and we use the token.

As you notice if you set your repository url with http, we use it and don't convert to https.
I'm not really sure how to solve that on our side as we need a way to figure out that the `GL_TOKEN` is set for API purpose only and not for accessing the repo.

Maybe we could try `git push --dry-run` with the actual url configured and if it works use it. If it doesn't we try to convert to `http`/`https` and use the `GL_TOKEN` as of now. I'd to experiment a bit to see if that could work.

Why not using `https` for your repository? Is it a common situation to not have `https` enabled?

**Comment by brokenmass** [comment]
> Maybe we could try git push --dry-run with the actual url configured and if it works use it. If it doesn't we try to convert to http/https and use the GL_TOKEN as of now. I'd to experiment a bit to see if that could work.
☝️ This for me would be the best solution.

Another scenario where this issue arises is if the user that owns the access token is different from the user owning the ssh key. this will commit code to the repository with the 'wrong' user.
