### ISSUE TITLE
Quick Question - no CI release

### ISSUE THREAD

**Issue by Apidcloud** [semantic-release/semantic-release#669]
Just a quick question that arose from a twitter thread.
Not sure if there's a better alternative to ask them, thus opening an issue here.

Is it possible to use semantic-release without a CI? The doubt is on whether: 
> how good the GitHub (Enterprise) integration would work

Thanks!

**Comment by pvdlg** [comment]
Those question are better asked via our different [support channels](https://github.com/semantic-release/semantic-release#get-help).

Yes it's possible to semantic-release without a CI. See [this FAQ](https://semantic-release.gitbooks.io/semantic-release/content/docs/support/FAQ.html#can-i-run-semantic-release-on-my-local-machine-rather-than-on-a-ci-server). As mentioned there it's not the recommended approach, but it's possible

Regarding GitHub Enterprise, several CI can be used with it I think (Travis Enterprise for example).

semantic-release supports GHE, see [githubUrl 
 and githubApiPathPrefix options](https://github.com/semantic-release/github#options).

semantic-release should also work with any CI supported by [env-ci](https://github.com/pvdlg/env-ci).
If a particular CI is not supported we can add it as long as we have the documentation regarding the environment variables available.

**Comment by Apidcloud** [comment]
Thanks a lot 😄 I'll be sure to use twitter or something next time!

**Comment by pvdlg** [comment]
Usually Gitter/Stackoverflow is the best option (or at least I spend more time there than on Twitter)
