### ISSUE TITLE
Package.json not updated with latest released version

### ISSUE THREAD

**Issue by bjavaid** [semantic-release/semantic-release#672]
## Current behavior

Travis CI pipeline show the following log of semantic-release

`[Semantic release]: The next release version is 3.2.3
[Semantic release]: Call plugin verify-release
[Semantic release]: Call plugin generateNotes
[Semantic release]: Create tag v3.2.3
[Semantic release]: Call plugin publish
[Semantic release]: Wrote version 3.2.3 to package.json
[Semantic release]: Publishing version 3.2.3 to npm registry
+ @blueeast/bluerain-os@3.2.3[Semantic release]: Published GitHub release: https://github.com/BlueEastCode/bluerain-os/releases/tag/v3.2.3
[Semantic release]: Published release: 3.2.3`

As you can check that debug logs shows "Wrote version 3.2.3 to package.json" but when I check my package.json on github, it shows the old version of the package. 

## Expected behavior

The package.json file should be updated on github with the latest released version.

## Environment

- **semantic-release** version: 14.0.0
- CI environment: Travis
- Plugins used: Default
- **semantic-release** configuration: Default Configurations
- CI logs: https://travis-ci.org/BlueEastCode/bluerain-os/builds/341260828

The version 13.3.0 was adding issues on my github; so I modified the semantic-release package version and run the pipeline and found this observation.

Currently I am defining version in the package.json file as "0.0.0-development"

**Comment by pvdlg** [comment]
That's the expected behavior, the updated `package.json` is published on npm but not pushed to the Git repository by default.
See this [FAQ](https://semantic-release.gitbooks.io/semantic-release/content/docs/support/FAQ.html#why-is-the-packagejsons-version-not-updated-in-my-repository) for explanation on solutions to push the `package.json` to the Git repository.

**Comment by pvdlg** [comment]
@bjavaid does that address your question/concerns ?

**Comment by pvdlg** [comment]
I'm going to close this issue, feel free to re-open if the problem persist.

**Comment by protoEvangelion** [comment]
Current FAQ location: https://semantic-release.gitbook.io/semantic-release/support/faq#why-is-the-package-jsons-version-not-updated-in-my-repository
