### ISSUE TITLE
"This PR is included in version x.y.z" commented twice on same pull request

### ISSUE THREAD

**Issue by gr2m** [semantic-release/semantic-release#682]
## Current behavior

(I’ve deleted the 2nd comment already)

- https://github.com/node-nock/nock/pull/1070#issuecomment-368255825
- https://github.com/node-nock/nock/pull/1071#issuecomment-368255824

But for what it's worth I have not seen it on other repositories, but I think this was the first I used v15 on

## Expected behavior

Should only comment once

## Environment

- **semantic-release** version: 15
- CI environment: Travis
- Plugins used: -
- **semantic-release** configuration: -
- CI logs: https://travis-ci.org/node-nock/nock/jobs/345729741#L2034-L2037

**Comment by pvdlg** [comment]
Do you know if this PR was referenced somewhere else? Like in a commit message or in a PR associated with a commit?

**Comment by gr2m** [comment]
yeah, here: https://github.com/node-nock/nock/commit/315104d4c7390199d60fc0c062abdd4ab6a11e89

`Squash & merge` adds the pull request reference by default so I usually keep it there

**Comment by pvdlg** [comment]
In the case of 1070 and 1071 it doesn't seems they are referenced by another commit or PR.

I think it happen when we split the `search` request in multiple. If there is multiple request that return the same PR they will be commented twice.
