### ISSUE TITLE
`ENOGHTOKEN` Error got

### ISSUE THREAD

**Issue by boxsnake** [semantic-release/semantic-release#684]
# Bug report

## Current behavior

1. When I run `npm run semantic-release`, the console gives a `ENOGHTOKEN` error. I am not sure which git config key is responsive for this.
2. My `npm` and `github` accounts are set with `semantic-release-cli setup` commands. This command result in a token in `.npmrc` but nothing change in `.gitconfig`.
3. Here is the whole log by calling `npm run semantic-release`.
```bash
λ npm run semantic-release

> test-repo@0.0.0-development semantic-release X:\test-path\test-repo
> semantic-release

[Semantic release]: Load plugin verifyConditions from @semantic-release/npm
[Semantic release]: Load plugin verifyConditions from @semantic-release/github
[Semantic release]: Load plugin getLastRelease from @semantic-release/npm
[Semantic release]: Load plugin analyzeCommits from @semantic-release/commit-analyzer
[Semantic release]: Load plugin generateNotes from @semantic-release/release-notes-generator
[Semantic release]: Load plugin publish from @semantic-release/npm
[Semantic release]: Load plugin publish from @semantic-release/github
[Semantic release]: This run was not triggered in a known CI environment, running in dry-run mode.
[Semantic release]: Run automated release from branch master
[Semantic release]: Call plugin verify-conditions
[Semantic release]: Verify authentication for registry https://registry.npmjs.org/
[Semantic release]: ENOGHTOKEN No github token specified.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! test-repo@0.0.0-development semantic-release: `semantic-release`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the test-repo@0.0.0-development semantic-release script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\Program Files\nodejs\node_global\cache\_logs\2018-03-01T04_43_44_978Z-debug.log
```

## Expected behavior

Expected: the github authentication success.

## Environment

- **semantic-release** version: 
- CI environment: N/A
- Plugins used: defaults
- **semantic-release** configuration: (in `package.json`)
```json
"release": {
  "verifyConditions": [
    "@semantic-release/npm",
    "@semantic-release/github"
  ]
}
```
- CI logs: N/A
- Other descriptions:
* Repo name: `test-repo`
* Path to repo: `X:\test-path\test-repo`
* `.gitconfig` content:
```ini
[core]
	excludesfile = C:\\Users\\boxsn\\Documents\\gitignore_global.txt
[user]
	name = Alex Fang
	email = deeno@qq.com
```
* `.npmrc` config:
```ini
prefix=D:\Program Files\nodejs\node_global\modules
cache=D:\Program Files\nodejs\node_global\cache
//registry.npmjs.org/:_authToken=[~~~hidden~~~]
```

**Comment by pvdlg** [comment]
`semantic-release-cli setup` sets up the npm and GitHub token on your CI, not on your local machine.

If seems you are running `npm run semantic-release` locally. You probably don't have the `GH_TOKEN` environment variable set locally as indicated by the error `No github token specified`.

If you want to run semantic-release locally you have to set the `NPM_TOKEN` and `GH_TOKEN` environment variable on your local machine as indicated in [this FAQ](https://semantic-release.gitbooks.io/semantic-release/content/docs/support/FAQ.html#can-i-run-semantic-release-on-my-local-machine-rather-than-on-a-ci-server).
