### ISSUE TITLE
semantic-release global unable to find semantic-release/git

### ISSUE THREAD

**Issue by MadsRCEnerginet** [semantic-release/semantic-release#685]
## Current behavior

Running semantic-release on gitlab-ci, using the node:8 image and npx semantic-release fails with `Cannot find module '@semantic-release/git'` - Even tried npm install -g @semantic-release/git prior to running semantic-release

## Expected behavior

To complete without error...

## Environment

- **semantic-release** version: 
- CI environment: gitlab-ci
- Plugins used: semantic-release/gitlab, semantic-release/git
- **semantic-release** configuration: https://gitlab.com/MadsRC/vee/blob/master/.releaserc.json
- CI logs: https://gitlab.com/MadsRC/vee/-/jobs/55332075

**Comment by pvdlg** [comment]
It seems I can't access your repo or the CI logs. I have a 404 error.

Doing `npm -g install @semantic-release/git semantic-release && semantic-release` should work.

**Comment by MadsRCEnerginet** [comment]
@pvdlg I had forgotten to publicize the repo, should be fixed now.

`npm -g install @semantic-release/git semantic-release && semantic-release` seemed to work, however I'm having issues with it trying to publish to npm (and failing due to no `package.json´ file... I'll keep working on it to try and get it to work.
