### ISSUE TITLE
ERROR You cannot publish over the previously published versions: 0.0.0-development 

### ISSUE THREAD

**Issue by abalad** [semantic-release/semantic-release#687]
## Bug report

Semantic-release is generating an error while trying to publish a new release in NPM. It arrives until publish the version but it generates an error at the moment of the build

## Expected behavior

Publish the release in NPM without generating this error

## Environment

- **semantic-release** version: 12.4.1
- CI environment:  TRAVIS
- **semantic-release** configuration: https://github.com/TemainfoSoftware/truly-ui/blob/master/package.json
- CI logs: https://api.travis-ci.org/v3/job/349305085/log.txt

**Comment by pvdlg** [comment]
In your `package.json` I see `"pkgRoot": "dist"` but in the CI logs `Wrote version 2.19.1 to package.json`. It should be `Wrote version 2.19.1 to dist/package.json`.

I cloned your repo and tried, and semantic-release properly logs `Wrote version 2.19.1 to dist/package.json`.

Are you sure the current configuration in `package.json` is the one that was used in the CI job for which you provided logs?

**Comment by abalad** [comment]
Sorry @pvdlg  really was that, I was passing the wrong package.json into the ci.
