### ISSUE TITLE
Getting 403

### ISSUE THREAD

**Issue by unional** [semantic-release/semantic-release#688]
https://travis-ci.org/unional/eslint-plugin-harmony/jobs/350104382
https://travis-ci.org/unional/eslint-plugin-harmony/jobs/350105378#L1452

```sh
travis-deploy-once "npm run semantic-release"
{ HTTPError: Response code 403 (Forbidden)
    at stream.catch.then.data (/home/travis/.nvm/versions/node/v9.7.1/lib/node_modules/travis-deploy-once/node_modules/got/index.js:341:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
  name: 'HTTPError',
  host: 'api.travis-ci.org',
  hostname: 'api.travis-ci.org',
  method: 'POST',
  path: '/auth/github',
  protocol: 'https:',
  url: 'https://api.travis-ci.org/auth/github',
  statusCode: 403,
  statusMessage: 'Forbidden',
  headers: 
   { connection: 'close',
     server: 'nginx',
     date: 'Wed, 07 Mar 2018 01:04:34 GMT',
     'content-type': 'application/json',
     'transfer-encoding': 'chunked',
     'access-control-allow-origin': '*',
     'access-control-allow-credentials': 'true',
     'access-control-expose-headers': 'Content-Type, Cache-Control, Expires, Etag, Last-Modified, X-Request-ID',
     'strict-transport-security': 'max-age=31536000',
     'x-endpoint': 'Travis::Api::App::Endpoint::Authorization',
     'x-pattern': '/github',
     'x-oauth-scopes': 'public',
     'x-accepted-oauth-scopes': 'public',
     vary: 'Accept,Accept-Encoding',
     'content-encoding': 'gzip',
     'x-rack-cache': 'invalidate, pass',
     'x-request-id': '2eaa9f3d-334b-4fde-bb08-aea346bf71a6',
     via: '1.1 vegur' } }
```

On all builds in this repo right not (haven't check other repos yet).

The NPM token and GITHUB token should be fine.

**Comment by gr2m** [comment]
Did it work before? Or is this an initial setup?

**Comment by unional** [comment]
Yes, it worked before. Released 1.0.0 and 1.0.1

**Comment by pvdlg** [comment]
The problem happens in `travis-deploy-once` not in semantic-release.
Is you repo added to Travis? Did you change your repo name recently?

**Comment by Arcanemagus** [comment]
I'm [seeing this](https://travis-ci.org/AtomLinter/atom-linter-pug/jobs/350722807#L1851) as well, the only change from the last build being https://github.com/AtomLinter/atom-linter-pug/pull/37 which updates to `semantic-release@15.0.1`/`@semantic-release/apm-config@2.0.0`.

**Comment by pvdlg** [comment]
It seems it's the Travis API that returns a 403 times to times for the `auth/github` endpoint.
On my local test it seems to happen quite rarely. I get only every 20 or 30 calls when call the API repeatedly and really fast.

I'll implement a retry mechanism in `travis-deploy-once` as it seems it's the only workaround possible.

**Comment by jan-molak** [comment]
I've just encountered the exact same issue 3 times in a row with `travis-deploy-once` v. 5.0.11 and `semantic-release` v 17.1.1. It worked on the 4th retry, so perhaps the retry logic in `travis-deploy-once` might need a bit more tweaking?
