### ISSUE TITLE
Write a <run script> verifyConditions plugin

### ISSUE THREAD

**Issue by remy** [semantic-release/semantic-release#69]
Run any script. If the exit code is `0`, then it's a "verified okay". Otherwise, don't publish.

Because it might be that the tests should pass, but the publish should not. (I have a specific use case in mind, but can't talk publically about it yet - client project).

**Comment by ariporad** [comment]
Shouldn't be hard, I'll take it on. @boennemann, can you create a repo for it?

**Comment by boennemann** [comment]
@remy Thanks for the idea, genius :+1: 

@ariporad Thanks for picking it up. Here you go, just PR it in :) https://github.com/semantic-release/condition-run-script
