### ISSUE TITLE
Remove v prefix from GitHub release tags

### ISSUE THREAD

**Issue by rarkins** [semantic-release/semantic-release#693]
Is it possible currently to tag releases without the `v` prefix? e.g. tags like `1.2.0` instead of `v1.2.0`?

**Comment by pvdlg** [comment]
Yes, with the [tagFormat option](https://semantic-release.gitbooks.io/semantic-release/content/docs/usage/configuration.html#tagformat)

**Comment by rarkins** [comment]
Thank you! I kept searching for tag and prefix - did not notice that option, sorry.

**Comment by LakshmiRavali** [comment]
> Thank you! I kept searching for tag and prefix - did not notice that option, sorry.

Can you please add the configuration that solved this issue?
