### ISSUE TITLE
SemanticReleaseError: The push permission to the Git repository is required

### ISSUE THREAD

**Issue by gr2m** [semantic-release/semantic-release#695]
`GH_TOKEN` was set via `semantic-release-cli setup`. I restarted the build, same result. Then I manually created a new token and updated it on travis, still same result.

## Current behavior

https://travis-ci.org/gr2m/octokit-rest-routes/jobs/352181416#L2017

## Expected behavior

It should publish a new version.

## Environment

- **semantic-release** version: 15.0.2
- CI environment: Travis
- Plugins used: none
- **semantic-release** configuration: none
- CI logs: https://travis-ci.org/gr2m/octokit-rest-routes/jobs/352181416#L2017

**Comment by gr2m** [comment]
No idea what could be going on here :/

**Comment by pvdlg** [comment]
Can you re-run with debug enabled?

**Comment by ahmadnassri** [comment]
I'm starting to see the same error, CI log here: https://travis-ci.org/ahmadnassri/glob-promise/jobs/352165164

I ran locally with `--no-ci --debug` to see if I can get the debug for you, but that seemed to actually work ...

```
> npx semantic-release --debug --no-ci
  semantic-release:config options values: [ 'branch', 'repositoryUrl', 'ci', 'debug', 'noCi' ] +0ms
  semantic-release:config name: undefined +2ms  semantic-release:config branch: 'master' +0ms
  semantic-release:config repositoryUrl: 'git+https://github.com/ahmadnassri/glob-promise.git' +0ms
  semantic-release:config analyzeCommits: undefined +0ms  semantic-release:config generateNotes: undefined +0ms
  semantic-release:config verifyConditions: undefined +0ms
  semantic-release:config verifyRelease: undefined +0ms
  semantic-release:config publish: undefined +0ms
[Semantic release]: Load plugin verifyConditions from @semantic-release/npm
[Semantic release]: Load plugin verifyConditions from @semantic-release/github
[Semantic release]: Load plugin getLastRelease from @semantic-release/npm
[Semantic release]: Load plugin analyzeCommits from @semantic-release/commit-analyzer
[Semantic release]: Load plugin generateNotes from @semantic-release/release-notes-generator
[Semantic release]: Load plugin publish from @semantic-release/npm
[Semantic release]: Load plugin publish from @semantic-release/github
  semantic-release:get-version-head Check if the current working directory is a git repository +0ms
  semantic-release:get-version-head cmd: 'git rev-parse --git-dir' +0ms
  semantic-release:get-version-head stdout: '.git' +1ms
  semantic-release:get-version-head stderr: '' +0ms
  semantic-release:get-version-head code: 0 +0ms
[Semantic release]: Run automated release from branch master
[Semantic release]: Call plugin verify-conditions
[Semantic release]: Verify authentication for registry https://registry.npmjs.org/
[Semantic release]: Verify GitHub authentication
[Semantic release]: Call plugin get-last-release
info attempt registry request try #1 at 08:23:56
http request GET https://registry.npmjs.org/glob-promise
http 200 https://registry.npmjs.org/glob-promise
[Semantic release]: Found version 3.3.0 of package glob-promise with dist-tag latest
  semantic-release:get-version-head Check if commit is in history +1s  semantic-release:get-version-head cmd: 'git merge-base --is-ancestor 93a7d4568de54dbcfc74f313dad7ab99ce0e6949 HEAD' +0ms
  semantic-release:get-version-head stdout: '' +0ms  semantic-release:get-version-head stderr: '' +0ms
  semantic-release:get-version-head code: 0 +0ms
  semantic-release:get-version-head Check if commit is in history +3ms
  semantic-release:get-version-head cmd: 'git merge-base --is-ancestor 93a7d4568de54dbcfc74f313dad7ab99ce0e6949 HEAD' +0ms
  semantic-release:get-version-head stdout: '' +0ms
  semantic-release:get-version-head stderr: '' +0ms
  semantic-release:get-version-head code: 0 +0ms
  semantic-release:get-commits Use gitHead: 93a7d4568de54dbcfc74f313dad7ab99ce0e6949 +0ms
[Semantic release]: Found 4 commits since last release
  semantic-release:get-commits Parsed commits: [ { commit: { long: '3b44f0ed6245cd07854ca1b2beecbda245fe54cf', short: '3b44f0e' }, tree: { long: '0d82467ee091287aad38949ef1484f18342d56e9', short: '0d82467' }, author: { name: 'Ahmad Nassri', email: 'ahmad@ahma
dnassri.com', date: 2018-03-12T03:50:23.000Z }, committer: { name: 'Ahmad Nassri', email: 'ahmad@ahmadnassri.com', date: 2018-03-12T03:50:48.000Z }, subject: 'docs(readme): use --production instead of --only', body: '[skip ci]\n', hash: '3b44f0ed6245cd07854ca
1b2beecbda245fe54cf', message: 'docs(readme): use --production instead of --only\n\n[skip ci]', gitTags: '(HEAD -> master, origin/master, origin/HEAD)', committerDate: 2018-03-12T03:50:48.000Z }, { commit: { long: '734117dc18a69432ffd620b980edc06b18d209ce', s
hort: '734117d' }, tree: { long: 'e194d64cf1aea316beaafc005d3ec79985cda653', short: 'e194d64' }, author: { name: 'Aluan Haddad', email: 'aluanh@gmail.com', date: 2018-03-12T03:44:38.000Z }, committer: { name: 'Ahmad Nassri', email: 'ahmad@ahmadnassri.com', da
te: 2018-03-12T03:44:38.000Z }, subject: 'feat(typescript): add TypeScript typings', body: '* Add TypeScript typings\r\n\r\n*  fix white space\r\n', hash: '734117dc18a69432ffd620b980edc06b18d209ce', message: 'feat(typescript): add TypeScript typings\n\n* Add
TypeScript typings\r\n\r\n*  fix white space', gitTags: '', committerDate: 2018-03-12T03:44:38.000Z }, { commit: { long: 'f4da92e7910c6662bde2f0ef5587190da24e8471', short: 'f4da92e' }, tree: { long: 'fdcc95a9bb771e1f3c1e4f6836791c903ed9bb8f', short: 'fdcc95a'
 }, author: { name: 'Ahmad Nassri', email: 'ahmad@ahmadnassri.com', date: 2018-03-12T03:42:28.000Z }, committer: { name: 'Ahmad Nassri', email: 'ahmad@ahmadnassri.com', date: 2018-03-12T03:42:28.000Z }, subject: 'docs(readme): improve readme', body: '', hash:
 'f4da92e7910c6662bde2f0ef5587190da24e8471', message: 'docs(readme): improve readme', gitTags: '', committerDate: 2018-03-12T03:42:28.000Z }, { commit: { long: '5c183106ec3895e2574aa00549030c7e7b948625', short: '5c18310' }, tree: { long: '4bfbc4ea6c41ad10139f
d71a6f1c1b3b9a086d3c', short: '4bfbc4e' }, author: { name: 'Ahmad Nassri', email: 'ahmad@ahmadnassri.com', date: 2018-03-12T03:39:11.000Z }, committer: { name: 'Ahmad Nassri', email: 'ahmad@ahmadnassri.com', date: 2018-03-12T03:39:11.000Z }, subject: 'feat(pa
ckage): update dependencies and improve repo meta and build process', body: '', hash: '5c183106ec3895e2574aa00549030c7e7b948625', message: 'feat(package): update dependencies and improve repo meta and build process', gitTags: '', committerDate: 2018-03-12T03:
39:11.000Z } ] +7ms
  semantic-release:get-version-head Get git commit tag +11ms
  semantic-release:get-version-head cmd: 'git describe --tags --exact-match 93a7d4568de54dbcfc74f313dad7ab99ce0e6949' +0ms
  semantic-release:get-version-head stdout: 'v3.3.0' +0ms
  semantic-release:get-version-head stderr: '' +0ms
  semantic-release:get-version-head code: 0 +0ms
[Semantic release]: Call plugin analyze-commits
[Semantic release]: Analyzing commit: docs(readme): use --production instead of --only

[skip ci]
  semantic-release:commit-analyzer Analyzing with default rules +0ms
[Semantic release]: The commit should not trigger a release
[Semantic release]: Analyzing commit: feat(typescript): add TypeScript typings

* Add TypeScript typings

*  fix white space
  semantic-release:commit-analyzer Analyzing with default rules +0ms
  semantic-release:commit-analyzer The rule { type: 'feat', release: 'minor' } match commit with release type 'minor' +0ms
[Semantic release]: The release type for the commit is minor
[Semantic release]: Analyzing commit: docs(readme): improve readme
  semantic-release:commit-analyzer Analyzing with default rules +1ms
[Semantic release]: The commit should not trigger a release
[Semantic release]: Analyzing commit: feat(package): update dependencies and improve repo meta and build process
  semantic-release:commit-analyzer Analyzing with default rules +0ms
  semantic-release:commit-analyzer The rule { type: 'feat', release: 'minor' } match commit with release type 'minor' +0ms
[Semantic release]: The release type for the commit is minor
[Semantic release]: Analysis of 4 commits complete: minor release
[Semantic release]: The next release version is 3.4.0
  semantic-release:get-version-head Get git head +9ms
  semantic-release:get-version-head cmd: 'git rev-parse HEAD' +0ms
  semantic-release:get-version-head stdout: '3b44f0ed6245cd07854ca1b2beecbda245fe54cf' +0ms
  semantic-release:get-version-head stderr: '' +0ms
  semantic-release:get-version-head code: 0 +0ms
[Semantic release]: Call plugin verify-release
[Semantic release]: Call plugin generateNotes
  semantic-release:release-notes-generator version: '3.4.0' +0ms
  semantic-release:release-notes-generator host: 'github.com' +0ms
  semantic-release:release-notes-generator owner: 'ahmadnassri' +0ms
  semantic-release:release-notes-generator repository: 'glob-promise' +0ms
  semantic-release:release-notes-generator previousTag: 'v3.3.0' +0ms
  semantic-release:release-notes-generator currentTag: 'v3.4.0' +0ms
[Semantic release]: Call plugin publish
[Semantic release]: Wrote version 3.4.0 to package.json
[Semantic release]: Wrote version 3.4.0 to package-lock.json
[Semantic release]: Publishing version 3.4.0 to npm registry
+ glob-promise@3.4.0  semantic-release:get-version-head Get git head +4s
  semantic-release:get-version-head cmd: 'git rev-parse HEAD' +0ms
  semantic-release:get-version-head stdout: '3b44f0ed6245cd07854ca1b2beecbda245fe54cf' +0ms
  semantic-release:get-version-head stderr: '' +0ms
  semantic-release:get-version-head code: 0 +0ms
  semantic-release:github release owner: 'ahmadnassri' +0ms
  semantic-release:github release repo: 'glob-promise' +0ms
  semantic-release:github release name: 'v3.4.0' +0ms
  semantic-release:github release branch: 'master' +0ms
  semantic-release:github Create git tag 'v3.4.0' with commit '3b44f0ed6245cd07854ca1b2beecbda245fe54cf' +242ms
[Semantic release]: Published GitHub release: https://github.com/ahmadnassri/glob-promise/releases/tag/v3.4.0
  semantic-release:get-version-head Get git head +1s
  semantic-release:get-version-head cmd: 'git rev-parse HEAD' +0ms
  semantic-release:get-version-head stdout: '3b44f0ed6245cd07854ca1b2beecbda245fe54cf' +0ms
  semantic-release:get-version-head stderr: '' +0ms
  semantic-release:get-version-head code: 0 +0ms
[Semantic release]: Published release: 3.4.0
```

**Comment by gr2m** [comment]
Hm I set `DEBUG=semantic-release`, see https://travis-ci.org/gr2m/octokit-rest-routes/jobs/352181416#L424, but output is still the same as far as I can tell? Is that an unrelated bug? I’ll change the command to run with --debug

**Comment by gr2m** [comment]
so, with the new commit and `--debug` it worked ¯\\\_(ツ)\_/¯
https://travis-ci.org/gr2m/octokit-rest-routes/builds/352421582#L1987

but there are some one error message in there

```
[Semantic release]: Running semantic-release version 15.0.2
2018-03-12T16:28:57.391Z semantic-release:get-version-head Error: Command failed: git push --dry-run git+https://github.com/gr2m/octokit-rest-routes.git HEAD:master
fatal: Unable to find remote helper for 'git+https'
    at makeError (/home/travis/build/gr2m/octokit-rest-routes/node_modules/execa/index.js:169:9)
    at Promise.all.then.arr (/home/travis/build/gr2m/octokit-rest-routes/node_modules/execa/index.js:274:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
2018-03-12T16:28:57.396Z semantic-release:config options values: { branch: 'master',
  repositoryUrl: 'https://[secure]@github.com/gr2m/octokit-rest-routes.git',
  tagFormat: 'v${version}',
  _: [],
  debug: true,
  '$0': 'node_modules/.bin/semantic-release' }
```

Does that ring a bell?

**Comment by pvdlg** [comment]
If you use the environment variable you have to set it to `DEBUG=semantic-release:*`. It seems to required by `debug`.

I noticed the problem with `Unable to find remote helper for 'git+https'` and I'm working on a fix.
The problem is that when we retrieve the `package.json` [here](https://github.com/semantic-release/semantic-release/blob/caribou/lib/get-config.js#L64) it goes through [normalize-package-data](https://github.com/npm/normalize-package-data) which transform the URL to `git+https` format for some reason.

We check if the bare URL from `package.json` allow us to push [here](https://github.com/semantic-release/semantic-release/blob/caribou/lib/get-config.js#L54) and it it doesn't we transform the URL to add the auth part.

Because of this issue `verifyAuth(options.repositoryUrl, options.branch)` always return `false` so we always go into `getGitAuthUrl(options.repositoryUrl)` which transform the `git+https` URL into `https`.

So this problem is not the cause of `The push permission to the Git repository is required`. The only explanation I see for `The push permission to the Git repository is required` is a temporary issue on GitHub or Travis.

**Comment by richardson-trevor** [comment]
Sounds like you're thinking this might be a blip with either Travis or Github. Just wanted to chime in and say that we're on v15.0.3 and we've had the same `The push permission to the Git repository is required` issue come up multiple times today.

**Comment by pvdlg** [comment]
I'm not really what is happening...But it seems that the problem is intermittent.
Maybe it's an issue that happen on very specific cases and we can solve it. But we would need more data to figure out what's going on.

Something that would be help is to configure semantic-release in debug mode (with `--debug`) and see exactly what the error is when it happens.

**Comment by richardson-trevor** [comment]
Something else we noticed was the following: 
```
[Semantic release]: EMISSINGREPO The repository ainCompliance/react-components [secure]esn't exist.
```
whereas the real repository name should be `GainCompliance`.

**Comment by pvdlg** [comment]
That happens here: https://github.com/semantic-release/github/blob/7b6bc952e03e5215f6d2862b983431f71f457ccd/lib/verify.js#L77-L92

The owner/repo is determined from the repositoryUrl (which come from either the `repositoryUrl`, your `package.json`'s `repository` value or the `origin` remote of the cloned repo).
It's parsed there: https://github.com/semantic-release/github/blob/master/lib/verify.js#L71

I don't really see how the `G` could be truncated...

**Comment by richardson-trevor** [comment]
Alright, another update on this one. I added the `--debug` flag as recommended and get the following:
```
2018-03-14T13:34:41.492Z semantic-release:git Error: Command failed: git push --dry-run https:///ainCompliance/react-components.git HEAD:master
fatal: unable to access 'https:///ainCompliance/react-components.git/': Could not resolve host: https
```
Again the G appears missing for some reason. The piece I find interesting is that a few lines **above** that I get: 
```
2018-03-14T13:34:40.595Z semantic-release:git Error: Command failed: git push --dry-run GainCompliance/react-components HEAD:master
fatal: 'GainCompliance/react-components' [secure]es not appear to be a git repository
```
which clearly has the entire owner name, but without the `--debug` flag was the output that did **not** contain the owner name.

**Comment by pvdlg** [comment]
What is the value of the `repository` key in your `package.json`?

**Comment by travi** [comment]
Oh, ouch. That's unfortunate. 

I use the shorthand in almost all of my packages. Looks like I've got some updates ahead of me. 

Any chance supporting the shorthand is on the roadmap?

**Comment by richardson-trevor** [comment]
Ah, okay, that's the problem then. We have ours as shown in https://github.com/semantic-release/semantic-release/issues/695#issuecomment-372810602. We had a major version bump recently and this must've been supported on our previous version as we've got a number of projects setup this way that have been working. Appreciate the help!

**Comment by pvdlg** [comment]
I guess we could support the shorthand but only for one provider (probably GitHub) as there is no way to know if `owner/repo` should be expanded to `https://github.com/owner/repo`, `https://gitlab.com/owner/repo` or `https://custom.com/owner/repo`.

Also when the shorthand is used we would always communicate with `https` and never with `ssh`.

**Comment by pvdlg** [comment]
> Ah, okay, that's the problem then. We have ours as shown in #695 (comment). We had a major version bump recently and this must've been supported on our previous version as we've got a number of projects setup this way that have been working. Appreciate the help!

Ah sorry I missed than in the previous comment. Several version ago the Git tag were created via the GitHub API and are now created via the `git` CLI. Maybe that explain the problem appearing after an upgrade.

**Comment by travi** [comment]
> I guess we could support the shorthand but only for one provider (probably GitHub)

I think that is completely reasonable. As far as I know the shorthand is only supported for github on the npm side of things as well.

**Comment by richardson-trevor** [comment]
👍that would work from our end.

**Comment by travi** [comment]
so, i did forget some of the detail around the shorthand. it looks like each [can be supported](https://docs.npmjs.com/files/package.json#repository) (not necessarily saying they should be for semantic-release) with a prefix. the current docs dont seem to make it clear that the non-prefixed shorthand is only for github, which was my previous understanding.

**Comment by travi** [comment]
the [`npm install` docs](https://docs.npmjs.com/cli/install) do seem to further suggest that the non-prefixed shorthand is limited to github though:

> Note: if you do not include the @-symbol on your scope name, npm will interpret this as a GitHub repository instead, see below. Scopes names must also be followed by a slash.

**Comment by peyerluk** [comment]
I ran into this issue as well.

Trying out some older versions I noticed that starting with version 15.03 `npx semantic-release -d` asked me for my github login (prompt: 'Username for 'https://github.com':') even though `GH_TOKEN` was set. Previous versions did not do this.

But this only happened if my repository url in the `package.json` started with `https:`.

So I tested a bit and tried different values for repository.url in the `package.json`. 

These are the results:

- `https://github.com/upfrontIO/microschema` -> asks for username and password twice, but works.
- `//github.com/upfrontIO/microschema` -> works as expected
- `github.com/upfrontIO/microschema` -> I get 'The push permission to the Git repository is required.'
- `upfrontIO/microschema` -> I get 'The push permission to the Git repository is required.' (as expected from the previous comments)

Same tests with `15.1.2`:

- `https://github.com/upfrontIO/microschema` -> asks for username and password once, then 'The push permission to the Git repository is required.'.
- `//github.com/upfrontIO/microschema` -> works as expected
- `github.com/upfrontIO/microschema` -> 'The push permission to the Git repository is required.'
- `upfrontIO/microschema` -> asks for username and password once, then 'The push permission to the Git repository is required.'.


 ¯\\_(ツ)_/¯

**Comment by gr2m** [comment]
Thanks for the extended bug report! Could you please create a follow up issue? It will be easier to track for us. My issue was fixed so it looks like yours is slightly different.

[v15.0.3](https://github.com/semantic-release/semantic-release/releases/tag/v15.0.3) had a change related to the URLs, maybe that’s a good place to start digging: b0b4fc8

**Comment by peyerluk** [comment]
I create an issue:
The push permission to the Git repository is required v2 #708
