### ISSUE TITLE
Where the library store the credentials

### ISSUE THREAD

**Issue by ArielGueta** [semantic-release/semantic-release#700]
Thanks for this great library. 

From a security perspective, when you publish the library on `npm` you need the credentials, but where do you store them? 

Thanks.

**Comment by Guria** [comment]
It is in secured travis environment variables

**Comment by pvdlg** [comment]
Yes indeed. See https://semantic-release.gitbooks.io/semantic-release/content/docs/usage/ci-configuration.html#authentication

**Comment by ArielGueta** [comment]
Thanks!
