### ISSUE TITLE
git CLI still prompts user/password on CI

### ISSUE THREAD

**Issue by AVVS** [semantic-release/semantic-release#707]
Copy from https://github.com/semantic-release/semantic-release/pull/703#issuecomment-374290461

I'm not sure if its some sort of weirdness with env not being passed down with execa, but thats what I get when manually testing, notice that when I pass env variables manually, its all good, but process.env thats been modified inside the nodejs process is actually not being treated by execa anyhow. Also the timeout option itself doesnt trigger for some reason

<img width="591" alt="screen shot 2018-03-18 at 9 28 13 pm" src="https://user-images.githubusercontent.com/1713617/37578075-a29e81bc-2af3-11e8-985a-e1b1694e7826.png">

**Comment by pvdlg** [comment]
Thanks for the report. I found the problem, I set the environment variables after checking for the auth...which doesn't make any sense. I was working on another PR which change a few things regarding where the auth check is done and I got mixed up. My bad.

I'll push a fix shortly.

In addition it seems the `execa` timeout doesn't work when the shell is prompting the user.
Not sure if it's a bug of if it's expected. I'll investigate more.

**Comment by pvdlg** [comment]
@AVVS can you test with version `15.1.3` that is released on `@next`?
If everything works fine I'll release it on `@latest`.
Thanks

**Comment by AVVS** [comment]
@pvdlg I can, though I cant still see it on the `@next`, nor `@15.1.3` - has it been released yet?

**Comment by pvdlg** [comment]
Oops I was a bit too fast to post this coment. The release will be done in a few minutes.

**Comment by pvdlg** [comment]
IT seems Travis has an issue to download a Docker image we use for the test so it prevent the release to be done. It's probably going to take a few hours to be resolved....

**Comment by pvdlg** [comment]
Ok it's released now!

**Comment by AVVS** [comment]
can confirm it works
