### ISSUE TITLE
Rollback release on CI error? 

### ISSUE THREAD

**Issue by abalad** [semantic-release/semantic-release#712]
everyone, I need to do helping the following:

After the tests of my application I compile my libs and these libs depend on the  version inside the package.json.

So I'm not sure how to use the semantic release in this case.

1- Perform the tests, execute  the semantic release and compile the application. (But in this case my doubt is that the compilation fails. Will the semantic release rollback in the newly released release?)

2- Or Is there a way I can edit the package.json with semantic without it sending the release, then after the success of the compilation it send the release?

**Comment by gr2m** [comment]
It looks to me like the `verifyRelease` would be the right place, the new version is calculated (but not yet set in package.json): https://semantic-release.gitbooks.io/semantic-release/content/docs/usage/plugins.html#verifyrelease-plugin

**Comment by pvdlg** [comment]
If you are using npm you can find a solution in this FAQ: [How can I use a npm build script that requires the package.json’s version](https://semantic-release.gitbooks.io/semantic-release/content/docs/support/FAQ.html#how-can-i-use-a-npm-build-script-that-requires-the-packagejsons-version-).

In any case you probably want to run different jobs on your CI for your test and for the release. You can have for example a few jobs running the test only (you app will be built with version `0.0.0-dev` but it shouldn't be an issue for the tests) then a job to release. On the release job you can skip the tests (as it should run only if the test jobs are successful) and you can configure semantic-release to use the [exec](https://github.com/semantic-release/exec) to run your build script on the `prepare` step, after the npm plugin.

**Comment by abalad** [comment]
Thanks guys, I'll try to do it this way.

**Comment by pvdlg** [comment]
@abalad did you manage to configure semantic-release the way you want?

**Comment by abalad** [comment]
Not yet. Because I'm finishing other tasks, because I need to update the Node of my environment. But as soon as I can finish here,

**Comment by pvdlg** [comment]
I'm going to close this issue as its a support question and the additional information requested 3 weeks ago were not provided.

I you have questions regarding semantic-release usage and configuration please take a look at the documentation and use one of our support channels: https://github.com/semantic-release/semantic-release#get-help

If you find an actual bug or want to propose a new feature, please open a new issue following [our contribution guideline](https://github.com/semantic-release/semantic-release/blob/caribou/CONTRIBUTING.md).
