### ISSUE TITLE
Bug in get-last-release.js

### ISSUE THREAD

**Issue by klinki** [semantic-release/semantic-release#714]
## Current behavior
When there is a tag which doesn't have common ancestor with current HEAD, it fails.

(It fails basically any time, when `git merge-base --is-ancestor ref HEAD` returns non `0` code).

Error message:
```
[Semantic release]: An error occurred while running semantic-release: TypeError: Cannot destructure property `gitTag` of 'undefined' or 'null'.
    at module.exports (D:\work\personal\au-datetime-picker\node_modules\semantic-release\lib\get-last-release.js:44:31)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

## Expected behavior
It should not fail.

## Environment

- **semantic-release** version: 15.0.3

Problem is probably on this line: https://github.com/semantic-release/semantic-release/blob/caribou/lib/get-last-release.js#L44 when `isRefInHistory` returns `false` for all tags. Then probably something wrong comes out of `pLocate` and it is not possible to unstruct it into `const {gitTag, version}` objects.

**Comment by pvdlg** [comment]
Good catch! Thanks for reporting!
