### ISSUE TITLE
Not work with git version under 2.0

### ISSUE THREAD

**Issue by Drapegnik** [semantic-release/semantic-release#720]
# Bug report

## Current behavior

for `git@1.7.1`:

```
git merge-base --is-ancestor v2.5.3 HEAD
error: unknown option `is-ancestor'
```

## Expected behavior

I solved this problem by installing `git@2+`, but I lost a lot of time until I found out what's wrong. If there is no solution, it would be nice to add git version as requirement in docs.

## Environment

- **semantic-release** version: `13.1.3`
- CI environment: `TeamCity`
- Plugins used: `@semantic-release/git`

**Comment by gr2m** [comment]
good idea on adding the requirement to the docs. We could maybe also check for the git version and show a more helpful error message? 

Would you like to send a pull request for either or both?

**Comment by pvdlg** [comment]
Related to #559

Do you know what is the minimal Git version that we can support based on the git command we run in [lib/git.js](https://github.com/semantic-release/semantic-release/blob/caribou/lib/git.js) ?

**Comment by pvdlg** [comment]
Maybe we could also check the `git` bin is in the `PATH` with something like https://github.com/springernature/hasbin or similar.

**Comment by Drapegnik** [comment]
what I found:
* `git merge-base --is-ancestor`: `--is-ancestor` only from [`git@1.8`](https://git-scm.com/docs/git-merge-base/1.8.0)
* `git fetch --unshallow --tags`: `--unshallow` only from [`git@1.8.4`](https://git-scm.com/docs/git-fetch/1.8.4)
* `git remote get-url origin`: `get-url` only from [`git@2.7`](https://git-scm.com/docs/git-remote/2.7.0)
