### ISSUE TITLE
How to use with Angular - help wanted 

### ISSUE THREAD

**Issue by ArielGueta** [semantic-release/semantic-release#721]
In the Angular world, we are using the `angular-cli` to create third-party libraries. 

We have the following structure:

```
-package.json
- src
    -app
    -lib
       package.json

```
The library files are in the lib folder which has its own `package.json` file. 
When we want to build the library, we need to run from the application root ` package.json` the following command:
`npm run build:lib`

The above command will build the library and put it in a dist folder at the root project.

So, we have **one** repository that includes the application and the library. 

Can we use semantic release with this structure to publish the library?

**Comment by pvdlg** [comment]
I would like to invite you to read our [contribution guidelines](https://github.com/semantic-release/semantic-release/blob/caribou/CONTRIBUTING.md) and in particular the section about the [issue tracker](https://github.com/semantic-release/semantic-release/blob/caribou/CONTRIBUTING.md#using-the-issue-tracker):
> The issue tracker is the channel for [bug reports](#bug-report), [features requests](#feature-request) and [submitting pull requests](#submitting-a-pull-request) only. Please use the [Support](docs/support/README.md) and [Get help](README.md#get-help) sections for support, troubleshooting and questions.

If you currently run `npm publish` from the root folder there is nothing special to do. Just configure semantic-release normally as indicated in the doc.
If you run `npm publish` from the `lib` folder then just set the [pkgRoot](https://github.com/semantic-release/npm#options) option to `lib`.

**Comment by ArielGueta** [comment]
Thanks for the quick response.
The problem is that if I run `semantic-release setup` in my root project, it does the magic (  "version": "0.0.0-development" ) inside the **root** package.json. When I run the release I need semantic release to bump the `package.json` that inside the **lib** folder and not the one that at the project root.

**Comment by pvdlg** [comment]
How is the `package.json` inside `lib` generated and when?

**Comment by ArielGueta** [comment]
It always there. 
<img width="223" alt="screen shot 2018-03-27 at 8 21 50" src="https://user-images.githubusercontent.com/20522870/37948474-239d64d0-3199-11e8-9e63-cfef2a5fe766.png">

**Comment by pvdlg** [comment]
Have you tried with `pkgRoot` set to `lib`?
As mentioned before and in the doc:
> The version will be updated only in the package.json and npm-shrinkwrap.json within the pkgRoot directory.

Isn't the version in `lib/package.json` updated?

**Comment by pvdlg** [comment]
Also according to your screenshot you have a `package.json` in the root and another in `src/lib`. But you don't have a `lib` at the root of your project.

Also, the `package.json` used to deliver is typically generated by the build step (based on the root `package.json`) and is not checked in the repository.

**Comment by ArielGueta** [comment]
After running `npm run build:lib` you will have a `dist` folder that should be published to `npm`. The build folder will contain the `package.json` that inside the `lib` folder.

**Comment by ArielGueta** [comment]
<img width="240" alt="screen shot 2018-03-27 at 8 43 43" src="https://user-images.githubusercontent.com/20522870/37948911-f9f5df7a-319a-11e8-942d-8c7743579de2.png">

**Comment by pvdlg** [comment]
Then just set `pkgRoot` to whatever directory you want `npm publish` to be run from.

**Comment by ArielGueta** [comment]
OK, I am sorry, I know it's confusing, I will try it and let you know. I really appreciate your help. Thanks.

**Comment by pvdlg** [comment]
Thanks. Please let us know if it works.
Feel free to close the issue whenever everything works as you expect.

**Comment by ArielGueta** [comment]
So I successfully published the package, but the problem is that is not updated the correct `package.json` file. 

It is running the npm publish from the `dist` folder, but it's updating the root `package.json` and not the one in the `dist` folder. Any idea why?

**Comment by pvdlg** [comment]
As mentioned in my [first comment](https://github.com/semantic-release/semantic-release/issues/721#issuecomment-376399267) please use the proper support channels.
Thanks.

See #731. You have to configure `pkgRoot` for both `prepare` and `publish` steps.
