### ISSUE TITLE
3421

### ISSUE THREAD

**Issue by dannychot** [semantic-release/semantic-release#724]
## Environment

- **semantic-release** version: 
- CI environment: 
- Plugins used: 
- **semantic-release** configuration: 
- CI logs:

**Comment by gr2m** [comment]
Was that an accident?

**Comment by dannychot** [comment]
Its reel



Envoyé depuis mon téléphone intelligent Samsung Galaxy.


-------- Message d'origine --------
De : Gregor Martynus <notifications@github.com>
Date : 18-03-31 16 h 37 (GMT-05:00)
À : semantic-release/semantic-release <semantic-release@noreply.github.com>
Cc : dannychot <dannychot@hotmail.com>, Author <author@noreply.github.com>
Objet : Re: [semantic-release/semantic-release] 3421 (#724)


Closed #724<https://github.com/semantic-release/semantic-release/issues/724>.
