### ISSUE TITLE
Bug: Bot incorrectly comments after release on open/unresolved issues

### ISSUE THREAD

**Issue by rarkins** [semantic-release/semantic-release#726]
## Current behavior

semantic-release sometimes adds a release announcement to issues that aren't closed and aren't part of the master commit that triggered the release. It has happened twice in the past week or so but I forget when exactly the first time was. That's 2 errors out of maybe 20-30 successful releases.

## Expected behavior

semantic-release should only add comments to issues that are closed as part of the master commit(s). This is what usually happens.

## Environment

- **semantic-release** version: 15.1.4
- CI environment: Travis
- Plugins used: analyze-commits ?
- **semantic-release** configuration:
```
  "release": {
    "branch": "master",
    "tagFormat": "${version}",
    "analyzeCommits": {
      "preset": "angular",
      "releaseRules": [
        {
          "type": "docs",
          "scope": "readme.md",
          "release": "patch"
        },
        {
          "type": "refactor",
          "release": "patch"
        }
      ]
    }
  }
```
- CI logs: https://travis-ci.org/renovateapp/renovate/builds/361551194

```
[Semantic release]: Running semantic-release version 15.1.4
[Semantic release]: Load plugin verifyConditions from @semantic-release/npm
[Semantic release]: Load plugin verifyConditions from @semantic-release/github
[Semantic release]: Load plugin analyzeCommits from @semantic-release/commit-analyzer
[Semantic release]: Load plugin generateNotes from @semantic-release/release-notes-generator
[Semantic release]: Load plugin prepare from @semantic-release/npm
[Semantic release]: Load plugin publish from @semantic-release/npm
[Semantic release]: Load plugin publish from @semantic-release/github
[Semantic release]: Load plugin success from @semantic-release/github
[Semantic release]: Load plugin fail from @semantic-release/github
[Semantic release]: Run automated release from branch master
[Semantic release]: Call plugin verify-conditions
[Semantic release]: Verify authentication for registry https://registry.npmjs.org/
[Semantic release]: Wrote NPM_TOKEN to .npmrc.
[Semantic release]: Verify GitHub authentication
[Semantic release]: Found git tag 11.47.5 associated with version 11.47.5
[Semantic release]: Found 1 commits since last release
[Semantic release]: Call plugin analyze-commits
[Semantic release]: Analyzing commit: fix: add 5s sleep after automerge or restart (#1761)
This hopefully gives a better chance of GitHub being able to finish computing the new mergeability status, and reduces the chance of a race condition.
Closes #1617
[Semantic release]: The release type for the commit is patch
[Semantic release]: Analysis of 1 commits complete: patch release
[Semantic release]: The next release version is 11.47.6
[Semantic release]: Call plugin verify-release
[Semantic release]: Call plugin generateNotes
[Semantic release]: Call plugin prepare
[Semantic release]: Wrote version 11.47.6 to package.json
[Semantic release]: Create tag 11.47.6
[Semantic release]: Call plugin publish
[Semantic release]: Publishing version 11.47.6 to npm registry
+ renovate@11.47.6[Semantic release]: Published GitHub release: https://github.com/renovateapp/renovate/releases/tag/11.47.6
[Semantic release]: Added comment to issue #1761: https://github.com/renovateapp/renovate/pull/1761#issuecomment-378189324
[Semantic release]: Added comment to issue #1774: https://github.com/renovateapp/renovate/pull/1774#issuecomment-378189328
[Semantic release]: Added comment to issue #1080: https://github.com/renovateapp/renovate/issues/1080#issuecomment-378189332
[Semantic release]: Added comment to issue #1617: https://github.com/renovateapp/renovate/issues/1617#issuecomment-378189338
[Semantic release]: Published release: 11.47.6
```

Only 1617 and 1761 should have had comments added.

**Comment by pvdlg** [comment]
It seems it a GitHub search issue.
In the example you provided, semantic-release found the commit 101226db977d8fa85c50bcef78f18e39735f1081 and make a [GitHub issue search](https://developer.github.com/v3/search/#search-issues).

The search is equivalent to: https://github.com/renovateapp/renovate/issues?utf8=%E2%9C%93&q=101226db977d8fa85c50bcef78f18e39735f1081

As you see it returns `#1774` and `#1761`. `#1761` make sense, however `#1774` is returned by GitHub even if it's unrelated. semantic-release has no way to know the PR `#1774` is unrelated and just trust GitHub search.
Then `#1080` is also commented because `#1774` references it.

It seems this is due to this comment https://github.com/renovateapp/renovate/pull/1774#discussion_r178764564 from `#1774` that references some code from the commit `101226db977d8fa85c50bcef78f18e39735f1081`.

Unfortunately I don't think there is anything we can do in semantic-release as there is no way to tell the GitHub search to return only the PRs that are associated with the commits and not the PR that contains a comment referencing the unrelated commit.

**Comment by pvdlg** [comment]
One thing we could it to make sure we add a comment to only closed PRs/issues. That will not completely solve the problem, just avoid some instances.

**Comment by rarkins** [comment]
Thanks for looking at it so quickly. It would be great if you can verify that the PRs contain the release commits. Otherwise, it would also suit my situation if I could disabled comments for open issues. i.e. only comment if the issue is in state closed, because issues and PRs that are resolved by a commit to master should always be closed immediately - prior to semantic release - anyway.

**Comment by pvdlg** [comment]
Yep. I'm going to implement that shortly. Thanks for the detailed report!

**Comment by pvdlg** [comment]
@rarkins I opened the PR semantic-release/github#59 that should solve the problem.
Feel to review it!
