### ISSUE TITLE
semantic-release configuration file .releaserc precedence over package.json

### ISSUE THREAD

**Issue by tarazansafak** [semantic-release/semantic-release#729]
## Current behavior

Configurations defined in package.json's release blcok ignores and overrides the .releaserc config.

Current precedence:

`cli > package.json > .releaserc`

## Expected behavior

Precedence should be `cli > .releaserc > package.json` release block config. 

## Use case

I want to give freedom to developers to define publish root dir by setting it in package.json's release block via:

```
"release": {
 "pkgRoot": "dist"
},
```

And I still want to have control over semantic-release's behavior from .releaserc file which contains custom exec steps for publishing and other steps.

**Comment by pvdlg** [comment]
semantic-release doesn't handle the config file priority itself but relies on [cosmiconfig](https://github.com/davidtheclark/cosmiconfig) which search for the config file in the following order: `package.json`, `json` rc file, `yaml` rc file, `js` rc file.

It's also important to note that the config are not merged. The first config file found is used. The CLI options are a bit different as they are merged with the config file content and take precedence.

I don't think it make sense to change this order of priority or that it's relevant to care about the order in any way. Only one file is used and projects are not supposed to have multiple file (or `package.json` entry) doing the same thing.

If you want to have a generic config for all your projects and override some properties on each project then you should use a shareable config: https://semantic-release.gitbooks.io/semantic-release/content/docs/usage/configuration.html#extends
