### ISSUE TITLE
npm publish fails silently after upgrading from 12.x to 15.x 

### ISSUE THREAD

**Issue by dalelotts** [semantic-release/semantic-release#731]
# Bug report

## Current behavior

When updating from 12.x to 15.x  it appears that the npm plugin ignores the `dist` folder when writing the version.  I'm not 100% sure it's the npm plugin since this is happened when updating from 12.x to 15.x so I am filing this issue here. Sorry if this is the wrong place.

## Expected behavior
Version should be written to the `package.json` and `package-lock.json` files in the directory specified by `npmPublish`, not the `root` directory.

## Environment
Travis CI
- **semantic-release** version: 15.1.5
- CI environment: Travis
- Plugins used: GitHub and NPM
- **semantic-release** configuration:
See https://github.com/dalelotts/angular-bootstrap-datetimepicker/blob/master/package.json
```
"release": {
    "publish": [
      {
        "path": "@semantic-release/npm",
        "pkgRoot": "dist"
      },
      {
        "path": "@semantic-release/github",
        "assets": [
          "dist/*.zip",
          "dist/*.tar.gz"
        ]
      }
    ],
    "success": [
      "@semantic-release/github"
    ],
    "fail": [
      "@semantic-release/github"
    ]
  }
```
- CI logs: 
Silent failure with 15.x - https://travis-ci.org/dalelotts/angular-bootstrap-datetimepicker/builds/362427046
Successful build with 12.x - https://travis-ci.org/dalelotts/angular-bootstrap-datetimepicker/builds/362386044

**Comment by pvdlg** [comment]
This is because the update of the package.json version is done in the `prepare` step and you configured `pkgRoot` only in the `publish` step.
To solve that issue you should configure `pkgRoot` directly under `release` in your configuration so it would applied to both `prepare` and `publish`.

**Comment by dalelotts** [comment]
Thanks. Do I also need to update the assets for gitHub?

**Comment by pvdlg** [comment]
It should be necessary as it's used only in the `publish` step. But it doesn't hurt to put it directly under `release` and would simplify the config a bit.

**Comment by dalelotts** [comment]
I'm a bit confused by that comment...sorry, I'm slow today.

Is this the correct configuration:
```
"release": {
    "pkgRoot": "dist",
    "publish": [
      {
        "path": "@semantic-release/npm"
      },
      {
        "path": "@semantic-release/github",
        "assets": [
          "dist/*.zip",
          "dist/*.tar.gz"
        ]
      }
    ],
    "success": [
      "@semantic-release/github"
    ],
    "fail": [
      "@semantic-release/github"
    ]
  }
```

or this?

```
"release": {
    "pkgRoot": "dist",
    "publish": [
      {
        "path": "@semantic-release/npm"
      },
      {
        "path": "@semantic-release/github",
        "assets": [
          "*.zip",   <------ Change here - removed dist
          "*.tar.gz" <------ and here
        ]
      }
    ],
    "success": [
      "@semantic-release/github"
    ],
    "fail": [
      "@semantic-release/github"
    ]
  }
```

**Comment by pvdlg** [comment]
What I meant is you could configure like this:
```json
"release": {
    "pkgRoot": "dist",
     "assets": [
          "dist/*.zip",
          "dist/*.tar.gz"
     ]
  }
```

**Comment by dalelotts** [comment]
Ah, I see. That is much simpler!

I didn't get that at all from the current documentation. I'll take a stab at a PR for the documentation if you like.

**Comment by pvdlg** [comment]
That's explained here in the doc: https://github.com/semantic-release/semantic-release/blob/caribou/docs/usage/plugins.md#configuration

But maybe it's not clear enough. Feel free to propose improvements via issue/PR, it's always much appreciated!

**Comment by tylerjgarland** [comment]
@pvdlg , if you search in your link posted above, there's no reference to `pkgRoot`
