### ISSUE TITLE
Failed Travis/GitHub API request

### ISSUE THREAD

**Issue by kentcdodds** [semantic-release/semantic-release#733]
# Bug report

## Current behavior

In [this build's](https://travis-ci.org/kentcdodds/dom-testing-library/builds/363107202) after_success step:

```
[release] installing semantic-release
[release] npx: installed 372 in 13.118s
[release] running semantic-release
[release] semantic-release WARN invalid config loglevel="notice"
[release] semantic-release ERR! pre Unexpected token < in JSON at position 0 in "https://api.travis-ci.org/auth/github": 
[release] semantic-release ERR! pre <!DOCTYPE html>
[release] semantic-release ERR! pre <html>
[release] semantic-release ERR! pre   <head>
[release] semantic-release ERR! pre     <meta charset="utf-8">
semantic-release ERR! pre     <meta http-equ...
[release] echo installing semantic-release && npx -p semantic-release@8 -c 'echo running semantic-release && semantic-release pre && npm publish && semantic-release post' exited with code 1
```

## Expected behavior

I expect this to publish like all my projects :)

Due to #732, I attempted to set up semantic-release myself, but it looks like I may have missed a step. I noticed that `GIT_CREDENTIALS` in [the docs here](https://github.com/semantic-release/semantic-release/blob/caribou/docs/usage/ci-configuration.md), but I don't see that variable in my other project travis configurations. Do I need to add it? If so, why don't my other projects have it? Also, how do I set that up manually?

## Environment

- **semantic-release** version: 8
- CI environment: Travis
- Plugins used: None
- **semantic-release** configuration: I use `kcd-scripts` to run the release which runs it with `npx` as shown above. That code lives here: https://github.com/kentcdodds/kcd-scripts/blob/7dd1f6a0364b9640d29d5984f3d5287b51b7430c/src/scripts/travis-after-success.js#L31, the travis cofig for this project is [here](https://github.com/kentcdodds/dom-testing-library/blob/master/.travis.yml)
- CI logs: https://travis-ci.org/kentcdodds/dom-testing-library/builds/363107202

Thanks for any help you can offer!

**Comment by pvdlg** [comment]
The error seems to happen when we check the Travis job on which you are running. It something on Travis side that happens sometimes.
semantic-release 8 is ancient and I'm not sure we can help much with it. I would recommend to install the last version (`15.1.5` as of now). We now recommend to use Travis Build Stage. See [recipe](https://github.com/semantic-release/semantic-release/blob/caribou/docs/recipes/travis-build-stages.md). That will avoid all the issues related to call the Travis API.

All the information you see in the docs are related to the current version of semantic-release. So most of it is irrelevant of inaccurate if you are using version 8, as it's 7 major release behind.

Regarding your question about `GIT_CREDENTIALS`, as mentioned in the doc `The Git authentication can be set with one of the following environment variables`. So you can choose which authentication method you prefer. If you are using GitHub the most simple is to use `GH_TOKEN`. Just configure the token as before.
But if you use GitLab you should use `GL_TOKEN` and if you use neither (Bitbucket or a custom Git server) then use `GIT_CREDENTIALS `.
They have different name as they are used slightly differently:
- `GH_TOKEN` is used for Git (i.e. the `git` CLI) as basic auth and GitHub API authentication
- `GL_TOKEN` is used for Git (i.e. the `git` CLI) as basic auth prefixed with `gitlab-ci-token:` and GitLab API authentication
- `GIT_CREDENTIALS` is used for Git Authentication as basic auth

**Comment by kentcdodds** [comment]
I upgraded and things and it's working great! I love the new automatic comment feature. Wahoo! Thanks :)
