### ISSUE TITLE
commits with `fix` or `feat` not triggering new release

### ISSUE THREAD

**Issue by neekey** [semantic-release/semantic-release#734]
## Current behavior

I have some commits contains `fix()` and `feat()` but still not triggered a new release, the log:

## Expected behavior

should trigger a new release

## Environment

- **semantic-release** version: ^15.1.5
- CI environment: Travis
- Plugins used: @semantic-release/git
- **semantic-release** configuration: https://github.com/neekey/semantic-release-test-repo/blob/master/.releaserc
- CI logs:

```
> semantic-release-test-repo@1.0.0 semantic-release /home/travis/build/neekey/semantic-release-test-repo
> semantic-release
[Semantic release]: Running semantic-release version 15.1.5
[Semantic release]: Load plugin verifyConditions from @semantic-release/npm
[Semantic release]: Load plugin verifyConditions from @semantic-release/github
[Semantic release]: Load plugin analyzeCommits from @semantic-release/commit-analyzer
[Semantic release]: Load plugin generateNotes from @semantic-release/release-notes-generator
[Semantic release]: Load plugin prepare from @semantic-release/npm
[Semantic release]: Load plugin prepare from @semantic-release/git
[Semantic release]: Load plugin publish from @semantic-release/npm
[Semantic release]: Load plugin publish from @semantic-release/github
[Semantic release]: Load plugin success from @semantic-release/github
[Semantic release]: Load plugin fail from @semantic-release/github
[Semantic release]: Run automated release from branch master
[Semantic release]: Call plugin verify-conditions
[Semantic release]: Verify authentication for registry https://registry.npmjs.org/
[Semantic release]: Wrote NPM_TOKEN to .npmrc.
[Semantic release]: Verify GitHub authentication
[Semantic release]: Found git tag v1.0.0 associated with version 1.0.0
[Semantic release]: Found 5 commits since last release
[Semantic release]: Call plugin analyze-commits
[Semantic release]: Analyzing commit: Merge pull request #3 from neekey/release
fix(test): fix test 
feat(text): feat test
perf(pencil): remove graphiteWidth option
[Semantic release]: The commit should not trigger a release
[Semantic release]: Analyzing commit: update dummyjs2
[Semantic release]: The commit should not trigger a release
[Semantic release]: Analyzing commit: Merge pull request #2 from neekey/release
Release new version
[Semantic release]: The commit should not trigger a release
[Semantic release]: Analyzing commit: Merge pull request #1 from neekeyni/master
feat(test): test feature
[Semantic release]: The commit should not trigger a release
[Semantic release]: Analyzing commit: test feature
[Semantic release]: The commit should not trigger a release
[Semantic release]: Analysis of 5 commits complete: no release
[Semantic release]: There are no relevant changes, so no new version is released.
```

**Comment by neekey** [comment]
the CI build : https://travis-ci.org/neekey/semantic-release-test-repo/jobs/363661634

**Comment by pvdlg** [comment]
Looking at the commit on your master branch the `1.0.0` release none of that have a valid angular format:
- `Merge pull request #3 from neekey/release`
- `update dummyjs2`
- `Merge pull request #2 from neekey/release`
- `Merge pull request #1 from neekeyni/master`
- `test feature`

None of your commits since the `1.0.0` release contain `fix()` or `feat()` in their subject.

If you want semantic-release to analyze those commit you have to format them according to [Angular convention](https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#-git-commit-guidelines).

If you look at the convention you will see that `fix()`, `feat()`, etc... have to be in the subject not the body.

Feel free to comment further or re-open if you disagree.

**Comment by jdalrymple** [comment]
Sorta the same problem. Are the merge commit messages not included in the commit analysis? Example: https://travis-ci.org/jdalrymple/node-gitlab/jobs/502889768

**Comment by travi** [comment]
the only commits that is see in the logs that you link to that follow the commit convention are of type `chore()`, which does not trigger a release. which commits did you expect to trigger a release?

**Comment by jdalrymple** [comment]
```
[02:59:13] [semantic-release] › ℹ  Start step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[02:59:13] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: Merge pull request #284 from carlzogheib/feature/283
**feat: Add support for DELETE /projects/:id/fork**
[02:59:13] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[02:59:13] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: 283: Add support for DELETE /projects/:id/fork
[02:59:13] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
```

**Comment by travi** [comment]
`feat:` does not follow the default commit convention. please review the details linked to above to ensure the expected syntax is followed

**Comment by jdalrymple** [comment]
Ah, i understand now! must include the (). I was sure I was missing something, thank you!

**Comment by jdalrymple** [comment]
Just as another note from the OP. Their console shows:

```
[Semantic release]: Analyzing commit: Merge pull request #3 from neekey/release
fix(test): fix test 
feat(text): feat test
perf(pencil): remove graphiteWidth option
[Semantic release]: The commit should not trigger a release
[Semantic release]: Analyzing commit: update dummyjs2
```

Where:
```
fix(test): fix test 
feat(text): feat test
perf(pencil): remove graphiteWidth option
```

Is part of the body of the commit message. Just to clarify, the bodies of commit messages are not looked at by the commit analyzer?

**Comment by ldiego08** [comment]
@pvdlg having this same issue when using squash and merge. The default squash and merge format is:

```md
PR title (#3)

* feat: Adds something

Extended description

* refactor: Refactors something

Extended description
```

Do semantic release works with squash and merge commits? Or should everything be rebased?

**Comment by crimsonronin** [comment]
They should handle squashes as of https://github.com/semantic-release/commit-analyzer/pull/66

Im having a similar-ish problem, but I'm trying to figure out if it's config related or commit message related.

**Comment by travi** [comment]
That PR was closed without being merged

**Comment by emirot** [comment]
> [Semantic release]: Analyzing commit: Merge pull request #3 from neekey/release
> fix(test): fix test 
> feat(text): feat test
> perf(pencil): remove graphiteWidth option
> [Semantic release]: The commit should not trigger a release
> [Semantic release]: Analyzing commit: update dummyjs2

@jdalrymple  Looking at your comment I first thought that () were missing, how to trigger a release then?

**Comment by jdalrymple** [comment]
Honestly, it was such a while ago, i don't even remember :laughing:

**Comment by tiavina-mika** [comment]
@scastaldi how to do that?

**Comment by scastaldi** [comment]
@tiavina-mika This was a long time ago; currently, I am not using semantic release...
From what I remember
1. Setup Forward merge (do not use squash, because it removes the fix: message)
2. add Fix: to your message.  ex: fix: fixing bug

**Comment by valorant-dhruv** [comment]
What happened with me was that I was doing the commit message as feat:added a new feature. However this was not triggering a release. Turns out the solution is you must add a space between feat and your commit message. For example for feat: added a new feature it worked now.
