### ISSUE TITLE
Premature matching of git tags in multi-package environment

### ISSUE THREAD

**Issue by nathanbrock** [semantic-release/semantic-release#735]
## Current behavior

We're currently attempting to setup Semantic Release (SR) in a monorepo environment. We are using [lerna](https://github.com/lerna/lerna) to manage dependencies and using SR independently of any additional tools or plugins.

Given we have two similar named packages, `schema-validator` and `validator`, each with name-spaced tags `schema-validator/v.x.x.x` and `validator/v.x.x.x`, when attempting to use the tagFormat option `validator/${version}`, the version number for the `schema-validator` package is returned.

Having poked around in [get-last-release.js](https://github.com/semantic-release/semantic-release/blob/caribou/lib/get-last-release.js), it looks like this is being caused by the regexp being generated by lodash. Given there is no caret symbol at the start of the pattern, it is matching any string that matches `validator/(.+)` and returning the first match found. In our case, the version number for `schema-validator` and not `validator`.

Do you see any unexpected side-effects if we were to submit a pull-request updating the function to match the given tagFormat from the _start_ of the git tag string? 

## Expected behavior

The version number for 'validator' to be returned, and not that of 'schema-validator'.

## Environment

- **semantic-release** version: 15.1.5
- CI environment: None
- Plugins used: N/a
- **semantic-release** configuration: 
```
{
  "publish": [],
  "verifyConditions": ["@semantic-release/npm"],
  "success": [],
  "fail": [],
  "prepare": ["@semantic-release/npm"],
  "noCi": true,
  "dryRun": false,
  "tagFormat": "validator/${version}"
}
```
- CI logs: 
```
[Semantic release]: Running semantic-release version 15.1.5
[Semantic release]: Load plugin verifyConditions from @semantic-release/npm in shareable config /<PATH>/semantic-release-config/releaserc.json
[Semantic release]: Load plugin analyzeCommits from @semantic-release/commit-analyzer
[Semantic release]: Load plugin generateNotes from @semantic-release/release-notes-generator
[Semantic release]: Load plugin prepare from @semantic-release/npm in shareable config /<PATH>/semantic-release-config/releaserc.json
[Semantic release]: Run automated release from branch package-versioning
[Semantic release]: Call plugin verify-conditions
[Semantic release]: Verify authentication for registry https://registry.npmjs.org/
[Semantic release]: Found git tag schema-validator/v0.12.7 associated with version v0.12.7
# Added comment into index.js to output last release details
last release { gitHead: 'f2051794df71319fad419fea063a84ed75b1ae1c',
  gitTag: 'schema-validator/v0.12.7',
  version: 'v0.12.7' }
...
```

p.s. Many thanks for Semantic Release, it's a fantastic tool!

**Comment by pvdlg** [comment]
That shouldn't be a problem.
The code that build the regexp in `get-last-release.js` should be something like that:
```js
const tagRegexp = `^${escapeRegExp(template(tagFormat)({version: ' '}))}`.replace(' ', '(.+)');
```

Can you also add a test that verify the use case you mentioned?

I would also like to mention that semantic-release does not support monorepo at this point. See #193.
There is solution out there be as explain in #193 they don't cover every case of a monorepo.
So the semantic-release maintainer team will not offer support for monorepo beside what's outlined in #193, which is mainly working with the community to find the right design that would fully support monorepo.
