### ISSUE TITLE
angular 4 is not installing in windows 10 inspite of having latest version of npm  and setting path in environmental variables

### ISSUE THREAD

**Issue by yashasvimm** [semantic-release/semantic-release#739]
## Environment

- **semantic-release** version: 
- CI environment: 
- Plugins used: 
- **semantic-release** configuration: 
- CI logs: 

## Third-party documentation

npm ERR! file C:\WINDOWS\system32\cmd.exe;
npm ERR! path C:\WINDOWS\system32\cmd.exe;
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn C:\WINDOWS\system32\cmd.exe;
npm ERR! uglifyjs-webpack-plugin@0.4.6 postinstall: `node lib/post_install.js`
npm ERR! spawn C:\WINDOWS\system32\cmd.exe; ENOENT
npm ERR!
npm ERR! Failed at the uglifyjs-webpack-plugin@0.4.6 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by pvdlg** [comment]
It seems the problem happens with `uglifyjs-webpack-plugin` postinstall that can't run `node lib/post_install.js`.

Did you mean to open this issue to another repo? This is not related to semantic-release in any way apparently.

If it's actually related to semantic-release, please reopen the issue and explain where semantic-release is involve.
