### ISSUE TITLE
Errors when generating release from Travis-CI

### ISSUE THREAD

**Issue by schalkneethling** [semantic-release/semantic-release#740]
## Current behavior

Ran build via Travis-CI after merging a pull request to master. Configuration was done via the CLI and I can confirm that the tokens was generated on NPM and Github and copied to Travis. I consistently run into the following error:

[Semantic release]: Verify GitHub authentication
[Semantic release]: EMISSINGREPO The repository git@github.com:mdn/bob doesn't exist.
The semantic-release repositoryUrl option must refer to your GitHub repository. The repository must be accessible with the GitHub API (https://developer.github.com/v3).
By default the repositoryUrl option is retrieved from the repository property of your package.json or the git origin url (https://git-scm.com/book/en/v2/Git-Basics-Working-with-Remotes) of the repository cloned by your CI environment.
If you are using GitHub Enterprise (https://enterprise.github.com) please make sure to configure the githubUrl and githubApiPathPrefix options (https://github.com/semantic-release/github/blob/master/README.md#options).
[Semantic release]: EGITNOPERMISSION The push permission to the Git repository is required.
semantic-release cannot push the version tag to the branch master on remote Git repository.
Please refer to the authentication configuration documentation (https://github.com/semantic-release/semantic-release/blob/caribou/docs/usage/ci-configuration.md#authentication) to configure the Git credentials on your CI environment.
{ SemanticReleaseError: The push permission to the Git repository is required.
    at module.exports (/home/travis/build/mdn/bob/node_modules/semantic-release/lib/get-error.js:6:10)
    at run (/home/travis/build/mdn/bob/node_modules/semantic-release/index.js:51:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  name: 'SemanticReleaseError',
  code: 'EGITNOPERMISSION',
  details: '**semantic-release** cannot push the version tag to the branch `master` on remote Git repository.\n\nPlease refer to the [authentication configuration documentation](https://github.com/semantic-release/semantic-release/blob/caribou/docs/usage/ci-configuration.md#authentication) to configure the Git credentials on your CI environment.',
  semanticRelease: true }

## Expected behavior

It should tag and release the repo on Github and NPM

## Environment

- **semantic-release** version: ^15.1.5
- CI environment: Travis-CI
- Plugins used: defaults
- **semantic-release** configuration: used default, and config was done via cli
- CI logs: https://travis-ci.org/mdn/bob/builds/364609477

**Comment by pvdlg** [comment]
This is because your repository URL in your `package.json` is configured to `https:git@github.com:mdn/bob.git` which is an invalid URL.
A URL cannot be both `https` and `git`.
You should configure `https://github.com:mdn/bob.git` or `git@github.com:mdn/bob.git`.

**Comment by schalkneethling** [comment]
@pvdlg - Ok so the `EMISSINGREPO` is resolved but, I am still getting `EGITNOPERMISSION The push permission to the Git repository is required`

The token was created by the CLI on Github and also added to Travis-CI, here is how the rights for the token is configured:

<img width="753" alt="screen shot 2018-04-11 at 09 49 31" src="https://user-images.githubusercontent.com/10350960/38603447-f2bdb334-3d6d-11e8-9ba7-f31ae33f5ea2.png">

Also, my user has admin rights to the repo in question so, not sure what else needs changing to enable semantic-release to push to the repo on Github.

**Comment by schalkneethling** [comment]
Here is the issue that was created by semantic-release:
https://github.com/mdn/bob/issues/16

**Comment by schalkneethling** [comment]
Just checked the job on Travis-CI and it is exporting the credentials so, they should be available to semantic-release:

```
Setting environment variables from repository settings
$ export GH_TOKEN=[secure]
$ export NPM_TOKEN=[secure]
```

**Comment by pvdlg** [comment]
Your repository URL is still incorrect. `https://github.com:mdn/bob.git` is not a valid URL.
It should be `https://github.com/mdn/bob.git`.
Just copy/paste the URL in your browser when you are on your repo GitHub page to avoid mistakes.

**Comment by schalkneethling** [comment]
🤦‍♂️ Oh my word! Man, I should be more attentive. Thanks again @pvdlg 🍰 ☕️

**Comment by pvdlg** [comment]
Can this issue be closed then?

**Comment by schalkneethling** [comment]
@pvdlg Yup, it looks like this is all good now. Thanks so much for your assistance.
