### ISSUE TITLE
Deploying build artifact to github

### ISSUE THREAD

**Issue by simlu** [semantic-release/semantic-release#746]
I'm trying to generate and publish a build artifact for github.

I've successfully disabled npm publishing by using the config
```json
{
  "npmPublish": false,
  "publish": [
    {
      "path": "@semantic-release/github"
    }
  ]
}
```

However github just does a release with the source code. Is there a way to push the build artifact to github (instead of npm)?

**Comment by pvdlg** [comment]
You can find all the explanation, configuration and example in GitHub plugin doc: https://github.com/semantic-release/github#assets

Is there something not clear in the doc that we can improve?

**Comment by simlu** [comment]
Honestly I thought the npm build artifact should be uploaded to github by default. Ideally there would be an option for that.

If I understand correctly we need to create and define artifacts manually for now?

So how about the following config:
```json
{
  "npmPublish": false,
  "publish": [
    {
      "path": "@semantic-release/github",
      "assets": [
        {
          "path": "release.tar.gz",
          "label": "Release Artifact"
        }
      ]
    }
  ]
}
``` 

and then build the artifacts as 

```json
{
  "scripts": {
      "clean-build": "...",
      "build-artifact": "npm run clean-build && tar -zxvf $(npm pack) && rm *-0.0.0-development.tgz && tar -zcvf release.tar.gz package/* && rm -rf package",
      "semantic-release": "npm run build-artifact && npm run clean-build && npx semantic-release"
  }
}
```

Does that sound about right?

**Comment by pvdlg** [comment]
> Honestly I thought the npm build artifact should be uploaded to github by default. Ideally there would be an option for that.

Plugins are independents, so the github plugin doesn't know if you are releasing on npm or somewhere else. semantic-release support a lot of workflow, project type, package manager registry etc... Every users have a different workflow, produces assets with different name in different folder, some want to upload to GitHub, some don't. At that point there is no point to maintain a state shared by different plugins, so there is no way for the github plugin (or semantic-release core) to know if an npm `tar.gz` was create and where it was created.

> If I understand correctly we need to create and define artifacts manually for now?

semantic-release is a release tool not a build tool. It has never been and I don't think it will ever be in the scope of semantic-release to be a build tool, to compile code or generate artifact.
There is dozen of tools doing way better than we could: `npm`, `gulp`, `grunt` among many other.

> Does that sound about right?

I guess but I didn't look in detail. As mentioned in the [Contribution guideline](https://github.com/semantic-release/semantic-release/blob/caribou/CONTRIBUTING.md#using-the-issue-tracker) the issue tracker is not for support.
You can find various ways to get support [here](https://github.com/semantic-release/semantic-release#get-help).

**Comment by simlu** [comment]
@pvdlg Thank you very much for your detailed reply! This cleared up a lot for me!

For anyone looking at this in the future, the above works as expected (you might want to get rid of the top level package folder though in the tar.gz).

Closing this since resolved. Cheers!
