### ISSUE TITLE
Fails on NPM publish with valid token

### ISSUE THREAD

**Issue by schalkneethling** [semantic-release/semantic-release#747]
## Current behavior

When running semantic release, a new tag is written to Github and the release is published but, the step to publish to NPM fails with

```
[Semantic release]: Publishing version 1.0.2 to npm registry
[Semantic release]: An error occurred while running semantic-release: { Error: Command failed: npm publish ./. --registry https://registry.npmjs.org/
npm ERR! publish Failed PUT 403
npm ERR! code E403
npm ERR! You do not have permission to publish "bob". Are you logged in as the correct user? : bob
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2018-04-18T08_25_57_953Z-debug.log
```

I am using tokens for both Github and NPM configured as environmental variables in Travis-CI.

One question though, does the last line of the error suggest that the user being used for NPM is bob? That is the repo name so, if that is the case, I am not sure how it is inferring that from the token.

Thank you in advance for your assistance.

## Expected behavior

It should publish to Github and NPM successfully.

## Environment

- **semantic-release** version: ^15.1.5
- CI environment: Travis-CI
- Plugins used: Just the defaults
- **semantic-release** configuration: default
- CI logs: https://travis-ci.org/mdn/bob/builds/368034044

**Comment by pvdlg** [comment]
This is not a semantic-release issue. It's related to npm.
See https://github.com/npm/npm/issues/8561

It's probably because the package name you are trying to publish has already been used by someone else.

The npm error message is not really explicit though... It would be a good idea to add that in [troubleshooting](https://github.com/semantic-release/semantic-release/blob/caribou/docs/support/troubleshooting.md)

**Comment by boennemann** [comment]
> It's probably because the package name you are trying to publish has already been used by someone else.

Note that also publishes fail if the names are too similar. E.g. if bob.js exists, you can't publish bobjs

**Comment by schalkneethling** [comment]
Thanks so much for the feedback. Change the name I must ;) Well slightly, but not to slightly.

**Comment by schalkneethling** [comment]
And it works! Thanks so much for the awesome tool and the exceptional support! https://www.npmjs.com/package/mdn-bob
