### ISSUE TITLE
Bower Support for libraries

### ISSUE THREAD

**Issue by kentcdodds** [semantic-release/semantic-release#75]
I just realized that (if I'm not mistaken) this fails to push the built version of the library to the tagged commit. This is not good for people who use my library via `bower` (as much as I hate it). Is there any way that as part of the post action, semantic-release could commit whatever's changed (built files) and push those up to the tag on the repository? This way people using bower can get my library's built files.

**Comment by gr2m** [comment]
Could the build files live in a separate branch? Then you could use https://www.npmjs.com/package/gh-pages-deploy for it. We use it do push docs after a deploy, e.g. for https://github.com/hoodiehq/pouchdb-hoodie-api, see https://github.com/hoodiehq/pouchdb-hoodie-api/blob/master/.travis.yml#L24

**Comment by kentcdodds** [comment]
Hi @gr2m. I want the built files to live in the tagged version because that's how bower works. It doesn't make a difference what branch it's in.

**Comment by gr2m** [comment]
Then you can achieve that with

1. On traves in after_success, run the build task which builds into `/dist` or similar
2. Copy / create bower.json file in `dist/` folder
3. Use gh-pages-deploy to push contents of `/dist` folder to a `dist` branch on GitHub
4. Point bower to the `dist` branch

That should work, right?

**Comment by kentcdodds** [comment]
Seems like it should. How do I authorize travis to commit to my repo?

**Comment by gr2m** [comment]
Travis already has the github token, so we use a smal script for that:
https://github.com/hoodiehq/pouchdb-hoodie-api/blob/master/bin/authorize-push.js

and run it in [predeploydocs](https://github.com/hoodiehq/pouchdb-hoodie-api/blob/master/package.json#L56)

**Comment by kentcdodds** [comment]
That looks awesome! Mind open sourcing that so I (and others) can just npm install?

**Comment by gr2m** [comment]
Not at all! I'll leave it to @boennemann, just to make sure there is no simpler way. Also it's his work, so honor to whom honor is due. Okay for you to copy & paste this for the time being?

**Comment by kentcdodds** [comment]
no problem. I'll let you know how it goes :-)

**Comment by kentcdodds** [comment]
Alright, so I've gotten something that works really well. Here's my `semantic-release` process: https://github.com/formly-js/angular-formly/blob/master/package.json#L32

```
semantic-release pre && npm run build && npm publish && semantic-release post && npm run publish:latest
```

Note: I need to run the build after `pre` because my build depends on the `package.json` `version` because I publish the version as part of my library (similar to what angular or react do).

Then the `publish:latest` is [this script](https://github.com/formly-js/angular-formly/blob/master/scripts/publish-latest.sh) which essentially:

1. checks out the `latest` branch
2. merges master
3. adds the `dist` directory (the generated files needed for bower)
4. commits it with the version as the message
5. Moves the tag that `semantic-release` just created
6. Force pushes (so the tag gets moved to the commit with the `dist` directory).

However, I think this is causing some odd behavior. If you look at my [releases](https://github.com/formly-js/angular-formly/releases) you'll see that the changelog is getting stacked. Each release has the changes from the previous releases as well as its own. If you look at the output from the [travis build](https://travis-ci.org/formly-js/angular-formly) you'll see that semantic-release is: "Generating changelog from v6.24.21 to HEAD..." every single release.

Any tips on how I could accomplish what I'm trying to do, but fix the changelog issue are appreciated!

**Comment by kentcdodds** [comment]
So I've changed a few things and now we no longer need to move the release tag (which is great). Here's how things look now:

```
semantic-release pre && npm run build && npm publish && npm run publish:latest && semantic-release post
```

So `publish:latest` has moved in front of `semantic-release post` and here's what it's doing now:

1. checks out the `latest` branch
2. merges `master`
3. adds the `dist` directory (the generated files needed for bower)
4. commits it with the version as the message
5. Force pushes `latest` (in case there is some kind of divergence for some reason).

All that's changed is I'm no longer moving the tag because it doesn't exist yet. This seems to work great. The only problem is that it's still generating the changelog from `6.24.21` so every release the changelog gets bigger and bigger filled with stuff that's been released before.

**Comment by kentcdodds** [comment]
I think I've found the problem. When I run `git describe --tags --abbrev=0` in my repo, I get back `v6.24.21`. I'm not sure why it's not showing me the actual latest. Any tips appreciated!

**Comment by kentcdodds** [comment]
I figured out that because I'm actually committing my tags on the `latest` branch, I need to change the branch to `latest` before `conventional-changelog` runs `git describe --tags --abbrev=0`. Still working out a few kinks. Hopefully I'll be able to create a plugin to suit this use case better in the future when I'm done :-)

**Comment by kentcdodds** [comment]
Alrighty! I've got it. It's kinda crazy, but it totally works. I'm all set!

**Comment by apowers313** [comment]
hi @kentcdodds -- I was just trying to figure out how to get `semantic-release` to push to Bower when I came across this post. Do you have some code you can share?

**Comment by kentcdodds** [comment]
Sure, if you look at my comments, I describe exactly what my code does and where it is. You need to alter the [`semantic-release`](https://github.com/formly-js/angular-formly/blob/master/package.json#L32) script slightly and you'll need to have [a script](https://github.com/formly-js/angular-formly/blob/master/scripts/publish-latest.sh) which commits built files and pushes them to a branch (I use `latest`). In addition, you'll need to either re-use your `GH_TOKEN` on [this line](https://github.com/formly-js/angular-formly/blob/master/scripts/publish-latest.sh#L20) or do what I did and have a `BOT_GH_TOKEN` which is a token for a bot account.

I'm hoping to make this a plugin eventually. Good luck!

**Comment by tlvince** [comment]
I've been using a similar script for sometime now and whilst it's a little hacky, it works. I've written up my workflow in [tlvince/tlvince-semantic-release-push-dist](https://github.com/tlvince/tlvince-semantic-release-push-dist), but I'd also love to see a plugin that implements this more robustly.

**Comment by kentcdodds** [comment]
That is quite similar. I'm working on something right now. Hopefully I'll
have it before too long.

-Kent C. Dodds

**Comment by kentcdodds** [comment]
Alrighty, I've open sourced my script. It seems to work great :-) http://npm.im/publish-latest

**Comment by juristr** [comment]
I have the exact same problem with semantic release & bower. Used to have the dist folder in master and to compile it just before creating a new release (really tedious work..).

@kentcdodds Ok, so if I got you correctly, Travis is listening for changes on master, builds etc, uses semantic-release and your script to publish the dist files to `latest` which you then tag. You cannot push the dist to master 'cause that would end in an infinite loop :smile:. Did I get that correctly?

**Comment by juristr** [comment]
@kentcdodds Hmm..ok. Set it up. Publishing to npm etc works. Tried to hook in your `publish-latest` plugin, but it failed. Any idea why: https://travis-ci.org/Swimlane/angular-model-factory/builds/82403298

```
...
> angular-model-factory@1.0.1 postpublish .
> publish-latest
stderr: fatal: 'travis/temp' does not appear to be a git repository
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
fatal: Cannot update paths and switch to branch 'dist' at the same time.
Did you intend to checkout 'package.json' which can not be resolved as commit?
stdout: > PL >> setting global git config: latest,
> PL >> running git config --global user.email
> PL >> running git config --global user.name "latest"
> PL >> setting remote
> PL >> running git remote set-url origin travis/temp
> PL >> checking for dist package.json branch
> PL >> dist package.json does not exist on remote... creating it...
> PL >> running git checkout -b dist package.json
...
```

Any idea?

**Comment by kentcdodds** [comment]
@juristr, you'd be fine to have a `dist` in master. Travis just runs the build as normal and it simply commits your built files and pushes them to `latest`. It explicitly adds `dist` and `package.json` (with `-f` so it works even if they're `.gitignore`d) (the files it adds is configurable). Glad you got it working!

Oh, also, I recommend you do [this](https://egghead.io/lessons/javascript-how-to-write-a-javascript-library-limit-built-branches-on-travis) also, to prevent building the `latest` branch.

**Comment by juristr** [comment]
> Oh, also, I recommend you do this also, to prevent building the latest branch.

@kentcdodds :+1: thx for the hint.

**Comment by tlvince** [comment]
For reference, I recently packaged up two other approaches:

* [publish-repo](https://www.npmjs.com/package/publish-repo): pushes dist to a separate repository
* [publish-dist](https://www.npmjs.com/package/publish-dist): commits and pushes dist to master if the last commit was not made by itself

**Comment by boennemann** [comment]
Wow these tools are all very nice :+1: Would someone mind adding them to the readme via a PR?

**Comment by kentcdodds** [comment]
Huh... @tlvince is there a reason you didn't just use [`publish-latest`](http://npm.im/publish-latest)? You know you can publish to a separate repository, to master, OR to the `latest` branch with it right?

**Comment by tlvince** [comment]
@kentcdodds NIH? :sweat_smile: In all seriousness, I didn't realise publish-latest was that flexible; I thought it only concerned itself with one scenario (publishing to a branch). I guess I didn't look very hard! (I'd also been using the scripts in different projects for quite some time before and wanted to consolidate them).

**Comment by kentcdodds** [comment]
That's my bad for not calling that out in the documentation [well enough](https://www.npmjs.com/package/publish-latest#cli-options).
