### ISSUE TITLE
Can't publish on npm

### ISSUE THREAD

**Issue by zlithgow** [semantic-release/semantic-release#750]
I've been using semantic-release recently on the new github repo I've setup. 
The problem is, we used to use BitBucket (for our commits/push) and do all our "npm publish" manually. Now that I'm on the GitHub repo, I don't have all the commits history from the BitBucket repo, so when I try to do "npm publish" via semantic-release, I get this error:

[Semantic release]: An error occurred while running semantic-release: { Error: Command failed: npm publish ./. --registry https://registry.npmjs.org/
npm ERR! publish Failed PUT 403
npm ERR! code E403
npm ERR! You cannot publish over the previously published versions: 1.0.0. : workwell

Which I totally understand because it does already exist (our current version on npm is 1.0.50). So how do I make semantic-release realize that it should be publishing version 1.0.51 ?

Thanks !

**Comment by pvdlg** [comment]
semantic-release use git tags to determine the last version present in the repo.

If you migrate from BitBucket to GitHub the proper solution is to migrate the complete repo, including all commits and tags. Loosing your git history will cause you several issues down the line and make maintenance of your project harder.

If you don't to do that for some reason then you have to create a tag with the last version released to the corresponding commit. semantic-release will use this tag to figure out the commit made between the last released (marked by the tag) and now.

**Comment by zlithgow** [comment]
Ok I see ! Thanks a lot !
