### ISSUE TITLE
GitHub Pages - release based on other branch

### ISSUE THREAD

**Issue by BartvdWaerden** [semantic-release/semantic-release#755]
## New feature motivation
Currently I'm using Github Pages for hosting my person website and User pages _must_ be built from the `master` branch. This branch contains compiled files, which I'm not interested in for my releases. I would like to have a release based on my `source` branch.

Currently my workflow is a follows: 

1. Developing a `feature` in a feature branch
2. Merge in to my `source` branch (via a Pull Request)
3. A build it triggered to the `master` branch (via Travis)
4. Sematic Release makes a release based on `master` branch

## New feature description

Preferred workflow: 
1. Developing a `feature` in a feature branch
2. Merge in to my `source` branch (via a Pull Request)
3. A build it triggered to the `master` branch (via Travis)
4. Sematic Release makes a release based on **`source`** branch

Please let me know if I'm missing something, our you need more info 😄

**Comment by gr2m** [comment]
Hey I’m sorry I don’t yet understand what you need exactly, and why?

If I understand correctly, you want the release build on Travis to be triggered by the a commit to a master branch. But then in that build you want semantic-release to check out the `source` branch and do its release from there? 

You can configure a custom branch for  semantic-release, e.g. set it to `"source"`, but the workflow you are looking for is not. I think your best option is a more common workflow, I head about your setup for the first time

**Comment by BartvdWaerden** [comment]
Hi thank you for your fast reply, really appreciate it!

Currently I'm committing/merging to my `source` branch using Commitizen using the cz-conventional-changelog method. When I merge a feature into the `source` branch Travis runs a build and commits and pushes compiled/optimized code to the `master` branch.  These commits by Travis are not following the cz-conventional-changelog, so no release gets triggered. 

What I would like is Semantic release to release every-time a merge into my `source` branch.

Maybe I'm using it totally wrong, and I should change my workflow. Please feel free to close this issue if you think that is the case.

**Comment by pvdlg** [comment]
One of the goal of using commit convention is that it allow you to have a clean and informative git history. I'm not sure I understand your workflow, nor what problem you try to solve but it seems you end up with a `master` branch that doesn't contains the conventional commits.

In addition, usually the `master` branch reflect the last version of the software released.

I don't really understand why you do this complex workflow and there must be reasons that I am missing. But I would propose the following workflow instead:
- Write conventional commits for your PRs/feature branches
- Merge your PRs/feature branches to `master`
- Run a Travis job on `master` and run semantic-release
- Use a `prePublishOnly` npm script to run your script that compile/optimize
- Use [@semantic-release/git](https://github.com/semantic-release/git) to push to compiled code code to the repo (in a dist folder for example)

**Comment by BartvdWaerden** [comment]
Thank you very much for your help guys! I've solved my problem using:
`  "release": {
    "branch": "source"
  }` in my `package.json`

Learned a bunch and I will adjust my workflow in the near future!
