### ISSUE TITLE
How to major release?

### ISSUE THREAD

**Issue by ethanneff** [semantic-release/semantic-release#757]
## Problem

How do I make a major release happen? I tried the following without success:
<img width="296" alt="screen shot 2018-04-27 at 1 39 56 pm" src="https://user-images.githubusercontent.com/2933593/39384091-7fa84eee-4a20-11e8-933e-ea8e7cfe2f51.png">
https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking/commit/7a4cf3895ce26b6a85c805e67212289648d16493

## Current behavior

2.5.26 -> 2.7.0

## Expected behavior

2.5.26 -> 3.0.0

## Environment

- **semantic-release version** 15.1.7
- **CI environment** travis
- **semantic-release configuration**  
```
"release": {
    "verifyConditions": [
      "@semantic-release/changelog",
      "@semantic-release/github",
      "@semantic-release/git",
      "@semantic-release/npm"
    ],
    "verifyRelease": [
      {
        "path": "@semantic-release/exec",
        "cmd": "node ./src/scripts/npm/updateNpmVersion"
      }
    ],
    "prepare": [
      {
        "path": "@semantic-release/changelog",
        "changelogFile": "CHANGELOG.md"
      },
      "@semantic-release/git"
    ],
    "publish": [
      "@semantic-release/github",
      "@semantic-release/npm"
    ]
  },
  "commitlint": {
    "extends": [
      "@commitlint/config-conventional"
    ]
  },
  "devDependencies": {
    "@commitlint/cli": "^6.1.3",
    "@commitlint/config-conventional": "^6.1.3",
    "@semantic-release/changelog": "^2.0.1",
    "@semantic-release/exec": "^2.2.3",
    "@semantic-release/git": "^4.0.2",
    "@semantic-release/github": "^4.2.11",
    "@semantic-release/npm": "^3.2.4"
},
"scripts": {
    "semantic-release": "semantic-release"
},
```

**Comment by gr2m** [comment]
It’s `BREAKING CHANGE:`, not `BREAKING:`. You can customise the conventions to your preference, see https://semantic-release.gitbooks.io/semantic-release/#commit-message-format

**Comment by ethanneff** [comment]
I was referencing `parserOpts` from https://github.com/semantic-release/commit-analyzer#options. I'll try `BREAKING CHANGE` next time to see what happens.
