### ISSUE TITLE
EGITNOPERMISSION git push fails with GIT_CREDENTIALS bitbucket.org 

### ISSUE THREAD

**Issue by botcheddevil** [semantic-release/semantic-release#761]
# Bug report

## Current behavior

git push fails with credentials message `[Semantic release]: EGITNOPERMISSION The push permission to the Git repository is required.`

Based on the documentation mentioned [here](https://github.com/semantic-release/semantic-release/blob/caribou/docs/usage/ci-configuration.md#authentication):

> GIT_CREDENTIALS can be the Git username and password in the format <username>:<password> or a token for certain Git providers like Bitbucket.

`GIT_CREDENTIALS` has been set as environment var with format `<username>:<password>`

### Note: 

Tried the following manually 
`git push --dry-run https://<username>:<password>@bitbucket.org/<owner>/release-test.git HEAD:master` and it works fine.

### Possible Issue

https://github.com/IonicaBizau/git-url-parse/blob/ff3919e950fa6cb74de99487ea5578dc9e1dd633/lib/index.js#L155-L159

```Javascript
        case "https":
            const auth = obj.token
              ? buildToken(obj) : obj.user && (obj.protocols.includes('http') || obj.protocols.includes('https'))
                ? `${obj.user}@` : "";
            return `${type}://${auth}${obj.resource}${port}/${obj.full_name}${maybeGitSuffix}`;
```

If `obj.token` (which is been populated from `GIT_CREDENTIALS` ) is set, this will buildToken of format `x-token-auth:<username>:<password>`, which is invalid.

https://github.com/IonicaBizau/git-url-parse/blob/ff3919e950fa6cb74de99487ea5578dc9e1dd633/lib/index.js#L177

### Possible solution

https://github.com/IonicaBizau/git-url-parse/pull/76

## Expected behavior

Access push to bitbucket should work with GIT_CREDENTIALS in the format <username>:<password>

## Environment

- GIT hosting provider: **Bitbucket.org**
- **semantic-release** version: **15.1.7**
- CI environment: **Jenkins**
- Plugins used: **exec**
- **semantic-release** configuration: 

```{
      "branch": "master",
      "verifyConditions": [
        {
          "path": "@semantic-release/exec",
          "cmd": "echo 'Conditions verified'"
        }
      ],
      "analyzeCommits": {
        "preset": "angular"
      },
      "verifyRelease": [
        {
          "path": "@semantic-release/exec",
          "cmd": "echo 'Release verified'"
        }
      ],
      "generateNotes": [
        "@semantic-release/release-notes-generator"
      ],
      "prepare": [
        {
          "path": "@semantic-release/exec",
          "cmd": "echo 'Prepare'"
        }
      ],
      "publish": [
        {
          "path": "@semantic-release/exec",
          "cmd": "echo 'Published'"
        }
      ],
      "success": [
        {
          "path": "@semantic-release/exec",
          "cmd": "echo 'Success'"
        }
      ],
      "fail": [
        {
          "path": "@semantic-release/exec",
          "cmd": "echo 'Failure'"
        }
      ]
}
```

- CI logs: 

```logs
[Semantic release]: Running semantic-release version 15.1.7
[Semantic release]: Load plugin verifyConditions from @semantic-release/exec
[Semantic release]: Load plugin analyzeCommits from @semantic-release/commit-analyzer
[Semantic release]: Load plugin verifyRelease from @semantic-release/exec
[Semantic release]: Load plugin generateNotes from @semantic-release/release-notes-generator
[Semantic release]: Load plugin prepare from @semantic-release/exec
[Semantic release]: Load plugin publish from @semantic-release/exec
[Semantic release]: Load plugin success from @semantic-release/exec
[Semantic release]: Load plugin fail from @semantic-release/exec
[Semantic release]: Call script echo 'Failure'
Failure
[Semantic release]: EGITNOPERMISSION The push permission to the Git repository is required.
semantic-release cannot push the version tag to the branch master on remote Git repository.

Please refer to the authentication configuration documentation (https://github.com/semantic-release/semantic-release/blob/caribou/docs/usage/ci-configuration.md#authentication) to configure the Git credentials on your CI environment.


{ SemanticReleaseError: The push permission to the Git repository is required.
    at module.exports (/usr/local/node/lib/node_modules/semantic-release/lib/get-error.js:6:10)
    at run (/usr/local/node/lib/node_modules/semantic-release/index.js:51:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
  name: 'SemanticReleaseError',
  code: 'EGITNOPERMISSION',
  details: '**semantic-release** cannot push the version tag to the branch master on remote Git repository.\n\nPlease refer to the [authentication configuration documentation](https://github.com/semantic-release/semantic-release/blob/caribou/docs/usage/ci-configuration.md#authentication) to configure the Git credentials on your CI environment.',
  semanticRelease: true }
```

**Comment by acgritt** [comment]
I was running into this same error as well the last few days and it turns out that mine is related to this issue that has been fixed in [envCi](https://github.com/pvdlg/env-ci/releases/tag/v2.0.1) where the branch name was not being parsed correctly and could have a trailing ")".  It works fine locally but on the build server it was having issues because the branch name had the ")".

**Comment by pvdlg** [comment]
@acgritt you have to make sure you have all the latest version of dependencies on your CI.

**Comment by botcheddevil** [comment]
@acgritt I don't think these two are related. I deep dived into both sem-rel and git-url-parse code and couldnt find a logic to handle this pattern.
