### ISSUE TITLE
Authentication failure with valid token

### ISSUE THREAD

**Issue by Arcanemagus** [semantic-release/semantic-release#771]
## Current behavior

semantic-release is throwing an `EGITNOPERMISSION` error, even though the same token works perfectly when manually running the command that supposedly is failing.

## Expected behavior

When a `GITHUB_TOKEN` is provided with the proper credentials, it should work.

## Environment

- **semantic-release** version: `^15.1.7` (`15.2.0` tested)
- CI environment: Travis CI
- Plugins used: No extra plugins
- **semantic-release** configuration: [`@semantic-release/apm-config@^2.0.1`](https://github.com/semantic-release/apm-config)
- CI logs:
    - [Failing deploy](https://travis-ci.org/AtomLinter/linter-htmllint/jobs/373647402#L571)
    - [Passing manual test of command](https://travis-ci.org/AtomLinter/linter-htmllint/builds/374633006#L500)

## Additional Information

Potentially related to the changes to fix https://github.com/semantic-release/semantic-release/issues/709?

**Comment by pvdlg** [comment]
I looked in detail but I couldn't figure out what happened...

I don't think it could be related to #709 as I don't see the message `The local branch %s is behind the remote one, therefore a new version won't be published` in the logs.

I opened #772 that logs the output of the `git push --dry-run`. That would help debugging hopefully.

What happen if you set the `DEBUG` environment variable to `semantic-release:*` in Travis and restart the hob https://travis-ci.org/AtomLinter/linter-htmllint/jobs/373647402 ?

**Comment by Arcanemagus** [comment]
Ah ha! It [looks like](https://travis-ci.org/AtomLinter/linter-htmllint/jobs/373647402#L592) the repository definition wasn't quite correct, leading it to not recognize the repository!

**Comment by pvdlg** [comment]
I'm really curious to know why the trailing `.git` makes a difference in some cases.
I tested there https://travis-ci.org/pvdlg/test-sr/jobs/374590162#L443 and it seems both works.

Maybe an obscure thing with slightly different version of git running on different Travis images....

**Comment by Arcanemagus** [comment]
Your test job is running on the `node_js` image just like these builds, so it's not the image itself at least.

**Comment by pvdlg** [comment]
Indeed. Can't figure out what's causing this "not found" error when omitting the `.git`...

**Comment by Arcanemagus** [comment]
Confirming that adding it at least [fixed the build](https://travis-ci.org/AtomLinter/linter-htmllint/jobs/374968073).

**Comment by pvdlg** [comment]
Great news!
I'd like to figure out when exactly the `.git` is required as some people have encounter this issue as well... If anyone reading this thread has any idea...

**Comment by pvdlg** [comment]
Closing in favor of #774
