### ISSUE TITLE
EGITNOPERMISSION error if trailing `.git` is missing from repository URL

### ISSUE THREAD

**Issue by pvdlg** [semantic-release/semantic-release#774]
In certain cases, apparently with GitHub and Travis, if the repository URL doesn't end with `.git` the command `git push --dry-run <repositoryUrl> HEAD:<branch>` fails and semantic-release errors out with `EGITNOPERMISSION`.

It's not really clear under which circumstances the issue happens.

See #771 for an example of the problem.
However it doesn't happen in this test: https://travis-ci.org/pvdlg/test-sr/jobs/374590162#L443

We would need to figure out in which circumstances (GitHub repo config, Travis image, Git version, etc...) a URL without `.git` fails. Depending on the finding we would add the `.git` to the URL in such circumstances or we would write a FAQ or troubleshooting section explaining the findings.

The `.git` is not added automatically as some Git host, such as VSTS doesn't work with it. It's not really clear when it is required or not, so for now semantic-release keep it if it's set by the user in the `package.json` or in the `repositoryUrl` and doesn't added if it's missing.

**Comment by marceloavf** [comment]
I was getting this error in VSTS so I changed to ssh authentication and it stops.

Old url:
```json
"url": "https://xxxxxx.visualstudio.com/xxxxx/_git/xxxx"
```

New one:
```json
"url": "ssh://xxxx@vs-ssh.visualstudio.com:22/_ssh/xxxxx"
```

**Comment by pvdlg** [comment]
Closing as the problem doesn't seems to happen anymore
