### ISSUE TITLE
SSH Guide should be more detailed

### ISSUE THREAD

**Issue by ev1stensberg** [semantic-release/semantic-release#782]
## New feature motivation

When following along the SSH key guide with github + travis, I did everything as expected, but it didn't work. In the guide it says "one of these is needed to push", so I assumed that a SSH key alone would make it work.

What defaults can I use, what defaults work out of the box? From intuition, I thought that if SSH keys were present, without the GH_TOKEN, then the release would trigger, but it didn't. 

## New feature description

A more detailed documentation on pushing with SSH keys and what is needed for SSH keys to work. 

( A small paragraph on what keys you need with SSH ) ( i.e GH_TOKEN + SSH keys)

## New feature implementation

N/A

**Comment by pvdlg** [comment]
Fixed in #783
