### ISSUE TITLE
Error when no upstream is configured for active branch

### ISSUE THREAD

**Issue by kai670** [semantic-release/semantic-release#786]
## Current behavior

Using semantic-release from Jenkins I'm experiencing the next error because Jenkins doesn't add an upstream branch for the checked out branch:

```
[Semantic release]: An error occurred while running semantic-release: { Error: Command failed: git rev-parse master@{u}
fatal: no upstream configured for branch 'master'
```

The problem is introduced in d15905c0d5acaa0847173cc3588deb40d2848301

## Expected behaviour

Skip verifying if the local branch is up to date with the remote one when there is no upstream configured. This way new check will still be useful but without breaking scenarios where upstream is not configured.

## Environment

- **semantic-release** version: 15.3.1
- CI environment: Jenkins

**Comment by pvdlg** [comment]
On my local machine and on Travis there is no upstream remote configure (only origin) and `git rev-parse master@{u}` works...
I'm not sure what the difference is.

What do you get is you run `git rev-parse master@{push}` on Jenkins?

**Comment by pvdlg** [comment]
Also what do you get with `git ls-remote --heads <repositoryUrl> <branch>` ?

**Comment by kai670** [comment]
I confirm it is working using semantic-release@15.1.9 and stops working with that change.

Checking semantic-release code, the push is done in `lib/git.js:124`:
```await execa('git', ['push', '--tags', repositoryUrl, `HEAD:${branch}`]);```

So afaik it works without the remote because it is specified in the command itself.

```
git fetch --unshallow --tags
fatal: --unshallow on a complete repository does not make sense

git rev-parse "master@{push}"
fatal: no upstream configured for branch 'master'
```

```
$ git ls-remote --heads <repositoryUrl> <branch>
9316be6efbc96ca3a48ed6cfaca351e8b7b26139	refs/heads/master
```

**Comment by pvdlg** [comment]
Ok so I'll replace `git rev-parse "master@{u}"` by `git ls-remote --heads <repositoryUrl> <branch>` then.

**Comment by pvdlg** [comment]
Checking explicitly if the local head is up to date was meant to distinguish an outdated local branch from an authentication errors, because `git push --dry-run` returns and error for both cases.

I just realized `git ls-remote --heads <repositoryUrl> <branch>` require authentication. So that doesn't allow to distinguish the 2 different cases, so we can't use that command...

Can you check if `git rev-parse origin/master` works in your scenario?
