### ISSUE TITLE
Unclear what "relevant code changes" means

### ISSUE THREAD

**Issue by ricardograca** [semantic-release/semantic-release#787]
The [Readme file](https://github.com/semantic-release/semantic-release/blob/caribou/README.md) mentions that:

> ... runs the `semantic-release` command to make a release if there are **relevant codebase changes** since the last release.

and:

> By default a release will be done for each push to the release branch that contains **relevant code changes**.

But it is never explained what "relevant code changes" means exactly. After reading the [FAQ](https://github.com/semantic-release/semantic-release/blob/caribou/docs/support/FAQ.md#is-it-really-a-good-idea-to-release-on-every-push) it seems to hint that a release will happen with every single push to the release branch, and not only when there are "relevant code changes". Of course this doesn't apply if the commit has a `[skip release]` in the message.

Given these somewhat contradictory statements I'm still not sure when a release is going to happen. Of course I'm a new user, otherwise I would probably know the answer through trial and error, but I'd prefer to be sure instead of having to go through that.

**Comment by ricardograca** [comment]
Great, thanks for the explanation, but it would be better if that was also in the Readme file. Even a simple

> Only these message types will trigger a release.

would help, since it says right there in the table that it's an "example", so there could be other message types that trigger releases for all I know.

**Comment by pvdlg** [comment]
The commit message that will trigger a release depends on the [configuration](https://github.com/semantic-release/commit-analyzer#options) of:
- The commit convention used with `preset`
- The release rules configured with `releaseRules`

This is why we use the somewhat vague term of "relevant change". The commits that will trigger a release depends on your config.

If you have a proposition for a better term or for clarification feel free to propose it here and open a PR.

**Comment by ricardograca** [comment]
How about:

> Note that only some message types will trigger a release. These message triggers depend on the configuration of the commit convention used with `preset` and the release rules configured with `releaseRules`, but by using the default config the table above lists all message types that would trigger a release and what kind of release it would be.

This is the best I can do without being too familiar with the project.
