### ISSUE TITLE
Semantic-release does not handle squash-merges.

### ISSUE THREAD

**Issue by jwalton** [semantic-release/semantic-release#792]
## Current behavior

```
[Semantic release]: Analyzing commit: Squashed commit of the following:

commit 74e6b0087331e5947fd8ba388e75d4d1900dfd44
Author: Jason Walton <dev@lucid.thedreaming.org>
Date:   Thu May 17 11:21:50 2018 -0400

    fix: More fixes

commit b894885ae467975226e81080a35625d247796960
Author: Jason Walton <dev@lucid.thedreaming.org>
Date:   Thu May 17 11:13:25 2018 -0400

    fix: Fix
[Semantic release]: The commit should not trigger a release
```

## Expected behavior

If a commit starts with "Squashed commit of the following:", semantic-release should parse out all the individual commit messages and analyze them individually.  The above contains two "fix" commits, so it should trigger a patch release.

## Environment

- **semantic-release** version: 15.4.0
- CI environment: Travis
- Plugins used: None
- **semantic-release** configuration: Default
- CI logs: n/a

**Comment by gr2m** [comment]
I think that could be done using an `analyzeCommit` plugin: https://semantic-release.gitbooks.io/semantic-release/docs/usage/plugins.html#analyzecommits-plugin

We might incorporate into semantic-release core but a plugin would be the first step

**Comment by jwalton** [comment]
I'll raise this over here then: https://github.com/semantic-release/commit-analyzer.  :)

**Comment by gr2m** [comment]
> I'll raise this over here then: semantic-release/commit-analyzer. :)

Either place works for discussion :)

Note that `semantic-release/commit-analyzer` is the default plugin to analyze commits. You can replace it with your own module that also parses squash-merges

**Comment by jwalton** [comment]
How does a regular merge work?  Like, where do we go fetch all the commits associated with a non-squash merge?

**Comment by gr2m** [comment]
> How does a regular merge work?

I’m not sure what you mean? `semantic-release` only runs on your main branch’s CI builds. It doesn’t matter if new commits are coming from a PR or have been pushed to the main branch directly. It just goes through all new commits and calculates version & changelogs based on that

**Comment by danielo515** [comment]
Was this ever implemented? I just did a sqash merge and got no release

**Comment by nfantone** [comment]
Exactly. I ran into this today. The squashed commits are omitted by default and couldn't find any matching option to enable that. Also, https://github.com/semantic-release/commit-analyzer/pull/66 was closed.

**Comment by travi** [comment]
https://semantic-release.gitbook.io/semantic-release/support/troubleshooting#squashed-commits-are-ignored-by-semantic-release

**Comment by rendomusr** [comment]
> https://semantic-release.gitbook.io/semantic-release/support/troubleshooting#squashed-commits-are-ignored-by-semantic-release

This is a poor stance to take. Not everyone fits into your idea of a perfect workflow. 

While I use atomic commits in my personal work, professionally it is required that we squash our commits. I want to use semantic release professionally but I can't because we don't fit your cookie cutter workflow.

Show a bit of empathy and please reconsider your stance. There is more that one way to merge

**Comment by achamas-playco** [comment]
Its the same with [release-please](https://github.com/google-github-actions/release-please-action), squashed commits don't get parsed so you need to enforce merge commits which is not ideal.

**Comment by DanieleCali** [comment]
Please, revive this thread and think about parsing also the squashed merges :(

**Comment by oxlade39** [comment]
We've been attempting to migration from the [semantic-release-gitlab](https://www.npmjs.com/package/semantic-release-gitlab) plugin and have all manor of problems. This being one of them.

I'm not entirely sure how [semantic-release-gitlab](https://www.npmjs.com/package/semantic-release-gitlab) managed to make squashed commits work but it did trigger the appropriate releases as if the merge had not been squashed.

Would support be reconsidered? or has anyone come up with a plugin that offers similar behaviour?

We now have many developers that are used to being able to squash merge through gitlab and it's second nature.

**Comment by romap0** [comment]
Hi guys. I've implemented a tiny wrapper for commit-analyzer and release-notes-generator which works with squashed MRs.
You can check it out: [semantic-release-unsquash](https://github.com/romap0/semantic-release-unsquash)
I've tested it on my project and it works like a charm

**Comment by rpivovar-godaddy** [comment]
> > https://semantic-release.gitbook.io/semantic-release/support/troubleshooting#squashed-commits-are-ignored-by-semantic-release
> 
> This is a poor stance to take. Not everyone fits into your idea of a perfect workflow.
> 
> While I use atomic commits in my personal work, professionally it is required that we squash our commits. I want to use semantic release professionally but I can't because we don't fit your cookie cutter workflow.
> 
> Show a bit of empathy and please reconsider your stance. There is more than one way to merge

100% agree

**Comment by RuneALiljegren** [comment]
> Hi guys. I've implemented a tiny wrapper for commit-analyzer and release-notes-generator which works with squashed MRs. You can check it out: [semantic-release-unsquash](https://github.com/romap0/semantic-release-unsquash) I've tested it on my project and it works like a charm

I could not use romap0 plugin, but it did help me in creating a similar plugin: [semantic-release-githubsquash](https://github.com/RuneALiljegren/semantic-release-githubsquash). Basically wraps the same as romap0s, but it only analyses the body of the squash commit. So you can create a headline and the do semantic-release notations in the body.

**Comment by jedwards1211** [comment]
The troubleshooting guide says

> A commit should contain exactly one self-contained functional change and a functional change should be contained in exactly one commit.

This isn't always realistic; sometimes you need to do a big refactor that fixes several issues at once and you want multiple bullet points in the changelog for it.

**Comment by lizozom** [comment]
@romap0 great work on https://github.com/romap0/semantic-release-unsquash!
Let me know if you ever need help maintaining it!
