### ISSUE TITLE
"https://[secure]@/ithub.com" string in logs

### ISSUE THREAD

**Issue by jwalton** [semantic-release/semantic-release#795]
## Current behavior

```
[Semantic release]: Running semantic-release version 15.4.1
[Semantic release]: Load plugin verifyConditions from @semantic-release/npm
[Semantic release]: Load plugin verifyConditions from @semantic-release/github
[Semantic release]: Load plugin analyzeCommits from @semantic-release/commit-analyzer
[Semantic release]: Load plugin generateNotes from @semantic-release/release-notes-generator
[Semantic release]: Load plugin prepare from @semantic-release/npm
[Semantic release]: Load plugin publish from @semantic-release/npm
[Semantic release]: Load plugin publish from @semantic-release/github
[Semantic release]: Load plugin success from @semantic-release/github
[Semantic release]: Load plugin fail from @semantic-release/github
[Semantic release]: The command "git push --dry-run https://[secure]@/ithub.com/benbria/secret-project HEAD:master" failed with the error message fatal: unable to access 'https://[secure]@/ithub.com/benbria/secret-project/': Could not resolve host: 
.
[Semantic release]: Verify GitHub authentication
[Semantic release]: EMISSINGREPO The repository ithub.com/benbria doesn't exist.
The semantic-release repositoryUrl option must refer to your GitHub repository. The repository must be accessible with the GitHub API (https://developer.github.com/v3).
```

## Expected behavior

Lol wut?  Where on earth is semantic-release getting "ithub.com" from???  :P

Travis is certainly cloning the correct repo: 

```
0.32s$ git clone --depth=50 --branch=master git@github.com:benbria/secret-project.git benbria/secret-project
Cloning into 'benbria/secret_project'...
Warning: Permanently added the RSA host key for IP address '192.30.253.112' to the list of known hosts.
```

And package.json has the repo set correctly:

```json
  "repository": {
    "type": "git",
    "url": "github.com/benbria/secret-project"
  },
```

I'm running exactly the same config on a whole bunch of private repos.  I just wrote [this yeoman generator](https://github.com/jwalton/node-generator-semantic-release) and applied it to a whole bunch of private repos today.  All the other ones are building correctly.

I had a very quick look at the semantic-release source to see where it is pulling this value from, but it's a parameter coming from more-than-two-calls-away, so I figured I'd raise an issue and see if anyone knew what was wrong before I dig any further.  :)

## Environment

- **semantic-release** version: ^15.4.1
- CI environment: Travis
- Plugins used: None
- **semantic-release** configuration: https://github.com/benbria/semantic-release-config/blob/master/index.js
- CI logs: Private repo.

**Comment by gr2m** [comment]
I’ve seen similar odd logs before, `semantic-release` redacts values of private environment variables, I’m certain it is related to that. But I haven’t seen that one specifically yet. Can you look trough past issues and see how we resolved it in the past?

**Comment by jwalton** [comment]
Before we call [here](https://github.com/semantic-release/semantic-release/blob/caribou/index.js#L57), options.repositoryUrl is "github.com/benbria/secret-project".  Afterwards, it is "https://[secure]@/ithub.com/benbria/secret-project".

We end up [here](https://github.com/semantic-release/semantic-release/blob/caribou/lib/get-git-auth-url.js#L49) with the error:

```
{ Error: Command failed: git push --dry-run github.com/benbria/secret-project HEAD:master
fatal: 'github.com/benbria/secret-project' does not appear to be a git repository
fatal: Could not read from remote repository.
```

Oh!  I can reproduce this locally, if I set GH_TOKEN and NPM_TOKEN.  That makes this easier to figure out...

**Comment by jwalton** [comment]
Aha.  The error is on [this line](https://github.com/semantic-release/semantic-release/blob/caribou/lib/get-git-auth-url.js#L55).  When we get here, `parsed.toString()` returns 'github.com/benbria/secret-project', but `parsed.toString('https') (which is the value of `protocol`) returns "https:///ithub.com/benbria/secret-project".  With the `user`, this ends up as "https://[GH_TOKEN]@/ithub.com/benbria/secret-project".

Note the extra "/" after the "@".  This is completely broken.  :P

But, likely this is being caused by some kind of permissions problem.  Although github says my user has write access to the repo.  :/

**Comment by jwalton** [comment]
If I `curl https://api.github.com/repos/benbria/secret-project?access_token=$GH_TOKEN`, I get back a big document that includes (amongst a lot of other things):

```
  "permissions": {
    "admin": false,
    "push": true,
    "pull": true
  },
```

So github, at least, thinks I have write access to this repo.

**Comment by jwalton** [comment]
[readPkgUp](https://github.com/semantic-release/semantic-release/blob/caribou/lib/get-config.js#L70) is returning an "https://" URL in one case, and a bare URL in the other case.

**Comment by jwalton** [comment]
Fixed by changing:

```json
  "repository": {
    "type": "git",
    "url": "github.com/benbria/secret-project"
  },
```

to

```json
  "repository": {
    "type": "git",
    "url": "https://github.com/benbria/secret-project.git"
  },
```

But yeah, you guys need a better error message for this.  :)

(BTW; as I've been digging into semantic-release, I feel like all I ever do is post horrible issues here.  Just wanted to take a moment to say thanks for building all of this.  Something I know open source maintainers don't hear enough.  :) )

**Comment by pvdlg** [comment]
`github.com/benbria/secret-project` is not a valid git URL, this is why it errors out.
We have to support multiple format of valid Git URL, including some shorthand, so unfortunately there is no great way to handle every possible mistakes that can be made while configuring the URL.

It's expected from the users to configure a repository URL that works with the `git` command line.
I'm not sure it's worthwhile to spend time trying to figure out every possible mistake to report better errors. The `git` CLI doesn't do it, and just fails when the URL is improperly formatted and it doesn't seems to be a big issue.

In addition the error message report the URL that is used, so users can figure out there is an issue with the repository URL.

**Comment by pvdlg** [comment]
> This project has been hosted on git for three years. It's worked fine with the git command line tools all this time. The git command line tool doesn't read package.json.

I never said the `git` command read the `package.json`. The `package.json` defines a property for repository URL used as a metadata of the project. semantic-release uses that to know what is the repository URL and it assume it's correct.
So yes sure you can have an incorrect URL in your `package.json` and it won't create any issue if you don't use it, but that doesn't means semantic-release should handle incorrect URL.

> The error did not report the URL that was used in package.json, it printed "ithub.com/benbria doesn't exist." This is not the URL from package.json, nor is it the url from git remote -v. At the very least, you should print the literal URL you tried to use (rather than the mangled version) and where it came from (because TBH I expected it to come from git remote -v).

semantic-release uses the URL in your `package.json` and transforms it:
- to expand shorthand URL
- to transform `git` URL into `https`
- to add the authentication part

In certain case a wrong URL fails right away as it's not readable. In cases like your where the URL is a correct generic URL but a wrong Git URL (as per what the `git` CLI considers correct) the transformations can still occur but ends up generating a still wrong URL.

So there is a grey area where the URL seems correct (according what a generic URL should be) but still doesn't work with `git` CLI. There is no way to way (at least not a simple one) for us to figure out if the URL is invalid, not authorized, point an offline location etc...

We just see that it's parseable but the `git` CLI report an error. If we start reporting configuration error (such as "The URL <URL_from_package.json> is not configure properly") as you suggest, it would be accurate in your specific situation. But someone with a permission issue will obtain an inaccurate error.

**Comment by jwalton** [comment]
It doesn't have to be "This is not a valid git url", it could be simply "We
are unable to contact the git repo at the URL xxxx, taken from
package.json".  But at leastlist the *actual* url  you're trying to use.  I
searched my project all over for ithub.com, with no success.

You've to at least give people a chance of figuring out where the url is
coming from, without having to use a debugger.

Even @gr2m didn't spot the problem right away, even though I had the line
from my package.json right there in my initial issue report.  So it's not
like this is just me.
