### ISSUE TITLE
peerinvalid Peer marked-terminal@2.0.0 wants marked@^0.3.6

### ISSUE THREAD

**Issue by UziTech** [semantic-release/semantic-release#800]
## Current behavior

installing throw an error

```
peerinvalid Peer marked-terminal@2.0.0 wants marked@^0.3.6
```

## Expected behavior

no error

## Environment

- issue: https://github.com/UziTech/number-string/issues/17
- **semantic-release** version: 15.4.3
- CI environment: travis
- CI logs: https://travis-ci.org/UziTech/number-string/builds/381739610

**Comment by gr2m** [comment]
Confirmed

**Comment by gr2m** [comment]
@UziTech note that you should remove the npm@2 install here: https://travis-ci.org/UziTech/number-string/builds/381739610#L453 :)

**Comment by pvdlg** [comment]
That should be solved with the `15.4.4` release. Could you confirm?

**Comment by UziTech** [comment]
looks good 👍 Thanks for the quick response.
