### ISSUE TITLE
Use rational branch names

### ISSUE THREAD

**Issue by jedwards1211** [semantic-release/semantic-release#807]
Please do not use animal names for the branches, use names that express something about how the features of the branches differ.  I have been confused at times when trying to dig through the code in this repo what the various animal named branches are about.

**Comment by pvdlg** [comment]
We don't really use those branches anymore. Once #563 lands will probably move toward something more usual: `master` and `next` and maybe some branches for older versions that we still want to maintain (`15.x`, `16.x`, etc...)

**Comment by jedwards1211** [comment]
Cool, that makes more sense!
