### ISSUE TITLE
Plugin with post-pre and pre-post hooks

### ISSUE THREAD

**Issue by kentcdodds** [semantic-release/semantic-release#81]
I realize that title isn't very helpful. But basically, I want to write a plugin that allows me to do something after the normal `semantic-release pre` and before the normal `semantic-release post`. My [angular-formly script](https://github.com/formly-js/angular-formly/blob/master/package.json#L32) looks like this:

```javascript
"semantic-release": "semantic-release pre && npm run build && npm publish && npm run publish:latest && semantic-release post"
```

As you can see, I just need to run something after the `pre` and run another something before the `post`. Technically, I could/should do this in two separate plugins. One is to build the project after the package.json `version` has been updated so I can use that to create a `version` variable in my project. The other is to commit the built files and push them to a `latest` branch and then `semantic-release` will use that for the github release.

I have this working for angular-formly, and I'd like to make two plugins to do this for me so I can re-use this elsewhere.

Any direction would be helpful! The docs weren't entirely straightforward. It appears that there isn't a general "hooks" but rather specific plugin slots that I'd have to fill in (and override in some cases). I would prefer something like:

```javascript
{
  "release": {
    "hooks": {
      "pre-pre": [
        "path-to-plugin",
        {"options": "for-plugin", "path": "path-to-other-plugin"}
      ],
      "post-pre": [ /* same idea as above */ ],
      "pre-post": [ /* same idea as above */ ],
      "post-post": [ /* same idea as above */ ]
    }
  }
}
```

Or am I just totally missing something?

**Comment by boennemann** [comment]
Any reason this won't work for you? (I split it up for readability)

```json
"scripts": {
  "prepublish": "npm run build",
  "presemantic-release": "semantic-release pre",
  "semantic-release": "npm publish && npm run publish:latest",
  "postsemantic-release": "semantic-release post"
}
```

If you want to expose the version number into the build just read it from the package.json, but fallback to "0.0.0-development" (or similar) if it isn't present. That way you can just make it part of the build script and have it work as expected for builds that are about to be distributed.

**Comment by tusharmath** [comment]
@boennemann If I want to execute my `gh-pages` script only if there is a new release then what should i do?
