### ISSUE TITLE
Possible error in plugin loading logic, says Succeed and Fail for @semantic-release/github

### ISSUE THREAD

**Issue by mattmazzola** [semantic-release/semantic-release#811]
## Current behavior

See logs for Travis CI.  It loads the plugin and then says "Succeed" _and_ "Fail" which shouldn't both be possible.

![image](https://user-images.githubusercontent.com/2856501/40947058-9a61057e-6815-11e8-9619-98980b18e9b1.png)

## Expected behavior

Should just print "Succeed" message.

## Environment

- **semantic-release** version: Latest? Used `npx semantic-release`
- CI environment: TravisCI
- Plugins used: None, defaults?
- **semantic-release** configuration: 
- CI logs: https://travis-ci.org/Microsoft/ConversationLearner-SDK/builds/388041180

**Comment by mattmazzola** [comment]
Ah never mind... See `fail` is just the name of the plugin... 😅

**Comment by travi** [comment]
@pvdlg seems like this has tripped people up a few times. i wonder if double-quoting the plugin names, or something similar, would be enough to clarify this for users.

**Comment by pvdlg** [comment]
Yes. The quotes seems a good idea. Do you want to make a PR?

**Comment by travi** [comment]
sure, i could put something together tonight.
