### ISSUE TITLE
Error: Cannot find module '../build/tries/current/icann.complete.json'

### ISSUE THREAD

**Issue by unlight** [semantic-release/semantic-release#816]
## Current behavior
```
{ Error: Cannot find module '../build/tries/current/icann.complete.json'
at Function.Module._resolveFilename (module.js:547:15)
at Function.Module._load (module.js:474:25)
at Module.require (module.js:596:17)
at require (internal/module.js:11:18)
at Object.<anonymous> (/home/rof/src/github.com/unlight/ref-holder/node_modules/semantic-release/node_modules/git-url-parse/node_modules/parse-domain/lists/icann.complete.js:5:28)
at Module._compile (module.js:652:30)
at Object.Module._extensions..js (module.js:663:10)
at Module.load (module.js:565:32)
at tryModuleLoad (module.js:505:12)
at Function.Module._load (module.js:497:3) code: 'MODULE_NOT_FOUND' }
```

## Expected behavior

No error

## Environment

- **semantic-release** version: 15.5.1
- CI environment: Codeship
- Plugins used: @semantic-release/changelog @semantic-release/git @semantic-release/npm 
- **semantic-release** configuration: https://github.com/unlight/ref-holder/blob/48519d6470ca1db665f2e07a00151953d48271a3/package.json#L67-L95
```
> npm ls semantic-release git-url-parse
`-- semantic-release@15.5.1
  +-- @semantic-release/release-notes-generator@6.0.12
  | `-- git-url-parse@9.0.1  deduped
  `-- git-url-parse@9.0.1
```

**Comment by pvdlg** [comment]
Does it happens when you run npm install? Or when you run semantic-release?
Have you tried to delete your node_modules folder and your lockfile and re-install?

**Comment by unlight** [comment]
It happens while runnig semantic-release.

> Have you tried to delete your node_modules folder and your lockfile and re-install?

I do not have lockfile.

I cannot remove node_modules on CI side (codeship) (reset cache did not help). 
I can try to do it locally, but it makes no much sense. I need working it on CI.

**Comment by unlight** [comment]
//cc @IonicaBizau

**Comment by unlight** [comment]
https://github.com/peerigon/parse-domain/issues/35

**Comment by jhnns** [comment]
This was introduced by change made in our module `parse-domain` (which is apparently a transitive dependency of semantic-release). You can probably close it here as it is not related to semantic-release itself.

**Comment by Aghassi** [comment]
@jhnns Any update as to when https://github.com/peerigon/parse-domain/pull/39 will be merged?

**Comment by pvdlg** [comment]
An alternative and probably better solution here: https://github.com/IonicaBizau/git-url-parse/pull/80

**Comment by nkristoffersen** [comment]
I wanted to try semantic-release but now find I cannot run it in CI due to this issue with `parse-domain`. Ironic since this is the exact situation semantic versioning is trying to solve :-)

**Comment by pvdlg** [comment]
Fixed by #860

**Comment by kimsagro1** [comment]
@pvdlg this is also affecting https://github.com/semantic-release/release-notes-generator

**Comment by DrMiaow** [comment]
What is this fix for this and what is causing it?
