### ISSUE TITLE
Travis CI build fails -- keytar can't find keyring

### ISSUE THREAD

**Issue by apowers313** [semantic-release/semantic-release#82]
I just started using semantic-release on a new project, and the [build on Travis CI fails](https://travis-ci.org/apowers313/testing/jobs/79420565) with the error:

```
> keytar@2.1.0 install /home/travis/build/apowers313/testing/node_modules/semantic-release-cli/node_modules/keytar
> node-gyp rebuild
Package gnome-keyring-1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gnome-keyring-1.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gnome-keyring-1' found
gyp: Call to 'pkg-config --libs-only-l gnome-keyring-1' returned exit status 1. while trying to load binding.gyp
gyp ERR! configure error
```

I had to add the following to the `.travis.yml` to get it to work:

``` yaml
sudo: true
before_install:
  - sudo apt-get install libgnome-keyring-dev
```

**Comment by christophwitzko** [comment]
Hi @apowers313,

there is no need to add `semantic-release-cli` to your [`devDependencies`](https://github.com/apowers313/testing/blob/master/package.json#L24).
The [`semantic-release-cli`](https://github.com/semantic-release/cli) is just used for setting up `semantic-release` on your repository.
You might install the CLI globally on your machine: `npm install -g semantic-release-cli`.

have a nice day,
Christoph

**Comment by apowers313** [comment]
@christophwitzko Ah, now it makes sense why nobody else was running into this issue. Thanks for the help.

I'm actually using it as [part of a template](https://github.com/apowers313/open-element-template) where I would expect others to run `semantic-release-cli` as part of the `npm post-install` process. I'll fix up the .travis.yml as part of my install process -- you can close out this issue.

On an unrelated topic, I found the undocumented use of `keytar` extremely disturbing when I realized that `semantic-release-cli` had saved my passwords without mentioning that was going to do so in the README or mentioning it as part of install script. The README doesn't even mention the command-line option for `--no-keychain`. I would advocate for defaulting `keychain` to `false` and updating the README. Happy to submit a PR if you guys are open minded to that.

**Comment by christophwitzko** [comment]
@apowers313 nice :+1: :relaxed: 

Regarding `keytar`: Sorry for the bad documentation. It would be awesome if you could create [here](https://github.com/semantic-release/cli/issues) an issue so we can discuss the further steps.
