### ISSUE TITLE
Help: How to use changelog plugin ?

### ISSUE THREAD

**Issue by Wikiki** [semantic-release/semantic-release#828]
Hi,

I'm trying to use add the changelog plugin to auto-update the changelog.md file but if I put the following config in my package.json then there is no release anymore:

```
"release": {
    "prepare": [
      {
        "path": "@semantic-release/changelog",
        "changelogFile": "docs/changelog.md",
      }
]
}
```

Do I have to rewrite all default configuration ? If yes: where I can find it to be sure don't miss anything ?

Thanks for your help

**Comment by pvdlg** [comment]
You just have to add to the `prepare` the other plugins you want to use in this step.
By default it's only the `@semantic-release/npm` one.
You can see the default plugins in the doc: https://github.com/semantic-release/semantic-release/blob/caribou/docs/usage/configuration.md#prepare

**Comment by Wikiki** [comment]
If I add the prepare rule into my package.json do I have to precise the npm plugin too or it still took into account 'cause it's the default one ?

**Comment by Wikiki** [comment]
Other question: in the doc I see <code>semantic-release/commit-analyzer
</code> is the default commit analyzer used. So Do I have to redefine it if I just want to change the prepare step ? If yes where can I find the default options it's called with ?

**Comment by pvdlg** [comment]
> If I add the prepare rule into my package.json do I have to precise the npm plugin too or it still took into account 'cause it's the default one ?

Yes you have to add the npm plugin in that step.

> in the doc I see semantic-release/commit-analyzer is the default commit analyzer used. So Do I have to redefine it if I just want to change the prepare step ? If yes where can I find the default options it's called with ?

No you don't have to redefine it in that case.

**Comment by Wikiki** [comment]
Clear now.
But where can I find the default options passed to the default plugins if I have to redefine them ?

**Comment by pvdlg** [comment]
There is no option set by default for plugin by semantic-release core. You can read each plugin documentation to find out what the default are.

**Comment by Wikiki** [comment]
Perfect. Thank you
