### ISSUE TITLE
Add way to pass in build meta data (or modify the version in general)

### ISSUE THREAD

**Issue by jamsea** [semantic-release/semantic-release#835]
## New feature motivation

I want to be able to add the Jenkins build number as metadata using this feature in semver: https://semver.org/#spec-item-10

Currently there's no way to modify/parse the version that I know of.

## New feature description

I think what could make the most sense is the ability to pass in a `parseVersion` function into `release.config.js`. This function would take in a version number and return a string.

## New feature implementation

It looks like this file is currently figuring out the version:
https://github.com/semantic-release/semantic-release/blob/caribou/lib/get-next-version.js

One potential solution is to pass in a `parseVersion` function that returns a new version and change line 7 to
```js
version = parseVersion(semver.inc(lastRelease.version, type));
```

**Comment by pvdlg** [comment]
It's part of the Semantic Versioning Specification so I guess we should support it.

It could be implemented with a new `buildMetata` plugin hook that would receive `{options, logger, lastRelease, commits, nextRelease}` and returns a String that would be set in the metadata part of the version 

As the metadata part of the semantic version is something rarely used (as far as I can tell) and it's not used by npm (the metadata is just ignored on publish) I imagine you are mostly interested in having it in the Git tag.
If it's indeed the case you can use the [tagFormat option](https://github.com/semantic-release/semantic-release/blob/caribou/docs/usage/configuration.md#tagformat) option like this: `v${version}+${process.env.JENKINS_BUILD_NUMBER}`.
Would such workaround works for you?

**Comment by pvdlg** [comment]
Yeah I just tried to publish version `2.1.0-beta.1+exp.sha.5114f85` and I get that on npm: https://www.npmjs.com/package/@pvdlg/test-release/v/2.1.0-beta.1.

The only differences I see between using the `tagFormat` workaround and having a proper implementation via plugin are:
- The version passed to `publish`, `prepare` and `success` plugins will be without the metadata (the `gitTag` prop will have it though)
- Therefore the version name in the GitHub release and the changelog will not have the metadata, but I'm not sure it's really valuable info anyway

Do you need that info anywhere else than in the Git tag?

**Comment by jamsea** [comment]
Yeah I think I might just have to write my own custom function for prepare to fit our workflow. Analyzing the commits doesn't really work because the team isn't used to formatting commit messages yet, so the least friction way to introduce this tool is to leverage the Jenkins build number for the minor version number (e.g. `v0.0.95100002` would be fine)

Something like this should work:
```js
const {prepare: npmPrepare} = require('@semantic-release/npm');
function customPrepare(pluginConfig, {nextRelease: {version}, logger}) {
    const jenkinsBuildNumber = process.env.BUILD_NUMBER;
    const customVersion = someCustomLogicHere(jenkinsBuildNumber);
    return npmPrepare(pluginConfig, {nextRelease: {version: customVersion}, logger});
}
```

**Comment by pvdlg** [comment]
That wouldn't work as it wouldn't follow semantic versioning. The concept is to increase version numbers by one on each new release (`1.0.0` then `1.0.1` etc...).
The entire concept of semantic-release is to determine the next version for you, based on the changes made since last release. We achieve that by analyzing the commit messages in the `analyzeCommit` plugin.

In addition plugins cannot modify the version by design as the core concept is to define the version based on semantic versioning rules.

**Comment by jamsea** [comment]
I see what you mean. I think I've been thinking about this wrong, this might be the wrong tool for the job I have (even though it'd be great to use for a new, or smaller project). Now that I'm thinking more about it, it's going to be tricky to get the git history too, because I'll be running this from inside a docker container that won't have the entire repo (just a sub folder), so I won't have access to the `.git` folder to read the tags. Do you know if the npm plugin determines the next version by checking the npm server? Or does it rely on git tags and the package.json?

**Comment by pvdlg** [comment]
The last version and next version are determined by the core, not by a plugin.
And yes the entire Git repo with the complete history is required.

**Comment by jamsea** [comment]
Thanks for your help! I'll close the issue
