### ISSUE TITLE
Allow to pass logger option via JS API

### ISSUE THREAD

**Issue by Aghassi** [semantic-release/semantic-release#852]
## New feature motivation

Currently, I am working on a tool that wraps Semantic Release to ease development at a fairly large company. I'd like to make it more "seamless" with the tool I'm creating (also a CLI tool). Since I'm using [Listr](https://github.com/SamVerschueren/listr) as a way to show the commands I'm running, I hand the Semantic-Release promise to RxJS to keep track of for when it is done. However, it messes up my terminal output when Semantic Release just spews info into the console via the `log` function. Ideally, I'd like a way to silence or redirect that output somewhere so that I can just point my users to it.

## New feature description

Add a `--silent` option that supresses the log output unless there is a failure. Ideally, the `--silent` option would also send the logs to a temp file written to disk that could then be opened after the process is done running.

## New feature implementation

Change:
https://github.com/semantic-release/semantic-release/blob/d548edcf37261ec7eaefeb7f0446289b0e91596c/lib/logger.js#L9

To do a check for `--silent` flag for starters. Then add the flag to:
https://github.com/semantic-release/semantic-release/blob/caribou/cli.js#L18

**Comment by pvdlg** [comment]
I'm guessing you are using `execa` to run the `semantic-release` command? Something similar to the examples shown in https://github.com/SamVerschueren/listr?

If yes, just the [stdio](https://github.com/sindresorhus/execa#stdio) option of `execa` or it's `pipe` function to pipe the stdout and stderr to whatever you stream your like.

If you want to write logs to a file then just pipe the execa `stderr` or `stdout` to a file writer.

That's not an issue with semantic-release. All the examples on https://github.com/SamVerschueren/listr also use command that write to the console. It's up to you to decide what you do with `stdout` and `stderr`.

**Comment by Aghassi** [comment]
I'm actually not 😅 . I could use `execa`, but I was trying to be a little more native than that since you already return a `Promise` and I didn't want to `Promise` chain if I didn't have to. My code is just this:

```javascript
      {
        title: 'Releasing via semantic-release...',
        skip: () => program.manual,
        task: () => {
          // Use observable to get pretty spinner while Semantic Release Runs
          from(semanticRelease({ dryRun: program.dry, noCi: !process.env.CI, isCi: process.env.CI }));
        }
      },
```

And at the top I just do
```javascript
import { from } from 'rxjs';
import semanticRelease from 'semantic-release';
```

**Comment by Aghassi** [comment]
To add to this, it looks like this also writes the results directly to the `stdout` stream

https://github.com/semantic-release/semantic-release/blob/45eee4acdd2a213672466369bcf0a04cd39ee0e1/index.js#L106

That means that if there is a `--silent` option, this would have to be handled too since it doesn't go through the normal `logger`.

**Comment by pvdlg** [comment]
Ah ok. You mentioned the option `--silent` which look like a CLI option so I assumed you were calling the CLI with `execa`.

I'm thinking about using [signale](https://github.com/klauscfhq/signale) for logging. I could add a parameter (or an option to `opts`) in the main JS function that would allow to define the `signale` config. If it's not set I would use the default one.

This way you could pass the `signale` config with the [disabled](https://github.com/klauscfhq/signale#disabled) option or the [stream](https://github.com/klauscfhq/signale#stream) option to collect the logs on whatever stream you'd like.

**Comment by Aghassi** [comment]
Looks cool! What would it take to get this going? Anything I can do to help?

**Comment by pvdlg** [comment]
I'm doing a lot of refactoring to simplify the code. I'll look at this feature after. I don't yet how it's going to be implemented in details.

**Comment by Aghassi** [comment]
Just as a note, until this is fix, I wanted to post my work around for now. For now, I used https://www.npmjs.com/package/intercept-stdout to hijack the console output temporarily and then log it later when I wanted to use it. Anyway, thanks again! Looking forward to when there is an official logger 😄

**Comment by pvdlg** [comment]
@Aghassi please see #865.

I implemented slightly differently then what I proposed above. Basically I allow to pass a writable stream to be used as `stdout` and `stderr` rather than the full `signale` options.
Allow to customize the logger options doesn't seems to provide much value and it would have created a lot of extra complexity.
I also added a JS API documentation with some examples.

Would that work for your use case?

**Comment by Aghassi** [comment]
@pvdlg Yeah that looks like it will work. That allows me to at least modify the stream before presening 😄
