### ISSUE TITLE
semantic-release throws on array of analyzeCommits plugins

### ISSUE THREAD

**Issue by sergeybekrin** [semantic-release/semantic-release#869]
## Current behavior

semantic-release throws an error if array of `analyzeCommits` plugins are present in config.

## Expected behavior

semantic-release supports multiple `analyzeCommits` or displays error message which clarifies on that only single plugin is supported.

## Environment

- **semantic-release** version: 15.8.1
- **@semantic-release/commit-analyzer** version: 6.0.0
- CI environment: any
- **semantic-release** configuration:
```js
{
  analyzeCommits: [
    { path: '@semantic-release/commit-analyzer' },
  ]
}
```
- CI logs:
```
The analyzeCommits plugin configuration (https://github.com/semantic-release/semantic-release/blob/caribou/docs/usag
e/plugins.md#analyzecommits-plugin) if defined, must be a single or an array of plugins definition. A plugin definition is either a string or an object with a path property.

Your configuration for the `analyzeCommits` plugin is `[ { path: '@semantic-release/commit-analyzer' } ]`
```

---

Hey there 👋

I believe this is a regression since [this change](https://github.com/semantic-release/semantic-release/commit/49f5e704ba0670cebff41853e29a747d93af0874#diff-205c5cf625514dcf92e20a30d112c1cdR16). `configValidator` for `analyzeCommits` doesn't check for an array, like other plugins do. Not sure if error message needs to be tweaked, or logic of config validator itself.

**Comment by pvdlg** [comment]
The `analyzeCommits` as always been a single plugin.
Currently the error message is generic for all plugins, which might be confusing. I guess it can be improved to be clearer.
Also I guess we can accept Arrays of 1 as valid for `analyzeCommits`.

**Comment by sergeybekrin** [comment]
@pvdlg thanks for clarification! Indeed we've used just a single plugin, but it an array :)
