### ISSUE TITLE
Does this works with Node v4x on windows?

### ISSUE THREAD

**Issue by hafeez-syed** [semantic-release/semantic-release#87]
Hi, I am just wondering if anyone tried installing this with Node v4 on windows? I have faced issues however when I downgraded it to Node v0.12.x then it works.

**Comment by gr2m** [comment]
if you changed to Node v4 after you run `npm install`, make sure to delete node_modules and run `npm install` again, as some installed binaries might break now

**Comment by hbetts** [comment]
@hafeez-syed could you please confirm whether @gr2m's comment applies?

**Comment by hafeez-syed** [comment]
no, I had to re-install my windows and re-install python and MS Visual Studio 2013 to make it work

**Comment by gr2m** [comment]
Glad to hear you got things working @hafeez-syed. Sounds like an issue not related to semantic-release. I'll close the issue, but feel free to keep commenting or reopening if you see a need :)
