### ISSUE TITLE
Fail to update the new version and no new release on GitHub

### ISSUE THREAD

**Issue by leocwlam** [semantic-release/semantic-release#872]
## Current behavior

npm package version keeps on '0.0.0-system-logger'  and no auto created tag release on GitHub 

## Expected behavior

Version change on npm and GitHub repo auto create the release with the new version

## Environment

- **semantic-release** version: 15.8.1
- CI environment: leocwlam/system-logger
- Plugins used: no
- **semantic-release** configuration: https://github.com/leocwlam/system-logger/blob/master/.travis.yml
- CI logs: https://travis-ci.org/leocwlam/system-logger/jobs/408544874

![versionissue](https://user-images.githubusercontent.com/35342488/43271229-fe2d0f08-90c4-11e8-93f1-a43bf89c722b.png)

**Comment by pvdlg** [comment]
Please see https://semantic-release.gitbook.io/semantic-release/support/faq#why-is-the-package-jsons-version-not-updated-in-my-repository

Also in your `.travis.yml` you try to deploy twice. Once with `provider: npm` and once with semantic-release.
Please follow the documentation to configure Travis: https://semantic-release.gitbook.io/semantic-release/recipes/recipes/travis-build-stages#multiple-node-jobs-configuration

**Comment by leocwlam** [comment]
Hi Pierre,
Thank for your help.  I think I am getting closer to success.  After all the change, I can see semantic-release, which create the release (on V1.0.0)
https://github.com/leocwlam/system-logger/releases
![release1](https://user-images.githubusercontent.com/35342488/43301465-4e2e4bde-9133-11e8-856b-69418bb4ea24.png)
but it still fails to publish on npm https://travis-ci.org/leocwlam/system-logger/jobs/408790147
![faildeployment](https://user-images.githubusercontent.com/35342488/43301513-af2fee56-9133-11e8-8ed8-ebf06277e95f.png)

FYI:
On Sunday, when I tried to release, I change the version to 1.0.0 and published on npm.  When I keep on modify code and release.  It failed to publish the 1.0.1.  Therefore, I ran **npm unpublish system-logger@1.0.0** to remove from npm on Monday morning.  (No one download yet)
I am not sure.  Does it cause the current issue?  

Do I still missing anything?

**Comment by pvdlg** [comment]
You can't republish a version on npm after unpublishing it.
Again, your problem is that in your .travis.yml you try to deploy twice, once with `provider: npm` and once with semantic-release.

**Comment by leocwlam** [comment]
Thanks for your quick reply.  

I already fixed .travis.yml.  I changed from **provider: npm** to **provider: script**
https://github.com/leocwlam/system-logger/blob/master/.travis.yml
Now, we are at 
![faildeployment](https://user-images.githubusercontent.com/35342488/43303102-4c16430c-913c-11e8-9356-195daa217b06.png)

If we can't republish a version on npm after unpublishing it.  (v1.0.0)
Now, what should we do?  Can we config semantic-release to start version 1.0.1 instead 1.0.0.?

**Comment by pvdlg** [comment]
Just recreate your `1.0.0` tag on the commit that was used to create that release

**Comment by leocwlam** [comment]
Thanks very much.  I tag the release v1.0.0 generated from semantic-release, as you mention above.  Now, I tested from my next fix, npm is showing up to 1.0.1.
