### ISSUE TITLE
Getting an "EGITNOPERMISSION" error even though i have a valid token.

### ISSUE THREAD

**Issue by JureSotosek** [semantic-release/semantic-release#876]
## Current behavior

Getting an "EGITNOPERMISSION The push permission to the Git repository is required." error even though valid token is provided.

## Expected behavior

Push to Github without a problem.

## Environment

- **semantic-release** version: 15.9.1
- CI environment: Circle CI
- **semantic-release** configuration: https://github.com/JureSotosek/ink-divider/tree/0d623370d5e114f8dd741f55fb79c195ebead074 note: I temporarily commented out the release part of circle ci config, this is the version where it wasn't yet commented out.
- CI logs: https://circleci.com/gh/JureSotosek/ink-divider/9

I tried running the --dry-run command in my terminal and it worked, also made sure that i didn`t have any auth already set up in my terminal so just running the --dry-run command without the token presented me with a prompt to enter my username.

**Comment by pvdlg** [comment]
Can you try to configure your `repository` in your package.json as `https://github.com/juresotosek/ink-divider.git` instead of `https://www.github.com/juresotosek/ink-divider.git`?

**Comment by JureSotosek** [comment]
That did the trick, seams odd. Any explanation on why that happening?
