### ISSUE TITLE
NPM plugin publish erroneous fail

### ISSUE THREAD

**Issue by ciccio86** [semantic-release/semantic-release#887]
## Current behavior

I set up a CircleCI pipeline involving a step of packaging using semantic-release. In the last 2 runs the semantic release step failed with the following messages:

> You cannot publish over the previously published versions: 0.3.0. : design-angular-kit

and

> You cannot publish over the previously published versions: 0.4.0. : design-angular-kit

Actually the npm package is correctly published on the registry but the CircleCI pipeline fails exactly at this step.

Obviously there where no already a 0.3.0 or a 0.4.0 version on the registry.

So the npm plugin publish step fails even if the package is successfully published.

## Expected behavior

If the package is successfully published, the step should complete successfully.

## Environment

- **semantic-release** version:  ^15.7.1 
- CI environment: CircleCI 
- Plugins used: changelog, npm, github, git, exec
- **semantic-release** configuration: [package.json](https://github.com/italia/design-angular-kit/blob/master/package.json)  
- CI logs: [CircleCI log](https://circleci.com/gh/italia/design-angular-kit/664)

**Comment by pvdlg** [comment]
According to the logs semantic-release properly update the `package.json` and calls `npm publish`.
And I don't see any indication in the logs nor any reason for semantic-release to try to publish twice.

Was the version `0.4.0` already published before you ran semantic-release?
Or did you publish it before then unpublished it?

**Comment by ciccio86** [comment]
@pvdlg the version 0.4.0 was a completely new version which was never published before. The fact is that even though semantic-release failed, the npm package has been successfully published on npm registry.

The problem actually occurred with version 0.3.0: [this is the log](https://circleci.com/gh/italia/design-angular-kit/650).

Anyway the problem did not occur earlier that day with release 0.2.1: [here the log](https://circleci.com/gh/italia/design-angular-kit/614).

**Comment by pvdlg** [comment]
The error is reported by `npm` which is ran by semantic-release.
Either it's a bug in npm or there was actually a `0.4.0` and `0.3.0` version already published before.

**Comment by ciccio86** [comment]
Just found this [NPM related issue](https://github.com/npm/npm/issues/19763).

**Comment by pvdlg** [comment]
So it seems it's an issue on the registry side...
There is no much we can do here.

Maybe it's similar to #804 ?

**Comment by pvdlg** [comment]
Closing as it seems to be a bug on npm registry. I invite you to open an issue over there.

**Comment by dharmatv** [comment]
I am getting the same issue, could u please suggest any solution. I didn't get any proper solutions
