### ISSUE TITLE
Custom `prepare` action to build standalone binaries with `pkg`

### ISSUE THREAD

**Issue by adrukh** [semantic-release/semantic-release#897]
## New plugin motivation

We are very happy users of `semantic-release` across all our internal and public codebases. Thank you so much for this valuable project 🙇 

We have a specific use-case with our [CLI tool](https://github.com/snyk/snyk), where we package the released version using [`pkg`](https://www.npmjs.com/package/pkg) to build standalone binaries of our CLI, and publish them on the GitHub release page [like this](https://github.com/snyk/snyk/releases/latest). Right now the process is manual, and we want to automate it with `semantic-release`. The asset uploading documentation is quite clear, but we're having a difficulty with one aspect - the timing of the `prepare` stage of the `npm` plugin. I'll explain:

A naive approach would be as follows:
1. Upon release, first run `npx pkg .` to generate the binary assets.
2. Run `npx semantic-release` to follow the release steps, including publishing of the built assets.

The problem here lies in the fact that the binary assets contain a version-less `package.json` file. A user of our binary CLI will not know which version they are using, making support needlessly difficult.

A solution we are considering to overcome this problem is to introduce a custom plugin for the `prepare` stage that will run after the `npm` plugin (which injects the new version value into `package.json`). This custom plugin will basically run `npx pkg .` and create the binary assets, with the proper version  embedded in them. Then the `publish` plugins will publish the release and handle the assets as expected.

We're seeking comments on this approach, and perhaps a pointer to something that already does what we need 🤞 

## Third-party documentation

https://github.com/zeit/pkg#readme

**Comment by adrukh** [comment]
🤦‍♂️ 
could it be that all we need to do it https://github.com/semantic-release/exec#prepare ?

**Comment by pvdlg** [comment]
I think you have the right approach.

As to whether you should create a plugin or use [@semantic-release/exec](https://github.com/semantic-release/exec) here a few general rules I would suggest. Create a plugin if one of those situation applies:
- You need to run something more complex than a few shell command (e.g. you need custom logic, conditional execution, parse options, specific error handling, etc...)
- You need to provide multiple plugin steps that share some code
- You want to make your plugin available to other (note that you could also provide a [shareable configuration](https://semantic-release.gitbook.io/semantic-release/usage/shareable-configurations) that uses [@semantic-release/exec](https://github.com/semantic-release/exec))

**Comment by adrukh** [comment]
Thanks @pvdlg , we seem to have this going for us with two additions:
* https://github.com/snyk/snyk/blob/master/.releaserc#L4-L7
* https://github.com/snyk/snyk/blob/master/.travis.yml#L30

Leaving this here in hopes it'll help someone else!

**Comment by pvdlg** [comment]
Thanks for the feedback.
Can this issue be closed then?

**Comment by pvdlg** [comment]
Closing as it seems you implemented the solution discussed

**Comment by adrukh** [comment]
Thanks @pvdlg !

This is the commit that made it work for us - https://github.com/snyk/snyk/commit/2eeab79eccc7fe8bb14948538f0697a441938433

Could not have `semantic-release` as a devDependency of the project due to our internal constraints (cannot have `npm` as a dependency), so had to overcome with `npm i -g`.
