### ISSUE TITLE
git-credentials are bugging with semantic-release.

### ISSUE THREAD

**Issue by kopax** [semantic-release/semantic-release#941]
I am using **git 2.19.0** and I have my CI job failing to push.

I expect to authenticate using [git-credentials](https://git-scm.com/docs/git-credential-store#git-credential-store-XDGCONFIGHOMEgitcredentials) store.

This is what I have in `.git/config`:

    [fetch]
    	recurseSubmodules = false
    [core]
    	repositoryformatversion = 0
    	filemode = true
    	bare = false
    	logallrefupdates = true
    [remote "origin"]
    	url = https://git.example.com/some-org/some-project.git
    	fetch = +refs/heads/*:refs/remotes/origin/*
    [branch "master"]
    	remote = origin
    	merge = refs/heads/master

This is what I have in `$HOME/.config/git/credentials`:
    
    $ cat $HOME/.config/git/credentials
    https://gitlab-ci-token:Dwq456WQd4q56QW@git.example.com/

However, when I do `git push`, it fails to use that configuration, instead it read the one from `.git/config` within the project.

Doing `cp $HOME/.config/git/credentials ~/.git-credentials` did not help.

Why would a [$HOME/.config/git/credentials](https://git-scm.com/docs/git-credential-store#git-credential-store-XDGCONFIGHOMEgitcredentials) would be ignored when I do `git push`?

Why is `git-credential-store erase` called? I cannot find anything about it in git documentation.

## Environment

- **semantic-release** version: 

```
    "semantic-release": "^15.9.1",
```
- CI environment: Gitlab-CI
- Plugins used: 
```
    "@semantic-release/changelog": "^3.0.0",
    "@semantic-release/exec": "^3.1.3",
    "@semantic-release/git": "^7.0.4",
    "@semantic-release/gitlab": "^3.0.4",
    "@semantic-release/npm": "^5.0.4",
```

- **semantic-release** configuration: 
- CI logs: 

    [0KRunning with gitlab-runner 10.0.2 (a9a76a50)
      on example_developers_gitlab_git-gitlab-runner-docker.b333e7a2-bc0d-11e8-b8f7-427f0c81db23 (cb1d7a32)
    [0;m[0KUsing Docker executor with image example/node10-jdk8-flyway4-sonarscanner2-docker17-debian ...
    [0;m[0KStarting service docker:dind ...
    [0;m[0KPulling docker image docker:dind ...
    [0;m[0KUsing docker image docker:dind ID=sha256:943cc2194c118472a134b2fee0bb7144c1c62ca415ff030d0cc00d43b81e29f7 for docker service...
    [0;m[0KWaiting for services to be up and running...
    [0;mRunning on runner-cb1d7a32-project-112-concurrent-0 via master-rbx-01...
    [32;1mFetching changes...[0;m
    Removing node_modules/
    HEAD is now at 493c40e Merge branch 'dev' into 'master'
    [32;1mChecking out 493c40ed as master...[0;m
    [32;1mSkipping Git submodules setup[0;m
    [32;1mDownloading artifacts for build (7322)...[0;m
    Downloading artifacts from coordinator... ok      [0;m  id[0;m=7322 responseStatus[0;m=200 OK token[0;m=7B69jgbC
    [0;33mWARNING: Part of .git directory is on the list of files to extract[0;m 
    [0;33mWARNING: This may introduce unexpected problems   [0;m 
    [32;1m$ npx rollup-umd-ci-before-script[0;m
    npx: installed 53 in 7.647s
    npx: installed 50 in 4.791s
    npm info it worked if it ends with ok
    npm info using npm@6.4.1
    npm info using node@v10.3.0
    npm timing npm Completed in 65ms
    npm info ok 
    Login Succeeded
    umd detected
    6.4.1
    v10.3.0
    [32;1m$ PACKAGE_VERSION=$(node -p 'require("./package.json").version')[0;m
    [32;1m$ export GIT_TRACE=1[0;m
    [32;1m$ cat .git/config[0;m
    [fetch]
    	recurseSubmodules = false
    [core]
    	repositoryformatversion = 0
    	filemode = true
    	bare = false
    	logallrefupdates = true
    [remote "origin"]
    	url = https://git.example.com/example/some-project.git
    	fetch = +refs/heads/*:refs/remotes/origin/*
    [branch "master"]
    	remote = origin
    	merge = refs/heads/master
    [credential]
    [32;1m$ cat $HOME/.config/git/credentials[0;m
    https://gitlab-ci-token:12345678910@git.example.com
    [32;1m$ git config --list[0;m
    18:25:22.740279 git.c:415               trace: built-in: git config --list
    user.email=dev@example.com
    user.name=Gitlab-CI
    push.default=matching
    credential.helper=store
    fetch.recursesubmodules=false
    core.repositoryformatversion=0
    core.filemode=true
    core.bare=false
    core.logallrefupdates=true
    remote.origin.url=https://git.example.com/example/some-project.git
    remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
    branch.master.remote=origin
    branch.master.merge=refs/heads/master
    [32;1m$ git fetch --tags https://git.example.com/example/some-project.git[0;m
    18:25:40.173737 git.c:349               trace: built-in: git 'fetch' '--tags' 'https://git.example.com/example/some-project.git'
    18:25:40.173772 run-command.c:341       trace: run_command: 'git-remote-http' 'https://git.example.com/example/some-project.git' 'https://git.example.com/example/some-project.git'
    18:25:40.173744 run-command.c:341       trace: run_command: 'git credential-store get'
    18:25:40.173778 run-command.c:192       trace: exec: '/bin/sh' '-c' 'git credential-store get' 'git credential-store get'
    18:25:40.173706 git.c:555               trace: exec: 'git-credential-store' 'get'
    18:25:40.173763 run-command.c:341       trace: run_command: 'git-credential-store' 'get'
    18:25:40.173745 run-command.c:341       trace: run_command: 'git credential-store store'
    18:25:40.173771 run-command.c:192       trace: exec: '/bin/sh' '-c' 'git credential-store store' 'git credential-store store'
    18:25:40.173797 git.c:555               trace: exec: 'git-credential-store' 'store'
    18:25:40.173761 run-command.c:341       trace: run_command: 'git-credential-store' 'store'
    18:25:40.173739 run-command.c:341       trace: run_command: 'git credential-store store'
    18:25:40.173719 run-command.c:192       trace: exec: '/bin/sh' '-c' 'git credential-store store' 'git credential-store store'
    18:25:40.173791 git.c:555               trace: exec: 'git-credential-store' 'store'
    18:25:40.173740 run-command.c:341       trace: run_command: 'git-credential-store' 'store'
    18:25:40.173797 run-command.c:341       trace: run_command: 'rev-list' '--objects' '--stdin' '--not' '--all' '--quiet'
    18:25:40.173738 run-command.c:341       trace: run_command: 'rev-list' '--objects' '--stdin' '--not' '--all'
    18:25:40.173716 exec_cmd.c:134          trace: exec: 'git' 'rev-list' '--objects' '--stdin' '--not' '--all'
    18:25:40.173758 git.c:349               trace: built-in: git 'rev-list' '--objects' '--stdin' '--not' '--all'
    From https://git.example.com/example/some-project.git
     * branch            HEAD       -> FETCH_HEAD
    [32;1m$ npx semantic-release --debug[0;m
    npx: installed 50 in 16.816s
    18:25:40.173757 git.c:415               trace: built-in: git config --global user.email dev@example.com
    18:25:40.192253 git.c:415               trace: built-in: git config --global user.name Gitlab-CI
    18:25:40.195393 git.c:415               trace: built-in: git config --global push.default matching
    npm info it worked if it ends with ok
    npm info using npm@6.4.1
    npm info using node@v10.3.0
    npm timing npm Completed in 71ms
    npm info ok 
    18:25:40.839457 git.c:415               trace: built-in: git config --global credential.helper store
    [6:25:41 PM] [semantic-release] › ℹ  Running semantic-release version 15.9.16
    [6:25:41 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/exec"
    [6:25:41 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/changelog"
    [6:25:41 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/npm"
    [6:25:41 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/git"
    [6:25:41 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/gitlab"
    [6:25:41 PM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
    [6:25:41 PM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
    [6:25:41 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/exec"
    [6:25:41 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/changelog"
    [6:25:41 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/npm"
    [6:25:41 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/git"
    [6:25:41 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/npm"
    [6:25:41 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/gitlab"
    [6:25:41 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/exec"
    [6:25:41 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/exec"
    [6:25:41 PM] [semantic-release] › ✔  Run automated release from branch master
    [6:25:42 PM] [semantic-release] › ✔  Allowed to push to the Git repository
    [6:25:42 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/exec"
    [6:25:42 PM] [semantic-release] [@semantic-release/exec] › ℹ  Call script npx rollup-umd-ci-release-transitive verify
    npx: installed 50 in 8.061s
    18:25:51.083931 git.c:415               trace: built-in: git config --global user.email dev@example.com
    18:25:51.103079 git.c:415               trace: built-in: git config --global user.name Gitlab-CI
    18:25:51.106197 git.c:415               trace: built-in: git config --global push.default matching
    Done verifying
    [6:25:52 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/exec"
    [6:25:52 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/changelog"
    [6:25:52 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/changelog"
    [6:25:52 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/npm"
    [6:25:52 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/npm"
    [6:25:52 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/git"
    [6:25:52 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/git"
    [6:25:52 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/gitlab"
    2018-10-02T18:25:52.342Z semantic-release:gitlab repoId: 'example/some-project'
    2018-10-02T18:25:52.343Z semantic-release:gitlab apiUrl: 'https://git.example.com/api/v4'
    [6:25:52 PM] [semantic-release] [@semantic-release/gitlab] › ℹ  Verify GitLab authentication (https://git.example.com/api/v4)
    [6:25:52 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/gitlab"
    [6:25:52 PM] [semantic-release] › ✖  An error occurred while running semantic-release: { Error: Command failed: git fetch --tags https://git.example.com/example/some-project.git
    18:25:52.554903 git.c:415               trace: built-in: git fetch --tags https://git.example.com/example/some-project.git
    18:25:52.555234 run-command.c:637       trace: run_command: GIT_DIR=.git git-remote-https https://git.example.com/example/some-project.git https://git.example.com/example/some-project.git
    18:25:52.692741 run-command.c:637       trace: run_command: 'git credential-store get'
    18:25:52.697314 git.c:659               trace: exec: git-credential-store get
    18:25:52.697372 run-command.c:637       trace: run_command: git-credential-store get
    18:25:52.936024 run-command.c:637       trace: run_command: 'git credential-store erase'
    18:25:52.940307 git.c:659               trace: exec: git-credential-store erase
    18:25:52.940365 run-command.c:637       trace: run_command: git-credential-store erase
    remote: HTTP Basic: Access denied
    fatal: Authentication failed for 'https://git.example.com/example/some-project.git/'
    
    
        at makeError (/mnt/mesos/sandbox/builds/example/some-project/node_modules/semantic-release/node_modules/execa/index.js:174:9)
        at Promise.all.then.arr (/mnt/mesos/sandbox/builds/example/some-project/node_modules/semantic-release/node_modules/execa/index.js:278:16)
        at process._tickCallback (internal/process/next_tick.js:68:7)
      code: 128,
      stdout: '',
      stderr:
       '18:25:52.554903 git.c:415               trace: built-in: git fetch --tags https://git.example.com/example/some-project.git\n18:25:52.555234 run-command.c:637       trace: run_command: GIT_DIR=.git git-remote-https https://git.example.com/example/some-project.git https://git.example.com/example/some-project.git\n18:25:52.692741 run-command.c:637       trace: run_command: \'git credential-store get\'\n18:25:52.697314 git.c:659               trace: exec: git-credential-store get\n18:25:52.697372 run-command.c:637       trace: run_command: git-credential-store get\n18:25:52.936024 run-command.c:637       trace: run_command: \'git credential-store erase\'\n18:25:52.940307 git.c:659               trace: exec: git-credential-store erase\n18:25:52.940365 run-command.c:637       trace: run_command: git-credential-store erase\nremote: HTTP Basic: Access denied\nfatal: Authentication failed for \'https://git.example.com/example/some-project.git/\'\n',
      failed: true,
      signal: null,
      cmd:
       'git fetch --tags https://git.example.com/example/some-project.git',
      timedOut: false,
      killed: false }
    { Error: Command failed: git fetch --tags https://git.example.com/example/some-project.git
    18:25:52.554903 git.c:415               trace: built-in: git fetch --tags https://git.example.com/example/some-project.git
    18:25:52.555234 run-command.c:637       trace: run_command: GIT_DIR=.git git-remote-https https://git.example.com/example/some-project.git https://git.example.com/example/some-project.git
    18:25:52.692741 run-command.c:637       trace: run_command: 'git credential-store get'
    18:25:52.697314 git.c:659               trace: exec: git-credential-store get
    18:25:52.697372 run-command.c:637       trace: run_command: git-credential-store get
    18:25:52.936024 run-command.c:637       trace: run_command: 'git credential-store erase'
    18:25:52.940307 git.c:659               trace: exec: git-credential-store erase
    18:25:52.940365 run-command.c:637       trace: run_command: git-credential-store erase
    remote: HTTP Basic: Access denied
    fatal: Authentication failed for 'https://git.example.com/example/some-project.git/'
    
    
        at makeError (/mnt/mesos/sandbox/builds/example/some-project/node_modules/semantic-release/node_modules/execa/index.js:174:9)
        at Promise.all.then.arr (/mnt/mesos/sandbox/builds/example/some-project/node_modules/semantic-release/node_modules/execa/index.js:278:16)
        at process._tickCallback (internal/process/next_tick.js:68:7)
      code: [33m128[39m,
      stdout: [32m''[39m,
      stderr:
       [32m'18:25:52.554903 git.c:415               trace: built-in: git fetch --tags https://git.example.com/example/some-project.git\n18:25:52.555234 run-command.c:637       trace: run_command: GIT_DIR=.git git-remote-https https://git.example.com/example/some-project.git https://git.example.com/example/some-project.git\n18:25:52.692741 run-command.c:637       trace: run_command: \'git credential-store get\'\n18:25:52.697314 git.c:659               trace: exec: git-credential-store get\n18:25:52.697372 run-command.c:637       trace: run_command: git-credential-store get\n18:25:52.936024 run-command.c:637       trace: run_command: \'git credential-store erase\'\n18:25:52.940307 git.c:659               trace: exec: git-credential-store erase\n18:25:52.940365 run-command.c:637       trace: run_command: git-credential-store erase\nremote: HTTP Basic: Access denied\nfatal: Authentication failed for \'https://git.example.com/example/some-project.git/\'\n'[39m,
      failed: [33mtrue[39m,
      signal: [1mnull[22m,
      cmd:
       [32m'git fetch --tags https://git.example.com/example/some-project.git'[39m,
      timedOut: [33mfalse[39m,
      killed: [33mfalse[39m }ps process exited with code 1
    [31;1mERROR: Job failed: exit code 1

1. You can notice that I have called the `git fetch --tags ${url}` before calling semantic-release and the git credentials are used correctly.
2. `notice the following done by git`:

```
    18:25:52.692741 run-command.c:637       trace: run_command: 'git credential-store get'
    18:25:52.697314 git.c:659               trace: exec: git-credential-store get
    18:25:52.697372 run-command.c:637       trace: run_command: git-credential-store get
    18:25:52.936024 run-command.c:637       trace: run_command: 'git credential-store erase'
    18:25:52.940307 git.c:659               trace: exec: git-credential-store erase
    18:25:52.940365 run-command.c:637       trace: run_command: git-credential-store erase
```

I have mailed the git list about that topic, not sure if it is related to semantic-release directly or git (semantic-release is manipulating the enviroment with some env like `GIT_CREDENTIALS`.)

Tested with git v2.11 and v2.19

**Comment by pvdlg** [comment]
`GIT_CREDENTIALS` is a semantic-release specific environment variable, Git itself doesn't do anything.

The only other variable we set are `GIT_AUTHOR_NAME`, `GIT_AUTHOR_EMAIL`, `GIT_COMMITTER_NAME`, `GIT_COMMITTER_EMAIL`, `GIT_ASKPASS` and `GIT_TERMINAL_PROMPT`.

`GIT_ASKPASS` and `GIT_TERMINAL_PROMPT` are set to prevent the `git` command to prompt the user. As it runs on a CI it would block the build.

Using ` $HOME/.config/git/credentials` is not something we have tested and is not mentioned in our doc. It present an important security as you would have a file on the CI containing your credential. Anyone can open a PR with code reading and printing the content of that file. The PR would trigger the job and your credential are compromised.

So I don't know if the problem you are reporting is specifically related to semantic-release or not, but in any case I don't see much reasons for us to investigate and potentially make changes to support an unsecure workflow.

The only recommended approach for authentication are the `GIT_CREDENTIALS` environment variable and ssh keys.

**Comment by kopax** [comment]
@pvldg thanks for the explanation. I thought that because git cli was used, then we could use any git authentication flow. 

I was and I am still confused with `GL_TOKEN`, if the recommended approach is `GIT_CREDENTIALS`.

I use to run semantic release with `GL_TOKEN=$token npx semantic-release`.

**Comment by pvdlg** [comment]
> I thought that because git cli was used, then we could use any git authentication flow.

Theoretically yes. In the sense that we don't do anything on purpose to prevent any authentication type. Now if a specific authentication type that provide value doesn't we will try to support it. In the present case, I'm not sure that authenticating with `$HOME/.config/git/credentials` present much value as it comes with a big security flow when running on a CI.

> I was and I am still confused with GL_TOKEN, if the recommended approach is GIT_CREDENTIALS.

`GIT_CREDENTIALS`, `GL_TOKEN`, `BB_TOKEN` and `GH_TOKEN` are effectively the same when it comes to the authentication for the `git` CLI. When I was referring to `GIT_CREDENTIALS` I was implying `GIT_CREDENTIALS` or `GL_TOKEN` or `BB_TOKEN` or `GH_TOKEN`.
`GL_TOKEN` will be used for `git` CLI auth and GitLab API auth, `same for `GH_TOKEN`. `GIT_CREDENTIALS` will be used only for `git` CLI auth. There is also some minor differences in the way the authenticated URL is built based on the platform (e.g. for GitLab the format is `https://gitlab-ci-token:<GL_TOKEN>@gitlab.com/owner/repo.git`).

> I used to run semantic release with GL_TOKEN=$token npx semantic-release and having git-credentials configured at the same time without hassle.

That's because semantic-release use `GL_TOKEN` for `git` CLI authentication in that case. What you set in `git-credentials` is probably just ignored.

**Comment by kopax** [comment]
Thanks a lot, it appear that semantic-release does not work with git-credentials so I am closing this.
