### ISSUE TITLE
EGITNOPERMISSION The push permission to the Git repository is required.

### ISSUE THREAD

**Issue by oleg-koval** [semantic-release/semantic-release#943]
## Current behavior

After successful setup and use of semantic-release with travis-deploy-once, it started to fail on ci during the release phase.

Setup was done with `semantic-release-cli setup`

Results of debug `semantic-release --no-ci --debug`:

```
> koa-verto@0.0.0-development semantic-release /Users/olegkoval/proj/koa-verto
> semantic-release

[12:05:30] [semantic-release] › ℹ  Running semantic-release version 15.9.17
[12:05:30] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/npm"
[12:05:31] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/github"
[12:05:31] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[12:05:31] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[12:05:31] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/npm"
[12:05:31] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/npm"
[12:05:31] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/github"
[12:05:31] [semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/github"
[12:05:31] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/github"
[12:05:31] [semantic-release] › ℹ  This run was not triggered in a known CI environment, running in dry-run mode.
[12:05:31] [semantic-release] › ✔  Run automated release from branch master
Username for 'https://github.com': oleg-koval
Password for 'https://oleg-koval@github.com':
Username for 'https://github.com': oleg-koval
Password for 'https://oleg-koval@github.com':
[12:05:53] [semantic-release] › ✖  The command "git push --dry-run https://github.com/oleg-koval/koa-verto.git HEAD:master" failed with the error message remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/oleg-koval/koa-verto.git/'
.
[12:05:53] [semantic-release] › ✖  EGITNOPERMISSION The push permission to the Git repository is required.
semantic-release cannot push the version tag to the branch master on remote Git repository with URL https://github.com/oleg-koval/koa-verto.git.

Please refer to the authentication configuration documentation (https://github.com/semantic-release/semantic-release/blob/caribou/docs/usage/ci-configuration.md#authentication) to configure the Git credentials on your CI environment and make sure the repositoryUrl (https://github.com/semantic-release/semantic-release/blob/caribou/docs/usage/configuration.md#repositoryurl) is configured with a valid Git URL (https://git-scm.com/book/en/v2/Git-on-the-Server-The-Protocols).

{ SemanticReleaseError: The push permission to the Git repository is required.
    at module.exports (/Users/olegkoval/proj/koa-verto/node_modules/semantic-release/lib/get-error.js:6:10)
    at run (/Users/olegkoval/proj/koa-verto/node_modules/semantic-release/index.js:71:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  name: 'SemanticReleaseError',
  code: 'EGITNOPERMISSION',
  details: '**semantic-release** cannot push the version tag to the branch `master` on remote Git repository with URL `https://github.com/oleg-koval/koa-verto.git`.\n\nPlease refer to the [authentication configuration documentation](https://github.com/semantic-release/semantic-release/blob/caribou/docs/usage/ci-configuration.md#authentication) to configure the Git credentials on your CI environment and make sure the [repositoryUrl](https://github.com/semantic-release/semantic-release/blob/caribou/docs/usage/configuration.md#repositoryurl) is configured with a [valid Git URL](https://git-scm.com/book/en/v2/Git-on-the-Server-The-Protocols).',
  semanticRelease: true }npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! koa-verto@0.0.0-development semantic-release: `semantic-release`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the koa-verto@0.0.0-development semantic-release script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /.npm/_logs/2018-10-04T10_05_53_197Z-debug.log
```

Also, not clear why login/password is asked twice:

```
Username for 'https://github.com': oleg-koval
Password for 'https://oleg-koval@github.com':
Username for 'https://github.com': oleg-koval
Password for 'https://oleg-koval@github.com':

```

## Expected behavior

As tokens were generated, the release stage should not throw `EGITNOPERMISSION The push permission to the Git repository is required.` error

## Environment

- **semantic-release** version: `"^15.9.17"`
- CI environment: Travis CI
- Plugins used: 
- **semantic-release** configuration: 
```json
"repository": {
    "type": "git",
    "url": "https://github.com/oleg-koval/koa-verto.git"
  },
```
- CI logs: https://travis-ci.com/oleg-koval/koa-verto/jobs/149680141

**Comment by pvdlg** [comment]
See the log message:
> The command "git push --dry-run https://github.com/oleg-koval/koa-verto.git HEAD:master" failed with the error message remote: Invalid username or password.

Also the CI logs link you provided doesn't contain the same logs you included in the issue. The logs on the CI says:
> Error: GitHub authentication missing

See https://travis-ci.com/oleg-koval/koa-verto/jobs/149680141#L2878

So I think the problem is you didn't configure the authentication on your CI. Please see the doc: https://github.com/semantic-release/semantic-release/blob/caribou/docs/usage/ci-configuration.md#authentication

**Comment by oleg-koval** [comment]
@pvdlg 
That's actually is strange, as I did configuration with CLI tool, as the output of this I had a couple of versions released with the semantic-release, but that's was done with an older version of semantic-release.

Will keep debugging, but don't know in which way, as I said I have all tokens setup

**Comment by pvdlg** [comment]
I don't think your GitHub token is set. See https://github.com/semantic-release/travis-deploy-once/blob/master/lib/validate.js#L12

And you have this error in your CI logs https://travis-ci.com/oleg-koval/koa-verto/jobs/149680141#L2878

**Comment by pvdlg** [comment]
Also now that Travis Build Stage are out of beta it's recommended to use them instead of `travis-deploy-once`. See https://github.com/semantic-release/semantic-release/blob/caribou/docs/recipes/travis-build-stages.md

**Comment by pvdlg** [comment]
Please make sure the `GH_TOKEN` environment variable is set properly in Travis and let us know if that solve the issue. If not please provide the Travis log with after the variable is set.

**Comment by oleg-koval** [comment]
@pvdlg All good now, the problem was that I was looking into the travis-pro page for my repo and travis-org, so sem-release was working on travis-org, but it was never set up for travis-pro. A bit of confusion will close this, 

thanks for learnings
