### ISSUE TITLE
travis ci not working

### ISSUE THREAD

**Issue by titanve** [semantic-release/semantic-release#945]
## Current behavior

when my travis.yml runs `yarn semantic-release`which is: `semantic-release pre && npm publish && semantic-release post` it says that it needs more params and doesn't publis to npm registry

## Environment

- **semantic-release** version: "semantic-release": "^15.9.17"
- CI environment: Travis CI
- Plugins used: 
- **semantic-release** configuration: .travis.yml: 
after_success:
  - yarn run semantic-release
- CI logs:

**Comment by pvdlg** [comment]
The form `semantic-release pre && npm publish && semantic-release post` is not supported for more than a year. 
Please read the documentation: https://github.com/semantic-release/semantic-release/blob/caribou/docs/usage/README.md
