### ISSUE TITLE
Unable to publish code from local PC to Gitlab

### ISSUE THREAD

**Issue by konsalex** [semantic-release/semantic-release#946]
## Current behavior

Hello there 👋, I am setting up Semantic Release with a private Gitlab repo and also I don't want to publish to NPM.
I have configured my package.json like this 
```
"release": {
    "branch": "staging",
    "dryRun": true,
    "ci": false,
    "debug": true,
    "verifyConditions": "@semantic-release/gitlab",
    "publish": "@semantic-release/gitlab",
    "success": false,
    "fail": false
  }
```
.
Now all I want is to push a new tag every time we push into the staging branch but I cannot figure out how to do this. 

The output that I get is the following and the commits are stacked together
```
[8:10:51 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analysis of 744 commits complete: minor release
[8:10:51 PM] [semantic-release] › ✔  Completed step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[8:10:51 PM] [semantic-release] › ℹ  There is no previous release, the next release version is 1.0.0
[8:10:51 PM] [semantic-release] › ℹ  Start step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[8:10:51 PM] [semantic-release] › ✔  Completed step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[8:10:51 PM] [semantic-release] › ℹ  Release note for version 1.0.0:
# 1.0.0 (2018-10-08)

### Bug Fixes

    * $CI: Testing Semantic Releasing (608c8e2 (https://gitlab.com/Loceye/platform/commit/608c8e2))
    * $CI: Versioning test (9505ebc (https://gitlab.com/Loceye/platform/commit/9505ebc))

### Features

    * $CI: Testing again if  working with Semantic Release (35a7946 (https://gitlab.com/Loceye/platform/commit/35a7946))
    * Releasing: No progress yet and removed releaserc (cc195d2 (https://gitlab.com/Loceye/platform/commit/cc195d2))
    * Releasing: Trying to implement the release code (b8426dc (https://gitlab.com/Loceye/platform/commit/b8426dc))

### Performance Improvements

    * $CI: I am testing again the Semantic (f5e3b26 (https://gitlab.com/Loceye/platform/commit/f5e3b26))
```

## Environment

- **semantic-release** version: 3.0.4
- CI environment: None
- Plugins used: @semantic-release/gitlab
- **semantic-release** configuration: 
```
"release": {
    "branch": "staging",
    "dryRun": true,
    "ci": false,
    "debug": true,
    "verifyConditions": "@semantic-release/gitlab",
    "publish": "@semantic-release/gitlab",
    "success": false,
    "fail": false,
    "getLastRelease": "last-release-git"
  }
```

**Comment by pvdlg** [comment]
As mentioned [in README](https://github.com/semantic-release/semantic-release#commit-message-format), semantic-release parse your commit according to a commit convention to determine the type of release to make and the default one is Angular. However it seems your commits do not follow that convention.

It also seems that you do not have any version tagged in your `staging` branch so far, so semantic-release analyze all your commits (744 of them) and it seems that at least one is formatted according to the angular convention so a version 1.0.0 is released.

Finally you are running in dry-run mode. I'm guessing one the first line of logs which you didn't include in your issue report is `This run was not triggered in a known CI environment, running in dry-run mode.` This is explained in [the FAQ](https://github.com/semantic-release/semantic-release/blob/caribou/docs/support/FAQ.md#can-i-run-semantic-release-on-my-local-machine-rather-than-on-a-ci-server).

**Comment by konsalex** [comment]
Thank you very much @pvdlg for your blazing fast support. The dry-run and the no-ci flag was indeed my mistake! 🙃
