### ISSUE TITLE
Semver in README

### ISSUE THREAD

**Issue by dferber90** [semantic-release/semantic-release#95]
According to @boennemann's [talk](https://speakerdeck.com/boennemann/we-fail-to-follow-semver-and-why-it-neednt-matter-1?slide=15), the suggested names instead of MAJOR.MINOR.PATCH are BREAKING.FEATURE.PATCH. The README however replaces MINOR with FIX in the headline. Is this a mistake or am I missing something?

https://github.com/semantic-release/semantic-release#minor-fix-release

**Comment by boennemann** [comment]
Yep, it's a mistake. Thanks for catching :)
