### ISSUE TITLE
Add ability to handle read-only repositories

### ISSUE THREAD

**Issue by ryaninvents** [semantic-release/semantic-release#957]
## New feature motivation

I'm working on implementing `semantic-release` for internal projects. Unfortunately, our Jenkins server has restrictions applied; credentials are only available during the initial code checkout. By the time `semantic-release` is run, the credentials have already been removed, so it cannot authenticate to Bitbucket. **This means the repo is effectively read-only** from the CI server's point of view.

<details>
<summary>Snippet of CI output</summary>
<pre><code>[15:59:37] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/npm"
[15:59:38] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[15:59:38] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[15:59:38] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/npm"
[15:59:38] [semantic-release] › ✔  Run automated release from branch develop
2018-10-17T19:59:38.578Z semantic-release:git Error: Command failed: git push --dry-run https://bitbucket.org/example-org/my-repo.git HEAD:develop
remote: Invalid username or password
fatal: Authentication failed for 'https://bitbucket.org/example-org/my-repo.git/'
(...truncated output...)
[15:59:39] [semantic-release] › ℹ  The local branch develop is behind the remote one, therefore a new version won't be published.</code></pre>
</details>

Since the repository is read-only during a CI run, a tag cannot be pushed for the freshly released version. I wrote a small tool that looks at the `gitHead` property of the `package.json` for the currently released version, and creates the git tag locally. This allows `semantic-release` to correctly determine changes since last publish. However, the build still fails because the `git push` for the tag is part of `semantic-release` core and not a plugin.

I have spent considerable time trying to find a workaround that does not require a PR into this project, but there exists no such workaround.

## New feature description

I propose adding an option to permit use of `semantic-release` in a read-only environment such as this. This could be a CLI flag (e.g. `--readonly-repo`), but could also be enabled via another mechanism if deemed appropriate (perhaps the community would prefer an env var if this feature is obscure).

## New feature implementation

I would be happy to implement this myself since it's blocking my team from using `semantic-release`.

1. Add a new CLI flag such as `--readonly-repo` or `--skip-tag-push`.
2. If the readonly flag is supplied:
    - Skip [the `verifyAuth` check](https://github.com/semantic-release/semantic-release/blob/cfc10039f37c9401810b5b0d168727358f41aec6/index.js#L61-L80)
    - Skip [pushing the tag back to the original branch](https://github.com/semantic-release/semantic-release/blob/cfc10039f37c9401810b5b0d168727358f41aec6/index.js#L113)

**Comment by pvdlg** [comment]
semantic-release used to allow to retrieve the last release commit via a plugin, and the npm plugin used to implement the tag retrieval by reading the `gitHead` property from the `package.json` published on npm. However we moved away from that mechanism for several reason:
- There is many cases where the `gitHead` was not present in the `package.json` on the registry
- It creates additional complexity
- If you don't use npm, or choose to not publish your package to the registry then you can't get the commit corresponding to the last release

For all those reasons we moved to a solution where we retrieve the last release from Git tags. Which means we have to push a tag during a release so we can read it in the next run.

In addition the feature #563 uses tags to figure out what version was published on various distribution channel. For example it allows us to determine if a given version was published on `@next` but not on `@latest`. If the `master` branch contains the tag `v2.0.0@next` but not the tag `v2.0.0` we know that `2.0.0` was published on `@next` and the corresponding commits were merged to `master` so we can add the release `2.0.0` to the `@latest` branch and create the tag `v2.0.0`.

So in the end it's a trade off. Using tags prevent to use semantic-release in cases where you don't have write access to the remote repo, but it makes thing more simple, allow to support more workflow (i.e. it doesn't require to publish to npm registry) and it allow to support multiple branches and distribution channels.
Considering that situation where you don't have write access to your repo are fairly uncommon we chose the solution that allow us to implement an often request feature and to support workflow that doesn't publish to the npm registry.

Regarding the problem you are facing. If the Git credentials (I'm guessing the `BITBUCKET_TOKEN` environment variable) is not available on your CI when running  semantic-release, that probably means `NPM_TOKEN` will not be available either so you won't be able to publish on the registry and retrieve the `gitHead` later.

Maybe using ssh keys for authentication would solve your problem: https://github.com/semantic-release/semantic-release/blob/caribou/docs/recipes/git-auth-ssh-keys.md. You would still need to make `NPM_TOKEN` available to semantic-release though.

**Comment by ryaninvents** [comment]
Thanks for the feedback! I figured it was a niche problem, and don't want to add complexity for such a rare edge case. I'll close this issue, since this seems like it would be better solved on my end.

Let me know if there's anything else I can help with towards #563 as well.

**Comment by pvdlg** [comment]
Just out of curiosity, why are the credential removed?
Can you confirmed that the `NPM_TOKEN` is also removed? If yes how would you publish to npm from the CI?
