### ISSUE TITLE
Return release notes on nextRelease even if running on dry mode

### ISSUE THREAD

**Issue by tsirlucas** [semantic-release/semantic-release#959]
## New feature motivation

Basically I need to get the release notes on the javascript API even if I'm running in dry mode. I'm working on a probot that checks the future release that a PR will generate and comment the changelog on the PR. For that, I need to run semantic release in dry mode (I don't want to release anything yet) and get the release notes from the next release to create the comment. 

## New feature description

It'll run the release notes plugin even if in dry mode and will return the notes on the nextRelease variable.

## New feature implementation

Basically this:
```js
  context.nextRelease = nextRelease;
  nextRelease.version = getNextVersion(context);
  nextRelease.gitTag = template(options.tagFormat)({ version: nextRelease.version });

  await plugins.verifyRelease(context);

  if (options.dryRun) {
    const notes = await plugins.generateNotes(context);
    logger.log(`Release note for version ${nextRelease.version}:`);
    if (notes) {
      context.stdout.write(marked(notes));
    }
  } else {
    nextRelease.notes = await plugins.generateNotes(context);
    await plugins.prepare(context);

```

becomes this:

```js
  context.nextRelease = nextRelease;
  nextRelease.version = getNextVersion(context);
  nextRelease.gitTag = template(options.tagFormat)({ version: nextRelease.version });
  nextRelease.notes = await plugins.generateNotes(context);

  await plugins.verifyRelease(context);

  if (options.dryRun) {
    logger.log(`Release note for version ${nextRelease.version}:`);
    if (nextRelease.notes) {
      context.stdout.write(marked(nextRelease.notes));
    }
  } else {
    await plugins.prepare(context);

```

I'll open a PR and point to this issue, please let me know if there is any kind of technical limitation against this implementation

**Comment by pvdlg** [comment]
Returning the release notes in the JS API makes sense, so I'll merge the PR!
However what you try to implement is not gonna work. See #585 for the details.

To summarize:
- semantic-release is currently coded to not run on PRs
- semantic-release requires access to a local repo clone which you won't have in a GitHub app
- secured environment variables (like `NPM_TOKEN`) will not be available in the GitHub app so many `verifyConditions` will fail

As you can see in #585 we plan to support commenting on PRs, but it's really not simple and we need to find the right solution first.
