### ISSUE TITLE
listed users and repositories cannot be searched

### ISSUE THREAD

**Issue by zeke** [semantic-release/semantic-release#962]
I just set up semantic-release on https://github.com/colorjs/get-svg-colors/pull/9, but it failed:

```
An error occurred while running semantic-release: { HttpError: {"message":"Validation Failed","errors":[{"message":"The listed users and repositories cannot be searched either because the resources do not exist or you do not have permission to view them.","resource":"Search","field":"q","code":"invalid"}],"documentation_url":"https://developer.github.com/v3/search/"}
```

Here's the full build output:

https://travis-ci.org/colorjs/get-svg-colors/builds/444916955#L625

The configured GitHub user is @zeke, and I have push access to the repo..

**Comment by pvdlg** [comment]
That error happened when we call the GitHub API to search for issues associated with the release commits. My guess is that it's related to yesterday's outage.

**Comment by zeke** [comment]
Thanks for the reply @pvdlg. 👍 

Is there a way to "retry" a Travis build so it will re-trigger semantic-release, or is it necessary to create a new "fake" PR to try again?

**Comment by pvdlg** [comment]
Unfortunately no because the releases happened and worked properly. It's the final `success` step that failed and there is no simple way at the moment to re-run only that step.

**Comment by zeke** [comment]
Ok I will give it another go and report back.

**Comment by pvdlg** [comment]
Actually I think it's related to https://github.com/octokit/octokit.net/issues/1381

This is because your repository url in your `package.json` is configured to `github:zeke/get-svg-colors` but it should be `https://github.com/colorjs/get-svg-colors`.
I guess you migrated your repo to an organization and didn't update the `package.json`.

**Comment by zeke** [comment]
Ahhh. So that API call doesn't follow redirects?

**Comment by pvdlg** [comment]
Most of the API calls follow redirects, but not the search API. I think it's because the repo and owner are part of the `q` parameter and are not part of the URL itself like other endpoints.

**Comment by ivneetsinghwahi03** [comment]
Facing same issue when searching the PR with some labels 

$(curl -s  -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $GITHUB_TOKEN"  "https://api.github.com/search/issues?q=is:pr+is:open+label:some-label+repo:${ORG}/${PROJECT}")
