### ISSUE TITLE
Semantic release uses http instead of https

### ISSUE THREAD

**Issue by gerardabello** [semantic-release/semantic-release#965]
## Current behavior
Our deploy started failing, saying that the github authentication failed (see logs).

Semantic release is doing a push with `--dry-run` to check the auth using http even if the repository url is using https. It looks like github does not accept http and rejects the auth (the same command with the same token on the same machine works with https).

- Repository in package.json: 
```
  "repository": {
    "type": "git",
    "url": "git+https://github.com/Typeform/forms.git"
  },
``` 

There is a workaround. Passing the url to the cli like this: `yarn semantic-release --repository-url https://github.com/Typeform/forms.git` works as expected.

## Expected behavior

Semantic release should push to github using https if the repository url in package.json is using https.

## Environment

- **semantic-release** version: 15.9.16
- CI environment: travis
- Plugins used: github, npm
- CI logs(running `yarn semantic-release`): 
```
...
The command "git push --dry-run http://[secure]@github.com/Typeform/forms.git HEAD:master" failed with the error message remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/Typeform/forms.git/'
...
```

**Comment by pvdlg** [comment]
This is due to https://github.com/IonicaBizau/git-up/issues/17. It should be resolved when https://github.com/IonicaBizau/git-up/pull/19 get merged.
In the meantime, changing your repository URL to `https://github.com/Typeform/forms.git` (remove the `git+` part) should solve the problem.
