### ISSUE TITLE
Release a beta version

### ISSUE THREAD

**Issue by ericdouglas** [semantic-release/semantic-release#97]
Is possible to release a beta version with semantic-release?

**Comment by boennemann** [comment]
If by "beta" you mean sth. like `1.0.0-beta.1 the default `analyzeCommit` plugin doesn't support them out of the box. If you find some heuristics on whether to publish those you can implement this though: https://github.com/semantic-release/semantic-release#analyzecommits

Even though this possible with your own plugin I'd strongly discourage you from using "beta versions". semantic-release has support for release-channels (https://github.com/semantic-release/semantic-release#how-does-it-work 3rd paragraph) by adding `"publishConfig": {"tag": "next"}` to your package.json. This is way better mechanism to communicate stability.


Best,
Stephan

**Comment by ericdouglas** [comment]
Great, @boennemann ! Many thanks :smile:

**Comment by Apidcloud** [comment]
Is there any way to release on GitHub under the same dist-tag? as mentioned in https://github.com/kentcdodds/ama/issues/318

Thanks!

**Comment by gr2m** [comment]
`semantic-release` does not support that, it only creates tags with the versions released on npm. 

I don’t see the use case for it. Can you explain why you’d want that? Would that be in addition to the version tags like `v1.2.3`, or as a substitute?

**Comment by Apidcloud** [comment]
At least as a substitute just like it happens over npm. Despite using a dist tag such as **beta**, GitHub keeps using a number as the version.

**Comment by gr2m** [comment]
yes that is intended behavior :) At the end, both npm & GitHub have releases with version numbers, but only npm gets the beta/next/custom tag, that is correct. Nobody asked for that to be added to GitHub yet. I wouldn’t be opposed adding it though. You’d also need to reset it if it already exists. Pull requests welcome 👍
