### ISSUE TITLE
Make "semantic-release ERR! pre Not publishing from tags" more clear

### ISSUE THREAD

**Issue by gr2m** [semantic-release/semantic-release#98]
we are working with both git & npm tags, and the team was confused of what this was referring to, so I'd suggest to change `Not publishing from tags` to `Not publishing from Git tags`, and maybe add a short URL to a README/FAQ section on it?

**Comment by gr2m** [comment]
Related question: can't we disable Travis builds on tags somehow?

**Comment by juristr** [comment]
@gr2m Maybe you're able to do with the `branches` property of the `.travis.yml` file:

```
...
branches:
  only:
    - master
...
```
This way it only builds `master` and nothing else. I did not yet check whether this also prevents from building tags, but I guess so.

**Comment by gr2m** [comment]
I've worked around it by setting

```yml
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
```

But it would be still nice to make the error message more descriptive

**Comment by boennemann** [comment]
I just published a new version of the condition-travis plugin that is responsible for these error messages: https://github.com/semantic-release/condition-travis/commit/be5386e3

I think this should make things much clearer, but I'm happy to get some feedback/contributions so we can make them even better.

Best,
Stephan
