### ISSUE TITLE
add arbitrary file to github release

### ISSUE THREAD

**Issue by cyberhck** [semantic-release/semantic-release#985]
## New feature motivation

So I'm trying to use semantic-release with golang, everything's fine when we use github, except, whenever new build is done, it does release, but with the source code.

Now if users have to build this on their PC, the release loses a lot of meaning.

I want to be able to pass a path to a binary with files (multiple) and they should be included in assets just below the source code.

## New feature description

I don't know if I'm even using the right template, this might have something to do with plugin. I think when we check for assets, we also check for config to see what files are supposed to be included, and include those files.

## New feature implementation

Not sure, I've no idea.

**Comment by travi** [comment]
would defining [assets](https://github.com/semantic-release/github#assets) within the github plugin config cover your need?

**Comment by cyberhck** [comment]
oh, wow, I should have went there before searching in semantic-release core repo, my bad, that's exactly what I'm looking for. Thanks.
