### ISSUE TITLE
[question] is the release process tied to npm?

### ISSUE THREAD

**Issue by SteveALee** [semantic-release/semantic-release#99]
This looks fantastic but appears to assume you are making npm package releases (also for testing?).

Is that true? Can we work around if only want github releases (say)?

**Comment by boennemann** [comment]
Hey @SteveALee,

this indeed coupled to npm very tightly, we were able to offer a `last-release` so this could potentially be solely based on git tags.

There is a work in progress implementation here: https://github.com/semantic-release/last-release-git-tag

Best,
Stephan

**Comment by SteveALee** [comment]
OK, thanks. I guess it's not masses of work making it a NPM package as well :)
